    #alternate

   / / Customer Service / Promotions / Blogs / Video / /

   Popular Mechanics
   ____________________ Search
   Try: Hottest Cars Ever / MINI Cooper / Best Gadgets Ever
   [sci-fi-everyone-01-0914-smn.jpg]
   The 30 Sci-Fi Stories Everyone Should Read Here on earth, there are
   consequences to testing ideas. Sometimes they turn out to be good.
   Sometimes they kill you. That's the thing...
   [dark-mail-0914-smn.jpg]
   Why We Should Encrypt Everyones Email Ladar Levison talks about his
   new project Dark Mail, online privacy, and how encrypting our email
   helps disassemble todays unconstitutional...
   [big-bertha-01-0914-smn.jpg]
   The Worlds Largest Tunnel-Boring Machine Must Be Saved Bertha has
   stalled deep beneath Seattle, leaving the citys planned waterfront
   renaissance hanging in...
   Automotive
     * Road Test
     * Auto News
     * DIY Auto
     * Motorcycles
     * Alternative Fuel
     * Tire Guide
     * Jay Leno's Garage
     * Saturday Mechanic YouTube Show

   Featured Stories
   [pmamelon-0614-smn.jpg]

   Musk Tweets Promise to Fix Model S
   [camaro-donuts-0814-smn.jpg]

   Moron Does Donuts on Golden Gate Bridge
   Technology
     * Gadgets
     * Aviation
     * Engineering
     * Military
     * Digital Hollywood
     * DIY Tech
     * Your DIY Tech Workshop

   Featured Stories
   [esq-01a-quote-de.jpg]

   The 50 Best Manly Movie Quotes
   [100-video-games-94-0614-smn.jpg]

   The 100 Greatest Video Games of All Time
   Science
     * Energy
     * Earth and the Environment
     * Space
     * Health
     * Mythbusters

   Featured Stories
   [ebolavaccine-0814-smn.jpg]

   We Don't Have Nearly Enough Ebola Drugs
   [frack-0814-smn.jpg]

   What Chemicals Are in Fracking Fluid?
   Home How-To
     * Projects & Plans
     * Home Improvement
     * Tools Reviews
     * Skills
     * Lawn and Garden

   Featured Stories
   [quick-lawn-tips-01-0814-smn.jpg]

   5 Quick Tips to Keep Your Lawn Looking Great
   [surprising-beer-uses-0814-smn.jpg]

   10 Things You Didnt Know You Could Do With Beer
   Outdoors

   Featured Stories
   [mini-golf-08-0814-smn.jpg]

   8 Mini-Golf Courses You Must Play Once
   [Flood-basement-1012-smn.jpg]

   What Not to Do With a Flooded Basement
     * Recreation
     * Sports
     * Survival
     * This is My Job

   DIY Central


   [tooltip-top.png] [tooltip-body.png] [tooltip-bottom.png]
   Homepage / New American Success Stories / 25 Makers Who Are Reinventing
   the American Dream

25 Makers Who Are Reinventing the American Dream

Now, as never before, DIYers are empowered to design, manufacture, and market
their creations. Call it the maker movement, a fresh industrial revolution,
or the new innovation economy. By any name, it's a great time to be an
innovator. And these visionaries are leading the way.

   By Chris Raymond
   Email
   Comments
   Share

   Local Motors Rally Fighhter
   March 18, 2014 6:30 AM Text Size: A . A . A
   « 5  of  5

21. Peter Weijmarshausen

   Shapeways
   Peter Weijmarshausen calls his Shapeways facilities factories of the
   future. The company provides online access to high-end 3D printersthe
   kind that can manufacture products using a variety of plastics, metals,
   ceramics, and sandstone. Customers can also buy and sell items on
   Shapeways' website. The marketplace features more than 1 million
   products, and 100,000 new designs are uploaded each month.

22. Matthew Burnett & Tanya Menendez

   Maker's Row
   (Video by Jane Nisselson / Virtual Beauty)
   By pairing entrepreneurs with domestic factories, Maker's Row is
   sparking a renaissance in U.S. manufacturing. As a watch and
   accessories designer, Burnett discovered that working with local
   partners gave him huge advantages in turnaround time and quality
   control. The downside: It often took months to find the right facility.
   Menendez, a former operations expert at Google and Goldman Sachs, saw
   that as an opportunity. Together they launched the company in 2012.
   Free advice: "Have courage," says Burnett. "Don't be afraid to try a
   new ideaand then start over if it doesn't work out."

23. Jay Rogers

   Local Motors
   This former Marine is shaking up the car world by enlisting an online
   community of enthusiasts for R&Dand recruiting customers to help build
   their own vehicles. His Rally Fighter is a street-legal off-road desert
   race car that was designed and built in an 18-month sprint. When DARPA
   challenged the company to construct a new combat-support vehicle, Local
   Motors finished the job in just four months.
   Résumé builder: Rogers earned a Harvard MBAand served in Iraq during a
   nine-year career in the military.

24. Danielle Applestone

   Other Machine Co.
   (Video by Jane Nisselson / Virtual Beauty)
   Danielle Applestone was using a DARPA grant to develop low-cost
   computer numerical control (CNC) machines for schools when the funding
   dried up. She didn't waver. Applestone simply took a CNC mill her
   engineering team had designed and launched a consumer products company.
   The Othermill, priced at just under $2000, can etch circuit boards and
   carve complex 3D shapes in metal, wood, and other materials. Best of
   all, it's small and quiet enough to sit on a kitchen table. Like
   desktop 3D-printer firms, Other Machine Co. is converting an industrial
   technology into a tool for everyone.

25. Scott Miller

   Dragon Innovation
   Miller once built a 6-ton walking triceratops for Disney. He created a
   doll with artificial intelligence for Hasbro. At iRobot, he managed the
   manufacturing operations for the Roomba vacuum cleaner. Now he helps
   entrepreneurs master the complexities of overseas production,
   introducing them to qualified manufacturing partners and putting
   product managers on the ground in Asia to sort out problems. Among the
   first 100 firms to enlist Dragon's expertise were MakerBot, Pebble, and
   Formlabs.

   <<< Makers 16-20
   [innovators-03-0314-smn.jpg]

   Email
   Comments
   Share
   Pin It

   Back

Post a comment

   Load More
   ____________________ Search
   Try: Hottest Cars Ever / MINI Cooper / Best Gadgets Ever

About
Popular Mechanics

     *
     *
     * About Us
     * Press Room
     * Privacy Policy
     * Your California Privacy Rights
     * Terms of Use
     * Site Map
     * Contact Us
     * Community Guidelines
     * Advertise Online
     * About Our Ads

Popularmechanics.com

     * Automotive
     * Technology
     * Science
     * Home How-To
     * Outdoors
     * DIY Central

   STUFF MEN LIKE
   Men's Shoes 2014
   Home Inspection Checklist
   2014 Suits and Blazers
   10 Science Fiction Movies
   Matching Shirts & Ties
   REVIEWS
   Ford F-150
   3D Printers
   Tuxedo 101
   24 Whiskey Drinks
   6 Zero Turn Mowers
   5 Tablet Reviews
   HOW TO
   How to Tie a Tie
   How to Grow a Beard
   5 Painting Tips
   How to Make Pancakes
   How to Build a Shed
   How to Make Beer
   TRENDING
   The Best Hairstyles for Guys
   Watches for Men
   Funny Comic Strips
   New Cars 2014 & 2015
   Top Rated Meatball Recipe
   Latest Daily Horoscopes
   DIY Halloween Costumes

   ©2014 Hearst Communication, Inc. All Rights Reserved. Being Green /Why
   did I get this ad?
   Hearst Men's Network

   IFRAME:
   //platform.twitter.com/widgets/follow_button.html?screen_name=PopMech&s
   ize=large

   Sign up for Popular Mechanics's free newsletter!
   Enter your email add (BUTTON)
