   The Conference Board

The Conference Board

   Sign In | Create an Account
   ____________________ Search
   Advanced Search
   Connect with us [share_facebook.jpg] [share_twitter.jpg]
   [share_linkedin.jpg] [share_youtube.jpg] [share_rss.jpg]
     * I Want To
     * Practices
     * Products & Services
     * Key Business Issues
     * Regions & Markets
     * Who We Are
     * Membership
     * Contact Us

     * Home
     * Press
     * Growing Labor Shortages on the Horizon in Mature Economies

     * Share This Page
          + Subscribe via RSS
          + "Like" The Conference Board on Facebook
          + Share on Twitter
          + Share on LinkedIn
     * Print
     * Cart

     * Press/News Archive
          + Public & Media Relations

Press Release / News

Growing Labor Shortages on the Horizon in Mature Economies

   02 September, 2014

   Serious labor shortages in the world’s advanced economies will create
   unprecedented challenges for business leaders and policymakers over the
   next fifteen years and beyond, according to a comprehensive new report
   released today by The Conference Board. From Not Enough Jobs to Not
   Enough Workers forecasts the impact of aging populations to compound
   rapidly as increasing numbers of baby boomers depart workforces. It
   draws on first-of-its-kind analysis of the relative risk of shortages
   in myriad individual labor markets, including 32 national economies,
   266 industries and 464 occupations in the United States, and 40
   occupations in Europe.

   “Mature economies are facing a historical turning point: for the first
   time since World War II, working-age populations are declining,” said
   Gad Levanon, Director of Macroeconomic Research at The Conference Board
   and a co-author of the report. “The global financial crisis and its
   aftermath—stubbornly high unemployment in many countries—have postponed
   the onset of this demographic transformation, but will not prevent it
   from taking hold. Companies in the U.S., Europe, and elsewhere must
   begin planning now for an environment in which difficulties recruiting
   and retaining workers will make it significantly harder to control
   labor costs without losing labor quality.”

   Jobs–Now Hard to Find, Soon Hard to Fill

   In examining likely labor-market trends in dozens of advanced
   economies, the report draws particular distinction between short-term
   outlooks—which reflect the continued impact of the Great Recession on
   various countries—and long-term forecasts rooted in demographic
   fundamentals. Indeed, while current labor markets in mature economies
   are not particularly tight overall—wage growth and labor turnover both
   remain below prerecession levels—this aggregate picture conceals huge
   variation between countries, with rapid reversal from labor surplus to
   shortage in many.

   This growing labor-market tightness can be traced in the gap between
   current unemployment and the estimated natural rate of unemployment.
   Already, Canada, Germany, Japan, and South Korea have reversed any
   effects of the recession and fallen below their natural rate of
   unemployment. The United States and United Kingdom are likely to follow
   in 2014–15, while countries like Australia, Sweden, Belgium, and
   Denmark will cross the threshold by 2016–17. The hardest-hit European
   economies—Greece, Spain, Italy, and Portugal—as well as France will
   likely retain slack labor markets for longer, with natural rates of
   unemployment unlikely to be reached until after 2018.

   To determine long-term trends, From Not Enough Jobs to Not Enough
   Workers introduces a Labor Shortage Index which combines current
   labor-market tightness with future demographic developments factors to
   predict the likelihood of countries experiencing labor shortages in
   2025:
     * Germany faces the largest risk of labor shortages among 32
       countries compared, based on negative projected labor-force growth
       and an unemployment rate already below the natural level. Germany’s
       highly integrated Central European neighbors—including Hungary,
       Poland, Austria, Slovakia, and the Czech Republic—face risks nearly
       as high.
     * Despite the severity of the economic crisis in Mediterranean
       countries, they may in fact see labor shortages by 2025. With
       minimal productivity growth and a large working-age population
       decline projected, Italy is at particularly high risk.
     * The Asia-Pacific picture is mixed. Already experiencing one of the
       world’s tightest labor markets, Japan faces similar demographic
       pressures as Germany in the decade ahead. High productivity growth
       should moderate the risk in South Korea.
     * The risk of labor shortages in the United Stateswill be moderate in
       a global context, as its working-age population grows minimally—but
       faster than most mature economies due to immigration. Risks in the
       U.K., France, and Canada will be broadly comparable to the U.S.

   Ground Zeroes for the Looming Labor Shortage

   Drilling deeper into country-wide data, the Future Occupational Labor
   Shortage Index introduced in the report identifies the industries most
   likely to face a scarcity of qualified talent over the next decade. The
   interaction of two factors—the speed of employment growth and the net
   number of new job-market entrants (or departures) —determines the level
   of risk for any particular occupation.

   Occupational data from the United States indicates that future labor
   shortages will cluster around three major categories of concern:
     * Health-related occupations. The same aging of the U.S. population
       that will curtail working-age population growth to as low as 0.15
       percent by 2030 is also driving up demand for medical workers. At
       the same time, high education and experience requirements limit
       entry into the job market. The result is a dearth in many
       healthcare professions, including occupational therapy assistants,
       physical therapists and therapist assistants, nurse practitioners
       and midwives, and dental hygienists. Among doctors, optometrists
       and podiatrists are the specialists most at risk of shortage, with
       the general physicians and surgeons category not far behind.
     * Skilled labor occupations. These jobs typically require more than a
       high-school education, but not a bachelor’s degree. Unlike
       healthcare, the primary driver of shortages here is not increased
       demand—employment growth is expected to be low in the coming
       decade—but instead a rapidly shrinking supply of young people
       entering these fields as increasing numbers retire. Skilled labor
       occupations most at risk include water and wastewater treatment
       plant and system operators, crane and tower operators,
       transportation inspectors, and construction and building
       inspectors.
     * STEM occupations. U.S. policymakers have long been concerned about
       shortages in science, technology, engineering, and mathematics, but
       many of these fields rank surprisingly average in a national
       context. Moderating the risk of shortages is the relatively high
       number of young entrants compared to baby-boomer retirees, as well
       as the large proportion of new immigrants in STEM jobs. Moreover,
       strong productivity growth means that output will continue to
       expand in areas like information technology, telecommunications,
       and high-tech manufacturing even as workforces in these jobs are
       expected to shrink. Nevertheless, certain STEM fields—including
       mathematical science, information security, and civil,
       environmental, biomedical, and agricultural engineering—do face
       significant shortages.

   “Our extensive database of occupational data points us to the U.S.
   industries most at risk of labor shortages,” said Levanon. “Topping the
   list are: healthcare, including hospitals and nursing facilities;
   transportation industries, including ground passenger, water, and rail
   transport; utilities; social assistance; and mining and construction.”

   “European occupational and industry data reveal a similar profile of
   risks, with social services, health professions, and medium-skilled
   trade occupations facing impending labor shortages,” said Bert Colijn,
   Senior Economist, Europe at The Conference Board and a co-author of the
   report. “STEM jobs  will also see higher pressures than in the U.S.,
   while the low-skilled occupations that form the crux of the current
   unemployment crisis in much of Europe are unlikely to see higher
   demand. This puts the onus on governments, education systems, and
   business to retrain workforces in the decade ahead.”

     Join the conversation on Twitter. @Conference Board #LaborShortage

   For complete details visit
   www.conferenceboard.org/laborshortages.

   Report From Not Enough Jobs to Not Enough Workers
   What Retiring Baby Boomers and the Coming Labor Shortage Mean for Your
   Company
   (Research Report R-1558-14-RR)
   By Gad Levanon, Bert Colijn, Ben Cheng, and Michael Paterra

   Related: International Comparison of Annual Labor Force Statistics
   part of The Conference Board International Labor Comparisons (ILC)
   program
   https://www.conference-board.org/ilcprogram/laborforceannual

   About the Conference Board

   The Conference Board is a global, independent business membership and
   research association working in the public interest. Our mission is
   unique: To provide the world’s leading organizations with the practical
   knowledge they need to improve their performance and better serve
   society. The Conference Board is a non-advocacy, not-for-profit entity
   holding 501 (c) (3) tax-exempt status in the United States.
   www.conference-board.org

   Read this report

   For further information contact:

   Jonathan Liu
   1 212 339 0257
   Jonathan.liu@conference-board.org

U.S. Indicators

     * Consumer Confidence
       Up 2.1 pts
     * Employment Trends Index
       Up 0.56 %
     * Help Wanted OnLine
       Up 164,600
     * Leading Economic Index
       Up 0.2 %
     * Measure of CEO Confidence
       Down 1.0 pts

Global Indicators

     * Australia Up 0.5%
     * Brazil Down 0.4%
     * China Up 0.7%
     * Euro Area Down 0.6%
     * France Up 0.5%
     * Germany Down 0.2%
     * India Down 0.5%
     * Japan Down 0.8%
     * Korea Down 1.1%
     * Mexico Up 0.1%
     * Spain Up 0.3%
     * U.K. Up 0.1%
     * U.S. Up 0.2%

     * About Us
     * Contact Us
     * Employment
     * Press
     * Terms of Use
     * Governance & Policies
     * The Conference Board of Canada

   © 2014 The Conference Board, Inc. All rights reserved.
   The Conference Board torch and logo are registered trademarks of The
   Conference Board Inc.

     * Ask TCB™ a Business Question
          + Submit question
     * Contact The Conference Board
     * Join
          + The Conference Board
          + China Center
          + Councils
          + Governance Center
          + Human Capital Exchange
          + Initiative on Corporate Philanthropy
          + Initiative on Sustainability
          + The Demand Institute
          + The Engagement Institute

     * Read
          + Research & Publications
          + CEO Challenge
          + The Conference Board Review
     * Register
          + Academies
          + Conferences/Events
          + Key Business Issues Briefings
          + Leadership Development Experiences
          + Research Working Groups
          + Round Tables
          + Webcasts

     * View Data & Analysis
          + Board Diversity Model
          + Business Cycles
          + CEO Confidence Data
          + Consumer Measures
          + Corporate Leadership Benchmarking
          + Economic Data & Analysis
          + Global Economic Outlook
          + Insights from our Economists
          + Labor Markets
          + Productivity & Innovation
          + Proxy Voting Data

     * Watch
          + Insight Minute
          + Upcoming Live Webcasts
          + Webcasts On Demand
          + DVDs and Video On Demand

     * Corporate Leadership
          + Corporate Finance
          + Corporate Governance
          + Marketing & Communications
          + Philanthropy & Citizenship
          + Quality Management
          + Risk Management
          + Sustainability

     * Economy & Business Environment
          + Business Scenarios
            & Strategic Planning
          + Consumer Dynamics
          + Economic Indicators & Forecasting
          + Energy & Sustainability
          + Global Value Chains
          + Growth, Productivity & Competitiveness
          + Innovation
          + Labor Markets
          + Marketing & Brand Strategy
          + Procurement & Supply Chain Strategy

     * Human Capital
          + Diversity & Inclusion
          + Employee Engagement
          + Human Capital Analytics
          + Labor Markets
          + Leadership Development
          + Strategic HR
          + Strategic Workforce Planning
          + Talent Management

     * Ask TCB™ a Business Question
          + Submit question
     * Conferences/Events
          + Search by date
          + Search by title
     * Leadership Development
          + Experiential Programs
          + Custom Programs
               o - Innovation Experience

     * Peer Learning
          + Academies
          + Councils
          + Human Capital Exchange
          + Round Tables
          + The Demand Institute
          + The Engagement Institute

     * Research
          + Publications
          + CEO Challenge
          + Research Working Groups
     * The Conference Board Review
          + Current issue
          + Previous issues
     * Webcasts and Videos
          + Live Webcasts
          + Webcasts On Demand
          + Insight Minute
          + DVDs and Video On Demand

     * Data & Analysis
          + Activist Surveillance
          + Board Diversity Model
          + Business Cycles
          + CEO Confidence Data
          + Consumer Measures
          + Corp. Leadership Benchmarking
          + Global Economic Outlook
          + Insights from our Economists
          + Labor Markets
          + Productivity & Innovation

     *
          + Looming labor shortages
          + Creating a culture of engagement
          + China's declining growth
          + Global economic outlook
          + Measuring social impact
          + CEOs top challenges for 2015
          + Closing talent gaps
          + Building a high-performing organization
          + Corporate sustainability in China
          + Productivity & competitiveness
          + Big data & human capital analytics
          + Sustainability, innovation & growth
          + Attend a briefing

     *
          + Asia-Pacific
          + China
          + Europe
          + South Asia
          + Middle East
          + The Americas
          + Educational Institutions
          + Mid-Markets

     * About Us
     * Our Community
          + Trustees
          + Voting Members
          + Global Counsellors
          + Our Experts
     * Membership
     * News

     * The Conference Board
     * China Center
     * Governance Center
     * Initiative on Corporate Philanthropy
     * Initiative on Sustainability
     * The Demand Institute
     * The Engagement Institute

     * Membership Inquiries
     * Ask TCB^™ a business question
     * Employment
     * Media Inquiries
     * Office Locations

     * Corporate Leadership
          + Sustainability
     * Economy & Business Environment
          + Business Scenarios & Strategic Planning
          + Consumer Dynamics
          + Economic Indicators & Forecasting
          + Energy & Sustainability
          + Labor Markets
          + Marketing & Brand Strategy

     Human Capital
     * Diversity & Inclusion
     * Employee Engagement
     * Labor Markets
     * Leadership Development

   Back to Top
