   #alternate alternate A to Z Terms of Use

   For a better experience on your device, try our mobile site.

   BBC

Accessibility links

     * Skip to content
     * Skip to local navigation
     * Accessibility Help

BBC navigation

     * News
     * Sport
     * Weather
     * Capital
     * Future
     * Shop
     * TV
     * Radio
     * More…

   Search term: ____________________ (BUTTON) Search

BBC News Science & Environment

     * Home
     * US & Canada
     * Latin America
     * UK
     * Africa
     * Asia
     * Europe
     * Mid-East
     * Business
     * Health
     * Sci/Environment
     * Tech
     * Entertainment
     * Video

   6 March 2014 Last updated at 02:45 ET

Share this page

     * Delicious
     * Digg
     * Facebook
     * reddit
     * StumbleUpon
     * Twitter
     * Email
     * Print

'Carbon bubble' threatens stock markets, say MPs

   Matt McGrath By Matt McGrath Environment correspondent, BBC News
   oil rig2 Investments in coal and oil may be overvalued, according to
   MPs
   Continue reading the main story

Related Stories

     * 'Fewer crops' now feeding the world
     * Pull fossil funds - UN climate chief
     * Firms 'own unburnable fossil fuels'

   The world's financial markets could be creating a "carbon bubble" by
   over valuing the fossil fuel assets of large companies say MPs.

   Much of this coal and oil may have to be left in the ground to combat
   climate change, according to the Environmental Audit Committee (EAC)

   The Committee also hits out at the lack of green finance.

   Less than half the £200bn needed to deliver emissions cuts by 2020 is
   in place they say.

   A number of studies in recent years have warned that stock markets
   around the world have overvalued companies with large holdings of coal,
   oil and gas.

   The problem stems from the fact that countries including the UK agreed
   at a UN meeting in Mexico in 2010 to limit global temperature rises to
   2C.

   To achieve this, economists including Sir Nicholas Stern have
   calculated that between 60 and 80% of existing reserves of fossil fuels
   will need to remain in the ground, unburned.

   Today's report from the House of Commons Environmental Audit Committee
   (EAC) reiterates these warnings.

   "The UK Government and Bank of England must not be complacent about the
   risks of carbon exposure in the world economy," said Committee chair
   Joan Walley MP.

   "Financial stability could be threatened if shares in fossil fuel
   companies turn out to be overvalued because the bulk of their oil, coal
   and gas reserves cannot be burnt without further destabilising the
   climate," she said.
   Global problem

   The MPs say that the Bank of England's Financial Policy Committee
   should regularly consult with the independent Committee on Climate
   Change (CCC), to help it monitor the risks to financial stability.
   wind The MPs criticise a green finance gap that they say is around
   £100bn

   They also call for new carbon reporting arrangements, so that there is
   greater clarity from corporations about their holdings and investments.

   These concerns were echoed by the UN's climate chief, Christiana
   Figueres.

   Speaking to the press in London, she said that the certainty of the
   science about climate change demanded that companies reduce their
   holdings of fossil fuels.

   "Those corporations that continue to invest in new fossil fuel
   exploration, new fossil fuel exploitation, are really in flagrant
   breach of their fiduciary duty because the science is abundantly clear
   that this is something we can no longer do," she said.

   Another new European study says that the carbon bubble risks for the
   UK's pension sector are far higher than for the banking sector.

   The report, commissioned by European Greens says that British pensions
   have a "high" exposure to carbon.

   They say that out of the 23 large EU pension funds that were examined
   in the study, the UK's Universities Superannuation Scheme has an
   "overwhelmingly large" amount of carbon risk in its portfolio.

   "The result is sobering," said Green MEP Reinhard Butikofer.

   "With over 1 trillion euros in high-carbon assets, we have identified
   that the carbon bubble is a significant risk, particularly for a number
   of EU Member States and EU financial institutions. Investments in
   fossil fuel companies could therefore quickly turn into fool's gold."
   Green banking

   As well as the carbon bubbles, the EAC report criticises the lack of
   investment in energy infrastructure to meet national and international
   targets.

   They say that less than half the £200bn that is needed to meet carbon
   reduction targets by 2020 is in place.

   However a spokesman for the Department of Energy and Climate Change
   (Decc) said that the picture of green investment in the UK was
   positive.

   "Record investments of around £40bn are expected in renewable
   electricity generation projects up to 2020, building on substantial
   investment announced since 2010," he said.

   "In total, these reforms will help to support up to £110bn of total
   investment and up to 200,000 jobs across the electricity sector by
   2020.

   "We have set the conditions to attract investment into our energy
   sector, which will keep the lights on for years to come."

   The Committee says the Coalition's Green Investment Bank has made a
   good start in areas such as financing low-energy street lighting around
   the UK that will be repaid from the savings that local authorities will
   make.

   However they criticise the fact that it does not yet have adequate
   power to borrow in order to leverage and enlarge its investments.

   "It has funding it can add value to but it is not able to go out and
   raise bonds or borrow on the market and work as a proper bank," said Dr
   Alan Whitehead MP, a member of the EAC.

   "That change clearly needs to happen at an early stage. The leverage
   that could be obtained from that is far greater."

   However a spokesman for the Department of Business Innovation and
   Skills (Bis) said that this is something for the future.

   "It is something we are keeping under review in the longer term as
   levels of public sector debt begin to fall."

   Follow Matt on Twitter.

More on This Story

Related Stories

     * 'Fewer crops' now feeding the world
       03 MARCH 2014, SCIENCE & ENVIRONMENT
     * Pull fossil funds - UN climate chief
       15 JANUARY 2014, SCIENCE & ENVIRONMENT
     * Firms 'own unburnable fossil fuels'
       19 APRIL 2013, SCIENCE & ENVIRONMENT

Share this page

     * Delicious
     * Digg
     * Facebook
     * reddit
     * StumbleUpon
     * Twitter
     * Email
     * Print

More Science & Environment stories

   RSS
     * Artist's impression of Philae deployment Date fixed for comet
       landing attempt
       Europe's daring attempt to put a small robot on the surface of
       Comet 67P will take place on Wednesday 12 November.
     * New images from Flight MH370 hunt
     * Complex molecule discovered in space

Top stories

     * A protester with his face covered with plastic wrap to protect
       himself from tear gas sits as he blocks the main street to the
       financial Central district, outside the government headquarters in
       Hong Kong on 29 September 2014 Roads blocked as HK protests spread
     * Obama: US underestimated rise of IS
     * New Afghan president to be sworn in
     * Modi wows Madison Square Garden
     * Japan volcano rescue finds 31 bodies

Features & Analysis

     * Byambajav Ulambayar (right) and Soslan Gagloev appeared at the 13th
       US Sumo Open in California on 15 September, 2013 Sumo stateside
       US hosts the largest amateur competition outside Japan
         ______________________________________________________________

     * German wurst Taste of history
       The country with one people, and more than 1,200 sausages
         ______________________________________________________________

     * Supporter holds America Loves Modi sign in Times Square, New York.
       28 Sept 2014 Mad for Modi
       NY star treatment for Indian PM
         ______________________________________________________________

     * Baylor Line First down
       Are college - and high school - football to blame for NFL woes?
         ______________________________________________________________

Most Popular

Shared

    1. 1: Tear gas and clashes at HK protest
    2. 2: Thousands at HK democracy protests
    3. 3: Curry spice 'helps brain self-heal'
    4. 4: Rosneft and Exxon find Arctic oil
    5. 5: Japan volcano rescue finds 31 bodies

Read

    1. 1: Obama: US underestimated rise of IS
    2. 2: Fresh clashes as HK protests spread
    3. 3: Hong Kong protests
    4. 4: Al-Nusra threat over air strikes
    5. 5: One people, 1,200 sausages
    6. 6: Modi wows Madison Square Garden
    7. 7: Tragedy at Dutch monster truck show
    8. 8: What is Hong Kong's Occupy Central?
    9. 9: Japan volcano rescue finds 31 bodies
   10. 10: Queen Mary: Liner that helped launch monster cruise ships

Video/Audio

    1. 2: Bodies found after volcano eruption Watch
    2. 3: Mr and Mrs Clooney step out in Venice Watch
    3. 4: Is this the kitchen of the future? Watch
    4. 5: On the front line of Hong Kong protests Watch
    5. 6: IS masked man 'identified' Watch
    6. 7: In 60 seconds: What does IS want? Watch
    7. 8: World's 'oldest woman' faces challenges Watch
    8. 9: World's most advanced jet - in 60 secs Watch
    9. 10: Japan volcano: View of eruption Watch

BBC Future

   (Getty Images)

How often must we see a dentist?

   The truth about six-month check-ups Read more...

Programmes

     * Trevi Fountain The Travel Show Watch
       The Eternal City where a few coins could help you find love. Watch
       to discover Rome in 60 seconds

Services

     *  Mobile
     *  Connected TV
     *  News feeds
     *  Alerts
     *  E-mail news

About BBC News

     * Editors' blog
     * BBC College of Journalism
     * News sources
     * Media Action
     * Editorial Guidelines

BBC links

     *
          + Mobile site
          + Terms of Use
          + About the BBC
     *
          + Advertise With Us
          + Privacy
          + Accessibility Help
     *
          + Ad Choices
          + Cookies
          + Contact the BBC
     *
          + Parental Guidance

   BBC

   BBC © 2014 The BBC is not responsible for the content of external
   sites. Read more.

   This page is best viewed in an up-to-date web browser with style sheets
   (CSS) enabled. While you will be able to view the content of this page
   in your current browser, you will not be able to get the full visual
   experience. Please consider upgrading your browser software or enabling
   style sheets (CSS) if you are able to do so.
