   #Search MIT Technology Review

     * Global Edition
     * Insider
     * Magazine
     * Business Reports
     * Lists
     * Events
     * More
          + About
          + Newsletters
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum

     * Connect

Select your localized edition:

   Close ×
     * English
     * Español
     * Deutsch
     * Italiano
     * Português
     * 中文

Filter by:

     * (*) News and Analysis
     * ( ) Magazine
     * ( ) List: Innovators Under 35
     * ( ) Conferences and Events

     * Argentina
     * Brasil
     * Colombia
     * Deutschland

     * Italia
     * México
     * Portugal
     * España

     * United States
     * Uruguay
     * 中国大陆

More Ways to Connect

   Discover one of our 28 local entrepreneurial communities »

   Be the first to know as we launch in new countries and markets around
   the globe.

   Interested in bringing MIT Technology Review to your local market?
   Search Search________________________
   Search
   Log In / Join
     * New
     * Popular
     * Login / Join

MIT Technology Review MIT Technology Review - logo

   Home News & Analysis ▾
     * Features
     * Views
     * Multimedia
     * Discussions
     * Topics

     * Popular:
     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

   cover of latest MIT Technology Review magazine issue Subscribe

     * Home
          + Home
          + Biomedicine
          + Business
          + Computing
          + Energy
          + Materials
          + Mobile
       Top Stories

Business Report

China’s Factory of the Future

Christina Larson
       1
          +

A Cheaper Way to Store Solar
         Kevin Bullis
          +

BitTorrent Adds a Paywall for Music
         Tom Simonite
          +

Using Phones’ Radio Signals to Detect Gestures
         Rachel Metz
          + See More Top Stories
     * Menu
          + News & Analysis
          + Magazine
          + Lists
          + Events
          + About
          + More
          + Features
          + Views
          + Multimedia
          + Discussions
          + Topics
          + Popular:
          + Storing Sunlight
          + Rat Control
          + Google’s Balloon Shot
          + Smarter Watson
          + Quantum Computing Questions
          + Gene Sequencing Soars
          + Printed Kidneys
       cover of latest MIT Technology Review magazine issue Subscribe
          + Current Issue
          + Past Issues
          + MIT News Magazine
          + International Editions
          + Business Reports
          + Special Publications
          + Subscriptions »
          + Smartest Companies
          + Innovators Under 35
          + Breakthrough Technologies
          + Nominations »
          + Upcoming Events
          + Partner Events
          + Emtech MIT
          + MIT Enterprise Forum
          + Our Team
          + Join Us
          + Press Room
          + Awards
          + Advertise
          + Permissions
          + Contact Us
          + Customer Support »
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum
     * Insider
     * Connect

     * The Latest
     * Popular
     * Most Shared
     * My Profile

   Unsupported browser: Your browser does not meet modern web standards.
   See how it scores »

   A Light on Madness Q&A: Emotions

Cracking the Brain’s Codes

Featured Story

     * 13 comments

Hacking the Soul

     * Free Will
     * Video: Measuring Neurons
     * Video: Manipulating Memory

     * Q&A: Emotions
     * Overcoming Paralysis
     * Q&A: Social Brain

     * The Technologies
     * Q&A: Memories
     * A Light on Madness
     * The Brain’s Codes

Cracking the Brain’s Codes

   How does the brain speak to itself?
     * By Christof Koch and Gary Marcus on June 17, 2014

     * 13 comments

     * Comments
     * Email
     * Service
     * Service
     * More Share
     * Print

   Also featured in:
   MIT Technology Review magazine
   July/August 2014
   More in this issue »

Why It Matters

   Once we understand how the brain communicates with itself, it will be
   possible to develop new ways of manipulating and directly interacting
   with it.

Hacking the Soul

     * The Technologies
     * Q&A: Memories
     * A Light on Madness
     * The Brain’s Codes
     * Q&A: Emotions
     * Overcoming Paralysis
     * Q&A: Social Brain
     * Free Will
     * Video: Measuring Neurons
     * Video: Manipulating Memory

   Close

   In What Is Life? (1944), one of the fundamental questions the physicist
   Erwin Schrödinger posed was whether there was some sort of “hereditary
   code-script” embedded in chromosomes. A decade later, Crick and Watson
   answered Schrödinger’s question in the affirmative. Genetic information
   was stored in the simple arrangement of nucleotides along long strings
   of DNA.

   The question was what all those strings of DNA meant. As most
   schoolchildren now know, there was a code contained within: adjacent
   trios of nucleotides, so-called codons, are transcribed from DNA into
   transient sequences of RNA molecules, which are translated into the
   long chains of amino acids that we know as proteins. Cracking that code
   turned out to be a linchpin of virtually everything that followed in
   molecular biology. As it happens, the code for translating trios of
   nucleotides into amino acids (for example, the nucleotides AAG code for
   the amino acid lysine) turned out to be universal; cells in all
   organisms, large or small—bacteria, giant sequoias, dogs, and
   people—use the same code with minor variations. Will neuroscience ever
   discover something of similar beauty and power, a master code that
   allows us to interpret any pattern of neural activity at will?

   At stake is virtually every radical advance in neuroscience that we
   might be able to imagine—brain implants that enhance our memories or
   treat mental disorders like schizophrenia and depression, for example,
   and neuroprosthetics that allow paralyzed patients to move their limbs.
   Because everything that you think, remember, and feel is encoded in
   your brain in some way, deciphering the activity of the brain will be a
   giant step toward the future of neuroengineering.

   Someday, electronics implanted directly into the brain will enable
   patients with spinal-cord injury to bypass the affected nerves and
   control robots with their thoughts (see “The Thought Experiment”).
   Future biofeedback systems may even be able to anticipate signs of
   mental disorder and head them off. Where people in the present use
   keyboards and touch screens, our descendants a hundred years hence may
   use direct brain-machine interfaces.

   But to do that—to build software that can communicate directly with the
   brain—we need to crack its codes. We must learn how to look at sets of
   neurons, measure how they are firing, and reverse-engineer their
   message.

   A Chaos of Codes

   Already we’re beginning to discover clues about how the brain’s coding
   works. Perhaps the most fundamental: except in some of the tiniest
   creatures, such as the roundworm C. elegans, the basic unit of neuronal
   communication and coding is the spike (or action potential), an
   electrical impulse of about a tenth of a volt that lasts for a bit less
   than a millisecond. In the visual system, for example, rays of light
   entering the retina are promptly translated into spikes sent out on the
   optic nerve, the bundle of about one million output wires, called
   axons, that run from the eye to the rest of the brain. Literally
   everything that you see is based on these spikes, each retinal neuron
   firing at a different rate, depending on the nature of the stimulus, to
   yield several megabytes of visual information per second. The brain as
   a whole, throughout our waking lives, is a veritable symphony of neural
   spikes—perhaps one trillion per second. To a large degree, to decipher
   the brain is to infer the meaning of its spikes.

   But the challenge is that spikes mean different things in different
   contexts. It is already clear that neuroscientists are unlikely to be
   as lucky as molecular biologists. Whereas the code converting
   nucleotides to amino acids is nearly universal, used in essentially the
   same way throughout the body and throughout the natural world, the
   spike-to-information code is likely to be a hodgepodge: not just one
   code but many, differing not only to some degree between different
   species but even between different parts of the brain. The brain has
   many functions, from controlling our muscles and voice to interpreting
   the sights, sounds, and smells that surround us, and each kind of
   problem necessitates its own kinds of codes.

   A comparison with computer codes makes clear why this is to be
   expected. Consider the near-ubiquitous ASCII code representing the 128
   characters, including numbers and alphanumeric text, used in
   communications such as plain-text e-mail. Almost every modern computer
   uses ASCII, which encodes the capital letter A as “100 0001,” B as “100
   0010,” C as “100 0011,” and so forth. When it comes to images, however,
   that code is useless, and different techniques must be used.
   Uncompressed bitmapped images, for example, assign strings of bytes to
   represent the intensities of the colors red, green, and blue for each
   pixel in the array making up an image. Different codes represent vector
   graphics, movies, or sound files.

     Some of the most important codes in any animal’s brain are the ones
     it uses to pinpoint its location in space. How does our own internal
     GPS work? How do patterns of neural activity encode where we are as
     we move about?

   Evidence points in the same direction for the brain. Rather than a
   single universal code spelling out what patterns of spikes mean, there
   appear to be many, depending on what kind of information is to be
   encoded. Sounds, for example, are inherently one-dimensional and vary
   rapidly across time, while the images that stream from the retina are
   two-dimensional and tend to change at a more deliberate pace.
   Olfaction, which depends on concentrations of hundreds of airborne
   odorants, relies on another system altogether. That said, there are
   some general principles. What matters most is not precisely when a
   particular neuron spikes but how often it does; the rate of firing is
   the main currency.

   Consider, for example, neurons in the visual cortex, the area that
   receives impulses from the optic nerve via a relay in the thalamus.
   These neurons represent the world in terms of the basic elements making
   up any visual scene—lines, points, edges, and so on. A given neuron in
   the visual cortex might be stimulated most vigorously by vertical
   lines. As the line is rotated, the rate at which that neuron fires
   varies: four spikes in a tenth of a second if the line is vertical, but
   perhaps just once in the same interval if it is rotated 45°
   counterclockwise. Though the neuron responds most to vertical lines, it
   is never mute. No single spike signals whether it is responding to a
   vertical line or something else. Only in the aggregate—in the neuron’s
   rate of firing over time—can the meaning of its activity be discerned.

   This strategy, known as rate coding, is used in different ways in
   different brain systems, but it is common throughout the brain.
   Different subpopulations of neurons encode particular aspects of the
   world in a similar fashion—using firing rates to represent variations
   in brightness, speed, distance, orientation, color, pitch, and even
   haptic information like the position of a pinprick on the palm of your
   hand. Individual neurons fire most rapidly when they detect some
   preferred stimulus, less rapidly when they don’t.

   To make things more complicated, spikes emanating from different kinds
   of cells encode different kinds of information. The retina is an
   intricately layered piece of nervous-system tissue that lines the back
   of each eye. Its job is to transduce the shower of incoming photons
   into outgoing bursts of electrical spikes. Neuroanatomists have
   identified at least 60 different types of retinal neurons, each with
   its own specialized shape and function. The axons of 20 different
   retinal cell types make up the optic nerve, the eye’s sole output. Some
   of these cells signal motion in several cardinal directions; others
   specialize in signaling overall image brightness or local contrast;
   still others carry information pertaining to color. Each of these
   populations streams its own data, in parallel, to different processing
   centers upstream from the eye. To reconstruct the nature of the
   information that the retina encodes, scientists must track not only the
   rate of every neuron’s spiking but also the identity of each cell type.
   Four spikes coming from one type of cell may encode a small colored
   blob, whereas four spikes from a different cell type may encode a
   moving gray pattern. The number of spikes is meaningless unless we know
   what particular kind of cell they are coming from.

   And what is true of the retina seems to hold throughout the brain. All
   in all, there may be up to a thousand neuronal cell types in the human
   brain, each presumably with its own unique role.

   Wisdom of Crowds

   Typically, important codes in the brain involve the action of many
   neurons, not just one. The sight of a face, for instance, triggers
   activity in thousands of neurons in higher-order sectors of the visual
   cortex. Every cell responds somewhat differently, reacting to a
   different detail—the exact shape of the face, the hue of its skin, the
   direction in which the eyes are focused, and so on. The larger meaning
   inheres in the cells’ collective response.

   A major breakthrough in understanding this phenomenon, known as
   population coding, came in 1986, when Apostolos Georgopoulos, Andrew
   Schwartz, and Ronald Kettner at the Johns Hopkins University School of
   Medicine learned how a set of neurons in the motor cortex of monkeys
   encoded the direction in which a monkey moves a limb. No one neuron
   fully determined where the limb would move, but information aggregated
   across a population of neurons did. By calculating a kind of weighted
   average of all the neurons that fired, Georgopoulos and his colleagues
   found, they could reliably and precisely infer the intended motion of
   the monkey’s arm.

   One of the first illustrations of what neurotechnology might someday
   achieve builds directly on this discovery. Brown University
   neuroscientist John Donoghue has leveraged the idea of population
   coding to build neural “decoders”—incorporating both software and
   electrodes—that interpret neural firing in real time. Donoghue’s team
   implanted a brushlike array of microelectrodes directly into the motor
   cortex of a paralyzed patient to record neural activity as the patient
   imagined various types of motor activities. With the help of algorithms
   that interpreted these signals, the patient could use the results to
   control a robotic arm. The “mind” control of the robot arm is still
   slow and clumsy, akin to steering an out-of-alignment moving van. But
   the work is a powerful hint of what is to come as our capacity to
   decode the brain’s activity improves.

   Among the most important codes in any animal’s brain are the ones it
   uses to pinpoint its location in space. How does our own internal GPS
   work? How do patterns of neural activity encode where we are? A first
   important hint came in the early 1970s with the discovery by John
   O’Keefe at University College in London of what became known as place
   cells in the hippocampus of rats. Such cells fire every time the animal
   walks or runs through a particular part of a familiar environment. In
   the lab, one place cell might fire most often when the animal is near a
   maze’s branch point; another might respond most actively when the
   animal is close to the entry point. The husband-and-wife team of Edward
   and May-Britt Moser discovered a second type of spatial coding based on
   what are known as grid cells. These neurons fire most actively when an
   animal is at the vertices of an imagined geometric grid representing
   its environment. With sets of such cells, the animal is able to
   triangulate its position, even in the dark. (There appear to be at
   least four different sets of these grid cells at different resolutions,
   allowing a fine degree of spatial representation.)

   Other codes allow animals to control actions that take place over time.
   An example is the circuitry responsible for executing the motor
   sequences underlying singing in songbirds. Adult male finches sing to
   their female partners, each stereotyped song lasting but a few
   seconds. As Michale Fee and his collaborators at MIT discovered,
   neurons of one type within a particular structure are completely quiet
   until the bird begins to sing. Whenever the bird reaches a particular
   point in its song, these neurons suddenly erupt in a single burst of
   three to five tightly clustered spikes, only to fall silent again.
   Different neurons erupt at different times. It appears that individual
   clusters of neurons code for temporal order, each representing a
   specific moment in the bird’s song.

   Grandma Coding

   Unlike a typewriter, in which a single key uniquely specifies each
   letter, the ASCII code uses multiple bits to determine a letter: it is
   an example of what computer scientists call a distributed code. In a
   similar way, theoreticians have often imagined that complex concepts
   might be bundles of individual “features”; the concept “Bernese
   mountain dog” might be represented by neurons that fire in response to
   notions such as “dog,” “snow-loving,” “friendly,” “big,” “brown and
   black,” and so on, while many other neurons, such as those that respond
   to vehicles or cats, fail to fire. Collectively, this large population
   of neurons might represent a concept.

     There is some cause for hope. Optogenetics now allows researchers to
     switch genetically identified classes of neurons on and off at will
     with colored beams of light. It could greatly speed up the search
     for codes.

   An alternative notion, called sparse coding, has received much less
   attention. Indeed, neuroscientists once scorned the idea as
   “grandmother-cell coding.” The derisive term implied a hypothetical
   neuron that would fire only when its bearer saw or thought of his or
   her grandmother—surely, or so it seemed, a preposterous concept.

   But recently, one of us (Koch) helped discover evidence for a variation
   on this theme. While there is no reason to think that a single neuron
   in your brain represents your grandmother, we now know that individual
   neurons (or at least comparatively small groups of them) can represent
   certain concepts with great specificity. Recordings from
   microelectrodes implanted deep inside the brains of epileptic patients
   revealed single neurons that responded to extremely specific stimuli,
   such as celebrities or familiar faces. One such cell, for instance,
   responded to different pictures of the actress Jennifer Aniston. Others
   responded to pictures of Luke Skywalker of Star Wars fame, or to his
   name spelled out. A familiar name may be represented by as few as a
   hundred and as many as a million neurons in the human hippocampus and
   neighboring regions.

   Such findings suggest that the brain can indeed wire up small groups of
   neurons to encode important things it encounters over and over, a kind
   of neuronal shorthand that may be advantageous for quickly associating
   and integrating new facts with preëxisting knowledge.

   Terra Incognita

   If neuroscience has made real progress in figuring out how a given
   organism encodes what it experiences in a given moment, it has further
   to go toward understanding how organisms encode their long-term
   knowledge. We obviously wouldn’t survive for long in this world if we
   couldn’t learn new skills, like the orchestrated sequence of actions
   and decisions that go into driving a car. Yet the precise method by
   which we do this remains mysterious. Spikes are necessary but not
   sufficient for translating intention into action. Long-term memory—like
   the knowledge that we develop as we acquire a skill—is encoded
   differently, not by volleys of constantly circulating spikes but,
   rather, by literal rewiring of our neural networks.

   That rewiring is accomplished at least in part by resculpting the
   synapses that connect neurons. We know that many different molecular
   processes are involved, but we still know little about which synapses
   are modified and when, and almost nothing about how to work backward
   from a neural connectivity diagram to the particular memories encoded.

   Another mystery concerns how the brain represents phrases and
   sentences. Even if there is a small set of neurons defining a concept
   like your grandmother, it is unlikely that your brain has allocated
   specific sets of neurons to complex concepts that are less common but
   still immediately comprehensible, like “Barack Obama’s maternal
   grandmother.” It is similarly unlikely that the brain dedicates
   particular neurons full time to representing each new sentence we hear
   or produce. Instead, each time we interpret or produce a novel
   sentence, the brain probably integrates multiple neural populations,
   combining codes for basic elements (like individual words and concepts)
   into a system for representing complex, combinatorial wholes. As yet,
   we have no clue how this is accomplished.

   One reason such questions about the brain’s schemes for encoding
   information have proved so difficult to crack is that the human brain
   is so immensely complex, encompassing 86 billion neurons linked by
   something on the order of a quadrillion synaptic connections. Another
   is that our observational techniques remain crude. The most popular
   imaging tools for peering into the human brain do not have the spatial
   resolution to catch individual neurons in the act of firing. To study
   neural coding systems that are unique to humans, such as those used in
   language, we probably need tools that have not yet been invented, or at
   least substantially better ways of studying highly interspersed
   populations of individual neurons in the living brain.

   It is also worth noting that what neuroengineers try to do is a bit
   like eavesdropping—tapping into the brain’s own internal communications
   to try to figure out what they mean. Some of that eavesdropping may
   mislead us. Every neural code we can crack will tell us something about
   how the brain operates, but not every code we crack is something the
   brain itself makes direct use of. Some of them may be
   “epiphenomena”—accidental tics that, even if they prove useful for
   engineering and clinical applications, could be diversions on the road
   to a full understanding of the brain.

   Nonetheless, there is reason to be optimistic that we are moving toward
   that understanding. Optogenetics now allows researchers to switch
   genetically identified classes of neurons on and off at will with
   colored beams of light. Any population of neurons that has a known,
   unique molecular zip code can be tagged with a fluorescent marker and
   then be either made to spike with millisecond precision or prevented
   from spiking. This allows neuroscientists to move from observing
   neuronal activity to delicately, transiently, and reversibly
   interfering with it. Optogenetics, now used primarily in flies and
   mice, will greatly speed up the search for neural codes. Instead of
   merely correlating spiking patterns with a behavior, experimentalists
   will be able to write in patterns of information and directly study the
   effects on the brain circuitry and behavior of live animals.
   Deciphering neural codes is only part of the battle. Cracking the
   brain’s many codes won’t tell us everything we want to know, any more
   than understanding ASCII codes can, by itself, tell us how a word
   processor works. Still, it is a vital prerequisite for building
   technologies that repair and enhance the brain.

   Take, for example, new efforts to use optogenetics to remedy a form of
   blindness caused by degenerative disorders, such as retinitis
   pigmentosa, that attack the light-sensing cells of the eye. One
   promising strategy uses a virus injected into the eyeballs to
   genetically modify retinal ganglion cells so that they become
   responsive to light. A camera mounted on glasses would pulse beams of
   light into the retina and trigger electrical activity in the
   genetically modified cells, which would directly stimulate the next set
   of neurons in the signal path—restoring sight. But in order to make
   this work, scientists will have to learn the language of those neurons.
   As we learn to communicate with the brain in its own language, whole
   new worlds of possibilities may soon emerge.

   Christof Koch is chief scientific officer of the Allen Institute for
   Brain Science in Seattle. Gary Marcus, a professor of psychology at New
   York University and a frequent blogger for the New Yorker, is coeditor
   of the forthcoming book The Future of the Brain.
     * Previous Article A Light on Madness
     * Next Article Q&A: Emotions

13 comments. Share your thoughts » 0 comments about this story. Start the
discussion »

   Credit: Illustration by Matt Dorfman

   Tagged: Biomedicine, EmTech2014, brain, neuroscience, neuroengineering

   Reprints and Permissions | Send feedback to the editor
     * Related stories
     * You may have missed

     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
       Controlled by software, paralyzed rats walk and climb stairs.
       Continue
       2

     *

EmTech: 3-D Printing Complex Kidney Components
       1
     *

EmTech: Risks of Gene-Editing Drugs Need Study, Pioneer Warns
       1
     *

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
       3
     *

EmTech: Three Questions with the Man Who Grows Meat
       13

     *

On the Horns of the GMO Dilemma
       23
     *

Best Tweets from EmTech: Day 1
       0
     *

EmTech: IBM Tries to Make Watson Smarter
       2
     *

EmTech: Box CEO Offers Advice for Microsoft
       0

     *

Making Innovation
     *

Three Questions with the CEO of D-Wave
     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
     *

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
     *

EmTech: IBM Tries to Make Watson Smarter
     *

EmTech: Google’s Internet “Loon” Balloons Will Ring the Globe within a Year

     * The Latest
     * Popular
     * Most Shared

     *

1 day ago

Other Interesting arXiv Papers (Week ending September 27, 2014)
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

2 days ago

Thom Yorke Album Sold Through BitTorrent in Attempt to Make File Sharers Pay
     *

2 days ago

Seven Stories You Shouldn’t Miss
(Week Ending September 27, 2014)
     *

Innovation Series: The Connected Home
       Brought to you by
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

2 days ago

Radio Interference Adds Gesture Recognition to Smartphones
     *

3 days ago

Recommended from Around the Web (Week Ending September 27, 2014)
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

3 days ago

Best Tweets from EmTech: Day 2
     *

Revolution in Progress: The Networked Economy
       In partnership with SAP
     *

3 days ago

Best Tweets from EmTech: Day 1
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

Technology Insights - Portability vs. Privacy: Striking the Right Balance in
the Mobile Era
       Free download courtesy of Symantec
     *

4 days ago

EmTech: Risks of Gene-Editing Drugs Need Study
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     * See full archive

     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

5 days ago

EmTech: Google’s Astro Teller Says Its “Loon” Balloons Will Ring the Globe in
2015
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

1 month ago

35 Innovators Under 35 | 2014
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

6 days ago

Uber’s Driver Poach Shows Lack of Respect for Workers
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

5 days ago

EmTech: Three Questions with a “Meat Brewer”
     *

5 days ago

App Talko Hopes to Get You to Use Phone to Actually Talk
     * See full archive

     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

1 week ago

Solar City and Tesla Combine Manufacturing Plans
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

1 week ago

The Hidden World of Facebook "Like Farms"
     *

2 months ago

Forget the Shortest Route Across a City; New Algorithm Finds the Most
Beautiful
     *

1 month ago

35 Innovators Under 35 | 2014
     *

3 years ago

Astronomers Find First Evidence of Other Universes
     *

1 year ago

Innovators Under 35
     *

1 year ago

Given Tablets but No Teachers, Ethiopian Children Teach Themselves
     *

1 year ago

First Teleportation from One Macroscopic Object to Another
     *

1 year ago

Government Lab Reveals It Has Operated Quantum Internet for Over Two Years
     *

5 months ago

How to Win at Rock-Paper-Scissors
     * See full archive

   Show comments »
   Conversation powered by Livefyre

New & Trending

     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

     * Other Interesting arXiv Papers (Week ending September 27, 2014)
     * First Quantum Logic Operation For An Integrated Photonic Chip
     * A Promising Step Toward Round-the-Clock Solar Power
     * Pirate Favorite BitTorrent Offers a New Way to Pay for Music

From the Archives

     * The Art of the Possible
    8 years ago
     * The Hottest VC on the Planet
    10 years ago
     * Nanotech Goes to Work
    13 years ago
     * Computing's Johnny Appleseed
    14 years ago

     * more
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * ...1899
     * more

   Close

Introducing MIT Technology Review Insider.

Already a Magazine subscriber?

   You're automatically an Insider. It's easy to activate or upgrade your
   account.
   Activate Your Account

Become an Insider

   It's the new way to subscribe. Get even more of the tech news,
   research, and discoveries you crave.
   Sign Up

Learn More

   Find out why MIT Technology Review Insider is for you and explore your
   options.
   Show Me

   News and Analysis
     * Home
     * Popular
     * Today's News
     * Blogs
     * Photo Galleries
     * Videos

   Back to Top

   The mission of MIT Technology Review is to equip its audiences with the
   intelligence to understand a world shaped by technology.
     * Editions
       Find your preferred version. Choose from six languages and in 13
       regions worldwide.
     * Archives
       Explore 115 years of innovation from the most respected technology
       publication.
     * Lists
       Discover the most important people, companies and technologies
       shaping our future.
     * Events
       Attend one of our over 400 thought-provoking live events worldwide.
     * Subscribers
       Have MIT Technology Review delivered to your doorstep, desktop, or
       tablet.

     * More
     * Newsletters
     * MIT Enterprise Forum
     * MIT News Magazine
     * EmTech

     * Company
     * About Us
     * Work for Us
     * Advertise with Us
     * Reprints and Permissions

     * Your Account
     * Join
     * View Profile
     * Manage Account
     * Manage Subscription

     * Customer Support
     * Help / Support
     * Contact us
     * Feedback
     * Sitemap

Connect

     * Twitter
     * LinkedIn
     * YouTube
     * Google+
     * StumbleUpon
     * Facebook
     * RSS
     * Mobile

MIT Technology Review

     * Ethics Statement
     * Terms of Service
     * Privacy
     * Commenting Guidelines

     * © 2014
     * v1.13.05.10

   [p?c1=2&c2=16198136&cv=2.0&cj=1]

   Quantcast
