
   MAYDAY.US
     * Facebook
     * Twitter
     * Email

   (BUTTON) Toggle navigation
   MENU
     * Our Plan
          + Our Plan
          + Candidates
     * Get Involved
          + My Super Pac
          + Embeddable Media
          + Stay Connected
          + Spread the Word
          + Buy Swag
          + Mayday Labs OSS Project
     * About
          + Team Bios
          + Donor Data
          + Videos & Media
          + FAQ
     * News
          + Mayday PAC News
          + In the News
     * Donate

     __________________________________________________________________

Enter The Contest!

   Make a 30-second video ad about money in politics #MAYDAYin30
   Enter Now
     __________________________________________________________________
     __________________________________________________________________

   MAYDAY.US is a crowd-funded SuperPAC to end all SuperPACs... including
   this one. Help us reduce the influence of money in politics by electing
   a Congress committed to fundamental reform by 2016. Let's win our
   democracy back!


$7,909,571
Raised



61,151
Donors
     __________________________________________________________________
     __________________________________________________________________

MAYDAY.US News
     __________________________________________________________________

Heading

2014-08-29

Labor Day

   Together, we have the power to fix this broken system and win our
   Democracy back ... nothing important is easy. And nothing could be as
   important as this.  Read More

   Watch Video

Heading

2014-08-27

Gallego Victory

   Our first Mayday reform candidate, Ruben Gallego, declared victory last
   night in Arizona's 7th Congressional District.  Read More

   View details

Heading

2014-08-26

Launch of Mayday Labs

   MAYDAY.US has broken new ground in online organizing. To build on this
   momentum, we are announcing the creation of Mayday Labs.  Read More

   View details
     __________________________________________________________________
     __________________________________________________________________

   Donate to Mayday PAC
     __________________________________________________________________

   Paid for by Mayday PAC.
   Not authorized by any candidate or candidate's committee.
   MAYDAY.US

   © 2014 Mayday PAC, Some rights reserved. [80x15.png]
   Twitter Page Facebook Page
