   #The Long Now Blog RSS Feed Blog of the Long Now » Drew Endy Seminar
   Primer Comments Feed We are Walking Rocks: Friends of the Pleistocene
   Explore the Geologic Now

     * Home
     * About
          + About
          + Community
          + Support
          + Essays
          + Press
          + Jobs
          + Store
          + Contact
     * Projects
          + The Interval
          + Seminars
          + Special Events
          + 10,000 Year Clock
          + Nevada
          + The Rosetta Project
          + PanLex
          + Long Bets
          + Revive & Restore
          + Long Server
          +
              _________________________________________________________

          + View all projects...
     * Blog
     * Seminars
          + Seminar Home page
          + Next Seminar
          + Seminar List View
          + Audio Podcast
          + Special Events
     * Membership
          + Become a Member
          +
              _________________________________________________________

          + Community
          + Dashboard
          + Newsletters
          + Settings
     * Donate
     * People
          + Board Members
          + Staff
          + Associates
     * Contact

Drew Endy Seminar Primer

   Posted on Wednesday, September 3rd, 02014 by Charlotte Hajer
   link Categories: Long Term Science, Seminars   chat 0 Comments

   On Tuesday, September 16th, Drew Endy presents “The iGEM Revolution“ as
   part of our monthly Seminars About Long-term Thinking. Each month, our
   Seminar Primer gives you some background about the speaker, including
   links to explore even more.

                               adventures-in2

             From Adventures in Synthetic Biology, by Drew Endy

   Biotechnology is a young science, but it’s already proven its
   (potential) benefit to civilization. We can now engineer bacteria to
   manufacture life-saving drugs, we have new ways to diagnose disease,
   and we know how to modify the genome of plants so they become resistant
   to certain pests. Yet so far, says Stanford synthetic biologist Drew
   Endy, biotech has only realized a few of the grand promises it made in
   the 01970s, after scientists first succeeded in the synthesis of
   recombinant DNA. How can we realize these promises? How can we make
   biology easier to engineer? Endy’s answer to these questions is the
   growing field of synthetic biology, and an open-source, collaborative
   approach to the development of new bio-engineering tools.

   Synthetic biology is built on the technologies of genetic engineering
   that were developed during the 20th century, but takes them a few steps
   further. Genetic engineers can isolate blocks of a cell’s genetic
   material, extract it from its nucleus, and splice it into another
   cell’s DNA to create a recombinant genome. Synthetic biologists, on the
   other hand, splice in pieces of DNA that they’ve built from scratch.
   It’s like the difference between composing an essay by cutting and
   pasting word sequences from existing texts, or doing so by putting
   individual letters in sequence in order to create words of your own.

     The Human Genome Project gave us the ability to read nature’s
     instructional manual – DNA – like words in a book. But the real
     opportunities, scientists say, lie in our ability to not only read
     genetic code, but to write it, then build it using off-the-shelf
     chemical ingredients, strung together like holiday lights. It is the
     creation of new genomes – and a new frontier in bioengineering. (San
     Jose Mercury News)

   IFRAME: //www.youtube.com/embed/EtADBcxWpVg

   Drew Endy was trained as an engineer, but found his way to biology when
   a senior-year college class made him realize that living matter holds
   great potential as building material. “I like to build stuff, and
   biology is the best technology we have for making stuff – trees,
   people, computing devices, food, chemicals, you name it,” Endy explains
   in an Edge conversation. He went on to obtain a graduate degree in
   biochemical engineering. But in his postdoctoral research, Endy began
   to grow frustrated with the existing cut-and-paste methods of DNA
   engineering. It’s an inexact science that often produces unexpected
   side effects: evolution has turned DNA into a complex library of
   information, and simply splicing in a new gene may not always lead the
   host cell to express it in the way you had expected. As a feature in
   The Economist explains,

     No intelligent designer would have put the genomes of living
     organisms together in the way that evolution has. Some parts
     overlap, meaning that they cannot change jobs independently of one
     another. Others have lost their function but have not been removed,
     so they simply clutter things up. And there is no sense of
     organization or hierarchy. That is because, unlike an engineer,
     evolution cannot go back to the drawing board, it can merely play
     with what already exists. Biologists, who seek merely to understand
     how life works, accept this. Engineers such as Endy, who wish to
     change the way it works, do not. They want to start again.

                        Image by Peter and Maria Hoey

   The only way to fully control – and understand – what a cell does, Endy
   realized, is to build its DNA from scratch. We should think of cells a
   bit more like we think of computers: as hardware that can be fully
   programmed – by DNA, the perfect software language. In an interview for
   the Stanford Alumni Magazine, Endy proposes,

     Let’s look at biology not as a science, but as a technology platform
     … Biology is the most compelling technology platform anybody has
     ever seen. It’s the stuff of life and it’s a reproducing machine!
     It’s a nanotechnology that actually works. You can program it with
     DNA – sort of. We’re learning how to do that. It’s the most
     overwhelmingly cool, impressive technology platform any engineer is
     ever going to encounter if they’re alive today.

   Endy’s mission is to help the world learn this new technology – to make
   biology easier (and thereby faster, more accessible, and finally more
   productive) to engineer. And in order to do that, Endy identifies two
   crucial tools.

   The first is standardization: rather than having to build pieces of DNA
   from scratch every time they want to create a new gene, synthetic
   biologists should be able to pick and choose ‘parts’ from a standard,
   universal toolkit of genetic material. Forbes explains:

     The Industrial Revolution got a serious boost in 1864 when a
     machinist standardized screws. Henceforth someone trying to build an
     engine could pluck a standard 8-gauge, 32-threads-per-inch machine
     screw off the shelf. Endy aims for similar standardization in the
     new field of synthetic biology, and embraces the radical approach of
     creating a free registry of building blocks. In 2002 MIT professors
     started a not-for-profit called BioBricks that has collected 2,000
     biological components, including gene sequences that sense light,
     produce light, send messages between cells and switch cell functions
     on and off.

   We can think of BioBricks as the biological equivalent of Legos:
   they’re pieces of genetic material with universal connectors on each
   end, so they can be combined with any other piece to create novel
   strings of DNA. BioBricks make DNA easier to engineer because they
   create a certain level of abstraction. Rather than having to put the
   individual As, Cs, T’s and G’s of DNA together when building a
   synthetic gene, engineers can use BioBricks as a kind of genetic
   shorthand – just as software programmers make use of languages like
   Java to spare them the work of writing out their code in bits (Stanford
   Alumni Magazine). Endy imagines that these BioBricks will be
   manufactured in so-called BioFabs (International Open Facility
   Advancing Biotechnology) – a “biological design-build facility.” In
   fact, he helped launch the first one in Emeryville, in 02009.

           Image from the European Molecular Biology Organization

   The idea of facilities dedicated entirely to building BioBricks
   suggests that standardization also leads to a productive division of
   labor. In his interview with the Stanford Alumni Magazine, Endy
   explains, “Separation of design and fabrication can allow people to
   specialize, becoming experts in each area … We’ve seen this with
   microprocessors. Someone designs the chip and somebody else builds it.”
   It’s led to more sophisticated processors – by allowing people to
   specialize, greater complexity can be developed.

   The second crucial tool involves making those standard parts publicly
   available and encouraging everyone – engineers and students alike – to
   get creative, share their findings, and help one another learn. The
   BioBricks Foundation, of which Endy is president and co-founder, works
   on the premise that “… fundamental scientific knowledge belongs to all
   of us and must be freely available for ethical, open innovation.” In
   his Edge conversation, Endy adds,

     Biotechnology today derives investments from business models that
     support the exclusive application of different biological functions
     for a very small number of problems. For example, there are
     wonderful companies that have locked up most of the relevant
     intellectual property around how to engineer proteins to bind DNA.
     The products that they can deliver are going to be measured in small
     positive integer numbers, a few diseases. But, the real value
     associated with being able to engineer proteins that bind DNA are in
     the uncountable applications people could use the proteins for. It’s
     like a programming language where it would be a big downstream
     economic cost if you owned “if/then” and you were the only person
     who could use it.

   Endy considers education a crucial component for fostering this
   open-source collaboration and innovation. He tries to get high
   schoolers and college students excited about synthetic biology in
   several ways – by writing comics about it, for example (and you’ll see
   several images from his Adventures in Synthetic Biology included in
   this post).

   But Endy’s interest in education is truly epitomized by iGEM – the
   International Genetically Engineered Machines competition. It began as
   an undergraduate course that Endy developed while teaching at MIT, and
   has since evolved into a large annual event that draws thousands of
   participants from all over the world. Competing teams use BioBricks –
   which they get from and contribute back to the BioBricks Foundation’s
   Standard Registry of Parts – to engineer synthetic organisms that
   perform particular functions. The competition not only gets
   undergraduates excited about the field of bioengineering; its promotion
   of creative collaboration also spurs innovation and advances new
   technologies.

   Of course, the widespread accessibility of new DNA-building tools isn’t
   entirely risk-free. Critics worry about what kinds of dangerous new
   things might be built if those standard parts fall into the wrong
   hands. Endy understands that advances in synthetic biology involve
   important questions about what new technologies might produce, who will
   control them, what cultural and ethical implications they’ll hold, and
   what safety issues may arise. He advocates discussion about these
   issues: in 02008, The Long Now Foundation hosted a debate between Endy
   and Jim Thomas, Research Programme Manager at the Action Group on
   Erosion, Technology, and Concentration (ETC), and an outspoken critic
   of synthetic biology.

   Though he sees the value of open discussion about the ethics of
   bioengineering, Endy hopes we do keep thinking about how synthetic
   biology might benefit society – and how engineering tools can be
   leveraged to produce that benefit in an accessible and easy, but also
   responsible and ethical way. Endy will talk about the promise of
   synthetic biology, his work with iGEM, and more on Tuesday, September
   16 at SFJAZZ Center.
     __________________________________________________________________

   navigateleft Previous Article
   We are Walking Rocks: Friends of the Pleistocene Explore the Geologic
   Now

Blog of the Long Now

   Ideas about Long-term Thinking
   ____________________
               

   The Long Now Foundation was established to creatively foster long-term
   thinking and responsibility in the framework of the next 10,000 years.
   More navigateright
   Become a Member

Categories

     * Announcements
     * Clock of the Long Now
     * Digital Dark Age
     * Events
     * Futures
     * Long Bets
     * Long News
     * Long Now salon (Interval)
     * Long Shorts
     * Long Term Art
     * Long Term Science
     * Long Term Thinking
     * Long-term Quotes
     * Manual for Civilization
     * Millennial Precedent
     * PanLex
     * Revive & Restore
     * Rosetta
     * Seminars
     * Technology
     * The Big Here
     * The Interval

Archives

     * 2014
     * 2013
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * 2007
     * 2006
     * 2005
     * 2004
     * 2003
     * 2002
     * 1999
     * 1996

   The Long Now Foundation  •  Fostering Long-term Responsibility  •  est.
   01996      Top of Page
