   #alternate

   (skip this header)
     * Subscribe to Times Union
     * Subscriber Services
     * Advertise With Us
     * Get TV Weekly Magazine

     * Register
     * Sign In

     * Weather
     * Closings
     * Traffic
     * Help

   Monday, September 29, 2014
   Times Union
____________________ [searchbutton.png]-Submit (*) timesunion.com ( )
                                                                      Businesses
     * Home
     * News
     * Sports
     * Business
     * Opinion
     * Entertainment
     * Living
     * Blogs

     * Jobs
     * Real Estate
     * Cars
     * Classifieds

     * Index ▼

   [findSave_color.png]
   Close [X]
   Quick links to other pages on this site | Still can't find it? see Site
   Index
     * Were You Seen?
     * Buy Photos
     * Calendar
     * TU Events
     * Archives
     * Obits
     * Capitol Confidential
     * On the Edge
     * Table Hopping
     * Magazines
     * Lottery

     * Local
     * Your Town
     * Capitol Confidential
     * Newsletters
     * State
     * Nation
     * World
     * Technology
     * Special Reports
     * School Closings
     * All Stories

     * HS Sports
     * Sidelines
     * Columnists
     * Siena
     * UAlbany
     * Hockey
     * MLB
     * NBA
     * NFL
     * Golf
     * Auto Racing
     * Fanshop
     * All Stories

     * Market Summary
     * The Buzz Blog
     * Women@Work
     * Technology News
     * Salary Wizard
     * Press Releases
     * Sponsored Content
     * All Stories

     * Editorials
     * Letters to Editor
     * Commentary
     * Columnists
     * Observation Deck
     * Editors' Blog
     * Submit Letters & Commentary
     * All Stories

     * Calendar
     * TU Events
     * Seen Photos
     * Movies
     * TV
     * Restaurants
     * Local Arts
     * Celebrities
     * Comics
     * Games
     * Horoscope
     * Lottery
     * All Stories

     * Parenting
     * Pets
     * Savings Source
     * High School
     * Celebrations
     * TU Events
     * 518Life
     * Women@Work
     * Explore
     * Sponsored Content
     * All Stories

     * All Blogs
     * Capitol Confidential
     * On the Edge
     * Table Hopping
     * Crime Confidential
     * Shopportunist
     * The Advocate
     * The Buzz
     * Hot Topics
     * Capital Region Gives

     * Jobs Weekly
     * Job Fair
     * Place an Ad
     * Careers and Worklife Blog
     * Business Blog
     * Salary Wizard

     * For Sale
     * For Rent
     * Open Houses
     * New Homes
     * Land & Farms
     * Commercial
     * Services
     * Auctions
     * Home Style

     * Search New Cars
     * Search Pre-Owned Cars
     * Vehicle Reviews
     * Classic Cars Blog
     * The Bike Blog
     * Car Sense

     * Shop Classifieds
     * Place an Ad
     * Find Ads
     * Help Topics
     * A-List Business Directory
     * Shopping & Coupons
     * How to Advertise
     __________________________________________________________________

   Print This Article
                     « Back to Article

Looking west for fast track guidance

Company works with Silicon Valley author, sage on product development

   Larry Ruliso, Times Union

By Larry Rulison

Published 9:41 pm, Tuesday, September 16, 2014

   IFRAME: galleryrefresher

   IFRAME: gallery_pos_refresher

   Tweet
   [pinit_fg_en_rect_gray_20.png]
   Larger | Smaller
   Printable Version
   Email This

   (*) Georgia (default)

   ( ) Verdana

   ( ) Times New Roman

   ( ) Arial
   Font

Latest News

     * Crash report lacking cause
     * Trash fire at Port of Albany
     * Cuomo vows homeland defense
     * Nominate your workplace for top honors

   Page 1 of 1

   Niskayuna

   General Electric Co.'s launch of its new fuel cell business in Malta
   last month is part of a larger corporate effort to get the company and
   its research labs to operate more like companies in Silicon Valley.

   Mark Little, the head of GE Global Research in Niskayuna, said Monday
   during an investor conference in Laguna Beach, Calif., that the
   creation of GE Fuel Cells was inspired by the company's new FastWorks
   initiative designed to get products to market faster, cheaper and with
   more input from customers.

   Unlike most GE businesses that traditionally fall under one of the
   industrial giant's units, GE Fuel Cells was launched as a standalone
   business with its own board of directors and milestones it must hit to
   receive funding from GE's venture capital arm.

   "We set up our separate team. We took technology and technologists out
   of our corporate research center and our business put them aside,
   letting them run fast and free," Little said at the conference, which
   was hosted by financial services company Morgan Stanley. "This is the
   idea of FastWorks."

   Little said that GE has been working with Silicon Valley entrepreneur
   and author Eric Ries, who wrote the book "The Lean Startup," which
   focuses on developing products more effectively. Little said he was
   skeptical at first that Ries could teach anything to executives like
   himself who have decades of experience.

   "We're looking at young Eric and thinking how the hell is this software
   dude going to have anything to say to us," Little said. "And yet his
   ideas were transformational for us. I went in completely skeptical
   about it. I came away completely enthused."

   Little said that GE has already started to change a culture that is
   used to methodically plodding along as it brings new products to
   market.

   "Now we say, give me your product spec, try it out with your customers,
   adjust, get products out fast, and learn, learn, learn," Little said.
   "This is very exciting to people in our company."

   GE Fuel Cells was created under that new model and employs 22 people in
   20,000 square feet of space at Saratoga Technology + Energy Park in
   Malta, where it is working on pilot manufacturing in close partnership
   with potential customers.

   It will also test the new fuel cells in partnership with Hudson Valley
   Community College's Tec-Smart campus next door.

   Little also said GE is thinking differently about partnerships,
   including its recent plan to work with SUNY Polytechnic Institute in
   Albany, formerly SUNY College of Nanoscale Science and Engineering, on
   power electronics chips made of silicon carbide. GE has been working on
   the technology for decades at its Niskayuna lab but hopes to now get it
   to market much faster by having SUNY Poly and its corporate partners
   get it into commercial production.

   "They're going to build out a capability to give us this in very
   significant quantities, driving the cost way down," Little said. "That
   will play in solar, that will play in many other parts of our health
   care business, our aviation business. It's going to be a great
   technology for us."

   lrulison@timesunion.com • 518-454-5504 • @larryrulison

   [usfeed.hearst.articles;sz=5x5;ord=1411964058?]
   Printable Version
   Email This
   Tweet
   [pinit_fg_en_rect_gray_20.png]

More Business Stories

   Previous Button Next Button
   Click to View RSS Feed
     * Construction continues at Ellis Hospital's new Emergency Care
       Center Thursday Sept. 18, 2014, in Schenectady, NY. (John Carl
       D'Annibale / Times Union)
       Efficiency to the rescue
     * David Puckett color illustration of black financial clouds looming
       over a middle-class population of people standing in field and
       looking up to the gloomy sky.
       Looking for a bargain
     * Stranded traveler Brian Campbell of Phoenix, Arizona, in line at a
       ticket counter at Albany Airport after a fire at a suburban air
       traffic control center in Illinois disrupted flights Friday Sept.
       26, 2014. (John Carl D'Annibale / Times Union)
       Chicago air traffic fire delayed hundreds in Albany
     * A detour sign is seen on Rt 67 by the turn for Rts. 32 and 4 near
       the Mechanicville bridge on Friday, Sept. 26, 2014 in Saratoga
       Springs, N.Y. (Lori Van Buren / Times Union)
       Driving away business?
     * Heat cost likely to chill
     * Photos: SteelDay 2014
     * $554M settlement with U.S. OK'd
     * Bustling time for buses
     * Rail shipments of crude face tighter standards
     * Aisle seat, middle seat — no seat
     * Living costs squeeze middle class
     * Wind energy company to model L.I. coast area

   Need to Register? (BUTTON) X
   ____________________ ____________________
   [ ] Remember Me
   Sign-in Forgot your password?

The Buzz: Business news

     * Sagamore Hotel sewage spill fouls Lake George
       DEC press releases describes the spill:...
       9/26/2014 | Comments »

     * Guess which local pollster gets an A- from FiveThirtyEight
     * Chamber holding job fair in Malta
     * Albany solar firm set to merge with Aussie company

   View Blog »

Featured videos

   Click to View RSS Feed

Latest News

   Click to View RSS Feed
     * Rescue workers at the scene of a plane crash at the Selkirk rail
       yard. Tom Heffernan Sr. / Special to the Times Union ORG XMIT:
       MER2014090818230069
       Picasa
       Crash report lacking cause
       A preliminary report gives a more detailed account of the Sept. 8
       plane crash that killed two people flying out of the South
       Albany...

Top Jobs

     * PEDIATRIC DENTAL ASSISTANT -
       P/T Experience required, Great Patients! Please email your resume
       ... more »
     * PROBATION OFFICER US Probation
       is accepting applications in Albany. Bachelor's degree required.
       P... more »

   More »

Times Union

     * News
     * Local News
     * Your Town
     * Capitol Confidential
     * Nation
     * World
     * Sports
     * High School Sports
     * Opinion

     * Business
     * Technology
     * Living
     * Entertainment
     * Movies
     * Television
     * Restaurants
     * Events Calendar
     * Comics
     * Games

     * Blogs
     * Weather
     * Obituaries
     * Births
     * Weddings/Celebrations
     * Photos and Video
     * Archives
     * 518 Life
     * Women@Work
     * Explore/Travel

Services

     * Help/Contact Us
     * Copyright/Reprint
     * Classroom Enrichment
     * Privacy Policy
     * California Privacy Rights
     * Terms of Service
     * Mobile site
     *
     * E-Edition
     * Newsletters

Home Delivery

     * Newspaper Subscription
     * Subscriber Services
     * Deliver the Paper
     * Marketplace
     * Cars
     * Jobs
     * Homes
     * Classifieds

     * Hope Fund
     * Business Directory
     * Shopping/Coupons
     * Find&Save Local Shopping
     * Purchase Photos
     * Today's Print Ads
     * Place an Ad
     * Info for Advertisers
     * Ad Choices

   © 2014 The Hearst Corporation
   Hearst Newspapers [rss.gif]    [myyahoo.gif]
