   #RSS Feed RSS

   Town Square

Town Square

The Official Square Blog

   Subscribe

Together, Square Sellers Are the 13th Largest Retailer in the Country

   Thursday, 18 September 2014

   Building a business can be daunting. Some days it can feel like it’s
   you against the world. We know that feeling. But together we’re making
   a huge impact.

   If taken collectively, Square sellers rank as the 13th largest retailer
   in the country by annual sales. That’s in the same league as giants
   like Safeway, McDonald’s, and Amazon. So take a step back and look at
   what we’ve accomplished — we’re all in this together.

   Top Retailers By Us Sales 500px

   Country/Language
     * United States (English)
     * United States (Español)
     * Canada (English)
     * Canada (Français)
     * 日本

   Support CenterAbout SquareSquare Blog
   © 2009–2014 Square, Inc.
   Privacy PolicySeller Agreement
