    #Raw Story » Feed Raw Story » Comments Feed Raw Story » Who gets shot
   in America: What I learned compiling records of carnage for the New
   York Times Comments Feed

   Quantcast Quantcast

   NEWS
   US News
   Blacks six times more likely to be busted for marijuana possession in
   FL counties: report Blacks six times more likely to be busted for
   marijuana possession in FL counties: report Ferguson protests continue
   as authorities seek suspects in shootings of two officers Ferguson
   protests continue as authorities seek suspects in shootings of two
   officers Facing tax shortfall, Kansas approves online sex toy auction
   to recoup lost tax revenue Facing tax shortfall, Kansas approves online
   sex toy auction to recoup lost tax revenue Family of five found dead of
   unknown causes in Utah home Family of five found dead of unknown causes
   in Utah home Trailing badly in polls, embattled Oregon GOP senate
   nominee ducks debates, appearances Trailing badly in polls, embattled
   Oregon GOP senate nominee ducks debates, appearances
   World
   US-led coalition jets pound Islamic State sites in Syria US-led
   coalition jets pound Islamic State sites in Syria Police use teargas as
   thousands of pro-democracy demonstrators fill streets of Hong Kong
   Police use teargas as thousands of pro-democracy demonstrators fill
   streets of Hong Kong Conservative British minister resigns after paper
   claims he sent explicit selfie to undercover reporter Conservative
   British minister resigns after paper claims he sent explicit selfie to
   undercover reporter More than 30 feared dead on Japan’s erupted Mount
   Ontake volcano More than 30 feared dead on Japan’s erupted Mount Ontake
   volcano 1804 plot to kill Napoleon linked to British cabinet minister
   1804 plot to kill Napoleon linked to British cabinet minister
   Science
   Five ways the superintelligence revolution might happen Five ways the
   superintelligence revolution might happen Can sex affect your risk of
   getting cancer? Can sex affect your risk of getting cancer? The grim
   story of the Snowy Mountains’ cannibal horses The grim story of the
   Snowy Mountains’ cannibal horses How to tell if your child has a speech
   or language impairment How to tell if your child has a speech or
   language impairment Gravity shift reveals West Antarctic ice loss
   Gravity shift reveals West Antarctic ice loss
   Tech
   Researchers use ‘wearable technology’ investigate obesity at Florida
   high school Researchers use ‘wearable technology’ investigate obesity
   at Florida high school ‘Anti-Facebook’ social network Ello gets viral
   surge ‘Anti-Facebook’ social network Ello gets viral surge Those
   ‘amazing’ Facebook relationship posts are just a mask for insecurity:
   study Those ‘amazing’ Facebook relationship posts are just a mask for
   insecurity: study World Wide Web inventor: ‘I want a web where I’m not
   spied on, where there’s no censorship’ World Wide Web inventor: ‘I want
   a web where I’m not spied on, where there’s no censorship’ Company
   files lawsuit against NASA and SpaceX over ‘space taxi’ contracts
   Company files lawsuit against NASA and SpaceX over ‘space taxi’
   contracts
   Media
   ‘Wire’ creator David Simon: Corporations ‘the cancer’ that are slowly
   killing American middle-class ‘Wire’ creator David Simon: Corporations
   ‘the cancer’ that are slowly killing American middle-class Prolific
   Prince goes funk, rock, sci-fi with two albums Prolific Prince goes
   funk, rock, sci-fi with two albums Is the audio cassette renaissance
   for real? Is the audio cassette renaissance for real? Picturing war:
   How photography has shocked and sanitized, but changed very little
   Picturing war: How photography has shocked and sanitized, but changed
   very little Marvel Entertainment settles with Jack Kirby estate ahead
   of Supreme Court hearing Marvel Entertainment settles with Jack Kirby
   estate ahead of Supreme Court hearing
   Video
   WATCH: PA police officers burst into home, arrest woman for filming
   them with cellphone WATCH: PA police officers burst into home, arrest
   woman for filming them with cellphone 2-year-old discovers loaded
   handgun with safety off in Florida rental car 2-year-old discovers
   loaded handgun with safety off in Florida rental car Fox host tells
   school to ‘stand up’ to atheists: ‘Salvation’ T-shirts are ‘harmless’
   Fox host tells school to ‘stand up’ to atheists: ‘Salvation’ T-shirts
   are ‘harmless’ Watch: Ingraham loses it after Bush aide says Reagan’s
   attorney general worse than Holder Watch: Ingraham loses it after Bush
   aide says Reagan’s attorney general worse than Holder Bill O’Reilly
   insults US military: It can’t defeat ISIS because there are ‘no Pattons
   today’ Bill O’Reilly insults US military: It can’t defeat ISIS because
   there are ‘no Pattons today’
   OPINION
   Pandagon
   ESPN’s suspension of Bill Simmons is a travesty ESPN’s suspension of
   Bill Simmons is a travesty Endless comedy gold as Republicans pretend
   they give a crap about women’s health Endless comedy gold as
   Republicans pretend they give a crap about women’s health The reward
   for being a “good Christian wife”: Being honored and protected as long
   as it’s convenient The reward for being a “good Christian wife”: Being
   honored and protected as long as it’s convenient Fox News explains why
   contraception is bad and tobacco is good: Because men, that’s why. Fox
   News explains why contraception is bad and tobacco is good: Because
   men, that’s why. Let this girl wear her ridiculous “Virginity Rocks”
   T-shirt Let this girl wear her ridiculous “Virginity Rocks” T-shirt
   TBogg
   Ready to have some Duggar sexytime tips shoved down your throat? Of
   course you are… Ready to have some Duggar sexytime tips shoved down
   your throat? Of course you are… Free Beacon: Hillary once wrote letters
   to Saul Alinsky using FDR stamps, so probably a commie Free Beacon:
   Hillary once wrote letters to Saul Alinsky using FDR stamps, so
   probably a commie World’s Slimiest Person (hint: Lanny Davis) defends
   Roger Goodell, because… of course World’s Slimiest Person (hint: Lanny
   Davis) defends Roger Goodell, because… of course New Miss America’s
   talent is baby-killing and handing out whore pills … some say New Miss
   America’s talent is baby-killing and handing out whore pills … some say
   Sarah Palin’s TV Channel is now just a hot mess existential version of
   ‘Wayne’s World’ Sarah Palin’s TV Channel is now just a hot mess
   existential version of ‘Wayne’s World’
   Katie Halper
   Dear Jews: Have a happy and healthy New Year by inter-marrying! Dear
   Jews: Have a happy and healthy New Year by inter-marrying! Cop who
   killed young Black man with dreads warned of Rasta drug culture Cop who
   killed young Black man with dreads warned of Rasta drug culture The
   sound of 310,000 people holding a moment of silence for climate change
   victims The sound of 310,000 people holding a moment of silence for
   climate change victims Urban Outfitter’s greatest racist, sexist,
   tasteless hits Urban Outfitter’s greatest racist, sexist, tasteless
   hits As a Jew, I’m grateful that Joe Biden used the word ‘Shylocks’ As
   a Jew, I’m grateful that Joe Biden used the word ‘Shylocks’
   Ed Schultz
   Commentary
   The same week the US goes to war with one, NYT’s Douthat asks, where
   are the cults? The same week the US goes to war with one, NYT’s Douthat
   asks, where are the cults? This week in Photos: 30 images from the
   People’s Climate March and Flood Wall St. This week in Photos: 30
   images from the People’s Climate March and Flood Wall St. Paul Krugman
   dismantles notion that the 1 percent’s lack of humility is the real
   problem Paul Krugman dismantles notion that the 1 percent’s lack of
   humility is the real problem Jesse Jackson: Silicon Valley has a proud
   record on innovation, a shameful one on equality Jesse Jackson: Silicon
   Valley has a proud record on innovation, a shameful one on equality
   Escape from Duggarville: How playing the good Christian housewife
   almost killed me Escape from Duggarville: How playing the good
   Christian housewife almost killed me
   MORE
   News
   US NewsWorldScienceTechMediaAll Video
   About Our Company
   MastheadJobs and Internships
   Contact
   News TipsCopyright & Syndication QuestionsBanned from Commenting?
   Advertise
   Advertise
   Legal
   Privacy PolicyTerms of Service
   Subscribe
   Get our daily newsletter!Like us on Facebook Follow us on
   TwitterGoogle+
   Search ...__________ (BUTTON)
   NEWS
   US NewsWorldScienceTechMediaVideo
   Blacks six times more likely to be busted for marijuana possession in
   FL counties: report Blacks six times more likely to be busted for
   marijuana possession in FL counties: report Ferguson protests continue
   as authorities seek suspects in shootings of two officers Ferguson
   protests continue as authorities seek suspects in shootings of two
   officers Facing tax shortfall, Kansas approves online sex toy auction
   to recoup lost tax revenue Facing tax shortfall, Kansas approves online
   sex toy auction to recoup lost tax revenue Family of five found dead of
   unknown causes in Utah home Family of five found dead of unknown causes
   in Utah home Trailing badly in polls, embattled Oregon GOP senate
   nominee ducks debates, appearances Trailing badly in polls, embattled
   Oregon GOP senate nominee ducks debates, appearances
   US-led coalition jets pound Islamic State sites in Syria US-led
   coalition jets pound Islamic State sites in Syria Police use teargas as
   thousands of pro-democracy demonstrators fill streets of Hong Kong
   Police use teargas as thousands of pro-democracy demonstrators fill
   streets of Hong Kong Conservative British minister resigns after paper
   claims he sent explicit selfie to undercover reporter Conservative
   British minister resigns after paper claims he sent explicit selfie to
   undercover reporter More than 30 feared dead on Japan’s erupted Mount
   Ontake volcano More than 30 feared dead on Japan’s erupted Mount Ontake
   volcano 1804 plot to kill Napoleon linked to British cabinet minister
   1804 plot to kill Napoleon linked to British cabinet minister
   Five ways the superintelligence revolution might happen Five ways the
   superintelligence revolution might happen Can sex affect your risk of
   getting cancer? Can sex affect your risk of getting cancer? The grim
   story of the Snowy Mountains’ cannibal horses The grim story of the
   Snowy Mountains’ cannibal horses How to tell if your child has a speech
   or language impairment How to tell if your child has a speech or
   language impairment Gravity shift reveals West Antarctic ice loss
   Gravity shift reveals West Antarctic ice loss
   Researchers use ‘wearable technology’ investigate obesity at Florida
   high school Researchers use ‘wearable technology’ investigate obesity
   at Florida high school ‘Anti-Facebook’ social network Ello gets viral
   surge ‘Anti-Facebook’ social network Ello gets viral surge Those
   ‘amazing’ Facebook relationship posts are just a mask for insecurity:
   study Those ‘amazing’ Facebook relationship posts are just a mask for
   insecurity: study World Wide Web inventor: ‘I want a web where I’m not
   spied on, where there’s no censorship’ World Wide Web inventor: ‘I want
   a web where I’m not spied on, where there’s no censorship’ Company
   files lawsuit against NASA and SpaceX over ‘space taxi’ contracts
   Company files lawsuit against NASA and SpaceX over ‘space taxi’
   contracts
   ‘Wire’ creator David Simon: Corporations ‘the cancer’ that are slowly
   killing American middle-class ‘Wire’ creator David Simon: Corporations
   ‘the cancer’ that are slowly killing American middle-class Prolific
   Prince goes funk, rock, sci-fi with two albums Prolific Prince goes
   funk, rock, sci-fi with two albums Is the audio cassette renaissance
   for real? Is the audio cassette renaissance for real? Picturing war:
   How photography has shocked and sanitized, but changed very little
   Picturing war: How photography has shocked and sanitized, but changed
   very little Marvel Entertainment settles with Jack Kirby estate ahead
   of Supreme Court hearing Marvel Entertainment settles with Jack Kirby
   estate ahead of Supreme Court hearing
   WATCH: PA police officers burst into home, arrest woman for filming
   them with cellphone WATCH: PA police officers burst into home, arrest
   woman for filming them with cellphone 2-year-old discovers loaded
   handgun with safety off in Florida rental car 2-year-old discovers
   loaded handgun with safety off in Florida rental car Fox host tells
   school to ‘stand up’ to atheists: ‘Salvation’ T-shirts are ‘harmless’
   Fox host tells school to ‘stand up’ to atheists: ‘Salvation’ T-shirts
   are ‘harmless’ Watch: Ingraham loses it after Bush aide says Reagan’s
   attorney general worse than Holder Watch: Ingraham loses it after Bush
   aide says Reagan’s attorney general worse than Holder Bill O’Reilly
   insults US military: It can’t defeat ISIS because there are ‘no Pattons
   today’ Bill O’Reilly insults US military: It can’t defeat ISIS because
   there are ‘no Pattons today’
   OPINION
   PandagonTBoggKatie HalperEd SchultzCommentary
   ESPN’s suspension of Bill Simmons is a travesty ESPN’s suspension of
   Bill Simmons is a travesty Endless comedy gold as Republicans pretend
   they give a crap about women’s health Endless comedy gold as
   Republicans pretend they give a crap about women’s health The reward
   for being a “good Christian wife”: Being honored and protected as long
   as it’s convenient The reward for being a “good Christian wife”: Being
   honored and protected as long as it’s convenient Fox News explains why
   contraception is bad and tobacco is good: Because men, that’s why. Fox
   News explains why contraception is bad and tobacco is good: Because
   men, that’s why. Let this girl wear her ridiculous “Virginity Rocks”
   T-shirt Let this girl wear her ridiculous “Virginity Rocks” T-shirt
   Ready to have some Duggar sexytime tips shoved down your throat? Of
   course you are… Ready to have some Duggar sexytime tips shoved down
   your throat? Of course you are… Free Beacon: Hillary once wrote letters
   to Saul Alinsky using FDR stamps, so probably a commie Free Beacon:
   Hillary once wrote letters to Saul Alinsky using FDR stamps, so
   probably a commie World’s Slimiest Person (hint: Lanny Davis) defends
   Roger Goodell, because… of course World’s Slimiest Person (hint: Lanny
   Davis) defends Roger Goodell, because… of course New Miss America’s
   talent is baby-killing and handing out whore pills … some say New Miss
   America’s talent is baby-killing and handing out whore pills … some say
   Sarah Palin’s TV Channel is now just a hot mess existential version of
   ‘Wayne’s World’ Sarah Palin’s TV Channel is now just a hot mess
   existential version of ‘Wayne’s World’
   Dear Jews: Have a happy and healthy New Year by inter-marrying! Dear
   Jews: Have a happy and healthy New Year by inter-marrying! Cop who
   killed young Black man with dreads warned of Rasta drug culture Cop who
   killed young Black man with dreads warned of Rasta drug culture The
   sound of 310,000 people holding a moment of silence for climate change
   victims The sound of 310,000 people holding a moment of silence for
   climate change victims Urban Outfitter’s greatest racist, sexist,
   tasteless hits Urban Outfitter’s greatest racist, sexist, tasteless
   hits As a Jew, I’m grateful that Joe Biden used the word ‘Shylocks’ As
   a Jew, I’m grateful that Joe Biden used the word ‘Shylocks’
   The same week the US goes to war with one, NYT’s Douthat asks, where
   are the cults? The same week the US goes to war with one, NYT’s Douthat
   asks, where are the cults? This week in Photos: 30 images from the
   People’s Climate March and Flood Wall St. This week in Photos: 30
   images from the People’s Climate March and Flood Wall St. Paul Krugman
   dismantles notion that the 1 percent’s lack of humility is the real
   problem Paul Krugman dismantles notion that the 1 percent’s lack of
   humility is the real problem Jesse Jackson: Silicon Valley has a proud
   record on innovation, a shameful one on equality Jesse Jackson: Silicon
   Valley has a proud record on innovation, a shameful one on equality
   Escape from Duggarville: How playing the good Christian housewife
   almost killed me Escape from Duggarville: How playing the good
   Christian housewife almost killed me
   MORE
   NewsUS NewsWorldScienceTechMediaAll Video
   About Our CompanyMastheadJobs and Internships
   ContactNews TipsCopyright & Syndication QuestionsBanned from
   Commenting?
   AdvertiseAdvertise
   LegalPrivacy PolicyTerms of Service
   SubscribeGet our daily newsletter!Like us on Facebook Follow us on
   TwitterGoogle+

     *

WATCH: PA police officers burst into home, arrest woman for filming them with
cellphone
     *

Arrested Catholic Archbishop’s computer contained over 100,000 images of
children
     *

Fox host tells Ben Carson: You as president is like a lawmaker doing brain
surgery
     *

ABC cuts off Rick Perry’s conspiracy rant about Obama, immigrants, drones,
and hurricanes
     *

Bill Maher: A cop’s job isn’t that dangerous — police need to stop ‘going
mental for no reason’
     *

Escape from Duggarville: How playing the good Christian housewife almost
killed me
     *

Watch: Ingraham loses it after Bush aide says Reagan’s attorney general worse
than Holder
     *

11-month old killed by foster mother was taken away from parents because of
pot use
     *

Christian broadcaster: Ebola could cleanse US of atheists, gay people, and
sluts
     *

Fox hosts blame drunk girls for frat rapes: ‘These guys, what are they
supposed to do?’

   Trigger Happy

Who gets shot in America: What I learned compiling records of carnage for the
New York Times

   Jennifer Mascia
   15 Jul 2014
   Don't miss stories. Follow Raw Story!
   Follow @rawstory

   JenniferMascia


   A year and a half ago, after the massacre at Sandy Hook Elementary
   School in Newtown, Conn., Joe Nocera, an Op-Ed columnist at the New
   York Times, asked me, an editorial assistant at the newspaper, to find
   out who gets shot in America every day.

   Joe has a young child, and he was haunted by the fact that it could
   easily have been his own son in that classroom. We realized that we
   didn’t know who the majority of gun violence victims were, the people
   whose deaths didn’t make it onto a CNN broadcast.

   Six weeks after Newtown, Joe wrote a column consisting of a few lines
   about shootings that had happened that week, presented without comment.
   He had a blog he wasn’t using, so starting the next day, I started
   writing at that blog by searching for America’s shooting victims.

   The project began with just a couple of items unearthed during a Google
   news search, but after a few months I was searching ten pages deep —
   for “shooting,” “man shot,” “woman shot,” “child shot,” “teen shot” and
   “accidentally shot.” By the project’s end, the report featured 40
   shootings a day. Of course, there were more, but I was only finding the
   ones reported in the news. This naturally limited my scope — most
   suicides aren’t reported at all.

   Each post garnered hundreds of comments, ranging from the staunchest
   gun-rights advocates to the most earnest gun control defenders. I
   moderated them all, and made sure to include a wide range of opinion.
   Some of these commenters began addressing me by name, and they engaged
   in a lively debate with each other. A community was born, and a
   conversation was being had that I didn’t think existed anywhere else.

   A few months in, I noticed how shootings spiked over the weekends, and
   I came up with a new format specifically for Friday through Sunday, in
   which I’d limit each shooting to a single detail-packed sentence
   instead of the three-line descriptions I employed during the week. I
   was inspired by Portraits of Grief, the post-9/11 victim profiles by
   the Times, which gave readers a clear picture of who these people were
   in remarkably few words. These single sentences resulted in paragraph
   after paragraph. I never expected people to read it all; I just wanted
   them to scroll through and see just how many shootings there were. I
   wanted them to get a sense of the carnage.

   One person who was impressed by the sheer volume of mayhem was Sen.
   Dick Durbin, who read the Gun Report on the Senate floor. Twice. “The
   tally of shootings in America goes on to fill 19 paragraphs,” Durbin
   remarked in May 2013.

   Summer was the worst. Holiday weekends were full of needless shootings
   — arguments, stray bullets, kids finding their parents’ guns. Compiling
   weekend reports took me 10 hours every Sunday. It was a slog, but it
   was necessary. This is exactly why I went to journalism school. It’s
   rare that you get to effect change on such a big stage. Even though the
   Gun Report was online, and appeared not in print but on a columnist’s
   personal blog, it got attention. No one else in the country was doing
   this, and the New York Review of Books and New York magazine took
   notice. Would this change public opinion or spark legislative change?
   Probably not. But perhaps it would elicit a conversation about guns
   between each mass shooting. That drumbeat needed to continue before and
   after the Adam Lanzas of the world did their damage.

   I covered many shootings of and by children — kids under 10 shooting
   each other while playing with a gun; a man once left an AK-47 on a
   picnic table, only for his 6-year-old grandson to pick it up and kill
   him with it — but I am haunted by one shooting in particular that
   didn’t involve children at all. In January, Phillip Willet, 79, who was
   bedridden after being diagnosed with cancer, shot and killed his wife,
   79-year-old Catherine Willet, and then shot himself. He lived; she did
   not. One of the victim’s sisters overheard the lead-up to the shooting,
   which took place in the couple’s bedroom.

   The two were arguing, and Catherine Willet could be heard saying,
   “Don’t do that. Why are you doing this? I love you. Please Phil, I love
   you.” He then shot her in the head.

   It took a lot to make me cry in regards to the Report — I was numb at
   this point — but after writing this one I had to put my head down and
   just let myself feel it. Much like the day I found myself reporting on
   a friend.

   Ali Eskandarian, 35, was one of a group of musicians shot and killed by
   a disturbed former acquaintance in the Williamsburg section of Brooklyn
   in November. I sat down at my desk at work, ready to put the finishing
   touches on that day’s report, when I opened the homepage of the Times
   and read about the murder of three members of the Yellow Dogs, a rock
   band comprised mostly of expats from Tehran. Ali was the ex-boyfriend
   of a former Times colleague of mine, and I’d gone to several of his
   live shows. The couple had me over for a few smoky, scotch-soaked
   parties at their apartment in Greenwood Heights. Ali was vibrant, full
   of positive energy and love. And a couple of e-mails later, I confirmed
   that he was dead.

   I wrote about him two days later. I was used to covering people I
   didn’t know; I was even moved by their plight. But this changed
   everything.

   Around the time the report marked its first year of existence, I began
   to feel its tug on my psyche. Starting with a blank page every morning
   and filling with news analysis, art and the punishing list of gunshot
   victims felt like climbing a mountain. But I didn’t want to stop. I
   couldn’t. If I did, who would speak for these people? If my voice fell
   silent, I’d let down those whose stories would never see the light of
   day beyond their local paper.

                                    —-

   My mother died four and a half years after my father succumbed to lung
   cancer, and as I was cleaning out her apartment I found his gun under
   their bed.

   It was a .22 and it had a name: “The Plinker,” which was etched into
   its Bakelite handle. It was my parents’ security gun, the one weapon
   they kept around the house just in case. In my youth I’d never found
   it, and I was an only child who rifled through every closet and drawer.
   My father kept it hidden and unloaded. But I was glad he had it.

   Five years earlier, days before I moved out of my parents’ apartment, a
   man followed me home from the bus stop. He drove slowly alongside me
   and tried to engage me as I trudged the long block home. I don’t
   remember what he said, trying my best to ignore him, but when I told my
   parents, they knew just what to do. The next day they met me at the
   stop, and stuck in the waistband of my mother’s sweatpants was my
   father’s gun. It was not the most secure place (as Plaxico Burress
   learned), but she made it clear that she was ready to defend her
   daughter from anyone who might snatch her off the street.

   This is why it’s impossible for me to be a gun control absolutist. I am
   a single woman living in New York City, and if someone breaks into my
   apartment while I am home, I am going to want a gun to defend myself.
   It’s the quickest way to stop someone. A knife involves approaching an
   assailant and it can be grabbed out of my hand. But I can fire a gun
   across a room and preclude a lifetime of psychological damage, or
   worse, in an instant.

   Why wasn’t the gun in the waistband of my father’s jeans that night?
   Because he was an ex-convict, and if he was caught with a gun in
   zero-tolerance New York, he’d likely be sent back to prison. He’d
   already broken his parole once, right after I was born, and he was so
   afraid of going back to Sing Sing that he took my mother and me across
   the country, where we lived under fake names. When I was five, the FBI
   found us, and when my father returned home a year later, we could be
   ourselves again. I grew up knowing that my father had been in prison,
   but I had no idea why.

   A few months before my parents met me at that bus stop, I’d found his
   criminal record on the Internet. Turns out he’d been in prison for 12
   years before I was born, for murder. Gun murder. He shot a criminal
   informant several times in a park in Brooklyn in 1963. Right before my
   mother died, she confessed that he’d committed several gun murders he’d
   never been arrested for. In 2010, I wrote a book about how I found out
   I was the daughter of a mob enforcer, Never Tell Our Business to
   Strangers.

   It wasn’t until I had been doing the Gun Report for several months that
   it sunk in that the daughter of a man who had taken lives with guns was
   given an opportunity to report on gun violence. Perhaps it was my
   penance. I could atone for the lives my father took. Joe didn’t even
   know of my family history when I took this on. One day I explained it
   to him, and he understood that this was a labor of love.

                                    —-

   Before starting work on Gun Report, I had my own ideas about gun
   violence: Most of it probably resulted from gang activity, I assumed,
   along with the marital domestic shootings we so often read about.

   More than 350 posts and 40,000 deaths later, here is what I learned.

   Gang shootings are prevalent, especially in former hubs of industry now
   in economic decline in Ohio; the Flint/Tri-Cities region of Michigan;
   in Indianapolis and Fort Wayne, Indiana; Newport News, Va.; and
   Milwaukee, Wisconsin. Carjackings and home invasions often appeared in
   my Google news searches. I was surprised to learn that suburbs were a
   magnet for gun violence, perhaps mirroring the housing implosion, which
   decimated the suburbs and propelled people to cities, where there are
   always jobs.

   Not that nation’s largest cities are exempt: Miami, Chicago, St. Louis,
   Detroit, Newark, New Orleans, Philadelphia, and Dallas are notable
   examples. (Less so New York, possibly because of the NYPD’s
   stop-and-frisk policy, which was ruled unconstitutional.) Drive-by
   shootings still plague northern and southern California; Los Angeles,
   Fresno and the entire east side of the state are rife with gang
   activity. Tennessee, Alabama, and Missouri also frequently popped up in
   this regard.

   What was also notable was where the shootings aren’t: Maine, Hawaii,
   Vermont, Wyoming, Montana, and New Hampshire were rarely mentioned in
   the report. Why? Weapons don’t easily flow into Hawaii, surrounded by
   the Pacific, and Montana and Wyoming are sparsely populated, mostly by
   experienced, rural gun owners. But homeowners in these states are also
   armed against home invaders, and as we saw in Montana in May, tragedy
   can result.

   But while half of the shootings I featured were the result of a crime,
   the other half, I was most surprised to learn, resulted from arguments
   — often fueled by alcohol — among friends, neighbors, family members
   and romantic partners. More and more, people are solving their
   differences not with their fists but with guns. Husbands and wives are
   shooting each other, as are sisters and brothers. In many homes across
   America, loaded guns are easily accessible, and children find them,
   accidentally shooting themselves or each other. One hundred children
   died in unintentional shootings in the year after Newtown, which breaks
   down to two every week.

   A year and a half later, you might expect that I’d have a solution to
   the country’s scourge of gun violence. But there is no one answer. It’s
   a favorite talking point of the right, but it’s true: Criminals will
   always find a way to get guns. But a lot of the people I covered
   weren’t criminals until the bullet left the chamber. How do you prevent
   a law-abiding person from obtaining a gun when he or she hasn’t done
   anything illegal yet?

   Perhaps we can solve the problem in pieces. We’re vetted in so many
   areas of society — for instance, we need several points of ID for
   driver’s licenses, plus a written test and behind-the-wheel driver’s
   ed; just try to get an apartment in New York City without a credit
   check, and employer, bank references, and a guarantor. I think we need
   more vetting to get a firearm.

   In Iowa, it’s easier to sell a gun than lemonade. In Arkansas, it takes
   less time to buy a gun than to qualify for food stamps. In Arizona, you
   need a permit to cut hair, but not to carry a concealed weapon. In
   Florida you’re fingerprinted to be a substitute teacher, but not to buy
   or carry a gun. It’s easier to buy an assault weapon than it is to
   vote.

   But in order to obtain a firearm in Japan, which has half the
   population of America and averages about four gun murders per year, you
   must fill out binders full of paperwork, listen to 20 hours of
   lectures, take a written test and a shooting class, pass a criminal
   background check, subject yourself to a physical and psychological
   exam, submit to half a dozen police interviews, and police interviews
   of your friends and family, as well. You are asked to produce a floor
   map of your home and indicate where a firearm will be stored, as well
   as photos of the locks on your gun safe. Approval usually takes a year.
   You need to jump through such extreme hoops to own guns — and can get
   arrested just for firing one — that the Yakuza, the mob in Japan,
   prefers not to use them.

   In Canada, where the right to private gun ownership is not guaranteed
   by law, third-party character references are required to get a gun, and
   licensing authorities conduct interviews with an applicant’s spouse,
   partner, or next of kin before issuing a license. You must pass a
   firearm safety and law class, and a practical training course is
   required — much like driver’s ed. Gun owners must re-apply and
   re-qualify for their firearm license every 5 years — much like a
   driver’s license. But all this vetting doesn’t inhibit gun ownership:
   Canadians can own an unlimited amount of weapons and ammunition, and
   they don’t need to provide a reason for acquiring a gun.

   After the Port Arthur massacre in Australia in 1996, legislation was
   enacted to tighten gun laws. Semi-automatic rifles and pump-action
   shotguns were banned, and you have to provide a reason to obtain all
   other firearms. The government held a gun buyback, netting 650,000 of
   newly illegal weapons from existing owners. Sure, some politicians lost
   their jobs by enacting gun control, but the laws stand, and there
   hasn’t been a mass shooting there since. Some estimate that the buyback
   has prevented 200 deaths a year. And perhaps most importantly, gun
   suicides declined. In America, 60 percent of adult firearm deaths are a
   result of suicide.

   These are strictures that Second Amendment absolutists would balk at,
   but I don’t think the pro-gun crowd honestly wants a crazy person to
   get hold of guns. Even Antonin Scalia, the strict constuctionist
   Supreme Court judge, believes that there are limits on gun ownership.

   “Like most rights, the Second Amendment right is not unlimited,” he
   wrote in District of Columbia v. Heller. “It is not a right to keep and
   carry any weapon whatsoever in any manner whatsoever and for whatever
   purpose.”

   Universal background checks are something most Americans already
   support. Ensuring that gun checks are cross-referenced with mental
   health records in every state is a must. When Second Amendment
   advocates say we should enforce the laws already in place, they’re
   right. Montana and South Dakota submitted only three mental health
   records to the National Instant Criminal Background Check System in
   2012. North Dakota and Massachusetts turned in one, and Rhode Island
   submitted none.

   Smart guns that only activate for their owner would reduce the chance
   that a child or an intruder could discharge them. Armatix, a German
   company, offers a gun that operates only when the owner is wearing a
   corresponding wristwatch. But the National Rifle Association has
   vigorously opposed such technology, and the two vendors who tried to
   market smart guns in America were harassed and received death threats
   from Second Amendment extremists, so they pulled the guns from their
   shelves.

   A favorite argument of the gun-rights crowd is that nothing stops a bad
   guy with a gun more effectively than a good guy with a gun. I have come
   to believe that people who think they are going to shoot the bad guys —
   which sometimes does happen — are influenced by movies. Often their own
   guns are grabbed by the bad guys and used against them, especially
   during home invasions. In my daily reports, I made sure to include
   police officers accidentally shooting themselves and each other. If
   highly trained people have accidents, how can civilians be expected to
   be perfect marksmen during a high-stress robbery?

   Maybe a solution to gun violence is one that Chris Rock cheekily
   proposed during a stand-up routine 15 years ago: bullet control. But
   it’s not such a bad idea. In 1993, New York Senator Daniel Patrick
   Moynihan floated the idea of an ammunition tax. In California last
   year, a nickel-per-bullet tax was briefly considered, and in New
   Jersey, lawmakers sought to slap an additional 5 percent sales tax on
   guns and ammo. Both bills appear to be dead.

   Efforts to curb gun violence by elected officials has done little to
   mitigate the damage. The NY SAFE Act, written in response to the
   Newtown massacre, instituted background checks for ammunition
   purchases, required that assault weapons be registered and broadened
   the definition of “assault weapon.” But gunmakers are modifying AR-15
   and AR-10 rifles to circumvent the new regulations, and they are just
   as deadly.

   In fact, when it comes to gun control, many state politicians are
   moving in the opposite direction: Kansas and Missouri have passed bills
   that nullify local and federal gun laws in favor of more relaxed state
   laws.

   Efforts to research the problem were hamstrung in 1996, when the NRA
   successfully lobbied the federal government to freeze funding for CDC
   research into gun violence. After Newtown, President Obama issued an
   executive action that replenished the funding, and though it is meager,
   we should see some results soon. In the meantime, legislators are
   starting to fill in the gaps, Congresswomen Robin Kelly, who represents
   part of Chicago, recently released her own report on gun violence.

   With more than 300 million guns already in circulation in America, and
   the right to carry a concealed weapon now legal in every state, it will
   be impossible to wipe out gun violence completely. But we can certainly
   reduce some deaths, and that is better than nothing. Let’s not let the
   perfect be the enemy of the good.

                                    —-

   A few days after the plug was pulled on the Gun Report in early June,
   there were school shootings in Portland and Seattle, and two officers
   in Las Vegas, along with another man, were shot and killed by
   anti-government extremists who then committed suicide. To be silenced
   while all this was going on was excruciating. I burned at not being
   able to cover it.

   But there will always be shootings. I could write gun reports until the
   end of my natural life, and given the apathy in Congress, the sheer
   volume will never diminish. I am not even sure much will change within
   the next few generations. All we can do — journalists, gunshot victims
   and their families, people who care — is continue the drumbeat. We can
   mark every death and remember every victim. It’s not a solution, but
   it’s something.

About the Author

   PA cops making arrest ( NBC10)
   Next on Raw Story >
   WATCH: PA police officers burst into home, arrest woman for filming
   them with cellphone
   By commenting, you agree to our terms of service and to abide by our
   commenting policy.
   Read Comments - Join the Discussion

New Stories

     * WATCH: PA police officers burst into home, arrest woman for filming
       them with cellphone
       0 [shares.jpg]
     * Blacks six times more likely to be busted for marijuana possession
       in FL counties: report
       0 [shares.jpg]
     * Ferguson protests continue as authorities seek suspects in
       shootings of two officers
       0 [shares.jpg]
     * Facing tax shortfall, Kansas approves online sex toy auction to
       recoup lost tax revenue
       0 [shares.jpg]
     * Researchers use ‘wearable technology’ investigate obesity at
       Florida high school
       0 [shares.jpg]
     * Family of five found dead of unknown causes in Utah home
       0 [shares.jpg]

   Sponsored Links

   [schultz_raw_250x300.gif]

   IFRAME:
   //www.youtube.com/embed/videoseries?list=PLTpcK80irdQhvmF3fmROeN5YAmsNR
   sYk1

New Videos

     * WATCH: PA police officers burst into home, arrest woman for filming
       them with cellphone
       0 [shares.jpg]
     * 2-year-old discovers loaded handgun with safety off in Florida
       rental car
       0 [shares.jpg]
     * Fox host tells school to ‘stand up’ to atheists: ‘Salvation’
       T-shirts are ‘harmless’
       0 [shares.jpg]
     * Watch: Ingraham loses it after Bush aide says Reagan’s attorney
       general worse than Holder
       0 [shares.jpg]

   SEE ALL RAW STORIES

   [rs-footer-email-icon.gif] SIGN UP FOR OUR NEWSLETTER
   Get the best of Raw Story, delivered daily
   Email Address _________________________
   ____________________
   SIGN UP

   Google+
