
   Donate Now Donate Now

   Truthout
   Monday, 29 September 2014 / TRUTH-OUT.ORG
     * For Oil and Gas Companies, Rigging Seems to Involve Wages, Too
       Oil and gas workers - men and women often performing high-risk jobs
       - are routinely being underpaid.
     * Fact-Checking Feinstein on the Assault Weapons Ban
       The researcher behind the key statistic Feinstein cites says it's
       an outdated figure that was based on a false assumption.
     *

   (BUTTON)
     * Home
          + News
          + Opinion
          + Video
          + Art
               o Cartoons
               o Graphic Journalism
               o Truthout on Flickr
     * BuzzFlash
          + Buzzflash Headlines
          + Buzzflash Commentary
     * Speakout
     * Progressive Picks
     * About Us
          + Submission Guidelines
          + Contact
          + Newsletter Sign-Up
          + Job Openings
     * Donate

     * Enter Search Text_______________________ OK
       Email to a friend
       Join our Newsletter_ Send

Monsanto's Herbicide Linked to Fatal Kidney Disease Epidemic: Could It Topple
the Company?

   Thursday, 10 July 2014 09:18 By Jeff Ritterman, M.D., Truthout | News
   Analysis
     *
     * font size decrease font size decrease font size increase font size
       increase font size
     * Print
     *

   2014 710 mons fw (Photo courtesy of Vivien Feyer)

   Also see: Dahr Jamail | Salvadoran Farmers Successfully Oppose the Use
   of Monsanto Seeds
   Truthout Interviews Dr. Jeff Ritterman on Roundup and Chronic Kidney
   Disease

   Monsanto's herbicide Roundup has been linked to a mysterious fatal
   kidney disease epidemic that has appeared in Central America, Sri Lanka
   and India.
   For years, scientists have been trying to unravel the mystery of a
   chronic kidney disease epidemic that has hit Central America, India and
   Sri Lanka. The disease occurs in poor peasant farmers who do hard
   physical work in hot climes. In each instance, the farmers have been
   exposed to herbicides and to heavy metals. The disease is known as
   CKDu, for Chronic Kidney Disease of unknown etiology. The "u"
   differentiates this illness from other chronic kidney diseases where
   the cause is known. Very few Western medical practitioners are even
   aware of CKDu, despite the terrible toll it has taken on poor farmers
   from El Salvador to South Asia.

   Dr. Catharina Wesseling, the regional director for the Program on Work
   and Health (SALTRA) in Central America, which pioneered the initial
   studies of the region's unsolved outbreak, put it this way,
   "Nephrologists and public health professionals from wealthy countries
   are mostly either unfamiliar with the problem or skeptical whether it
   even exists."

   Dr. Wesseling was being diplomatic. At a 2011 health summit in Mexico
   City, the United States beat back a proposal by Central American
   nations that would have listed CKDu as a top priority for the Americas.

   David McQueen, a US delegate from the Centers for Disease Control and
   Prevention who has since retired from the agency, explained the US
   position.

   "The idea was to keep the focus on the key big risk factors that we
   could control and the major causes of death: heart disease, cancer and
   diabetes. And we felt, the position we were taking, that CKD was
   included."

   The United States was wrong. The delegates from Central America were
   correct. CKDu is a new form of illness. This kidney ailment does not
   stem from diabetes, hypertension or other diet-related risk factors.
   Unlike the kidney disease found in diabetes or hypertension, the kidney
   tubules are a major site of injury in CKDu, suggesting a toxic
   etiology.

   2014 710 mons 2 Salvadoran farmer returning from the fields, Palo
   Grande, El Salvador. Photo courtesy of Vivien Feyer.CKDu is now the
   second leading cause of mortality among men in El Salvador. This small,
   densely populated Central American country now has the highest
   overall mortality rate from kidney disease in the world. Neighboring
   Honduras and Nicaragua also have extremely high rates of kidney
   disease mortality. In El Salvador and Nicaragua, more men
   are dying from CKDu than from HIV/AIDS, diabetes, and leukemia
   combined. In one patch of rural Nicaragua, so many men have died that
   the community is called "The Island of the Widows."

   In addition to Central America, India and Sri Lanka have been hit hard
   by the epidemic. In Sri Lanka, over 20,000 people have died from CKDu
   in the past two decades. In the Indian state of Andhra Pradesh, more
   than 1,500 have been treated for the ailment since 2007. Given the
   rarity of dialysis and kidney transplantation in these regions, most
   who suffer from CKDu will die from their kidney disease.

   2014 710 mons 3 Mural celebrating traditional agrarian life, Juayua, El
   Salvador. Photo courtesy of Vivien Feyer.

   In an investigation worthy of the great Sherlock Holmes, a scientific
   sleuth from Sri Lanka, Dr. Channa Jayasumana, and his two colleagues,
   Dr. Sarath Gunatilake and Dr. Priyantha Senanayake, have put forward a
   unifying hypothesis that could explain the origin of the disease. They
   reasoned that the offending agent had to have been introduced into Sri
   Lanka within the last 30 years, since the first cases appeared in the
   mid-1990s. The chemical also needed to be able to form stable complexes
   with the metals in hard water and to act as a shield, protecting those
   metals from metabolism by the liver. The compound would also need to
   act as a carrier and be able to deliver the metals to the kidney.

   We know that political changes in Sri Lanka in the late 1970s led to
   the introduction of agrochemicals, especially in rice farming. The
   researchers looked for likely suspects. Everything pointed
   to glyphosate. This herbicide is used in abundance in Sri Lanka.
   Earlier studies had shown that once glyphosate binds with metals, the
   glyphosate-metal complex can last for decades in the soil.

   Glyphosate was not originally designed for use as an herbicide.
   Patented by the Stauffer Chemical Company in 1964, it was introduced as
   a chelating agent. It avidly binds to metals. Glyphosate was first used
   as a descaling agent to clean out mineral deposits from the pipes in
   boilers and other hot water systems.

   It is this chelating property that allows glyphosate to form complexes
   with the arsenic, cadmium and other heavy metals found in the
   groundwater and soil in Central America, India and Sri Lanka. The
   glyphosate-heavy metal complex can enter the human body in a variety of
   ways. The complex can be ingested, inhaled or absorbed through the
   skin. Glyphosate acts like a Trojan horse, allowing the bound heavy
   metal to avoid detection by the liver, since the glyphosate occupies
   the binding sites that the liver would normally latch onto. The
   glyphosate-heavy metal complex reaches the kidney tubules, where the
   high acidity allows the metal to break free of the glyphosate. The
   cadmium or arsenic then damages the kidney tubules and other parts of
   the kidneys, ultimately resulting in kidney failure and, most often,
   death.

   At this point, this elegant theory advanced by Dr. Jayasumana and
   colleagues can only be considered hypothesis-generating. Further
   scientific studies will need to confirm the hypothesis that CKDu is
   indeed due to glyphosate-heavy metal toxicity to the kidney tubules.
   For the present, this may be the best explanation for the epidemic.

   Another explanation is that heat stress may be the cause, or
   a combination of heat stress and chemical toxicity. Monsanto, of
   course, is standing behind glyphosate and disputing the claim that it
   plays any role whatsoever in the genesis of CKDu.

   While the exact cause of CKDu has not been proven conclusively, both
   Sri Lanka and El Salvador have invoked the precautionary principle. El
   Salvador banned glyphosate in September 2013 and is currently looking
   for safer alternatives. Sri Lanka banned glyphosate in March of this
   year because of concerns about CKDu.

   2014 710 mons 4 Mural celebrating traditional agrarian life, Palo
   Grande, El Salvador. Photo courtesy of Vivien Feyer.

   Glyphosate has had an interesting history. After its initial use as a
   descaling agent by Stauffer Chemical, scientists at Monsanto discovered
   its herbicidal qualities. Monsanto patented glyphosate as an herbicide
   in the 1970s, and has marketed it as "Roundup" since 1974. Monsanto
   retained exclusive rights until 2000, when the patent expired. By 2005,
   Monsanto's glyphosate products were registered in more than 130
   countries for use in more than 100 crops. As of 2013, glyphosate was
   the world's largest selling herbicide.

   Glyphosate's popularity has been due, in part, to the perception that
   it is extremely safe. The Monsanto website claims:

     Glyphosate binds tightly to most types of soil so it is not
     available for uptake by roots of nearby plants. It works by
     disrupting a plant enzyme involved in the production of amino acids
     that are essential to plant growth. The enzyme, EPSP synthase, is
     not present in humans or animals, contributing to the low risk to
     human health from the use of glyphosate according to label
     directions.

   Because of glyphosate's reputation for both safety and
   effectiveness, John Franz, who discovered glyphosate's usefulness as a
   herbicide, received the National Medal of Technology in 1987. Franz
   also received the American Chemical Society's Carothers Award in 1989,
   and the American Section of the Society of Chemical Industry's Perkins
   Medal in 1990. In 2007, he was inducted into the United States'
   Inventor's Hall of Fame for his work on the herbicide. Roundup was
   named one of the "Top 10 Products That Changed the Face of
   Agriculture" by the magazine Farm Chemicals in 1994.

   Not everyone agrees with this perception of glyphosate's safety. The
   first "Roundup resistant" GMO crops, soybeans, were introduced by
   Monsanto in 1996. The same year, the first glyphosate resistant
   weeds began to emerge. Farmers responded by using increasingly toxic
   herbicides to deal with the new super weeds that had developed
   glyphosate resistance.

   In addition to the concern about the emergence of super weeds,
   a study in rats demonstrated that low levels of glyphosate induced
   severe hormone-dependent mammary, hepatic, and kidney disturbances.
   Recently two activist groups, Moms Across America and Thinking Moms
   Revolution, asked the US Environmental Protection Agency (EPA)
   to recall Monsanto's Roundup, citing a host of adverse health impacts
   in their children from the herbicide, including failure to thrive,
   leaky gut syndrome, autism and food allergies.

   Glyphosate is no ordinary herbicide. Besides being the most used
   herbicide on earth, it is also the central pillar of Monsanto's temple.
   Most of Monsanto's seeds, including soy, corn, canola, alfalfa, cotton,
   sugar beets and sorghum, are glyphosate resistant. As of 2009,
   Monsanto's Roundup (glyphosate) products, which include its GMO seeds,
   represented about half of Monsanto's yearly revenue. This reliance on
   glyphosate products makes Monsanto extremely vulnerable to research
   challenging the herbicide's safety.

   Glyphosate-resistant seeds are engineered to allow the farmer to drench
   his fields in the herbicide to kill off all of the weeds. The
   glyphosate resistant crop can then be harvested. But if the combination
   of glyphosate and the heavy metals found in the groundwater or the soil
   destroys the farmer's kidneys in the process, the whole house of cards
   falls apart. This may be what is happening now.

   An ugly confrontation has been unfolding in El Salvador. The US
   government has been pressuring El Salvador to buy GMO seeds from
   Monsanto rather than indigenous seeds from their own farmers. The US
   has threatened to withhold almost $300 million in aid unless El
   Salvador purchases Monsanto's GMO seeds. The GMO seeds are more
   expensive. They are not adapted to the Salvadoran climate or soil.

   The only "advantage" of Monsanto's GMO seeds is their glyphosate
   resistance. Now that glyphosate has been shown to be a possible, and
   perhaps likely, cause of CKDu, that "advantage" no longer exists.

   2014 710 mons 5 Mural, Concepcion de Ataco, El Salvador. Photo courtesy
   of Vivien Feyer.

   What is the message from the United States to El Salvador exactly?
   Perhaps the kindest explanation is that the United States is unaware
   that glyphosate may be the cause of the fatal kidney disease epidemic
   in El Salvador and that the government sincerely believes that the GMO
   seeds will provide a better yield. If so, a sad mixture of ignorance
   and arrogance is at the heart of this foreign policy blunder. A less
   kind interpretation would suggest that the government puts Monsanto's
   profits above concerns about the economy, environment and health of the
   Salvadorans. This view would suggest that a tragic mix of greed and
   callous disregard for the Salvadorans is behind US policy.

   Unfortunately, there is evidence to support the latter view. The United
   States seems to be completely behind Monsanto, regardless of any
   science questioning the safety of its products. Cables released by
   WikiLeaks show that US diplomats around the world are pushing GMO crops
   as a strategic government and commercial imperative. The cables also
   reveal instructions to punish any foreign countries trying to ban GMO
   crops.

   Whatever the explanation, pressuring El Salvador, or any country, to
   buy GMO seeds from Monsanto is a tragic mistake. It is foreign policy
   not worthy of America. Let's change it. Let's base our foreign and
   domestic policies on human rights, environmental stewardship, health
   and equity.

   Post script: After articles about the seed dispute appeared in the
   media, The New York Times reported that the United States has reversed
   its position and will stop pressuring El Salvador to buy Monsanto's
   seeds. Thus far, the aid money has not been released.
   Copyright, Truthout. May not be reprinted without permission.

Jeff Ritterman, M.D.

   Jeff Ritterman, M.D. is vice president of the board of directors of the
   SF Bay Chapter of Physicians for Social Responsibility. He is the
   retired chief of cardiology at Kaiser Richmond and a former Richmond,
   California, city councilman. Follow him on Twitter @JeffRitterman.

Related Stories

   Monsanto and Gates Foundation Push GE Crops on Africa
   By Mike Ludwig, Truthout | Report
   Monsanto Found Guilty of Chemical Poisoning in France
   By Anthony Gucciardi, Natural Society | Report
   Monsanto and Big Food Losing the GMO and "Natural" Food Fight
   By Ronnie Cummins, Organic Consumers Association | News Analysis
     __________________________________________________________________

   Show Comments

   Hide Comments
   View the discussion thread. blog comments powered by Disqus
   back to top
   (BUTTON) Read more
   GET DAILY TRUTHOUT UPDATES
   Enter your email add Submit

   FOLLOW TRUTHOUT tog torss tot tofb

   IFRAME:
   //www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%
   2FTruthout.org&send=false&layout=button_count&width=120&show_faces=fals
   e&action=like&colorscheme=light&font&height=21&appId=174773479325394

   Follow @truthout
   This Changes Everything

Latest Stories

     * Uruguay's Legalization of Marijuana Makes Sense in a Senseless Drug
       War
       By Benjamin Dangl, teleSUR | News Analysis
     * Truthout Interviews Featuring Paul Armentano on Marijuana, Alcohol
       and the Law
       By Ted Asregadoo, Truthout | Video Interview
     * It's Time for a Real Debate on Reader Privacy
       By Josh Stearns, Freedom of the Press Foundation | Op-Ed
     * Pledges Can Work, But It Will Take International Law to Fight
       Climate Change
       By Luke Kemp, The Conversation | Op-Ed
     *

Buzzflash Headlines

     * Why Obama’s Assurance of "No Boots on the Ground" Isn’t So
       Reassuring - Washington Post
     * Hong Kong Police Use Teargas and Pepper Spray to Disperse
       Protesters - The Guardian
     * Police Officer Shot In Ferguson As Protests Continue - Crooks and
       Liars

   Peace Calendar
   Truthout Progressive Picks

Featured Videos

     * Freed After Hunger Strike, Egyptian Journalist in US to Campaign
       for Jailed Colleagues
    Freed After Hunger Strike, Egyptian Journalist in US to Campaign for
       Jailed Colleagues
       By Amy Goodman and Juan Gonzalez, Democracy Now! | Video Interview
     * "What's Possible," a New Film for World Leaders on the Urgency of
       Global Warming
    "What's Possible," a New Film for World Leaders on the Urgency of
       Global Warming
       By Bill Moyers, Moyers & Company | Video Report
     * No Charges in Ohio Police Killing of John Crawford as Walmart Video
       Contradicts 911 Caller Account
    No Charges in Ohio Police Killing of John Crawford as Walmart Video
       Contradicts 911 Caller Account
       By Amy Goodman and Juan Gonzalez, Democracy Now! | Video Interview
     *

Monsanto's Herbicide Linked to Fatal Kidney Disease Epidemic: Could It Topple
the Company?

   Thursday, 10 July 2014 09:18 By Jeff Ritterman, M.D., Truthout | News
   Analysis
     *
     * font size decrease font size decrease font size increase font size
       increase font size
     * Print
     *

   2014 710 mons fw (Photo courtesy of Vivien Feyer)

   Also see: Dahr Jamail | Salvadoran Farmers Successfully Oppose the Use
   of Monsanto Seeds
   Truthout Interviews Dr. Jeff Ritterman on Roundup and Chronic Kidney
   Disease

   Monsanto's herbicide Roundup has been linked to a mysterious fatal
   kidney disease epidemic that has appeared in Central America, Sri Lanka
   and India.
   For years, scientists have been trying to unravel the mystery of a
   chronic kidney disease epidemic that has hit Central America, India and
   Sri Lanka. The disease occurs in poor peasant farmers who do hard
   physical work in hot climes. In each instance, the farmers have been
   exposed to herbicides and to heavy metals. The disease is known as
   CKDu, for Chronic Kidney Disease of unknown etiology. The "u"
   differentiates this illness from other chronic kidney diseases where
   the cause is known. Very few Western medical practitioners are even
   aware of CKDu, despite the terrible toll it has taken on poor farmers
   from El Salvador to South Asia.

   Dr. Catharina Wesseling, the regional director for the Program on Work
   and Health (SALTRA) in Central America, which pioneered the initial
   studies of the region's unsolved outbreak, put it this way,
   "Nephrologists and public health professionals from wealthy countries
   are mostly either unfamiliar with the problem or skeptical whether it
   even exists."

   Dr. Wesseling was being diplomatic. At a 2011 health summit in Mexico
   City, the United States beat back a proposal by Central American
   nations that would have listed CKDu as a top priority for the Americas.

   David McQueen, a US delegate from the Centers for Disease Control and
   Prevention who has since retired from the agency, explained the US
   position.

   "The idea was to keep the focus on the key big risk factors that we
   could control and the major causes of death: heart disease, cancer and
   diabetes. And we felt, the position we were taking, that CKD was
   included."

   The United States was wrong. The delegates from Central America were
   correct. CKDu is a new form of illness. This kidney ailment does not
   stem from diabetes, hypertension or other diet-related risk factors.
   Unlike the kidney disease found in diabetes or hypertension, the kidney
   tubules are a major site of injury in CKDu, suggesting a toxic
   etiology.

   2014 710 mons 2 Salvadoran farmer returning from the fields, Palo
   Grande, El Salvador. Photo courtesy of Vivien Feyer.CKDu is now the
   second leading cause of mortality among men in El Salvador. This small,
   densely populated Central American country now has the highest
   overall mortality rate from kidney disease in the world. Neighboring
   Honduras and Nicaragua also have extremely high rates of kidney
   disease mortality. In El Salvador and Nicaragua, more men
   are dying from CKDu than from HIV/AIDS, diabetes, and leukemia
   combined. In one patch of rural Nicaragua, so many men have died that
   the community is called "The Island of the Widows."

   In addition to Central America, India and Sri Lanka have been hit hard
   by the epidemic. In Sri Lanka, over 20,000 people have died from CKDu
   in the past two decades. In the Indian state of Andhra Pradesh, more
   than 1,500 have been treated for the ailment since 2007. Given the
   rarity of dialysis and kidney transplantation in these regions, most
   who suffer from CKDu will die from their kidney disease.

   2014 710 mons 3 Mural celebrating traditional agrarian life, Juayua, El
   Salvador. Photo courtesy of Vivien Feyer.

   In an investigation worthy of the great Sherlock Holmes, a scientific
   sleuth from Sri Lanka, Dr. Channa Jayasumana, and his two colleagues,
   Dr. Sarath Gunatilake and Dr. Priyantha Senanayake, have put forward a
   unifying hypothesis that could explain the origin of the disease. They
   reasoned that the offending agent had to have been introduced into Sri
   Lanka within the last 30 years, since the first cases appeared in the
   mid-1990s. The chemical also needed to be able to form stable complexes
   with the metals in hard water and to act as a shield, protecting those
   metals from metabolism by the liver. The compound would also need to
   act as a carrier and be able to deliver the metals to the kidney.

   We know that political changes in Sri Lanka in the late 1970s led to
   the introduction of agrochemicals, especially in rice farming. The
   researchers looked for likely suspects. Everything pointed
   to glyphosate. This herbicide is used in abundance in Sri Lanka.
   Earlier studies had shown that once glyphosate binds with metals, the
   glyphosate-metal complex can last for decades in the soil.

   Glyphosate was not originally designed for use as an herbicide.
   Patented by the Stauffer Chemical Company in 1964, it was introduced as
   a chelating agent. It avidly binds to metals. Glyphosate was first used
   as a descaling agent to clean out mineral deposits from the pipes in
   boilers and other hot water systems.

   It is this chelating property that allows glyphosate to form complexes
   with the arsenic, cadmium and other heavy metals found in the
   groundwater and soil in Central America, India and Sri Lanka. The
   glyphosate-heavy metal complex can enter the human body in a variety of
   ways. The complex can be ingested, inhaled or absorbed through the
   skin. Glyphosate acts like a Trojan horse, allowing the bound heavy
   metal to avoid detection by the liver, since the glyphosate occupies
   the binding sites that the liver would normally latch onto. The
   glyphosate-heavy metal complex reaches the kidney tubules, where the
   high acidity allows the metal to break free of the glyphosate. The
   cadmium or arsenic then damages the kidney tubules and other parts of
   the kidneys, ultimately resulting in kidney failure and, most often,
   death.

   At this point, this elegant theory advanced by Dr. Jayasumana and
   colleagues can only be considered hypothesis-generating. Further
   scientific studies will need to confirm the hypothesis that CKDu is
   indeed due to glyphosate-heavy metal toxicity to the kidney tubules.
   For the present, this may be the best explanation for the epidemic.

   Another explanation is that heat stress may be the cause, or
   a combination of heat stress and chemical toxicity. Monsanto, of
   course, is standing behind glyphosate and disputing the claim that it
   plays any role whatsoever in the genesis of CKDu.

   While the exact cause of CKDu has not been proven conclusively, both
   Sri Lanka and El Salvador have invoked the precautionary principle. El
   Salvador banned glyphosate in September 2013 and is currently looking
   for safer alternatives. Sri Lanka banned glyphosate in March of this
   year because of concerns about CKDu.

   2014 710 mons 4 Mural celebrating traditional agrarian life, Palo
   Grande, El Salvador. Photo courtesy of Vivien Feyer.

   Glyphosate has had an interesting history. After its initial use as a
   descaling agent by Stauffer Chemical, scientists at Monsanto discovered
   its herbicidal qualities. Monsanto patented glyphosate as an herbicide
   in the 1970s, and has marketed it as "Roundup" since 1974. Monsanto
   retained exclusive rights until 2000, when the patent expired. By 2005,
   Monsanto's glyphosate products were registered in more than 130
   countries for use in more than 100 crops. As of 2013, glyphosate was
   the world's largest selling herbicide.

   Glyphosate's popularity has been due, in part, to the perception that
   it is extremely safe. The Monsanto website claims:

     Glyphosate binds tightly to most types of soil so it is not
     available for uptake by roots of nearby plants. It works by
     disrupting a plant enzyme involved in the production of amino acids
     that are essential to plant growth. The enzyme, EPSP synthase, is
     not present in humans or animals, contributing to the low risk to
     human health from the use of glyphosate according to label
     directions.

   Because of glyphosate's reputation for both safety and
   effectiveness, John Franz, who discovered glyphosate's usefulness as a
   herbicide, received the National Medal of Technology in 1987. Franz
   also received the American Chemical Society's Carothers Award in 1989,
   and the American Section of the Society of Chemical Industry's Perkins
   Medal in 1990. In 2007, he was inducted into the United States'
   Inventor's Hall of Fame for his work on the herbicide. Roundup was
   named one of the "Top 10 Products That Changed the Face of
   Agriculture" by the magazine Farm Chemicals in 1994.

   Not everyone agrees with this perception of glyphosate's safety. The
   first "Roundup resistant" GMO crops, soybeans, were introduced by
   Monsanto in 1996. The same year, the first glyphosate resistant
   weeds began to emerge. Farmers responded by using increasingly toxic
   herbicides to deal with the new super weeds that had developed
   glyphosate resistance.

   In addition to the concern about the emergence of super weeds,
   a study in rats demonstrated that low levels of glyphosate induced
   severe hormone-dependent mammary, hepatic, and kidney disturbances.
   Recently two activist groups, Moms Across America and Thinking Moms
   Revolution, asked the US Environmental Protection Agency (EPA)
   to recall Monsanto's Roundup, citing a host of adverse health impacts
   in their children from the herbicide, including failure to thrive,
   leaky gut syndrome, autism and food allergies.

   Glyphosate is no ordinary herbicide. Besides being the most used
   herbicide on earth, it is also the central pillar of Monsanto's temple.
   Most of Monsanto's seeds, including soy, corn, canola, alfalfa, cotton,
   sugar beets and sorghum, are glyphosate resistant. As of 2009,
   Monsanto's Roundup (glyphosate) products, which include its GMO seeds,
   represented about half of Monsanto's yearly revenue. This reliance on
   glyphosate products makes Monsanto extremely vulnerable to research
   challenging the herbicide's safety.

   Glyphosate-resistant seeds are engineered to allow the farmer to drench
   his fields in the herbicide to kill off all of the weeds. The
   glyphosate resistant crop can then be harvested. But if the combination
   of glyphosate and the heavy metals found in the groundwater or the soil
   destroys the farmer's kidneys in the process, the whole house of cards
   falls apart. This may be what is happening now.

   An ugly confrontation has been unfolding in El Salvador. The US
   government has been pressuring El Salvador to buy GMO seeds from
   Monsanto rather than indigenous seeds from their own farmers. The US
   has threatened to withhold almost $300 million in aid unless El
   Salvador purchases Monsanto's GMO seeds. The GMO seeds are more
   expensive. They are not adapted to the Salvadoran climate or soil.

   The only "advantage" of Monsanto's GMO seeds is their glyphosate
   resistance. Now that glyphosate has been shown to be a possible, and
   perhaps likely, cause of CKDu, that "advantage" no longer exists.

   2014 710 mons 5 Mural, Concepcion de Ataco, El Salvador. Photo courtesy
   of Vivien Feyer.

   What is the message from the United States to El Salvador exactly?
   Perhaps the kindest explanation is that the United States is unaware
   that glyphosate may be the cause of the fatal kidney disease epidemic
   in El Salvador and that the government sincerely believes that the GMO
   seeds will provide a better yield. If so, a sad mixture of ignorance
   and arrogance is at the heart of this foreign policy blunder. A less
   kind interpretation would suggest that the government puts Monsanto's
   profits above concerns about the economy, environment and health of the
   Salvadorans. This view would suggest that a tragic mix of greed and
   callous disregard for the Salvadorans is behind US policy.

   Unfortunately, there is evidence to support the latter view. The United
   States seems to be completely behind Monsanto, regardless of any
   science questioning the safety of its products. Cables released by
   WikiLeaks show that US diplomats around the world are pushing GMO crops
   as a strategic government and commercial imperative. The cables also
   reveal instructions to punish any foreign countries trying to ban GMO
   crops.

   Whatever the explanation, pressuring El Salvador, or any country, to
   buy GMO seeds from Monsanto is a tragic mistake. It is foreign policy
   not worthy of America. Let's change it. Let's base our foreign and
   domestic policies on human rights, environmental stewardship, health
   and equity.

   Post script: After articles about the seed dispute appeared in the
   media, The New York Times reported that the United States has reversed
   its position and will stop pressuring El Salvador to buy Monsanto's
   seeds. Thus far, the aid money has not been released.
   Copyright, Truthout. May not be reprinted without permission.

Jeff Ritterman, M.D.

   Jeff Ritterman, M.D. is vice president of the board of directors of the
   SF Bay Chapter of Physicians for Social Responsibility. He is the
   retired chief of cardiology at Kaiser Richmond and a former Richmond,
   California, city councilman. Follow him on Twitter @JeffRitterman.

Related Stories

   Monsanto and Gates Foundation Push GE Crops on Africa
   By Mike Ludwig, Truthout | Report
   Monsanto Found Guilty of Chemical Poisoning in France
   By Anthony Gucciardi, Natural Society | Report
   Monsanto and Big Food Losing the GMO and "Natural" Food Fight
   By Ronnie Cummins, Organic Consumers Association | News Analysis
     __________________________________________________________________

   Show Comments

   Hide Comments
   View the discussion thread. blog comments powered by Disqus
   back to top

   © 2014 Truthout
