   #Google Play alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate alternate
   alternate alternate alternate alternate alternate alternate

   Search Images Maps Play YouTube News Gmail Drive More »

     * Apps
          + My apps
          + Shop
          +
          + Games
          + Editors' Choice
     * Movies & TV
          + My movies & TV
          + Shop
          +
          + Movies
          + TV
          + Studios
          + Networks
     * Music
          + My music
          + Shop
     * Books
          + My books
          + Shop
          +
          + Textbooks
     * Newsstand
          + My newsstand
          + Shop
     * Devices
          + Shop
     * Store
     *
          + My Play activity
          + My wishlist
          + (BUTTON) Redeem
          + Buy gift card
          + (BUTTON) Buy Google Play credit
     *

   (BUTTON)
   (BUTTON) Categories
   Categories________
     *
          +
          +
          + Books & Reference
          + Business
          + Comics
          + Communication
          + Education
          + Entertainment
          + Finance
          + Health & Fitness
          + Libraries & Demo
          + Lifestyle
          + Live Wallpaper
          + Media & Video
          + Medical
          + Music & Audio
          + News & Magazines
          + Personalization
          + Photography
          + Productivity
          + Shopping
          + Social
          + Sports
          + Tools
          + Transportation
          + Travel & Local
          + Weather
          + Widgets
     *
          + Games
          +
          + Action
          + Adventure
          + Arcade
          + Board
          + Card
          + Casino
          + Casual
          + Educational
          + Family
          + Music
          + Puzzle
          + Racing
          + Role Playing
          + Simulation
          + Sports
          + Strategy
          + Trivia
          + Word

   (BUTTON)
   (BUTTON)
   (BUTTON)
   Home
   (BUTTON)
   (BUTTON)
   Top Charts
   (BUTTON)
   (BUTTON)
   New Releases
   (BUTTON)
   (BUTTON)
   (BUTTON)
   (BUTTON)
   (BUTTON)
   (BUTTON)
   __________________
     *
       My orders (BUTTON)
     *
       Settings (BUTTON)
     *
       Android Device Manager (BUTTON)

   (BUTTON)

   Cover art
   Timehop
   Timehop
   - September 19, 2014
   Social
   1
   (BUTTON)
   Install Listen Read Device Only Added (BUTTON) Watch Installed
   (BUTTON)
   Add to Wishlist
   Adding...
   Added to Wishlist
   Remove
   Removing...
   Loading device compatibility...
   (36,199)

   Timehop - screenshot thumbnail Timehop - screenshot thumbnail Timehop -
   screenshot thumbnail Timehop - screenshot thumbnail Timehop -
   screenshot thumbnail Timehop - screenshot thumbnail
   Timehop - screenshot
   Timehop - screenshot
   Timehop - screenshot
   Timehop - screenshot
   Timehop - screenshot
   Timehop - screenshot

   Description
   (Requires Facebook Login)
   Timehop helps you celebrate the best moments of the past. It's like
   #tbt every day!

   What were you doing a year ago today? Two years? Three years? Timehop
   brings together your old photos and posts from your Phone, Facebook,
   Instagram, Twitter, and Foursquare and replays your past a day at a
   time.

   You'll quickly fall in love with checking your daily Timehop. Give it a
   try today!
   (BUTTON) Read more (BUTTON)

   You must install this app before submitting a review.
   Google Play reviews now use Google+ so it's easier to see opinions from
   people you care about. New reviews will be publicly linked to your
   Google+ profile. Your name on previous reviews now appears as "A Google
   User".
   Sign up for Google+
   Google Play reviews now use Google+ so it's easier to see opinions from
   people you care about. New reviews will be publicly linked to your
   Google+ profile. Your name on previous reviews now appears as "A Google
   User".
   (BUTTON) Continue
   Write a review
   ____________________

   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   (BUTTON) (BUTTON) (BUTTON) (BUTTON) (BUTTON)
   (BUTTON) Submit Review
   My review
   (BUTTON)
   Review from

Reviews

   Helpfulness
   Newest
   Rating
   Helpfulness
   (BUTTON) Write a Review
   4.1
   36,199 total
   5 18,580
   4 8,917
   3 4,619
   2 1,827
   1 2,256
   Dan Bull avatar image
   Dan Bull
   No activity Most days I get no activity to show. maybe one old fb
   status will pop from 4 years back but 3 years, 2 years, 1 years just
   says no activity, this happen most days and I have never got a picture
   yet.
   Donna Hawkins avatar image
   Donna Hawkins
   Sucks I want my friends to see what I share. Not just timehop header.
   Sarah McKim avatar image
   Sarah McKim
   Parts don't work After a few weeks the pictures Don't show up anymore.
   Just a black box. Fix that and I'll give it 5 stars.
   Caitlin Delorme avatar image
   Caitlin Delorme
   Fun facts Love this app. Its cool to look back and see all the cool
   stuff you used to do
   Kayla Herrick avatar image
   Kayla Herrick
   Fix it Keep getting a little black box when I want to share the
   picture....I'll give 5 stars if that problem gets fixed
   Susie Stuckey avatar image
   Susie Stuckey
   I have u installed both Fb and time hop and it doesn't show any
   pictures on Facebook. Used to be awesome what happened
   User reviews
   Dan Bull avatar image
   Dan Bull September 25, 2014
   No activity Most days I get no activity to show. maybe one old fb
   status will pop from 4 years back but 3 years, 2 years, 1 years just
   says no activity, this happen most days and I have never got a picture
   yet.
   Full Review
   Donna Hawkins avatar image
   Donna Hawkins September 23, 2014
   Sucks I want my friends to see what I share. Not just timehop header.
   Full Review
   Sarah McKim avatar image
   Sarah McKim September 20, 2014
   Parts don't work After a few weeks the pictures Don't show up anymore.
   Just a black box. Fix that and I'll give it 5 stars.
   Full Review
   Caitlin Delorme avatar image
   Caitlin Delorme September 25, 2014
   Fun facts Love this app. Its cool to look back and see all the cool
   stuff you used to do
   Full Review
   Kayla Herrick avatar image
   Kayla Herrick September 24, 2014
   Fix it Keep getting a little black box when I want to share the
   picture....I'll give 5 stars if that problem gets fixed
   Full Review
   Susie Stuckey avatar image
   Susie Stuckey September 20, 2014
   I have u installed both Fb and time hop and it doesn't show any
   pictures on Facebook. Used to be awesome what happened
   Full Review
   Katrina Dungan avatar image
   Katrina Dungan September 28, 2014
   Its always days behind and when I try to post things they don't show up
   Full Review
   Brooke Spitzer avatar image
   Brooke Spitzer September 22, 2014
   LOVE the concept, Hate the black box I really love this on my friend's
   social media pages but all I'm getting is a black box when I share a
   picture. Please FIX!
   Full Review
   Brooke Lumsden avatar image
   Brooke Lumsden September 21, 2014
   Pictures dont show up just a black box when I go to share it hopefully
   gets fixed soon and it will get 5 stars
   Full Review
   Andrew Scelzi avatar image
   Andrew Scelzi September 22, 2014
   Neat, if it worked I like being able to see these photos with ease.
   It's a really enjoyable app, but when I want to share my timehops, the
   photos never show up in the post.
   Full Review
   Ashley Freet avatar image
   Ashley Freet September 21, 2014
   Great I love this app! I forget about what I have posted years ago but
   this brings it back. Great app!!
   Full Review
   Justine Narro avatar image
   Justine Narro September 22, 2014
   Fun app It's cool getting small memories from the years. I love being
   able to see what I was doing 1 year ago today.
   Full Review
   Victoria Kidner avatar image
   Victoria Kidner September 21, 2014
   Good app, 1 issue This app is great to see what statuses & pics were
   posted in the past but there is a really annoying error that happens
   quite often where the picture does not share/show up its just blank &
   goes on Facebook as just the text if this gets fixed this app would be
   5 stars.
   Full Review
   Caroline Bertoni avatar image
   Caroline Bertoni September 24, 2014
   Love it but.. I love this app but lately all it does is crash as I am
   scrolling though. PLEASE FIX THIS
   Full Review
   Andy Ford avatar image
   Andy Ford September 23, 2014
   Why have an app that doesn't work When I get my daily notification, it
   invariably is an image. So I click share, add a comment and it posts to
   facebook....but only the timehop logo and the 1,2,3 or 4 year ago
   headline, not the image itself, not the post from 1,2,3 or 4 years ago.
   Its just noise, doesn't work.
   Full Review
   kristel tagatac avatar image
   kristel tagatac September 23, 2014
   Include photobucket Hope you'll include photobucket. I have older
   pictures there 😄
   Full Review
   Robyn Popescu avatar image
   Robyn Popescu September 21, 2014
   Photo showing up as black box😨 I love this app. I hope this gets fixed
   Full Review
   Jessica Sercu avatar image
   Jessica Sercu September 22, 2014
   Black box no pictures What is the deal with the pictures not working?
   so many photos I wanted to share and I can't because the picture
   doesn't post. I Take screen shots but can't upload them to the actual
   Time hop album so it's pointless... please fix!
   Full Review
   jackie speed avatar image
   jackie speed September 27, 2014
   Don't have facebook I don't have a Facebook but I have an instagram and
   would love to use this but can't. How dumb!
   Full Review
   Kirstie Warner avatar image
   Kirstie Warner September 19, 2014
   I wish I could look at previous days when I miss checking a day.
   Otherwise, I love it!
   Full Review

   What's New
   1.4.03
   * Google integration! Just your auto-backup photos for now, more coming
   soon!
   1.3.34
   * Redesigned Instagram sharing
   * Updated theme for Android L users
   1.3.30
   * Crash fixes
   1.3.26
   * Add your Dropbox photos to Timehop
   * Improved new user experience
   1.3.14
   * Updated Facebook login
   * Improved new user experience
   1.3.10
   * We've heard your feedback about login issues and we are working to
   resolve them.
   (BUTTON) Read more (BUTTON)

   Additional information
   Updated
   September 19, 2014
   Size
   Varies with device
   Installs
   1,000,000 - 5,000,000
   Current Version
   1.4.03
   Requires Android
   4.0 and up
   Content Rating
   Medium Maturity
   Contact Developer
   Visit Developer's Website Email Developer Privacy Policy
   Permissions
   (BUTTON) View details
   Report
   Flag as inappropriate

Similar

   Statuses for all occasions

Statuses for all occasions

   InterZnak
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   The best app and huge collection of statuses for all occasions for
   quick update status in Facebook, Twitter etc.

   All statuses are divided into 11 categories: Funny statuses, Love
   statuses, New Year statuses, Sad statuses, Nice statuses, Man statuses,
   Woman statuses, Clever statuses, Life statuses, Joke statuses, Friend
   statuses.

   Using our application you can log in and post statuses in social
   networks: Facebook, Twitter, VKontakte, Odnoklassniki and Moi Mir.
   You can edit any short status from the collection, and send their own
   status (no longer than 250 characters) to multiple social networks in
   one click!
   Post statuses on the wall Facebook, Twitter and VKontakte with photo or
   image.
   Post Photo statuses into Facebook and VKontakte.
   Post statuses on a background pictures on the wall Facebook, Twitter
   and VKontakte.
   Copy any status in clipboard.
   Share any status in to third-party applications, such as a text editor
   or an application for sending SMS.
   Collect your personal collection of Favorite statuses.
   Store in "Favorites" any phrases up to 250 characters from the
   third-party applications or publish these phrases in social networks in
   the form of statuses.
   Set up app's widget on home screen.

   Menu is available on the main page of the application:
   Two main menu items – Search and Settings.
   "Search" – search statuses by any your keywords.
   "Settings" – select the social network, which you will work, update
   statuses, sorting statuses in categories, how long time to keep posting
   history, set up widget theme and the ability to change the language of
   the application (Russian / English / Spanish / German / French /
   Italian / Portuguese).
   "History" – posting history of statuses with using of the application
   (for 7 days by default).
   "Download" - download additional database of statuses for the app.

   This application is absolutely free! Looking forward to your feedback
   and suggestions for improvement:
   https://www.facebook.com/StatusesForAllOccasions
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Facebook

Facebook

   Facebook
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Keeping up with friends is faster than ever.

   • See what friends are up to
   • Share updates, photos and videos
   • Get notified when friends like and comment on your posts
   • Text, chat and have group conversations
   • Play games and use your favorite apps

   Now you can get early access to the next version of Facebook for
   Android by becoming a beta tester. Learn how to sign up, give feedback
   and leave the program in our Help Center: http://on.fb.me/133NwuP

   Problems downloading or installing the app? See
   http://bit.ly/GPDownload1
   Still need help? Please tell us more about the issue.
   http://bit.ly/invalidpackage

   Facebook is only available for users age 13 and over.
   Terms of Service: http://m.facebook.com/terms.php.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Pinterest

Pinterest

   Pinterest, Inc.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Welcome to Pinterest, the world's biggest collection of everybody's
   favorite things.
   Join Pinterest to discover ideas for all your projects and interests,
   hand-picked by people like you.
   With Pinterest you can:
   • Plan projects—home decor overhauls, car restorations, garden
   redesigns and other DIY efforts
   • Dream up your next travel outing—outdoor adventures, road trips with
   friends, family outings and exotic travel
   • Collect your favorite things—illustrations, ideas for tattoos,
   hilarious quotes, jewelry designs, the latest technology and inspiring
   art and architecture
   • Save great ideas—articles to read, movies to watch, gifts to buy, art
   for your home, fashion and beauty how-tos, food and recipes to cook,
   fitness tips and great hair looks
   • Get organized for a party—wedding decor, birthday themes, dresses for
   the dinner party and recipes for game day
   Use Pinterest today to discover things you you’re interested in, and
   let Pinterest inspire you to do those things.
   How it works:
   You organize all your ideas into collections (called “boards”) of
   visual bookmarks (called “Pins”). When you find something that looks
   interesting, all you have to do is Pin It! Pinning on Android is easy.
   Once you install the app, just go to any website. When you find
   something interesting, tap the Menu button and click Share. Click Add
   to Pinterest, and we’ll find all the images. Click the image you want
   to Pin, save it to a board, and you’re done.
   Boards can be shared with friends. Trying to spice up your next holiday
   dinner? Collect recipes for you and your family to try. Planning that
   dream wedding? Invite the other members of your wedding party to your
   wedding board to help them make it extra special and show them all the
   hair, makeup, and shoes you’re considering. Have a DIY club in your
   neighborhood? Have the group share their various projects to keep the
   inspiration flowing.
   Browsing Pins is even easier. Discover Pins in every possible interest
   by browsing interests and categories. Your home feed will have the
   latest Pins from your friends. Depending on your friends, you may see
   tattoos and recipes or quotes and shoes. Use search to find something
   more specific, like DIY jewelry and fancy dresses for next month’s
   cocktail party, or home decor ideas for your upcoming remodel.
   What will you discover on Pinterest?
   Quotes from reviews of Pinterest:
   "The near-perfect Pinterest mobile app rocks at just about all of your
   basic pinning and browsing needs." – CNET
   “Love it! Great app!” – All kinds of Pinterest reviewers
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Instagram

Instagram

   Instagram
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Over 200 million users love Instagram!

   It's a simple way to capture and share the world's moments on your
   Android. Customize your photos and videos with one of several gorgeous
   and custom built filter effects. Transform everyday moments into works
   of art you'll want to share with friends and family.

   Share your photos and videos with friends and followers in a photo
   feed, or send posts directly to your friends.
   Follow what your friends post with the click of a single button. Every
   time you open up Instagram, you'll see new photos and videos from your
   closest friends, and creative people from around the world.

   Features
   • Linear and Radial Tilt-Shift blur effects for extra depth of field
   • Instant sharing to Facebook, Twitter, Flickr, Tumblr and Foursquare
   • Unlimited uploads
   • Send photos and videos directly to friends
   • Interact with friends through giving & receiving likes and comments
   • And much much more...
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Snapchat

Snapchat

   Snapchat, Inc.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Enjoy fast and fun mobile conversation! Snap a photo or a video, add a
   caption, and send it to a friend. They’ll view it, laugh, and then the
   Snap disappears from the screen – unless they take a screenshot!

   You can also add a Snap to your Story with one tap to share your day
   with all of your friends.

   The best conversations happen when both friends are present, so we’ll
   let you know if your friend is Here in your Chat so that you can give
   each other your full attention. And if you're both Here, simply press
   and hold to share live video - and Chat face-to-face!

   Happy Snapping!

   ***

    Please note: even though Snaps, Chats, and Stories are deleted from
   our servers after they expire, we cannot prevent recipient(s) from
   capturing and saving the message by taking a screenshot or using an
   image capture device.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Vine

Vine

   Vine Labs, Inc.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Vine is the best way to see and share life in motion. Create short,
   beautiful, looping videos in a simple and fun way for your friends and
   family to see.

   • Unlimited uploads and free
   • Instantly post videos on Vine, then share to Twitter and Facebook
   • Find, follow, and interact with people close to you
   • Explore trending posts, featured hashtags and editor's picks
   • And so much more

   Have questions, problems, or feedback? Reach out to us at @vineapp on
   Twitter.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Twitter

Twitter

   Twitter, Inc.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Twitter is a free app that lets you connect with people, express
   yourself, and discover more about all the things you love.

   • Get breaking news. Stay informed with the local and global news that
   matters to you most, as it happens.

   • Go behind the scenes at exclusive events like the Oscars, the Emmys,
   the MTV VMA's and the World Cup.

   • Express yourself with text, photos, emoji, emoticons, video, GIFs and
   Vines.

   • Use hashtags (like #NFL) to find more Tweets about topics you love.

   • Get closer to people who interest you, including celebrities like Kim
   Kardashian, Harry Styles and Rihanna.

   • Share Tweets with apps like Facebook, Whatsapp, Kik, LINE, email and
   SMS.

   • Tweet links from sites like YouTube, Pinterest, Instagram, Spotify
   and Pandora.

   Click here to see why Twitter is requesting permission to access
   features on your device:
   https://support.twitter.com/groups/54-mobile-apps/topics/223-android/ar
   ticles/20171517-why-is-the-twitter-app-requesting-permission-to-access-
   features-on-my-android-device
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Quick Social

Quick Social

   Lupine Development
   1
   (BUTTON) $1.49 Listen Read Device Only Added (BUTTON) Watch Installed
   Quick Social is an app that allows you to tweet/post to Facebook/post
   to Google+ right from the notification drawer!

   Enable any or every social network, login and... you're done! It's that
   simple!

   Help us translating Quick Social: http://maciej.es/6i3-e

   We have put a lot of effort to create Quick Social. If you notice any
   bug while enjoying the app, don't run to the Play Store to give us a
   1-star review. Instead, contact us at quicksocial@lupine.cc - we'll do
   what can to fix the issue as soon as possible!
   1
   (BUTTON) $1.49 Listen Read Device Only Added (BUTTON) Watch Installed
   Followers+ for Instagram

Followers+ for Instagram

   Tappple
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Track your lost/gained followers... PLUS MUCH, MUCH MORE!

   "The only Followers app you'll ever need... and its Free!"

   - Who are your best followers? Who are your worst?
   - Who isn't following you back? Who did you forget to follow back?
   - Who do you like the most? Who are the ghosts? Who posts near by? Far
   away?
   - Track your Average Likes per Photo, Fame Value, and many other stats

   And Much, More!!

   PLEASE READ:
   -You must have an Instagram account to use this app.

   Tell us what you think! support@tappple.com
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Tumblr

Tumblr

   Tumblr, Inc.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   • Post anything, from anywhere.
   • Share photos, gifs, video, music, quotes, chats, links, and text.
   Find and follow the things you love, and get all your latest news from
   your dashboard.
   • Bonus: Add a 'create a post' widget to your home screen.
   • Advanced controls: Save drafts, queue posts, customize tweets, and
   more!
   • Messages: View and reply to messages.
   • Multiple blogs: Seamlessly manage all of your blogs.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Tango Messenger, Video & Calls

Tango Messenger, Video & Calls

   Tango
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Tango is a free messaging service that allows you to connect, get
   social, and have fun with those who matter most to you. Send text
   messages, make video & voice calls, share photos, meet new friends,
   play games, send music messages powered by Spotify & more! Join the
   hundreds of millions of people around the world using Tango as their #1
   messaging app & new mobile social network.

   Free & Easy to Use
   - All video & phone calls & text messages are free locally & globally
   - Calls & messages don’t use your minutes or SMS plan
   - No login & password - create an account in seconds
   - Automatically finds your friends using Tango
   - Calls & messages work just like they do on your phone
   - Always on so you don’t miss a thing

   Connect
   - High quality video & voice calls & messages
   - 1 to 1 & group chat with up to 300 friends
   - Works across most smartphones, tablets, & PCs
   - Great quality voice & video calls on 3G, 4G, & Wi-Fi

   Get Social
   - Personalize your profile with status updates & photos
   - Edit, share, comment & like photos
   - Post status, videos, music clips, links, audio messages, and animated
   surprises to the News Feed
   - Easily find friends nearby or anywhere in the world
   - Connect with friends of friends in “People You May Know”

   Have Fun
   - Browse Channels in different categories, including entertainment,
   sports, music, lifestyle, and news
   - Follow your favorite brands to find and share fun videos, photos,
   links, and more
   - Challenge friends, send gifts, & climb leaderboards in 40+ featured
   games on Tango
   - Discover, listen & share songs powered by Spotify
   - Personalize your calls & messages with fun animations
   - Play a mini-game or share photos during a call

   Awards
   - Best Communication App – 2013 Appy Awards
   - Best Texting App – 2013 About.com Reader’s Choice Awards
   - Must Have Apps List – 2013 Verizon Wireless

   * Learn more at http://www.tango.me
   * Like us on Facebook at http://facebook.com/TangoMe
   * Follow us on Twitter at http://twitter.com/TangoMe
   * Follow us on Google+ at google.com/+tangoapp
   * Follow us on LinkedIn at http://www.linkedin.com/company/tango-me
   * Need Help? Visit http://support.tango.me
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   LinkedIn

LinkedIn

   LinkedIn
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Opportunity is always within reach with the LinkedIn app for Android.
   Our Android app makes it even easier to build your personal brand, make
   connections, stay informed with personalized news, and more – right in
   your feed.

   • Find and connect with a professional network of more than 300 million
   members worldwide
   • Read the latest industry news to stay informed and ready for your
   workday
   • Follow Influencers to get advice and inspiration from industry
   leaders
   • Update your profile from within the app, building your brand wherever
   you are
   • View and save recommended jobs – look for the option to apply with
   your LinkedIn profile in just one tap
   • Follow companies you’re interested in to get job postings, updates,
   and find people you may know
   • Keep up with your favorite groups, whether it’s asking questions or
   adding to the conversation
   • Upgrade your account to LinkedIn Premium from within the app

   Have questions on a particular permission? http://linkd.in/1l0S8YZ
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Ask.fm - Social Q&A Network

Ask.fm - Social Q&A Network

   Ask.fm
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Ask.fm is the #1 app for social Q&A that lets you explore your friends’
   personalities by asking them to answer smart, interesting and fun
   questions about themselves. It’s entertaining, completely easy to use
   and you can quickly connect using your Facebook, Twitter or VK login.

   Ask.fm is used by millions of users around the world every day, asking
   and answering millions of questions every month in over 40 languages.
   Are you on Ask.fm already? Simply log in with your username and
   password.

   Here’s everything the official Ask.fm app has to offer:
   • Easy, intuitive interface
   • Access to all your social media friends
   • See the activity of everyone you follow
   • Read and respond to your questions anywhere, anytime
   • Add photos and animated GIFs to your answers
   • Always stay on top with push notification

   Any issues or questions? Let us know at: app@ask.fm
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Bright Camera for Facebook

Bright Camera for Facebook

   Amazing Studio
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   With Bright Camera, you can create and share you attractive selfie on
   Facebook simple and easy.
   Get notified when friends like and comment on your selfie and see
   friends’ latest photos in one place.

   Bright Camera free app is: Facebook photo feed, android photo gallery,
   advanced camera for selfie, photo portrait editor and Facebook photo
   uploader.

   Photo portrait editor features:
   ★ Beautification & makeup: lighten, whiten and smoothing skin in one
   touch
   ★ Beauty camera photo effects: color effects like Photoshop effects,
   pastel themes, retro camera effects, neon lights and bokeh effects for
   pictures, Hearts - a set of special love effects
   ★ Radial Tilt-Shift effects with backlight, blur effect, violet light,
   azure blue, pink and coral vignette camera effects,
   pixel art or mosaic picture effect, lamp light, monochrome photo effect
   for integrity and perfect composition
   ★ Glow art photo filters and lens: sweet hearts, light rays of love,
   disco light, stars of love, bubble pop, diamond hearts, smileys, space
   effects and shining stars, magic bokeh
   ★ Love quotes and sayings in beautiful photo frames: I love you, I love
   U, Together forever, You color my world, Good morning, Good night,
   happy birthday,
   sweet dreams, diamond hearts as picture in picture
   ★ Edit photo size: instasize no crop for Instagram: сrop photos, rotate
   screen with a photo, zoom camera and mirror camera options
   ★ Extra photo editor tools for Instagram: “instasize no crop” for
   uploading entire photos on Instagram without cropping; “instaframe” set
   of photo frames for additions special photo frame for portrait or
   landscape photo to Instagram’s squared photo
   ★ Write text quotes on photos

   Advanced camera features:
   ★ Special features for portraits: self timer camera, silent camera, big
   camera button
   ★ Anti shake camera mode with stabilization
   ★ Digital Zoom
   ★ Flashlight and 3 flash modes
   ★ Different capture scene modes: Automatic, Macro camera, Portrait,
   Sports, Night, Beach.

   Android photo gallery features:
   ★ Instagram and Facebook photo downloader with beauty camera effects
   ★ Photo gallery viewing photo grid like photo calendar
   ★ Smart photo gallery organizer with visual tags
   ★ Instant sharing to Facebook, Instagram, WhatsApp
   ________
   ★ App supports Android versions from 2.3.3 to 4.3
   ★ Tested on Samsung Galaxy S4, Samsung Galaxy S2, Samsung Galaxy S3
   Samsung Galaxy S3 mini, Samsung Galaxy S4, Samsung Galaxy Note,Samsung
   Galaxy Note 2,Samsung Galaxy Y, Samsung Galaxy Tab 2, Samsung Galaxy
   Ace, Samsung Galaxy S, Samsung Galaxy S Advance, Samsung Galaxy S Plus,
   HTC One X, HTC Sense, HTC Desire HD, HTC Evo 4G, HTC Incredible S, LG
   Motion 4G, LG Optimus, ZTE N860, Nexus 7, Nexus 4, Nexus 5, Sony
   Ericsson Xperia Arc S, Sony Ericsson Xperia S, Sony Xperia U and works
   well on other android phones.
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   We Heart It

We Heart It

   We Heart It
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   Discover inspiration and images you love every day! #Happiness

   We Heart It is the place to find the most beautiful images of
   everything you love, inspired by millions of people from around the
   world!

   Save a collection of quotes, view pictures that match your mood, find
   images for an art or fashion collage, upload your top inspirations from
   your photo gallery, and get updated on news through images of the
   latest styles, for free!

   Top features:
   • View the highest-quality photos, GIFs, and videos in a variety of
   colorful, vivid, artistic, vintage, and black & white styles.
   • Search and find exactly what you're looking for, whether it's fashion
   and hair trends or a hipster cat with glasses!
   • Save your favorite pictures to your We Heart It gallery, phone, or
   wallpaper.
   • Share the newest images with your friends on Tumblr, Facebook, or
   Twitter.
   • Group your top pictures by creating "collections" of anything from
   the dresses you want, to travel places, to a home or bedroom decoration
   theme, to tattoo ideas, and everything else you love.
   • Follow top tastemakers and join the social community of people from
   the US, Brazil, Norway and dozens of other countries.
   • You can even save, upload, and post your favorite images from other
   sites or blogs into your We Heart it collection.

   Keep hearting on We Heart It!
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   MeetMe: Chat & Meet New People

MeetMe: Chat & Meet New People

   MeetMe.com
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed
   MeetMe shows you who’s nearby, ready to chat and meet — FREE!

   Whether you’re at the bar, on the beach, or hanging out at home, MeetMe
   is the BEST app for meeting new people near you!
   MeetMe is for all ages, all nationalities, all backgrounds -- EVERYONE!

   More than 90 MILLION PEOPLE are on MeetMe making friends, chatting, and
   hanging out.
   Use MeetMe to:
   - Meet great people near you by joining the conversation in Live Feed
   - See who's right nearby and start chatting fast in Locals
   - Ask and answer anything with Ask Me
   - ...and much more!

   --------
   MeetMe Stories

   "[It's] probably one of the greatest sites... greater variety of
   people... everyone is at one place at one time... meeting new people."
   - Stevie S.

   "I log on here, and these people you don't even know, they care more
   about me than my real friends do, these people are so nice." - Michelle
   M.

   "I've met so many people from the world that I wouldn't normally meet."
   Jazzeh N.

   *** #1 Social Network for Meeting New People in the US ***
   1
   (BUTTON) Free Listen Read Device Only Added (BUTTON) Watch Installed

   (BUTTON) Show More
   ©2014 Google Site Terms of Service Devices Terms of Sale Privacy Policy
   Developers Artists About Google
