   #publisher The Atlantic Best of The Atlantic Technology Channel Alexis
   C. Madrigal's Feed




   Continue to TheAtlantic.com [arrow.png]
   Advertisement

The Atlantic

   Subscribe Now
   [medium.jpg?nc2mvq]
   [shop_JUL09_2014_cards.jpg] [shop_JUL09_2014_Mtee.jpg]
   [shop_JUL09_2014_mugs.jpg] [shop_JUL09_2014_Wtee.jpg]
   ____________________ (BUTTON)
   Get The Atlantic on Facebook
     * Politics
          + Top Stories
          + The Supreme Court Is Looking Out for the Rights of the
            Majority
          + Eric Holder's Legacy as Attorney General
          + The Little Rock 9: How Far Has the Country Come?
          + The Mystery Candidate Shaking Up Kansas Politics
          + How Politics Breaks Our Brains
          + Books for the Horde: The New Jim Crow, Chapters 2 and 3
          + Sponsor Content The Brooklyn Navy Yard Is Creating a New Model
            for Urban Revitalization
            [adServer.bs?cn=tf&c=19&mc=imp&pli=11099584&PluID=0&ord=%%CACH
            EBUSTER%%&rtu=-1]
          + Sponsor Content Hologic Enables Better Outcomes for Patients
          + Sponsor Content Solazyme Is Producing a New Source of
            Renewables
          + Sponsor Content MRC Global: A Leading Supplier to the Energy
            Industry
          + Sponsor Content How Titan International Is Creating American
            Manufacturing Jobs
     * Business
          + Top Stories
          + Saving Paris's Oldest Bookstore
          + Christmas Ads Already?! Actually, Most People Don't Seem to
            Mind
          + Is Bike Sharing Just for Gentrifiers?
          + Peter Thiel's Zero to One Might Be the Best Business Book I've
            Read
          + "Kleenex Is a Registered Trademark" (And Other Desperate
            Appeals)
          + America, the Plannable: How Banks Affect Family Size
          + Sponsor Content The Extinction of Spectator Sports
          + Sponsor Content The Search for the Next Yellow Line
          + Sponsor Content How Apps Might Change Your Swing
          + Sponsor Content Protecting the World's Most Valuable Human
            Real Estate
          + Sponsor Content Blood, Sweat and Data
     * Tech
          + Top Stories
          + Beyond GMOs: The Rise of Synthetic Biology
          + The Woman With the Bionic Eye
          + How to Stop a Rumor Online (Before the Rumor Becomes a Lie)
          + When Everything Works Like Your Cell Phone
          + Ello Says You're Not a Product, But You Are
          + Peering Ever Deeper Into Matter
          + Sponsor Content The Art and Science of Our Senses
            [B8161992.110556643;sz=1x1;ord=%n]
          + Sponsor Content Solving for Sound
     * Entertainment
          + Top Stories
          + The Equalizer: The Ultimate Denzel Washington Role
          + Did Clayton Kershaw Just Have the Best Summer in Baseball
            History?
          + 30 Years of Coens: True Grit
          + "Can a TV Show Save Lives?"
          + Lost, Bill Simmons, and Denzel: The Week in Pop-Culture
            Writing
          + Dave Matthews Band, Happy Rebels
     * Health
          + Top Stories
          + How to Test a Couch for Toxins
          + Toward an Effective Tuberculosis Vaccine
          + The World War II Campaign to Bring Organ Meats to the Dinner
            Table
          + The Health Effects of Leaving Religion
          + France's Troubled Romance With Beef
          + How Exercise Could Erode Teeth
     * Education
          + Top Stories
          + B.J. Novak Proves That Kids' Books Don't Need Pictures
          + How to Make Teachers More Like Doctors
          + Why Girls Tend to Get Better Grades Than Boys Do
          + The Little Rock Nine: How Far Has the Country Come?
          + Where Girls Get Kidnapped on Their Way to School
          + What Do You Wish You Had Learned in College?
          + Sponsor Content The Solution to the US Skills Gap Isn't What
            You Think
          + Sponsor Content This is the Future of Your Commute
          + Sponsor Content How Smart Grids Could Transform the Developing
            World
     * Sexes
          + Top Stories
          + Where Girls Get Kidnapped on Their Way to School
          + Pop Culture's Transgender Moment: Why Online TV Is Leading the
            Way
          + The Economic Case for Paternity Leave
          + When Bosses Discriminate Against Pregnant Women
          + Will "Cisgender" Survive?
          + No, Hope Solo Is Not "Like" Ray Rice
     * National
          + Top Stories
          + The “Other” America
          + Kosher Meets Hipster
          + When Philosophy Becomes Therapy
          + The Health Effects of Leaving Religion
          + Cop Asks for Man's License, Shoots Him When He Reaches for It
          + Saving Wukchumni
          + Sponsor Content Cities Need Small Business Growth Strategies
            [B8212757.15;dc_trk_aid=284503546;dc_trk_cid=59471219;ord=%%CA
            CHEBUSTER%%]
     * Global
          + Top Stories
          + Songdo, South Korea: City of the Future?
          + France's Troubled Romance With Beef
          + Why Is the U.S. Yielding to Iran Now?
          + Saving Paris's Oldest Bookstore
          + Dismantling Empires Through Devolution
          + China's Other Food-Safety Problem
     * Video
          + Top Stories
          + Famous Movies Recreated With Stock Footage
          + What Is a City?
          + The Flight of a Moth, In Extreme Slow Motion
          + What Do You Wish You Had Learned in College?
          + Saving Wukchumni
          + CrossFit Versus Yoga: Choose a Side
     * Magazine
          + In This Month's Issue
          + What Happens When We All Live to 100?
          + Why I Hope to Die at 75
          + How Gangs Took Over Prisons
          + [medium.jpg?nc2mvq]
               o Subscribe
               o Renew
               o Give a Gift
               o Digital Editions

     * Subscribe
     * Events
     * Newsletters
     * Books
     * Apps
     * Features
     * In Focus
     * Just In
       The Health Effects of Leaving Religion

     * [skybox-thumb.jpg?ncif2m]

The Supreme Court: Looking Out for the Majority
       By Garrett Epps
     * [skybox-thumb.jpg?ncif2m]

30 Years of Coens: True Grit
       By Christopher Orr
     * [skybox-thumb.jpg?ncif2r]

Dismantling Empires With Devolution
       By Parag Khanna
     * [] Sponsor Content The Search for the Next Yellow Line
     * [] Sponsor Content How Apps Might Change Your Swing
     * [] Sponsor Content Protecting the World's Most Valuable Human Real
       Estate
     * [skybox-thumb.jpg?ncj3ob] Sponsor Content Blood, Sweat and Data
     * [skybox-thumb.jpg?ncj41i] Sponsor Content The Extinction of
       Spectator Sports

Email Is Still the Best Thing on the Internet

   The gentle, dependable workhorse that everyone relies on and nobody
   owns
   Alexis C. Madrigal Aug 14 2014, 12:34 PM ET
   Tweet
   More
   Email
   Print
   [lead.jpg?nabz4a]
   You've still got mail, and you always will. (lansvision/Shutterstock)

   All these people are trying to kill email.

   "E-mail is dead, or at least that’s what Silicon Valley is banking on,"
   wrote Businessweek tech reporter Ashlee Vance.

   There's the co-founder of Asana, the work software startup. Email has
   "become a counter-productivity tool,” Justin Rosenstein likes to say.

   Slack, the superhot work chat tool, likes to brag that they've "saved
   the world from over 70,000,000 emails" (if you assume that every five
   Slack messages prevent one email from getting its wings).

   And it's not just entrepreneurs with cloud software to sell. There are
   the young people, too, especially whatever we call the
   younger-than-Millennials.

   Getting an email address was once a nerdy right of passage for Gen-Xers
   arriving on college campuses. Now, the kids are waging a war of
   indifference on poor old email, culling the weak and infirm old-people
   technology. One American professor maintained that, to his
   students, "e-mail was as antiquated as the spellings 'chuse' and
   'musick' in the works by Cotton Mather and Jonathan Edwards." The
   vice-chancellor of Exeter University claimed, "There is no point in
   emailing students any more." The youth appear to think there are
   better, faster, more exciting ways to communicate than stupid email.
   Email is actually a tremendous open platform on which new, innovative
   things can and have been built.

   Yet, despite all the prognosticators predicting it will—choose the
   violence level of your metaphor—go out of style, be put out to pasture,
   or taken out back and shot, email grinds on.

   You can't kill email! It's the cockroach of the Internet, and I mean
   that as a compliment. This resilience is a good thing.

   "There isn't much to sending or receiving email and that's sort of the
   point," observed Aaron Straup Cope, the Cooper-Hewitt Design
   Museum's Senior Engineer in Digital and Emerging Media. "The next time
   someone tells you email is 'dead,' try to imagine the cost of investing
   in their solution or the cost of giving up all the flexibility that
   email affords."

   Email is actually a tremendous, decentralized, open platform on which
   new, innovative things can and have been built. In that way, email
   represents a different model from the closed ecosystems we see
   proliferating across our computers and devices.

   Email is a refugee from the open, interoperable, less-controlled "web
   we lost." It's an exciting landscape of freedom amidst the walled
   gardens of social networking and messaging services.

   Yes, email is exciting. Get excited!

   * * *

   For all the changes occurring around email, the experience of email
   itself has been transformed, too. Email is not dying, but it is
   being unbundled.

   Because it developed  early in the history of the commercial Internet,
   email served as a support structure for many other developments in the
   web's history. This has kept email vitally important, but the downside
   is that the average inbox in the second decade of the century had
   become clogged with cruft. Too many tasks were bolted on to email's
   simple protocols.

   Looking back on these transitional years from the 2020s, email will
   appear to people as a grab bag of mismatched services.

   Email was a newsfeed. With the proliferation of newsletters, email
   alerts, flash sale emails, and other email-delivered content, one's
   email client became a major site of media consumption. It was a feed as
   much as an inbox.

   Email was one's passport and identity. Before Facebook became a true
   alternative for verifying one's identity on the web, the email address
   was how one accomplished serious things on the Internet. Want to verify
   a bank account? Email. Amazon? Email. Forums? Email. Even Facebook in
   the early days? Email. And it meant something where your email address
   was hosted. FirstName@YourLastName.com signaled you owned a domain. A
   Hotmail account might indicate you were a beginner and a Well address
   connoted early Internet connectivity. For a time, Gmail addresses were
   a sign of sophistication. Now, both the functional and symbolic
   importance of email addresses is in decline. There are so many more
   ways to signal who we are online now.

   Email was the primary means of direct social communication on the
   Internet. Email was how to send a message to someone, period. BBSs,
   chat rooms, and message boards have existed for as long as email, but
   email formed the private links between people that undergirded the
   public channels, which evolved before and with the web. Now, there are
   a lot of ways to reach someone on the net. There is one's phone,
   Facebook profile, Twitter account, LinkedIn, Instagram, Qik, WhatsApp,
   etc., etc. It's telling that in the mobile world, app developers want
   access to a user's phone's contact list, not her email connections.

   Email was a digital package-delivery service. After FTP faded from
   popularity, but before Dropbox and Google Drive, email was the primary
   way to ship heavy digital documents around the Internet. The attachment
   was a key productivity tool for just about everyone, and it's hard to
   imagine an Internet without the ability to quickly append documents to
   a message. Needless to say, email is a less than ideal transmission or
   storage medium, relative to the new services.

   Email was the primary mode of networked work communication. Most
   companies would have a hard time functioning without email, the French
   company Atos's successful email ban notwithstanding. And it's this last
   category of email service that so many companies are eager to reform.
   HootSuite's CEO laid out why in a Fast Company article in 2013: Email
   is, he said, unproductive, linear, not social, and paradoxically tends
   to create information silos. Plus, who doesn't want some enterprise
   budget? Many startups, tiring of or failing in the consumer space, need
   to pivot somewhere.

   * * *

   Looking at this list of email's many current uses, it is obvious that
   some of these tasks will leave its domain. Each person will get to
   choose whether they use email as their primary identity on the web.
   Work and simple social messaging will keep moving to other platforms,
   too. The same will be true of digital delivery, where many cloud-based
   solutions have already proved superior.

   So, what will be left of the inbox, then?

   I contend email might actually become what we thought it was: an
   electronic letter-writing platform.

   My colleague Ian Bogost pointed out to me that we've used the metaphor
   of the mail to describe the kind of communication that goes on through
   these servers. But, in reality, email did not replace letters, but all
   classes of communications: phone calls, in-person encounters, memos,
   marketing pleas, etc.
   Email has gotten much smarter and easier to use, while retaining its
   ubiquity and interoperability. But there is no one company promoting
   Email (TM), so those changes have gone unremarked upon.

   The metaphor of electronic mail never fully fit how people use e-mail.
   But, now, perhaps it might. Email could become a home for the kinds of
   communications that come in the mail: letters from actual people,
   bills, personalized advertisements, and periodicals.

   This change might be accelerated by services like Gmail's Priority
   Inbox, which sorts mail neatly (and automatically) into categories, or
   Unroll.me, which allows users to bundle incoming impersonal
   communications like newsletters and commercial offers into one easy
   custom publication.

   That is to say, our inboxes are getting smarter and smarter. Serious
   tools are being built to help us direct and manage what was once just a
   chronological flow, which people dammed with inadequate organization
   systems hoping to survive the flood. (Remember all the folders in
   desktop email clients!)

   It's worth noting that spam, which once threatened to overrun our
   inboxes, has been made invisible by more sophisticated email filtering.
   I received hundreds of spam emails yesterday, and yet I didn't see a
   single one because Gmail and my Atlantic email filtered them all neatly
   out of my main inbox. At the same time, the culture of botty spam
   spread to every other corner of the Internet. I see spam comments on
   every website and spam Facebook pages and spam Twitter accounts every
   day.

   Email has gotten much smarter and easier to use, while retaining its
   ubiquity and interoperability. But there is no one company promoting
   Email (TM), so those changes have gone relatively unremarked upon.
   This is what email used to be (Wikimedia).

   But recall Hotmail in 1996 or Microsoft Outlook in 1999 or—and I know
   some nerds will hate me for saying this—Pine over a telnet connection
   in 1993. Compare it to Gmail today or Mailbox on an iPhone. The process
   of receiving email has gotten so much better, friendlier, and more
   sophisticated.

   And one last thing ... This isn't something the originators of email
   ever could have imagined, but: Email does mobile really well.

   While the mobile web is a rusting scrapheap of unreadable text, broken
   advertisements, and janky layouts, normal emails look great on phones!
   They are super lightweight, so they download quickly over any kind of
   connection, and the tools to forward or otherwise deal with them are
   built expertly and natively into our mobile devices.

   All this to say, email has soaked up many of the great things about the
   current web. It's pretty. It's convenient. Algorithms work over the raw
   feed to simplify the flow of information. Email, generally, is
   mobile-friendly and renders beautifully on all devices. These are the
   things that the current generation of web companies strive to
   accomplish. And look at old email, doing all that effortlessly.

   While email's continued evolution is significant, what it has retained
   from the old web sets it apart from the other pretty, convenient apps.
   Email is an open, interoperable protocol. Someone can use Google's
   service, spin up a server of her own, or send messages through
   Microsoft's enterprise software. And yet all of these people can
   communicate seamlessly. While various governments have done what they
   can to hassle or destroy anonymous email services in the post-Snowden
   world, email is one of the more defensible and private parts of the
   mainstream Internet experience, especially if one is willing to go
   through some extra security procedures.

   Last, Silicon Valley startups seem to be able to offer the great
   experiences that they do because they centralize our information within
   their server farms. But email proves that this is not necessarily the
   case. Progress can come from much more distributed decision-making
   processes. The email protocol evolves based on the deliberations of
   the Internet Engineering Task Force, not by the fiat rule of a single
   company in Silicon Valley or New York.

   And what's changing isn't a product that must be rolled out to all
   users, but an ecosystem that provides niches for all kinds of different
   emailers.

   Perhaps the way, then, to recover some of the old web, before the
   dominance of Apple, Google, Amazon, and Facebook, isn't to build new
   competitors to those companies, but to redouble our use and support of
   good old email.

   Email—yes, email—is one way forward for a less commercial, less
   centralized web, and the best thing is, this beautiful cockroach of a
   social network is already living in all of our homes.

   Now, all we have to do is convince the kids that the real rebellion
   against the pressures of social media isn't to escape to the
   ephemerality of Snapchat, but to retreat to the private, relaxed
   confines of their email inboxes.
   Jump to comments
   Tweet

   IFRAME:
   http://www.reddit.com/static/button/button2.html?width=51&url=http%3A%2
   F%2Fwww.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F08%2Fwhy-email-
   will-never-die%2F375973%2F

     * Email
     * Print

   Presented by
   [author-headshot.jpg?m8tdem]

Alexis C. Madrigal

   Alexis Madrigal is the deputy editor of TheAtlantic.com. He's the
   author of Powering the Dream: The History and Promise of Green
   Technology. More

   The New York Observer has called Madrigal "for all intents and
   purposes, the perfect modern reporter." He co-founded Longshot
   magazine, a high-speed media experiment that garnered attention from
   The New York Times, The Wall Street Journal, and the BBC. While at
   Wired.com, he built Wired Science into one of the most popular blogs in
   the world. The site was nominated for best magazine blog by the MPA and
   best science website in the 2009 Webby Awards. He also co-founded Haiti
   ReWired, a groundbreaking community dedicated to the discussion of
   technology, infrastructure, and the future of Haiti.
   He's spoken at Stanford, CalTech, Berkeley, SXSW, E3, and the National
   Renewable Energy Laboratory, and his writing was anthologized in Best
   Technology Writing 2010 (Yale University Press).
   Madrigal is a visiting scholar at the University of California at
   Berkeley's Office for the History of Science and Technology. Born in
   Mexico City, he grew up in the exurbs north of Portland, Oregon, and
   now lives in Oakland.
     * All Posts
     * RSS
     * Email
     * Follow @alexismadrigal

   [ebook-banner-zen.jpg] [TAL_WWI_Layout1.gif]
   Try 2 Free Issues! Go
     * Subscribe
     * Renew
     * Give a Gift
     * Digital Edition

   Get Today's Top Stories in Your Inbox (preview)
   Email Address ____________________ [X] Sign Up
     * Why Don't We Treat Our Teeth Like the Rest of Our Bodies?
       Olga Khazan Sep 25, 2014
     * Peering Ever Deeper Into Matter
       Sarah Laskow Sep 26, 2014
     * Shaking Up Kansas' Politics
       Molly Ball Sep 27, 2014
     * It's Not Just Ferguson
       James Forman Jr. Sep 17, 2014

Video

   More video
   [video-featured.png?nciosb]

Famous Movies Recreated With Stock Footage

   From Apocalypse Now to The Lord of the Rings, this clever video puts a
   new spin on Hollywood's greatest hits.
     * Share on Facebook
     * Tweet
     *

   [home-article-curation-405x234.jpg?ncmvsw]

When Everything Works Like Your Cell Phone

   [home-article-curation-405x234.png?ncmvsw]

The Woman With the Bionic Eye

   [home-article-curation-405x234.jpg?ncmvsw]

Pop Culture's Transgender Moment

   [home-article-curation-405x234.jpg?ncmvsw]

The Economic Case for Paternity Leave

   ‹ ›
     __________________________________________________________________

Join the Discussion

   After you comment, click Post. If you’re not already logged in you will
   be asked to log in or register. Please enable JavaScript to view the
   comments powered by Disqus. blog comments powered by Disqus
   Close

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

What Do You Wish You Learned in College?

   Ivy League academics reveal their undergrad regrets

Video

   [play-button.png] [curation-special-report-thumb.png?nciy7c]

Famous Movies, Reimagined

   From Apocalypse Now to The Lord of the Rings, this clever video puts a
   new spin on Hollywood's greatest hits.

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

What Is a City?

   Cities are like nothing else on Earth.

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

CrossFit Versus Yoga: Choose a Side

   How a workout becomes a social identity

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

In Online Dating, Everyone's a Little Bit Racist

   The co-founder of OKCupid shares findings from his analysis of millions
   of users' data.

Writers

   Up
     * Julie Beck
       How Exercise Could Erode Teeth Sep 27, 2014
     * Molly Ball
       The Mystery Candidate Shaking Up Kansas Politics Sep 27, 2014
     * Megan Garber
       How to Stop a Rumor Online (Before the Rumor Becomes a Lie) Sep 26,
       2014
     * David Frum
       Why Is the U.S. Yielding to Iran Now? Sep 26, 2014
     * Joe Pinsker
       Christmas Ads Already?! Actually, Most People Don't Seem to Mind
       Sep 26, 2014
     * Chris Heller
       Famous Movies Recreated With Stock Footage Sep 26, 2014
     * Derek Thompson
       Did Clayton Kershaw Just Have the Best Summer in Baseball History?
       Sep 26, 2014
     * Conor Friedersdorf
       Cop Asks for Man's License, Shoots Him When He Reaches for It Sep
       26, 2014
     * Christopher Orr
       30 Years of Coens: True Grit Sep 26, 2014
     * James Fallows
       Iron Pigs Rising Sep 25, 2014
     * David A. Graham
       With Eric Holder's Exit, Obama Loses a Key Ally Sep 25, 2014
     * Olga Khazan
       Why Don't We Treat Teeth Like the Rest of Our Bodies? Sep 25, 2014
     * Bourree Lam
       Quantifying Americans' Distrust of Corporations Sep 25, 2014
     * Uri Friedman
       3 Men Visited 19 Countries in 24 Hours—or Did They? Sep 24, 2014
     * Robinson Meyer
       Facebook's Mood Manipulation Experiment Might Have Been Illegal Sep
       24, 2014
     * Jeffrey Goldberg
       A Pugnacious Obama Takes on (Most of) the World Sep 24, 2014
     * Ta-Nehisi Coates
       Books for the Horde: The New Jim Crow, Chapters 2 and 3 Sep 24,
       2014
     * Jennie Rothenberg Gritz
       B.J. Novak Proves That Kids' Books Don't Need Pictures Sep 24, 2014
     * Kathy Gilsinan
       The U.S. Has Bombed Two Different Sides in Syria's Civil War Sep
       23, 2014
     * Emma Green
       Half of Americans Believe Gay Sex Is a Sin Sep 22, 2014
     * Adrienne LaFrance
       Humanity's Most Famous Mixtape Is Now 11 Billion Miles From Earth
       Sep 22, 2014
     * Matt Ford
       The United States of Great Britain? Sep 19, 2014
     * Peter Beinart
       How to Defeat ISIS, According to Ted Cruz Sep 19, 2014
     * James Bennet
       “I Never Dreamed It Would Turn Out This Way” Sep 17, 2014

   Down

More in Technology

     * [channel-curation-featured-small.jpg?ncj3k2]

Beyond GMOs: The Rise of Synthetic Biology
       Josie Garthwaite
     * [channel-curation-featured-small.png?ncj3k2]

The Woman With the Bionic Eye
       Rose Eveleth
     * [channel-curation-featured-small.jpg?ncj3k2]

How to Stop a Rumor Online (Before the Rumor Becomes a Lie)
       Megan Garber

[camera-white.png] In Focus

   [highlight_2014092609.jpg]

Photos of the Week: 9/20-9/26

Most Popular

   1
          Life as a Nonviolent Psychopath

   2
          Peter Thiel's Zero to One Might Be the Best Business Book I've
          Read

   3
          Steve Kroft's Softball Obama Interviews Diminish '60 Minutes'

   4
          The Health Effects of Leaving Religion

   5
          Songdo, South Korea: City of the Future?

   6
          When Everything Works Like Your Cell Phone

   7
          Why I Hope to Die at 75

   8
          The Miracle of Writing

   9
          Photos of the Week: 9/20-9/26

   10
          Dismantling Empires Through Devolution

Just In

     * The Health Effects of Leaving Religion Jon Fortenbury
     * "Can a TV Show Save Lives?" Ali Liebegott
     * When Everything Works Like Your Cell Phone Alexis C. Madrigal and
       Robinson Meyer

ATLANTIC MEDIA

CityLab

     * My 5 Favorite Maps: Bill Rankin
     * 10 Big Ideas From CityLab 2014 Attendees
     * For Bee-Friendly Parks, Head For the Great Unmown

   More from CityLab

The Wire

     * Al Qaida Leader Vows Revenge for Airstrikes in Syria
     * Hong Kong Police Unleash Tear Gas on Protesters
     * Ferguson Police Officer Shot, Two Suspects Wanted

   More from The Wire

Quartz

     * “Hands up, don’t shoot” comes to Hong Kong’s pro-democracy movement
     * Democracy activists’ plan to disrupt Hong Kong is starting to work
     * Why global commodity prices are crashing and what it means for
       India

   More from Quartz

National Journal

     * Political TV Ads Will Soon Reach Facebook-Level Creepiness
     * Ted Cruz Banks on Foreign Policy as His 2016 Differentiator
     * Democratic House Candidates Are Walloping Republicans in the
       Small-Money Game

   More from National Journal

Defense One

     * This Site Tracks the Guns Going Into Syria
     * Our Best Bet Against ISIL: Kurdish Crude
     * How American Precision Weapons Opened the Door to an Arab Coalition

   More from Defense One

Follow The Atlantic

     * App store
     * Google Play
     * Facebook
     * Twitter
     * Linkedin
     * Google Plus
     * Tumblr
     * RSS

E-Newsletters

     * Today's Top Stories
     * This Week
     * This Month
     * New at In Focus
     * CityLab
     * 5 Best Columns
     * Today's News

Information

     * FAQ
     * Subscribe Help
     * Masthead
     * Store
     * Emporium
     * Jobs
     * Privacy
     * Site Map
     * Terms and Conditions
     * Advertise
     * Advertising Guidelines
     * Press
     * Contact Us
     * Special Reports
     * Atlantic Scene
     * Books
     * Events
     * Atlantic Media

Subscribe

   [large.jpg?nc2mvq] Get 10 issues a year and save 65% off the cover
   price
   ______________________________
   ______________________________
   ______________________________
   ______________________________
   ______________________________
   [STATE]         __________
   ______________________________
   (Submit) Next ►

Fraud alert regarding The Atlantic
     __________________________________________________________________

   Copyright © 2014 by The Atlantic Monthly Group. All Rights Reserved.
   CDN powered by Edgecast Networks. Insights powered by Parsely .

   Powered by the Parse.ly Publisher Platform (P3).

   [img]
