
     * Massachusetts Institute of Technology

     * News
     * Video
     * Social

   Follow MIT
     * MIT News RSS
     * Follow MIT on Twitter
     * Follow MIT on Facebook
     * Follow MIT on Google+
     * Follow MIT on Instagram
     * Follow MIT on Flickr
     * Follow MIT on YouTube

   MIT News Office

MIT News Office

   Browse or
   ____________________ Submit

Browse

     *

Most Popular
          + Study: Online classes really do work
          + Chemists recruit anthrax to deliver cancer drugs
          + Using science for service
          + Q&A: Science journalism and public engagement
          + Can you out-race a computer?
          + Letter to the community on East Campus/Kendall Square design
            firm selection
          + Community picnic to honor former ombudsperson Mary Rowe
          + 3 Questions: Calestous Juma on African development
     *

By Topic
          + Computer Science and Artificial Intelligence Laboratory
            (CSAIL)
               o Can you out-race a computer?
               o MIT Professional Education announces new offerings of
                 Online X professional course on big data
               o Fingertip sensor gives robot unprecedented dexterity
               o Will tomorrow’s robots move like snakes?
          + Computer vision
               o Can you out-race a computer?
               o Fingertip sensor gives robot unprecedented dexterity
               o Where to grab space debris
               o An end to drug errors?
          + Electrical Engineering & Computer Science (eecs)
               o Can you out-race a computer?
               o Battling superbugs
               o Engineered proteins stick like glue — even in water
               o Magnetic fields make the excitons go ’round
          + Imaging
               o Extracting audio from visual information
               o [20130729121753-0.jpg?itok=y06kSlOK] McGovern Institute
                 gets new brain scanner
               o Multiview 3-D photography made simple
               o [20130104145954-3.jpg?itok=yGDImtpd] Tiny tools help
                 advance medical discoveries
          + Research
               o How to make a “perfect” solar absorber
               o Know thy banker — it could keep you solvent
               o Biologists find an early sign of cancer
               o Underwater robot for port security
       See All Topics
     *

By School
          + School of Architecture + Planning
               o Soft design for a sustainable world
               o 3 Questions: Calestous Juma on African development
               o MacArthur confers “genius” awards for playful math and
                 practical art
               o Sheila Kennedy awarded $100K Berkeley-Rupp Prize
          + School of Engineering
               o How to make a “perfect” solar absorber
               o Underwater robot for port security
               o How to make stronger, “greener” cement
               o Can you out-race a computer?
          + School of Humanities, Arts, and Social Sciences
               o MIT presents new music series: MIT Sounding
               o Evan Lieberman: Southern Africa as a lens on ethnicity,
                 governance, and citizenship
               o Using science for service
               o The Scottish referendum: What it means
          + Sloan School of Management
               o Know thy banker — it could keep you solvent
               o New master's track established integrating design and
                 management
               o Paradigm shifter
               o MIT ranked as nation’s No. 7 university by U.S. News
          + School of Science
               o Biologists find an early sign of cancer
               o Voices of MIT at the People’s Climate March
               o Tania Baker to be honored with Arthur Kornberg and Paul
                 Berg Lifetime Achievement Award
               o Researchers engineer new mouse model to study disease
     *

By Department
          + History
               o Said and Done for Summer 2014
               o [20131229084159-1_1.jpg?itok=cLnFjT-9] Anthropologist
                 Manduhai Buyandelger wins the 2013 Levitan Prize in the
                 Humanities
               o [20131213180343-0.jpg?itok=ILMgDLvS] The surprising story
                 of Mongolian shamanism
               o [20131105143220-0_1.jpg?itok=1W6eEVA1] Dower granted
                 major ‘lifetime achievement’ award in history
          + Physical Education
               o Sports Shorts for March 17: A weekly wrap-up of MIT
                 varsity athletics
               o Sports Shorts for March 10: A weekly wrap-up of MIT
                 varsity athletics
          + and Recreation
               o Sports Shorts for March 17: A weekly wrap-up of MIT
                 varsity athletics
          + Civil and Environmental Engineering
               o How to make stronger, “greener” cement
               o How to hide like an octopus
               o Protecting infrastructure with smarter CPS
               o Summer scholars deepen research skills
          + Linguistics and Philosophy
               o Said and Done for Summer 2014
               o A new leadership model for a new Haiti
               o From contemporary syntax to human language’s deep origins
               o Philosopher Sally Haslanger receives Ford Chair
       See All Departments
     *

By Center, Lab, & Program
          + Computer Science and Artificial Intelligence Laboratory
            (CSAIL)
               o Can you out-race a computer?
               o MIT Professional Education announces new offerings of
                 Online X professional course on big data
               o Fingertip sensor gives robot unprecedented dexterity
               o Will tomorrow’s robots move like snakes?
          + Biomimetics Robotics Lab
               o Bound for robotic glory
          + Research Laboratory of Electronics
               o Study: Online classes really do work
               o Engineered proteins stick like glue — even in water
               o Magnetic fields make the excitons go ’round
               o Toward optical chips
          + Computer Science and Artificial Intelligence Laboratory
            (CSAIL)
               o Can you out-race a computer?
               o MIT Professional Education announces new offerings of
                 Online X professional course on big data
               o Fingertip sensor gives robot unprecedented dexterity
               o Will tomorrow’s robots move like snakes?
          + Technology and Policy Program
               o Shrink-wrapping spacesuits
               o True Diversity: A Multiplier in Global STEM Innovation
       See All Centers, Labs, & Programs

   Login or Subscribe Newsletter
     * Sandy Pentland Sandy Pentland
       Photo: Sam Ogden
       Full Screen
     * Cover of “Social Physics: How Good Ideas Spread — The Lessons from
       a New Science
       Cover of “Social Physics: How Good Ideas Spread — The Lessons from
       a New Science"
       Full Screen

Social physics

   Sandy Pentland

   Media Lab professor’s new book ties more than a decade’s research into
   a new theory of information propagation in communities large and small.

   Larry Hardesty, MIT News Office
   March 4, 2014
   Press Inquiries Share

Press Contact

   Abby Abazorius
   Email: abbya@mit.edu
   Phone: 617-253-2709
   MIT News Office

Media Resources

   2 images for download

   Access Media

   Media can only be downloaded from the desktop version of this website.

Share

Comment

   Leave a comment

   Since 2001, the Human Dynamics Laboratory at the MIT Media Lab has used
   digital technologies — from home-brewed portable sensors to cellphone
   call records — to try to get a quantitative handle on the nature and
   the consequences of different types of human social interactions. The
   group’s focus has ranged from the very small, such as speed-dating
   sessions, to the very large, such as entire cities.

   In a new book, “Social Physics: How Good Ideas Spread — The Lessons
   from a New Science,” Alex “Sandy” Pentland, the Toshiba Professor of
   Media Arts and Sciences and the director of the Human Dynamics
   Laboratory, draws all that research together into a new theory of human
   social interaction, which he then applies to questions of
   organizational management, urban planning, and digital privacy.

   Pentland’s title appropriates the term that Auguste Comte, generally
   regarded as the father of sociology, initially applied to his own
   discipline. According to Pentland, the proliferation of mobile-sensor
   data in the Internet age, the advent of new mathematical tools for
   analyzing network interdependencies, and the power of modern computers
   mean that the aspiration to quantitative rigor in the term “social
   physics” is less far-fetched that it once was.

   “We have enough data to take all of these theories about people and
   innovation and good decision-making and make them quantitative,”
   Pentland says. “And when you do that, you find that there are some
   reasonably simple principles that account for 80, 90 percent of the
   variance in some cases.”

   Being there

   As Pentland argues in the book, those principles have to do with the
   interplay of two distinct types of information propagation, which he
   calls “exploring” and “engagement.” Exploring represents exposure to
   novel ideas; engagement is the type of face-to-face social interaction
   in which nonverbal communication — the subject of Pentland’s first
   book, “Honest Signals” — still plays a crucial role.

   According to “Social Physics,” however good an idea may look on paper —
   or on a computer screen — engagement is still the mechanism whereby it
   takes root in a community. “Adopting habits is a very conservative
   process that seems to be driven very largely by social learning, by
   seeing other people doing the same thing,” Pentland says. “Habits are
   things that sort of fire off automatically. You don’t want to get bad
   habits in your repertoire, because they’re real hard to get rid of. But
   when you’re exploring new ideas, you want to take everything you
   possibly can, because there’s really no cost to that.”

   The importance of balancing exploration and engagement, Pentland says,
   is something that emerges again and again in his group’s research. One
   telling example, described in “Social Physics,” involves the
   stock-trading site eToro. Members of this site can choose to reveal
   their stock trades to each other, and any member may adopt — or in
   eToro parlance, “copy” — the trades of any other. Members receive
   financial rewards every time their trades are copied, creating an
   incentive for disclosure, but no one can tell whose trade anyone else
   is copying.

   But eToro granted Pentland’s group access to the entire network of
   trades for 10 million transactions executed by 1.6 million eToro
   members. Some eToro members were loners: They almost never copied
   anyone else’s trades. Others — unbeknownst to themselves — were trapped
   in what Pentland calls echo chambers: They were densely connected to
   each other but rarely copied any outsiders’ trades. The MIT researchers
   found that eToro members whose networks allowed them to cull from a
   wide range of strategies earned a 30 percent better return on their
   investments than either the loners or the members trapped in echo
   chambers.

   Scaling up

   A similar dynamic, Pentland says, governed a bank, a military
   installation, an IT consultancy, and several other organizations that
   his group studied; in each case, creating opportunities for employees
   to interact face to face — by, say, synchronizing their break times —
   increased productivity. Remarkably, the same principle seems to apply
   to entire cities, where GDP turns out to be highly correlated with
   opportunities for face-to-face encounters.

   One of the things Pentland’s lab is investigating is how to harness
   these effects. He and his students have, for instance, compared schemes
   for promoting changes in exercise or diet among groups of volunteers.
   In one scheme, volunteers receive a small financial reward if they meet
   particular goals; in another, they receive the same reward only if
   their peers meet the same goals. The difference between the success of
   the two schemes is not subtle, Pentland reports: The addition of peer
   pressure makes the program anywhere from twice to 16 times as
   successful.

   Indeed, it was an elaboration of the same peer-based incentive scheme
   that enabled Pentland’s group to win a contest that the Defense
   Advanced Research Projects Agency sponsored in celebration of the
   Internet’s 40th anniversary, in which competitors used social media to
   identify the locations of 10 weather balloons placed randomly around
   the country.

   “We’re not where economics is yet,” Pentland says. “That will take
   another 100 years. But we’re moving in some very promising directions.”
     __________________________________________________________________

   Topics: Big data, Books and authors, Reality mining

Comments

   View the discussion thread.

Press Mentions

     * John Naughton includes research by Professors Eric Brynjolfsson and
       Sandy Pentland for this Guardian article on Big Data. Both
       Brynjolfsson and Pentland acknowledge that Big Data analytics
       provide a great deal of information about individuals and
       organizations.
       The Guardian
     * Joshua Rothman writes for The New Yorker about Professor Alex
       "Sandy" Pentland’s book, Social Physics. “In fact, part of what
       makes the book so interesting is that Pentland has figured out how
       to capture, in numerical form, the intimate social vibrations of
       office life,” writes Rothman.
       The New Yorker
     * Randy Bean of The Wall Street Journal interviews Professor Alex
       “Sandy” Pentland on the transformational power of big data.
       “Scientists are discovering that we can begin to explain many
       things—financial crashes, revolutions, panics—that previously
       appeared to be random events,” says Pentland.
       The Wall Street Journal
     * New York Times reporter Steve Lohr profiles the work of Professor
       Alex “Sandy” Pentland, director of the Human Dynamics Laboratory at
       the MIT Media Lab, Pentland’s new book, “Social Physics: How Good
       Ideas Spread – The Lesson From a New Science,” argues that data
       collected about everyday human interaction can be used to
       accelerate the pace of innovation.
       New York Times

Related

     * Human Dynamics Laboratory
     * MIT Technology Review: “Social Studies”

Archives

     * Why innovation thrives in cities

About This Website

   This Website is maintained by the MIT News Office.
     * About the MIT News Office
     * MIT News Press Center
     * Press Inquries
     * Filming Guidelines
     * Contact Us
     * Terms of Use

     * RSS
     * Twitter
     * Facebook
     * Google+
     * Instagram
     * Flickr
     * YouTube

     * MIT Homepage
     * MIT Video
     * MIT Connect
     * MIT Resources
     * Events Calendar

     * About MIT
     * Admissions
     * Alumni
     * Education
     * Labs and Centers

Resources

     * Submit Campus News
     * Pitch a Story
     * Sign Up for Newsletter
     * Subscribe to Press Releases
     * Terms of Use

   GIVE TO MIT
   Massachusetts Institute of Technology

   MIT News Office • Building 11-400
   Massachusetts Institute of Technology • Cambridge, MA 02139-4307

   Back to the top
