    #The Verge - All Posts

   Trending now

Those Coke cans with names on them increased sales for the first time in a
decade

     *

Watch this: new 'Jupiter Ascending' trailer delivers more space rollerblades
     *

AT&T is offering double data for its largest Mobile Share plans with new
promotion
     *

Instagram reportedly blocked in mainland China as protests in Hong Kong
intensify

     *
     *
     *
     *
     *

   5 New articles
   Previous

September 28, 2014

     * 9:07 PM Last night on 'Doctor Who,' a caretaker and a new companion
     * 6:04 PM Instagram reportedly blocked in mainland China as protests
       in Hong Kong intensify
     * 4:57 PM Classical musicians honor 'Batman' theme songs with an
       incredible music video journey
     * 2:28 PM Those Coke cans with names on them increased sales for the
       first time in a decade
     * 12:36 PM iPhones and iPads star in this intricately animated love
       story
     * 11:58 AM Watch Chris Pratt and the 'Saturday Night Live' cast push
       the superhero genre to its limits

     * 10:23 AM Japanese telecom giant SoftBank reportedly in talks to
       acquire DreamWorks Animation
     * 12:11 AM Incomplete episodes from canceled 'Star Wars: The Clone
       Wars' animated show released online

September 27, 2014

     * 7:41 PM New app from the makers of Secret sends you mysterious
       notifications throughout the day
     * 6:32 PM Microsoft reveals 'Windows TH' naming on new Technical
       Preview site
     * 4:00 PM AT&T is offering double data for its largest Mobile Share
       plans with new promotion
     * 2:26 PM Yahoo Directory, once the center of a web empire, will shut
       down at year's end
     * 12:16 PM These animated GIFs bring classic music albums to life
     * 11:04 AM Microsoft expected to unveil new Windows name next week

     * 10:09 AM Everything to do, see, and read this weekend
     * 8:14 AM Florida has turned to a Marvel superhero to sell more
       orange juice
     * 2:08 AM Watch this: new 'Jupiter Ascending' trailer delivers more
       space rollerblades

   Next
   Menu
     * Default-avatar.v9899025 Log in | Sign up
     * Home
     * Longform
     * Video
     * Reviews
     * Tech
     * Science
     * Culture
     * Design
     * Business
     * US & World
     * Forums
     * Search ____________________
     * More Sections
     *

     *
     *
     *
     *
     *

     * Back

     * Home

Longform

     * All Longform
     * All Verge Features

Video

     * All Video
     * 90 Seconds
     * Detours
     * Features
     * On The Verge
     * Reviews
     * Small Empires
     * The Verge Mobile Show
     * The Vergecast
     * Top Shelf
     * Verge Update

Reviews

     * All Reviews
     * See All Products

Tech

     * All Tech
     * Apple
     * Google
     * Microsoft
     * Mobile
     * Photography
     * Home
     * Apps

Science

     * All Science

Culture

     * All Culture
     * Entertainment
     * Web
     * Gaming
     * Movie Reviews

Design

     * All Design
     * Architecture
     * Typography
     * Concepts

Business

     * All Business
     * Policy & Law

US & World

     * All US & World
     * Politics
     * National Security

Forums

     * All Forums
     * Apple Core
     * Apps & Software
     * Betamaxed
     * Book Club
     * Events
     * Gaming
     * Googleplex
     * Hacks / DIY
     * Linux / Open Source
     * Meta
     * Microsoft Tribe
     * Mobile
     * Off-topic / chit-chat
     * PCs
     * Science
     * Tablet Talk
     * The Firm
     * The Fringe
     * The Lens
     * Transportation
     * Web & Social

     *

Previous Story
       The Flash is a horrible runner in this new poster
     *

Next Story
       A physics experiment might soon tell us if we're living in a 2D
       hologram

     * Business
     * Tech
     * Exclusive
     * Report

This is Uber's playbook for sabotaging Lyft

   'Brand ambassadors' with burner phones and credit cards attempt to
   #shavethestache
     * By Casey Newton
     * on August 26, 2014 03:42 pm
     *
     * @CaseyNewton
     *

   222
   Don't miss stories follow The Verge
   Like Follow Subscribe Follow
   Share on Facebook Tweet Share Share Pin Share

   Uber is arming teams of independent contractors with burner phones and
   credit cards as part of its sophisticated effort to undermine Lyft and
   other competitors. Interviews with current and former contractors,
   along with internal documents obtained by The Verge, outline the
   company’s evolving methods. Using contractors it calls "brand
   ambassadors," Uber requests rides from Lyft and other competitors,
   recruits their drivers, and takes multiple precautions to avoid
   detection. The effort, which Uber appears to be rolling out nationally,
   has already resulted in thousands of canceled Lyft rides and made it
   more difficult for its rival to gain a foothold in new markets. Uber
   calls the program "SLOG," and it’s a previously unreported aspect of
   the company’s ruthless efforts to undermine its competitors.
     __________________________________________________________________

   Together, the interviews and documents show the lengths to which Uber
   will go to halt its rivals’ momentum. The San Francisco startup has
   raised $1.5 billion in venture capital, giving it an enormous war chest
   with which to battle Lyft and others. While the company’s cutthroat
   nature is well documented, emails from Uber managers offer new insight
   into the shifting tactics it uses to siphon drivers away from
   competitors without getting caught. It also demonstrates the strong
   interest Uber has taken in crushing Lyft, its biggest rival in
   ridesharing, which is in the midst of a national expansion.

   After The Verge asked Uber for comment on its report, the company
   stalled for time until they could write this blog post introducing
   Operation SLOG to the world. "We never use marketing tactics that
   prevent a driver from making their living — and that includes never
   intentionally canceling rides," the company said.

‘A special ongoing project’

   Earlier this month, CNN reported that Uber employees around the country
   ordered and then canceled 5,560 Lyft rides, according to an analysis by
   Lyft. (Lyft arrived at this figure by cross-referencing the phone
   numbers of users who tried to recruit Lyft drivers to Uber with users
   who had previously canceled rides.) Uber flatly denied trying to
   sabotage its competitor: "Lyft’s claims against Uber are baseless and
   simply untrue," the company said.

   ""Uber is flat-out lying to their customers.""

   But one Uber contractor The Verge spoke with said Lyft’s complaint had
   merit. "What’s simply untrue is that not only does Uber know about
   this, they’re actively encouraging these actions day-to-day and, in
   doing so, are flat-out lying both to their customers, the media, and
   their investors," the contractor said. Until now, the canceled Lyft
   rides have been understood as a kind of prank call designed to keep
   competitors’ drivers off the road. But interviews and internal
   documents suggest another reason: Uber’s recruitment program has vastly
   increased in size and sophistication, and recruiters cancel rides in
   part to avoid detection by Lyft.

   The ground troops in Uber’s sabotage campaign are the company’s
   ambassadors, some of whom it hires through TargetCW, a San Diego-based
   employment agency. For the most part, ambassadors work at events or on
   college campuses, promoting Uber as a cheap and easy way of getting
   around town. The primary goal is to recruit riders, not drivers, and
   Uber calls the activity "slanging." But since at least mid-summer, some
   brand ambassadors in New York have been turning their talents against
   Lyft. Using Uber-provided iPhones and credit cards, the contractors
   hail rides, strike up conversations with their drivers, and attempt to
   sign them up before they arrive at their destination. (In other cities
   recruiters travel with "driver kits" that include iPhones and
   everything else a driver needs to get started on Uber; ambassadors were
   told New York State does not allow this.) Compensation varies, but
   contractors can earn a $750 commission for successfully recruiting a
   single new driver to Uber, according to a contractor.

   "Organizing a street team"

   As Lyft has gotten better at sniffing out recruiters and banning them
   from the service, Uber has been forced to alter its tactics. In the
   run-up to Lyft’s high-profile launch last month in New York City, Uber
   organized a "street team" to analyze Lyft’s expansion strategy. On July
   9th, a marketing manager emailed a subset of the company’s contractors
   in New York city with a new opportunity. "We have a special ongoing
   project that we’re going to be rolling out next week and I wanted to
   get about 8–10 of you to help out," he wrote. "This is going to be
   completely based on your own personal hustle, as it’s not a typical
   onsite event. We are going to have you working on your own time helping
   us sign up Uber drivers, and there is HUGE commission opportunity for
   everyone you signup."

Operation SLOG

   The special ongoing project had a different codename: SLOG. Contractors
   in New York who responded to the "special ongoing project" message were
   invited to individual hour-long meetings with Uber marketing managers,
   who had traveled from Los Angeles and Washington, DC, to New York to
   oversee the team’s creation.

   It was there that the company laid out its plan, according to a
   contractor. With Lyft’s arrival in New York imminent, Uber said it was
   creating a "street team" charged with gathering intelligence about
   Lyft’s launch plans and recruiting their drivers to Uber. Contractors
   were then handed two Uber-branded iPhones and a series of valid credit
   card numbers to be used for creating dummy Lyft accounts. Uber assumed
   every contractor would be caught by Lyft eventually; the second phone,
   according to a contractor interviewed by The Verge, was issued so "you
   would have a backup phone if and when that happened so you wouldn’t
   have to go back."

   "Backup phones for days"

   A follow-up email outlined the process for recruiting Lyft drivers in
   detail. It emphasizes the importance of requesting rides from different
   physical locations so as not to arouse Lyft’s suspicions, suggests
   methods of recruiting, and outlines the process for signing up drivers
   on Uber’s platform.

   operationslog operationslog

   The message linked to an online form, which was still active as this
   story went to press, where Uber could collect information about the
   Lyft drivers.

   uber signup uber signup

   As their plans evolved, Uber realized the likelihood that Lyft drivers
   would be recruited multiple times by its team members and alert Lyft
   about the street team’s existence. The solution: a private group on the
   messaging app GroupMe where members of the street team could post Lyft
   driver profiles. That way, Uber contractors could make sure their Lyft
   driver had not already been pitched. "You guys will run into drivers
   you have already got in cars with," a Los Angeles-based marketing
   manager emailed the team. "Post the driver profiles in groupme when you
   request so people are aware."

   In messages to the contractors, Uber’s marketing managers are full of
   good cheer. "Hello my lovely Sloggers!" begins one note, which gives
   instructions for filling out some paperwork. Once that’s out of the
   way, she writes, "then it’s all the little Lyfts your hearts desire."
   She ends her sentence with the hashtag #shavethestache, a reference to
   the big pink mustaches Lyft drivers affix to their vehicles’ grilles.

   operationslog operationslog

   Uber appears to be replicating its program across the country. One
   email obtained by The Verge links to an online form for requesting
   burner phones, credit cards, and driver kits — everything an Uber
   driver needs to get started, which recruiters often carry with them.
   The form lists 10 cities, including LA, Seattle, Boston, Miami, and
   Washington, DC. "We are growing and growing so with that said this will
   put some organization to your madness," says the form, which was still
   live at the time of publication. "I need BA phones to make a lyft
   account," reads one line, referring to brand ambassadors; "Great how
   many do you need," reads the line below.

   ""This will put some organization to your madness!""

   operationslog operationslog

   Uber’s aggressive tactics reflect the fact that ridesharing is largely
   a zero-sum game: a driver picking up an Uber customer can’t
   simultaneously pick up a Lyft customer. (Drivers are allowed to drive
   for both services, though the companies discourage the practice.)
   Having more active drivers on the road creates a virtuous circle that
   improves geographical coverage, increases demand, and allows services
   to lower prices by taking a smaller cut from a growing number of rides.
   Uber and Lyft are competing to become the first app you think of when
   you need a taxi, and the service with the most drivers likely stands
   the best chance of winning.

   That helps to explain why competition between the two has become so
   vicious, with Uber and Lyft both offering hefty bonuses and other perks
   to drivers who switch services. For a time, Uber lost money on every
   ride to help spur demand. And Lyft has itself aggressively recruited
   Uber drivers, offering cash bonuses for joining, and hosting free taco
   lunches at its driver center. The Spy-vs.-Spy nature of their
   competition was revealed again earlier this month, when Uber caught
   wind of Lyft’s multi-passenger ridesharing offering and preemptively
   announced a nearly identical offering the night before Lyft made its
   announcement.

   Lyft declined to comment for this story. After Uber became aware that
   The Verge was asking questions, Target CW sent out multiple emails
   warning contractors that talking to the press violated a non-disclosure
   agreement they signed when they joined.
     * Related Itemscompetition uber lyft ridesharing ridesharing apps
       brand ambassadors shavethestache

More from The Verge

The Magic Capital of the World

Welcome to Colon, Magic Capital of the World

   By Kyle Chayka

Oculus' new prototype is where VR should be right now

   By Adi Robertson

How the hell did Vizio make a $999 4K TV?

   By Nilay Patel
   Sign
   up
     * Email Newsletter

   The best of The Verge, delivered daily – sign up for The Verge
   Newsletter.
   ____________________ Sign Up
   The
   Latest
     * Headlines

     * Last night on 'Doctor Who,' a caretaker and a new companion
     * Instagram reportedly blocked in mainland China as protests in Hong
       Kong intensify
     * Classical musicians honor 'Batman' theme songs with an incredible
       music video journey
     * Those Coke cans with names on them increased sales for the first
       time in a decade
     * iPhones and iPads star in this intricately animated love story
     * Watch Chris Pratt and the 'Saturday Night Live' cast push the
       superhero genre to its limits
     * Japanese telecom giant SoftBank reportedly in talks to acquire
       DreamWorks Animation

   Back to top ^
   ____________________
   The Sections
     * Longform
     * Video
     * Reviews
     * Tech
     * Science
     * Culture
     * Design
     * Business
     * US & World

   The Basics
     * Site Status
     * About
     * Contact
     * Tip Us
     * Forums
     * Jobs

   The Elsewhere
     * Facebook
     * Twitter
     * Google+
     * Tumblr
     * YouTube
     * Instagram
     * Subscribe

   Ethics Statement - Community Guidelines
   Terms of Use - Privacy Policy
   v2.0, September 2, 2014
   All Systems Operational Check out our status page for more details.

   © 2014 Vox Media, Inc. All rights reserved.

   X
   Eater The Verge Polygon SB Nation
   Log In Sign Up
   T F G
   Y O
   ____________________
   Open ID Log in

   ____________________

   ____________________ forgot?

   [ ] Remember me? Log in
   Log In Sign Up
   T F G
   Y O
   ____________________
   Open ID Log in

   ____________________

   ____________________

   ____________________

   [ ] Yes, I would like to receive a daily newsletter from The Verge and
   occasional dedicated newsletters from sponsors and/or partners.

   Continue

Forgot password?

   We'll email you a reset link.

   If you signed up using a 3rd party account like Facebook or Twitter,
   please login with it instead.
   ____________________
   Submit

Forgot password?

   Try another email?

Almost done,

   By becoming a registered user, you are also agreeing to our Terms and
   confirming that you have read our Privacy Policy.
   Register
   Spinner.vc97ec6e

Authenticating

Great!

   Choose an available username to complete sign up.

   ____________________

   Sign Up

   In order to provide our users with a better overall experience, we ask
   for more information from Facebook when using it to login so that we
   can learn more about our audience and provide you with the best
   possible experience. We do not store specific user data and the sharing
   of it is not required to login with Facebook.
   (*) Yes, share my data ( ) Please don't share my data
   Submit

   tracking_pixel_5345_tracker Quantcast
   [audmeasure.gif?liveconclientID=5497559777280&PageID=650423876&EventTyp
   e=view]
