   #publisher

   Our cookie policy has changed. Review our cookies policy for more
   details and to change your cookie preference.
   By continuing to browse this site you are agreeing to our use of
   cookies.

   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26dcopt%3Dist%26pos%
   3Dldr_top&sz=728x90|970x90|970x250&tile=1&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dsub_top&sz=2
   23x90&tile=2&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dpslug_top&sz
   =970x35&tile=3&c=470977173]

     * More from The Economist
          + The Economist digital editions
          + Newsletters
          + Events
          + Jobs.Economist.com
          + The Economist Store
          + Timekeeper saved articles
     * My Subscription
          + Subscribe to The Economist
          + Manage my subscription
          + Renew
     * Log in or register
     * Subscribe

   Search this site: _______________
   Search

The Economist

     * World politics
          + Politics this week
          + United States
          + Britain
          + Europe
          + China
          + Asia
          + Americas
          + Middle East & Africa
     * Business & finance
          + All Business & finance
          + Which MBA?
     * Economics
          + All Economics
          + Economics by invitation
          + Economics A-Z
          + Markets & data
          + Indicators
     * Science & technology
          + All Science & technology
          + Technology Quarterly
     * Culture
          + All Culture
          + More Intelligent Life
          + Style guide
          + The Economist Quiz
          + Book reviews
     * Blogs
          + Latest blog posts
          + Americas view
          + Analects
          + Babbage
          + Banyan
          + Baobab
          + Blighty
          + Buttonwood's notebook
          + Charlemagne
          + Democracy in America
          + Eastern approaches
          + Erasmus
          + Free exchange
          + Game theory
          + Graphic detail
          + Gulliver
          + Newsbook
          + Pomegranate
          + Prospero
          + The Economist explains
     * Debate
          + Economist debates
          + What the world thinks
          + Economics by invitation
          + Letters to the editor
     * Multimedia
          + Multimedia library
          + World
          + Business & economics
          + Science & technology
          + Culture
          + Events
          + The Economist in audio
     * Print edition
          + Current issue
          + Previous issues
          + Special reports
          + Politics this week
          + Business this week
          + Leaders
          + KAL's cartoon
          + Obituaries

Foreign students

Coming and going

Bright foreigners like to study in America. Shame they can’t stay

   Aug 30th 2014 | From the print edition
     * Timekeeper
       Close
       Save this article
       Click this to add articles to your Timekeeper reading list. Learn
       more »
       Rolex values your time. Timekeeper by Rolex.
     *
     * Tweet

   THE number of foreign students at universities in America reached a new
   high of 819,644 last year. Many of them came from China on F-1 visas,
   which are reserved for students. Chinese studying in America now number
   200,000, up from 16,000 in 2003. Students from India, South Korea and
   Saudi Arabia also flock to America’s top-notch universities.

   Foreign students contribute over $30 billion to the American economy,
   according to a new report from the Brookings Institution, a think-tank.
   But few are invited to stay past their studies. The number of H-1B
   visas, which are given to skilled foreign workers, has barely budged
   over the past decade (see chart). America is not trying to poach bright
   young minds, say officials. Research has shown that foreigners who
   study in America bring liberal values back home with them.
   In this section
     * Casting stones in the Granite State
     * The Help, updated
     * Quietly booming
     * Hunting for dividends
     * Coming and going
     * Bone appétit
     * The Rand Paul bubble

   Reprints
   Related topics
     * Politics
     * Think-tanks
     * Government and politics
     * Political policy
     * United States

   But American employers want those bright minds to stick around. Foreign
   students often study in fields—like science, technology, engineering
   and maths—where America has skills shortages. Under pressure from
   business, the White House is considering giving thousands of high-tech
   workers new green cards. More far-reaching reforms, though, will need
   the approval of Congress, which is unlikely.

   From the print edition: United States
     *
     * Tweet
     * Submit to reddit
     *
     *

   View all comments (41)
   Want more? Subscribe to The Economist and get the week's most relevant
   news and analysis.

     *

Print edition
       X
       Aug 30th 2014
       Aug 23rd 2014
       Aug 16th 2014
       Aug 9th 2014
     *

Next in The world this week
       X

Politics this week
     *

Next in The world this week
       X

Business this week
     *

Next in The world this week
       X

KAL's cartoon
     *

Next in Leaders
       X

Corporate settlements in the United States

The criminalisation of American business
       Companies must be punished when they do wrong, but the legal system
       has become an extortion racket
     *

Next in Leaders
       X

The euro zone

That sinking feeling (again)
       If Germany, France and Italy cannot find a way to refloat Europe’s
       economy, the euro may yet be...
     *

Next in Leaders
       X

NATO’s summit

Mr Putin’s wake-up call
       The Western alliance is responding better to Russian aggression in
       Ukraine. But there is more to do
     *

Next in Leaders
       X

India in Asia

Eastern promises
       Asia will gain from India finally taking foreign policy seriously
     *

Next in Leaders
       X

Ceasefire in Gaza

A war without winners
       Sadly, the end of the fighting is unlikely to mark the beginning of
       the peace
     *

Next in Letters
       X

On the sex business, Scotland, Iraq, college sports, Newfoundland

Letters to the editor
     *

Next in Briefing
       X

Criminalising the American company

A mammoth guilt trip
       Corporate America is finding it ever harder to stay on the right
       side of the law
     *

Next in United States
       X

New Hampshire’s Senate race

Casting stones in the Granite State
       Democrats cannot afford to lose New Hampshire if they are to retain
       control of the Senate. But they...
     *

Next in United States
       X

Domestic work in the South

The Help, updated
       Maids are no longer servants
     *

Next in United States
       X

South Dakota

Quietly booming
       How a neglected state is succeeding
     *

Next in United States
       X

Alaska’s bush country

Hunting for dividends
       The virtues and shortcomings of Eskimo capitalism
     *

Next in United States
       X

Dogs in restaurants

Bone appétit
       Some welcome progress towards a dog-eat-out world
     *

Next in United States
       X

Lexington

The Rand Paul bubble
       The libertarian senator from Kentucky is probably not the
       Republicans’ saviour
     *

Next in The Americas
       X

Colombia’s peace process

The moment of truth
       The government and the FARC grapple with victims, truth, justice
       and the mechanics of ending a...
     *

Next in The Americas
       X

The Caribbean

Twelve clueless men
       A drive to abolish jury trials
     *

Next in The Americas
       X

Peru’s media

Liberty’s enfant terrible
       Enrique Zileri, a fighter for press freedom and democracy and
       against corruption
     *

Next in Asia
       X

India looks east

A strenuous September
       India’s government is embarking on a whirlwind month of Asian
       diplomacy
     *

Next in Asia
       X

Alcohol in Kerala

Saturation point
       A heavy-handed solution to Kerala’s drinking problem
     *

Next in Asia
       X

Japan’s right wing

Unwelcome change
       A cabinet reshuffle poses risks for Japan’s ties with its
       neighbours
     *

Next in Asia
       X

Indonesian politics

Great expectations
       Indonesia’s constitutional court has confirmed that Joko Widodo
       will be the next president. He...
     *

Next in Asia
       X

Banyan

Passing the torch
       To add to its many woes, Timor-Leste has a succession problem
     *

Next in China
       X

State-owned enterprises

Fixing China Inc
       Reform of state companies is back on the agenda
     *

Next in China
       X

Religious sects

No-cult zone
       A murder at a McDonald’s has given the party a pretext for
       attacking an old foe
     *

Next in Middle East and Africa
       X

European jihadists

It ain’t half hot here, mum
       Why and how Westerners go to fight in Syria and Iraq
     *

Next in Middle East and Africa
       X

The hostage trade

Handsome ransoms
       The many motives for kidnapping in Syria
     *

Next in Middle East and Africa
       X

A ceasefire in Gaza

Long may it hold
       Israelis and Palestinians breathe a sigh of relief. But the respite
       may not last
     *

Next in Middle East and Africa
       X

Libya

Anarchy looms
       Foreign involvement and reckless militias make a flammable cocktail
     *

Next in Middle East and Africa
       X

South Africa and its parliament

Red-letter day
       Julius Malema and his populists may be getting under the ruling
       party’s skin
     *

Next in Europe
       X

France’s government

Adieu, Cuba à la française
       By getting rid of its leftists, François Hollande has created a
       more cohesive government. But the...
     *

Next in Europe
       X

French political fiction

What if it were true?
       When truth really is stranger than fiction
     *

Next in Europe
       X

Germany’s economy

Watching the wages
       Germany’s economy stutters, even if the fundamentals are strong
     *

Next in Europe
       X

Berlin’s mayor

Wowi bows out
       Klaus Wowereit jumps before he is pushed
     *

Next in Europe
       X

Ukraine and Russia

War, not peace
       The evidence of Russian incursions into eastern Ukraine becomes
       ever clearer
     *

Next in Europe
       X

Turkey’s new government

Davutoglu’s moment
       Turkey’s new president, Recep Tayyip Erdogan, picks a loyal prime
       minister
     *

Next in Britain
       X

Sexual exploitation

See no evil, hear no evil, speak no evil
       An utterly shocking—and distinctively British—child sex abuse
       scandal
     *

Next in Britain
       X

Scotland’s referendum endgame

A war of attrition
       The peculiar smallness of Scotland’s independence debate
     *

Next in Britain
       X

Business and Scottish independence

Grouse more
       Scottish firms worry a lot about separation, but talk about it less
     *

Next in Britain
       X
       UK only

Oil and gas

Mud wrestling
       Who is right about the North Sea?
     *

Next in Britain
       X
       UK only

Civil liberties

Speak loudly but carry no stick
       The government’s surprisingly liberal anti-terrorism regime
     *

Next in Britain
       X
       UK only

Buses

Up to speed
       Copying the capital is even harder than it looks
     *

Next in Britain
       X
       UK only

Architecture

Nasty, brutish and tall
       Champions of brutalist architecture are having some surprising
       successes
     *

Next in Britain
       X
       UK only

High streets

Strange town
       Why some streets in London stay resolutely the same
     *

Next in Britain
       X

Bagehot

David Cameron’s half-cocked war
       The prime minister needs to make a much clearer case for military
       intervention in Iraq
     *

Next in International
       X

The future of NATO

NATO flexes its muscle memory
       Russia’s aggression in Ukraine has made NATO’s summit in Wales the
       most important since the end...
     *

Next in Business
       X

Marketing

What are brands for?
       Brands are the most valuable assets many companies possess. But no
       one agrees on how much they are...
     *

Next in Business
       X

Accounting for brands

Untouchable intangibles
       Sometimes you see brands on the balance-sheet, sometimes you don’t
     *

Next in Business
       X

Cloud computing

Silver lining
       Tech giants are waging a price war to win other firms’ computing
       business
     *

Next in Business
       X

Online gaming

Streaming down the Amazon
       Why Amazon is buying a video-game streaming site
     *

Next in Business
       X

Burger King

Seventh time lucky?
       Why some firms are flipped more often than a beef patty on a flame
       grill
     *

Next in Business
       X

Natural gas in China

Shale game
       China drastically reduces its ambitions to be a big shale-gas
       producer
     *

Next in Business
       X

Schumpeter

A new green wave
       A few pioneering businesses are developing “sustainability
       policies” worthy of the name
     *

Next in Finance and economics
       X

Popping property bubbles

Choosing the right pin
       House prices in Europe are losing touch with reality again.
       Deflating the bubbles will not be easy
     *

Next in Finance and economics
       X

Global property markets

Frothy again
       Easy money is inflating house prices across much of the globe
     *

Next in Finance and economics
       X

Israel’s economy

Shekeled and bound
       The strong shekel is hurting Israel’s economy more than the
       conflict in Gaza
     *

Next in Finance and economics
       X

Japan’s bond market

Quantitative freezing
       Japanese bond traders say the central bank is stifling their market
     *

Next in Finance and economics
       X

Superstitious investors

Black-cat market
       Irrational investment habits lead to lower returns
     *

Next in Finance and economics
       X

Free exchange

Fluid dynamics
       America’s famously flexible labour market is becoming less so
     *

Next in Science and technology
       X

Biotechnology

A new opium pipe
       Narcotic drugs could soon be manufactured by yeast
     *

Next in Science and technology
       X

Pseudo-satellites

The west wind blows afresh
       A cheap alternative to satellites is starting to take off
     *

Next in Science and technology
       X

Animal colouration

Now you see me...
       ...now you don’t
     *

Next in Science and technology
       X

Precambrian animals

Making an impression
       An ancient jellyfish shows its muscles
     *

Next in Books and arts
       X

Modern Asian leaders

No unity in diversity
       Remembering the giants of 20th-century Asian politics
     *

Next in Books and arts
       X

Prison in America

Protection rackets
       Prison gangs are the rational solution to a growing problem
     *

Next in Books and arts
       X

Technology

Will the internet eat your brain?
       A neuroscientist warns
     *

Next in Books and arts
       X

Fiction

Multiple imaginings
       David Mitchell big heart and distant vision
     *

Next in Books and arts
       X

Food writing

Filling up
       Foodies and food crazes
     *

Next in Books and arts
       X

Michelangelo

The maestro’s maestro
       Six reasons why he’s the best
     *

Next in Obituary
       X

Obituary

Simin Behbahani
       Simin Behbahani, the “Lioness of Iran”, died on August 19th, aged
       87
     *

Next in Economic and financial indicators
       X

Interactive indicators
     *

Next in Economic and financial indicators
       X

Output, prices and jobs
     *

Next in Economic and financial indicators
       X

Trade, exchange rates, budget balances and interest rates
     *

Next in Economic and financial indicators
       X

The Economist commodity-price index
     *

Next in Economic and financial indicators
       X

Markets
     *

Next in Economic and financial indicators
       X

Poverty in Asia
     *

Print edition
       X
       Aug 30th 2014
       Sep 6th 2014
       Sep 13th 2014
       Sep 20th 2014

   From the print edition Aug 30th 2014
     * Comment (41)
     * Print
     * E-mail
     * Reprints & permissions
     *

   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dmpu_no_wrapp
   er_top&sz=20x20&tile=6&c=470977173]

   Advertisement
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dmpu_top&sz=3
   00x250|350x900|350x600|300x600&tile=7&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dabsribbon&sz
   =351x49&tile=8&c=470977173]
   Follow The Economist
     * Facebook
     * Twitter
       Follow @TheEconomist
     * Linked in
       Follow
     * Google plus
     * Tumblr
       Follow
     * Pinterest
       Follow
     * YouTube
       Follow
     * RSS
       RSS feeds by section & topic
       Excerpts from the print edition & blogs »
     * Mail
       Free e-mail newsletters
       Editor's Highlights, The World This Week, and more »

Latest updates »

   India, America and political theatre

   India, America and political theatre: I give you Narendra Modi

   Democracy in America 1 hrs 53 mins ago
   The Economist explains

   The Economist explains: The many names of ISIS (also known as IS,
   ISIL,...

   The Economist explains September 28th, 23:50
   Bill Gross and PIMCO

   Bill Gross and PIMCO: Overthrowing the Bond King

   Business and Finance September 28th, 17:11
   Lung exchanges

   Lung exchanges: Breathe deeply for the three of us

   Free exchange September 28th, 14:10
   The Canada-EU trade deal

   The Canada-EU trade deal: Signed, not sealed

   Americas view September 28th, 13:07
   Blackberry

   Blackberry: Not there yet

   Business and Finance September 27th, 17:03
   Cadillac

   Cadillac: A new standard?

   Business and Finance September 26th, 23:47
   More latest updates »

   Most popular
     * Commented

Commented

     * Mission relaunched 1America and Islamic StateMission relaunched
     * 2Hong Kong students on strike: Class struggle
     * 3Ukraine and Russia: Win some, lose more
     * 4Mars exploration: First time lucky
     * 5Hate speech in Japan: Spin and substance

   Advertisement
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dmpu_bottom&s
   z=300x250|50x50|300x600&tile=9&c=470977173]
   Products and events

   Have you listened to The Economist Radio on Facebook?
   The Economist Radio is an on-demand social listening platform that
   allows you to listen, share and recommend The Economist audio content

   Test your EQ
   Take our weekly news quiz to stay on top of the headlines

   In Other Words
   Try our new audio app and website, providing reporting and analysis
   from our correspondents around the world every weekday

   Want more from The Economist?
   Visit The Economist e-store and you’ll find a range of carefully
   selected products for business and pleasure, Economist books and
   diaries, and much more

   Advertisement
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dmpu_bottom_r
   ight&sz=300x250|45x45&tile=10&c=470977173]
   Classified ads
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dbutton1&sz=1
   25x125&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dbutton2&sz=1
   25x125&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dbutton3&sz=1
   25x125&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dbutton4&sz=1
   25x125&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dbutton5&sz=1
   25x125&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dbutton6&sz=1
   25x125&c=470977173]
   The Economist
     * Contact us
     * Help
     * My account
     * Subscribe
     * Print edition
     * Digital editions
     * Events
     * Jobs.Economist.com
     * Timekeeper saved articles

Sections

     * United States
     * Britain
     * Europe
     * China
     * Asia
     * Americas
     * Middle East & Africa
     * Business & finance
     * Economics
     * Markets & data
     * Science & technology
     * Culture
     * Multimedia library

Debate and discussion

     * The Economist debates
     * What the world thinks
     * Letters to the editor
     * The Economist Quiz

Blogs

     * Americas view
     * Analects
     * Babbage
     * Banyan
     * Baobab
     * Blighty
     * Buttonwood's notebook
     * Charlemagne
     * Democracy in America
     * Eastern approaches
     * Erasmus
     * Free exchange
     * Game theory
     * Graphic detail
     * Gulliver
     * Newsbook
     * Pomegranate
     * Prospero
     * The Economist explains

Research and insights

     * Topics
     * Economics A-Z
     * Special reports
     * Style guide
     * The World in 2014
     * Which MBA?
     * The Economist GMAT Tutor
     * Reprints and permissions

The Economist Group »

     * The Economist Intelligence Unit
     * The Economist Intelligence Unit Store
     * The Economist Corporate Network
     * Ideas People Media
     * Intelligent Life
     * Roll Call
     * CQ
     * EuroFinance
     * The Economist Store

View complete site index »

   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dslider&sz=1x
   1&tile=11&c=470977173]
   [a&t=subs%3Dn%26wsub%3Dn%26sdn%3Dn%26!c%3D21614225%26pos%3Dadcast&sz=25
   0x1000&tile=12&c=470977173]
     * Contact us
     * Help
     * About us
     * Advertise with us
     * Editorial Staff
     * Staff Books
     * Careers
     * Site index

     * Copyright © The Economist Newspaper Limited 2014. All rights
       reserved.
     * Accessibility
     * Privacy policy
     * Cookies info
     * Terms of use

   Quantcast

   IFRAME:
   //4396156.fls.doubleclick.net/activityi;src=4396156;type=Econo014;cat=E
   cono0;ord=1;num=1?
