    #alternate

   (BUTTON) ____________________
     * Sign In
     * Username
     * PostTV
     * Politics
     * Opinions
     * Local
     * Sports
     * National
     * World
     * Business
     * Tech
     * Lifestyle
     * Entertainment
     * Classifieds
     * Jobs
     * Real Estate
     * Events
     * Rentals
     * Cars
     * WP BrandConnect
     * Subscribe

   washingtonpost.com © 1996-2014 The Washington Post

   Help and Contact Us

   Terms of Service

   Privacy Policy

   Submissions and Discussion Policy

   RSS Terms of Service

   Ad Choices

   Sections
   The Washington Post
   New therapies raise hope for a breakthrough in tackling cancer
   ____________________ (BUTTON)
   Sign In
   Username
   Subscribe
   Health & Science

New therapies raise hope for a breakthrough in tackling cancer

   Share on Facebook
   Share on Twitter
   Share on Google Plus
   Share via Email
   More Options
   Share on LinkedIn
   Share on Pinterest
   Share on Tumblr
   Resize Text
   Print Article
   Comments
   [iStock_000004443081Medium.jpg?uuid=TwuukpXLEeOWFtNn-m6pmw]
   (iStockphoto/Handout)
   By Arthur Allen February 17

   In the summer of 2012, a year after his wife had died of lung cancer,
   Michael Harris scraped open an old mole on his back and it would not
   stop bleeding. The doctors said he had stage 4 melanoma, with a
   virtually inoperable tumor, and that patients in his condition
   typically lived about eight months. By last June, the cancer had spread
   to his liver and lungs.

   At that point Harris joined a clinical trial at Georgetown University,
   one of scores that have sprung up around the country to test a new
   class of cancer drugs called immune-checkpoint inhibitors. Two weeks
   after his first infusion, Harris’s primary tumor was fading, along with
   the black cancerous beads around it. A month later, his liver and lungs
   were clean.

   “This stuff was like vanishing cream,” says Harris’s daughter, Rhonda
   Farrell. Today, Harris, a sun-
   leathered 66-year-old Vietnam veteran from Waldorf, Md., is back at
   work. And though his doctors won’t declare him cured, he says, “I feel
   like a normal person.”

   Because it can be so inexorable and deadly, cancer tends to inspire
   hopes of miracle cures. Because of all the failed miracle cures, cancer
   doctors are a cautious lot. This makes it all the more astounding to
   hear cautious clinicians and scientists describe the treatments Harris
   and thousands of others are receiving.

   “It’s a breakthrough,” says oncologist Michael Atkins, who recruited
   Harris to the trial at Georgetown’s Lombardi Cancer Center. “This is
   real,” adds Louis Weiner, the physician who leads the center. “We’re
   still in a bit of shock,” says Suzanne Topalian, a cancer immunologist
   at Johns Hopkins University who has been a key player in bringing the
   substances into clinical trials.
   [w-cancergraphic_promo.jpg?uuid=Z-AtMJg3EeOuRUWJJ8zttg] View Graphic
   Weighing the impact of cancer by years lost to the disease.

   Immune-checkpoint blockade is a form of immunotherapy, meaning it aims
   to help the patient’s own immune system fight cancer. It uses
   substances called monoclonal antibodies, which are designed by drug
   companies to target extremely specific molecules on cell surfaces. In
   this case, the antibodies unblock a reaction that stops the immune
   system’s natural attack on invading cancer cells.

   Although a range of new cancer treatments, such as targeted
   chemotherapy for breast cancer and cell-signaling inhibitors for
   leukemia, have shown positive effects over the past two decades, the
   checkpoint inhibitors seem to be providing uniquely long-term benefits.
   At least seven drug companies are testing the antibodies.

   Topalian’s husband, Drew Pardoll, also a Hopkins cancer immunologist,
   predicts that five years from now, half of the 600,000 Americans who
   receive diagnoses of advanced cancer each year will receive checkpoint
   inhibitors or other immune-related therapies.

   Medical, commercial and patient interest in the new drugs is intense.
   “Research activity is just going through the roof,” Topalian says.
   While Bristol-Myers Squibb, Merck and other companies rush to get their
   versions of the therapy approved by the Food and Drug Administration
   for treatment of melanoma and lung and kidney cancers, the substances
   also are being tested in smaller trials against cancers of the blood,
   colon, stomach, breast, bladder, liver, head and neck and brain. “The
   field is just afire now,” says immunologist Gordon Freeman of the
   Dana-Farber Cancer Institute in Boston.

   The checkpoint inhibitors may also have uses in battling some chronic
   infections. Trials using the antibodies against hepatitis B, HIV and
   even the blood infections that contributes to 200,000 U.S. deaths each
   year are underway or in planning stages.

   Not everyone, though, is convinced that the checkpoint inhibitors are
   quite so tide-turning. Stephen A. Rosenberg, who has led immunotherapy
   research for decades at the National Cancer Institute and has studied
   the checkpoint inhibitors, is a skeptic.

   “Because [the antibodies] take advantage of natural immune reactions,
   they only are likely to work in a small number of cancers,” Rosenberg
   says. “The path to treatment of cancers that . . . kill 90 percent of
   cancer patients is likely to be through genetic manipulation of the
   immune system.” Rosenberg is the pioneer in such genetic treatments. He
   has had 40 percent cure rates in some small melanoma trials at NIH.
   How they work

   One way our bodies deal with infections, and with cancer is by
   activating immune cells, called T-cells, which recognize foreign agents
   and marshal various parts of the immune system to clear or control
   them. Certain types of T-cells infiltrate tumors and release chemical
   signals that tell other parts of the immune system to attack. But one
   of these signals, a chemical called interferon-gamma, tells tumor cells
   to produce a molecule that actually blocks the T-cell response.

   This inactivation switch probably evolved to keep our immune systems
   from going haywire — overreacting and damaging organs. In dealing with
   cancer, however, the mechanism is a Catch-22, because it allows the
   cancer to grow.

   So in the mid-1990s, scientists began designing monoclonal antibodies
   to short-circuit the immune switch-off. Most of the checkpoint
   inhibitors under development target a protein on T-cells that
   scientists in 1992 named “Programmed Death Receptor 1” (at the time
   they knew only of its role in the natural death process of cells); it
   is now called PD-1. Other monoclonal antibodies target a tumor molecule
   that binds with PD-1 and is called PD-L1. This molecule appears only on
   the surface of certain tumor cells when they are under attack from
   T-cells; interferon-gamma causes it to appear.

   About 3,000 American and European patients have received nivolumab, the
   anti-PD1 drug that Michael Harris is receiving, according to Michael
   Giordano, global director of oncology and immunoscience for
   Bristol-Myers Squibb. Roughly half of the kidney cancer or melanoma
   patients in PD-1 trials have seen their tumors shrink significantly or
   disappear, according to Pardoll. Cures are difficult to speak of in
   drugs this new, but about 24 percent of lung cancer patients receiving
   the drug, for example, have survived at least two years. With previous
   treatments, which rely on chemotherapy, only about 5 percent of such
   patients survived two years.

   Even the most enthusiastic supporters of the checkpoint inhibitors
   acknowledge that about half their patients have not benefited. They
   don’t entirely know why, but many of those who don’t respond to the
   antibodies lack the PD-L1 molecule on their tumor cells. Their tumors
   may be using other molecules to switch off the immune response.

   In Harris’s case, it is only six months since he began the therapy.
   It’s not clear that his melanoma has disappeared altogether. He retains
   about a dozen black spots on his back that could be active or dead
   tumor. His doctors at this point classify him as “a partial response.”

   “Unfortunately,” Harris says, “there’s no prognosis except that if
   things stay good, they stay good.”

   Harris is a cable installation contractor, a “happy-go-lucky guy who
   doesn’t fret over his disease on the Internet,” Atkins says. Harris’s
   daughter makes sure he gets to appointments, and while he does what the
   doctors say he should do, he focuses on enjoying life — his three
   children and seven grandchildren and, for example, the country music
   festival he’ll attend next month in Austin.

   Harris has had few side effects, other than a slight rash. A few
   patients have had toxic immune responses; three early nivolumab
   patients died of lung inflammations. Since then, clinicians have gotten
   more vigilant, and they use other drugs to prevent such calamities.

   M. Dennis Sisolak, a 72-year-old from Bel Air, Md., had late-stage
   kidney cancer in 2009 when he began 18 months of nivolumab infusions at
   Johns Hopkins Hospital. His tumors disappeared a few months after the
   treatment, and his scans have been clean since. “The only side effect
   was the annoyance of having to drive an hour and a half to Baltimore
   every two weeks,” Sisolak says.
   ‘Breakthrough of the Year’

   The emergence of checkpoint inhibitors, which Science magazine declared
   2013’s Breakthrough of the Year, is a high point in the long story of
   cancer immunotherapy. In 1891, William Coley, a New York surgeon,
   discovered he could keep certain cancer patients alive by giving them
   bacterial infections, which caused their immune systems to release a
   healing serum.

   Over the years, many intrigued scientists tried to extend Coley’s
   experiments, and in 1975 they isolated the immune elixir and named it
   tumor necrosis factor. But immunotherapy had few big successes until
   1985, when the NCI’s Rosenberg managed to cure several melanoma
   patients with another immune chemical, interleukin-2. This work was
   validated by outside investigators led by Atkins — who was then at
   Harvard Medical School — leading to FDA approval in 1997. Oncologists
   have employed it since then against melanoma and kidney cancer, with
   occasionally wonderful results, but it causes severe side effects.

   Many other immunotherapies are being tested on cancers. In fact, when
   Harris received his diagnosis in August 2012, his doctors recommended
   that he enter one such clinical trial under Rosenberg’s care. Harris
   spent eight weeks that fall and winter at the NIH Clinical Center
   undergoing a delicate and complicated care regimen.

   Doctors zapped his immune system after culling his blood for T-cells,
   which they genetically tweaked to better fight his tumor and then
   returned to his body. Rosenberg and his staff have had some dramatic
   cures with variations on this therapy, but it didn’t work for Harris.

   By February, his cancer had shrunk a little, but in April new tumors
   appeared. Rosenberg’s team pressed for Harris to receive
   checkpoint-inhibiting antibodies. When a trial opened at Georgetown in
   June, Harris was the first of only 10 patients admitted.

   “We had patients coming out of the woodwork trying to enter the trial,”
   says Atkins, who with other physicians at Lombardi is running several
   other studies of the blockade inhibitors, sometimes in combination with
   other drugs. “We had calls from Australia, Israel, Eastern Europe.”
   A fundamental difference

   Immunotherapy is fundamentally different from other cancer research
   funded by NIH. Many other lines of investigation are aimed at
   identifying the genes that turn off and on in a particular cancer and
   at matching patients to drugs that target the genes of their particular
   tumor.

   These new, sophisticated forms of molecular medicine are clearly a step
   forward from older chemotherapies, which use powerful drugs to kill
   cancer cells but often cause severe side effects and provide benefit
   only as long as the cancer finds ways to evade them — typically an
   average of six months.

   Checkpoint inhibition therapy’s champions believe that its approach
   holds more long-term promise. Instead of aiming at the tumor and its
   mutations, or accelerating the immune system the way interleukin-2
   does, the checkpoint inhibitor antibodies are designed to take the
   brakes off the system, Freeman says.

   “Cancers are like the Road Runner cartoon character. If you choose one
   target in the cancer, it will sidestep it eventually by mutating,” he
   says. Chemotherapy usually fails, eventually, because the tumor evolves
   a way to beat it. Since the checkpoint inhibitor restores the immune
   system’s ability to attack, the cancer “can’t change one thing and
   escape detection, because it’s getting machine-gunned,” Freeman says.
   “The immune system is an evolutionary learning system. If you can
   engage it and get it to work successfully, it learns how to attack the
   cancer. And the wonderful thing is that it works.”

   Helen Harris, Michael Harris’s wife of 35 years, became ill too early
   for these new treatments. A lifetime smoker, she received a diagnosis
   of lung cancer in 2008 and died about three years later, with severe,
   heartbreaking complications in the final months.

   Harris and his daughter don’t know whether the treatments he received
   could have helped her back then. “Dad was a wonderful husband to her.
   She was a lucky lady,” Rhonda Farrell says. “We knew her kind of cancer
   wasn’t going to go away.”

   Allen is a freelance writer and author of “Vaccine: The Controversial
   Story of Medicine’s Greatest Lifesaver.” His new book, “The Fantastic
   Laboratory of Dr. Weigl,” will be released in July.
     *   Share on FacebookShare
     *   Share on TwitterTweet

   SECTION: {section=national, subsection=health-science}!!!
   INITIAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!!
   UGC FROM ARTICLE: {allow_comments=true, allow_photos=false,
   allow_videos=false, comments_period=14, comments_source=washpost.com,
   default_sort=, default_tab=, display_comments=true,
   is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}!!!
   FINAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!
   customFields- published 1392681420/1392681420000/1392681420 tracking:
   {authors=Arthur Allen, content_category=Health-Environment-Science,
   in_url_headline=new-therapies-raise-hope-for-a-breakthrough-in-tackling
   -cancer, section={section=national, subsection=health-science},
   show_ads=true, show_comments=true, ugc={allow_comments=true,
   allow_photos=false, allow_videos=false, comments_period=14,
   comments_source=washpost.com, default_sort=, default_tab=,
   display_comments=true, is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}}
   allow_comments: false published_date:Feb 17, 2014 11:57:00 PM close
   date: Mar 3, 2014 11:57:00 PM
   Comments
   SECTION: {section=national, subsection=health-science}!!!
   INITIAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!!
   UGC FROM ARTICLE: {allow_comments=true, allow_photos=false,
   allow_videos=false, comments_period=14, comments_source=washpost.com,
   default_sort=, default_tab=, display_comments=true,
   is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}!!!
   FINAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!
   customFields- published 1392681420/1392681420000/1392681420 tracking:
   {authors=Arthur Allen, content_category=Health-Environment-Science,
   in_url_headline=new-therapies-raise-hope-for-a-breakthrough-in-tackling
   -cancer, section={section=national, subsection=health-science},
   show_ads=true, show_comments=true, ugc={allow_comments=true,
   allow_photos=false, allow_videos=false, comments_period=14,
   comments_source=washpost.com, default_sort=, default_tab=,
   display_comments=true, is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}}
   allow_comments: false published_date:Feb 17, 2014 11:57:00 PM close
   date: Mar 3, 2014 11:57:00 PM

   SuperFan Badge

   SuperFan badge holders consistently post smart, timely comments about
   Washington area sports and teams.

   More about badges | Request a badge

   Culture Connoisseur Badge

   Culture Connoisseurs consistently offer thought-provoking, timely
   comments on the arts, lifestyle and entertainment.

   More about badges | Request a badge

   Fact Checker Badge

   Fact Checkers contribute questions, information and facts to The Fact
   Checker.

   More about badges | Request a badge

   Washingtologist Badge

   Washingtologists consistently post thought-provoking, timely comments
   on events, communities, and trends in the Washington area.

   More about badges | Request a badge

   Post Writer Badge

   This commenter is a Washington Post editor, reporter or producer.

   Post Forum Badge

   Post Forum members consistently offer thought-provoking, timely
   comments on politics, national and international affairs.

   More about badges | Request a badge

   Weather Watcher Badge

   Weather Watchers consistently offer thought-provoking, timely comments
   on climates and forecasts.

   More about badges | Request a badge

   World Watcher Badge

   World Watchers consistently offer thought-provoking, timely comments on
   international affairs.

   More about badges | Request a badge

   Post Contributor Badge

   This commenter is a Washington Post contributor. Post contributors
   aren’t staff, but may write articles or columns. In some cases,
   contributors are sources or experts quoted in a story.

   More about badges | Request a badge

   Post Recommended

   Washington Post reporters or editors recommend this comment or reader
   post.

   You must be logged in to report a comment.
   Sign in here

   You must be logged in to recommend a comment.
   Sign in here

   Comments our editors find particularly useful or relevant are displayed
   in Top Comments, as are comments by users with these badges: . Replies
   to those posts appear here, as well as posts by staff writers.

   All comments are posted in the All Comments tab.
   More about badges
   Get a badge

   To pause and restart automatic updates, click "Live" or "Paused". If
   paused, you'll be notified of the number of additional comments that
   have come in.
   Comments our editors find particularly useful or relevant are displayed
   in Top Comments, as are comments by users with these badges: . Replies
   to those posts appear here, as well as posts by staff writers.
     * Spam
     * Offensive
     * Disagree
     * Off-Topic

     *
          + Facebook
          + Twitter
          + Reddit
          + StumbleUpon
          + Digg
          + Delicious

   Most Read National
     * 1
       [imrs1.jpg]
       Scientists confess to sneaking Bob Dylan lyrics into their work for
       the past 17 years
     * 2
       [20140927_MICHAELBROWN_EDIT4.jpg]
       Michael Brown's mother: 'They robbed my son of his future'
     * 3
       Watching a tattoo needle in slow motion reveals the physics of
       getting inked
     * 4
       Arrest made in Indiana State University shooting
     * 5
       Neil deGrasse Tyson admits he botched Bush quote

   The Most Popular All Over
     * [400x225&h=60&w=80]
       The Baltimore Sun
       Unseld steps into spotlight to announce Wizards preseason game
     * [10620961236_5bd233aa5d_z.jpg?itok=G5e9o8Wd&h=60&w=80]
       PRI
       China says no to a shipment of US corn contaminated with GMOs — and
       surprising lawsuits follow
     * [farmersmarketBB3.jpg&h=60&w=80]
       WNYC - New York Public Radio
       ABCs: Apples; Bans; Cell Phones
     * [300x.jpg&h=60&w=80]
       The Dodo
       Brilliant German Shepherd Jailbreaks His Little Friend From Her
       Crate
     * [20140925__jeffoc-students-protests-columbine-high~p1_200.jpg&h=60&
       w=80]
       The Denver Post
       Massive protest near Columbine High School marks fourth day of
       Jeffco school walk outs
     * [Khorasan_Group-0f06e.jpg&h=60&w=80]
       The Washington Post
       FBI director: U.S. has identified the killer of two beheaded
       American journalists
     * [523f010d5177d.preview-300.jpg&h=60&w=80]
       St. Louis Post-Dispatch
       Starter cut-off devices keep car payments coming
     * [3036090-poster-p-1-190-bourdain-we-wil-have-what-he-is-having.jpg&
       h=60&w=80]
       Fast Company
       Anthony Bourdain Has Become The Future Of Cable News, And He
       Couldn't Care Less
     * [140924_bb_KThompson-montage.jpg.CROP.rectangle-large.jpg&h=60&w=80
       ]
       Slate
       Why Saturday Night Live Writers Lean on Kenan Thompson
     * [lead_large.jpg?ncest2&h=60&w=80]
       The Atlantic
       Murder in a Time Before Google
     * [b4s_fakebreast092414_13919185.jpg&h=60&w=80]
       Tampa Bay Times
       Tampa woman with three breasts? Suitcase find points to false front
     * [lowe-jpgStanley-Lowe.jpg&h=60&w=80]
       The Toledo Blade
       Ex-Pathway exec investigated
     * [20140924_brk_hal01.jpg&h=60&w=80]
       Honolulu Star-Advertiser
       Prosecutor: Hawaii prison gang 'kings of castle'
     * [phil_hartman-300x200.jpg&h=60&w=80]
       Salon
       Phil Hartman's final night: The tragic death of a "Saturday Night
       Live" genius

   [themost-290x60.png]
     * washingtonpost.com
     * © 1996-2014 The Washington Post
     *
     * Help and Contact Us
     * Terms of Service
     * Privacy Policy
     * Submissions and Discussion Policy
     * RSS Terms of Service
     * Ad Choices

   [p?c1=2&c2=3005617&cv=2.0&cj=1]
