   #All Mac Rumors Headlines Front Page Mac Blog iPhone/iOS Blog

   IFRAME: //www.googletagmanager.com/ns.html?id=GTM-NBTPJP

   Mac Rumors
   Got a tip for us? Let us know
     * a. Send us an email
     * b. Anonymous form
     * close (x)


     * Front Page
     * Mac Blog
     * iOS Blog
     * Roundups
          + AirPort [airport_roundup_menu.png]
          + Apple Pay [apple_pay_touch_roundup_menu.png]
          + Apple TV [apple_tv_roundup_menu.png]
          + Apple Watch [apple_watch_roundup_menu.png]
          + iMac [imac_roundup_menu.png]
          + iOS 8 [ios_8_color_roundup_menu.png]
          + iOS 8 Features [ios_8_color_roundup_menu.png]
          + iPad Air [ipad_air_roundup_menu.png]
          + iPad mini [retina_ipad_mini_roundup_menu.png]
          + iPhone 6 [iphone_6_6_plus_roundup_menu.png]
          + iPod nano [ipod_nano_roundup_menu.png]
          + iPod shuffle [ipod_shuffle_roundup_menu.png]
          + iPod touch [ipod_touch_roundup_menu.png]
          + Mac mini [mac_mini_roundup_menu.png]
          + Mac Pro [mac_pro_2013_roundup_menu.png]
          + MacBook Air [macbook_air_mav_ru_menu.png]
          + MacBook Pro [retina_macbook_pro_menu.png]
          + OS X Mavericks [os_x_mavericks_menu.png]
          + OS X Yosemite [os_x_yosemite_roundup_menu.jpg]
          + Thunderbolt Display [tb_display_mav_menu.png]
     * Buyer's Guide
     * Forums

   ____________________
   Facebook Twitter
     * Apple Pay
     * iPhone 6
     * Apple Watch
     * iOS 8
     * iOS 8 Features
     * iPad Air
     * iPad mini
     * Mac mini
     * MacBook Air
     * OS X Yosemite
     * Mac Pro
     * Apple TV
     * iMac
     * Thunderbolt Display
     * MacBook Pro
     * AirPort
     * iPod nano
     * iPod shuffle
     * iPod touch
     * OS X Mavericks
     * All >

   New in OS X: Get MacRumors Push Notifications on your Mac
   Resubscribe Now Close

Apple Hires Chief Medical Officer From Pulse Oximetry Company Masimo,
Possibly for iWatch Team

   Thursday January 30, 2014 2:10 pm PST by Juli Clover
   Over the course of the last year, Apple has made several hires from the
   medical and sensor field, presumably to bolster the team of experts
   working on its much-rumored smart watch project, and MacRumors today
   learned of another high-profile sensor expert that has joined the
   company.
   Michael O'Reilly, M.D., formerly the Chief Medical Officer and EVP of
   Medical Affairs at Masimo Corporation, left his position in July of
   2013 to take on a role at Apple, possibly on the iWatch team. News of
   O'Reilly's employment at Apple was first leaked to MobiHealthNews last
   week and when contacted for comment earlier today, Masimo told
   MacRumors it "could not dispute" what had been reported.
   While O'Reilly was at Masimo, the company developed several cutting
   edge pulse oximetry devices, including the iSpO2 Pulse Oximeter that
   connects to the iPhone and gives readings via an accompanying app. The
   iSpO2, which takes its readings from a finger, is designed to measure
   both oxygen saturation in the blood and pulse rate, with technology
   that allows it to take readings during movement and with low blood
   flow.
   ispo2pulseoximeterdevice

                     The iSpO2 Pulse Oximeter for iPhone

   While it is not clear what position O'Reilly holds with Apple or how
   his pulse oximetry expertise will be used by the company, he does join
   a number of other hires in the medical field that have reportedly been
   recruited for the iWatch team. In 2013, Apple hired several scientists
   and executives from notable sensor companies like AccuVein, C8
   MediSensors, and Senseonics, and two weeks ago, another report pointed
   to two additional hires in the sensor field.
   Reports have suggested that Apple's smart watch project, the iWatch,
   could focus heavily on health sensors and biometrics, possibly
   including features like a pedometer and a heart rate monitor. Apple's
   multitude of hires in the health field does suggest, however, that the
   company could include even more advanced sensor technology in the
   iWatch or in a future product.
   With the addition of O'Reilly, Apple has now hired employees with
   expertise in pulse oximetry, vasculature visualization (vein finding),
   non-invasive glucose monitoring, blood chemistry monitoring via
   microneedle, heart/breath rate monitoring, and fitness. Notably,
   several hires have also had experience with low-profile, non-invasive
   biosensor devices.
   On his LinkedIn page, O'Reilly is also listed as both an Adjunct
   Associate Professor of Anesthesiology at the University of Michigan and
   a Professor of Anesthesiology and Perioperative Care at the University
   of California, Irvine.
   Related roundup: Apple Watch
   [ 53 comments ]
     * [ispo2pulseoximeterdevice.jpg]
     * [ispo2pulseoximeterdevice.jpg]
     * [ispo2pulseoximeterdevice.jpg]

Top Rated Comments

   (View all)

   Avatar
   Sky Blue
   9 months ago
   damn! this iwatch is going to be a mobile hospital!
   Rating: 6 Votes
   Avatar
   IJ Reilly
   9 months ago

   The only thing I don't understand is whether or not this will be
   stand-alone device or not.
   The only thing? Nobody knows any thing.
   ----------

   damn! this iwatch is going to be a mobile hospital!
   Just wait till you see the prostate exam app!
   Rating: 5 Votes
   Avatar
   o0smoothies0o
   9 months ago

   I hope people can understand the potential of this product by now.
   Yeah, the sad part is that people still don't. 'Watches are useless'.
   Good thing Apple actually has intelligent, imaginative people working
   for them, as opposed to the people who can't even think past 'It tells
   time'.
   Rating: 5 Votes
   Avatar
   Rayd5365
   9 months ago

   it seems that the watch is not nearly as close to being finished as i
   would have hoped. if they are still hiring people for sensors they
   can't possibly be finished with the design or testing of the watch.
   hopefully they speed things up! :apple:
   Note though that the hire was supposedly made last July….
   Rating: 3 Votes
   Avatar
   iLondoner
   9 months ago
   At last, the penny has dropped for the watchers.
   The iWatch may well have some form of simple monitoring, but I reckon
   Apple is going much further into the medical field.
   Already iPads are used extensively in hospitals for displaying scan and
   x-ray results. Integrated medical systems could be the next big field
   for Apple, just as instrumentation was for Hewlett-Packard in the
   1960s. Could stray into Agilent
   (http://en.wikipedia.org/wiki/Agilent_Technologies)'s backyard.
   .
   Rating: 2 Votes
   Avatar
   IJ Reilly
   9 months ago

   I hope it doest require a probe :eek:
   Let's put it this way: It will put the "i" in iWatch.
   ----------

   At last, the penny has dropped for the watchers.
   The iWatch may well have some form of simple monitoring, but I reckon
   Apple is going much further into the medical field.
   Already iPads are used extensively in hospitals for displaying scan and
   x-ray results. Integrated medical systems could be the next big field
   for Apple, just as instrumentation was for Hewlett-Packard in the
   1960s. Could stray into Agilent
   (http://en.wikipedia.org/wiki/Agilent_Technologies)'s backyard.
   .
   I suspect you are onto something This is why I thought Apple might make
   a play for the remnants of Kodak, with their medical imaging products
   and patents.
   Rating: 2 Votes
   Avatar
   Compile 'em all
   9 months ago
   The iWatch is gonna be awesome!
   Rating: 1 Votes
   Avatar
   Illusion986
   9 months ago

   Just wait till you see the prostate exam app!
   I hope it doest require a probe :eek:
   Rating: 1 Votes
   Avatar
   springsup
   9 months ago
   I'm still totally unsold on the idea of carrying around a mobile
   medical station. I'm not a professional athlete; I don't need real-time
   statistics on what every organ in my body is doing, how much energy I'm
   using, etc.
   The Tarahumara people (http://en.wikipedia.org/wiki/Tarahumara_people)
   can run 200 mile-stretches over a couple of days, and AFAIK they don't
   use fitbits, Nike smart watches, iWatches or anything else. They drink
   beer and eat beans and squirrels.
   Not just their young people, either - even the middle-aged and elderly
   can run enormous distances.
   Point is: teching yourself up doesn't make you healthier or fitter.
   Some of the most primitive people on the planet could put our best
   olympic athletes to shame.
   That said, of course, I said I'm not sold on the idea. Maybe Apple will
   convince me, but if this really is a "health" statistics device, then
   no thanks.
   Rating: 1 Votes
   [ Read All Comments ]

Upcoming

     * [os_x_yosemite_roundup_menu.jpg]
       OS X Yosemite Fall 2014
       More modern look coming this fall.
     * [ipad_air_roundup_menu.png]
       iPad Air October 2014
       iPad Air with Touch ID, anti-reflective display coming soon.
     * [retina_ipad_mini_roundup_menu.png]
       iPad mini October 2014
       Retina iPad mini expected to gain Touch ID.
     * Mac mini October 2014?
     * Apple Watch Early 2015

More Blog Stories

     * iOS 8 Safari Supports Animated PNG Images
       56 minutes ago on iOS Blog
       [Animated_PNG_example_bouncing_beach_ball.png?thumbretina] With the
       release of iOS 8, Safari has gained the ability to display Animated
       PNGs (APNGs). Originally proposed in 2004 as a replacement to
       animated GIF images, APNGs offers more color and...
       13 comments
     * AT&T Doubling Data on Mobile Share Value Plans in Limited Time
       Promotion
       7 hours ago on iOS Blog
       [attdoubledata.jpg?thumbretina] AT&T today announced that it is
       launching a new limited-time promotion for its Mobile Share Value
       Plans, offering double the amount of data for new and existing
       customers with monthly data plans...
       82 comments
     * Supposed Internal Memo Suggests October 10 Launch for iPhone 6 in
       China
       8 hours ago on iOS Blog
       [chinaoctober101.jpg?thumbretina] Apple may be looking to launch
       the iPhone 6 and iPhone 6 Plus in China on October 10, according to
       an internal Apple retail employee memo shared by Techweb (Google
       Translate). The memo also states...
       9 comments
     * Apple Ceases Signing iOS 7.1.2, Downgrading No Longer Possible
       2 days ago on iOS Blog
       [ios_7_icon.jpg?thumbretina] As of today, Apple has stopped signing
       the iOS 7.1.2 firmware, which will prevent users from downgrading
       from iOS 8 back to iOS 7 (via iClarified). This means that users
       who are unhappy with the...
       163 comments
     * Buyer's Guide: Deals on Civilization V for Mac, iPhone 6 and 6 Plus
       Cases, and More
       2 days ago on Mac Blog
       [civilizationv.jpg?thumbretina] We've partnered with GameAgent this
       week to offer MacRumors readers a great deal on one of the best Mac
       games around -- Civilization V. From now until Sunday, readers can
       get Sid Meier's...
       21 comments
     * Apple's iPhone 6 and 6 Plus Quickly Dominate Japanese Smartphone
       Sales
       4 days ago on iOS Blog
       [APPLE-BCN-3-CARRIERS-AND-6-VS-6-PLUS.png?thumbretina] Apple's new
       iPhone 6 and 6 Plus handsets are dominating the Japanese market in
       their first week of sales, reports Forbes, which cited weekly sales
       rankings provided by Japan's BCN. iPhone...
       37 comments
     * Apple Launches Yosemite 'AirDrop Test Fest' For AppleSeed Members
       4 days ago on Mac Blog
       [airdroptestfest.jpg?thumbretina] Apple has sent out invites to
       multiple AppleSeed testers to invite them to participate in a
       "AirDrop Test Fest" to fix any potential bugs in the file sharing
       service ahead of the launch of OS...
       31 comments
     * iPhone 6 Touch ID Still Vulnerable to Specialized Fake Fingerprint
       Hack
       5 days ago on iOS Blog
       [photo-3-touchid.jpg?thumbretina] Apple has done little to improve
       security in the Touch ID technology used in its current iPhone 6
       handset, claims security researcher Marc Rogers of Lookout Security
       (via CNET). As shown by Rogers,...
       104 comments

   • Now TV Adds New Entertainment and Sky Movies Passes to Apple TV in UK
   (22)
   • iPhone 6 Plus Bending Limits Tested in New Video (542)
   • Apple Opening Retail Store in Hanover, Germany on September 27 (16)
   • 'iPod Father' Tony Fadell Comments on Discontinuation of iPod Classic
   (150)
   • Apple Releases OS X Yosemite Mail Update for Developers and Public
   Beta Testers (43)
   • iPhone 6 and 6 Plus Capable of Faster Charging Using iPad 2.1A
   Adapter (202)
   • iPhone 6 Adoption Easily Outpacing iPhone 6 Plus (128)

Rumors by Product

   iPhone - iPad - iPad Mini - iPod
   MacBook Pro - Retina MacBook Pro
   MacBook Air
   Mac mini - iMac - Mac Pro
   Blogs: iPhone - Mac

   MacRumors


   MacRumors attracts a broad audience of both consumers and professionals
   interested in the latest technologies and products. We also boast an
   active community focused on purchasing decisions and technical aspects
   of the iPhone, iPod, iPad, and Mac platforms.
   Advertise on MacRumors

Our Staff

   Arnold Kim
   Editorial Director
   Email • Twitter
   Eric Slivka
   Editor in Chief
   Email • Twitter
   Jordan Golson
   Editor
   Email • Twitter
   Marianne Schultz
   Editor
   Email • Twitter
   Juli Clover
   Editor
   Email • Twitter • Google+
   Husain Sumra
   Contributing Editor
   Email • Twitter
   Richard Padilla
   Contributing Editor
   Email • Twitter
   Kelly Hodgkins
   Contributing Editor
   Email • Twitter

Links

Touch Arcade

     * The TouchArcade Show - 174 - XXL iPhone XXL Edition
     * TouchArcade Game of the Week: 'Turbo Dismount'
     * Best iPhone and iPad Games of the Week: 9/26/14 - 'Anomaly
       Defenders', 'Smarter Than You', 'Rapture - World Conquest', and
       'WWE Supercard'
     * Simogo Wrapping Up 'The Sailor's Dream', Offer Vague New Teaser
       that Won't Spoil Any Surprises
     * Square Enix and DeNA's 'Final Fantasy Record Keeper' Available in
       the Japanese App Store
     * 'Rapture - World Conquest' Review - Take over the World in Five
       Minutes

AppShopper

     * Apple Announces iPhone 6 Models and NFC-Based Electronic Payment
       System
     * Apple Watch Revealed with Early 2015 Release Timeframe and $349
       Price Tag
     * Apple to Release iOS 8 on September 17
     * Apple to Live Stream September 9 iPhone Announcement Event
     * Apple Announces iOS 8 and Mac OS X 'Yosemite'
     * Fantastical 2 for iPad Now Available

   Copyright © 2000- MacRumors.com, LLC.
   Privacy / DMCA contact / Affiliate and FTC Disclosure
   Mobile Version | Fixed | Fluid | Fluid HD

   Quantcast
