     * Insider Shop
     * Insight Community
     * Step2
     * Search Techdirt_ Search

   Techdirt Techdirt
     * Sign In
     * Register
     * Preferences

     * Techdirt
     * Wireless News
     * Innovation
     * Case Studies
     * Startups
     * Net Neutrality

     * Main
     * Submit a Story
     * rss RSS

   Patent Troll That Accused FindTheBest Of 'Hate... >>
   << Europeans Club Google Over The Head At A Rate...
     tdicon
   Verizon Begs To Be Classified Under Title II... >>
   << If Comcast CEO Brian Roberts Really Believes...
    |

   Broadband

   by Mike Masnick

   Mon, Jun 2nd 2014 7:29am
   In last night's John Oliver show (technically "Last Week Tonight"), his
   "top story" was all about net neutrality. This is both surprising
   (because the issue has received little mainstream...

   Filed Under:
   broadband, cable companies, fast lanes, john oliver, lobbying, net
   neutrality, open internet, politics

   Companies:
   at&t, comcast, time warner cable, verizon

   Permalink.

John Oliver: Stop Calling It Net Neutrality; It's 'Preventing Cable Company
F**kery'

from the a-bit-more-on-target dept

   In last night's John Oliver show (technically "Last Week Tonight"), his
   "top story" was all about net neutrality. This is both surprising
   (because the issue has received little mainstream attention) and
   awesome, because it needs much more mainstream attention.

                 IFRAME: //www.youtube.com/embed/fpbOEoRrHyU

   Not surprisingly, it's both insightful and hilariously funny. He mocks
   how the FCC has made the issue sound incredibly boring. He mocks telco
   industry lawyers claiming it's "not about fast lanes and slow lanes"
   but "fast lanes and hyperspeed lines." Oliver summarized that quote
   simply as "bullshit." He shows this graphic of Netflix's speed on
   Comcast before and after it agreed to pay up, and directly compares it
   to a mafia shakedown. He highlights how the broadband companies (though
   he unfortunately lumps telco companies in as "cable companies") have
   basically bought off Washington DC, amusingly comparing an FCC run by a
   former lobbyist regulating the cable industry to an Australian couple
   hiring a dingo to babysit.
   And, finally, he has an amusing call to action for "internet
   commenters" who he suggests have been training their whole lives for
   this moment, when the FCC has asked people for comments on its
   proposal. It's just too bad he pointed them directly at the confusing
   FCC.gov site, rather than the EFF's much better interface at
   DearFCC.org.
   Either way, it's great to see Oliver take on this issue in an amusing
   way -- and hopefully it will spur more people to speak up on the issue.
   37 Comments | Leave a Comment
   If you liked this post, you may also be interested in...
     * Apparently The Reason Comcast Has Crappy Customer Service Is
       Because It Was Lacking A 'Customer Experience' VP
     * VoIP Pioneer Worried About Net Neutrality Reclassification -- But
       Without It, Broadband Providers Could Kill VoIP Startups
     * Web Inventor Tim Berners-Lee Gets To The Core Of Net Neutrality
       Debate: You Need An Open Internet To Have A Free Market
     * Healthcare.gov Is A Security Disaster... And Those Working On It
       Knew It, And Tried To Stop Independent Security Review To Hide It
     * The Court's Own Words: Life Without Title II Has Online
       Discrimination, Paid Prioritization, Exclusive Deals, And Maybe
       Blocking

Reader Comments (rss)

   (Flattened / Threaded)
    1.
       icon
       Zakida Paul (profile), Jun 2nd, 2014 @ 7:45am

Cable company fuckery
       I like that, is it copyrighted?
       I may use it

       [ reply to this | link to this | view in thread ]
    2.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:08am

Best Part of My Day Just Happened
       Thank You, that was the best internet video I have ever seen and
       put a huge smile on my face.

       [ reply to this | link to this | view in thread ]
    3.
       icon
       Namel3ss (profile), Jun 2nd, 2014 @ 8:08am
       That was at least 5 different flavors of awesome with awesomesauce
       on top!

       [ reply to this | link to this | view in thread ]
    4.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:09am

Looks like they may be getting swamped. This is the link now.
       Hibernate operation: Cannot open connection; uncategorized
       SQLException for SQL [???]; SQL state [null]; error code [0];
       weblogic.common.resourcepool.ResourceLimitException: No resources
       currently available in pool ecfs to allocate to applications,
       please increase the size of the pool and retry..; nested exception
       is weblogic.jdbc.extensions.PoolLimitSQLException:
       weblogic.common.resourcepool.ResourceLimitException: No resources
       currently available in pool ecfs to allocate to applications,
       please increase the size of the pool and retry

       [ reply to this | link to this | view in thread ]
    5.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:11am
       since when has a former employee of any industry become the head of
       an industry/company and NOT leaned heavily in the favorable
       direction of his former employees? apart from showing exactly what
       was wanted by the industries concerned, and those wants coming to
       fruition, it shows as well exactly who is pulling Obama's chains,
       and why Wheeler got the job!! with the number of mails, complaints,
       suggestions and fears of what was going to happen if he went the
       way he wanted, Wheeler then ignored everything and everyone,
       preferring to still go down the road he had every intention of
       traveling all along! looking at things from the other side, which
       seems to have died a death since it happened, is the ruling that
       came down to remove net neutrality in the first place. it certainly
       makes me extremely suspicious that this whole debacle was an
       elaborate set up from the beginning!!

       [ reply to this | link to this | view in thread ]
    6.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:19am

Conflict of Interest
       Is obviously a term that Obama has no problem with. And not just to
       throw him under the bus, but the same problem exists for the rest
       of the government.
       It's be long past time to end the revolving door between the lobby
       and government regulators.

       [ reply to this | link to this | view in thread ]
    7.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:21am

Re: Looks like they may be getting swamped. This is the link now.
       Yea, already over 45k in comments... definitely being overloaded!

       [ reply to this | link to this | view in thread ]
    8.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:26am
       #preventingcablecompanyfuckery?
       Wish he would've chosen something shorter for the age of Twitter.

       [ reply to this | link to this | view in thread ]
    9.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:30am

Re:
       #RICO

       [ reply to this | link to this | view in thread ]
   10.
       identicon
       David, Jun 2nd, 2014 @ 8:31am

Cannot open connection
       Conveniently, the FCC site is lovely down. No can comment, Tarzan.
       It's not like the FCC is going to pay attention anyway. There's a
       history of this sort of thing. It's Thank You For Your Comments
       (those of you who got through), now we'll get on with what we were
       planning to do all along.
       Maybe there's some hope. Maybe if there's enough flood, they can't
       ignore it. But they don't have an incentive to increase the
       capacity of their system. They know this direction doesn't serve
       the customers, the people, the startups, etc. Exactly the point.

       [ reply to this | link to this | view in thread ]
   11.
       icon
       GMacGuffin (profile), Jun 2nd, 2014 @ 8:38am

Cox Cable Apparently Clueless
       /* begin bitching
       */
       I was surprised last week to get an email from my broadband
       provider Cox telling me that for an extra $5/month I can get even
       faster broadband! Yay.
       I'm already paying an extra $10/month for "Premium" access but I
       checked it out anyway. The new offer is really about $10-12 more
       per month (liars), and offers download speeds of 'up to' 50Mbps (I
       had routers in 1999 that could handle more than that).
       I was too put out to determine whether they are slowing down my
       Premium speeds, or just offering a third tier of even higher
       not-very-fast speeds for a higher, misrepresented sum.
       Other broadband options available?: None to speak of.
       In light of current issues - tackiness threshhold has been
       surpassed.
       /* end bitch
       */

       [ reply to this | link to this | view in thread ]
   12.
       icon
       Lowestofthekeys (profile), Jun 2nd, 2014 @ 8:42am

Re: Cable company fuckery
       It sounds like a pretty bitchin' band name.

       [ reply to this | link to this | view in thread ]
   13.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 8:49am

Re: Looks like they may be getting swamped. This is the link now.
       Don't worry, they'll get it fixed about an hour before the 120 day
       comment period is over.

       [ reply to this | link to this | view in thread ]
   14.
       icon
       Zakida Paul (profile), Jun 2nd, 2014 @ 9:23am

Re: Re: Cable company fuckery
       I can imagine them playing hardcore punk rock

       [ reply to this | link to this | view in thread ]
   15.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 9:39am
       Is there a way we could make every member of the House and Senate
       watch that video? (Tho to do so one would likely need to go a bit
       "Clockwork Orange" on them... Yet the results might be worthwhile.)

       [ reply to this | link to this | view in thread ]
   16.
       identicon
       Asok, Jun 2nd, 2014 @ 10:41am
       The call to use fcc.gov/comments is worse than useless. It makes
       people think they are doing something useful. But the FCC can Tom
       Wheeler can just easily ignore them.
       Use the old fashioned telephone. Talk to the FCC. Tie up their
       phone lines. Much more useful than making comments on their
       website.
       Use the script here:
       http://www.reddit.com/r/sysadmin/comments/25pltx/online_petition_to
       _remove_tom_wheeler_as_chairman/c hjimuq

       [ reply to this | link to this | view in thread ]
   17.
       icon
       Josh in CharlotteNC (profile), Jun 2nd, 2014 @ 10:54am

Re: Looks like they may be getting swamped. This is the link now.
       Stating the obvious: the government body charged with overseeing
       the Internet can't manage to keep their servers up reliably when
       asking for comments over the Internet.

       [ reply to this | link to this | view in thread ]
   18.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 11:21am
       Fucking Brilliant!

       [ reply to this | link to this | view in thread ]
   19.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 11:29am

Re: Re: Looks like they may be getting swamped. This is the link now.
       I'd say that was very much on purpose. A design feature, not a
       failure.
       During the hot topic time, all those people don't get heard. As
       soon as the heat of passion dies down and the lines go back to
       normal, they can surface and report far, far, fewer people had an
       issue with this change the FCC wants. See?? No problem at all.
       And here is the government office in charge of broadcast, public
       utilities, and communications, unable to serve the needs of it's
       own customers. How friggin' convenient.

       [ reply to this | link to this | view in thread ]
   20.
       identicon
       Herp Derpington, Jun 2nd, 2014 @ 12:05pm

Re: Cannot open connection

     Conveniently, the FCC site is lovely down. No can comment, Tarzan.
       Sounds like the FCC should have paid up for the hyperspeed lane.

       [ reply to this | link to this | view in thread ]
   21.
       icon
       Mike Masnick (profile), Jun 2nd, 2014 @ 12:25pm

Re:
       The call to use fcc.gov/comments is worse than useless. It makes
       people think they are doing something useful. But the FCC can Tom
       Wheeler can just easily ignore them.
       I disagree. The comment period matters *tremendously*. There's a
       political game being played here. There is a very decent chance
       that Wheeler is actually interested in reclassification, but knows
       it's politically untenable. If the FCC is *ABSOLUTELY FLOODED* with
       pro-reclassification comments, he can turn around and make the
       political argument that the public absolutely wants it.
       i.e., the comment period is an opportunity to give him political
       cover to make the politically untenable... tenable.

       [ reply to this | link to this | view in thread ]
   22.
       identicon
       Anonymous Coward, Jun 2nd, 2014 @ 12:47pm

Re: Re:
       I agree. It's like SOPA. All the politicians took all the lobbying
       money and thought everything was just going to sail right through
       like business as usual, until the public showed up and told them to
       hold the phone. Then they couldn't drop support for it fast enough.
       Same thing. Lot's of commentary, loud and often, can make a
       difference.

       [ reply to this | link to this | view in thread ]
   23.
       icon
       John Fenderson (profile), Jun 2nd, 2014 @ 3:33pm

Re: Re:
       You hit the nail on the head. One of the really huge secrets in
       Washington is that they are absolutely terrified of the power of
       public opinion.

       [ reply to this | link to this | view in thread ]
   24.
       identicon
       Anonymous, Jun 2nd, 2014 @ 3:50pm

Re: Re:
       #RICO
       You're liable to reach that little brat from "Hannah Montana".

       [ reply to this | link to this | view in thread ]
   25.
       identicon
       Anonymous, Jun 2nd, 2014 @ 3:54pm

Re: Re: Re:
       Oh, you mean like the public opinion against Obamacare, NSA spying,
       the IRS, and the Middle East wars? It must really be a secret,
       since they hide their fear so well.

       [ reply to this | link to this | view in thread ]
   26.
       icon
       Spaceman Spiff (profile), Jun 2nd, 2014 @ 4:06pm

Re: brill!
       You beat me to it! Couldn't agree more! :-)

       [ reply to this | link to this | view in thread ]
   27.
       icon
       Lars (profile), Jun 2nd, 2014 @ 5:29pm

Re: Re: Re: Re:
       Except the public hasn't shown up in significant numbers to
       actually combat those issues.

       [ reply to this | link to this | view in thread ]
   28.
       icon
       R.H. (profile), Jun 2nd, 2014 @ 7:54pm

Re: Conflict of Interest
       The problem there is called 'regulatory capture'. The majority of
       the people interested and qualified for the regulatory jobs are
       people who either worked in the industry before or people who the
       industry would, even without the government job on their resum, be
       interested in hiring. After an agency has existed for a few years,
       many of its members will be former members of the regulated
       industry.
       It's a problem but, unless the government tries to prohibit
       individuals from taking certain jobs after their government service
       is complete (which would be of questionable legality), I don't know
       how to fix the issue.

       [ reply to this | link to this | view in thread ]
   29.
       icon
       JohnG (profile), Jun 3rd, 2014 @ 5:02am

Re: Re:
       but classifying broadband to a public utility won't fix the
       underlying issue - regional monopolies which largely prevent
       competition.
       If Comcast had a serious competitor or two in areas you'd see that
       if they started shaking down Netflix or throttling them, their
       competitor could use such actions in their own marketing to steal
       customers. There you go - problem solved without additional
       government

       [ reply to this | link to this | view in thread ]
   30.
       identicon
       Anonymous Coward, Jun 3rd, 2014 @ 6:15am

Re: Re: Looks like they may be getting swamped. This is the link now.
       Yup: fixed an hour before the 120 day comment period is over,
       followed by "it looks like no one cares, so let's vote now."

       [ reply to this | link to this | view in thread ]
   31.
       identicon
       Anonymous Coward, Jun 3rd, 2014 @ 6:17am

Re: Re:
       RICO Suave?

       [ reply to this | link to this | view in thread ]
   32.
       icon
       John Fenderson (profile), Jun 3rd, 2014 @ 8:39am

Re: Re: Re: Re:
       What Lars said. There is no substantial backlash against any of
       those things. There was substantial backlash against the war, but
       it was counterbalanced by the unprecedented propaganda campaign
       that fired up the extreme, violent nationalists in the US. Even
       there, though, you can see their fear by looking at the amount of
       time, effort, and lying that went into countering the opinion.

       [ reply to this | link to this | view in thread ]
   33.
       identicon
       Anonymous, Jun 3rd, 2014 @ 3:12pm

Re: Re: Re:
       Yep, that would be him MWAH-HA-HA-HA-HA!

       [ reply to this | link to this | view in thread ]
   34.
       icon
       skeptacular (profile), Jun 3rd, 2014 @ 4:47pm

Fuckery
       Hello, I am a professional fucker. With merely some earthy
       malfeasance and a fucker's wheel, I create fakery with my own two
       hands. Useful around the house, yet praised as fine art too,
       fuckery is really coming into its own in the 21st Century, and I'm
       here to teach you how you can make fine fuckery too. For pleasure,
       commerce, or to make your own statement, learn fuckery and you can
       call yourself a fucker too!

       [ reply to this | link to this | view in thread ]
   35.
       identicon
       Ingrid Phillips, Jun 3rd, 2014 @ 7:56pm

Re: Solution to Internet's High Cost
       Hi ~ I was looking for a tweet from a tech person who put a name
       (can't find it) to using ? (something) instead of paying high
       prices for cable. Don't want to go to DSL & haven't had luck
       w/DirectTV. Remember those horrible days of dialup. I have a VOIP
       w/ooma (not premium) so don't pay for any long distance calling.
       Thanks for your insights,
       ingy59

       [ reply to this | link to this | view in thread ]
   36.
       identicon
       Jerry Hall, Jun 7th, 2014 @ 4:18am

Net Neutrality FCC comment section broken/down/Useless?
       Um, why is each link on the FCC page broken - when one is trying to
       comment on the Net Neutrality measure?
       Well, that's if you got past not including the www will take you to
       a broken link as well (i.e. fcc.gov/comments doesn't work).
       Try these links:
       http://apps.fcc.gov/ecfs/upload/begin?procName=14-28&filedFrom=X
       http://www.fcc.gov/comment s
       http://fjallfoss.fcc.gov/ecfs/
       http://apps.fcc.gov/ecfs/comment_search/execute?proceeding=14-28
       Stran ge?

       [ reply to this | link to this | view in thread ]
   37.
       icon
       Sheogorath (profile), Jun 7th, 2014 @ 9:54pm

Re: Cable company fuckery
       Too short to be copyrighted, so get in there before someone thinks
       to trademark it.

       [ reply to this | link to this | view in thread ]

Add Your Comment

   Have a Techdirt Account? Sign in now. Want one? Register here
   Name    __________________________________________________
   Email   __________________________________________________ [ ] Get
           Techdirt’s Daily Email
   URL     __________________________________________________
   Subject __________________________________________________
   Comment
           this is for spambots, do not use this_______________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________

           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
   Options [ ] Save me a cookie
           Submit Preview
     * Note: A CRLF will be replaced by a break tag (<br>), all other
       allowable HTML will remain intact
     * Allowed HTML Tags: <b> <i> <a> <em> <br> <strong> <blockquote> <hr>
       <tt>

   Close
   Have a Techdirt Account? Sign in now. Want one? Register here
   Name    __________________________________________________
   Email   __________________________________________________ [ ] Get
           Techdirt’s Daily Email
   URL     __________________________________________________
   Subject __________________________________________________
   Comment
           this is for spambots, do not use this_______________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________

           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
   Options [ ] Save me a cookie
           Submit Preview
     * Note: A CRLF will be replaced by a break tag (<br>), all other
       allowable HTML will remain intact
     * Allowed HTML Tags: <b> <i> <a> <em> <br> <strong> <blockquote> <hr>
       <tt>

   Patent Troll That Accused FindTheBest Of 'Hate... >>
   << Europeans Club Google Over The Head At A Rate...
     tdicon
   Verizon Begs To Be Classified Under Title II... >>
   << If Comcast CEO Brian Roberts Really Believes...
    |
   Follow Techdirt

Techdirt's Daily Email Newsletter

   Enter Your Email Address_ Subscribe
   Advertisement
   Essential Reading

Hot Topics

     * 5.4 Another Story Of A 'Fake' Brilliant Inventor? Is 'Scorpion
       Walter O'Brien' A Real Computer Security Genius?
     * 5.3 FBI Director Angry At Homebuilders For Putting Up Walls That
       Hide Any Crimes Therein
     * 5.1 Funniest/Most Insightful Comments Of The Week At Techdirt
     __________________________________________________________________

New To Techdirt?

   Explore some core concepts:
     * Perhaps It's Not The Entertainment Industry's Business Model That's
       Outdated
     * Saying You Can't Compete With Free Is Saying You Can't Compete
       Period
     * The Future Of Music Business Models (And Those Who Are Already
       There)

   read all »
   Techdirt Reading List
   Amazon.com Widgets
   Techdirt Insider Chat

   Get the Insider Chat!
   Advertisement
   Recent Stories

   Sunday

   12:00 Funniest/Most Insightful Comments Of The Week At Techdirt (3)

   Saturday

   12:00 This Week In Techdirt History: September 20th - 27th (5)
   09:00 Awesome Stuff: Simple And Small Stuff (8)

   Friday

   19:39 Nine Epic Failures Of Regulating Cryptography (41)
   18:11 Apparently The Reason Comcast Has Crappy Customer Service Is
         Because It Was Lacking A 'Customer Experience' VP (25)
   17:00 DailyDirt: That's A Spicy Meatball, But It's Not Italian...? (5)
   15:48 Health Experts Issue Call To Prevent ICANN's Commercialization Of
         New .health Domain Leading To Exclusive Control Of Online Health
         Information (11)
   14:40 Eric Holder Was The Worst Attorney General For The Press In A
         Generation: We Deserve Better (28)
   13:39 Jimi Hendrix Biopic Opens Today... Without Any Jimi Hendrix
         Music, Thanks To Copyright (74)
   12:29 Cameras Watching Cops: Still A Good Idea (25)

More  arrow

   Advertisement

   [td_logov140.png]

Company

   About Us
   Advertising Policies
   Privacy

Contact

   Help & Feedback
   Media Kit
   Sponsor/Advertise
   Submit a Story

Tools & Services

   Twitter
   Facebook
   RSS
   Techdirt for Mobile
   Research & Reports

More

   Insight Community
   Step2
   Insider Shop
   Brought to you by Floor64

   Close

   Email This
     * To Address this is for spambots ____________________
     * Your Name this is for spambots ____________________
     * Your Address this is for spambots ____________________
     * Send It

   [p?c1=2&c2=6036036&cv=2.0&cj=1] Quantcast
