    #VentureBeat Feed Amazon restores preorders for Warner Bros. movies
   Expanding nurturing beyond email alternate alternate VentureBeat
   WordPress.com publisher

   VentureBeat

   News

     * News
     * Events
     * Insight
     * Notifcations
     * [arrow_medgrey.png]

   ____________________ (BUTTON)

Events

Insight

Webinars

   VentureBeat

   (BUTTON) Navigate
     * Channels
          + GAMESBEAT
          + Health
          + Big Data
          + Lifestyle
          + Business
          + Marketing
          + Cloud
          + Media
          + Deals
          + Mobile
          + Dev
          + New York
          + Education
          + Reviews
          + Enterprise
          + Science
          + Entrepreneur
          + Security
          + Gadgets
          + Small Biz
          + Green
          + Social
     * Events
     * Insight
     * Videos
     * Newsletters
     * Jobs
     * Got news? Tell us!

   Education

Tim O’Reilly wants tech heroes to change government (interview)

   Tim O’Reilly wants tech heroes to change government (interview)
   Tim O’Reilly wants tech heroes to change government (interview)

   Above: Tim O'Reilly, CEO of O'Reilly Media
   Image Credit: Dean Takahashi
   June 24, 2014 8:00 AM
   Dean Takahashi
   3

   Tim O’Reilly created a tech media empire at O’Reilly Media while
   advocating free software and open source. His life’s work earned him a
   Visionary Award from Silicon Valley tech association SVForum.

   In his acceptance speech, O’Reilly said he spent the past year in
   Washington, D.C., with his fiancé Jennifer Pahlka, helping with Code
   for America, a nonprofit that wants to modernize government with
   the help of tech-savvy professionals. He said he is passionate about
   people who are trying to change the world.

   “The thing we should all be looking for are people who want to make a
   difference,” he said. “I’m a big believer in the Silicon Valley
   religion of the power of markets. But I also believe in our obligation
   to give back, and to give back in the way we do business, to create
   more value than we capture for ourselves.”

   Right now, he is trying to change government, which he notes is a third
   of our economy. He said the failure of Healthcare.gov at the outset led
   to a great turnaround as tech-savvy experts came in to fix it.

   “That is not something we should allow to fail,” he said. “That is
   something we must stand up for and make work. We want to show how
   technology can be applied to fix our problems. We need to celebrate not
   just success but to celebrate people who make a difference. It starts
   with people who do things for love, with no expectation of return. Some
   of that turns into enormous financial success, and then some of it goes
   back into doing it for love. Those people who worked tirelessly on
   Healthcare.gov are heroes.”

   We caught up with O’Reilly for a one-on-one interview at the awards
   event. Here’s an edited transcript of our conversation.
   Jen Pahlka of Code for America and Tim O'Reilly

   Above: Jen Pahlka of Code for America and Tim O’Reilly
   Image Credit: Dean Takahashi

   VentureBeat: What are you up to lately?

   Tim O’Reilly: A lot of my energy is going to Code for America, Jen
   Pahlka’s non-profit startup. We’re doing a lot of great work teaching
   government how to apply technology and changing the culture of
   government. Jen just had a year in Washington as deputy CTO. I went
   along for the ride and was helpful where I could be.

   I’m also spending a lot of time focusing on two big areas at O’Reilly
   Media. One is the transformation of our events business. It’s a much
   bigger part of our business today.

   VB: I missed the Web 2.0 event. I always used to go every year.

   O’Reilly: Yeah, the Web 2.0 events were terrific. There’s this great
   line that I once heard from Joni Mitchell. She talked about why she
   preferred to be a painter than a singer-songwriter. She said, “Nobody
   ever said to Van Gogh, ‘paint A Starry Night again!’” I have to say, I
   got so tired of talking about the same stuff. You have to move on. With
   most of my events, I’ve been successful at not being necessary to it.
   We’re still doing our open source convention after 17 years, but I’m
   not the main man there. Web 2.0, John and I were so much the frontmen
   for it. It was just time to move on.

   I’m super excited about our new Solid event that we just had a couple
   of weeks ago. There’s this new wave intersecting hardware and software.
   Thinking about that and getting people to think about it in the right
   way is super important.

   The other thing I’m spending a bunch of time on at O’Reilly is the
   transition of publishing from print to ebooks. We’ve done a lot of
   interesting things there. Safari Books Online, our joint venture with
   Pearson, is growing apace. That’s the online library of computer and
   business books we launched in 2000. It’s become a very powerful
   business. Also we’re doing really well with downloadable ebooks, where
   we’ve taken a strong position on DRM-free downloads. It’s been driven
   by the recognition that Amazon has an implicit lock-in with the Kindle.
   If publishers don’t step up to create open formats, then we’re hosed.
   We give people the choice. When you buy an ebook from O’Reilly, you get
   an ebook bundle, your choice of any or all formats – PDF, .mobi, .epub,
   or even Daisy files if you’re visually impaired. We’ve built the
   infrastructure to be able to generate those, and we do it all DRM-free,
   because we think that if you don’t trust your customers, why should
   they trust you?

   In general, we’re thinking about new business models for ebooks. We’re
   also working on a new platform called Atlas, which is our own internal
   publishing platform. We’re now turning it into a B2B service for other
   publishers.

   Finally, I’m putting a lot of my time into O’Reilly AlphaTech Ventures,
   our venture firm. You may have seen one of our portfolio companies,
   Cover, come to San Francisco. They’re an Uber-like experience for
   paying your restaurant check. We have a lot of stuff in the news about
   micro satellites. We’re an investor in Planet Labs. 3D Robotics, with
   drones. Another company, Sight Machines, is doing industrial machine
   vision. A lot of data companies. There are a lot of different areas
   that are very much aligned with the things I talked about.

   I mentioned Code for America. There’s a whole startup ecosystem we’re
   trying to build around government.
   Tim O'Reilly

   Above: Tim O’Reilly
   Image Credit: Dean Takahashi

   VB: That seems like the hardest of all the things you’re doing.

   O’Reilly: In some ways it is, but it’s among the most important.
   Government is a third of our economy. Jen gave a talk last night that I
   thought was great. She said, “We have these hard problems. We set aside
   enormous resources to tackle them. But then we spend it so badly.” You
   look at healthcare.gov. It’s a noble goal, totally bungled. And yet
   when they brought in a bunch of people with the right skills to fix it,
   with that leadership, the same contractors who bungled it were able to
   turn it around. They met their original goals. It’s one of the most
   important tech turnarounds in history, led by a bunch of people from
   the private sector who said, “I gotta go help.”

   That’s a lot of what Code for America is about. We work at the local
   level, but the White House has copied a lot of its programs through the
   Presidential Innovation Fellows and things like the healthcare.gov
   rescue. How do we get this talent that understands from the consumer
   side – how to build services that actually work for people? What are
   the processes by which you build that software? You get those people
   into government. That’s a lot of what Jen was working on over the last
   year in Washington. She’s back at Code for America.

   It’s hard to underestimate how big the challenge is, because of
   business processes, because of the way that people in government feel
   constrained by regulations. There’s nobody who can just decide. Steve
   Jobs came back to Apple and said, “We’re going from 300 products to
   seven.” You don’t have anybody, even the president, with the authority
   to do that. It’s this enormous thicket of regulations about hiring,
   about procurement. These are laws. Congress has to write a new law to
   throw this stuff out.

   That’s one reason why we decided to work at the city level. You can
   show what’s possible. You can start to get that change happening. A
   huge part of it is a culture of putting the citizen first. We did an
   application last year in San Francisco for the folks who run food
   stamps. It turned out there was this huge churn in the system. People
   would get these notices from the government saying they’d missed some
   requirement and they’re about to be dropped from the program. They
   either wouldn’t get the letter because it’s sent to the wrong place, or
   they would read these letters that are truly mind-numbing in their
   language. It’s completely unclear what you’re supposed to do, so people
   would do nothing and suddenly one day their CalFresh card doesn’t work.

   The Code for America fellows went in and signed up for the program.
   They debugged the process. They came up with a new process where now
   you get a text message that says, “There’s a problem with your
   benefits. Call the office.” That’s it. It’s made a huge difference. But
   they had to get permission. It’s not a hard technical problem, but
   nobody was actually trying the service. They weren’t going through the
   process of signing up and realizing, “This is crazy! There are 50
   screens in the signup process!” No consumer internet service could
   survive if it made you do that.

   We’re trying to think about this whole idea of simplification, culture
   change, and how you do that by showing government what’s possible. But
   then a lot of the small startup teams get the government bug. A number
   of startups here come out of the space. Some of them are going to be
   very successful.

   VB: The words I remember a lot from the Web 2.0 events were
   “disruption” and “platform struggle.” Some of those are still with us.
   Disruption of media and publishing seems to be happening.

   O’Reilly: We’re doing quite well, I think. While there’s a lot of
   disruption in the market, ebooks on the whole have been good for
   publishing. People who fought it have gotten on board now. But I don’t
   think disruption has ever been one of my themes. It’s something that
   people talk a lot about in Silicon Valley. What I care about,
   ultimately, is making the world a better place. That’s why I’m
   attracted to government work. It’s about saying, “How do we put these
   talents we have to work making the world a better place?”

   I’ve been focused, from a technology point of view, on the potential of
   the internet to harness collective intelligence and solve hard
   problems. It seems to me that there are very hard problems ahead of us.
   When you look at demographics and aging populations and the need for
   health care, there’s a pretty clear case that in some countries that’s
   going to require a complete re-ordering of our society. You look at
   income inequality and the possible disruption that comes from there.
   You look at climate change and all the issues there. You look at robots
   taking people’s jobs. I’ve been involved in a task force thinking about
   the future of the American economy. One of the things I’m thinking a
   lot about is, never mind where we’re going to get the jobs. Let’s think
   about what needs doing. There are lots of challenges ahead of us.

   I feel like a lot of the focus in Silicon Valley is on trivia. I’m
   heartened that an increasing number of companies are working on what I
   call “stuff that matters.” That’s what makes great companies. They try
   to think about stuff that matters.
   Tim O'Reilly of O'Reilly Media at Visionary Awards

   Above: Tim O’Reilly of O’Reilly Media at Visionary Awards
   Image Credit: Dean Takahashi

   VB: Maker has become a very interesting movement. I wonder if you feel
   like it’s hitting a stride as far as going mainstream, or whether it’s
   a hobby still.

   O’Reilly: If you look at every technology movement, it begins with DIY.
   The people who started the personal computer revolution were DIY. I
   used to show, in my talks, a slide of Steve Wozniak’s original Apple I,
   made in a wood shop. It was a maker project, effectively. You look at
   what happened, the arc of the computer industry, those things became
   consumer goods.

   If you look at the early web, it was all maker, people doing cool
   stuff. But you also look at things like multitouch. It came into the
   popular conception with the iPhone, but the year before, there was Jeff
   Han at our emerging technologies conference with this big DIY rig he
   hooked up as a professor at NYU, doing this amazing stuff on stage. He
   started this company that he sold to CNN for these big tactile
   displays. Danny Hillis was doing different kinds of technology,
   multitouch map tables. It was maker stuff before it was consumer.

   A lot of what’s happened in the maker movement in the last few years is
   going to turn into consumer. Then the makers will move on. It’ll be DIY
   bio. You may notice that O’Reilly started publishing a DIY bio journal,
   because think that’s one of those areas where hands-on DIY goes. But I
   also think that, as the rest of this stuff becomes more
   mainstream—First of all, there’s great investment opportunities. I met
   this morning with a guy who has a startup that’s tracking stress. He’s
   applying this for veterans, for example, with PTSD, to be able to help
   them track and manage their stress. This was originally a maker
   project. Now it looks like a consumer smart watch kind of thing. But
   the impulse of, “Hey, there’s this new technology that can solve a
   problem,” that’s terrific.

   VB: So you think maker can be steered into making the world a better
   place.

   O’Reilly: That’s right. Dale Dougherty, who runs Maker Media, is really
   interested in the potential for education. That’s another aspect of
   this, getting kids hands-on with technology. The maker movement is a
   fantastic way to do that.

   VB: Technology in general, do you still love it? Do you get bored with
   it? Do you stay fascinated?

   O’Reilly: I guess I would just say that in general, one of my
   weaknesses is that I love everything. There’s too much of everything to
   keep up with it all. I get bored with Silicon Valley technology a lot.
   I’ve always had much more of a draw to the people who are doing things
   for love than the people who are doing things for money. I say that
   despite being a venture capitalist and somebody who’s built a
   successful business.

   VB: Beyond Silicon Valley, what about Microsoft, Apple, Sony, the
   competition that’s taking place among those guys?

   O’Reilly: I generally find people who have a mission to be the most
   interesting. I don’t know what Apple’s mission is anymore. I think
   Google still has a mission. Amazon still has a mission. It’s not really
   that there’s an opposition between money and what excites me. The early
   Microsoft had a mission, a computer on every desktop. That was a pretty
   amazing vision. We all built on it. I tend to find that you find that
   mission more purely, though, in these new emergent movements – like the
   maker movement, like open source software, like the web before it was
   commercial – which is why I’m always drawn to those.

More information:

     * OReilly Media

   “This company was created to provide interesting work for interesting
   people. We follow our dreams, our curiosity, and our sense of what’s
   important.” –Tim O’Reilly, Founder and CEO O’Reilly Media, Inc. spreads
   the kn... read more »

   Powered by VBProfiles

Topics >

   3D Robotics Amazon Apple code for america cover Dale Dougherty Danny
   Hillis Google Jeff Han Jennifer Pahlka Maker Media Microsoft O’Reilly
   AlphaTech Ventures OReilly Media Pearson Planet Labs Sight Machine Tim
   O'Reilly top-stories web 2.0
   3 comments
     Livefyre
     * Get Livefyre
     * FAQ

   Sign in
   + Follow
   Post comment

   Link
   Newest | Oldest
   Nitin Bansal
   Nitin Bansal 5pts

   That's the way to go ahead with...
   Steven Heizmann
   Steven Heizmann 5pts

   1776 DC start-up incubator works on projects like this. I have 2 on
   this topic alone.
   Michael Koloberdin
   Michael Koloberdin 5pts

   Technofascism FTW! :)

Latest News

     * How best-of-breed apps can topple the enterprise monopoly
       How best-of-breed apps can topple the enterprise monopoly
       How best-of-breed apps can topple the enterprise monopoly
     * Why it’s critical to find early customers outside of Silicon Valley
       Why it’s critical to find early customers outside of Silicon Valley
       Why it’s critical to find early customers outside of Silicon Valley

Research You'll Like

Press Releases

     * Corporate Venture & Innovation Initiative (CVI²), J. Thelander
       Consulting Release Most Comprehensive Corporate Venture Capital
       (CVC) Compensation Report
       Corporate Venture & Innovation Initiative (CVI²), J. Thelander
       Consulting Release Most Comprehensive Corporate Venture Capital
       (CVC) Compensation Report
       Corporate Venture & Innovation Initiative (CVI²), J. Thelander
       Consulting Release Most Comprehensive Corporate Venture Capital
       (CVC) Compensation Report
     * Unitas Global Honored with 2014 Cloudys Award
       Unitas Global Honored with 2014 Cloudys Award
       Unitas Global Honored with 2014 Cloudys Award
     * Nimble Launches Android Smart Contacts App to Intelligently Build
       and Nurture Social Selling Relationships
       Nimble Launches Android Smart Contacts App to Intelligently Build
       and Nurture Social Selling Relationships
       Nimble Launches Android Smart Contacts App to Intelligently Build
       and Nurture Social Selling Relationships

   View more [business-wire-widget.png?m=1391186376g]

     * Home
     * About
     * Contact
     * Careers
     * Advertise
     * Events
     * Privacy Policy
     * Terms of Service

   © Copyright 2014 VentureBeat. All rights reserved. Powered by
   WordPress.com VIP
