    ____________________

   Search Images Maps Play YouTube News Gmail Drive More »
   Send Feedback | Web History | Help | Sign in
   Home
   Home
   Profile
   People
   Photos
   Communities
   Events
   Hangouts
   Pages
   Local
   Settings
   Feedback
   Help  ·  Region
   Privacy & Terms  ·  Maps Terms
   [photo.jpg]
   Google Glass

Google Glass

   Shared publicly  -  2014-03-20

   The Top 10 Google Glass Myths
   Mr. Rogers was a Navy SEAL. A tooth placed in soda will dissolve in 24
   hours. Gators roam the sewers of big cities and Walt Disney is
   cryogenically frozen. These are just some of the most common and --
   let’s admit it -- awesome urban myths out there.
   Myths can be fun, but they can also be confusing or unsettling. And if
   spoken enough, they can morph into something that resembles fact. (Side
   note: did you know that people used to think that traveling too quickly
   on a train would damage the human body?)
   In its relatively short existence, Glass has seen some myths develop
   around it. While we’re flattered by the attention, we thought it might
   make sense to tackle them, just to clear the air. And besides, everyone
   loves a good list:
   Myth 1 - Glass is the ultimate distraction from the real world
   Instead of looking down at your computer, phone or tablet while life
   happens around you, Glass allows you to look up and engage with the
   world. Big moments in life -- concerts, your kid’s performances, an
   amazing view -- shouldn’t be experienced through the screen you’re
   trying to capture them on. That’s why Glass is off by default and only
   on when you want it to be. It’s designed to get you a bit of what you
   need just when you need it and then get you back to the people and
   things in life you care about.
   Myth 2:  Glass is always on and recording everything
   Just like your cell phone, the Glass screen is off by default. Video
   recording on Glass is set to last 10 seconds. People can record for
   longer, but Glass isn't designed for or even capable of always-on
   recording (the battery won’t last longer than 45 minutes before it
   needs to be charged). So next time you’re tempted to ask an Explorer if
   he’s recording you, ask yourself if you’d be doing the same with your
   phone. Chances are your answers will be the same.
   Myth 3 - Glass Explorers are technology-worshipping geeks
   Our Explorers come from all walks of life. They include parents,
   firefighters, zookeepers, brewmasters, film students, reporters, and
   doctors. The one thing they have in common is that they see the
   potential for people to use technology in a way that helps them engage
   more with the world around them, rather than distract them from it. In
   fact, many Explorers say because of Glass they use technology less,
   because they’re using it much more efficiently. We know what you’re
   thinking: “I’m not distracted by technology”. But the next time you’re
   on the subway, or, sitting on a bench, or in a coffee shop, just look
   at the people around you. You might be surprised at what you see.
   Myth 4 - Glass is ready for prime time
   Glass is a prototype, and our Explorers and the broader public are
   playing a critical role in how it’s developed. In the last 11 months,
   we’ve had nine software updates and three hardware updates based, in
   part, on feedback from people like you. Ultimately, we hope even more
   feedback gets baked into a polished consumer product ahead of being
   released. And, in the future, today's prototype may look as funny to us
   as that mobile phone from the mid 80s.
   Myth 5: Glass does facial recognition (and other dodgy things) Nope.
   That’s not true. As we’ve said before, regardless of technological
   feasibility, we made the decision based on feedback not to release or
   even distribute facial recognition Glassware unless we could properly
   address the many issues raised by that kind of feature.  And just
   because a weird application is created, doesn’t mean it’ll get
   distributed in our MyGlass store. We manually approve all the apps that
   appear there and have several measures in place (from developer
   policies and screenlocks to warning interstitials) to help protect
   people’s security on the device.
   Myth 6: Glass covers your eye(s)
   “I can't imagine having a screen over one eye...” one expert said in a
   recent article. Before jumping to conclusions about Glass, have you
   actually tried it? The Glass screen is deliberately above the right
   eye, not in front or over it. It was designed this way because we
   understand the importance of making eye contact and looking up and
   engaging with the world, rather than down at your phone.

   Myth 7 - Glass is the perfect surveillance device
   If a company sought to design a secret spy device, they could do a
   better job than Glass! Let’s be honest: if someone wants to secretly
   record you, there are much, much better cameras out there than one you
   wear conspicuously on your face and that lights up every time you give
   a voice command, or press a button.
   Myth 8 - Glass is only for those privileged enough to afford it
   The current prototype costs $1500 and we realize that is out of the
   range of many people. But that doesn’t mean the people who have it are
   wealthy and entitled. In some cases, their work has paid for it. Others
   have raised money on Kickstarter and Indiegogo. And for some, it’s been
   a gift.
   Myth 9 - Glass is banned... EVERYWHERE
   Since cell phones came onto the scene, folks have been pretty good at
   creating etiquette and the requisite (and often necessary) bans around
   where someone can record (locker rooms, casino floors, etc.). Since
   Glass functionality mirrors the cell phones (down to the screen being
   off by default), the same rules apply. Just bear in mind, would-be
   banners: Glass can be attached to prescription lenses, so requiring
   Glass to be turned off is probably a lot safer than insisting people
   stumble about blindly in a locker room.
   Myth 10 - Glass marks the end of privacy
   When cameras first hit the consumer market in the late 19th century,
   people declared an end to privacy. Cameras were banned in parks, at
   national monuments and on beaches.  People feared the same when the
   first cell phone cameras came out. Today, there are more cameras than
   ever before. In ten years there will be even more cameras, with or
   without Glass. 150+ years of cameras and eight years of YouTube are a
   good indicator of the kinds of photos and videos people capture--from
   our favorite cat videos to dramatic, perspective-changing looks at
   environmental destruction, government crackdowns, and everyday human
   miracles. ﻿
   2014-03-20
   3 photos
   [walking%2Bwith%2Bcell%2Bphones.png]
   Google Glass's photos
   [mobile%2Bdevices.jpg]
   [Screen%2BShot%2B2014-03-20%2Bat%2B11.46.02%2BAM.png]
   1924
   804
   Andres Calvo's profile photo Binh Dang's profile photo Robin de
   Villiers's profile photo Corban Hoppins's profile photo
   298 comments
   Otakar Schön
   +
   2
   0
   1
   0
   Reply

   i really hope for some big news at Google I/O 2014....
   This posts comes at the right time, but is a bit weak to disspell the
   doubts tech community (geeks not the general public) are facing
   regarding glass.
   Still, I am pretty excited about a prospect of using Glass for a full
   week in near future. It cant come soon enough﻿
   Shawn Mernagh
   +
   4
   5
   6
   5
   Reply

   Excellent post, Thank you Glass Team. ﻿
   Jeremy Reger
   +
   2
   3
   2
   Reply

   I wouldn't count on glass news at io +Otakar Schön, others yes but not
   glass.. just saying.. ﻿
   Otakar Schön
   +
   1
   1
   2
   1
   Reply

   +Jeremy Reger we have a saying in my country that hope dies the
   last...
   I was there two years ago when Glass was announced and I watch the
   space so closely... but I too start to feel like things are moving too
   slow. I wrote an article about the state fo glass last week and it was
   pretty depressing. Especially the lack of apps while most of the
   innitial testers were developers. ﻿
   Pete Stergion
   +
   5
   6
   5
   Reply

   Well said +Google Glass ﻿
   Douglas Girardot
   +
   7
   8
   7
   Reply

   Blunt honesty is the best kind of honesty.﻿
   Joe Gaspar
   +
   1
   7
   8
   7
   Reply

   I feel like #6 should be true. Specifically, I mean that Glass should
   come in a DBZ Scouter form factor.﻿
   Jason Saunders
   +
   1
   1
   2
   1
   Reply

   In myth 4, what was the 3rd hardware update?  In the last 11 months
   there have only be V1 and V2 versions right?﻿
   Timothy Jay
   +
   1
   1
   2
   1
   Reply

   Thanks for posting this.  While I've gotta admit that those who run
   social media outlets for Google-esque products have always been bold
   and talkative with the community, I feel like this is a post that wipes
   out a lot of the rumors and thoughts that've been hurting Glass.
   Respect.﻿
   Scott Joniec
   +
   0
   1
   0
   Reply

   Great article! ﻿
   Robert Vorthman
   +
   7
   8
   7
   Reply

   #6 quotes Jim Lardear from AAA who supports legislation to ban Glass
   while driving.  I hope being called out by Google makes him take a
   second look at how hands-free devices like Glass can make driving
   safer.  It is the only GPS I know of that allows you to enter a
   destination and receive navigation guidance both hands-free and
   eyes-free.﻿
   Spencer Kleyweg
   +
   2
   3
   2
   Reply

   Amazing list! I love being an Explorer even though many people are
   unaware of the true potential of Glass!﻿
   Thomas Tenkely
   +
   1
   0
   1
   0
   Reply

   +Google Glass ...
   Thank you very much for making this post. I hope this isn't a one and
   done situation. Glass education coming directly from you is incredibly
   important. ﻿
   Vincent Martinez
   +
   2
   3
   2
   Reply

   Great post. I love it. Sharing.﻿
   Teddy A
   +
   0
   1
   0
   Reply

   Love it!﻿
   Joe Evans
   +
   0
   1
   0
   Reply

   Thanks for finally making this. ﻿
   David Allen Wizardgold
   +
   0
   1
   0
   Reply

   I would love to spend time with Glass. Technology is great anyway and
   Glass is is even more enhancing personally.
   Lovely toy to play with too.﻿
   Lou Kohn
   +
   1
   2
   1
   Reply

   This needs to be public knowledge for all. The more that can read and
   understand this the more Glass can be accepted in our culture! ﻿
   Roger Lam
   +
   1
   2
   1
   Reply

   Was there an XE-A?  Would love to see details for the sake of
   technology history.﻿
   Erik Boesen
   +
   1
   2
   1
   Reply

   Agreed! +Lou Kohn﻿
   Ned Jeffery
   +
   1
   2
   1
   Reply

   +Jeff Jarvis would be proud of you for Myth 10. It's almost like he
   wrote it himself :-P ﻿
   Chad Louis
   +
   2
   3
   2
   Reply

   Serious question, related to myth two and ten, is Glass not subject to
   the Communications Assistance for Law Enforcement Act?
   http://en.wikipedia.org/wiki/Communications_Assistance_for_Law_Enforcem
   ent_Act https://www.eff.org/issues/calea﻿
   Paul Schroeer-Hannemann
   +
   0
   1
   0
   Reply

   So people were claiming the end of privacy even back in the 19th
   century?  Funny how they could say that when the majority had only had
   privacy for less than a century.﻿
   Andy Turner
   +
   4
   5
   4
   Reply

   What about the 30 minute battery life?﻿
   Thomas Tenkely
   +
   1
   2
   1
   Reply

   +Jason Saunders XE-A, B, and C (C is what people call V2...it is not)﻿
   Keith Barrett
   +
   7
   8
   7
   Reply

   +Google Glass Who told you that Walt Disney isn't frozen??!!!!!﻿
   Jeremy Reger
   +
   2
   3
   2
   Reply

   Haha seriously +Keith Barrett!! I want to know! ﻿
   Jason Saunders
   +
   3
   4
   3
   Reply

   +Thomas Tenkely If you look at the last picture of the Evolution of
   Glass, which version had the chrome camera accent and what appears to
   be a flash?  There may be more to that statement than XE A, B, and C.
   Also pay attention to word choice...  Upgrade means "an improved
   version".  By definition XE-A is the initial device, XE-B and XE-C are
   upgrades. ﻿
   Jasper Geier
   +
   1
   2
   1
   Reply

   Really this is great I got my glass yesterday and it's amazing. Before
   I got it I beloved all the rumors but it's the coolest thing ever!﻿
   Bash Terminal
   +
   0
   1
   0
   Reply

   My only problem with +Google Glass is the asimetrical, "lop-sided"
   design, but as batteries get smaller I'm sure that will go. Until then,
   though, I'd rather wear half a car air filter like Geordie LaForge. Heh
   heh.﻿
   Kevin Trainor
   +
   2
   3
   2
   Reply

   I love my glass it's amazing! I just wish my boss would allow me to
   wear it on shift...﻿
   Julian Haeger
   +
   0
   1
   0
   Reply

   "ultimately we hope even more feedback gets baked into a polished
   consumer products ahead of being released" - does that strike anyone as
   sounding less confident / committed to consumer release any time soon?
   Or am I just being paranoid? ﻿
   Peter G McDermott
   +
   1
   0
   1
   0
   Reply

   +Google Glass, these are some great myths you are aiming to dispel, but
   you're preaching to the choir on this one.
   How is Google going to help educate the public about this technology?
   We've already seen you contract with third party marketing companies to
   establish a presence in brick and mortar stores like Best Buy, but
   there is no Glass exposure in those stores.
   Granted, it is not your responsibility to educate the public, but to
   gain faster and wider cultural acceptance, there is going to need to be
   some serious evangelism. Is there any plan to start "vetting" Explorers
   to take to local media outlets to start sharing the truth about Glass
   and to end the rumors?﻿
   Tomas Pekarek
   +
   2
   3
   2
   Reply

   But the price is really out of my range...﻿
   Steve Mattison
   +
   1
   2
   1
   Reply

   Wow, just saw #MrRogers   is trending down right now, I wonder if this
   article is why it's even on the radar?﻿
   Iwan Uswak
   +
   4
   5
   4
   Reply

   +Google Glass i have created an infographic to explain myth 7. It
   explains how the glass camera works and why it is in some cases even
   harder to record secretly than with other devices. Check out
   http://glass-apps.org/google-glass ﻿
   marek kolbuk-lukasiewicz
   +
   0
   1
   0
   Reply

   :-)﻿
   Andres Calvo
   +
   2
   3
   2
   Reply

   I'm starting a blog on Android and Glass development, and one of my
   first posts is on this same topic, though I called them misconceptions
   instead of
   myths. http://www.ocddevelopers.com/2014/common-misconceptions-about-gl
   ass/﻿
   Thomas Tenkely
   +
   3
   4
   3
   Reply

   +Peter G McDermott... I'd argue it is their responsibility to educate
   the public, if they want Glass to succeed in anyway.﻿
   Richard Gil
   +
   1
   2
   1
   Reply

   I'm happy to explain and let people try my GG.  Poeple have always a
   positive response (demographic from early 20s to late 70's).  I love
   them.  Just got my prescription frame, the only thing is I'm sad I'm
   going to need to choose between sunglasses or prescription.  My GG w/o
   prescription can be used with contacts and will use the sunglasses
   attachment when needed (golfing or snowboarding).  Not the same with
   prescription.﻿
   Daniel Lawlor
   +
   0
   1
   0
   Reply

   About number 8, I got invited to be an Explorer at a bad time. Really
   excited about what the future will be like with Glass in years to come
   though. Waiver? ﻿
   Eric forty
   +
   5
   6
   5
   Reply

   When the internet was born that marked the end of privacy. Maybe if
   people stopped posting there lives on Facebook,twitter and every other
   social network instead of blaming Google Glass and the NSA for
   violating their privacy and took responsibility for what they put
   online.
   I understand if someone wants to post that their child won the science
   fair or got into Harvard. What parent wouldn't be proud but I do not
   need to know every detail of your child's life from the day they were
   born to the day they graduated college and would it kill people to
   actually talk to someone in person rather then text or FaceTime them
   from the other room.﻿
   Gilbert Gonzalez
   +
   0
   1
   0
   Reply

   I can't really confirm any of this....brotha can't get a damn invite to
   buy one! Lol ﻿
   Neil Howcroft
   +
   0
   1
   0
   Reply

   Please can.we try glass in the uk? I would love to be an explorer. I
   signed up as soon as I could even though it was for USA only﻿
   J.L. Francois
   +
   7
   8
   7
   Reply

   When people ask me ,"Are you recording me?" my response is, "No, are
   you famous?"﻿
   David Kim
   +
   0
   1
   0
   Reply

   I love you +Google. You may take my money. ﻿
   Steve A
   +
   1
   2
   1
   Reply

   Very well put +Google Glass Some have heard here. Negative feedback
   hasn't happened yet.. Life can go on with use.( actually have cell in
   video before I thought about it...and stuck it in pocket) I have my
   hands free a lot more! Thanks also enjoy texting with both hands on the
   wheel and eyes on the road. Or simply walking, can't wait to try the
   soup know its going to be great! Try my best to explain and let others
   try and see the smiles are plentifully as well as interest.﻿
   Garner Marshall
   +
   3
   4
   3
   Reply

   I'm as confused as +Jason Saunders I had glass from the beginning and I
   didn't know there were 3 revisions. I thought there was only 2
   versions. (Maybe you mean the bulky alpha version that you created
   before v1)
   +Robert Vorthman Jim Lardear is a 'tard. I tell people this all the
   time about any product, "don't knock it 'til you try it" you can't make
   assumptions based on some dream you had. He never owned a pair of
   +Google Glass, furthermore you can't get a feel for the unit by playing
   around. I thought it was a bit awkward at first before I gave it a
   chance. It took me about 3 days to get used to it.
   +Lou Kohn They should make this into an informative YouTube video.
   +Keith Barrett in with you I think that Walt Disney is really frozen
   +Peter G McDermott & +Thomas Tenkely I understand both of views but I
   don't think that it's Google that needs to educate the public. Just
   like any other technology we the people usually educate each other.
   Tech reviewers and YouTubers do a very good job of that. No one offered
   formal training sessions on televisions, cell phones, game consoles,
   and most other household gadgets.
   +Richard Gil we have to get a company to do transition lens.
   For all those that are using price as a deterrent. I am definitely NOT
   rich. I wanted the device and saved up and got one because I saw the
   potential. I am really happy with this prototype as I use my cellular
   phone less and less and my Glass more and more. I feel that I'm way
   more productive using Glass than when I just had a cell phone.
   Glass is a great device and I think once more people learn what it can
   do I think that fear of loss of privacy will dissipate. ﻿
   Michael Gomez
   +
   0
   1
   0
   Reply

   +Robert Scoble﻿
   Diana de Avila
   +
   0
   1
   0
   Reply

   This is great!  Thanks #GoogleGlass  ... I hope you will add this to
   the FB page too!!!  Need to share there.  It seems as if there is much
   more misunderstanding over in that world than there is over here on G+.
    :-D﻿
   Yanil Ruiz
   +
   2
   3
   2
   Reply

   Aren't the "looking down" people from the first photo +Ingress
   players?﻿
   John Shaw
   +
   1
   2
   1
   Reply

   I think the "Are you recording me?" question is one of the most common
   I get. Once you get passed that one people really seem to be very
   interested in the technology and the sentiment from random people on
   the street seems far more positive than negative. If I were designing
   the hardware I might consider slapping a red light or something on it
   to appease the "I can't tell when you're filming" crowd.﻿
   William Pulkowski
   +
   1
   2
   1
   Reply

   Very good Urban Mythbuster list (Fact vs Fiction). I have been using
   Glass for three months and can confirm the advantages of Glass over
   constantly looking down at your cell phone while walking. Technical
   writers who perpetuated these erroneous claims must have never really
   tried Glass 1st hand. Try it...to separate fact from fiction!﻿
   Google Glass
   +
   3
   4
   3
   Reply

   +Jason Saunders +Thomas Tenkely +Garner Marshall Sorry for the
   confusion! Our 3 hardware updates refer to the one-time device swap,
   the Titanium Collection frames, and our stereo and mono earbuds.
   +Neil Howcroft Thanks for being a fan! No updates on when Glass might
   be available outside the US, but we hope to expand in the future.﻿
   Neil Stoker
   +
   0
   1
   0
   Reply

   Interesting move...
   But the strategy could be something like this: let Android Wear grow
   what is a comparatively similar model but with more immediately
   achievable technology, and when that model is better established the
   technical hurdles to get glass small enough with better battery life
   should have been scaled.
   Getting lots of people using Wear could give the kick start to a killer
   app that Glass currently lacks too.﻿
   Greg Lauver
   +
   0
   1
   0
   Reply

   This is great; it actually acknowledges some of my concerns as well. My
   only reason for not wearing them at this very moment is the price tag
   for the prototype. Honest - I got an Explorer invite to my elation and,
   simultaneously, disappointment since it's just too high for me. ﻿
   Stan Jamrog
   +
   0
   1
   0
   Reply

   Love the idea. I for one would welcome facial recognition apps. I am
   faceblind. You have no idea how nice it would be if people who say hi,
   and expect me to recognize them, came with a little hud telling me who
   it is.﻿
   Gregory Bing II
   +
   0
   1
   0
   Reply

   +Google Glass exactly. Thank you for this. It is our job as explorers
   to break these thought processes. I allow people to wear mine whenever
   possible so they can understand﻿
   Jason Saunders
   +
   1
   2
   1
   Reply

   +Google Glass thanks for clarifying. I haven't taken that step yet.
   Time to upgrade.﻿
   Melissa Rudden
   +
   0
   1
   0
   Reply

   +Google Glass Very glad to see this. I've shared it. I love letting
   others try on and ask me questions about #glass  It makes me smile when
   I see the light go on as they realize the possibilities. I'm crossing
   my fingers that the consumer version will come out sooner rather than
   later and at a price that is affordable so that more people will be
   able to use this incredible technology. ﻿
   Abner shi
   +
   0
   1
   0
   Reply

   I want to know the final answer myth 8, I believe it will make everyone
   can afford﻿
   Christopher Ferguson
   +
   0
   1
   0
   Reply

   +Jeff Jarvis you would appreciate this post immensely. They even talk
   about the introduction of the cameras to the consumer market like you
   use as an example on TWIG all the time. ﻿
   Binh Dang
   +
   0
   1
   0
   Reply

   I love it ﻿
   Josh Arcadia
   +
   0
   1
   0
   Reply

   u know how to defend yourself... everything has its pros and cons so
   deal with it﻿
   Dan K
   +
   3
   4
   3
   Reply

   Does an LED come on indicating that it is recording or taking a photo?
    If not, why not?  End the "are you recording me?" with an LED
   indicator on the front and side that shows when it's recording.﻿
   Melissa Rudden
   +
   3
   4
   3
   Reply

   +Daniel Kinem there is no LED, but you can see the lit up screen in the
   prism from most vantage points. ﻿
   Raymond Farias
   +
   1
   2
   1
   Reply

   Yes an LED does come on when recording. Yet, rumors and worries still
   spread. ﻿
   Dan K
   +
   0
   1
   0
   Reply

   +Raymond Farias Thanks﻿
   Mostafa Safavi
   +
   0
   1
   0
   Reply

   Ping +Center You
   #myfavlist14﻿
   Lewis Vail
   +
   4
   5
   4
   Reply

   Do you have any references to support your claim regarding privacy
   concerns when cameras first hit the consumer market? I did some quick
   searching and couldn't find anything online to support this. Also my
   wife took two history of photography courses in college and she's never
   heard of this. And I'm pretty sure a turn of the 20th century consumer
   camera would be fairly useless in a museum.﻿
   Douglas Stone
   +
   2
   3
   2
   Reply

   Kodak cameras were banned from beaches when they first came out over
   privacy concerns﻿
   Bryan Foster
   +
   0
   1
   0
   Reply

   AMEN and AMEN! ﻿
   Lewis Vail
   +
   1
   2
   1
   Reply

   Found it:
   http://www.pbs.org/wgbh/amex/eastman/peopleevents/pande13.html﻿
   Stafford Lumsden
   +
   3
   4
   3
   Reply

   Myth 5 - officially sanctioned apps for #googleglass don't do facial
   recognition.... Some side loaded ones have the potential ("Name Tag").
   Just saying....﻿
   Ned Jeffery
   +
   1
   2
   1
   Reply

   +Stafford Lumsden so what. you can do the same thing with your phone.
   that's kinda the point. in fact Google Goggles used to do exactly this
   until that feature was pulled.﻿
   Dan K
   +
   0
   1
   0
   Reply

   There should be no problem as the Glass has a flashing LED light in
   plain view when it's recording.﻿
   Stafford Lumsden
   +
   1
   2
   1
   Reply

   +Ned Jeffery don't get me wrong, I am having great fun with my
   #googleglass, but that's the kind of thing that someone will latch on
   to as "proof that +Google is evil" blah blah blah.... And various other
   arguments I have no time for. ﻿
   Travis Lenamon
   +
   1
   2
   1
   Reply

   So true﻿
   Michael Delpach
   +
   0
   1
   0
   Reply

   So +Google Glass you are saying Glass is not ready for the prime time?﻿
   Douglas Stone
   +
   0
   1
   0
   Reply

   That's correct. It is in beta testing right now. ﻿
   Corban Hoppins
   +
   0
   1
   0
   Reply

   I'll get glass when it can read power levels.﻿
   Alex Bryant
   +
   1
   2
   1
   Reply

   I heard when it's made available to the public it will be priced around
   $400. Any ideas when it will be put out to market or is it still under
   wraps?﻿
   John Shaw
   +
   0
   1
   0
   Reply

   +Raymond Farias There is no LED on mine when it is recording... the
   display stays on and people can see that light but there is certainly
   no record light.﻿
   Douglas Stone
   +
   0
   1
   0
   Reply

   Yes, no LED but you can see video on crystal if you stare at someone
   wearing glasses. ﻿
   Mokhtar J
   +
   5
   6
   5
   Reply

   Is there a reason almost every single one of you feel the need to wear
   the Glass headgear in your profile pics? The extreme level of
   evangelizing here is pretty creepy, to be quite honest. I think that's
   one of the things that turns normal people off. ﻿
   John Shaw
   +
   1
   2
   1
   Reply

   +Mokhtar J We don't ALL wear it in our profile pictures...﻿
   Mokhtar J
   +
   0
   1
   0
   Reply

   +John Shaw I realise that, which is why I said "almost". Its fine to
   support a product, but needing to update your profile photo to include
   it is just a bit much. It comes off as either gloating in a strange
   fashion, or trying way too hard to normalise something that isn't
   normal.﻿
   Stafford Lumsden
   +
   0
   1
   0
   Reply

   +Raymond Farias... I'm not even wearing mine right now! (But they are
   on my desk in front of me)﻿
   Atharv Bhat
   +
   0
   1
   0
   Reply

   Gotta admit it......
   People who believe these myths are dumb﻿
   Abner shi
   +
   0
   1
   0
   Reply

   +Alex Bryant I get the message is $600?﻿
   Brian Estrella
   +
   2
   3
   2
   Reply

   Feels like all i really want is a go pro hung on my face.... ﻿
   Saeed Rasooli
   +
   0
   1
   0
   Reply

   My personal suggestion for the future is a colorful and fast display
   similar to (grayscale and slow) E-Book readers, which don't produce
   light.﻿
   H. David Shaw
   +
   0
   1
   0
   Reply

   And don't forget Paul from the Wonder Years is Marilyn Manson.  ﻿
   George Krumins
   +
   5
   6
   5
   Reply

   None of this addresses the issue that it just makes the wearer look
   insanely stupid.﻿
   Chris van Gorder
   +
   0
   1
   0
   Reply

   Then you don't have to buy or wear one +George Krumins . It's that
   simple.﻿
   Vishal Khedkar
   +
   0
   1
   0
   Reply

   +Google Glass is there any way I get the privilege to get a Glass? Or
   is it US only?﻿
   Atharv Bhat
   +
   0
   1
   0
   Reply

   +Vishal Khedkar there were only a few﻿ and even if u manage to get
   one.... Its 80000 rupees..
   Better wait for consumer version which will (most probably) be cheaper
   and better than the explorer edition , which i assume is the beta
   version.﻿
   Vishal Khedkar
   +
   0
   1
   0
   Reply

   +Atharv Bhat also it is US only :/﻿
   Matt Koehler
   +
   0
   1
   0
   Reply

   I was so happy the day I got my invite for google glass, although I
   couldnt afford it at the time because I was moving to germany for the
   army and needed to keep a little cushion in my wallet for any
   emergencies that came up, I really wish I could have participated
   though﻿
   Caroline Lowe
   +
   1
   2
   1
   Reply

   Thanks +Google Glass for the list! Look forward to the day when there
   are a lot more of us out there wearing Glass and we all just blend with
   the scenery. Hope Glass will create a charcoal-colored vest in which we
   can carry our Glass,etc and truly have our hands-free "wearable"
   technology. ﻿
   Sheraz Ahmad Khilji
   +
   0
   1
   0
   Reply

   I would say that this post will shut up all the critics that have
   nothing more to do than spreading negativity about the new innovations
   in market. Learn to Adapt people :D
   Thanks for clearing the myths  +Google Glass ﻿
   Tim Lesher
   +
   0
   1
   0
   Reply

   +Steve Mattison More likely because his birthday was yesterday.﻿
   Atharv Bhat
   +
   0
   1
   0
   Reply

   +Viktor Braunagel while I agree with you on that app thing...
   I disagree with you saying that its not useful....
   Its certainly useful to pissoff your friends :p
   Jokes aside..
   Glass gives us a first person view of pretty amazing things.
   Imagine an astronaut with Google glass on a space walk !!
   Who wouldn't want to see that !!
   In near future , I believe that these things will change the way we use
   our phones...
   Today we can read messages and stuff without even touching our phones
   using glass...
   Glass will also prevent accidents.
   Drivers won't have to look at that stupid screen and take their eyes
   off the roads...
   So it is pretty useful. :)﻿
   Jonniher Martinez
   +
   0
   1
   0
   Reply

   Realmente que en el Google I/O 2014 vamos a recibir grandes noticias
   sobre este gadget. ﻿
   Translate
   Michael McGrade
   +
   3
   4
   3
   Reply

   Hey +Google Glass send me a pair and I'll help remove the myths about
   #Glass ...thanks.﻿
   Colin McNicol
   +
   1
   2
   1
   Reply

   Why not facial recognition? The greatest practical use for Google Glass
   could be to save the embarrassment of not being able to recall the name
   of that old friend you just bumped into and that you know you have to
   introduce to your partner any second now!﻿
   Bruce Burke
   +
   0
   1
   0
   Reply

   Great stuff! We're focused on +Google Glass & other wearables at the
   Social Mobile Engagement Conference & Code Challenge - Register today
   to Win +Google Glass http://www.socialmobileengagement.com﻿
   Curtis Smith
   +
   0
   1
   0
   Reply

   +Colin McNicol Eh, I don't see that as a big problem to begin with.
   More a fan of saying "I'm not sure if I already told you, but I forget
   names very easily. I also forget what I've told people." ﻿
   Dan Tynan
   +
   2
   3
   2
   Reply

   And yet, some people continue to act like Glassholes.
   https://www.yahoo.com/tech/are-you-a-glasshole-take-this-quiz-to-find-o
   ut-79901226113.html﻿
   Tom Geeve
   +
   0
   1
   0
   Reply

   I really agree with this post, people have to try it their own and do
   not have to say things without any knowledge and thinking about it...﻿
   George Krumins
   +
   2
   3
   2
   Reply

   +Chris van Gorder
   Your response does not address my comment. I am not talking about me, I
   am talking about those people who choose to look a total nerd by
   wearing Google glasses. Being a nerd is not cool, therefore wearing
   Google glasses is not cool.﻿
   Laura Ulrick
   +
   3
   4
   3
   Reply

   Myth 8 is my FAV.... I've seen numerous holidays, a birthday, a
   anniversary, and countless occasions a "just cause" gift could have
   been given (yesterday I Googled "Why does Ohio even call this time of
   year Spring, when I am freezing to death" on a +Chromebook  , after
   checking my Google Apps from +Google for Nonprofits  based work email
   on my +Android  phone and adding a appointment to my personal Google
   calendar via Chrome displayed on my TV thanks to +Chromecasting ) and
   yet... not once have I opened my snailmail box to find a package
   labeled "  +Google Glass   Gift from +Google  for (insert holiday,
   occasion, reason here). What on +Google Earth  do I have to do Google?
   Do I not love you enough already?﻿
   JennySue Devost
   +
   3
   4
   3
   Reply

   +George Krumins you dont know to much do you? we live in a day and age
   where glasses ARE NOT NERDY, millions of ppl purchase glasses that are
   fake as in buying frames and wearing them with just a glass lens. so
   for you to say that they are nerdy you need to wake up and stop your
   senseless ignorant comments.      ﻿
   Noble Ackerson
   +
   2
   3
   2
   Reply

   +George Krumins says being a nerd is not cool. Being cool is cool
   though I bet right? WTF are you talking about...stop it.﻿
   Curtis Smith
   +
   0
   1
   0
   Reply

   +Alain Caupin Old and outdated are different things. :P﻿
   Daniel McDonough
   +
   1
   2
   1
   Reply

   At my office these facts don't matter. Glass is banned because a couple
   of people feel uncomfortable.﻿
   Lester G. Santos
   +
   0
   1
   0
   Reply

   I use Glass when playing video games. Mostly so i don't have to take my
   eyes off the screen. The rest of the time it sits in it's case
   charging. (BTW if anyone is already working on a map overlay for World
   of Tanks and or League if Legends, hurry it up pls).﻿
   Phillip Pham
   +
   0
   1
   0
   Reply

   A friend of mine let me try on his GGlass and although it's cool from a
   technology perspective, but man it hurt my eyes just after few minutes
   of use.  Initially, when glass came out, I thought you can look into
   the display with just one eye, but my short time with it.  I have to
   focus my eyes into the "center' of the focal point of display.  If
   Glass goes mainstream, I think the display needs to be bigger and more
   "natural".   Maybe if I use it more often I'll get use to it...who
   knows.﻿
   LS Da Mota
   +
   0
   1
   0
   Reply

   Good thing Google Wear has made Glass irrelevant.﻿
   Matt Hewlett
   +
   2
   3
   2
   Reply

   Here's one that isn't a myth:
   Google Glass is incompatible with prescription eyeglasses.﻿
   Brian Day
   +
   1
   2
   1
   Reply

   After several months wearing Glass in a town that has its own share of
   myths (Detroit), I was asked for the first time last night if I was
   recording. The question was tongue in cheek; nearly every conversation
   I've had (including with curious police/fire departments and physicians
   interested in potential application in the medical space) has been
   around how practical the device is, and efficiencies gained from using
   Glass. I am admittedly still a bit self conscious while wearing glass,
   but the impact on workflow has certainly been felt, and the
   conversations it generates have been both intelligent and practical.
   Benefits and potential aside, even with the tap code access, there are
   some obvious security concerns that need to be addressed (for example,
   any voice can command Glass to access content). In the early phases of
   many development projects, security takes a backseat to usability, but
   there appears to be enough steam behind this moonshot to cover the
   necessary bases.
   As a technologist, I've greatly enjoyed both the personal experience
   and the first person peek into the realm of possibility with Glass. I
   hope the momentum continues. ﻿
   Matt Weldon
   +
   8
   9
   8
   Reply

   Regarding Myth #2: "So next time you’re tempted to ask an Explorer if
   he’s recording you, ask yourself if you’d be doing the same with your
   phone. Chances are your answers will be the same."
   Wow, you guys just don't get it do you?  I can TELL when someone is
   probably recording me with their phone, because most likely they are
   holding it up in the air and pointing it at me.
   The whole creep-factor with Google Glass is the fact that I DON'T know
   when you're recording me or not.  You're wearing them on your head when
   you're recording, you're wearing them on your head when you're NOT
   recording.  There is no light or indicator or anything to alert others
   that the camera is on.
   Seriously how do you guys not get this?  How can you be so incredibly
   dense?
   Put a damn LED light on the front when Glass is recording.  To give
   people the courtesy of deciding whether they'd like to be recorded or
   not.  Otherwise people will continue to be creeped out by this product
   and find it invasive and rude when someone is using them in public.
   It's a design problem.  Fix it.﻿
   Curtis Smith
   +
   0
   1
   0
   Reply

   +Matt Hewlett Umm... Sure... If you want to believe that... Despite it
   being that Google Glass is actually only compatible with glasses
   (regardless of lenses).﻿
   Tim Robertson
   +
   2
   3
   2
   Reply

   Thanks for this list, I just copied and pasted it on my Facebook page
   to answer most of the questions I have been getting.﻿
   Darien Caldwell
   +
   4
   5
   4
   Reply

   Comparing it to a cell phone is ridiculous. You don't walk down the
   street with a cell phone stuck on your face. So when someone pulls a
   cell phone out and starts pointing it at you, that's a pretty big clue
   they are starting to record you.
   With Glass, there is no social cue to let people know when a recording
   has started; Google refuses to even put a warning light on it to let
   others know recording is happening. That's the big problem. Until
   Google respects the rights of others to know when they are being
   recorded or not, their precious glasses will not be socially accepted.﻿
   Lester G. Santos
   +
   0
   1
   0
   Reply

   +Matt Hewlett What prescription do you have that it's not compatible?
   I'm wearing Glass on prescription lenses right now. And my prescription
   is up there in numbers.﻿
   Zach Snethen
   +
   2
   3
   2
   Reply

   Thank you for posting this Google as an explorer I have difficulty with
   people that freak out about glass and there is a lot of mis information
   out there. I don't get how people can write reviews without even trying
   them. And a large amount have!﻿
   iPan Baal
   +
   1
   2
   1
   Reply

   It's not what Google intends, but what all the myriad users will create
   and adapt to do with it that could be potentially worrisome to a lot of
   people.
   All this post really says is, "We don't officially support what a lot
   of you pervs are going to do anyway, that way we can cover our own ass
   and promote our product".
   Which is totally cool with me - I'm a fan! I couldn't care less about
   privacy, it's an outdated concept.
   Just stop trying to candy coat the shit. I don't buy the corporo-speak.
   We all know that people - the ingenious little buggers they are - are
   going to do everything that is physically possible with this
   technology, whether you officially support it or not.
   That's just the nature of evolution.
   Onward, brave #Glassholes  - you are the future.﻿
   Adam Lock
   +
   1
   2
   1
   Reply

   I think these myths are hilarious because they ignore the obvious
   point. Glass is like constantly pointing a video camera at someone.
   It's disrepectful, creepy and distracting. How is a person supposed to
   know if the camera is on or off? Why is the burden on them to know any
   way? People WILL take offence and glass users had better apply common
   sense or they're inviting a fist in their face.﻿
   Zach Snethen
   +
   2
   3
   2
   Reply

   +Adam Lock I got news for you pal there are cameras pointing at you all
   the time. time to get over it. and as for punching in a glass Explorer
   in the face I wouldn't recommend it you only thing going to do is get
   thrown in jail for assault and best of all we will have video of it and
   don't think ima take your punch sitting down you going to get the crap
   beat out of you﻿
   Tom Guarriello
   +
   0
   1
   0
   Reply

   Explorers, just remember what they did to Google Reader...﻿
   Panos La
   +
   0
   1
   0
   Reply

   Well I would say let the myth busting for the mythbusters...
   Your glass is definitely marking the end of privacy. Your device have
   the capability to record video, take snapshots, acquire biometrics such
   as my voice as well other peoples voice, it can take biometrics from
   the facial recognition, it can point my location and through social
   media such as facebook, your google+ and many many other can know what
   I like for lunch, what's my sexual orientation, my political views,
   what I crave, what I hate and many many others.
   So, your argument is that, well you know... we won't let our device to
   use facial recognition... we got minimum of 10secs of video recording..
   your privacy on our social media is granted.
   Your other argument is that, this technology that I am already
   describing it already exists on mobile phones... which is true.. The
   fact that it exists though it doesn't mean that it is not an intrusion
   to our privacy. I would say that what you have created there is a
   better version of the mobile phone, intruding in our privacy more
   efficiently...
   Just because you give us your word that you won't use the technology
   you already have is not enough... who knows what shitty excuse you will
   use to actually "force your selves" to include gradually facial
   recognition and god knows other dodgy things to the authorities and god
   know who else...
   The worse thing though is this... even if I choose not to wear your
   glasses and make my privacy transparent to you, my privacy is still not
   granted.
   Someone else will wear the glasses, someone else will accidentally
   record me, my face or my voice... someone else will accidentally reveal
   my whereabouts only by having me in a geotagged picture. Your glass is
   pretty much like smoking... Someone can choose wether he smokes or
   not.. it's his health on the stake, but you have laws that prevents
   smokers to smoke publicly. Smoke cannot be controlled, and having
   someone smoking passively against his will is simply wrong.
   How you can grant me that my privacy will not be compromised just
   because someone else who is wearing your glasses won't record
   information about me collaterally?
   At least the mobile phone, in order to record it needs someone to pick
   it up and aim with it.. this kind of behaviour is obvious... Your
   glasses are on our heads, looking wherever we have our eyes looking...
   god know what will be you next hardware update... maybe a retina
   tracker to control the movement of the camera and actually look at
   exactly what we look and not what we "face"...﻿
   iPan Baal
   +
   2
   3
   2
   Reply

   Get used to the idea - whether it's Google, or someone else, the
   technology is coming, and it won't be contained.
   The much deeper issue is reciprocal transparency.
   We need to know when someone is watching us.
   The end of privacy should also mean the end of secrecy - when someone
   is watching me (recording me, intercepting my emails, reading them,
   etc.) I have no desire to stop them from doing that - what I want, is a
   notification that they are doing that.
   I want to take away the secrecy (privacy!) of their surveillance.
   Why should any group or individual get to keep the fact that they are
   spying on you secret (private!) when the very act is an intrusion of
   your privacy.
   It's about equality of surveillance.
   I want to know when (and who!) someone is watching me.
   End all secrecy, especially those who have any kind of power or
   authority.﻿
   Adam Lock
   +
   0
   1
   0
   Reply

   +zach snethen thanks for your condescending and pointless response﻿
   C. Wilson
   +
   0
   1
   0
   Reply

   In this era of wealth inequality, running around wearing a $1500 TOY is
   just asking for a baseball bat to the face. Every argument in favor of
   Glass is either insane or idiotic.﻿
   Thijs van H.
   +
   0
   1
   0
   Reply

   ugh﻿
   Raj Kumar
   +
   1
   2
   1
   Reply

   Please remove the camera - "the prying eye" - from the Google Glass.
   It'll make it lighter, cheaper, less obtrusive on the face and less
   offensive to the others. In other words, make it humble please!!﻿
   Jim Baker
   +
   2
   3
   2
   Reply

   +Robert Vorthman I have used car navigation systems in the US and UK
   that were eyes-free and hands-free, other than pushing an initial
   connect button...both connected to a real person to look up the
   address, and then gave audio instructions.﻿
   Lary Breeding
   +
   0
   1
   0
   Reply

   A few points about the list starting with #10.  The loss of privacy is
   a valid argument.  If I am walking down the street and see someone with
   a camera taking pictures because I recognize it as a camera I have the
   opportunity to stop, walk around that person, go in another direction,
   etc. I have no way of knowing if a person has these glasses on or not.
   If they are wearing them is the camera on or off, I have no real way of
   knowing particularly from a distance.  As for Myth's 5 and 7 if the
   camera's aren't of a high enough quality now they will be soon so that
   argument isn't really valid or at least it won't be for long.  We
   already live in a police state because of the Patriot act.  These
   glasses will only make it worse.  Google already tracks much of our
   lives, without our permission I might add, They have also proven their
   willingness to work with the government against us.  What is a good
   argument to trust Google and the government to not spy on us, their
   word?﻿
   Jim Baker
   +
   1
   2
   1
   Reply

   Indeed, the privacy issues (and distraction issues) seem little
   different than for other mobile devices.  (However, I do find that
   those are a bit too connected, and harvesting and selling information
   about me a bit too fervently.)  But the movie theater issue seems
   valid...a cell phone or camera one would have to hold up rather
   obviously, compared to a Glass (hence forbidding Glass wearing in a
   theater seems valid).
   This posting highlights an interesting issue...people aren't worried
   about the privacy aspects of mobile devices mostly because they don't
   think about them, and Glass makes them think about them.﻿
   iPan Baal
   +
   6
   7
   6
   Reply

   My eyeballs are cameras, and my brain is a recording device.
   I don't see people asking me to close my eyes everywhere I go.
   Privacy is a myth.﻿
   Hugh Roper
   +
   4
   5
   4
   Reply

   What about the myth that battery life is terrible? Oh wait, that's not
   a myth.﻿
   iPan Baal
   +
   0
   1
   0
   Reply

   Get a battery back pack?﻿
   Raj Kumar
   +
   0
   1
   0
   Reply

   Navigation is a great app for the glass and a camera-less Glass will
   work better.﻿
   Aziz A.
   +
   0
   1
   0
   Reply

   sound angry as heck﻿
   Raul Sanchez
   +
   0
   1
   0
   Reply

   Not mentioned - you'll still look like a complete ass wearing those
   into a seedy punk bar at 1am.﻿
   Tim Twelves
   +
   1
   2
   1
   Reply

   Privacy is a Human Right.
   No one shall be subjected to arbitrary interference with their privacy,
   family, home or correspondence, nor to attacks upon their honour and
   reputation. Everyone has the right to the protection of the law against
   such interference or attacks.
   Article 12, the Universal Declaration of Human Rights.
   http://www.un.org/en/documents/udhr/index.shtml#a12﻿
   Josh Sustarich
   +
   3
   4
   3
   Reply

   What a painfully self-aware, if not self-aggrandizing, post; as a
   casual observer I think it is a stretch to label anything from the
   above list as a widespread myth creeping toward accepted fact.  The
   overarching public sentiment (strategically parsed as the listed myths)
   seems to be that anyone wearing glass is a "glasshole".  Of course,
   that is not true, but the folks I have seen wearing Glass, to me, LOOK
   like (gl)assholes--and therein, Google, lies the obstacle.  Appearance
   isn't everything, but it can account for a whole lot.﻿
   Bill Smith
   +
   0
   1
   0
   Reply

   Lets see some glasshole wear them into a Vegas casino...hope they like
   the taste of carpet when security takes them down.﻿
   Dave Corson
   +
   2
   3
   2
   Reply

   Drink the cool aid.  Posts like this won't sell anything.  It comes off
   rather pretentious and defensive.  Would make more sense to acknowledge
   concerns and highlight how to address those concerns.  You're getting
   into Apple user levels of pretentiousness.﻿
   James Melton
   +
   3
   4
   3
   Reply

   If you want Glass to be considered something other than a toy for the
   elite, you are handling it wrong. Think about it. You have to be
   invited to test it. And you have to pay $1,500 for the privilege of
   being a guinea pig. And, the testers are called "explorers."
   I like a lot of things about Google. But Glass seems to be aimed
   entirely at the rich douchebag demographic. ﻿
   iPan Baal
   +
   2
   3
   2
   Reply

   +James Melton
   I disagree - I think it appeals mostly to the DIY crowd (at first).
   Not that elitist douchebags won't like it too, but rather that Google's
   "target" demographic is probably the kind of people who go to the Maker
   Faire.﻿
   Dennis Bratland
   +
   1
   2
   1
   Reply

   I guess if I glue a knife to my prescription glasses, they have to let
   me on a plane with it, right?
   Logic fail.﻿
   Lizzy Miles
   +
   1
   2
   1
   Reply

   i am a Glass Explorer and a hospice social worker.  not rich by any
   means, but i bought Glass because I think it will be helpful for me to
   participate in and also record our last wish events with hospice
   clients.  I certainly could have used Google Glass in the past few
   years when I was pushing a wheelchair through the zoo, on a ski slope
   with a hospice client, or fishing.   i look forward to all the ways I
   will use  my Glass﻿
   iPan Baal
   +
   2
   3
   2
   Reply

   Most of the naysayers are likely curmudgeony, neo-Luddites who will
   jump on board once it's common place, then claim they were on board the
   whole time.﻿
   Larry Mateo
   +
   0
   1
   0
   Reply

   You can write articles about Glass until the cows come home, but you
   have to convince the average person--me, for example--that they're
   useful in some way.
   I see many niche uses for the product, and they will function
   brilliantly therein, but why should I purchase a pair? What are the
   benefits to me--a person who uses desktop and laptop computers,
   tablets, and smartphones?﻿
   Steve Rhodes
   +
   2
   3
   2
   Reply

   First, you're making up myths.
   9 - nobody thinks Glass is banned everywhere (though some may wish it
   was).
   It is currently banned in a few places. There is a list (though not
   complete since it focuses on the Bay Area and Seattle
   http://www.glasshole-free.org
   Though I'm sure more places will be banning glass. So if someone has
   the prescription version, they better hold onto their old glasses or
   wear contacts.
   Don't expect a biker bar or one called Molotov's to trust someone
   turned them off.
   And the $1,500 price tag with no grants and no loaner program for
   journalists was a huge mistake (it is a bit difficult to complain about
   media spreading myths when there is no way for them to try Glass for
   more than a few minutes unless they fork over $1,500 personally or have
   a rare employer who will pay for it).
   Now anyone wearing glass is seen as wearing a very expensive device on
   their face
   Yes, some people who aren't rich saved their pennies, or crowd funded
   it (though that takes a wealth of contacts many who might have a good
   use for Glass don't have), or were given it.
   Though it didn't help that one person who was given Glass reinforced
   many myths about it, was horrible with media, and received more media
   attention than anyone else who uses Glass.
   And it is another prominent symbol of Google when there is a rising
   anger particularly in San Francisco towards Google.
   The many Glass Explorers impressed by Google's attempt at myth busting
   should take off their rose colored glasses (or shale, sky, charcoal,
   tangerine...)
   PS You're welcome to be in denial and think Glass critics are
   neo-Luddites. But there are legitimate criticisms of glass, how google
   has handled glass, and some glass users made by people who use tech
   (this is written on an IPad) and have been using it for a long time
   (the first online forums I posted on were on PLATO when I was in middle
   school).
   And there are people I know using glass who are doing interesting
   things with it, but they aren't being heard from much﻿
   Johnny Connolly
   +
   0
   1
   0
   Reply

   Soon: Myth #1: Glass's batter only lasts 45 minutes.﻿
   iPan Baal
   +
   1
   2
   1
   Reply

   Glass is only the first in a long stream of augmented and virtual
   reality headsets to come.
   So of course they're going to take shit for it - society hasn't
   adjusted to it yet.
   But you will. And then you'll find something else to bitch about.﻿
   koushik yeluri
   +
   0
   1
   0
   Reply

   I'm waiting for the day when i can wear a moto360,glass n carry my
   nexus at same time.﻿
   Steve Wright
   +
   0
   1
   0
   Reply

   It doesn't matter whether an LED is placed on the glasses to let others
   know when they're being recorded -- the LED can't be seen from a
   distance, and people will paint over it so that others aren't aware
   they're being recorded, duh.
   And, of course, these glasses make you look like a weak, effeminat
   limpswisher.  So if you're a weak, effeminate limpswisher, these
   glasses will accentuate your natural personality, and let others know
   that you're easy pickins for a beatdown.﻿
   iPan Baal
   +
   0
   1
   0
   Reply

   +Steve Wright
   O'Doyle rules!﻿
   Maximilian Deubel
   +
   1
   2
   1
   Reply

   sry google, but how should I as a custumer(/upcoming dev) even get to a
   google glass? $1,500 is out of range by far :(﻿
   Jeff Jones
   +
   1
   2
   1
   Reply

   Well folks Glass is here to stay so DEAL!﻿
   Swanky Butters
   +
   0
   1
   0
   Reply

   Glass is Google's Kinect, a piece of tech no one asked for, no one
   wants to pay for and doesn't have a purpose yet.﻿
   Paul Dickinson
   +
   0
   1
   0
   Reply

   Well, thank God that you've cleared that up, now that everyone will see
   it, since it's posted on Google+.﻿
   Jon Webb
   +
   2
   3
   2
   Reply

   Hilarious. Never do this. You cannot debunk "myths" by listing them.
   You look paranoid and clueless. ﻿
   Charlene Buck
   +
   0
   1
   0
   Reply

   Oh, so you're 'explorers'? What new wonders are you 'exploring'? The
   reason Massachusetts recently had to pass a law specifically outlawing
   'upskirt' photos was that technology had gotten ahead of the laws.
   Please be ready for the legal system to 'explore' the various ways the
   wearers of Google Glass will have to be regulated to prevent them from
   infringing on other's rights.﻿
   bozhidar mihaylov
   +
   1
   2
   1
   Reply

   Tell em +Google!
   Few things to say:
   1st. The discussion will rise and help clear moral questions and laws.
   ..the point "will you do the same"!? Is kinda a hint..
   2nd. Face recognition can help you track the online footprint of your
   "face"..
   ..and "Are you recording me" is just a way to say "Hi, what up, what's
   that!?"
   3rd. Simply lifting up the glasses on your head can make others feel
   better.
   4th. Another Glass without camera is not a bad idea.
   5th. Excuse my English : )﻿
   Juan Jorge
   +
   0
   1
   0
   Reply

   +Jon Webb Letting myths and bad press about your upcoming devices
   spread is not a smart thing to do trying to educate people about the
   truth is smart whether they are smart enough to see it is true or not.﻿
   Allen Wren
   +
   2
   3
   2
   Reply

   What snide bullshit. "Have you tried it?" they ask when we assume how
   it works based on what it looks like and what information has gotten
   around publicly. No of fucking course we haven't because not everyone's
   got a grand and a half lying around (or begged, borrowed or stolen or
   whatever.) I, for one, don't even have a cell phone because, hey, I'm
   broke. Have half a heart and a half a brain cell. Glass users are
   already seen as preening technological Illuminati, why compound the
   problem?﻿
   Brian Lockwood
   +
   4
   5
   4
   Reply

   this a design problem, plain and simple make Glass look like some
   regular pair of sun glasses. Don't make the heads up devise so obvious.
   Blend the camera into the frame and balance out the battery so it's
   systemically balanced. The current design Asymmetry makes Glass feel
   dorky and communicates all these myths ﻿
   S. Walker
   +
   2
   3
   2
   Reply

   Without a red LED, non-wearers can't know if you're recording them,
   even for 10 seconds. Hence the S.F. bar fight.
   If you have Glass on prescription lenses, you have no business going
   into a locker room or sauna. The considerate solution when others are
   nude (etc.) is to use a second pair of glasses.﻿
   Katrina Maksimuk
   +
   0
   1
   0
   Reply

   +Tomas Pekarek I did a campaign to raise money just like they said (I
   thought I was the only one). I was lucky that I have people in the
   community who believed in me. #glassexplorer﻿
   Cori Haws
   +
   0
   1
   0
   Reply

   +Matt Weldon Your logic is completely flawed. Like Google has said,
   there are far better devices which can be used to spy on people.  For
   all you know someone could be wearing a hidden camera. You wouldn't
   have a clue and it would do a hell of a better job than glass would
   with it's 10 second recording limit. The chances are no-one is going to
   be interested in recording you and so won't do it, especially with
   Glass. In fact, whenever you go outside you've probably been recorded.
   CCTV dominates our societies these days and you have no choice in the
   matter whether it be in the street, in shops or in restaurants. They
   ALL have surveillance equipment somewhere or another.
   By all means Google should put a red light on the front. But everyone
   else is being ridiculous about the product. The "It's Invading my
   Privacy" band wagon is something that very easy to hop on.﻿
   Zak Pence
   +
   0
   1
   0
   Reply

   People are so desperate to add value and meaning to their lives that
   they will pay (or beg others to pay) for the privilege to be called
   "Explorers". This is testimony to the exploitative marketing genus of
   Google. And, the creation of a polarizing tension between "glassholes"
   and "glasshaters", through the fabrication of negative "myths"....
   great work, Google! That said, I'll take my Glass in charcoal. Thanks!﻿
   Darth Continent
   +
   1
   2
   1
   Reply

   Google Glass is a fad, plain and simple.
   It's an in-between step toward true onboard technology resembling the
   cyberpunk phenomenon, where a HUD might be projected onto someone's
   retina and their brain could manipulate it effortlessly.
   I for one don't invest in in-betweens, but I wait with bated breath for
   the "real" thing, true integration of electronics with the biochemistry
   and bioelectronics of our bodies.
   Will Google deliver?﻿
   Eli Fulton
   +
   0
   1
   0
   Reply

   I fall into the category of the people that can't afford it.﻿
   Mark Daku
   +
   0
   1
   0
   Reply

   Glass has a fundamental problem that can not be overcome. It's a device
   that does not require a human body movement to give away what you are
   about to do.  Let explain by example.
   Examples of body queue's we know instantly what the user is doing.
   The mobile phone as a phone.  place up to the side of the head.
   The mobile phone as a camera or video recorder.  Placed in front of
   body and user looks into screen not the subject matter.
   Blue tooth head set.  Basically a universal sign that the user is a
   douchebag.  Why, There is no body queue that the person has switched to
   conversation over the head set.
   If we look at people in the street with wired head sets we see a common
   usage pattern.  A user will either hold the phone with the wire hanging
   out of it in a visible manor.  OR they will hold the mic piece on the
   cord while talking.  We know what this person is doing.  As this is a
   persistent body posture used through out the usage scenario.  People do
   these things over time because it gives everyone else that social
   queue.  Often there is no need for these body queues people just seem
   to do it.
   Glass does not have this.  Just like bluetooth headsets there is an
   activation body action.  Voice or physical.  (  Voice will have low use
   for related social reasons. ) There just is no body queue that the user
   is performing an interaction of any kind with glass.  If I come around
   a corner and see a glass user I just do not know if they are
   interacting with it.  I will instinctively assume they are.  Why?
   because I have no other indicator to gauge what they are doing.
   The blue light doesn't mean anything.  It's a nice to have thing. But
   by no means is a must have. It will break, be covered, be removed what
   have you by certain people.  No one can doubt this.  Thus as an
   indicator it is next to useless.
   I do foresee people adopting a physical body indicator to reveal they
   are recording.  I think people will start to hold a finger or two to
   the side of glass to socially indicate they are recording.  It will
   evolve from the touch activation and people will simply leave their
   hand there.  In exactly the same way the few bluehead set wearers today
   hold a finger or two to the headset while speaking.
   As long as glass does not have a social queue with it, it will
   struggle.﻿
   Joshuel Patterson
   +
   0
   1
   0
   Reply

   Myth #1 is subjective, although the default "off" state does help the
   argument, which, is why I think they should put that bit at the
   beginning of the paragraph...﻿
   Joshuel Patterson
   +
   0
   1
   0
   Reply

   Dear Google Glass - it would help if your picture was of someone, such
   as the brewmaster who is using it - using it in a practical situation,
   or better yet a collection of images of people using it in practical
   ways.
   Seeing an image of some designer/model chick staring at you with the
   same face you'd see on a porn star probably doesn't help you make your
   case.﻿
   Guriqbal Singh
   +
   0
   1
   0
   Reply

   :)﻿
   Mark Wilson
   +
   0
   1
   0
   Reply

   As wearables flounder, Google struggles to dispel Glass 'myths'
   http://betanews.com/2014/03/22/as-wearables-flounder-google-struggles-t
   o-dispel-glass-myths/﻿
   Mark Creig
   +
   2
   3
   2
   Reply

   Fact 1 - You look like a giant toolbag wearing Glass.﻿
   James Taylor
   +
   0
   1
   0
   Reply

   Nobody would use an obvious thing like a camera on a cellphone to
   record you or shoot pictures up your skirt. Oh, wait...
   It isn't the 80% under the bell-curve you need to worry about...﻿
   Selop masa
   +
   0
   1
   0
   Reply

   I'm waiting for the day it will be possible to purchase them in
   israel ﻿
   Jeremiah Johnson
   +
   0
   1
   0
   Reply

   I wasn't even aware they came in prescription. Thought they were
   safety-goggles (safety-googles?) with AR capability. Good to know,
   though, if I could ever afford one, after it hits market.﻿
   Mark Wilson
   +
   0
   1
   0
   Reply

   As wearables flounder, Google struggles to dispel Glass
   'myths': http://betanews.com/2014/03/22/as-wearables-flounder-google-st
   ruggles-to-dispel-glass-myths/﻿
   David Abraham
   +
   0
   1
   0
   Reply

   People look down at phones for a change of scenery. Though shalt not
   demonize the behavior :)﻿
   Andy Seme
   +
   0
   1
   0
   Reply

   I love the google glasses ﻿
   Daniel Benoy
   +
   0
   1
   0
   Reply

   This article seems to be sending the message that software which goes
   on the Glass will be heavily curated by Google. I guess everything will
   be closed-source and locked down?﻿
   Andy Seme
   +
   0
   1
   0
   Reply

   You are right
   ﻿
   George Krumins
   +
   1
   2
   1
   Reply

   +JennySue Devost
   Don't believe me, fine. Do this instead. Wearing you Google glasses,
   ask your significant other or a close friend "Does me wearing Google
   glasses make me look nerdy?" and also ask them "Does wearing Google
   Glass make me look uncool?" Then report back with their comments.
   The better comment I should of written, and is more to the point was
   written by Swanky Butters: "Glass is Google's Kinect, a piece of tech
   no one asked for, no one wants to pay for and doesn't have a purpose
   yet." The difference is that with the Xbox One the camera and
   microphone are always on, unless of course, you unplug it. However, I
   can't unplug or turn off the camera and microphone on your Google
   glasses. And the difference between a phone camera and Google glasses
   is that the recording with Google Glass is always surreptitious.
   How long has Google Glass been in beta, and will it ever be a
   commercial product? I predict that it will go the way of Google's other
   failed product, the Nexus Q.﻿
   William Cornelius
   +
   0
   1
   0
   Reply

   In a few years this conversation will seem quaint. "Remember back when
   everyone thought Glass was the work of the devil."﻿
   George Krumins
   +
   0
   1
   0
   Reply

   Nice straw man argument. I said nothing of the sort.﻿
   William Cornelius
   +
   0
   1
   0
   Reply

   +George Krumins Do you mean me? I don't see you otherwise replying to
   anyone in particular. If you are referring to my statement, I was not
   taking part in whatever argument you have going on. I have barely read
   any of this thread at all. I was just making a lone statement.﻿
   George Krumins
   +
   0
   1
   0
   Reply

   Sorry, my mistake. I don't think any of the negative comments anyone
   has written said anything of the sort, so it still a straw man
   argument.﻿
   Matt Weldon
   +
   0
   1
   0
   Reply

   +iPan Baal What a crock.  Can you post what your eyeballs are seeing to
   Youtube within an instant for the world to see, including my family,
   friends, and potential employers etc?  No?  Than your argument is
   idiotic, sorry.
   Privacy is a real thing.  Whether or not you personally value yours is
   not a factor in whether or not it exists as a social norm.﻿
   Ravneet Singh
   +
   0
   1
   0
   Reply

   The person in the photo on top of the article looked disabled for a
   second until I realized that she was wearing Google Glass. It's going
   to take some time for people to get used to Google Glass in public. Saw
   a google self driving car the other day. That looked bad ass.﻿
   Bachowny Plamborgs
   +
   0
   1
   0
   Reply

   Ok cool, now let us list the top 10 things that Glass should do but
   doesn't? The reason people are talking about distraction and privacy is
   because the product does nothing else but distract and socialise. Can I
   throw a virtual ball to my friend with Glass? No. So you've missed the
   point of why people are waiting for this technology.﻿
   Tinh Dang
   +
   0
   1
   0
   Reply

   I think it's a better way to capture something, which just happens in a
   blink of an eye. ﻿
   David French
   +
   0
   1
   0
   Reply

   The recording comment (Myth 2) neatly sidesteps the real issue, which
   is that people are uncomfortable that they may be being recorded
   without their knowledge. It's not easy to covertly record with a mobile
   phone or GoPro, as they're pretty obvious. However - unless I'm missing
   something, as a non-Glass user - you don't know if somebody is
   recording you or not. I think this is what brings out the paranoia.﻿
   Onno Vocks
   +
   1
   2
   1
   Reply

   They are not fooling me, just because Google Glass is not set up for
   facial recognition and full time recording and transmission, doesn't
   mean it can't/won't be done at some point. You are not getting into my
   house wearing that thing! I won't be talking to you if you wear that
   thing, period! Anything you say can and will be used against you so
   take it off and shut it off!﻿
   Paweł Komarnicki
   +
   0
   1
   0
   Reply

   Does glass even show that recording is made? Because putting a red
   diode like the cameras do would stop the paranoia — the problem seems
   to be the fact that it could be done, not that it is actually done ;)﻿
   carl turner
   +
   0
   1
   0
   Reply

   I worked for Xybernaut the original wearable computer company....we
   experimented with a variety of head mounted displays, while they may be
   useful for a limited number of applications they just have no practical
   everyday use...its a matter of human physiology...both eyes want to see
   and focus on the same object....so one cannot wear the glass and
   function properly in the real world. Just as people staring at their
   cell screens can't either....no amount of Brin's generous underwriting
   is going to change that quirk of nature. Of course one day we could
   evolve and have independently operating eyes ala chameleons but until
   then take your $1500 and buy a nice Mac....﻿
   Robert Vorthman
   +
   0
   1
   0
   Reply

   +carl turner Just because a computer requires your focus, doesn't mean
   it is useless.  Following your logic, you are suggesting that cell
   phones are useless.  The idea behind Glass is that it is faster to
   access than a phone, which means less of the user's time is shifted
   away from the real world when compared to phone use.﻿
   Beau Ravn
   +
   0
   1
   0
   Reply

   Glass does not need to develop face recognition technology because that
   is already being developed through social media. It only needs to
   integrate with those platforms. It needs to be understood that for
   facial recognition apps to even function, there needs to be a database
   of faces and linked names somewhere for the app to access and compare.
   This library is being built every time you 'tag' a photo on Facebook
   and suchlike. So the basic facial recognition database will already
   exist through integration with Facebook, etc, regardless of whether it
   is included in glass or not. In addition, there are already a number of
   Google Glass 'clones' that are being developed in China, Korea and
   Japan that are eagerly waiting for the official launch so that they can
   also launch their clone products immediately after and at half the
   price. So the longer Google takes to get to a public release product,
   the more time it gives to the cloners to also develop THEIR products.
   Right now, it is highly likely that the Apple iGlass or Sonyview (made
   up names) will take the Google Glass idea to another level and actually
   present a far better product from the outset.﻿
   Jonathan M
   +
   2
   3
   2
   Reply

   You've disputed the "myths" of your choice.  This reads like ten
   straw-man arguments.
   Glass is the idea of Bluetooth earpieces taken to another level.  How
   well have those things been received?    ﻿
   Robin de Villiers
   +
   0
   1
   0
   Reply

   Just disable recording.  Its really straight forward.  Why is google
   creating a public relations nightmare on this issue?
   They are going to kill off the augmented reality concept before it even
   starts.
   Augmented reality is what we want anyway.  That's what is really
   important.  That is the revolution that is about to happen.  We don't
   need videos recordings or images....  ﻿
   carl turner
   +
   0
   1
   0
   Reply

   +Robert Vorthman "while they may be useful for a limited number of
   applications they just have no practical everyday use"--where did I say
   useless? I said they are impractical...if you want to wear one and
   shift your focus to the little display hanging off your right or left
   eye to get information then be my guest...if you are still using it 5
   years from now will be the acid test...﻿
   Alan Sutherland
   +
   0
   1
   0
   Reply

   what about the 'urban legend' that wearing Glass for extended periods
   of time can cause terrible
   headaches? https://plus.google.com/+Scobleizer/posts/1UfNLdZAN4h﻿
   Peter Basch
   +
   0
   1
   0
   Reply

   #2 is the only substantive complaint, but with a twist: the fear isn't
   that Glass isn't recording everything all the time, but that it can be
   turned on surreptitiously, and there's no way for others to tell if
   someone is recording you or just looking at you. If there were a
   bright, blinking red LED, then maybe... but it would be only a matter
   of about a day (tops) until someone hacked that. As for the comparison
   with phones - if someone were walking around pointing their phone
   camera at people, it would be a pretty good guess that they're
   recording. If they're holding it up at an angle, looking at the screen,
   then they're probably not - they're just texting, etc.
   The rest are strawmen (like #9 - nobody thinks it's banned everywhere;
   just some places), and people being judgmental. So, sure, if one of
   your myths is "some say that people wearing Glass are jerks," then the
   reader would likely want to distance themselves from that.﻿
   Peter Basch
   +
   0
   1
   0
   Reply

   BTW, none of the above should be construed as meaning I don't want one.
   A friend was invited to buy a Glass, and called me to ask if he should
   do it (he makes a decent living, but is by no means rich). I asked him
   if he found electronic devices delightful or frustrating. He said they
   tended to be frustrating. So I told him not to bother. A $1500 expense
   should make him totally happy. The only reason I thought he should buy
   one is that he could invite me to buy one, too. He ended up not getting
   one.
   I think it's an amazing device, but I think I would wear it very
   rarely, mostly to play/experiment. I certainly have little desire to
   hit the mall with one. And my wife would mock me mercilessly. But my
   kids would be impressed.﻿
   John Mercil
   +
   1
   2
   1
   Reply

   Glass is really expensive and is not for the average person.﻿
   Matthew Jordan
   +
   1
   2
   1
   Reply

   You've helped create this distracted world of cloying immediacy and
   technology-worship, and now you're positioning Cyborg Face as a
   solution to it? Hilarious.﻿
   David Graf
   +
   2
   3
   2
   Reply

   People who pooh pooh the concept of privacy just don't understand what
   can happen to you when it's been invaded. Of course, I don't expect
   much of techies when it comes to history.﻿
   Emily Shaw
   +
   3
   4
   3
   Reply

    I think Google is seriously miscalculating the primacy of the human
   face in social interactions. If you made a similar device in the form
   of a watch or necklace, you wouldn't have these issues. Once you put
   something on a human face, you start sliding into the uncanny valley
   and freaking everyone out.﻿
   Kayza Kleinman
   +
   0
   1
   0
   Reply

   +Lewis Vail
   It took me about three minutes, if even that, to find this:
   http://www.pbs.org/wgbh/amex/eastman/peopleevents/pande13.html
   I didn't look further, but I have no doubt that if one were to look at
   old newspapers and the like it wouldn't be too hard to find it.﻿
   Shashwat Sinha
   +
   0
   1
   0
   Reply

   Nice post ﻿
   Wendy Hou
   +
   1
   2
   1
   Reply

   Google, number 8 was rotten. You're advising people (most of whom
   aren't beta testers) to beg on the internet or ask for a gift from a
   wealthy friend? What are you saying? For now, Glass IS for the wealthy.
   Even you don't have a dignified solution for it.﻿
   Chris BSomething
   +
   0
   1
   0
   Reply

   Yes these are all myths. Most of them won't remain myths though as
   Glass goes mainstream.﻿
   David Entrikin
   +
   0
   1
   0
   Reply

   Thanks for clearing that up G.﻿
   David Entrikin
   +
   0
   1
   0
   Reply

   I'm ready for it . Need it . Want it .﻿
   Ivan Klimovich
   +
   0
   1
   0
   Reply

   OK Glass. I think that the problem with video recording is also in
   heating of the device. Hope they will fix that.
   And I will buy Glass only to film 24/7﻿
   Michelle Morioka Lewis
   +
   0
   1
   0
   Reply

   I have some limited vision in my right eye.  Wondering if it's still
   possible to use?  Would really like to try this.﻿
   Shannon McCoy
   +
   3
   4
   3
   Reply

   I have found no negative reactions to my GG so far in the last month
   since I got it. I wear it constantly and have found the best way to
   educate people is to simply let them try it on. I have a Samsung gear
   which is a much better way of secretly videoing someone as I don't have
   to be staring at them. So if someone asks if I am recording them I
   would simply show them how the system works then show them the gear I
   am wearing and how if I wanted to record them the GG would be the worst
   option available and a very expensive inefficiency at that. Every time
   I simply let some one and in fact even strangers at stores and waiting
   in line they are blown away and can't wait to see the price come down
   so they can get one too. My killer app is the turn by turn directions.
   I simply have them put it on and ask for directions to whatever address
   they want. As soon as they see it come up they stare in wonderment. I
   think we as Explorers need to be as approachable and open as possible
   to the curious or suspicious so that they can see its just a fancy
   bluetooth headset with so-so camera.
   As for facial rec software I think it is a must especially for a
   product I have been designing for those with Alzheimer's to help them
   recognize people with a simple whisper in their ear. Imagine the
   possibilities to help an elder find their way home or remember where
   they were going or the people they know that GG offers. Yes there are
   limitations and functional and practical hurdles ( before anyone starts
   nay-saying, I have thought of them ), but there are some amazing
   possibilities.
   I am also working on a system for a motorcycle HUD that can give you
   live vehicle information (speed/rpm/gear) so that you don't have to
   take your eyes off the road.  When you share your possibilities with
   others they start thinking of their own uses and  possibilities. If we
   are truly to earn the moniker Explorer then we have a duty to share
   what we discover with those to still think the world is flat. +Google
   Glass keep up the good work.﻿
   Onno Vocks
   +
   0
   1
   0
   Reply

   I disagree entirely, especially on #5. Any good quality recorded
   footage can be used for facial recognition or the facial reader, a new
   technology revealing your emotional state. The facial reader has been
   used on old footage to determine if political leaders were lying during
   an interview, footage that precedes the digital camera. Either way, I
   will not have a conversation with some one wearing Google Glass, or any
   other camera, the footage can be used against you years later, and no
   one I know has perfect memory. The fact that Google Glass is not
   currently set up for facial recognition does not guarantee that it
   won't be in the future. What you do with Google Glass on the street is
   your business, you are not coming on to my property or into my house
   with that thing, period. Same goes for your "smart" phone, leave it in
   the car before you knock on my door. If you think I'm over reacting,
   just ask anyone who has ever been extorted, blackmailed, slandered,
   libeled or subjected to ID theft and you'll get the answer of an expert
   on what can be done with the footage. It's your choice, I think I've
   clearly stated mine.﻿
   Google Glass
   +
   4
   5
   4
   Reply

   +Daniel Kinem Thanks for your concern. You should be able to tell when
   someone is recoding a video or snapping a pic because Glass' display
   will be lit up.
   +Michael Delpach As we mentioned in our post, we're still working on
   making Glass ready for consumer release. Our Explorers have been
   sharing their feedback for the past year to help us improve the product
   for when we launch to the public. We're continuing to better Glass each
   day and we're excited for the future.
   +Alex Bryant We've heard that rumor going around, but it isn't true. We
   expect Glass to cost more than that, but less than $1500.
   +Vishal Khedkar Thanks for being a fan! We're US only for now, but we
   hope to expand in the future. Stay informed
   here: http://www.google.com/glass/start/how-to-get-one
   +Raj Kumar Thanks for your feedback!
   +Maximilian Deubel We're just getting started with Glass and this was
   the right price for this version. We don't have much info about future
   pricing for Glass, but we expect the next one to be less than $1500.
   +Michelle Morioka Lewis This prototype has the display on the
   right-side only. We know this won't work for everyone, but we
   appreciate your feedback and we'll pass it along to our team. ﻿
   Dan K
   +
   0
   1
   0
   Reply

   I'm sure the display comes on for a lot of reasons. Put an LED on when
   it's recording and end the discussion. ﻿
   Keith Barrett
   +
   2
   3
   2
   Reply

   +Daniel Kinem No modern consumer recording device, be it video camera,
   DSLR, or cell phone, comes with a subject facing LED to indicate it's
   recording video. Glass should not be any exception to that. It would
   not end the discussion. ﻿
   Naime Bond
   +
   0
   1
   0
   Reply

   No one wants to walk into a bar or restaurant and see anyone within 500
   feet of them (or their date) wearing these glasses., no matter what you
   say.    Phones do not come anywhere near to evoking the response these
   peepers do.  ﻿
   Thomas Tenkely
   +
   2
   3
   2
   Reply

   +Naime Bond why?
   Because you assume you are being recorded?
   Because you are not, at least not with Glass.
   A. Why would I want to to record you?
   B. If I were going to record you I'd need to be staring right at you
   with the prism glowing... kind of a big indicator.
   You should more concerned with things are far less obvious... and more
   likely to happen.﻿
   Keith Barrett
   +
   3
   4
   3
   Reply

   +Naime Bond Speaking as someone that has been in nearly a hundred bars
   and restaurants wearing Glass, and has never had anything but positive
   responses from people, I can tell you that your belief is wrong, no
   matter what you say. No one but the errant egotistical believe anyone
   wants to record them.﻿
   Dan K
   +
   0
   1
   0
   Reply

   I personally don't care what people do with Glass. But I'm realistic.
   People will always think you are recording them. Admit it and put an
   LED on, or deny it and explain it over and over to pissed off rednecks.
   ﻿
   Keith Barrett
   +
   2
   3
   2
   Reply

   +Daniel Kinem You say that, but your absolute statements defy reality.
   NO ONE out of all the bars, restaurants, and night clubs I've been to
   thought I was recording them. Out of hundreds of people -- not one. And
   no one cared if I did when asked. Some club owners even told me record
   all I wanted to. Where is your real life experience to back up that
   "People will always think" view? That's not realistic; that's fear. My
   real life experience does not confirm that fear.  You likely mean you
   would think that.  No Glass owner wants to kill their batter in 40 mins
   for boring videos of strangers. And the few people that might think
   that way, would likely be that way about anything and an LED would not
   appease them.(BTW - I'd just paint over the LED).﻿
   Miles Smith
   +
   0
   1
   0
   Reply

   $1500. That's the only reason I didn't take up my beta invite. I want a
   device I can LIVE with, not feel like it needs to have it's own
   bodyguard.﻿
   Dan K
   +
   0
   1
   0
   Reply

   +Keith Barrett LOL, you might want to take it up with the Google Glass
   team because that's what the part of the post and many of the comments
   in this thread is about.  Convincing me that it's not a problem doesn't
   matter.﻿
   Thomas Tenkely
   +
   4
   5
   4
   Reply

   +Daniel Kinem its more of a media perception problem than an actual
   issue. I wear Glass around town, bars, concerts resturaunts, parks,
   etc. In actual practice the typical reaction is positive and one of
   curiosity of the tech. ﻿
   Keith Barrett
   +
   0
   1
   0
   Reply

   +Daniel Kinem Well it is a list of myths :-)﻿
   iPan Baal
   +
   3
   4
   3
   Reply

   Ok, here's why (at least one reason) your privacy concerns are simply
   irrelevant:
   http://medicalxpress.com/news/2014-03-reconstruct-facial-images-viewer-
   mind.html
   Researchers reconstruct facial images locked in a viewer's mind
   Using only data from an fMRI scan, researchers led by a Yale University
   undergraduate have accurately reconstructed images of human faces as
   viewed by other people.
   Now, in a couple years, this technology will be miniaturized until it
   is part of your "Google Glass", your "smartphone", or whatever.
   When that happens, it doesn't matter if someone has a device or not.
   Imagine this:
   A 'normal' human (no electronic devices, no cybernetics) walks into
   your home and looks around, including looking at you.
   When that person leaves your home, I scan their brain with the
   micro-fMRI that comes standard on my "Glass" (whatever form that will
   take) and extract an image of your face from their brain.
   See what I'm talking about?
   Everyone who has eyes and a brain possess recording equipment that
   makes your privacy null and void.
   It's an obsolete issue.
   How long before this technology is part of smartphones? Hint: it's not
   going to take very long at all.﻿
   Antonin Petra
   +
   0
   1
   0
   Reply

   Google should definitely make Glass with NO camera. So there would be
   no need to fight half of the myths.
   If you would take out the posts of shared videos/photos made by Glass
   at the +GoogleGlass page there is actually very little of helpful use
   of Glass. Was the first idea to take videos & photos?
   Make the DISPLAY useful to help people. E.g. to read the sheet music or
   other info they need.﻿
   iPan Baal
   +
   0
   1
   0
   Reply

   Google should definitely make Glass with NO camera. So there would be
   no need to fight half of the myths.
   It doesn't matter if Google did this or not.
   If they did, then someone else will come along with a pair that does
   have a camera.
   Don't you people get it yet? You can't stop this.﻿
   Keith Barrett
   +
   2
   3
   2
   Reply

   +Antonin Petra For me the camera is the least used feature, just as on
   my phone. I use Glass to read CNN, respond to my Twitter feed and text
   messages, read urgent email, identifying music, Google searches, and
   for GPS. None of that would produce content you could view in a Google+
   stream so your analysis is flawed.﻿
   Lisa Bld
   +
   0
   1
   0
   Reply

   I don't trust Google any more than I trust the government.﻿
   Antonin Petra
   +
   0
   1
   0
   Reply

   +Keith Barrett Good for you. But look at the +Google Glass page...
   Videos (of "I've been here or there") are flashing all over the place.﻿
   Bryan Foster
   +
   1
   2
   1
   Reply

   That's because the camera is the social element...photos can be
   "shared" on a social network. Many of the uses for Glass as an
   individual aren't sharable. Of course all you see are photos and videos
   on G+.﻿
   Keith Barrett
   +
   3
   4
   3
   Reply

   +Antonin Petra What do you expect? Using the GPS or reading Twitter
   doesn't produce shareable content on Google+. Only photography does.
   It's not an indication that Glass is mostly a camera; it's just that's
   the content that can be shared.﻿
   Jeremy Reger
   +
   1
   2
   1
   Reply

   +Antonin Petra you are in luck.. Google is making glass without the
   camera.. it's called #moto360  ﻿
   Shannon McCoy
   +
   1
   2
   1
   Reply

   OK that's it. We keep the camera but it can only shoot Polaroids that
   print from your forehead every time you take a picture. That will make
   the privacy paranoids happy and the picture people happy and revive a
   dying industry. Disaster avoided. Or maybe we could make IR LED glasses
   that hide your face to all cameras if you don't want to be photographed
   like the Indians that think a picture steals their soul. Or that
   necklace in Total Recall that gives you a totally different face. Get
   on that Google. You can call it Google Ghost!﻿
   Shannon McCoy
   +
   2
   3
   2
   Reply

   +Panos La Name one thing that Google Glass does that I cannot do with
   my Samsung Gear and I will concede you the point. The fact is that with
   the Gear I don't even have to look at you I can just point my wrist at
   you and you look the other way. This is assuming I am stalking you for
   some reason. The reality is that in social situations accessible to
   strangers there is no expectation of privacy. You are confusing privacy
   with anonymity. There is no expectation of privacy when you are in
   public. Kinda in the name... private vs public. ﻿
   S. Walker
   +
   1
   2
   1
   Reply

   Privacy paranoids? Cute post, perhaps, but it doesn't advance the
   discussion and it's dismissive of genuine concerns. Find a way to work
   with others, rather than label and dismiss them.﻿
   James Jansson
   +
   1
   2
   1
   Reply

   "Myth 7 - Glass is the perfect surveillance device
   If a company sought to design a secret spy device, they could do a
   better job than Glass! Let’s be honest: if someone wants to secretly
   record you, there are much, much better cameras out there than one you
   wear conspicuously on your face and that lights up every time you give
   a voice command, or press a button. "
   So, is the light hardwired in when the camera receives power or
   software controlled? I bet it is the latter. So it could potentially be
   off while recording. Talking about recording... glass responds to voice
   commands, meaning the mic is basically always on as well. Hmm...
   maybe the best place to hide is in plain sight.
   This piece was written by someone who either doesn't understand the
   technology, or is ridiculously dismissive considering tech companies'
   involvement with government spy agencies.﻿
   Mike Houlden
   +
   0
   1
   0
   Reply

   well sadly to say that on one hand i do commend those who worked hard
   for google glass,but on the other hand.... I will not purchase anything
   that can possibly pose a threat to privacy (NSA and all).I prefer to
   shut off cams and  possibly any computer period.And all cell phones
   turned off.It is bad enough i work on computers,but to have my life
   interfered with by them? no thank you.﻿
   C Owens
   +
   0
   1
   0
   Reply

   I'm still dubious to some of the myths, but I'd take that gift offer
   and give you a proper review if you like :P﻿
   Keith Barrett
   +
   1
   2
   1
   Reply

   It just means then if you go out in public, you're the one unarmed.﻿
   Wayne Resnick
   +
   0
   1
   0
   Reply

   If you let people have telephones in their homes, they might be able to
   listen to the opera in their bath robes. Society will crumble. What
   menace is this Google Glass? ﻿
   James Jansson
   +
   0
   1
   0
   Reply

   I'm not saying Glass is a bad thing. When it becomes publicly
   available, I probably will get one. But saying "Ha ha you silly
   plebeian! This can't be used for surveillance!" is a denial of the
   issues rather than addressing the reality, and makes me worry about how
   Google deals with privacy and security.﻿
   Keith Barrett
   +
   0
   1
   0
   Reply

   +James Jansson It's not denial - it's really horrible and stupid to
   think of it as a surveillance device. For under $100 I can buy stealth
   eyeglasses or sunglasses capable of hours of video recording at 1080p
   and you have NO CLUE they are even a camera let alone are being used.
   Why in the world would you think a glowing prism on my face with a
   $1500 camera that only works in good lighting 5 feet from you
   personally and dies in under 40 minutes is stealth? It's pure
   irrational fear and ignorance.﻿
   Shannon McCoy
   +
   0
   1
   0
   Reply

   Actually Google we could use a white LED on Glass to use as a head lamp
   or light or flash for low light situations like we can do with a phone.
   The ubiquitous "flashlight app"  That is one thing that is sorely
   missing.﻿
   James Jansson
   +
   0
   1
   0
   Reply

   +Keith Barrett I don't mean that spies will go out and buy it. I mean
   it is a surveillance device just like our phones are surveillance
   devices: our own electronics are being used against us. The recent NSA
   scandal has shown that the NSA is capable of accessing basically all
   data held by US tech companies. Google Glass is constantly connected to
   Google, constantly listening for voice prompts, and the light on almost
   all cameras can be turned off with simple software hacks. This means
   that Google glass is the perfect surveillance device that you choose to
   wear. The government can know where you are, see what you are doing and
   hear what you are talking about. But please, tell me again why I'm
   being 'horrible and stupid' for calling Google out for lying about the
   surveillance capabilities of Google Glass. ﻿
   Wayne Resnick
   +
   0
   1
   0
   Reply

   It's not perfect, considering that there are already glasses that have
   built in cameras, no intelligence, and serve only to record (and
   perhaps correct vision.) And there are hats and helmets and buttons and
   lapel pins that do a better job of streaming high resolution video to a
   concealed device.  There are even pens that do this better.  Why would
   anybody spy on anybody using the most obvious and one of the least
   efficient means? It can't handle continuous HD video and the battery
   would go dead. ﻿
   Wayne Resnick
   +
   0
   1
   0
   Reply

   AAA (yes, the automobile club) just sent me today's deal that lets me
   get "Swaag Brands - Remember the last amazing moment that made you say,
   “I can’t believe I didn’t get that on video!”? Whether you’re a parent,
   daredevil, adventurer, filmmaker, or simply an active believer in
   recording life’s matchless moments, hands-free recording is now
   possible with Today’s Deal from Swaag Brands. Read more..." for $33
   INCLUDING SHIPPING. Of course these are in no way akin to Google Glass.
   All they do is EVERYTHING THAT PEOPLE ARE AFRAID THAT GOOGLE GLASS CAN
   DO and nothing that Glass actually does.  They look like sunglasses.
   They don't look like cameras. They capture 720 video and higher
   resolution stills. And even non-geeks can afford them.  I have no idea
   how well they work and this is not an endorsement, but it points out
   the absurdity of the misdirected paranoia.﻿
   Keith Barrett
   +
   1
   2
   1
   Reply

   +James Jansson If they did that my battery would die in 30 minutes and
   I'd know something was up. Glass is almost always in an off state.﻿
   Jeremy Reger
   +
   2
   3
   2
   Reply

   not to mention +Keith Barrett it would burn your head.. lol the battery
   would get so hot.. ﻿
   Keith Barrett
   +
   1
   2
   1
   Reply

   "ow ow ow. The NSA must be at it again!" :-)﻿
   mr seva
   +
   0
   1
   0
   Reply

   so far my biggest issues with Glass is the apparent lack of access for
   a developer to reach directly to core services. (i could be completely
   wrong). for example, the microphone isn't bad, but their processing is
   terrible. Google is a magnificently complex data system, but sometimes
   ya just can't do it all yourself.  i have lengthy experience in
   improving audio quality in very small systems and Google simply replied
   "we are working on that". what they should do is hire an expert or open
   the dev access to direct outputs of all sensors.  otherwise they'll
   make the same mistake Sony makes repeatedly (proprietary processes)
   instead of the successes Apple makes repeatedly (closed system with
   deep access for dev).  (disclaimer: apple also fracks up their own
   audio too and doesn't allow dev to touch direct microphone outputs).
    yes i'm talking only about sound here, but everyone fusses so much
   about video yet will accept abhorrent sound (SiriusXM, trying to use a
   laptop for a presentation, nearly any mp3 ever created, cheap Walgreens
   earbuds...).      it's not only the microphone, but the speaker itself
   built into the frames is so very poorly implemented when so much is
   known about bone conduction of audio (they didn't even use it).  it is
   kinda like an iPhone without an App store, and that's going to be the
   killer of the project instead of the killer app.   the voice-command
   and audio quality are paramount and Google seems to be rationalizing
   instead of coming to Jesus on this.   integration of Spritz would be
   obvious but haven't seen it yet. ﻿
   Robert Vorthman
   +
   0
   1
   0
   Reply

   +mr seva A developer implemented Spritz on Glass here:
   https://github.com/Aenterhy/SpritzGlass﻿
   Keith Barrett
   +
   0
   1
   0
   Reply

   It's Android Linux. You have access to anything. Don't depend on an SDK
   for it.﻿
   mr seva
   +
   0
   1
   0
   Reply

   robert, thanks. keith, thanks.﻿
   mr seva
   +
   0
   1
   0
   Reply

   +Wayne Resnick one of the things we use in pro audio is "pre-record"
   functions which buffer recording. when you press Record, then the
   buffer dumps and live media continues. so if you see/hear an event,
   press record within the pre-record time and you didn't miss it.   this
   will be the way of future consumer media acquisition tools.  price is a
   little heavy at the moment (for video, audio is ok). ﻿
   Jake Livits
   +
   0
   1
   0
   Reply

   Does Google glass have a full capability of a computer and a phone?
   Can it run programs that have data feed?﻿
   anyway yang
   +
   0
   1
   0
   Reply

   好夢幻的3C裝備，好想要擁有…﻿
   Translate
   Wayne Resnick
   +
   0
   1
   0
   Reply

   I think it's not so much a question of how it compares to a computer,
   but with respect to this thread it's a matter of whether people's
   expectations are off base. Considering that there are very cheap
   unobtrusive video cameras that do a far better job of "invading
   people's privacy" than a blatantly visible and attention grabbing
   device that lacks the battery power for long term recording in public,
   I think it's safe to say that anybody who really wanted to make such
   recordings would either wear glasses that are unobtrusive with video
   recording capability  or perhaps have a backpack or purse with lenses
   smaller and less obvious than a button that can do it for far longer
   and from many angles for much less money.
   As for the capabilities of phones, when they first came out they were
   considered scarier than Google glasses. They could let teenagers have
   inappropriate conversations. They could even allow people to listen to
   the opera in their own homes while attired in a bathrobe, which would
   be completely inappropriate. These days, we have "smartphones," which
   are called by that misnomer based on historical accident, although they
   are more properly PDAs that have an added  feature of being able to
   make phone calls. ﻿
   El Long
   +
   0
   1
   0
   Reply

   While this article tries to compare Google glasses to a cellphone, it's
   completely different.  With a cellphone you know you are being recorded
   when someone aims it at your direction, with this it's always aimed
   directly at people so you don't know when you're being recorded.  So
   basically with a cellphone you know when someone is trying to record
   you and with this you won't know.  In one of my classes there was a kid
   that pointed his phone towards me and I knew he was trying to record
   me, whereas, if he used Google glasses I would have no idea whether or
   not he was trying to record or take my picture.  I never used this
   device to know if it has a light to show it's recording, but it doesn't
   take a smart person to figure out how to bypass that.
   These types of technologies just forces introverted people to be more
   reclusive.  (Sure I know I'm going to somehow have tons of self
   anointed introverts claiming it doesn't bother them and they want the
   glasses, but not everyone likes being recorded or video taped without
   permission).    I don't have anything to hide in terms of being a
   criminal, but I don't want to be recorded by people or uploaded onto
   the internet.  Sure some of you guys will have etiquette and not record
   people behind there backs, but not every person is the same and this
   will just be a technology that will be abused to harass people.  Right
   now as the article states it records for 10 seconds and the record time
   could be changed as well as it can't record 24/7, but this technology
   is just a catalyst for other similar types of devices.  Given time
   there will be one that records 24/7, which leads me to ask - what's the
   point in recording 24/7?  Is it to catch people's embarrassing moments
   and try to get a viral hit on Youtube?  That's what I believe most
   people would buy this for because for people that just want to record
   24/7 for their own personal reasons it will take the same amount of
   time reviewing what they recorded; however, for those looking for just
   a viral hit, they will just speed through the recordings to find the
   embarrassing moment and upload it on Youtube.  Some people that
   secretly record also instigate stuff for these reactions as well.  Look
   at Youtube trolling videos it's a prime example of this.
   If people want these kinds of devices there needs to be better laws in
   terms of recording people and uploading stuff on the web and I would
   have no problems with it.  Current laws make it where people can record
   in the public whoever they want and I believe people can upload those
   recordings as long as they don't monetize the videos and that's pretty
   similar to bullying those who do not want to be recorded and uploaded
   on the web.  I am also speaking from experience of people recording me
   without my permission just because they know I don't like being
   recorded and I have no idea what they do with the footage.﻿
   Wayne Resnick
   +
   0
   1
   0
   Reply

   The problem with that argument is that people would have to stay away
   from anybody wearing glasses if they wanted to be safe. Indeed they
   would need to stay away from anybody wearing clothing or carrying
   anything.  If anything, Google glass makes it obvious that there's a
   possibility of being recorded while hidden devices, including those in
   other glasses,  give no clue.﻿
   El Long
   +
   0
   1
   0
   Reply

   My point is there needs to be better laws about recording people in
   public as well as uploading things on the internet.  I am aware of
   other devices and secretly recording, which I mentioned in my post
   about trolling videos where people have hidden cameras and instigate
   stuff with people just to get reactions for their videos.  With the
   rise of technology and companies such as this trying to make these
   types of devices even more mainstream, there needs to be better laws to
   protect people who do not want to be recorded or placed on the
   internet.  Even though some people don't mind being recorded and
   welcome the fame from being in a viral hit, others don't want to be
   filmed or portrayed as an idiot in the media.  I also know that people
   are trying to promote the benefits of Google glass such as being able
   to record stuff for their own memories or have a fast way to record an
   event that happens instantly, but not everyone thinks like that - just
   as it has those benefits it has negatives just as with other hidden
   recording devices.  What this product does is push recording devices
   into the limelight.  Yeah there are etiquette people talk about, but
   not everyone follows it and it's not enforced.
   Here's a real example of how technology is being abused without proper
   laws and regulations in place.  In colleges/universities there are
   professors do not want students recording their lectures, but people
   still do it.  They put their cellphones on their desks or hide it in
   their bags and record audio.  As a student who knows I'm being recorded
   I don't participate at all because I don't want my voice recorded or
   give the wrong answer and be subject to ridicule by the teacher while
   it's all on tape.  So how does this relate to Google glass?  Students
   might start bringing these things into lectures and just recording
   everything or claiming they aren't recording, but actually are.  It's
   just going to be abused just as how cellphones are.  You can't exactly
   trust someone that has a camera pointed directly at you who claims they
   aren't recording you.  What about bathroom instances?  There's
   etiquette about that, but it's not enforced as well.  If someone has
   their cellphone out in the bathroom people are cautious of that person
   if it's pointed towards them, but having Google glasses on means
   there's a camera in a pretty good spot and you have no idea if they are
   recording.  It's just sickening and makes people like me feel disgusted
   by those who abuse technology that way.  Also, for bathroom situations,
   unless you frequent x rated sites you won't know where that footage is
   - whether it's for their personal storage or uploaded on those x rated
   sites so it's not like you have have the video pulled down unless you
   are aware of it.
   The only solution to this is regulation and laws that impose hefty
   fines against people who do this stuff and recording people in public
   should be regulated as well.  If this is what Google glass's aim was -
   for better privacy and recording laws/regulations - I'm all for it.﻿
   Ellin Beltz
   +
   0
   1
   0
   Reply

   Nice try, but ...
   Reality bites.﻿
   kumar setu
   +
   0
   1
   0
   Reply

   Well written. Cleared lots of myths around Google glass.﻿
   Robert Harsh
   +
   0
   1
   0
   Reply

   I like most Google stuff, especially Chrome OS, but this is the most
   retarded product ever.  People should be beaten up on site for wearing
   these faggy looking things.  Phones with cameras are one thing, but
   looking like a hipster attending Fag by Fag West is not going to turn
   the unwashed masses into users.  Try walking into a bar, movie theater,
   or strip club and see how it takes to get thrown out, your ass beat,
   both or worse. ﻿
   Claude Albertario
   +
   0
   1
   0
   Reply

   It's beyond stupid to think that Glassholes looking to their upper
   right visual field will be any less unaware of their field of view. You
   do know that the eyeballs move conjugally yes? The right is up, the
   left eye is up. I will never speak to anyone showing me a phone, or
   wearing these moronic things. I do not care what bullshit you spew.
   Just like people do not like having regular cameras pointed at them,
   and here we are 150 years from its invention and still....so wait that
   long before the "norms" of society shake out on this stupid
   "technology."﻿
   Robert Harsh
   +
   0
   1
   0
   Reply

   +Claude Albertario I hope the Glassholes field of view isn't obstructed
   by a fist plowing into their face.  I just want to see more videos of
   these faggot getting beat up while wearing their faggy face PCs.  Good
   day.﻿
   Vern Schwanke
   +
   0
   1
   0
   Reply

   This could evolve into a great device for people that are very hard of
   hearing or deaf.    Also for macular degeneration (MD) were you have
   side vision but may not have any center vision.  MD application can
   spread picture to edges.  MD with limited center vision have wavy
   distortion of picture, an application may be able to correct that
   distortion.  The application would allow the user to compensate for the
   waviness and this correction could give the doctor better understanding
   of the patient's problems. ﻿
   Robert Harsh
   +
   0
   1
   0
   Reply

   +Vern Schwanke You know...you raise good points.  But who is using it
   now?  A bunch of Fag by Fag West fudge packing Gen Y Millennial loser
   trash that votes Democrat.  Google needs to direct to your ideas then I
   think glass might be a good idea.  But until then, I hope to see people
   getting beaten up while wearing them.  Not often you get a first-person
   perspective in a fag beat down.﻿
   IUse TheForce
   +
   0
   1
   0
   Reply

   Thanks Google Glass Team Trolls.  I will NEVER use this device.  I am
   as techy as they come.  Nothing on my body will ever be computed.  The
   divide between robots (sheep) and awakened people will soon come to
   fruition.  It will be evident by the dead-stares of the zapped
   population.  (a lot already live in this limitation).   Technology
   won't stop, but if you stop using crap like this, it will alter to a
   more complimentary form.﻿
   IUse TheForce
   +
   0
   1
   0
   Reply

   +Vern Schwanke :  What does democrat have to do with anything?  The
   fact that you say that makes me feel that you haven't woken up yet.
   There is no two party system.  They are one in the same.  What is
   spoken from each is never acted out.  Words mean nothing.  If they did,
   then the word "conservative, aka republican" would have resulted in a
   17 trillion dollar surplus, not a war-ridden 17 trillion dollar
   deficit.  Look at the facts and not the "pretend" ideologies.  If you
   want to survive in this new world, one must rise their head above the
   "bullshit".  You need a better bullshit meter.  I don't want to start a
   debate, because all politicians are the same color of evil.﻿
   IUse TheForce
   +
   1
   2
   1
   Reply

   Privacy.... I'm a realist.  If you walk up to me and think you are
   going to film the world around me non-stop... we're gonna have
   problems.  I will ask you to take it off, and if you decline, I will
   take them off you and smash them on the ground in front of you.  You
   don't like it?  Don't violate my privacy and do what I requested.
   This is my personal space, not yours.﻿
   Robert Harsh
   +
   0
   1
   0
   Reply

   +IUse TheForce I agree and that is the problem.  These glasshole losers
   seem to think they are going to be recording everything in a new
   "privacy free" society.  And then what happens to people that wear real
   vision correction glasses when these things evolve to look like
   Glasshole Wear?
   This idea is fucking stupid, hands down.  If this were a concept that
   help blind people see then I would be all for it.  But these Fag by Fag
   West hipster devices are junk and have no legit value.﻿
   Wayne Resnick
   +
   0
   1
   0
   Reply

   +IUse TheForce so recording somebody in a public place is not
   acceptable, even if legal,  but destroying private property is, even
   though it's a criminal offense and most likely would constitute
   assault?﻿
   Michel LAUDET
   +
   0
   1
   0
   Reply

   Waiting for them
   ﻿
   Brian Morse
   +
   0
   1
   0
   Reply

   Mr. Harsh has serious issues and may benefit from counseling. I suspect
   he has not only a tiny brain, but also a tiny penis. Rob should connect
   with Mr. Sterling and see what other stupid ass stuff they can conjur
   up. What a frickin dick-head.﻿
   IUse TheForce
   +
   0
   1
   0
   Reply

   +Wayne Resnick Recording people in a public place is not legal
   (technically)... But most people don't press charges.  If you ever
   watch the morning news, you'll see people from the waist down when the
   show a shot of people walking in the city.   The reason for that is
   that you can't video people in public places without their consent.  So
   I guess what it comes down to... is.... are people really violating
   other people's rights?  YES.  Why?  Because people feel funny when they
   are filmed.  That is violating their rights via common law.  Sure...
   Smacking the glasses off of Sheldon in the park is a bad idea.  But it
   really isn't different.  It's all a form of violation of another's
   space and privacy.
   Above all... These DORKS (I mean that) should go play outside more.
   "Get away from the glass"  it's exactly that... blocking the real world
   through a screen/filter/obstruction.  ﻿
   Robert Harsh
   +
   0
   1
   0
   Reply

   +Brian Morse I need counseling?  I am not the one walking around with
   some retarded glasses on my face, looking like a corporate tool
   douchebag.  Anyone who does DESERVES to be beaten up!﻿
   Brian Morse
   +
   0
   1
   0
   Reply

   It is odd that some choose to focus on having their photos taken, or
   being recorded without knowledge or permission. What I seem to not yet
   understand is the REASON I or any other Glass user would WANT to
   randomly photograph or record people. What would I do with a picture of
   Mr Harsh? Why would I want to do that, even though I could? Strange
   that some are stuck on that aspect of the technology. Go figure.﻿
   Brian Morse
   +
   0
   1
   0
   Reply

   Building off of The Force guys comments...I have noticed that the
   majority of adults at a typical kids sporting event, like a soccer game
   as an example, are not even looking up at the field...even though they
   are outside and most not wearing Glass.
   They typically are catching up on email, some may be occasionally
   looking at the game through the screen on their phones. I have found I
   can enjoy the world in front of me, wink a picture if something strikes
   my fancy, capture a short video, and even delete an email or two from
   my in-box....all while at least appearing to my kid I am paying
   attention. I really am paying attention, and more so than most of the
   others around me potentially pounding out insults of ignorance on a
   website.
   It baffles me how simply owning a product like Glass puts one into such
   a despiteful category to some, while if they looked in the mirror (some
   call it a Looking Glass) they may find they fall into a potentially
   less than positive catagory, at least as defined by some.
   I wonder if the Force guy is outside when he is pounding out his
   insults of others not being outside. But hey guys...Freedom to express
   ones opinion is a big deal, and even you guys are afforded that. Rock
   on.﻿
   Nikhil Vootkur
   +
   0
   1
   0
   Reply

   what does xe mean﻿
   Tristan B.
   +
   0
   1
   0
   Reply

   If one of these falls into my lap. I would probably make really silly
   things like a health and ammo display. Honestly this tech is incredible
   .... Niche to say the least. I feel the same way about smart watches.
   Though maybe in ten years I'll feel differently. Interesting idea to
   get to Tech War style tech... But then again we kinda skipped the whole
   video phone stage....
   ﻿
   Deniz Akşimşek
   +
   0
   1
   0
   Reply

   +Nikhil Vootkur Explorer Edition ﻿
   John Loya
   +
   0
   1
   0
   Reply

   These are a great way to record work production +John Loya ﻿
   Add a comment...

   Start a hangout
