   #publisher next The Atlantic Best of The Atlantic Technology Channel
   Alexis C. Madrigal's Feed




   Continue to TheAtlantic.com [arrow.png]
   Advertisement

The Atlantic

   Subscribe Now
   [medium.jpg?nc2mvq]
   [shop_JUL09_2014_cards.jpg] [shop_JUL09_2014_Mtee.jpg]
   [shop_JUL09_2014_mugs.jpg] [shop_JUL09_2014_Wtee.jpg]
   ____________________ (BUTTON)
   Get The Atlantic on Facebook
     * Politics
          + Top Stories
          + The Supreme Court Is Looking Out for the Rights of the
            Majority
          + Eric Holder's Legacy as Attorney General
          + The Little Rock 9: How Far Has the Country Come?
          + The Mystery Candidate Shaking Up Kansas Politics
          + How Politics Breaks Our Brains
          + Books for the Horde: The New Jim Crow, Chapters 2 and 3
          + Sponsor Content The Brooklyn Navy Yard Is Creating a New Model
            for Urban Revitalization
            [adServer.bs?cn=tf&c=19&mc=imp&pli=11099584&PluID=0&ord=%%CACH
            EBUSTER%%&rtu=-1]
          + Sponsor Content Hologic Enables Better Outcomes for Patients
          + Sponsor Content Solazyme Is Producing a New Source of
            Renewables
          + Sponsor Content MRC Global: A Leading Supplier to the Energy
            Industry
          + Sponsor Content How Titan International Is Creating American
            Manufacturing Jobs
     * Business
          + Top Stories
          + Saving Paris's Oldest Bookstore
          + Christmas Ads Already?! Actually, Most People Don't Seem to
            Mind
          + Is Bike Sharing Just for Gentrifiers?
          + Peter Thiel's Zero to One Might Be the Best Business Book I've
            Read
          + "Kleenex Is a Registered Trademark" (And Other Desperate
            Appeals)
          + America, the Plannable: How Banks Affect Family Size
          + Sponsor Content The Extinction of Spectator Sports
          + Sponsor Content The Search for the Next Yellow Line
          + Sponsor Content How Apps Might Change Your Swing
          + Sponsor Content Protecting the World's Most Valuable Human
            Real Estate
          + Sponsor Content Blood, Sweat and Data
     * Tech
          + Top Stories
          + Beyond GMOs: The Rise of Synthetic Biology
          + The Woman With the Bionic Eye
          + How to Stop a Rumor Online (Before the Rumor Becomes a Lie)
          + When Everything Works Like Your Cell Phone
          + Ello Says You're Not a Product, But You Are
          + Peering Ever Deeper Into Matter
          + Sponsor Content The Art and Science of Our Senses
            [B8161992.110556643;sz=1x1;ord=%n]
          + Sponsor Content Solving for Sound
     * Entertainment
          + Top Stories
          + The Equalizer: The Ultimate Denzel Washington Role
          + Did Clayton Kershaw Just Have the Best Summer in Baseball
            History?
          + 30 Years of Coens: True Grit
          + "Can a TV Show Save Lives?"
          + Lost, Bill Simmons, and Denzel: The Week in Pop-Culture
            Writing
          + Dave Matthews Band, Happy Rebels
     * Health
          + Top Stories
          + How to Test a Couch for Toxins
          + Toward an Effective Tuberculosis Vaccine
          + The World War II Campaign to Bring Organ Meats to the Dinner
            Table
          + The Health Effects of Leaving Religion
          + France's Troubled Romance With Beef
          + How Exercise Could Erode Teeth
     * Education
          + Top Stories
          + B.J. Novak Proves That Kids' Books Don't Need Pictures
          + How to Make Teachers More Like Doctors
          + Why Girls Tend to Get Better Grades Than Boys Do
          + The Little Rock Nine: How Far Has the Country Come?
          + Where Girls Get Kidnapped on Their Way to School
          + What Do You Wish You Had Learned in College?
          + Sponsor Content The Solution to the US Skills Gap Isn't What
            You Think
          + Sponsor Content This is the Future of Your Commute
          + Sponsor Content How Smart Grids Could Transform the Developing
            World
     * Sexes
          + Top Stories
          + Where Girls Get Kidnapped on Their Way to School
          + Pop Culture's Transgender Moment: Why Online TV Is Leading the
            Way
          + The Economic Case for Paternity Leave
          + When Bosses Discriminate Against Pregnant Women
          + Will "Cisgender" Survive?
          + No, Hope Solo Is Not "Like" Ray Rice
     * National
          + Top Stories
          + The “Other” America
          + Kosher Meets Hipster
          + When Philosophy Becomes Therapy
          + The Health Effects of Leaving Religion
          + Cop Asks for Man's License, Shoots Him When He Reaches for It
          + Saving Wukchumni
          + Sponsor Content Cities Need Small Business Growth Strategies
            [B8212757.15;dc_trk_aid=284503546;dc_trk_cid=59471219;ord=%%CA
            CHEBUSTER%%]
     * Global
          + Top Stories
          + Songdo, South Korea: City of the Future?
          + France's Troubled Romance With Beef
          + Why Is the U.S. Yielding to Iran Now?
          + Saving Paris's Oldest Bookstore
          + Dismantling Empires Through Devolution
          + China's Other Food-Safety Problem
     * Video
          + Top Stories
          + Famous Movies Recreated With Stock Footage
          + What Is a City?
          + The Flight of a Moth, In Extreme Slow Motion
          + What Do You Wish You Had Learned in College?
          + Saving Wukchumni
          + CrossFit Versus Yoga: Choose a Side
     * Magazine
          + In This Month's Issue
          + What Happens When We All Live to 100?
          + Why I Hope to Die at 75
          + How Gangs Took Over Prisons
          + [medium.jpg?nc2mvq]
               o Subscribe
               o Renew
               o Give a Gift
               o Digital Editions

     * Subscribe
     * Events
     * Newsletters
     * Books
     * Apps
     * Features
     * In Focus
     * Just In
       The Health Effects of Leaving Religion

     * [skybox-thumb.jpg?ncif2m]

The Supreme Court: Looking Out for the Majority
       By Garrett Epps
     * [skybox-thumb.jpg?ncif2m]

30 Years of Coens: True Grit
       By Christopher Orr
     * [skybox-thumb.jpg?ncif2r]

Dismantling Empires With Devolution
       By Parag Khanna
     * [] Sponsor Content The Search for the Next Yellow Line
     * [] Sponsor Content How Apps Might Change Your Swing
     * [] Sponsor Content Protecting the World's Most Valuable Human Real
       Estate
     * [skybox-thumb.jpg?ncj3ob] Sponsor Content Blood, Sweat and Data
     * [skybox-thumb.jpg?ncj41i] Sponsor Content The Extinction of
       Spectator Sports

In Defense of Google Flu Trends

   If the system failed, it did so only in the outsize dreams of Big Data
   acolytes.
   Alexis C. Madrigal Mar 27 2014, 10:27 AM ET
   Tweet
   More
   Email
   Print
   [lead.jpg?n345cz]
   Shutterstock/Giovanni Cancemi

   In 2008, Google released an experiment called Flu Trends, which
   attempted to predict the prevalence of the flu from searches that users
   made for about 40 flu-related queries.

   Based on the data up to that point in time, Flu Trends worked really
   well. The Centers for Disease Control, which had been involved in
   shaping how it functioned, liked the data that it produced.
   Even the reliable pro-nerd hangout Slashdot headlined their thread
   'Google Flu Trends Suggests Limits of Crowdsourcing.'

   "We really are excited about the future of using different
   technologies, including technology like this, in trying to figure out
   if there's better ways to do surveillance for outbreaks of influenza or
   any other diseases in the United States," Joseph Bresee, the chief of
   the epidemiology and prevention branch in the CDC's influenza division,
   said at the time.

   And so, aside from some misplaced nagging about privacy, the new tool
   was celebrated in the news media. All the big outlets covered it: CNN,
   The New York Times, the Wall Street Journal, and many, many more.

   Flu Trends fit the golden image of Google, circa 2008: a company that
   did gee-whiz things just because they were good ideas.

   This was the era of Google.org, formed under a guy named Larry
   Brilliant, who said things like, "I envision a kid (in Africa) getting
   online and finding that there is an outbreak of cholera down the
   street. I envision someone in Cambodia finding out that there is
   leprosy across the street." As the global economy collapsed, Google
   gleamed among the ruins.

   This was all years before people started even talking about "big data."



   But times have changed. Now, data talk is everywhere, and people are
   more worried than excited. The NSA looms over every tech discussion.
     __________________________________________________________________

   Innovation Week

An Atlantic Special Report
Read More
     __________________________________________________________________

   And Google no longer seems so different from other companies. As Bill
   Gates put it in an interview with Bloomberg BusinessWeek, "Google
   started out saying they were going to do a broad set of things. They
   hired Larry Brilliant, and they got fantastic publicity. And then they
   shut it all down. Now they’re just doing their core thing." Larry
   Brilliant left in 2009. Google.org redirects to Google.com/giving/.

   Which brings us back to Google Flu Trends. If you've been watching the
   headlines this month, you've probably seen that a study published in
   the journal Science took Flu Trends to task for "big data hubris." A
   team led by Northeastern political scientist David Lazer found that Flu
   Trends has been missing high, including "100 out of 108 weeks starting
   with August 2011." They pointed to problems with the opacity of
   Google's method and the inconsistency of the Google search user
   interface and algorithms. The paper was titled, "The Parable of Google
   Flu: Traps in Big Data Analysis."

   And the response to it in the media was swift and rough. Here is a list
   of just a few of the headlines that followed Lazer's methodological
   fisking:

   Google Flu Trends Gets It Wrong Three Years Running
   Why Google Flu Is a Failure
   A Case of Good Data Gone Bad
   Data Fail! How Google Flu Trends Fell Way Short
   Google Flu Trends Failure Shows Drawbacks of Big Data

   Even the reliable pro-nerd hangout Slashdot headlined their thread on
   the story, "Google Flu Trends Suggests Limits of Crowdsourcing."

   A skim of the headlines and most of the stories would lead you to
   believe that Google Flu Trends had gone horribly wrong. Here, this
   thing was nominally supposed to predict future CDC reports—and it
   wasn't even as good as simple extrapolations from past CDC reports.

   How you like them apples, Google/Big Data!

   But lurking in the Lazer paper was an interesting fact about the Google
   Flu Trends data: when you combined it with the CDC's standard
   monitoring, you actually got a better result than either could provide
   alone. "Greater value can be obtained by combining GFT with other
   near–real time health data," Lazer wrote. "For example, by
   combining GFT and lagged CDC data."

   If that was true, and the CDC was aware of it, couldn't they simply
   combine the data on their own and have a better epidemiological
   understanding of the country? And if that was true, wasn't Flu Trends a
   success, at least according to the standards laid out in the
   Nature paper describing it in 2009?
   If GFT failed, it did so, more than anywhere else, in the popular
   imagination—and in the wishes of Big Data acolytes.

   "The system is not designed to be a replacement for traditional
   surveillance networks or supplant the need for laboratory-based
   diagnoses or surveillance," Google and CDC authors wrote. They
   continued, "As with other syndromic surveillance systems, the data are
   most useful as a means to spur further investigation and collection of
   direct measures of disease activity."

   In other words, Google Flu Trends is not a magical tool that replaces
   the CDC with an algorithm. But, then, the people who built it never
   imagined that it was. If it failed, it did so, more than anywhere else,
   in the popular imagination—and in the wishes of superficial Big Data
   acolytes.
     * 1
     * 2
     * > >
     * Single Page

   Jump to comments
   Tweet

   IFRAME:
   http://www.reddit.com/static/button/button2.html?width=51&url=http%3A%2
   F%2Fwww.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F03%2Fin-defense
   -of-google-flu-trends%2F359688%2F

     * Email
     * Print

   Presented by
   [author-headshot.jpg?m8tdem]

Alexis C. Madrigal

   Alexis Madrigal is the deputy editor of TheAtlantic.com. He's the
   author of Powering the Dream: The History and Promise of Green
   Technology. More

   The New York Observer has called Madrigal "for all intents and
   purposes, the perfect modern reporter." He co-founded Longshot
   magazine, a high-speed media experiment that garnered attention from
   The New York Times, The Wall Street Journal, and the BBC. While at
   Wired.com, he built Wired Science into one of the most popular blogs in
   the world. The site was nominated for best magazine blog by the MPA and
   best science website in the 2009 Webby Awards. He also co-founded Haiti
   ReWired, a groundbreaking community dedicated to the discussion of
   technology, infrastructure, and the future of Haiti.
   He's spoken at Stanford, CalTech, Berkeley, SXSW, E3, and the National
   Renewable Energy Laboratory, and his writing was anthologized in Best
   Technology Writing 2010 (Yale University Press).
   Madrigal is a visiting scholar at the University of California at
   Berkeley's Office for the History of Science and Technology. Born in
   Mexico City, he grew up in the exurbs north of Portland, Oregon, and
   now lives in Oakland.
     * All Posts
     * RSS
     * Email
     * Follow @alexismadrigal

   [ebook-banner-zen.jpg] [TAL_WWI_Layout1.gif]
   Try 2 Free Issues! Go
     * Subscribe
     * Renew
     * Give a Gift
     * Digital Edition

   Get Today's Top Stories in Your Inbox (preview)
   Email Address ____________________ [X] Sign Up
     * How to Stop a Rumor on the Internet
       Megan Garber Sep 26, 2014
     * Dismantling Empires Through Devolution
       Parag Khanna Sep 26, 2014
     * Peering Ever Deeper Into Matter
       Sarah Laskow Sep 26, 2014
     * Shaking Up Kansas' Politics
       Molly Ball Sep 27, 2014

Video

   More video
   [video-featured.png?nciosb]

Famous Movies Recreated With Stock Footage

   From Apocalypse Now to The Lord of the Rings, this clever video puts a
   new spin on Hollywood's greatest hits.
     * Share on Facebook
     * Tweet
     *

   [home-article-curation-405x234.jpg?ncmvsw]

When Everything Works Like Your Cell Phone

   [home-article-curation-405x234.png?ncmvsw]

The Woman With the Bionic Eye

   [home-article-curation-405x234.jpg?ncmvsw]

Pop Culture's Transgender Moment

   [home-article-curation-405x234.jpg?ncmvsw]

The Economic Case for Paternity Leave

   ‹ ›
     __________________________________________________________________

Join the Discussion

   After you comment, click Post. If you’re not already logged in you will
   be asked to log in or register. Please enable JavaScript to view the
   comments powered by Disqus. blog comments powered by Disqus
   Close

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

What Do You Wish You Learned in College?

   Ivy League academics reveal their undergrad regrets

Video

   [play-button.png] [curation-special-report-thumb.png?nciy7c]

Famous Movies, Reimagined

   From Apocalypse Now to The Lord of the Rings, this clever video puts a
   new spin on Hollywood's greatest hits.

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

What Is a City?

   Cities are like nothing else on Earth.

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

CrossFit Versus Yoga: Choose a Side

   How a workout becomes a social identity

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

In Online Dating, Everyone's a Little Bit Racist

   The co-founder of OKCupid shares findings from his analysis of millions
   of users' data.

Writers

   Up
     * Julie Beck
       How Exercise Could Erode Teeth Sep 27, 2014
     * Molly Ball
       The Mystery Candidate Shaking Up Kansas Politics Sep 27, 2014
     * Megan Garber
       How to Stop a Rumor Online (Before the Rumor Becomes a Lie) Sep 26,
       2014
     * David Frum
       Why Is the U.S. Yielding to Iran Now? Sep 26, 2014
     * Joe Pinsker
       Christmas Ads Already?! Actually, Most People Don't Seem to Mind
       Sep 26, 2014
     * Chris Heller
       Famous Movies Recreated With Stock Footage Sep 26, 2014
     * Derek Thompson
       Did Clayton Kershaw Just Have the Best Summer in Baseball History?
       Sep 26, 2014
     * Conor Friedersdorf
       Cop Asks for Man's License, Shoots Him When He Reaches for It Sep
       26, 2014
     * Christopher Orr
       30 Years of Coens: True Grit Sep 26, 2014
     * James Fallows
       Iron Pigs Rising Sep 25, 2014
     * David A. Graham
       With Eric Holder's Exit, Obama Loses a Key Ally Sep 25, 2014
     * Olga Khazan
       Why Don't We Treat Teeth Like the Rest of Our Bodies? Sep 25, 2014
     * Bourree Lam
       Quantifying Americans' Distrust of Corporations Sep 25, 2014
     * Uri Friedman
       3 Men Visited 19 Countries in 24 Hours—or Did They? Sep 24, 2014
     * Robinson Meyer
       Facebook's Mood Manipulation Experiment Might Have Been Illegal Sep
       24, 2014
     * Jeffrey Goldberg
       A Pugnacious Obama Takes on (Most of) the World Sep 24, 2014
     * Ta-Nehisi Coates
       Books for the Horde: The New Jim Crow, Chapters 2 and 3 Sep 24,
       2014
     * Jennie Rothenberg Gritz
       B.J. Novak Proves That Kids' Books Don't Need Pictures Sep 24, 2014
     * Kathy Gilsinan
       The U.S. Has Bombed Two Different Sides in Syria's Civil War Sep
       23, 2014
     * Emma Green
       Half of Americans Believe Gay Sex Is a Sin Sep 22, 2014
     * Adrienne LaFrance
       Humanity's Most Famous Mixtape Is Now 11 Billion Miles From Earth
       Sep 22, 2014
     * Matt Ford
       The United States of Great Britain? Sep 19, 2014
     * Peter Beinart
       How to Defeat ISIS, According to Ted Cruz Sep 19, 2014
     * James Bennet
       “I Never Dreamed It Would Turn Out This Way” Sep 17, 2014

   Down

More in Technology

     * [channel-curation-featured-small.jpg?ncj3k2]

Beyond GMOs: The Rise of Synthetic Biology
       Josie Garthwaite
     * [channel-curation-featured-small.png?ncj3k2]

The Woman With the Bionic Eye
       Rose Eveleth
     * [channel-curation-featured-small.jpg?ncj3k2]

How to Stop a Rumor Online (Before the Rumor Becomes a Lie)
       Megan Garber

[camera-white.png] In Focus

   [highlight_2014092609.jpg]

Photos of the Week: 9/20-9/26

Most Popular

   1
          Life as a Nonviolent Psychopath

   2
          Peter Thiel's Zero to One Might Be the Best Business Book I've
          Read

   3
          Steve Kroft's Softball Obama Interviews Diminish '60 Minutes'

   4
          The Health Effects of Leaving Religion

   5
          Songdo, South Korea: City of the Future?

   6
          When Everything Works Like Your Cell Phone

   7
          Why I Hope to Die at 75

   8
          The Miracle of Writing

   9
          Photos of the Week: 9/20-9/26

   10
          The Case for Reparations

Just In

     * The Health Effects of Leaving Religion Jon Fortenbury
     * "Can a TV Show Save Lives?" Ali Liebegott
     * When Everything Works Like Your Cell Phone Alexis C. Madrigal and
       Robinson Meyer

ATLANTIC MEDIA

CityLab

     * My 5 Favorite Maps: Bill Rankin
     * 10 Big Ideas From CityLab 2014 Attendees
     * For Bee-Friendly Parks, Head For the Great Unmown

   More from CityLab

The Wire

     * Al Qaida Leader Vows Revenge for Airstrikes in Syria
     * Hong Kong Police Unleash Tear Gas on Protesters
     * Ferguson Police Officer Shot, Two Suspects Wanted

   More from The Wire

Quartz

     * “Hands up, don’t shoot” comes to Hong Kong’s pro-democracy movement
     * Democracy activists’ plan to disrupt Hong Kong is starting to work
     * Why global commodity prices are crashing and what it means for
       India

   More from Quartz

National Journal

     * Political TV Ads Will Soon Reach Facebook-Level Creepiness
     * Ted Cruz Banks on Foreign Policy as His 2016 Differentiator
     * Democratic House Candidates Are Walloping Republicans in the
       Small-Money Game

   More from National Journal

Defense One

     * This Site Tracks the Guns Going Into Syria
     * Our Best Bet Against ISIL: Kurdish Crude
     * How American Precision Weapons Opened the Door to an Arab Coalition

   More from Defense One

Follow The Atlantic

     * App store
     * Google Play
     * Facebook
     * Twitter
     * Linkedin
     * Google Plus
     * Tumblr
     * RSS

E-Newsletters

     * Today's Top Stories
     * This Week
     * This Month
     * New at In Focus
     * CityLab
     * 5 Best Columns
     * Today's News

Information

     * FAQ
     * Subscribe Help
     * Masthead
     * Store
     * Emporium
     * Jobs
     * Privacy
     * Site Map
     * Terms and Conditions
     * Advertise
     * Advertising Guidelines
     * Press
     * Contact Us
     * Special Reports
     * Atlantic Scene
     * Books
     * Events
     * Atlantic Media

Subscribe

   [large.jpg?nc2mvq] Get 10 issues a year and save 65% off the cover
   price
   ______________________________
   ______________________________
   ______________________________
   ______________________________
   ______________________________
   [STATE]         __________
   ______________________________
   (Submit) Next ►

Fraud alert regarding The Atlantic
     __________________________________________________________________

   Copyright © 2014 by The Atlantic Monthly Group. All Rights Reserved.
   CDN powered by Edgecast Networks. Insights powered by Parsely .

   Powered by the Parse.ly Publisher Platform (P3).

   [img]
