   #Search MIT Technology Review

     * Global Edition
     * Insider
     * Magazine
     * Business Reports
     * Lists
     * Events
     * More
          + About
          + Newsletters
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum

     * Connect

Select your localized edition:

   Close ×
     * English
     * Español
     * Deutsch
     * Italiano
     * Português
     * 中文

Filter by:

     * (*) News and Analysis
     * ( ) Magazine
     * ( ) List: Innovators Under 35
     * ( ) Conferences and Events

     * Argentina
     * Brasil
     * Colombia
     * Deutschland

     * Italia
     * México
     * Portugal
     * España

     * United States
     * Uruguay
     * 中国大陆

More Ways to Connect

   Discover one of our 28 local entrepreneurial communities »

   Be the first to know as we launch in new countries and markets around
   the globe.

   Interested in bringing MIT Technology Review to your local market?
   Search Search________________________
   Search
   Log In / Join
     * New
     * Popular
     * Login / Join

MIT Technology Review MIT Technology Review - logo

   Home News & Analysis ▾
     * Features
     * Views
     * Multimedia
     * Discussions
     * Topics

     * Popular:
     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

   cover of latest MIT Technology Review magazine issue Subscribe

     * Home
          + Home
          + Biomedicine
          + Business
          + Computing
          + Energy
          + Materials
          + Mobile
       Top Stories

Business Report

China’s Factory of the Future

Christina Larson
       1
          +

A Cheaper Way to Store Solar
         Kevin Bullis
          +

BitTorrent Adds a Paywall for Music
         Tom Simonite
          +

Using Phones’ Radio Signals to Detect Gestures
         Rachel Metz
          + See More Top Stories
     * Menu
          + News & Analysis
          + Magazine
          + Lists
          + Events
          + About
          + More
          + Features
          + Views
          + Multimedia
          + Discussions
          + Topics
          + Popular:
          + Storing Sunlight
          + Rat Control
          + Google’s Balloon Shot
          + Smarter Watson
          + Quantum Computing Questions
          + Gene Sequencing Soars
          + Printed Kidneys
       cover of latest MIT Technology Review magazine issue Subscribe
          + Current Issue
          + Past Issues
          + MIT News Magazine
          + International Editions
          + Business Reports
          + Special Publications
          + Subscriptions »
          + Smartest Companies
          + Innovators Under 35
          + Breakthrough Technologies
          + Nominations »
          + Upcoming Events
          + Partner Events
          + Emtech MIT
          + MIT Enterprise Forum
          + Our Team
          + Join Us
          + Press Room
          + Awards
          + Advertise
          + Permissions
          + Contact Us
          + Customer Support »
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum
     * Insider
     * Connect

     * The Latest
     * Popular
     * Most Shared
     * My Profile

   Unsupported browser: Your browser does not meet modern web standards.
   See how it scores »

     * Comments
     * Email
     * Service
     * Service
     * More Share
     * Print

The Brain Is Not Computable

View

     * 169 comments

Antonio Regalado

February 18, 2013

The Brain Is Not Computable

   A leading neuroscientist says Kurzweil’s Singularity isn’t going to
   happen. Instead, humans will assimilate machines.

   Miguel Nicolelis, a top neuroscientist at Duke University, says
   computers will never replicate the human brain and that the
   technological Singularity is “a bunch of hot air.”

   “The brain is not computable and no engineering can reproduce it,” says
   Nicolelis, author of several pioneering papers on brain-machine
   interfaces.

   The Singularity, of course, is that moment when a computer
   super-intelligence emerges and changes the world in ways beyond our
   comprehension.

   Among the idea’s promoters are futurist Ray Kurzweil, recently hired on
   at Google as a director of engineering, who has been predicting that
   not only will machine intelligence exceed our own, but people will be
   able to download their thoughts and memories into computers (see “Ray
   Kurzweil Plans to Create a Mind at Google—and Have It Serve You”).

   Nicolelis calls that idea sheer bunk. “Downloads will never happen,” he
   said during remarks made at the annual meeting of the American
   Association for the Advancement of Science in Boston on Sunday. “There
   are a lot of people selling the idea that you can mimic the brain with
   a computer.”

   The debate over whether the brain is a kind of computer has been
   running for decades. Many scientists think it’s possible, in theory,
   for a computer to equal the brain given sufficient computer power and
   an understanding of how the brain works.

   Kurzweil delves into the idea of “reverse-engineering” the brain in his
   latest book, How to Create a Mind: The Secret of Human Thought
   Revealed, in which he says even though the brain may be immensely
   complex, “the fact that it contains many billions of cells and
   trillions of connections does not necessarily make its primary method
   complex.”

   But Nicolelis is in a camp that thinks that human consciousness (and if
   you believe in it, the soul) simply can’t be replicated in silicon.
   That’s because its most important features are the result of
   unpredictable, nonlinear interactions among billions of cells,
   Nicolelis says.

   “You can’t predict whether the stock market will go up or down because
   you can’t compute it,” he says. “You could have all the computer chips
   ever in the world and you won’t create a consciousness.”

   The neuroscientist, originally from Brazil, instead thinks that humans
   will increasingly subsume machines (an idea, incidentally, that’s also
   part of Kurzweil’s predictions).

   In a study published last week, for instance, Nicolelis’s group at Duke
   used brain implants to allow mice to sense infrared light, something
   mammals can’t normally perceive. They did it by wiring a head-mounted
   infrared sensor to electrodes implanted into a part of the brain called
   the somatosensory cortex.

   The experiment, in which several mice were able to follow sensory cues
   from the infrared detector to obtain a reward, was the first ever to
   use a neural implant to add a new sense to an animal, Nicolelis says.

   That’s important because the human brain has evolved to take the
   external world—our surroundings and the tools we use—and create
   representations of them in our neural pathways. As a result, a talented
   basketball player perceives the ball “as just an extension of himself”
   says Nicolelis.

   Similarly, Nicolelis thinks in the future humans with brain implants
   might be able to sense x-rays, operate distant machines, or navigate in
   virtual space with their thoughts, since the brain will accommodate
   foreign objects including computers as part of itself.

   Recently, Nicolelis’s Duke lab has been looking to put an exclamation
   point on these ideas. In one recent experiment, they used a brain
   implant so that a monkey could control a full-body computer avatar,
   explore a virtual world, and even physically sense it.

   In other words, the human brain creates models of tools and machines
   all the time, and brain implants will just extend that capability.
   Nicolelis jokes that if he ever opened a retail store for brain
   implants, he’d call it Machines “R” Us.

   But if he’s right, us ain’t machines, and never will be.

169 comments. Share your thoughts » 0 comments about this story. Start the
discussion »

   Credit: Duke University

   Tagged: Computing, Web, Mobile

   Reprints and Permissions | Send feedback to the editor
     * Related stories
     * You may have missed
     * More from this author

     *

First Quantum Logic Operation For An Integrated Photonic Chip
       The first teleportation of a photon inside a photonic chip
       illustrates both the potential for quantum computation and the
       significant challenges that lay ahead.
       Continue
       0

     *

Seven Must-Read Stories (Week Ending September 27, 2014)
       0
     *

EmTech: Nest Technologist on the Problem of Remaking “Unloved Devices”
       1
     *

Seven Must-Read Stories (Week Ending September 20, 2014)
       0
     *

Nanotechnologists Discover How to Carve Tunnels Beneath the Surface of
Silicon Chips
       1

     *

How Network Theory Is Revealing Previously Unknown Patterns in Sports
       5
     *

Seven Must-Read Stories (Week Ending September 13, 2014)
       0
     *

The Revolutionary Technique That Quietly Changed Machine Vision Forever
       8
     *

Simple Illumination Technique Creates 3-D Virtual Models Using One Digital
Camera
       0

     *

Making Innovation
     *

Three Questions with the CEO of D-Wave
     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
     *

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
     *

EmTech: IBM Tries to Make Watson Smarter
     *

EmTech: Google’s Internet “Loon” Balloons Will Ring the Globe within a Year

   Antonio Regalado Editor

   View Profile »

   Follow @antonioregalado
     * RSS

     *

EmTech: Risks of Gene-Editing Drugs Need Study, Pioneer Warns
       1
     *

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
       3
     *

Radical New DNA Sequencer Finally Gets into Researchers’ Hands
       8
     *

On the Horns of the GMO Dilemma
       23

     *

Michael Schmidt | Innovators Under 35
     *

Maryam Shanechi | Innovators Under 35
     *

Could a Genetic Test Predict the Risk for Suicide?
       2
     *

Spotting Cancer in a Vial of Blood
       15
     * See all from this author

     * The Latest
     * Popular
     * Most Shared

     *

1 day ago

Other Interesting arXiv Papers (Week ending September 27, 2014)
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

2 days ago

Thom Yorke Album Sold Through BitTorrent in Attempt to Make File Sharers Pay
     *

2 days ago

Seven Stories You Shouldn’t Miss
(Week Ending September 27, 2014)
     *

Innovation Series: The Connected Home
       Brought to you by
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

2 days ago

Radio Interference Adds Gesture Recognition to Smartphones
     *

3 days ago

Recommended from Around the Web (Week Ending September 27, 2014)
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

3 days ago

Best Tweets from EmTech: Day 2
     *

Revolution in Progress: The Networked Economy
       In partnership with SAP
     *

3 days ago

Best Tweets from EmTech: Day 1
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

Technology Insights - Portability vs. Privacy: Striking the Right Balance in
the Mobile Era
       Free download courtesy of Symantec
     *

4 days ago

EmTech: Risks of Gene-Editing Drugs Need Study
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     * See full archive

     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

5 days ago

EmTech: Google’s Astro Teller Says Its “Loon” Balloons Will Ring the Globe in
2015
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

1 month ago

35 Innovators Under 35 | 2014
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

6 days ago

Uber’s Driver Poach Shows Lack of Respect for Workers
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

5 days ago

EmTech: Three Questions with a “Meat Brewer”
     *

5 days ago

App Talko Hopes to Get You to Use Phone to Actually Talk
     * See full archive

     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

1 week ago

Solar City and Tesla Combine Manufacturing Plans
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

1 week ago

The Hidden World of Facebook "Like Farms"
     *

2 months ago

Forget the Shortest Route Across a City; New Algorithm Finds the Most
Beautiful
     *

1 month ago

35 Innovators Under 35 | 2014
     *

3 years ago

Astronomers Find First Evidence of Other Universes
     *

1 year ago

Innovators Under 35
     *

1 year ago

Given Tablets but No Teachers, Ethiopian Children Teach Themselves
     *

1 year ago

Astrobiologists Find Ancient Fossils in Fireball Fragments
     *

1 year ago

First Teleportation from One Macroscopic Object to Another
     *

1 year ago

Government Lab Reveals It Has Operated Quantum Internet for Over Two Years
     * See full archive

   Show comments »
   Conversation powered by Livefyre

New & Trending

     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

     * Other Interesting arXiv Papers (Week ending September 27, 2014)
     * First Quantum Logic Operation For An Integrated Photonic Chip
     * A Promising Step Toward Round-the-Clock Solar Power
     * Pirate Favorite BitTorrent Offers a New Way to Pay for Music

From the Archives

     * The Art of the Possible
    8 years ago
     * The Hottest VC on the Planet
    10 years ago
     * Nanotech Goes to Work
    13 years ago
     * Computing's Johnny Appleseed
    14 years ago

     * more
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * ...1899
     * more

   Close

Introducing MIT Technology Review Insider.

Already a Magazine subscriber?

   You're automatically an Insider. It's easy to activate or upgrade your
   account.
   Activate Your Account

Become an Insider

   It's the new way to subscribe. Get even more of the tech news,
   research, and discoveries you crave.
   Sign Up

Learn More

   Find out why MIT Technology Review Insider is for you and explore your
   options.
   Show Me

   News and Analysis
     * Home
     * Popular
     * Today's News
     * Blogs
     * Photo Galleries
     * Videos

   Back to Top

   The mission of MIT Technology Review is to equip its audiences with the
   intelligence to understand a world shaped by technology.
     * Editions
       Find your preferred version. Choose from six languages and in 13
       regions worldwide.
     * Archives
       Explore 115 years of innovation from the most respected technology
       publication.
     * Lists
       Discover the most important people, companies and technologies
       shaping our future.
     * Events
       Attend one of our over 400 thought-provoking live events worldwide.
     * Subscribers
       Have MIT Technology Review delivered to your doorstep, desktop, or
       tablet.

     * More
     * Newsletters
     * MIT Enterprise Forum
     * MIT News Magazine
     * EmTech

     * Company
     * About Us
     * Work for Us
     * Advertise with Us
     * Reprints and Permissions

     * Your Account
     * Join
     * View Profile
     * Manage Account
     * Manage Subscription

     * Customer Support
     * Help / Support
     * Contact us
     * Feedback
     * Sitemap

Connect

     * Twitter
     * LinkedIn
     * YouTube
     * Google+
     * StumbleUpon
     * Facebook
     * RSS
     * Mobile

MIT Technology Review

     * Ethics Statement
     * Terms of Service
     * Privacy
     * Commenting Guidelines

     * © 2014
     * v1.13.05.10

   [p?c1=2&c2=16198136&cv=2.0&cj=1]

   Quantcast
