   Jump to navigation

   The Big Data Hub
   Search _______________ Search
     * About Us
     * Contact Us

     * Home
     * Blogs
     * Videos & Podcasts
          + Videos
          + Big Data Bytes
          + Big Data Developers Streaming Meetups
          + IBM Big Data in a Minute
          + Podcasts
     * Resources
          + White Papers & Reports
          + Infographics & Animations
          + Presentations
          + Galleries
     * Events
          + Upcoming Events
          + Webcasts
          + Twitter Chats
          + Meetups
     * Around the Web
     * View By Tag
     * RSS Feeds

The Big Data Hub

         ×
     * Use Cases
          + Acquire, Grow and Retain Customers
          + Create New Business Models
          + Improve IT Economics
          + Manage Risk
          + Optimize Operations and Reduce Fraud
          + Transform Financial Processes
     * Industries
          + Banking
          + Consumer Products
          + Energy & Utilities
          + Government
          + Healthcare & Life Sciences
          + Insurance
          + Media & Entertainment
          + Retail
          + Telecommunications
     * Analytics
          + Content Analytics
          + Customer Analytics
          + Entity Analytics
          + Predictive Analytics
          + Social Media Analytics
     * Technology
          + Cloud
          + Data Warehouse & Storage
          + Database Management
          + Discovery & Exploration
          + Hadoop & Open Source
          + Integration & Governance
          + Stream Computing
          + Technical Enablement
     * Watson Foundations
     * For Developers

Blogs

   Topics
   Analytics, Big Data Education, Big Data Technology, Data Scientists,
   Hadoop
   Tags
   Twitter chat, #BigDataMgmt, Hadoop, skills, skills gap, data scientist
     __________________________________________________________________

   David Pittman
   Social Media Strategist, Information & Analytics Group
   Follow me on Twitter, LinkedIn, Google+
   Post a Comment

What skills are needed for big data?

   May 9, 2014

   The gap between the demand for analytics talent globally and the supply
   of talent  is one of the key obstacles to big data implementations
   across all organizations. In a global study of business and IT leaders
   conducted by IBM Institute for Business Value, 1/3 of respondents cited
   the lack of skills to analyze and interpret data into meaningful
   business actions as the top business challenge impeding better use of
   analytics within their organizations. And this challenge is expected to
   grow. Gartner says that by 2015, the demand for data and analytics
   resources will reach 4.4 million jobs globally, but only one-third of
   those jobs will be filled.

   In this #BigDataMgmt Twitter chat, we will discuss which skills are
   most in need currently and which are hardest to develop, how academia
   is responding to the challenge, and how technology may be able to help.

   Our special guests for the chat are Edd Dumbill (@edd), technology
   analyst, editor and VP of strategy at Silicon Valley Data
   Science; Paula Wiles Sigmon (@paulawilesigmon), program director,
   InfoSphere Information Server product marketing; and Tom Deutsch
   (@thomasdeutsch) program director, IBM big data and advanced analytics.
   Twitter handle @IBMbigdata will be moderating the chat.

   You can follow along and join the discussion using the
   hashtag #BigDataMgmt. Here are the questions we’ll be discussing, as
   well as reference articles to help inspire the conversation on
   Wednesday, May 14, 12:00 noon EST.

#BigDataMgmt chat questions

    1. We hear talk of the big data skills gap. How dire is the current
       situation?
    2. What are the key curricula or disciplines needed for big data
       workers?
    3. What skills are the hardest to find or develop: deep analytic
       expertise or strong business acumen?
    4. How is academia responding to this shortage of data scientists?
    5. How can a data analyst develop stronger business and communication
       skills?
    6. What’s your advice for data analysts & statisticians who want to
       further develop data science skills?
    7. If orgs are looking to hire data scientists, what should they look
       for?
    8. How is technology helping bring “big data to all”?

Background Resources

   IBM Institute for Business Value Study: “Analytics: A blueprint for
   value”

   Blog: What Skills are Essential for Big Data?

   Blog: Right Skills, Right Place, Right Time: Educating the
   Next-Generation Big-Data Professional

   Podcast: Data Scientists and Their Curriculum

   Blog: Big Data Requires Strong Analytics Capabilities

   Blog: Development and access to skills and capabilities

   Blog: Hadoop and the big data opportunity

Related Content

     * Blogs
     * Infographics & Animations
     * Podcasts
     * Presentations
     * Slideshows
     * Videos
     * White Papers & Reports

     * Big Data & Analytics Heroes: Sharath Cholleti
     * Big Data & Analytics Heroes: Terri Dean
     * Big Data & Analytics Heroes: Timothy Llewellynn
     * Most popular infographics and presentations of 2014—so far
     * Top 10 blog posts on big data and analytics from the first half of
       2014
     * Top videos on big data and analytics from the first half of 2014
     * Top big data and analytics podcasts from the first half of 2014
     * Big Data & Analytics Heroes: Suresh Sidhu

     * IBM Insight 2014 by the numbers
     * The Evolution of Big Data
     * The Four V's of Big Data
     * Big Data: Making the World Go Round
     * Big Data: The New Natural Resource
     * The Flood of Big Data
     * Tuning Into Big Data as the Buzz Gets Louder
     * Smarter CMOS Driving More IT Decisions

     * Gaining an advantage from information management
     * Juggler or high diver: How do you work in real time?
     * Transforming potential into action
     * It must be big data's fault
     * Big data in the Middle East and Africa
     * 6 trends in big data and analytics
     * Conquering culture clash: A new methodology for big data success
     * Big data is all data

     * Why infrastructure matters for big data and analytics
     * Hadoop is better with Big SQL from IBM
     * IBM Big SQL Technology Preview Program
     * Analytics: A Blueprint for Value - Executive Overview
     * Presentation: 5 Keys to Making Big Data Production-Ready
     * Debunking Myths about Data Scientists

     * IBM Big Data & Analytics Heroes
     * Quick Facts and Stats on Big Data

     * IBM Big Data in a Minute: Spotting trends with big data
     * IBM Big Data in a Minute: Analyzing data in motion
     * IBM Big Data in a Minute: The age of the customer
     * IBM Big Data in a Minute: Transforming unstructured data into
       better healthcare outcomes
     * IBM Big Data in a Minute: Bringing the power of Hadoop to the
       enterprise
     * IBM Big Data in a Minute: Driving creativity with data
     * IBM InfoSphere: The need for real-time analytics is real
     * IBM Big Data in a Minute: Gaining competitive advantage with speed

     * Book: Harness the Power of Big Data
     * Top Tips for Securing Big Data Environments: e-book
     * Big Data Analytics: Disruptive Technologies for Changing the Game
     * Understanding Big Data: e-book
     * Analytics: A blueprint for value - Converting big data and
       analytics insights into results
     * Book: The MDM Advantage: Creating Insight from Big Data
     * Book: Data Protection for Big Data Environments
     * Book: Understanding Big Data So You Can Act with Confidence

Post a Comment

   View the discussion thread.
     *

   Big Data Dev Works

   Four-Ways-Sidebar-Ad-Banner-2.jpg

Follow IBM Big Data & Analytics

     * Twitter
     * Twitter
     * Facebook
     * LinkedIn
     * YouTube
     * Google+

     * Site Map
     * Privacy
     * Terms of Use
     * 2013 IBM

     * Explore By Content Type
          + Blogs
          + Videos
          + Podcasts
          + Big Data Bytes
          + Big Data Developers Streaming Meetups
          + White Papers & Reports
          + Infographics & Animations
          + Presentations
          + Galleries
          + Events
          + Around the Web
          + View Content By Tag
          + About The Big Data & Analytics Hub
          + Contact Us
          + RSS Feeds
     * Explore By Category
          + Use Cases
          + Industries
          + Analytics
          + Technology
          + IBM Watson Foundations
          + For Developers
     * Additional Big Data Resources
          + AnalyticsZone
          + Big Data University
          + Channel Big Data
          + developerWorks Big Data Community
          + IBM big data for the enterprise
          + IBM Data Magazine
          + Smarter Questions Blog

     * Home
     * Use Cases
          + All Use Cases
          + Acquire, Grow and Retain Customers
          + Create New Business Models
          + Manage Risk
          + Improve IT Economics
          + Optimize Operations & Reduce Fraud
          + Transform Financial Processes
     * Industries
          + All Industries
          + Banking
          + Consumer Products
          + Energy & Utilities
          + Government
          + Healthcare & Life Sciences
          + Insurance
          + Media & Entertainment
          + Retail
          + Telecommunications
     * Analytics
          + All Analytics
          + Content Analytics
          + Customer Analytics
          + Entity Analytics
          + Predictive Analytics
          + Social Media Analytics
     * Technology
          + All Technologies
          + Cloud
          + Data Warehouse & Storage
          + Database Management
          + Discovery & Exploration
          + Hadoop & Open Source
          + Integration & Governance
          + Stream Computing
          + Technical Enablement
     * IBM Watson Foundations
     * For Developers
     * Blogs
     * Videos & Podcasts
          + Videos
          + Big Data Bytes
          + Big Data Developers Streaming Meetups
          + IBM Big Data in a Minute
          + Podcasts
     * Resources
          + White Papers & Reports
          + Infographics & Animations
          + Presentations
          + Galleries
     * Events
          + Upcoming Events
          + Webcasts
          + Twitter Chats
          + Meetups
     * Around the Web
     * View By Tag
     * RSS Feeds
     * About The Big Data Hub
     * Contact Us
