   #Search MIT Technology Review

     * Global Edition
     * Insider
     * Magazine
     * Business Reports
     * Lists
     * Events
     * More
          + About
          + Newsletters
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum

     * Connect

Select your localized edition:

   Close ×
     * English
     * Español
     * Deutsch
     * Italiano
     * Português
     * 中文

Filter by:

     * (*) News and Analysis
     * ( ) Magazine
     * ( ) List: Innovators Under 35
     * ( ) Conferences and Events

     * Argentina
     * Brasil
     * Colombia
     * Deutschland

     * Italia
     * México
     * Portugal
     * España

     * United States
     * Uruguay
     * 中国大陆

More Ways to Connect

   Discover one of our 28 local entrepreneurial communities »

   Be the first to know as we launch in new countries and markets around
   the globe.

   Interested in bringing MIT Technology Review to your local market?
   Search Search________________________
   Search
   Log In / Join
     * New
     * Popular
     * Login / Join

MIT Technology Review MIT Technology Review - logo

   Home News & Analysis ▾
     * Features
     * Views
     * Multimedia
     * Discussions
     * Topics

     * Popular:
     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

   cover of latest MIT Technology Review magazine issue Subscribe

     * Home
          + Home
          + Biomedicine
          + Business
          + Computing
          + Energy
          + Materials
          + Mobile
       Top Stories

Business Report

China’s Factory of the Future

Christina Larson
       1
          +

A Cheaper Way to Store Solar
         Kevin Bullis
          +

BitTorrent Adds a Paywall for Music
         Tom Simonite
          +

Using Phones’ Radio Signals to Detect Gestures
         Rachel Metz
          + See More Top Stories
     * Menu
          + News & Analysis
          + Magazine
          + Lists
          + Events
          + About
          + More
          + Features
          + Views
          + Multimedia
          + Discussions
          + Topics
          + Popular:
          + Storing Sunlight
          + Rat Control
          + Google’s Balloon Shot
          + Smarter Watson
          + Quantum Computing Questions
          + Gene Sequencing Soars
          + Printed Kidneys
       cover of latest MIT Technology Review magazine issue Subscribe
          + Current Issue
          + Past Issues
          + MIT News Magazine
          + International Editions
          + Business Reports
          + Special Publications
          + Subscriptions »
          + Smartest Companies
          + Innovators Under 35
          + Breakthrough Technologies
          + Nominations »
          + Upcoming Events
          + Partner Events
          + Emtech MIT
          + MIT Enterprise Forum
          + Our Team
          + Join Us
          + Press Room
          + Awards
          + Advertise
          + Permissions
          + Contact Us
          + Customer Support »
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum
     * Insider
     * Connect

     * The Latest
     * Popular
     * Most Shared
     * My Profile

   Unsupported browser: Your browser does not meet modern web standards.
   See how it scores »

     * Comments
     * Email
     * Service
     * Service
     * More Share
     * Print

After Microsoft Deal, What’s Left of Nokia Will Bet on Internet of Things

Mobile News

     * 0 comments

After Microsoft Deal, What’s Left of Nokia Will Bet on Internet of Things

   With the devices business gone, Nokia’s CTO says he’ll try to
   capitalize on innovations in sensors, materials, and cloud software.
     * By David Talbot on February 25, 2014

Why It Matters

   Despite losing its perch atop the mobile-phone business, Nokia still
   could significantly influence the future of communications.

   After Microsoft closes its purchase of Nokia’s devices and services
   businesses in the coming weeks, Nokia’s chief technology officer, Henry
   Tirri, will be part of a new organization. The new outfit, known as
   Nokia Advanced Technologies, will be expected to take better advantage
   of Nokia’s vast patent portfolio and its richly financed R&D
   organization (see “Can This Man Work Magic?”).

   Nokia’s intellectual property includes more than 30,000 patents,
   including many fundamental to wireless communications—as well as others
   in materials, nanoscience, and software. With the devices division
   gone, the Advanced Technologies business will cut licensing deals and
   perform advanced R&D with partners, with around 600 people around the
   globe, mainly in Silicon Valley and Finland.

   In a conversation at Mobile World Congress in Barcelona, Spain, with
   David Talbot, chief correspondent of MIT Technology Review, Tirri said
   he sees opportunity in the Internet of Things as the once-dominant
   Finnish mobile phone giant tries to reinvent itself yet again.

   On what technology areas will Nokia’s Advanced Technologies business
   focus?

   First you need to have a vision—a point of view about the
   future—otherwise things don’t make sense. We are now talking about the
   idea of a programmable world. We are not just talking about a computing
   revolution as in the past; to me it reflects much more what will happen
   in your home, your connected car, with your wearable devices, and so
   on. No device now works alone. You use the same things from your
   laptop, your tablet, smartphone or whatever. Many of your smartphone
   apps already lose their value when they are not cloud connected. The
   same thing will be true in the future for other everyday objects.

   If you believe in such a vision, as I do, then a lot of our
   technological assets will help in the future evolution of this world:
   global connectivity, our expertise in radio connectivity, materials,
   imaging and sensing technologies.

   What are some examples of such technologies?

   Bluetooth low-energy technology. Any modern sensing app which is
   connected to a smartphone will be using Bluetooth LE, a low-powered
   technology compatible with Bluetooth, for which much of the development
   was done in our labs. Other domains will be wearable sensors, such as
   e-Skin—nanosensing various kinds of biological measurements that can be
   used for monitoring your health and wellness. And particularly
   graphene—we were one of the founders of the EU’s Graphene Flagship
   program—will help in new kinds of computing and sensing devices. And of
   course, there is a software dimension to all of these.

   Why not build some new products? Nokia has reinvented itself before.

   We will explore new product areas, either to develop ourselves or
   potentially for technology licensing to others, as Advanced
   Technologies will also be a licensing business. We have an existing
   portfolio, developed ourselves, built from more than 50 billion euros
   of R&D investment over the last 20 years, as well as experience in
   building products. Beyond simply licensing IP, we expect to be
   developing technologies and products together with customers, in the
   way you see others such as Qualcomm or ARM doing. We have technologies
   in our portfolio that we have not broadly licensed because we reserved
   them for differentiating our products. But as we divest our devices
   business, we could, for example, look to license imaging technology to
   camera manufacturers; or take connectivity technologies and license
   them for use in wearable devices.

   What are you going to get rid of?

   It’s too early to be certain, but there may be some technologies,
   perhaps including mobile phone user interface-related work, that won’t
   make sense for us to continue, but we need to look at this in more
   depth once the transaction with Microsoft has closed.

   It’s no secret that Nokia’s huge research efforts over the years did
   not help it avoid being outflanked by the iPhone and go from a mobile
   phone pioneer to a minor player in the smartphone business.

   That was not purely an R&D question, but a platform business question,
   and the steps we then took to adopt Windows Phone to address this have
   been well documented. In the future, Advanced Technologies will itself
   be a business, which is quite a fundamental change from being a
   corporate function to becoming a business in its own right. Technology
   licensing and advanced R&D will be intertwined within the business, as
   opposed to being a separate corporate research team and IP business.

0 comments. Share your thoughts » 0 comments about this story. Start the
discussion »

   Tagged: Computing, Communications, Web, Mobile

   Reprints and Permissions | Send feedback to the editor
     * Related stories
     * You may have missed
     * More from this author

     *

Travel App Can Recommend Places by Looking at Them
       Software that counts dogs, martini glasses, and mustaches in
       Instagram photos provides a novel way to rate businesses.
       Continue
       1

     *

Radio Waves Offer Cheap Gesture Detection on Smartphones
       0
     *

An App That Wants You to Actually Talk on Your Phone
       4
     *

This Phone App Knows If You’re Depressed
       5
     *

Can a Website Help You Decide to Have a Kid?
       12

     *

Datacoup Wants to Buy Your Credit Card and Facebook Data
       0
     *

A Dating Site for Algorithms
       1
     *

Smartphone Newcomers Find Success in Markets with Room to Grow
       0
     *

Recommended from Around the Web (Week Ending September 27, 2014)
       0

     *

Making Innovation
       The hubs of advanced manufacturing will be the economic drivers of
       the future because innovation increasingly depends on...
       Continue
       5
     *

Three Questions with the CEO of D-Wave
       The CEO of quantum computing startup D-Wave says its machines are
       helping companies analyze Wall Street data and search for...
       Continue
       1
     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
       Controlled by software, paralyzed rats walk and climb stairs.
       Continue
       2
     * Francis de Souza, president of Illumina

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
       Record number of genomes being decoded, but cost of DNA sequencing
       might not fall much further, says Illumina president.
       Continue
       3
     *

EmTech: IBM Tries to Make Watson Smarter
       IBM executive says Watson could find success with commercial apps
       in wealth management, call centers, and medicine.
       Continue
       2
     * Astro Teller

EmTech: Google’s Internet “Loon” Balloons Will Ring the Globe within a Year
       Google X research lab boss Astro Teller says experimental wireless
       balloons will test delivering Internet access throughout...
       Continue
       10

   David Talbot Editor

   View Profile »

   Follow @David_A_Talbot
     * RSS

     *

EmTech: IBM Tries to Make Watson Smarter
       0
     *

EmTech: Three Questions with the Man Who Grows Meat
       11
     *

U.N. Predicts New Global Population Boom
       29
     *

Construction Begins at a Carbon-Capture Plant, but Will It Ever Be Completed?
       21

     *

Surging Carbon Dioxide Shows Clean Tech Failure
       152
     *

A Nimble-Wheeled Farm Robot Goes to Work in Minnesota
       2
     *

Networked Home Gadgets Offer Hackers New Opportunities
       2
     *

Massive Internet Outage Points to Flaws in Policy and Technology
       9
     * See all from this author

     * The Latest
     * Popular
     * Most Shared

     *

1 day ago

Other Interesting arXiv Papers (Week ending September 27, 2014)
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

2 days ago

Thom Yorke Album Sold Through BitTorrent in Attempt to Make File Sharers Pay
     *

2 days ago

Seven Stories You Shouldn’t Miss
(Week Ending September 27, 2014)
     *

Innovation Series: The Connected Home
       Brought to you by
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

2 days ago

Radio Interference Adds Gesture Recognition to Smartphones
     *

3 days ago

Recommended from Around the Web (Week Ending September 27, 2014)
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

3 days ago

Best Tweets from EmTech: Day 2
     *

Revolution in Progress: The Networked Economy
       In partnership with SAP
     *

3 days ago

Best Tweets from EmTech: Day 1
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

Technology Insights - Portability vs. Privacy: Striking the Right Balance in
the Mobile Era
       Free download courtesy of Symantec
     *

4 days ago

EmTech: Risks of Gene-Editing Drugs Need Study
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     * See full archive

     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

5 days ago

EmTech: Google’s Astro Teller Says Its “Loon” Balloons Will Ring the Globe in
2015
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

1 month ago

35 Innovators Under 35 | 2014
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

6 days ago

Uber’s Driver Poach Shows Lack of Respect for Workers
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

5 days ago

EmTech: Three Questions with a “Meat Brewer”
     *

5 days ago

App Talko Hopes to Get You to Use Phone to Actually Talk
     * See full archive

     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

1 week ago

Solar City and Tesla Combine Manufacturing Plans
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

1 week ago

The Hidden World of Facebook "Like Farms"
     *

2 months ago

Forget the Shortest Route Across a City; New Algorithm Finds the Most
Beautiful
     *

1 month ago

35 Innovators Under 35 | 2014
     *

3 years ago

Astronomers Find First Evidence of Other Universes
     *

1 year ago

Innovators Under 35
     *

1 year ago

Given Tablets but No Teachers, Ethiopian Children Teach Themselves
     *

1 year ago

First Teleportation from One Macroscopic Object to Another
     *

1 year ago

Government Lab Reveals It Has Operated Quantum Internet for Over Two Years
     *

5 months ago

How to Win at Rock-Paper-Scissors
     * See full archive

   Show comments »
   Conversation powered by Livefyre

New & Trending

     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

     * Other Interesting arXiv Papers (Week ending September 27, 2014)
     * First Quantum Logic Operation For An Integrated Photonic Chip
     * A Promising Step Toward Round-the-Clock Solar Power
     * Pirate Favorite BitTorrent Offers a New Way to Pay for Music

From the Archives

     * The Art of the Possible
    8 years ago
     * The Hottest VC on the Planet
    10 years ago
     * Nanotech Goes to Work
    13 years ago
     * Computing's Johnny Appleseed
    14 years ago

     * more
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * ...1899
     * more

   Close

Introducing MIT Technology Review Insider.

Already a Magazine subscriber?

   You're automatically an Insider. It's easy to activate or upgrade your
   account.
   Activate Your Account

Become an Insider

   It's the new way to subscribe. Get even more of the tech news,
   research, and discoveries you crave.
   Sign Up

Learn More

   Find out why MIT Technology Review Insider is for you and explore your
   options.
   Show Me

   News and Analysis
     * Home
     * Popular
     * Today's News
     * Blogs
     * Photo Galleries
     * Videos

   Back to Top

   The mission of MIT Technology Review is to equip its audiences with the
   intelligence to understand a world shaped by technology.
     * Editions
       Find your preferred version. Choose from six languages and in 13
       regions worldwide.
     * Archives
       Explore 115 years of innovation from the most respected technology
       publication.
     * Lists
       Discover the most important people, companies and technologies
       shaping our future.
     * Events
       Attend one of our over 400 thought-provoking live events worldwide.
     * Subscribers
       Have MIT Technology Review delivered to your doorstep, desktop, or
       tablet.

     * More
     * Newsletters
     * MIT Enterprise Forum
     * MIT News Magazine
     * EmTech

     * Company
     * About Us
     * Work for Us
     * Advertise with Us
     * Reprints and Permissions

     * Your Account
     * Join
     * View Profile
     * Manage Account
     * Manage Subscription

     * Customer Support
     * Help / Support
     * Contact us
     * Feedback
     * Sitemap

Connect

     * Twitter
     * LinkedIn
     * YouTube
     * Google+
     * StumbleUpon
     * Facebook
     * RSS
     * Mobile

MIT Technology Review

     * Ethics Statement
     * Terms of Service
     * Privacy
     * Commenting Guidelines

     * © 2014
     * v1.13.05.10

   [p?c1=2&c2=16198136&cv=2.0&cj=1]

   Quantcast
