   #Businessweek.com Top News RSS

   Sign in with Facebook Or use your Businessweek account
   Email
   _______________________________________________________________________
   Password Forgot password? ____________________ [ ] Remember me Sign In

   Already a Bloomberg.com user?

   Sign in with the same account.

   Don't have an account? Sign up.

   Help! I can't access my account.
   This site uses cookies. By continuing to browse the site you are
   agreeing to our use of cookies. X
   Bloomberg Businessweek

Technology

   Ebola Rising
   LIMITED-TIME OFFER SUBSCRIBE NOW
   ____________________
     * Global Economics
     * Companies & Industries
     * Politics & Policy
     * Technology
     * Markets & Finance
     * Innovation & Design
     * Lifestyle
     * Business Schools
     * Small Business
     * Video & Multimedia

Features

Google's Sundar Pichai Is the Most Powerful Man in Mobile

   By Brad Stone June 24, 2014
     __________________________________________________________________

   (An earlier version of this story ran online.)
   (Corrects the price of the Chromecast hardware in second-to-last
   paragraph.)

   Benjamin Rasmussen for Bloomberg BusinessweekAt the Consumer
   Electronics Show in Las Vegas in January, Samsung (005930:KS)
   introduced new software for its tablets, called the Magazine UX. This
   was a revamped interface that resembled the table of contents in a
   magazine, allowing users to click directly into videos and articles.
   Manufacturers often apply their own design flourishes to Android, and
   this one looked good—not groundbreaking, maybe—but slick, intuitive,
   and completely unobjectionable.

   Behind the scenes, though, the announcement enraged executives at
   Google (GOOG), the company that owns and administers Android. Magazine
   UX hid Google services such as its Play apps store and required Android
   users and application developers to learn an entirely new set of
   behaviors for Samsung devices. The South Koreans were relegating Google
   to the background.

   Defusing the situation fell to Sundar Pichai, the tactful, tactical new
   chief of Google’s Android division. Pichai set up a series of meetings
   with J.K. Shin, chief executive officer of Samsung Mobile
   Communications, at the Wynn (WYNN) hotel on the Vegas strip, at
   Google’s offices in Mountain View, Calif., and again in February at the
   Mobile World Congress convention in Barcelona. Pichai says they held
   “frank conversations” about the companies’ intertwined fates. A fragile
   peace was forged. Samsung agreed to scale back Magazine UX and,
   signaling a new era of cooperation, the two companies announced a broad
   patent cross-licensing arrangement. “We now work together more closely
   on user experience than we ever have before,” Pichai says.

   Ten years ago, the Indian-born Pichai, 42, was a product manager at
   Google, and his domain consisted of the search bar in the upper right
   corner of Web browsers. He then persuaded his bosses to wade into the
   browser wars with Chrome, which in time became the most popular browser
   on the Internet and led to the Chrome operating system that runs on a
   line of cheap laptops called Chromebooks. Pichai took over Gmail and
   Google Docs in 2011. In 2013, CEO Larry Page put him in charge of
   Android, making him one of the most powerful technology executives in
   the world. Page says Pichai “has deep technical expertise, a great
   product eye, and tremendous entrepreneurial flair. This is a rare
   combination, which is what makes him a great leader.”

   Google doesn’t discuss Android’s profitability, and analysts have had a
   notoriously difficult time making estimates. Yet the operating system
   is vital to Google, whose revenue was $60 billion in 2013. Android runs
   on 1.2 billion devices around the world. It drives users to the
   company’s hugely profitable search engine and the ads on its maps
   service. Google search and maps are available on phones made by Apple
   (AAPL) and Microsoft (MSFT), too, but Google pays those companies
   referral fees. The more people use Android, the more Google can keep
   that revenue to itself.

   Managing Android might be the hardest job at the company. Every phone
   maker that joins the Android world has to balance its interests with
   those of Google. The software is open-source, so anyone can adapt the
   code for his or her own purposes. Google distributes the latest
   versions free under the agreement that device makers will highlight
   profitable Google services—especially search and maps—while their own
   brands and services take a back seat.

   Samsung isn’t the only company whose relationship with Google is
   complicated. Companies such as Amazon.com (AMZN), which recently
   introduced its own phone, the Fire, and Nokia (NOK) have created custom
   variations of Android that use older versions of the software and leave
   out Google services entirely. HTC (2498:TT) and LG Electronics
   (066570:KS) have taken the deal but make little money from their
   Android devices and hold negligible shares of the smartphone market.
   Meanwhile, developers complain about the complexity of making
   applications for the varied world of Android phones and tablets, all
   with differently sized screens and processors, particularly compared
   with the relative ease of developing for Apple’s more orderly universe
   of iPhones and iPads.

   “The openness and flexibility that Android created is a double-edged
   sword,” says Dave Feldman, co-founder of Emu, which makes a mobile
   messaging service. “Because carriers and manufacturers can modify
   Android, the task of creating and debugging an app can be far more
   time-consuming than for iOS. That is Android’s big challenge.”

   Tim Cook, Apple’s CEO, used the stage at Apple’s Worldwide Developers
   Conference in June to call Android a “toxic hellstew” of security
   vulnerabilities and fragmentation, running on so many kinds of devices
   that it fails to offer the latest features to users. Pichai calmly
   mounts a defense of Android’s security features and its relationship
   with developers, but it concludes as less of a retort than a sigh of
   envy. “It must be liberating [for Apple] to wake up and think about
   your device, your software—and hey, ‘I can even call the chip-set guys
   and say what the chip should be,’” he says. “I have to think about
   building a platform and bringing as many people along on this journey
   and getting it right. I believe that ultimately, it’s a more powerful
   approach, but it’s a lot more stressful as well.”

   Photograph by Benjamin Rasmussen for Bloomberg BusinessweekPichai’s
   colleagues talk up his affability and skills as a diplomat, how he
   bucks the contemporary image of technology executives as vainglorious,
   out-of-touch men-children. “I would challenge you to find anyone at
   Google who doesn’t like Sundar or who thinks Sundar is a jerk,” says
   Caesar Sengupta, a vice president who has worked with Pichai for eight
   years.

   In person Pichai is soft-spoken and self-deprecating. He warns that
   without proper care, Android’s future might resemble a surfing lesson
   he recently took in Hawaii with his 11-year-old daughter: It seemed
   like a triumph when he got up for the first time, but then he fell
   badly. In a series of interviews in conference rooms at Google’s
   Mountain View, Calif., and San Francisco offices, he peppers his
   conversation with idiosyncratic tics, abusing the word “internalize,”
   and inserting “et cetera” at the end of many phrases. A recently grown,
   gray-flecked beard adds gravitas to his boyish face. He says not
   shaving saves time and “reflects the state of mind of having more
   responsibility.”


   Pichai was born in Chennai, a city of 4 million in the southern Indian
   state of Tamil Nadu. His mother worked as a stenographer before she had
   children; his father was an electrical engineer for the British
   conglomerate GEC and managed a factory that made electrical components.
   “I used to come home and talk to him a lot about my work day and the
   challenges I faced,” recalls Regunatha Pichai. “Even at a young age, he
   was curious about my work. I think it really attracted to him to
   technology.” Pichai with his parents in California in 1997, when they
   came to visit him in the U.S. for the first time Courtesy Sundar
   PichaiPichai with his parents in California in 1997, when they came to
   visit him in the U.S. for the first time

   The family of four lived in a two-room apartment, with Sundar and his
   younger brother sleeping in the living room. During much of his
   childhood, the Pichais didn’t have a television or a car. For
   transportation, the choice was either one of the crowded, stifling city
   buses or the family’s blue Lambretta scooter. All four would pile
   on—Regunatha driving, Sundar standing at the front, and his younger
   brother perched on the back of the seat with their mother.

   The Pichais got their first telephone, a rotary, when Sundar was 12.
   The phone revealed to him the magical conveniences of technology, as
   well as an unusual gift: He could remember every number he ever dialed.
   “My uncle would call up and say, ‘Hey, I lost this phone number, but
   you once helped me dial it,’ and I would be able to tell him,” Pichai
   says. “I wasn’t so sure that was useful.” (It is now: Google executives
   marvel at Pichai’s powers of numerical recall. Alan Eustace, vice
   president for engineering, says that during a recent meeting, Pichai
   produced a statistic related to the increase of voice-activated
   searches. “That’s my area,” Eustace says, “and he knew a number I did
   not know.”)

   Pichai excelled at school and won a coveted spot at the Indian
   Institute of Technology in Kharagpur, where he studied engineering.
   After graduating, he won an additional scholarship to Stanford
   University to study materials science and semiconductor physics.
   Pichai’s father tried to take out a loan to cover the cost of the plane
   ticket and other expenses. When it didn’t come through in time, he
   withdrew $1,000 from the family’s savings—more than his annual salary.
   “My dad and mom did what a lot of parents did at the time,” Pichai
   says. “They sacrificed a lot of their life and used a lot of their
   disposable income to make sure their children were educated.”

   Upon arriving at Stanford in 1993, he tried to buy a new backpack and
   “was in an absolute state of shock” to learn it cost $60. He later
   bought a used one on an online bulletin board. Pichai lived with a host
   family during his first year and spent much of the time miserably
   lamenting the absence of his girlfriend, Anjali, who later joined him
   in the U.S. and is now his wife. Pichai at the Stanford University
   dorms in 1994 Courtesy Sundar PichaiPichai at the Stanford University
   dorms in 1994

   Pichai planned to get a Ph.D. at Stanford and pursue an academic
   career, but he briefly panicked his parents by dropping out to work as
   an engineer and product manager at Applied Materials, a Silicon Valley
   semiconductor maker. After getting an MBA from the Wharton School of
   Business in 2002 and spending a stint as a consultant at McKinsey,
   Pichai arrived at the Googleplex on April 1, 2004. On the day of his
   job interview, Google launched Gmail, the free e-mail service. Pichai
   says he thought it was one of the company’s famous April Fools’ pranks.

   Pichai joined the small team working on Google’s search toolbar. It
   gave users of Internet Explorer and Firefox, the dominant browsers at
   the time, easy access to Google search. He proposed that Google build
   its own browser and won the support of the company’s co-founders,
   though he faced an objection from then-CEO Eric Schmidt, who thought
   that joining the browser wars would be an expensive distraction. Chrome
   eventually proved fast and painless to use while ensuring that Web
   users had direct access to Google’s search engine and its immensely
   profitable advertising system. Chrome now holds 32 percent of the
   browser market on phones and desktop PCs, ahead of Internet Explorer,
   Firefox, and Apple’s Safari, according to Adobe. Pichai and his wife,
   Anjali, in New York in 2002 Courtesy Sundar PichaiPichai and his wife,
   Anjali, in New York in 2002

   Even Pichai’s effort to develop the Chrome operating system for laptops
   is showing promise amid an overall slump in PC sales. Chromebooks route
   users directly onto the Internet, where they store all their
   information, instead of on a hard drive. When Chrome OS was introduced
   in 2011, such a stripped-down system that kept data “in the cloud”
   seemed preposterous; now 21 percent of commercial laptops sold in the
   U.S. last year were Chromebooks, according to the NPD Group. Pulling
   that off was a managerial feat: Pichai assembled a large, well-funded
   group inside Google that was serious about building hardware and
   forging strong relationships with retailers such as Best Buy (BBY) and
   PC manufacturers such as Dell, Lenovo (0992:HK), and Samsung. Those
   skills would come in handy running Android.


   The first Android device came out in 2008, more than a year after the
   first iPhone. The G1 smartphone, made by HTC, ran only on T-Mobile
   (TMUS) in the U.S. and had a sliding screen that revealed a
   physical, BlackBerry (BBRY)-like keyboard. It met with lukewarm
   reviews. Within three years, boosted by the proliferation of varied,
   inexpensive Android devices made by Samsung, HTC, and others, Android
   had become the most popular smartphone operating system in the world.
   IDC, a tracking firm, expects Android to run on 80 percent of the
   smartphones that will be sold this year, blowing away Apple’s 15
   percent market share. Android now powers everything from Samsung’s new
   Galaxy S5 smartphone ($650 without a contract) and Motorola Mobility’s
   smaller Moto E phone ($130) to a universe of connected devices such as
   smart-watches, refrigerators, and a $3,000 treadmill from NordicTrack.

   Andy Rubin deserves much of the credit for Android’s success. A
   charismatic technologist and repeat entrepreneur, Rubin founded a
   startup called Android in 2003 and sold it to Google in 2005. Then he
   guided the chief product—the mobile operating system—for the next eight
   years, building its huge ecosystem of device makers and developers
   while successfully preventing Apple from utterly dominating the next
   stage of computing with the iPhone. Rubin kept handset makers off
   balance by selectively sharing information and choosing a different
   company each year for early access to the newest version of the
   software. That approach fostered competition among phonemakers, which
   outdid each other with faster processors, higher resolution screens,
   and other improvements.

   Click to compare iOS and Android screen sizes Photograph by Brent
   Lewin/BloombergClick to compare iOS and Android screen sizes

   Rubin’s style also grated. Hardware manufacturers, vying for special
   treatment, viewed him as Machiavellian and difficult to work with,
   according to many executives at these companies. As the operating
   system gained popularity, every division of Google wanted to plant its
   flag on Android smartphones. Rubin closed Android’s ranks, and Google
   employees were fond of saying that it was easier to work with rival
   Apple than Android. “Part of it was just the phase of the project,”
   says Brian Rakowski, an Android vice president. “The team really needed
   to just ignore everybody.” Rubin also fought to keep the platform
   neutral, giving outside developers as much of a chance on Google phones
   as internal services such as social network Google Plus. One person
   close to Google’s management team, who was not authorized to speak
   publicly, says Rubin’s reluctance to work openly with other parts of
   Google was responsible for the only shouting matches he’s witnessed in
   the upper ranks at the company.

   In 2012, Google announced a version of Pichai’s Chrome browser for
   Android, which would replace the mobile browser Rubin had developed
   within his own group. It seemed a perfect model for friendly
   collaboration within Google. Yet the relationship between the divisions
   was so strained that they wouldn’t work together without a term sheet,
   a contract normally required between two companies that stipulated the
   responsibility of each side.

   “There was nothing ever personal,” Pichai says, when asked whether he
   got along with Rubin. “We had a good sense of friendship, though we
   weren’t particularly close, but we never had any major disagreements.
   We had passionate debates about certain courses.” He allows that their
   styles differed. “Andy kept a lot about how he thought about things to
   himself. My sense is that at a base level, that is how he functioned.
   Andy had a plan and a strategy, but it was inside his own head.” Google
   declined to make Rubin available for comment, and Pichai says he
   doesn’t consult with him.

   By 2013, Android was winning the smartphone war but lagging in newer
   markets. Apple’s iPad dominated tablets, while Google-led efforts were
   struggling. An early attempt to develop Android-based software for TV
   set-top boxes, called Google TV, also failed.

   At the beginning of 2013, CEO Page told Rubin he had to integrate
   Android with the rest of Google. Rubin agreed at first, then changed
   his mind and decided he couldn’t do it. He resigned his position,
   though he remains at Google, working on a skunk works robotics project.
   A person close to Google’s management says that forcing Rubin’s hand
   was the most difficult decision Page has made since reclaiming the CEO
   spot at Google three years ago. Page then handed responsibility for
   Android over to Pichai.


   Benjamin Rasmussen for Bloomberg BusinessweekPichai says his first task
   was to do no harm. “I was worried about disruption,” he says. “This was
   a small team executing well.” Others at Google say he quickly started
   opening doors between Android and other product groups. He pushed
   Google Now, the Android feature that sends users customized, intuited
   information such as driving times and the sports scores of favorite
   teams. Rubin had introduced it, but Pichai created an interdisciplinary
   team with the search group, which had voice search technology and
   algorithms that could discern what information might be most important
   to users. “Sundar helped me to formalize a relationship,” says Johanna
   Wright, the product manager who runs Google Now. “Because search and
   Android sit in two different buildings, we ended up doing a people
   swap.” It was a kind of Google glasnost that would have been unlikely
   to happen under Rubin.

   Pichai threw extra resources at a project called Svelte, a slimmed-down
   Android intended to run well on cheap, low-powered devices. It means
   developers don’t have to create multiple versions of their apps to
   compensate for old operating systems run by budget phones. And Pichai
   killed a project to develop a version of Android for touchscreen
   laptops—it overlapped with Chromebooks—shifting attention toward
   tablets and new categories such as smart TVs and wearable computers.
   Deciding that the coming age of connected home appliances needed a
   separate focus, he helped orchestrate the $3.2 billion acquisition of
   smart thermostat maker Nest in January. Then he shuttered several
   smart-home projects inside Android and handed responsibility for
   connected appliances to Nest because, he says, “I felt it was far
   enough out and different enough from what we were doing.” Nest has
   drawn good reviews for its original product, a connected thermostat,
   but had to temporarily take its newer smoke detector off the market to
   correct a safety glitch. Nest recently acquired Dropcam, a maker of
   wireless security cameras, for $555 million and announced it would
   allow outside developers to link into its devices. (The smoke detector
   went back on sale on June 17.)

   Pichai has tried to improve relations with other companies as well. In
   April 2013, he took Page and Chief Business Officer Nikesh Arora on a
   trip to South Korea to visit Samsung executives and tour a factory. He
   says the intent of the trip was to convey respect. “I felt there was
   more distance than I would like in a partnership,” he says. “I wanted a
   closer, more direct line of communication.” Page also shook hands with
   South Korean President Park Geun-hye without causing an international
   stir by keeping one hand in his pocket, as Bill Gates had done the
   previous week.

   Pichai is still walking a tightrope with Samsung, balancing the needs
   of the Android superpower while keeping rival manufacturers in the
   fold. Samsung still touts its own rival Linux-based mobile operating
   system called Tizen, suggesting it may be planning for a day when it
   decides to reduce its dependence on Android. Pichai shrugs off that
   possibility. “I view Tizen as a choice which people can have,” he says.
   “We need to make sure Android is the better choice.”

   For now, Samsung uses Tizen primarily to run its Galaxy Gear smartwatch
   and a new phone, the Samsung Z, which is being introduced later this
   year in Russia. Gene Munster, an analyst at Piper Jaffray, believes
   Pichai has quelled the threat. “The relationship is never going to be
   perfect, but I think it’s in good shape,” he says. “They both need each
   other is the bottom line.”


   On June 25 and 26, 6,000 developers and members of the media descended
   on San Francisco for Google’s high-profile annual conference, called
   I/O. Really, though, it was the Sundar Show. (Page and Google
   co-founder Sergey Brin were not in attendance.) Pichai served as master
   of ceremonies, pitching Android’s suitability for the workplace and for
   the coming age of connected televisions, automobiles, and wristwatches.

   Pichai had been preparing for I/O since early June, which isn’t a lot
   of time as major Silicon Valley events go. Google typically plans these
   things at the last minute—a week before the conference, Pichai had yet
   to make several big decisions about whether certain projects were ready
   to be unveiled. No doubt there was a lot of pacing during the prep
   meetings: Colleagues say Pichai likes to walk when deep in thought and
   will occasionally wander away during a meeting, only to reappear with
   an answer to a problem.

   When the day arrived, Pichai made a change that seemed small and
   technical but is actually a huge deal. In the past, Google often waited
   until the fall to announce the next annual version of the operating
   system, each named for a different sweet beginning with the next letter
   of the alphabet (in the last three years, Ice Cream Sandwich,
   Jellybean, and KitKat). Android hardware makers hated that, complaining
   that the announcement came too late for them to get ready for the
   holidays. It also put them at a disadvantage to the one company
   selected each year to develop a phone in conjunction with Google.

   This year, Pichai previewed the next release for the first time at I/O
   rather than waiting until the fall. The updated Android—as yet
   unnamed—includes a design that adds more depth and richer animations to
   the screen and allows people to more easily unlock their phones based
   on the proximity of devices such as a smartwatch. Introducing the new
   Android early in the year is a significant shift toward greater
   transparency. “I want the world to understand what we are doing
   sooner,” Pichai says.

   Android executives also talked about Android Wear, a version of the
   operating system for fitness trackers and wearable computers, and
   announced new smartwatches from Samsung, LG, and Motorola. The watches
   serve up notices about pending appointments and health data such as the
   wearer’s heart rate. They also run a range of their own applications,
   so users can order takeout and call taxis from their wrists and not
   have to pull out their phones.

   Google is racing against Apple, which will introduce its iWatch in the
   fall. Pichai says it’s “crazy” that people visit their doctors once a
   year at most to have their heart rate and blood pressure measured. “You
   obviously need to be able to measure these things so many more times
   and then apply more intelligence to it,” he says.

   Television was also on the agenda. Google has struggled when it comes
   to the living room, with the failed Google TV effort in 2010. It’s had
   more success with a $35 piece of hardware called the Chromecast that
   allows users to run video and apps from phones or tablets on their
   HDTVs. Seeking to avoid the inconsistent approaches of the past, Pichai
   has brought everyone at Google working on TV software into one group
   within Android. The new software lets gamemakers and other developers
   easily transfer their apps over to televisions. Owners of Google TV
   devices, which are coming later this year, will be able to use their
   voices to search for shows and films and use their phone or watch as a
   remote control.

   Pichai explained that Android TV is meant to give “TV the same level of
   attention that phones and tablets have enjoyed.” Samsung, LG, Sharp,
   and others make smart TVs that run their own proprietary software;
   presumably none of them want to cede control over their customers to
   Google, as they already have in smartphones and tablets. Pichai’s job
   will be to persuade them to bet on Android all over again.
   Story: Exclusive: Sundar Pichai, Head of Google's Android, on Apple,
   Samsung, and Amazon
   Graphic: The Fragmented World of Android
   Video: The Best Android Phone Gets Better
   Video: Is Google Android More Secure Than Apple iOS?
   Story: Heartbleed: Android Phones Still at Risk for Data Breach
   Story: Nothing Keeps Apple From Making an Android Phone Except Common
   Sense
   Story: Google Introduces KitKat, Its Latest Version of Android
   Story: Why Google, Comcast, and AT&T Are Making Power Utilities Nervous
   Story: UnGoogle Me: The Case for Scrubbing Search Results
   Story: Google Employs Fewer Women Than Dozens of Its S&P 500 Peers
   Story: Why Google Is Sending Its Smartphones Into Space
   Stone_190
   Stone is a senior writer for Bloomberg Businessweek in San Francisco.
   He is the author of The Everything Store: Jeff Bezos and the Age of
   Amazon (Little, Brown; October 2013). Follow him on Twitter @BradStone.
     __________________________________________________________________

   Ebola Rising
   LIMITED-TIME OFFER SUBSCRIBE NOW

Feed Most Popular

     * Read
     * Shared
     * Discussed

     * How Islamic State Wages War
     * Why Hospitals Want Patients to Pay Upfront
     * Twin Peaks: 'Hooters Just Wasn't Racy Enough'
     * How SNL Became the Most Successful Comedy Show Ever
     * Google Cuts Ties With Right-Wing Group: ‘They’re Just Literally
       Lying’

     * Why Hospitals Want Patients to Pay Upfront
     * Belgian Town Builds a Beer Pipeline to Save the Environment
     * The Insurgents Who Could Bring Down the NCAA
     * Polaroid Goes After GoPro With a $99 Action Camera
     * Twin Peaks: 'Hooters Just Wasn't Racy Enough'

     * After 9 Years and $67 Billion, F-22 Raptor Sees Combat in Syria
     * Mississippi Tea Partiers Vow to Keep Fighting the State GOP
     * How the U.S. Screwed Up in the Fight Against Ebola
     * Google Cuts Ties to Right-Wing Group: 'They’re Just Literally
       Lying'
     * Next-Generation GMO Seeds Wait for Weed Killer to Win Over EPA

Newsletter Signup

   Sample copy
   ______________________________ I'm in
   [X] Businessweek.com, on behalf of itself and select partners, may send
   me offers and promotions.
   [ ] Bloomberg, on behalf of itself and select partners, may send me
   offers and promotions.

   Thank you for subscribing to our Daily Newsletter. You will receive a
   confirmation email shortly at .

Companies Mentioned

     * 005930:KS
       (Samsung Electronics Co Ltd)
          + $1185000.0 KRW
          + 29000.00
          + 2.45%
          +
     * GOOG
       (Google Inc)
          + $577.1 USD
          + 2.04
          + 0.35%
          +

   Market data is delayed at least 15 minutes.

Bloomberg Businessweek

     * A Moscow Rally for Ukraine's Rebels: 'This War Should Last Until
       the Victorious End'
     * Russia Won't Cry Uncle to U.S. Sanctions Russia Won't Cry Uncle to
       U.S. Sanctions
    Russia Won't Cry Uncle to U.S. Sanctions
     * Tech Bubble About to Burst?: Bloomberg West (09/26) Tech Bubble
       About to Burst?: Bloomberg West (09/26)
    Tech Bubble About to Burst?: Bloomberg West (09/26)
     * We Aim to Elevate the Category of Rum: Serrallés We Aim to Elevate
       the Category of Rum: Serrallés
    We Aim to Elevate the Category of Rum: Serrallés
     * De Halve Maan (Half Moon) Brewery's interior beer hall in Bruges,
       Belgium De Halve Maan (Half Moon) Brewery's interior beer hall in
       Bruges, Belgium
    Belgian Town Builds a Beer Pipeline to Save the Environment
     * Yes, Americans Can Be Fired for Running for Office Yes, Americans
       Can Be Fired for Running for Office
    Yes, Americans Can Be Fired for Running for Office
     * Pimco founder and co-chief investment officer Bill Gross plays golf
       at Pebble Beach Golf Links in California, 2012 Pimco founder and
       co-chief investment officer Bill Gross plays golf at Pebble Beach
       Golf Links in California, 2012
    Bill Gross Takes a Big Step Down
     * The semitrailer carrying 35,000 pounds of frozen chicken, abandoned
       at a western Montana truck stop on Sept. 24, 2014 in Missoula The
       semitrailer carrying 35,000 pounds of frozen chicken, abandoned at
       a western Montana truck stop on Sept. 24, 2014 in Missoula
    A Raw Chicken Heist With a Rotten Ending
     * Mario Goetze of Germany scores a goal past Sergio Romero of
       Argentina in extra time during the 2014 FIFA World Cup Brazil Final
       Mario Goetze of Germany scores a goal past Sergio Romero of
       Argentina in extra time during the 2014 FIFA World Cup Brazil Final
    The Jumping Sneaker Prices Behind Nike's Boom Times
     * A Vivid Glimpse of the Fed's Cozy Relationship With Goldman A Vivid
       Glimpse of the Fed's Cozy Relationship With Goldman
    A Vivid Glimpse of the Fed's Cozy Relationship With Goldman

Ads by Google

Sponsored Links

   Buy a link now!

Social

     * Follow us on Twitter
     * Join us on Facebook
     * Connect with us on LinkedIn
     * Connect with us on Google+
     * Subscribe to Bloomberg Businessweek
     * Bloomberg

Links

     * Our Company
     * News Mission
     * Advertising
     * Careers
     * Content Licensing
     * Feedback
     * Custom Publishing
     * Manage Subscription

     * Mobile
     * Newsletters
     * Privacy Policy
     * Reprints & Permissions
     * Sitemap
     * Terms of Use
     * [+] Rate This Page
     * Sponsor Content Terms

Get Businessweek Delivered

   Ebola Rising

Ebola Rising

   Subscribe

   ©2014 Bloomberg L.P. All Rights Reserved. Made in NYC Ad Choices



   blog comments powered by Disqus

   Continue to Businessweek

   *
