   #prev next

     * Contact
     * Feedback
     * Submit
     * Subscribe
     * PNAS First Look Blog

   Search ____________________ GO GO
   Advanced Search »
   Proceedings of the National Academy of Sciences of the United States of
   America

PNAS, Proceedings of the National Academy of Sciences

   Skip to main page content
     * Sackler
     *
     * Science Sessions: The PNAS Podcast Program

     * Current Issue
     * Archive
     * News & Multimedia
     * For Authors
     * About PNAS

     * Collected Articles
          + 100th Anniversary
          + Colloquium Papers
          + Commentaries
          + Core Concepts
          + Cozzarelli Prize
          + Editorials
          + Feature Articles
          + Front Matter
          + Inaugural Articles
          + In This Issue
          + Inner Workings
          + Letters and Replies
          + News Features
          + Opinions
          + Perspectives
          + PNAS Classics
          + PNAS Plus
          + PNAS Portals
          + Profiles
          + QnAs
          + Retrospectives
          + Science and Culture
          + Significance Statements
          + Special Features
          + Sustainability Science
     * Browse by topic
          + Applied Biological Sciences
          + Applied Mathematics
          + Applied Physical Sciences
          + Astronomy
          + Biochemistry
          + Biophysics and Computational Biology
          + Cell Biology
          + Chemistry
          + Anthropology
          + Computer Sciences
          + Developmental Biology
          + Earth, Atmospheric, and Planetary Sciences
          + Ecology
          + Economic Sciences
          + Engineering
          + Environmental Sciences
          + Evolution
          + Genetics
          + Geology
          + Geophysics
          + Immunology and Inflammation
          + Mathematics
          + Medical Sciences
          + Microbiology
          + Molecular Biology
          + Neuroscience
          + Pharmacology
          + Physics
          + Physiology
          + Plant Biology
          + Political Sciences
          + Population Biology
          + Psychological and Cognitive Sciences
          + Social Sciences
          + Statistics
          + Sustainability Science
          + Systems Biology
     * Early Edition
          + All Early Edition
          + Highlights from Early Edition

     * Go to PNAS Homepage
     * > Current Issue
     * > vol. 111 no. 36
     * > Cunjiang Yu,  12998–13003

   [crossmark_button.png]

Adaptive optoelectronic camouflage systems with designs inspired by
cephalopod skins

    1. Cunjiang Yu^a,
    2. Yuhang Li^b,^c,
    3. Xun Zhang^d,
    4. Xian Huang^d,
    5. Viktor Malyarchuk^d,
    6. Shuodao Wang^d,
    7. Yan Shi^b,^e,
    8. Li Gao^d,
    9. Yewang Su^b,
   10. Yihui Zhang^b,
   11. Hangxun Xu^f,
   12. Roger T. Hanlon^g,^h,
   13. Yonggang Huang^b, and
   14. John A. Rogers^d,^i,^1

    1. ^aDepartment of Mechanical Engineering, Department of Electrical
       and Computer Engineering, University of Houston, Houston, TX 77204;
    2. ^bDepartment of Civil and Environmental Engineering, Department of
       Mechanical Engineering, Center for Engineering and Health, and Skin
       Disease Research Center, Northwestern University, Evanston, IL
       60208;
    3. ^cThe Solid Mechanics Research Center, Beihang University, Beijing
       100191, China;
    4. ^dDepartment of Materials Science and Engineering, University of
       Illinois at Urbana–Champaign, Urbana, IL 61801;
    5. ^eState Key Laboratory of Mechanics and Control of Mechanical
       Structures, Nanjing University of Aeronautics and Astronautics,
       Nanjing 210016, China;
    6. ^fDepartment of Polymer Science and Engineering, Chinese Academy of
       Sciences Key Laboratory of Soft Matter Chemistry, University of
       Science and Technology of China, Hefei 230026, China;
        7. ^gMarine Biological Laboratory, Woods Hole, MA 02543;
    8. ^hDepartment of Ecology and Evolutionary Biology, Brown University,
       Providence, RI 02912; and
    9. ^iDepartment of Electrical and Computer Engineering, Department of
       Chemistry, Department of Mechanical Science and Engineering,
       Frederick Seitz Materials Research Laboratory, and Beckman
       Institute for Advanced Science and Technology, University of
       Illinois at Urbana–Champaign, Urbana, IL 61801

    1. Edited by David A. Weitz, Harvard University, Cambridge, MA, and
       approved July 30, 2014 (received for review June 5, 2014)

Significance

   Artificial systems that replicate functional attributes of the skins of
   cephalopods could offer capabilities in visual appearance modulation
   with potential utility in consumer, industrial, and military
   applications. Here we demonstrate a complete set of materials,
   components, fabrication approaches, integration schemes, bioinspired
   designs, and coordinated operational modes for adaptive optoelectronic
   camouflage sheets. These devices are capable of producing
   black-and-white patterns that spontaneously match those of the
   surroundings, without user input or external measurement. Systematic
   experimental, computational, and analytical studies of the optical,
   electrical, thermal, and mechanical properties reveal the fundamental
   aspects of operation and also provide quantitative design guidelines
   that are applicable to future embodiments.

Abstract

   Octopus, squid, cuttlefish, and other cephalopods exhibit exceptional
   capabilities for visually adapting to or differentiating from the
   coloration and texture of their surroundings, for the purpose of
   concealment, communication, predation, and reproduction. Long-standing
   interest in and emerging understanding of the underlying
   ultrastructure, physiological control, and photonic interactions has
   recently led to efforts in the construction of artificial systems that
   have key attributes found in the skins of these organisms. Despite
   several promising options in active materials for mimicking biological
   color tuning, existing routes to integrated systems do not include
   critical capabilities in distributed sensing and actuation. Research
   described here represents progress in this direction, demonstrated
   through the construction, experimental study, and computational
   modeling of materials, device elements, and integration schemes for
   cephalopod-inspired flexible sheets that can autonomously sense and
   adapt to the coloration of their surroundings. These systems combine
   high-performance, multiplexed arrays of actuators and photodetectors in
   laminated, multilayer configurations on flexible substrates, with
   overlaid arrangements of pixelated, color-changing elements. The
   concepts provide realistic routes to thin sheets that can be
   conformally wrapped onto solid objects to modulate their visual
   appearance, with potential relevance to consumer, industrial, and
   military applications.
     * flexible electronics
     * metachrosis
     * thermochromic

Footnotes

     * ↵^1To whom correspondence should be addressed. Email:
       jrogers{at}illinois.edu.

     * Author contributions: C.Y. and J.A.R. designed research; C.Y.,
       Y.L., X.Z., X.H., V.M., S.W., Y. Shi, L.G., Y. Su, Y.Z., H.X.,
       Y.H., and J.A.R. performed research; C.Y., Y.L., Y. Su, Y.Z., Y.H.,
       and J.A.R. analyzed data; and C.Y., Y.L., Y. Shi, Y. Su, R.T.H.,
       Y.H., and J.A.R. wrote the paper.
     * The authors declare no conflict of interest.
     * This article is a PNAS Direct Submission.
     * This article contains supporting information online at
       www.pnas.org/lookup/suppl/doi:10.1073/pnas.1410494111/-/DCSupplemen
       tal.

Online Impact

     * Add to Facebook Facebook
     * Add to Twitter Twitter
     * Add to Google+ Google+
     * Add to CiteULike CiteULike
     * Add to Delicious Delicious
     * Add to Digg Digg
     * Add to Mendeley Mendeley

   What's this?

In This Issue

   This Week in PNAS: In This Issue PNAS 2014 111 (36) 12955-12956;
   doi:10.1073/iti3614111
     * Extract
     * Full Text (HTML)
     * Full Text (PDF)
     * Figures Only

This Issue

   Cover
     * September 9, 2014
       vol. 111 no. 36
       Masthead (PDF)
       Table of Contents

     * prev prev article
     * next article next


Don't Miss

   Thinking of submitting your next paper to PNAS? Learn tips in the new
   PNAS tutorial videos.
     __________________________________________________________________

Article Tools

Article Alerts

    1. Alert me when this article is cited
    2. Alert me if a correction is posted
    3. Email this article to a colleague

Export Citation

    1. Download to citation manager

Save for Later

    1. Add to My File Cabinet

Request Permission

    1. ©   Request Permission

Share

    1.
          + Add to Facebook Facebook
          + Add to Twitter Twitter
          + Add to Google+ Google+
          + Add to CiteULike CiteULike
          + Add to Delicious Delicious
          + Add to Digg Digg
          + Add to Mendeley Mendeley
       What's this?
     __________________________________________________________________

   Published online before print August 18, 2014, doi:
   10.1073/pnas.1410494111
   PNAS September 9, 2014 vol. 111 no. 36 12998-13003

   Classifications
     * Physical Sciences
          + Engineering
     __________________________________________________________________

Access

    1. » Abstract
    2. Full Text (HTML)
    3. Full Text (PDF)
    4. PDF + SI
    5. Figures Only
    6. Supporting Information
    7. In This Issue
     __________________________________________________________________

Figures

    1. Fig. 1. Fig. 1. Browse All Figures

Other Articles

Citing This Article

    1. Load citing article information
    2. Citing articles via CrossRef
    3. Citing articles via Web of Science

Google Scholar

    1. Articles by Yu, C.
    2. Articles by Rogers, J. A.

PubMed

    1. PubMed citation
    2. Articles by Yu, C.
    3. Articles by Rogers, J. A.
    4.

Similar to This Article

    1. Similar articles in this journal
    2. Similar articles in ISI
    3. Similar articles in PubMed
     __________________________________________________________________

   submit an article
   NAS, National Academy of Sciences
   HighWire Press, Stanford University
   PNAS
   PNAS
   PNAS Online is distributed with the assistance of
   HighWire Press® | Online ISSN 1091-6490
   Copyright © 2014 National Academy of Sciences. Website by Boston
   Interactive
     * Contact
     * Feedback
     * Subscribe
     * For the Press
     * Editorial Board
     * Site Map
     * Privacy/Legal

     * For an alternate route to PNAS: http://intl.pnas.org
