   Login / Create an Account

   Search______________ Submit

Open Compute Project

     * Specs & Designs
          + Storage
          + Networking
          + Server Design
          + Open Rack
          + Compliance and Interoperability
          + Hardware Management
          + Data Center
          + OCP Archive
     * News
     * Community
          + Get Involved
          + Events
          + Careers
          + OCP Calendars
     * About
          + Mission and Principles
          + Organization and Board
          + Energy Efficiency
          + Solution Providers
          + Member Directory
     * Contact

     * Specs & Designs
          + Storage
          + Networking
          + Server Design
          + Open Rack
          + Compliance and Interoperability
          + Hardware Management
          + Data Center
          + OCP Archive
     * News
     * Community
          + Get Involved
          + Events
          + Careers
          + OCP Calendars
     * About
          + Mission and Principles
          + Organization and Board
          + Energy Efficiency
          + Solution Providers
          + Member Directory
     * Contact

OCP Summit V: Keynote Videos

   Wednesday, January 29, 2014 · Posted by at 6:00 AM

   Missed out on the livestream? Catch up on the keynotes here. A full
   list of video replays can be found here.

Day Two - Keynotes

     * Fireside Chat: Marc Andreessen (Co-founder and General Partner,
       Andreessen Horowitz); Andy Bectholsheim (Founder, Chief Development
       Officer, and Chairman, Arista Networks); Cade Metz (Senior Editor,
       Business and Enterprise, Wired) - http://youtu.be/O-gENvy0F-w

     * "ARM for the Datacenter" - Ian Drew (Chief Marketing Officer, ARM)
       - http://youtu.be/fazdfD2iypU

     * "Opening Up Network Hardware" - Najam Ahmad (Director,
       Infrastructure, Facebook); JR Rivers (Co-founder and CEO, Cumulus
       Networks); Martin Casado (Chief Architect, Networking, VMware);
       Matthew Liste, (Managing Director, Core Platform Engineering,
       Goldman Sachs); Dave Maltz (Partner Development Manager, Microsoft)
       - http://youtu.be/fzA4VIUnAIw

     * "Adopting OCP Technologies" - Cole Crawford (Executive Director,
       OCP Foundation); Justin Erenkrantz (Head of Cloud Architecture,
       Bloomberg); Jeremy Huylebroeck, (Software and IT Architect,
       Orange); Ron Williams (VP of Operations, Riot Games)
       - http://youtu.be/OOajrB0-Yos


Day One - Keynotes

     * "The Open Compute Project: 2014 and Beyond" - Frank Frankovsky
       (Chairman and President, Open Compute Foundation)
       - http://youtu.be/VIWK_NyCO14

     * "Microsoft Datacenters at Cloud Scale" - Bill Laing (CVP, Windows
       Server and System Center Group Development, Microsoft)
       - http://youtu.be/synH7fXUmRs

     * "Open Architecture: The Tipping Point for Enterprise Cloud" -
       George Slessmen (CEO and Product Architect, IO); Tim Lyons
       (Executive Director, Digital Innovation and Outreach, Merck & Co.);
       Cole Crawford (Executive Director, OCP
       Foundation) - http://youtu.be/XOAjEDvIJWw

     * "Efficiency is Profitable: Facebook's Approach to Full-Stack
       Infrastructure Optimization" - Jay Parikh (VP, Infrastructure,
       Facebook); Matt Corddry (Director, Hardware Engineering, Facebook);
       Marco Magarelli (Design Engineer,
       Facebook) - http://youtu.be/yu8jin33G64

     * Fireside Chat: Tim O'Reilly and Mark Zuckerberg (CEO, Facebook)
       - http://youtu.be/imwHX_dlpIw

     * "Disruptive Technologies for the Datacenter" - Andrew Feldman (GM
       and CVP, AMD) - http://youtu.be/XJPNWk1w3iE

     * "The Datacentered Future" - Greg Huff (CTO, LSI)
       - http://www.youtube.com/watch?v=ZCCm2M6itP0




   The Open Compute Project was first released by Facebook in 2011. Read
   our requisite legal stuff. Privacy Policy | Terms of Service
   Major thanks to Rackspace for hosting.

   Also contact and follow us at
   email fb tw rss google plus
