   #How Tea Party tax cuts are turning Kansas into a smoking ruin - Los
   Angeles Times

   The Economy Hub
   With Michael Hiltzik
   BusinessThe Economy Hub

How Tea Party tax cuts are turning Kansas into a smoking ruin

   BusinessBusinessPoliticsTaxationPersonal IncomeGovernmentProductivity
   How Tea Party tax cuts are turning Kansas into a smoking ruin


Michael Hiltzik


    Los Angeles Timesmichael.hiltzik​@latimes.com

@hiltzikmWhy US health costs have soared: Nation's top insurer paid $43
million in allegedly fraudulent claims w/o checking: http://t.co/XfdClsrcwp

   Sam Brownback
   Sam Brownback
   Mike Yoder / Associated Press
   Kansas Gov. Sam Brownback promised that his steep tax cuts would
   supercharge the state's economy. But job growth in Kansas trails the
   nation. Above, Brownback at a news conference in March.
   Kansas Gov. Sam Brownback promised that his steep tax cuts would
   supercharge the state's economy. But job growth in Kansas trails the
   nation. Above, Brownback at a news conference in March. (Mike Yoder /
   Associated Press)
   Whatʼs the matter with Kansas? Idiotic tax cuts, thatʼs what
   Tea party-inspired tax cuts in Kansas benefit the Koch brothers but are
   destroying state services

   Sam Brownback, the Republican governor of Kansas, doesn't just believe
   in whistling past the graveyard--he's willing to stroll past it in
   full-throated song.

   The graveyard is where the economy of Kansas has been buried since
   2012, when Brownback and his Republican state legislature enacted a
   slew of deep tax cuts in a tea party-esque quest for economic
   "freedom."
   Our new pro-growth tax policy will be like a shot of adrenaline into
   the heart of the Kansas economy. - Kansas Gov. Sam Brownback in 2012,
   promising an elusive bright future

   "Our new pro-growth tax policy will be like a shot of adrenaline into
   the heart of the Kansas economy," he promised then. Brownback's tax
   consultant, the supply-side guru Art Laffer, promised Kansans that the
   cuts would pay for themselves in supercharged economic growth.

   Instead, job growth in Kansas trails the nation. The state's rainy-day
   fund is dwindling to zero. Month after month, revenue comes in even
   lower than fiscal officials' most dire expectations.

   In the rest of the country, school budgets are finally beginning to
   recover from the toll of the last recession; in Kansas, they're still
   falling. Healthcare, assistance for the poor, courts, and other state
   services are being eviscerated.
   lRelated A fraud accusation like nothing youʼve seen before

   The Economy Hub
          A fraud accusation like nothing youʼve seen before

   See all related
   8

   Who's benefiting? The rich, including those proud offspring of Wichita,
   Kan.: the Koch brothers.

   Despite all this, Brownback resorted to an op-ed in the Wall Street
   Journal a few weeks ago to declare that "the early results are
   impressive." Among other statistics he cited, "In the past year, a
   record number of small businesses — more than 15,000 — were formed."

   Yes, but as shown by the Center on Budget and Policy Priorities, a
   Washington economic think tank, 16,000 disappeared. And many of those
   businesses that Brownback crowed about were surely created to take
   advantage of one of the tax-cut quirks Brownback enacted. This is the
   elimination of all taxes on partnerships, sole proprietorships, and
   LLCs that pass through their tax liabilities to their owners. That
   allows everyone from freelancers and petty contractors to huge
   partnerships to avoid any state income tax at all, as long as they're
   organized as a certain type of "small business."

   Brownback's policy, and his claims about its outcome, define the term
   "ideological" -- the imposition of preconceived notions on a
   contradictory reality.
   cComments
     * The Laffer curve again!!!! This defies logic. How can any
       governmental entity (or leader) any where on this planet let alone
       in this country be suckered into adopting this thoroughly debunked
       snake oil economic theory. When Reagan implemented it in the 1980ʼs
       he drove the National Debt...
       Hobbsian Paradox
       at 11:21 AM July 10, 2014

   Add a comment See all comments
   159

   The record of Kansas since 2012 shows the folly of such draconian cuts
   in revenue. It's one thing to enact targeted cuts in tax rates during
   an economic upswing, when such a policy can add fuel to job generation.
   It's quite another to do so blindly during a slump, when cuts in state
   services undermine efforts at recovery.

   Brownback's tax policy came right out of the conservative playbook. His
   2012 package cut the top two personal income tax rates from 6.45% (on
   income over $60,000) and 6.25% (on income between $30,000 and $60,000)
   to 4.9%. The rate on income under $30,000 was pared to 3% from 3.5%.
   Pass-through business income was made fully tax-exempt. The law
   increased the standard deduction, but also eliminated several tax
   credits that assisted the poor.

   More tax changes were enacted last year. The top rate was cut to 3.9%
   in stages through 2018. But other cuts were reversed; much of a sales
   tax reduction was canceled, and the standard deduction was cut back,
   effectively raising taxes for the middle- and working-class.

   In all, as the CBPP documents, the changes will cut the taxes of the
   wealthiest 1% of Kansans by 2.2%. The poorest 20% of Kansans will see
   their taxes rise by 1.3%.

   The impact on overall state revenue has been devastating. Despite
   Laffer's prediction, the state ended fiscal 2014 with a shortfall of
   $338 million.

   Brownback continues to promise his citizens that growth is just around
   the corner. But there's no evidence that the kinds of cuts he promoted
   have anything to do with genuine economic growth. Indeed, it's likely
   that preserving the quality of crucial state services is more
   important. That's a policy pursued in California under Gov. Jerry
   Brown, who successfully pushed to raise taxes after the recession; the
   state's job growth since then has left Kansas and the country as a
   whole in the dust.

   "States considering deep tax cuts in hopes of sparking a surge of
   economic growth should look carefully at Kansas," the CBPP suggested in
   March. Yes, look carefully -- and run the other way.

   Keep up to date with The Economy Hub by following @hiltzikm.
   Copyright © 2014, Los Angeles Times
   Related Content
   BusinessBusinessPoliticsTaxationPersonal IncomeGovernmentProductivity
     * A fraud accusation like nothing youʼve seen before
       The Economy Hub
       A fraud accusation like nothing youʼve seen before
       It can be hard to keep up with the latest examples of fraud rings
       and other organized wrongdoing, but hereʼs one that takes the cake:
       the scientific monthly Journal of Vibration and Control is
       retracting 60 articles "implicated in a peer review and citation
       ring."
     * The right sharpens its knives for Social Security disability, again
       The Economy Hub
       The right sharpens its knives for Social Security disability, again
       As we all know, the official animal of Washington, D.C., is the
       scapegoat. Todayʼs example is Carolyn W. Colvin, the acting
       commissioner of Social Security.

     * Does America have the political maturity for single-payer
       healthcare?
       The Economy Hub
       Does America have the political maturity for single-payer
       healthcare?
       Responding to my post about how the Supreme Courtʼs Hobby Lobby
       ruling demonstrates the necessity of a single-payer healthcare
       system, Ezra Klein raises the specter of unrestrained political
       interference in healthcare decisions.
     * Farewell to the big-screen plasma TV
       The Economy Hub
       Farewell to the big-screen plasma TV
       Via Reuters comes the news that Samsung, one of the last major
       manufacturers of plasma TV screens, will shut down production by
       the end of November. Panasonic had already stopped making plasma
       panels, and South Koreaʼs LG will end production soon.
     * How did UnitedHealth let so many questionable claims slip past?
       The Economy Hub
       How did UnitedHealth let so many questionable claims slip past?
       Hereʼs how the nationʼs largest health insurance company aided and
       abetted what it says was a $43-million healthcare fraud.
     * How Bill Gross and Pimco got too big for each other
       The Economy Hub
       How Bill Gross and Pimco got too big for each other
       The instant reaction to the sudden departure of Pimcoʼs bond king,
       Bill Gross, for Janus Capital is that the move is a disaster for
       Pimco and a windfall for Janus.
     * Heritage Foundation: Americaʼs poor actually live pretty durn well!
       The Economy Hub
       Heritage Foundation: Americaʼs poor actually live pretty durn well!
       The Heritage Foundation has weighed in with its contribution to the
       enduring conservative effort to paint Americaʼs poor as undeserving
       mooks.
     * The jury in a mortgage case finally strikes back at fraudulent
       bankers
       The Economy Hub
       The jury in a mortgage case finally strikes back at fraudulent
       bankers
       Given the governmentʼs failure to bring criminal cases against
       bankers and other Wall Street figures for collapsing the U.S.
       economy in 2008, itʼs been left to the little guy to strike back.

   Comments
   Previous PostView the Blog
   Loading
     __________________________________________________________________
     __________________________________________________________________
     __________________________________________________________________

   á ____________________
   Member CenterPlace an Ad
   LocalSportsEntertainmentNationWorldBusinessOpinionLifestyleTravelAutosR
   eal EstateJobsPhotos & VideoGreat Reads CLASSIFIEDS SHOP ADVERTISING
   CORRECTIONS PRIVACY POLICY TERMS SITE MAP ABOUT US CONTACT US ©2014 LA
   Times

   SectionsLocalCrimeData &
   MapsEducationNeighborhoodsObituariesPoliticsTransportationWeatherPartne
   r SitesLocal+BlogsL.A. NowHomicide ReportPoliticalRobin AbcarianSoCal
   MomentsDon't Miss…
   Northern California fires may offer a grim preview for Southland
   Northern California fires may offer a grim preview for Southland
   CHP agrees to settle, officer resigns in beating case CHP agrees to
   settle, officer resigns in beating case
   SectionsSportsAngelsClippersDodgersHigh SchoolKingsLakersNFLNHL /
   DucksScores & StatsUCLAUSCMore sportsBlogsDodgers NowLakers NowSports
   NowUSC NowUCLA NowVarsity InsiderDon't Miss…
   Baseball awards picks: Clayton Kershaw, Mike Trout ... <i>not</i> TWC
   Baseball awards picks: Clayton Kershaw, Mike Trout ... not TWC
   Chivas USA's future is up in the air as league considers selling Chivas
   USA's future is up in the air as league considers selling
   SectionsEntertainmentArtsBooksCritics PicksMoviesMusicTelevisionThe
   EnvelopeEnt+BlogsCarolina A. MirandaCompany TownCulture
   MonsterGossipHero ComplexJacket CopyMovies NowPop & HissShow
   TrackerDon't Miss…
   The costumes are the stars of film academy exhibit The costumes are the
   stars of film academy exhibit
   FAA clears way for drones to be used on film sets FAA clears way for
   drones to be used on film sets
   SectionsNationObituariesPoliticsScienceBlogsNation NowPolitics
   NowScience NowDon't Miss…
   Despite slow, troubled start, Holder leaves mark at Justice Department
   Despite slow, troubled start, Holder leaves mark at Justice Department
   He's no longer a prisoner of the war on drugs He's no longer a prisoner
   of the war on drugs
   SectionsWorldAfghanistanAfricaAmericasAsiaEuropeMiddle EastDon't Miss…
   Ebola outbreak often leaves children alone and terrified Ebola outbreak
   often leaves children alone and terrified
   In Russia-held Crimea, some prosper, others fear for their future In
   Russia-held Crimea, some prosper, others fear for their future
   SectionsBusinessAutosJobsReal EstateBusiness+BlogsCompany TownHot
   PropertyMichael HiltzikTechnology NowDon't Miss…
   At CounterPunch Studios, actors' digital doubles come to life At
   CounterPunch Studios, actors' digital doubles come to life
   Mammoth Mountain owner buys Bear Mountain and Snow Summit Mammoth
   Mountain owner buys Bear Mountain and Snow Summit
   SectionsOpinionEditorialsEndorsementsOp-EdReaders ReactReaders
   RepBlogsDavid HorseyOpinion L.A.Don't Miss…
   How to rewrite the DMV test for real-life driving How to rewrite the
   DMV test for real-life driving
   Daniele Watts speaks up on why she didn't cooperate with LAPD Daniele
   Watts speaks up on why she didn't cooperate with LAPD
   SectionsLifestyleBooksComicsCrosswordFashionFoodGamesHealthHome &
   GardenHoroscopesRecipesSudokuHealth+Lifestyle+BlogsAll the RageDaily
   DishJacket Copy
   SectionsTravelCaliforniaEuropeHawaiiLas VegasMexicoAsiaTheme
   ParksTravel+BlogDeals & NewsDon't Miss…
   Lodrick M. Cook Rotunda a gem of the Los Angeles Central Library
   Lodrick M. Cook Rotunda a gem of the Los Angeles Central Library
   Daily Detour: Odd spots, strange trips, great moments in travel Daily
   Detour: Odd spots, strange trips, great moments in travel
   SectionsAutosReviewsPrint AdsSELL YOUR CARDon't Miss…
   Older Honda Accords, Civics continue to top most stolen car rankings
   Older Honda Accords, Civics continue to top most stolen car rankings
   2014 Pebble Beach: '54 Ferrari 375 MM wins Concours best of show award
   2014 Pebble Beach: '54 Ferrari 375 MM wins Concours best of show award
   SectionsReal EstateHome & GardenRentalsPrint AdsSELL YOUR HOMEBlogHot
   Property
   BlogsCompany TownHot PropertyMichael HiltzikTechnology NowDon't Miss…
   At CounterPunch Studios, actors' digital doubles come to life At
   CounterPunch Studios, actors' digital doubles come to life
   Mammoth Mountain owner buys Bear Mountain and Snow Summit Mammoth
   Mountain owner buys Bear Mountain and Snow Summit
   SectionsPhotos & VideoPhotosVideoBlogFrameworkDon't Miss…
   King fire in Eldorado National Forest King fire in Eldorado National
   Forest
   Celebrity portraits by The Times Celebrity portraits by The Times
   AutosJobsReal EstateRentalsLegal NoticesMiscellaneousPrint AdsPlace an
   Ad
   Local DealsTravel OffersLATimes StorePhoto StoreMarketplaceLocal
   ListingsSports GearDistrict West
   Media KitPlace an AdServicesAbout our Ads
   PortfolioExecutive
   TeamMastheadNewsroomPressEventsPermissionsArchivesCareersMedia KitTERMS
   News TipsSite FeedbackSubmit LetterReaders Rep
