   #alternate TechCrunch » Feed TechCrunch » Comments Feed TechCrunch »
   OpenSignal Nets $4M To Build Out Its Crowdsourced Mobile Sensor Data
   Maps Comments Feed Scytl Closes $104M To Step Up Growth Of Its
   Electronic Voting Platform CrunchBase Unleashes The Business Graph
   alternate alternate TechCrunch WordPress.com

   TechCrunch
   Got a tip? Let us know.
   Menu Search
     * News
          + Channels
          + Startups
          + Mobile
          + Gadgets
          + Enterprise
          + Social
          + Europe
          + Asia
          + CrunchGov

     * Trending

     * Tinder
     * NSA
     * Android
     * Google
     * Microsoft
     * Apple
     * Twitter
     * Facebook

   All Topics
   All Galleries

     TCTV

   Shows

     * TCTV News
     * CrunchWeek
     * Fly Or Die
     * Gadgets

     * Incubated
     * Inside Jobs
     * One Lap
     * TC Cribs

   All Shows

   All Videos

     Events

     * TechCrunch Events

     * Disrupt
     * Crunchies
     * Meetups
     * International City Events
     * Hackathon
     * Hardware Battlefield

     * News About

     * Google I/O 2014
     * CES
     * SXSW
     * WWDC 2014

   All Events

   Search TechCrunch

   Search TechCrunch ____________________ (BUTTON) Search

   CrunchBase

     * Follow Us
     * Facebook
     * Twitter
     * Google+
     * LinkedIn
     * Youtube
     * RSS
     * Email
     * More
          + LinkedIn
          + Youtube
          + RSS
          + Email

   Disrupt Europe 2 Weeks Left to Save £300 on Disrupt Europe Tickets -
   Register Now!
   AOL Privacy Policy and Terms of Service

   Apps
     * Enterprise App Marketplaces Respond To Pain Points In Corporate IT

Enterprise App Marketplaces Respond To Pain Points In Corporate IT
     * Kano Ships Its First 18,000 Learn-To-Code Computer Kits, Fueled By
       $1.5M Kickstarter

Kano Ships Its First 18,000 Learn-To-Code Computer Kits, Fueled By
$1.5M Kickstarter
     * Led By Pixar Alums, ToyTalk Launches Its First Paid Kids App,
       Begins To License Tech

Led By Pixar Alums, ToyTalk Launches Its First Paid Kids App, Begins To
License Tech
     *

Browse more...

   sensors
     * Notion’s Connected Sensors Aim To Serve You All Sorts Of
       Home Alerts

Notion’s Connected Sensors Aim To Serve You All Sorts Of Home Alerts
     * Sensors And Sensitivity

Sensors And Sensitivity
     * Robin, A Company Enabling Sensor-Powered Smart Offices, Raises
       $1.4 Million

Robin, A Company Enabling Sensor-Powered Smart Offices, Raises $1.4 Million
     *

Browse more...

   Qualcomm Ventures
     * After Catching Google’s Eye, Mantis Vision Bags $12.5M From
       Qualcomm, Samsung And Others For Its Mobile 3D

After Catching Google’s Eye, Mantis Vision Bags $12.5M From Qualcomm, Samsung
And Others For Its Mobile 3D
     * Crowdsourced WiFi Network Fon Picks Up $14M Led By Qualcomm, Adds
       Facebook Integration

Crowdsourced WiFi Network Fon Picks Up $14M Led By Qualcomm, Adds
Facebook Integration
     * Deck, A Cloud-Based Presentation App From India, Raises $600K From
       Qualcomm, Hotmail Co-Founder

Deck, A Cloud-Based Presentation App From India, Raises $600K From Qualcomm,
Hotmail Co-Founder
     *

Browse more...

   opensignal
     * Android Device Ecosystem: More Diverse Than Ever

Android Device Ecosystem: More Diverse Than Ever
     * Samsung’s Android Dominance Visualised By OpenSignal — Data Also
       Shows Droid Device Diversity Has Tripled In A Year

Samsung’s Android Dominance Visualised By OpenSignal — Data Also Shows Droid
Device Diversity Has Tripled In A Year
     * OpenSignal Launches WeatherSignal, Using Its Crowdsourcing Cell
       Phone Coverage Tech To Tackle Meteorology

OpenSignal Launches WeatherSignal, Using Its Crowdsourcing Cell Phone
Coverage Tech To Tackle Meteorology
     *

Browse more...

OpenSignal Nets $4M To Build Out Its Crowdsourced Mobile Sensor Data Maps

   Posted Aug 5, 2014 by Natasha Lomas (@riptari)
     *
     *
     *
     *
     * More
          + Add to Flipboard Magazine.
          +
          + submit to reddit
          +

   Next Story

Scytl Closes $104M To Step Up Growth Of Its Electronic Voting Platform

   [screen-shot-2014-08-05-at-12-33-22-pm.png?w=738]

   Crowdsourced mobile signal mapper OpenSignal has closed a $4 million
   Series A funding round, led by chipmaker Qualcomm via its investment
   arm, Qualcomm Ventures. Prior investors O’Reilly AlphaTech Ventures and
   Passion Capital also participated in the round.

   The UK startup previously raised a $1.3million seed round led by
   O’Reilly AlphaTech Ventures, back in 2012.

   OpenSignal’s premise focuses on offering independent/unbiased — and
   likely more accurate — signal maps (vs carriers self reporting their
   coverage) by encouraging smartphone users to download and run its
   signal-checking software on their devices.

   CEO Brendan Gill tells TechCrunch it’s now had more than nine million
   people download its app globally. “This boils down to over 35 billion
   data points on the coverage and performance of wireless networks.  We
   have data on every single mobile operator in every country out there.
   We’ve also mapped over 250 million WiFi hotspots as well,” he says.

   Gill says the OpenSignal maps are now comprehensive enough to enable it
   to determine the best carrier in “pretty much any metropolitan area in
   the world outside of some parts of the Middle East & Africa (although
   both of those areas are growing very fast for us)”.

   “In the larger metropolitan areas e.g. New York, London, we can drill
   down to neighborhood level. However, there is still much to be gained
   by increasing our user-base as we’ll be able to drill down to ever
   increasing levels of granularity,” he adds.

   OpenSignal’s business model involves providing intel on the consumer
   experience on mobile and wireless networks to a range of paying
   customers — including carriers, web companies, consultancy firms, hedge
   funds and telecoms regulators.

   “In the year since we started commercial operations we’ve signed up
   over 20 paying customers around the world (spanning all five
   continents) including Telefonica, China Mobile and Deloitte,” says
   Gill.

   OpenSignal says it will be using the new funding for building out its
   team — with a focus on hiring data specialists in a range of areas
   — from individuals with expertise in data mining and locating hidden
   correlations, to people who can tell stories using data visualization,
   to data engineers who can build scalable pipelines for handling large
   volumes of data.

   The future for OpenSignal is evidently going to be about expanding the
   type of crowdsourced data it captures — fueled by the increasing
   numbers of sensors being embedded into mobile devices (or linked to
   mobile devices via Bluetooth connectivity).

   It has already started this expansion, launching a meteorology app
   called WeatherSignal in May last year — which it dubbed a “side
   project” at the time.

   The network drew on mobile sensor data from the likes of light meters
   and barometers, but also expanded the amount of data feeding its
   meteorology mapping after stumbling on a correlation between battery
   temperature and the ambient temperature around a particular device. So
   basically turning something that wasn’t intended to be a weather sensor
   into a weather-related data-set by applying an algorithm that could
   unpick the correlation between battery temperature and outdoor climate.

   Since WeatherSignal launched, the quantity of connected sensors in and
   around mobile devices has continued to proliferate — meaning there is
   huge potential for expanding the types of maps that can be created in
   the future using a crowdsourced OpenSignal-esque approach.

   “We are only scratching the surface of the insight that can be drawn
   from wireless sensors, with OpenSignal, and from weather related
   sensors, with our sister project WeatherSignal and we won’t be reducing
   the focus on either of those in the near future,” says Gill.

   Two areas of particular interest to OpenSignal are Bluetooth Low Energy
   beacons, and air quality sensors, according to Gill.

   “There’s no doubt that there will be an explosion in the rise of BLE
   beacons (including iBeacons) in the coming years and we have an
   opportunity to crowdsource a reference database of these,” he says,
   pointing out that the level of location granularity supported by
   mapping BLE beacons offers huge potential to map dynamic context.

   “BLE beacons could know your context right down to something as
   specific as ‘in isle 6 of the supermarket looking at the vegetarian
   dishes’.  So we consider crowdsourcing a reference database of BLE
   sensors as equivalent to crowdsourcing a reference database of context
   for the world, which is a very powerful opportunity,” he adds.

   On the air quality sensor front, Gill says that’s interesting to
   OpenSignal because mobile makers are working on embedding these sensors
   into devices. The size of the data-set that could be built using
   OpenSignal’s crowdsourced approach could yield applications for civic
   planning scenarios.

   “As we’ve seen with other companies like Waze there is a huge
   opportunity to tap into the sensors that people are carrying around in
   their pockets to understand the flow and conditions of the cities we
   live in.  We believe that tapping into these crowdsourced sensor
   networks will be instrumental in building the smart cities of the
   future,” he adds.
     *
     *
     *
     *
     *
     * submit to reddit

   Advertisement

   Advertisement

CrunchBase

     * OpenSignal
          + Founded 2010
          +
          + Overview OpenSignal provides mobile operators with unrivalled
            insight into the customer experience on their networks based
            on a crowdsourced panel of over 5 million users of the
            OpenSignal mobile app. No approximations; no statistical
            models; OpenSignal provides operators with a direct window
            into the end-to-end user experience. OpenSignal tracks
            performance across all operators in a market so every KPI is …
          + Location Laguna Hills, California
          + Categories Maps, Wireless, Mobile
          + Founders Brendan Gill, Sina Khanifar, James Robinson, Sam
            Westwood
          + Website http://opensignal.com
          + Full profile for OpenSignal
     * Qualcomm Ventures
          + Founded 2000
          +
          + Overview Qualcomm Ventures (QCV) was formed and began funding
            in 2000, with a $500-million fund commitment to make strategic
            investments in early-stage high-technology ventures. Since
            then, QCV has funded numerous companies in the wireless
            sector, and set up several exclusive regional funds to spur
            development in key strategic markets, including a $60-million
            fund in Korea, a $30-million fund in Japan, a $100-million …
          + Location San Diego, California
          + Website https://qualcommventures.com/
          + Full profile for Qualcomm Ventures

TechCrunch Daily

   Latest headlines delivered to you daily

   Subscribe to TechCrunch Daily

   Enter Email Address ____________________ (BUTTON) Subscribe

Related Videos

     * Gillmor Gang: Five Card Stud
       Play Video
    Gillmor Gang: Five Card Stud
       1:14:47
     * Ello, Apple's Problems And Startups
       Play Video
    Ello, Apple’s Problems And Startups
     * Stella Solar Powered Car
       Play Video
    Stella Solar Powered Car

   More Related Videos
     * sensors
     * Qualcomm Ventures
     * opensignal
     * Apps
     * Popular Posts

   Up Next

Scytl Closes $104M To Step Up Growth Of Its Electronic Voting Platform

   Posted Aug 5, 2014

CrunchBoard

Job Listings

     *

Enterprise Database Manager
       Foundation Center
     *

Programmer
       Foundation Center
     *

Manager/Director of User Growth
       Figure 1
     *

Software Engineer, Search Engine Optimization
       PayScale
     *

Program Manager, Search Engine Optimization
       Payscale

   More from CrunchBoard

   Advertisement

TechCrunch

[crunch-network.jpg?m=1410805882g]

     * News
     * TCTV
     * Events
     * CrunchBase

About

     * Staff
     * Contact Us
     * Advertise With Us
     * Send Us A Tip

International

     * China
     * Europe
     * Japan

Follow TechCrunch

     * Facebook
     * Twitter
     * Google+
     * LinkedIn
     * Youtube
     * Pinterest
     * Tumblr
     * Instagram
     * StumbleUpon
     * Feed

TechCrunch Apps

     * iOS
     * Android
     * Windows 8

Subscribe to TechCrunch Daily

   Latest headlines delivered to you daily

   Subscribe to <span class="no-mobile">Subscribe to </span>TechCrunch
   Daily

   Enter Email Address ____________________ (BUTTON) Subscribe

   © 2013-2014 AOL Inc. All rights reserved. Aol Tech Privacy Policy About
   Our Ads Anti Harassment Policy Terms of Service
   Powered by WordPress.com VIP
   Fonts by <Webtype>

   [b?c1=2&c2=6036210&c3=&c4=&c5=&c6=&c15=&cv=1.3&cj=1]
   [lb?site=695501&srvc=1&betr=22708=580803[720]]

   Follow

Follow “TechCrunch”

   Get every new post delivered to your Inbox.

   Join 93,047 other followers

   Enter your email add

   Sign me up
   Powered by WordPress.com
