   #publisher Breaking Science News | Sci-News.com » Feed Breaking Science
   News | Sci-News.com » Comments Feed Breaking Science News |
   Sci-News.com » Asian Elephants Reassure Others in Distress, Study Finds
   Comments Feed

     * Home
     * About Us
     * News Archive
     * Copyright
     * Privacy Policy
     * Contact Us
     * Newsletter
     * RSS

     * twitter
     * gplus
     * facebook

   Top Headlines:
     * New Ankylosaur Discovered in New Mexico
     * 39,000-Year-Old Neanderthal Engraving Found in Gorham’s Cave
     * Bahian Mouse-Colored Tapaculo: New Bird Species Discovered in
       Brazil
     * Rhinorex condrupus: New Herbivorous Dinosaur Discovered in Utah
     * Europeans Descended from 3 Groups of Ancient Humans, Study Reveals
     * Cell-Like Structure Found within 1.3-Billion-Year-Old Martian
       Meteorite
     * Jethro Cairn: 5,000-Year-Old Stone Monument Discovered in Israel

   ____________________ Submit
     * Home
     * Astronomy
     * Space Exploration
     * Archaeology
     * Paleontology
     * Biology
     * Physics
     * Medicine
     * Genetics
     * Geology
     * More
          + Anthropology
          + Biochemistry
          + Chemistry
          + Geography
          + Geophysics
          + Linguistics
          + Mathematics
          + Nanotechnologies
          + Paleoclimatology
          + Psychology
          + Technologies

Asian Elephants Reassure Others in Distress, Study Finds

   Feb 19, 2014 by Sci-News.com
   « PREVIOUS
   |
   NEXT »

   A study led by Dr Joshua Plotnik from Mahidol University and the Think
   Elephants International has found that Asian elephants (Elephas
   maximus) console others who are in distress, using physical touches and
   vocalizations.
   Asian elephants get distressed when they see others in distress,
   reaching out to calm them down. Image credit: E. Gilchrist / the Golden
   Triangle Asian Elephant Foundation.

   Asian elephants get distressed when they see others in distress,
   reaching out to calm them down. Image credit: E. Gilchrist / the Golden
   Triangle Asian Elephant Foundation.

   “For centuries, people have observed that elephants seem to be highly
   intelligent and empathic animals, but as scientists we need to actually
   test it,” said Dr Plotnik, who is the first author of a paper published
   in the open-access journal PeerJ.

   Consolation behavior is rare in the animal kingdom, with empirical
   evidence previously provided only for the great apes, canines and
   certain corvids.

   “With their strong social bonds, it’s not surprising that elephants
   show concern for others. This study demonstrates that elephants get
   distressed when they see others in distress, reaching out to calm them
   down, not unlike the way chimpanzees or humans embrace someone who is
   upset,” said second author Dr Frans de Waal from Emory University.

   For nearly a year, Dr Plotnik and his colleague studied a group of 26
   captive Asian elephants at a camp in northern Thailand. They observed
   and recorded incidences when an elephant displayed a stress reaction,
   and the responses from other nearby elephants.

   The initial stress responses came from either unobservable, or obvious,
   stimuli: events such as a dog walking past, a snake or other
   potentially dangerous animal rustling the grass, or the presence of
   another, unfriendly elephant.

   “When an elephant gets spooked, its ears go out, its tail stands erect
   or curls out, and it may emit a low-frequency rumble, trumpet and roar
   to signal its distress,” Dr Plotnik explained.

   The scientists found that nearby elephants affiliated significantly
   more with a distressed individual through directed, physical contact
   following a stress event than during control periods. As a typical
   example, a nearby elephant would go to the side of the distressed
   animal and use its trunk to gently touch its face, or put its trunk in
   the other animal’s mouth.

   The gesture of putting their trunks in each other’s mouths is almost
   like an elephant handshake or hug.

   “It’s a very vulnerable position to put yourself in, because you could
   get bitten. It may be sending a signal of, ‘I’m here to help you, not
   hurt you,” Dr Plotnik said.

   The responding elephants also showed a tendency to vocalize.

   IFRAME: //player.vimeo.com/video/87084592?byline=0&portrait=0

   “The vocalization I heard most often following a distress event was a
   high, chirping sound. I’ve never heard that vocalization when elephants
   are alone. It may be a signal like, ‘Shshhh, it’s okay,’ the sort of
   sounds a human adult might make to reassure a baby,” Dr Plotnik said.

   In addition, elephants frequently responded to the distress signals of
   other elephants by adopting a similar body or emotional state, a
   phenomenon known as “emotional contagion,” which may be related to
   empathy. Groups of nearby elephants also were more likely to bunch
   together, or make physical contact with each other.

   Reconciliation behaviors have been demonstrated in many more species
   than those that have shown the capacity for consolation.

   “One hypothesis for why we don’t see consolation as often is that more
   complex cognition may underlie it. Rather than just functioning as a
   way to maintain or repair relationships in a social group, consolation
   may also require empathy: The ability to put yourself emotionally into
   someone else’s shoes,” Dr Plotnik said.

   The current elephant study’s limitations include the fact that it was
   restricted to captive animals.

   “This study is a first step,”” Dr Plotnik said.

   ______

   Plotnik JM, de Waal FB. 2014. Asian elephants (Elephas maximus)
   reassure others in distress. PeerJ 2: e278; doi: 10.7717/peerj.278
   Published in
     * Biology

   Tagged as
   Asian elephantElephant
   Follow
   Share
   You Might Like
   The Emerald rockcod (Trematomus bernacchii) is a common notothenioid
   species. Image credit: Zureks / CC BY-SA 3.0.

Ice Crystals inside Antarctic Fishes May Never Melt

   The Bahian Mouse-colored Tapaculo (Scytalopus gonzagai), an adult male
   at Boa Nova, Bahia. Image credit: © Ciro Albano.

Bahian Mouse-Colored Tapaculo: New Bird Species Discovered in Brazil

   Specimens of Dendrogramma enigmatica and Dendrogramma discoides (with
   *). Image credit: Just J et al.

Dendrogramma: Two Unclassifiable Deep-Sea Animals Discovered off Australia

   Banded archerfish (Toxotes jaculatrix) jetting water at an insect.
   Image credit: Ingo Rischawy / Schuster lab / University of Bayreuth.

Excellent Sharpshooting Skills of Archerfish Amaze Ichthyologists

   Greenhouse camel cricket, Diestrammena asynamora. Image credit: ©
   Andrew Blanchard.

Asian Cricket Invades Eastern United States, Study Finds

   The Aquitanian pike (Esox aquitanicus), holotype specimen. Image
   credit: G.P.J. Denys et al.

Aquitanian Pike: New Fish Species Discovered in France

   The Senegal bichir, Polypterus senegalus. Image credit: © Cam Gillman,
   via cichlids.com.

‘Walking’ African Fish Holds Clues to Terrestrialization of Vertebrates

   [INS: :INS]
   [INS: :INS]
   Latest News
   This image shows stone tools found at the site of Nor Geghi, Armenia:
   top - biface tool; bottom - a Levallois core. Image credit: © Dan
   Adler.

Stone Tool Discovery in Armenia Gives Insight into Human Innovation 325,000
Years Ago

   Sep 27, 2014 | Anthropology
   Space-filling representation of the Star of David catenane. Image
   credit: David A. Leigh et al.

Star of David Molecule Created

   Sep 26, 2014 | Chemistry
   Family tree of coelurosaurian theropods and birds. Image credit:
   Stephen L. Brusatte et al.

Family Tree Sheds More Light on Transition from Dinosaurs to Birds

   Sep 26, 2014 | Paleontology
   This new global geologic map of Mars depicts the most thorough
   representation of the planet’s surface; colors show distribution of 44
   map units; for example, greens represent mainly lowland and basin
   units; yellow is relatively young impact material; reds and purples are
   volcanic units; blues are polar units; and earth tones are apron,
   transition, and highland units. Image credit: Tanaka, K.L. et al.

Scientists Create New Geologic Map of Mars

   Sep 26, 2014 | Space Exploration
   An illustration of water in our Solar System through time from before
   the formation of the Sun through the creation of the planets. Image
   credit: Bill Saxton / NSF / AUI / NRAO.

Half of Water on Earth Older than Sun, Scientists Say

   Sep 26, 2014 | Space Exploration
   The Imaging Ultraviolet Spectrograph (IUVS) instrument aboard MAVEN
   obtained these images just 8 hours after arrival. Image credit: NASA /
   Laboratory for Atmospheric and Space Physics / University of Colorado.

MAVEN Takes its First Images of Mars

   Sep 25, 2014 | Space Exploration
   This Megasphaera fossil displays unexpected evidence of complexity:
   arrow marks a matryoshka and arrowhead denotes dyads. Scale bar - 100
   μm. Image credit: Lei Chen et al.

Paleontologists Find 600-Million-Year-Old Microfossils of Complex
Multicellular Organisms

   Sep 25, 2014 | Paleontology
   Life restoration of Ziapelta sanjuanensis. Image credit: © Sydney Mohr.

New Ankylosaur Discovered in New Mexico

   Sep 25, 2014 | Paleontology
   Comparison of HAT-P-11b with Neptune. Image credit: Aldaron / CC BY-SA
   3.0

Water Vapor Detected on Neptune-sized Exoplanet HAT-P-11b

   Sep 24, 2014 | Astronomy
   Neanderthal engraving from Gorham's Cave, Gibraltar. Image credit:
   Joaquín Rodríguez-Vidal et al.

39,000-Year-Old Neanderthal Engraving Found in Gorham’s Cave

   Sep 24, 2014 | Archaeology
   The Emerald rockcod (Trematomus bernacchii) is a common notothenioid
   species. Image credit: Zureks / CC BY-SA 3.0.

Ice Crystals inside Antarctic Fishes May Never Melt

   Sep 23, 2014 | Biology
   Combinatorial and modular genetic strategy for engineering
   self-assembling underwater adhesives; abbreviations: Mfps - mussel foot
   proteins (Mfp3 and Mfp5 - major mussel adhesive foot proteins, have
   unstructured coil structures in solution and are critical to the
   underwater interfacial adhesion of mussels); CsgA - an amyloidogenic
   protein that is the major subunit of adhesive curli ﬁber in Escherichia
   coli (contains five stacked strand–loop–strand motifs mediated by
   conserved residues and can self-assemble into nanofibers via a
   rate-limiting nucleation step followed by fibril extension). Image
   credit: Chao Zhong et al.

Mussel-Inspired Waterproof Adhesives Could Help Heal Wounds, Repair Ships

   Sep 23, 2014 | Materials Science
   [INS: :INS]
     * Home
     * About Us
     * News Archive
     * Copyright
     * Privacy Policy
     * Newsletter
     * RSS
     * Contact Us

   © 2011-2014. Sci-News.com. All Rights Reserved. | Back to top
