   Skip to main content

   The Fiscal Times
   Free Newsletter
   Opinion

Search form

   Search _______________
   Search
     * Home
     * Opinion
     * Photos
     * Policy + Politics
          + Big Decisions
               o America at War
               o Government Shutdown
               o Government Waste
               o Debt Ceiling
               o Defense
               o Obamacare
          + Elections
               o 2016 Elections
               o 2014 Elections
          + People
     * Business + Economy
          + Sectors + Companies
          + US Economy
          + Global Economy
     * Life + Money
          + Learning Economics
          + Career Economics
          + Personal Economics
               o Retirement
     * TFT•wire

   You are here:
     * Home >
     * Columns >
     * Health Care Savings to Come From Unlikely Places

   Health Care Savings to Come From Unlikely Places
   Tim Boyle/Getty Images
   Printer-friendly version PDF version
   a a

   Type Size: Small

   IFRAME:
   //www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.thefiscaltime
   s.com%2FColumns%2F2014%2F03%2F02%2FHealth-Care-Savings-Come-Unlikely-Pl
   aces&layout=standard&show_faces=true&width=450&font=arial&height=30&act
   ion=like&colorscheme=light&locale=en_US&send=false

   By John F. Wasik,
   The Fiscal Times
   March 2, 2014

   Let's say that the U.S. health care industry really is embarking upon a
   major wave of innovation and cost cutting. Where would you expect that
   most of those savings occur? In hospitals? Clinics? Outpatient centers?

   The best bet might be in so-called "non-traditional" settings — perhaps
   even your local drug store.

   Much of the nascent movement to push health care outside of hospitals
   and clinics isn't being driven by the industry. It's an outgrowth of
   the formation of Medicare Accountable Care Organizations (ACOs), an
   obscure part of Obamacare that seeks to reward organizations for
   efficiency and high-quality care.

   The premise is simple: Create new health care organizations that
   promote quality care at a lower cost. Savings will be split between the
   providers and Medicare. According to the National Institutes of Health,
   some 55 percent of the U.S. population lives within an area served by
   227 ACOs. These groups can be organized by doctors or hospitals.

   A recent study by three researchers with the Dartmouth Institute for
   Health Policy and Clinical Practice found that there are early signs
   that ACOs are "driving innovation in the marketplace." For example, one
   way of lowering costs is to simply move treatment and health monitoring
   out of a hospital or clinic. The Dartmouth researchers cited an example
   where a "high touch care management system" run by Beth Israel
   Deaconess Care Organization used nurse practitioners to visit its
   sickest patients at home. That strategy is designed to reduce hospital
   readmissions.

   Other forms of non-traditional health care are available in retail
   pharmacies like CVS and Walgreens. The latter pharmacy chain has just
   launched three ACOs to provide low-cost care. In an indirect move
   designed to boost its share and re-orient its business model around
   in-store clinics, CVS recently announced that it will stop selling
   cigarettes and focus more on its 750 "MinuteClinics."

   The bigger trend is pushing traditional pharmacy chains deeper into
   primary care. Although they have long offered advice on prescriptions
   and flu shots, they are offering a broader array of services. According
   to The Washington Post:

   With 750 MinuteClinics, CVS has the country's largest chain of
   pharmacy-based health clinics. The clinics have allowed the company to
   pursue contracts with hospitals and health plans, often to provide
   primary care services weekends and evenings, when doctors' offices tend
   to be closed. CVS Chief Medical Officer Troyen A. Brennan estimates
   that the company has 30 to 40 partnerships with health-care systems
   across the country and is in talks with a similar number about starting
   arrangements.

   The Larger Trend
   Fueled by ACOs, will non-traditional health care providers make an
   inroad into the most basic level of care? They've already gained a
   following due to their "first come, first served" approach. Although
   they clearly gain additional revenue from prescriptions,
   over-the-counter and other retail sales, they are convenient, open
   weekends and generally accessible.

   Clinics at both Walgreens and CVS have become first-line primary care
   stops for my family. They are generally thorough and easy to visit when
   our family doctor's office is closed. They charge a flat fee ($89 in
   our area), which is roughly what our primary care physician would
   charge us after an insurance discount.

   Although in-store clinics are no substitute for emergency rooms for
   acute care situations, they are at least competitive. More research is
   needed, though, to see if their lack of diagnostics — you can't get a
   CT-scan or MRI at a pharmacy — will play a factor in reducing the
   overall cost of primary care.

   More importantly, will non-traditional models curb rising health care
   insurance costs, an issue that Obamacare does not fully address? Of
   special concern is what small business employers pay for health
   insurance. According to a new report by the Centers for Medicare and
   Medicaid Services, some 11 million workers may face higher premiums due
   to the ACA.

   There's also a concern that technology may continue to inflate costs.
   While tech will also play a part in reducing costs — perhaps through
   electronic medical records — providers that have invested heavily in
   new diagnostic and treatment tools will want to use them as much as
   they can, which could raise costs over time.

   At present, there are more incentives to overuse technology in testing
   and procedures than there are to employ low-cost primary care.  As
   David Carr observes at InformationWeek HealthCare:

   Reformers refer to these as "perverse incentives" that drive
   overutilization, resulting in episodic "sick care" rather than a
   systematic effort to improve people's health. If what we want instead
   is a healthcare system that makes people healthier at a reasonable
   price, the incentives should reward preventive care that reduces the
   need for those visits, admissions, and surgeries.

   In the accountable care model, critics of the fee-for-service system
   claim, most roads to cost saving lead back to strong, primary care to
   head off the costly implications of unmanaged chronic diseases and
   hospitalizations.

   Not every ACO-based model will thrive, however. Many institutions, with
   large fixed costs, will find it difficult to depart from the old,
   fee-for-service model where compensation is based on the number of
   tests, treatments and procedures — and not overall health outcomes.

   Nevertheless, where this care is provided is important. If it's in the
   home or a retail store, medicine might move away from an expensive
   focus on institutional diagnostics and treatments and concentrate on a
   more fundamental approach to care. This "back to the basics" model
   might be the most powerful idea in lowering costs over the long term.

   Top Reads From The Fiscal Times:
     * Why Tax Preparers May Be Obamacare's Biggest Boosters
     * Chris Christie’s Biggest Problem Isn’t ‘Bridgegate’
     * GOP Obamacare Fix Kicks One Million Off Private Insurance

   John F. Wasik
   Journalist and speaker John F. Wasik has written 14 books on subjects
   that range from wealth to ecology to retirement. He writes for Reuters
   and contributes to Forbes, The New York Times and other publications.
   Post a Comment
     __________________________________________________________________

   View the discussion thread.

Get Our FREE Newsletter

   Newsletter
   Email Address * _________________________
   Save
   More

Top-Grossing Broadway Musicals

   1) The Lion King
   Click to View Slideshow

On Our Radar

   1) The Lion King
   The 10 Top-Grossing Broadway MusicalsRead more
   Obama’s ISIS Strategy Is His Jimmy Carter MomentRead more
   Eric Holder’s Shameful Legacy on Wall Street FraudRead more
   Khorasan: 8 Things You Never Knew About KhorasanRead more

Sign up to get our Free Newsletters!

   Newsletter
   Email Address * _________________________
   Save

Connect to The Fiscal Times

     * Newsletter
     * Facebook
     * Twitter
     * Google+
     * RSS

   [p?c1=2&c2=14117530&cv=2.0&cj=1]
   Quantcast

   You are here: Health Care Savings to Come From Unlikely Places
     * Home
     * Opinion
     * Photos
     * Policy + Politics
     * Business + Economy
     * Life + Money
     * TFT•wire

     * About Us
     * Contact Us
     * Media Kit
     * Privacy Policy
     * Terms of Use

   The Source For All Things Fiscal
   © 2009-2014 The Fiscal Times. All rights reserved.
