   #RSS

   [logo-bi-print.png]

     * Featured
     * Trending
     * Recent

   Business Insider
     * Login

            ____________________ ____________________ [ ] Remember me
            Login I forgot username or password
              _________________________________________________________

            Login with Twitter Login with Facebook Login with LinkedIn
            Login with Google

          Register
               o
               o
               o
               o
               o Events
               o BI Intelligence
            ____________________ (BUTTON)
               o Tech
               o Finance
               o Politics
               o Strategy
               o Life
               o Entertainment
               o All
            Continue to Business Insider »
            You will be redirected in seconds.
            (BUTTON) ×

            From
            ____________________
            To
            ____________________
            Send
            You have successfully emailed the post.
            Politics More: Slate AirBnB Uber

Here's The Real Reason Governments Are Cracking Down On Uber And Airbnb
            Slate
               o Zachary Karabell, Slate
               o Apr. 28, 2014, 6:55 PM
               o 36,092
               o 28
               o facebook
               o linkedin
               o twitter
               o google+
               o print
               o email
               o
               o
               o
               o
               o print
               o email
               o share
               o share
               o tweet
               o share
               o print
               o email
               o Share on Facebook
               o Share on Twitter
               o Share on Linkedin
               o share
               o print
               o email
        Travis Kalanick Uber Limo Driver_04 Mike Nudelman/Business Insider
            It hasn’t been a great week for Airbnb. On Tuesday
            representatives of New York State Attorney General Eric
            Schneiderman and lawyers for the apartment sublet company
            Airbnb
            met in an Albany court. At issue is a broad subpoena issued by
            the New York AG last fall, demanding that Airbnb turn over
            information about its “hosts” (those who list their
            apartments) in the belief that thousands of them are in
            violation of the law by acting as de facto unregistered
            hotels.
            Airbnb has challenged the subpoena on the grounds that it
            constitutes an invasion of privacy of the thousands of people
            who use its service. Then, on Wednesday, the San Francisco
            city attorney brought suit against two local landlords,
            alleging that they illegally evicted residents in order to
            convert residential housing into short-term rentals advertised
            on Airbnb and similar services.
            The San Francisco case in particular appears to have
            considerable merit. (According to the City Attorney’s Office,
            two of the evicted residents were disabled, while the
            Airbnb-ization of the city’s already painfully squeezed
            housing market is troubling at best.) A larger issue to be
            considered, however, is that Airbnb is part of a wave of
            companies whose business model is inherently disruptive both
            of existing industries and existing laws. Those industries and
            many regulators are challenging these new business models, and
            the outcome is critical to the future arc of our entire
            economy.
            Airbnb is part of a suite of new companies—among them Uber
            (which Schneiderman is also investigating for alleged
            price-gouging), Aereo (in the news this week because of a
            pending Supreme Court case), HomeAway, and Lyft—that are
            frequently described as constituting the “sharing economy.”
            It’s a poor term at best. None of what these companies do is
            “shared,” because nothing is free; everyone is in it to make
            some money.
            What is notable about these models, however, is that they
            provide technology allowing users and buyers to transact
            without mediation by the powers that have traditionally
            controlled those transactions. So Airbnb matches those with
            rooms to those seeking to rent rooms; Uber matches cars and
            drivers with those seeking to hire cars and drivers; and so
            on. In a sense, Bitcoin serves a similar function, providing a
            direct means of exchange for any set of buyers and sellers
            anywhere in the world, with clear pricing and no involvement
            by banks or payment companies.
            At stake are hundreds of billions of dollars of revenue (which
            will not be “shared”). Incumbents are attempting to protect
            that revenue using the legal system. As we all know, laws are
            not simply the manifestation of societal norms of justice and
            a need to protect and serve the common good. They can also be
            tools crafted in the interest of established groups and
            businesses to further their needs and inhibit those of others.
            Regulations used to protect and steer the common good are
            essential, but laws used to stifle innovation are deadly.
            Until recently, however, the U.S. has mostly steered away from
            the worst effects of laws and regulations used to kill
            innovation and new business models. Yes, the Big Three car
            cartels in Detroit managed to make it nearly impossible for
            any competitors to manufacture cars for much of the
            20th century. Their implosion in the 2000s created an opening
            for Tesla. Yet now states such as New Jersey are responding to
            the complaints of car dealers and attempting to shut
            down Tesla’s direct-to-consumer sales model—which is another
            variant of cutting out the middleman. Taxi and limousine
            commissions have taken to courts to fight Uber, and a similar
            surge is happening with Airbnb. (Perhaps a more positive sign
            was that rather than litigating against Zipcar, which offered
            peer-to-peer car rental, Avis simply bought it in 2013.)
            It’s comforting to imagine that, in the end, the power of
            innovative technologies and business models will win out over
            status-quo thinking and entrenched interests, all for the
            public good. In the late 1990s, the established music industry
            viewed digital music as a proximate threat, pursued
            file-sharing innovator Napster with a vengeance, and won in
            court. It won that battle, only to see digitization overwhelm
            its distribution model anyway. Further disruption occurred
            when the iTunes-driven ecosystem of today upended the
            brick-and-mortar stores selling albums and CDs. That ruined
            several chains, but enriched Apple and the lives of hundreds
            of millions of users.
            For a more troubling precedent, we could look to what happened
            in India in the 20thcentury. After its independence from Great
            Britain in 1947, the Indian economy was known as the “License
            Raj,” denoting a web of rules and regulations that required
            anyone attempting to open a business or do something new to
            navigate an endless gauntlet of permits and permissions from
            multiple government agencies. This system was seen as a
            primary cause of almost nonexistent growth in this crucial
            historical period.
            Just as India is fleeing as quickly as possible from its
            License Raj, however, the U.S. is showing signs of
            constructing one. Established companies, aware of the
            precariousness of their franchises, are determined to maintain
            their position. They use the tools of regulation and
            litigation as a powerful bludgeon—the Tesla debacle in New
            Jersey is a particular lowlight.
            These rearguard actions assume a zero-sum economy where every
            gain for innovative entrants is a loss for incumbents. That
            may be true in some cases, but it is hardly a given. Certainly
            with music and video, peer-to-peer has led to an explosive
            growth in usage rather than new entrants carving up a finite
            pie. It’s too soon to tell whether Uber will actually decimate
            the taxi industry, but in New York City, medallion sales are
            hitting record highs even with the onslaught of Uber—an early
            indication that Uber may simply lead to more people using car
            services, not fewer people taking taxis.
            The only way that new models will avoid the snare of old-guard
            companies and ill-considered laws is for regulations and laws
            to adapt to new technologies and new business models, rather
            than be used as tools to inhibit them. Instead of
            indiscriminately challenging the Ubers and Airbnbs of the
            world, regulators should be guided by what is in the public
            interest. If Airbnb hosts are in fact illegally evicting
            disabled residents from their homes in San Francisco,
            authorities should hit back hard. But if new companies are
            simply creating models that provide more access to rides, more
            ease of facilitating travel and tourism, more ways of buying
            cars—all of which indisputably boost local economies—then our
            regulatory and legal system should embrace them, not impede
            them. The surest way to create a zero-sum world is prevent the
            efflorescence of models that unlock ever more economic
            activity. These upstarts are only the enemy of old industries
            if those industries fail to evolve.


More from Slate:

     * The 10,000 Hour Rule Is Wrong and Perpetuates a Cruel Myth
     * Last Night’s Premiere Was the Best SNL Episode in a While. Here Are
       the Best Parts.
     * Americans Have No Idea How Bad Inequality Really Is
     * How One Guy in Oregon Made the Best U.S. Map You’ll Ever See
     * Japanese Volcano Eruption Caught on Video… VERY Up Close and
       Personal

   This article originally appeared at Slate. Copyright 2014. Follow Slate
   on Twitter.

     * facebook
     * linkedin
     * twitter
     * google+
     * email

     *
     *
     *
     *
     * email

     * share
     * share
     * tweet
     * share
     * email

     * Share on Facebook
     * Share on Twitter
     * Share on Linkedin
     * Share on Google Plus
     * email

Recommended For You

     *
     *
     *
     *
     *

Comments

   Comments on this post are now closed.
     * Insiders 2
     * All Comments 28
       Apply To Be An "Insider" »

   Loading Loading

Here's The Real Reason Governments Are Cracking Down On Uber And Airbnb

   Here's The Real Reason Governments Are Cracking Down On Uber And Airbnb
   [heres-the-real-reason-governments-are-cracking-down-on-uber-and-airbnb
   .jpg]

   It hasn’t been a great week for Airbnb....

Get Politics Emails & Alerts

   ____________________ (BUTTON) Sign-Up
   Learn More »
     * [X] Politics Select

   More
   Featured
     * [ ] Business Insider Select
     * [ ] Tech Select
     * [ ] Tech Chart Of The Day
     * [ ] Markets Chart Of The Day
     * [ ] 10 Things Before the Opening Bell
     * [ ] Instant MBA
     * [ ] Breaking News
     * [ ] Business Insider Events

   Entertainment
     * [ ] Entertainment Select
     * [ ] Sports Select

   Finance
     * [ ] Finance Select
     * [ ] Markets Select
     * [ ] Monday Scouting Report
     * [ ] Your Money Select
     * [ ] Financial Advisor Insights
     * [ ] Smart Investor

   Strategy
     * [ ] Strategy Select
     * [ ] Advertising Select
     * [ ] Retail Select
     * [ ] Careers Select
     * [ ] Marketing Mondays
     * [ ] Advertising: The Brief

   Politics
     * [X] Politics Select
     * [ ] Military Select
     * [ ] Law & Order Select

   Life
     * [ ] Life Select
     * [ ] Transportation Select
     * [ ] Education Select

   Tech
     * [ ] Enterprise Select
     * [ ] Science Select
     * [ ] Mobile Chart Of The Day
     * [ ] E-Commerce Chart Of The Day
     * [ ] Payments Chart Of The Day
     * [ ] Digital Media Chart Of The Day

   Charts of the Day
     * [ ] Sports Chart Of The Day

   Top 10 Things
     * [ ] 10 Things In Tech You Need To Know
     * [ ] Closing Bell

Advertisement

Your Money

   NASDAQ Composite 4,512  +45.44 (+1.017%)
   S&P 500          1,983  +16.86 (+0.858%)
   NYSE Composite   10,799 +76.67 (+0.715%)

Sponsored By

   LinkedIn
     * [the-future-of-payments-2014-slide-deck.jpg]
       THE FUTURE OF PAYMENTS: 2014 [SLIDE DECK]
     * [social-media-engagement-the-surprising-facts-about-how-much-time-p
       eople-spend-on-the-major-social-networks.jpg]
       Social Media Engagement: The Surprising Facts About How Much Time
       People Spend On The Major Social Networks
     * [why-google-asks-everyone-applying-for-a-job-the-same-exact-questio
       ns.jpg]
       Why Google Asks Everyone Applying For A Job The Same Exact
       Questions

   Login with LinkedIn to see what your friends are reading on Business
   Insider.
   Login with LinkedIn

   No articles have recently been shared in your network.

   More »

Featured

     * The 7 Most Viral Drone Videos In The World
       The 7 Most Viral Drone Videos In The World
       More "Game Changers" »
     * How To Ask For A Prenup Without Causing A Breakup
       How To Ask For A Prenup Without Causing A Breakup
       More "Life Plan" »
     * Here Are The Next 3 Industries Apple Is Likely To Reinvent
       Here Are The Next 3 Industries Apple Is Likely To Reinvent
       More "Tech 360" »
     * This Boston Startup Is Trying To Close The Gender Gap By Matching
       Women With Mentors
       This Boston Startup Is Trying To Close The Gender Gap By Matching
       Women With Mentors
       More "Game Changers" »

Welcome, !

You are logged into Facebook

Social:

     * Your Activity|

These articles have been shared on your timeline. You can remove them here:
     * Options

Notify me when a story is shared.
       (*) Yes ( ) No

Welcome, !

You are logged in with Google

Social:

     * Your Activity|

These articles have been added to your Google activity log. You can remove
them here:
     * Options

Notify me when a story is shared.
       (*) Yes ( ) No

Watch & Learn

   hate voice
     * Why You Hate The Sound Of Your Own Voice
     * Scientists Discovered What Makes Someone A Good Dancer
     * How The Secrets Of The Samurai Can Help You Achieve Laser-Focus

Trending

The Pulse of Digital

   Social Media Disruption
     * BEACONS FAQ: It's Time To Set The Story Straight
     * THE PROGRAMMATIC ADVERTISING REPORT: Forecasts And Top Trends
     * The Future of Payments [SLIDE DECK]


Read Business Insider On The Go

   [.png]

   FREE App
   Download
   [appstorebadgeen.png]
   Available for iPhone, iPad, Android, BlackBerry and Windows
   [appleicon.png] [androidicon.png] [.png] [windowsicon.png]

Advertisement

Career Builder

Find A Job

     * Tech Jobs
     * Media Jobs
     * Finance Jobs

     * C-Level Jobs
     * Design Jobs
     * Sales Jobs

   See All Jobs

Thanks to our partners

   Datapipe Catchpoint - Web Performance Monitoring Ooyala

     * * Copyright © 2014 Business Insider Inc. All rights reserved.
       Registration on or use of this site constitutes acceptance of our
       Terms of Service and Privacy Policy.
     * Disclaimer
     * Commerce Policy

     * Powered by MongoDB
     * Hosted by Datapipe
     * Stock quotes by YCharts
     * Made in NYC

   International Editions:
     * AUS
     * ID
     * IN
     * MY
     * SG

   [p?c1=2&c2=9900186&cv=2.0&cj=1]
