    #Vox - All Posts Vox - Card Stacks

       Log In / Sign Up

   Monday, September 29, 2014
     *
     *
     *
     *
     *

Map: Here's how 95°F days could become more common in your lifetime

   Updated by Brad Plumer on June 26, 2014, 12:19 p.m. ET @bradplumer
   Tweet Share on Twitter Share Share on Facebook +1 LinkedIn Share on
   LinkedIn Email Email Print Print
   Don't miss stories. Follow Vox!

   IFRAME:
   //www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com
   %2FVox&send=false&layout=button_count&width=200&show_faces=false&action
   =like&colorscheme=light&font&height=21

   Follow

   Brutally hot days when the temperature rises above 95°F are still a
   relative rarity in most of the United States. On average, Americans
   only experience about 13 such days a year (and most people get far
   fewer than that, especially in the Northeast).

   But if greenhouse gases keep accumulating in the atmosphere and global
   temperatures keep rising, that's expected to change. A new report from
   the Risky Business Project shows where 95°F days are expected to become
   much more common under unchecked global warming:

   Average days over 95°F: Projections over a lifetime

   Daysover95_full

   Risky Business Project. Data Source: Rhodium Group

   By mid-century, the report notes, Americans could see two to three
   times as many days hotter than 95°F — about 27 to 50 per year, on
   average. By the end of the century, that could rise to 45 to 96 days
   each year. And there's huge regional variation, with the South seeing a
   much bigger rise in extremely hot days.

   "By the end of the century, Oregon could have more 95°F days than Texas
   has now"

   "To put this in context," the report notes, "by the end of the century,
   Oregon, Washington, and Idaho could well have more days above 95°F each
   year than there are currently in Texas."

   Note that this is based off a modeled forecast for the most extreme
   climate scenario — in which greenhouse gases keep rising unabated
   through the century. The actual number of days hotter than 95°F could
   be fewer if, say, greenhouse gases don't keep rising (or if global
   warming is lower than the "likely" range of projections).

   But climate models do tend to agree that any significant amount of
   global warming will mean more extremely hot days. So it's worth taking
   a look at what that would mean:

What a rise in 95°F days would mean

   2561243705_f03dec3c5a_b

   Mr.TinDC/Flickr

   First, there are huge regional variations here. The Southwest,
   Southeast, and Midwest get hit especially hard. Under high-end
   scenarios, the report notes, they could spend the equivalent of several
   months each year with temperatures higher than 95°F.

   "Productivity in outdoor sectors could drop as 95° days increase"

   That could have major implications for industries that require workers
   to stay outside — like construction, landscaping, or agriculture. Some
   research suggests that productivity in these sectors could drop as much
   as 3 percent in the Southeast. Those industries will have to figure out
   some way to adapt.

   If the number of unbearably hot days rises, the use of air conditioning
   is also expected to skyrocket. Grid operators will have to figure out
   how to deal with the sharp rise in electricity demand during the
   summer.

   Then there's health to consider. In cities like Atlanta or New Orleans,
   hospitalizations and deaths already tend to rise when the temperatures
   climb past 95°F, especially among the elderly. That will be something
   to watch if these days become more common. The "Risky Business" report
   projects an additional 11,000 to 36,000 deaths per year in the
   Southeast from heat. (Though that's without adaptation — more on that
   crucial point below.)

Could it ever become too hot to go outside?

   173555014

   Runners pass a heat danger warning sign during the AdventurCORPS
   Badwater 135 ultra-marathon race on July 15, 2013 in Death Valley
   National Park, California. David McNew/Getty Images

   Perhaps most jarringly, the Risky Business report raises the prospect
   of occasional days toward century's end in which it'll be too dangerous
   for anyone to go outside for more than an hour or so.

   "The US has never seen a day with heat and humidity this severe"

   Normally, the human body cools down during hot days by sweating, so as
   to keep skin temperature below 95°F and the body's core temperature
   from rising above 98.6°F. But high humidity can prevent that sweat from
   evaporating and cooling the skin, which can cause core temperature to
   rise until a person collapses of heat stroke.

   The United States has never seen a day in which the combination of heat
   and humidity — dubbed the "Humid Heat Stroke Index" — was this severe.
   In fact, the only country that has ever seen heat like this is Saudi
   Arabia in 2003 (when the outside temperature reached 108°F and the dew
   point was 95°F).

   But the report's modeling suggests that, with unchecked global warming,
   the eastern US could see an average of one such day a year by century's
   end, and more thereafter. "Less than an hour of activity outdoors in
   the shade [on these days] could cause a moderately fit individual to
   suffer heat stroke," said Rutgers climate scientist Robert Kopp, a lead
   scientific author of the report.

How can we adapt to a rise in 95°F days?

   53253679

   A man enters a cooling center located in a Chicago Department of Human
   Services center July 18, 2005 in Chicago, Illinois. Chicago operates
   eight Human Services Centers across the city during extreme weather
   conditions. Tim Boyle/Getty Images

   Unfortunately, the Risky Business report doesn't really dwell on
   possible adaptation strategies to a rise in extremely hot days. And
   that's a crucial angle here, since adaptation to severe heat will
   likely prove necessary even if we only get moderate global warming.

   "more green spaces could reduce the need for medical assistance by 50%
   during heat waves"

   For a better discussion of this, it's worth turning to another recent
   report from the Intergovernmental Panel on Climate Change. The
   scientists who compiled that report looked at past deadly heat waves in
   places like Europe and tried to figure out what helped and what didn't.

   For instance, many of the deaths during heat waves occur among the
   elderly with weak social networks or poor health care. (A 2003 heat
   wave in Europe was particularly deadly because it followed on the heels
   of a nasty flu outbreak.) Better public-health infrastructure and
   monitoring could help.

   The IPCC also noted that the urban heat island effect tends to
   exacerbate heat waves. Because of all the buildings and cars and black
   pavement, cities tend to be even hotter than their surroundings. But
   there are ways to mitigate that. One study found, for instance, that
   introducing more green spaces into a city could reduce the need for
   medical assistance during scorching heat waves by 50 percent.

   Adaptation is getting more and more attention lately as scientists
   realize that we've already locked in some global warming into the
   system — and it's unclear how much the world will reduce greenhouse
   gases in the coming century. No matter how much the number of 95°F days
   rises, most of these strategies will prove necessary.

   Further reading:
     * Here's the full Risky Business report, which looks at the economic
       risks of climate change in regions around the United States. The
       group was chaired by Michael Bloomberg, Tom Steyer, and Hank
       Paulson, although the modeling was done by the Rhodium Group along
       with climate scientists Robert Kopp of Rutgers and Solomon Hsiang
       of Berkeley.
     * Here's the full IPCC report on adapting to the effects of climate
       change. Here's the relevant chapter on extreme heat.

Read This

     * Hong Kong's unprecedented protests and police crackdown, explained
     * "Poverty is fucking expensive"
     * 10 dramatic photos that show the protests and crackdown in
       Hong Kong
     * 41 maps (and charts) that explain the Midwest
     * 31,000 people an hour are joining the social network Ello.
       The anti-Facebook, explained.
     * Is it legal for the US to bomb Syria?
     * On Fox News, male soldiers get respect, but a female pilot is
       “boobs on the ground”
     * The problem with home-cooked meals

   Tweet Share on Twitter Share Share on Facebook +1 LinkedIn Share on
   LinkedIn Email Email Print Print

Most Read

    1. 1 Hong Kong's unprecedented protests and police crackdown,
       explained
    2. 2 10 dramatic photos that show the protests and crackdown in Hong
       Kong
    3. 3 22 maps and charts that will surprise you
    4. 4 Hong Kong's protesters are using the "hands up, don't shoot"
       gesture from Ferguson

   vox

   v1.3, September 5, 2014 / Terms of Use / Privacy Policy

   © 2014 Vox Media, Inc. All Rights Reserved

   All Systems Operational Check out our status page for more details.

   Advertise with us

   Jobs @ Vox Media

   Quantcast

   X
   Eater The Verge Polygon SB Nation
   Log In Sign Up
   T F G
   Y O
   ____________________
   Open ID Log in

   ____________________

   ____________________ forgot?

   [ ] Remember me? Log in
   Log In Sign Up
   T F G
   Y O
   ____________________
   Open ID Log in

   ____________________

   ____________________

   ____________________

   Continue

Forgot password?

   We'll email you a reset link.

   If you signed up using a 3rd party account like Facebook or Twitter,
   please login with it instead.
   ____________________
   Submit

Forgot password?

   Try another email?

Almost done,

   By becoming a registered user, you are also agreeing to our Terms and
   confirming that you have read our Privacy Policy.
   Register
   Spinner.vc97ec6e

Authenticating

Great!

   Choose an available username to complete sign up.

   ____________________

   Sign Up

   In order to provide our users with a better overall experience, we ask
   for more information from Facebook when using it to login so that we
   can learn more about our audience and provide you with the best
   possible experience. We do not store specific user data and the sharing
   of it is not required to login with Facebook.
   (*) Yes, share my data ( ) Please don't share my data
   Submit

   tracking_pixel_10934_tracker
