
   Donate Now Donate Now

   Truthout
   Monday, 29 September 2014 / TRUTH-OUT.ORG
     * For Oil and Gas Companies, Rigging Seems to Involve Wages, Too
       Oil and gas workers - men and women often performing high-risk jobs
       - are routinely being underpaid.
     * Fact-Checking Feinstein on the Assault Weapons Ban
       The researcher behind the key statistic Feinstein cites says it's
       an outdated figure that was based on a false assumption.
     *

   (BUTTON)
     * Home
          + News
          + Opinion
          + Video
          + Art
               o Cartoons
               o Graphic Journalism
               o Truthout on Flickr
     * BuzzFlash
          + Buzzflash Headlines
          + Buzzflash Commentary
     * Speakout
     * Progressive Picks
     * About Us
          + Submission Guidelines
          + Contact
          + Newsletter Sign-Up
          + Job Openings
     * Donate

     * Enter Search Text_______________________ OK
       Email to a friend
       Join our Newsletter_ Send

Secret $700,000 Donation Has Scott Walker Scrambling to Address "Appearance
of Corruption"

   Thursday, 28 August 2014 16:20 By John Nichols, The Nation | News
   Analysis
     *
     * font size decrease font size decrease font size increase font size
       increase font size
     * Print
     *

   2014 828 scot st Scott Walker declared victory at the Wisconsin GOP
   gubernatorial primary, September 14, 2010. (Photo: Wis Politics)When
   Gogebic Taconite LLC began moving in November 2010—the same month Scott
   Walker was elected governor of Wisconsin—to develop an open-pit iron
   mine in one of the most environmentally sensitive regions of northern
   Wisconsin, the Florida-based mining firm got a lot of pushback.
   Residents of the region objected, along with Native American tribes.
   So, too, did citizens from across Wisconsin, a state that has long
   treasured the wild beauty of the Penokee Range. Environmental and
   conservation groups voiced their concerns, as did local and state
   officials from across the political spectrum.

   The outcry heightened as Gogebic Taconite and its allies promoted a
   radical rewrite of existing mining regulations in order to promote a
   project that could grow to be four miles long, more than a mile wide
   and 1,000 feet deep. Democratic and Republican legislators began to ask
   tough questions. Yet Governor Scott Walker -- who as a state legislator
   had supported strict mining regulations --  remained “eager to advance
   a mining bill.”

   Wisconsin media outlets reported extensively during the 2011 and 2012
   on the governor’s determination to overrule objections to the grand
   schemes of an out-of-state corporation. Now, those same media outlets
   are reporting on  newly released documents that show the mining firm
   secretly steered $700,000 into “independent” efforts to provide
   political cover for the embattled governor.

   The documents, released as part of legal wrangling over a “John Doe”
   investigation into alleged fund-raising abuses during the recall
   elections of 2011 and 2012, have revealed both big contributions and
   big concerns on the part of a key investigator about “an appearance of
   corruption.”

   Walker, of course, denies any wrongdoing, as does Gogebic and the group
   that managed the money.

   Yet there is no question that the governor provided substantial support
   for the mining company. During a long, high-profile battle, he
   dismissed and denied a broad array of objections to Gogebic’s plans.

   The Nature Conservancy argued that the proposed changes to Wisconsin
   mining regulations would “pose serious risks to the rivers, lakes,
   wetlands, groundwater and other natural resources.”

   The Sierra Club announced that “the largest ever mine proposed in
   Wisconsin presents unacceptable risks to Lake Superior and the
   sensitive and exceptional Bad River Watershed which includes…the
   largest freshwater estuary on Lake Superior.”

   “It’s devastating,” said Annie Maday, a member of the tribal council of
   the Bad River Band of Lake Superior Chippewa, which argued that the
   mine could destroy wild rice beds and pollute waters on its nearby
   reservation. “They’re going to destroy my home.”

   When the state Senate took up the bill, it was opposed by Bob Jauch,
   the Poplar Democrat who represents northwest Wisconsin. “Our job is not
   to be Santa Claus to the mining company and Scrooge to the taxpayers,”
   Jauch said. “This is a bill that offers a sweetheart deal for the
   mining company and shortchanges the taxpayer.”

   State Senator Dale Schultz, a Republican who broke with his party to
   oppose the mining legislation at several key points, said, “My
   conscience simply won’t allow me to surrender the existing
   environmental protections without a full and open debate.”

   When the controversial rule changes were approved by the legislature in
   2013, Walker announced that he was “thrilled” to sign the bill.

   What went unmentioned at the time was the extent to which Gogebic
   Taconite was “thrilled” with Walker.

   The documents that were briefly unsealed last week by the US Court of
   Appeals for the Seventh Circuit—which is weighing whether to permit the
   continuation of the “John Doe” probe into alleged illegal coordination
   between Walker’s campaign and so-called “independent” groups that
   supported the governor—shined light on the shadowy political networks
   that developed to aid Walker. The Milwaukee Journal Sentinel noted that
   the “hundreds of pages of documents that… showed Walker’s team sought
   to solicit funds for the Wisconsin Club for Growth from an array of
   nationally known donors to fend off his 2012 recall. Real estate
   developer Donald Trump, industrialist billionaire brothers Charles and
   David Koch, and casino mogul Sheldon Adelson were all targets.”

   The documents reinforce the image of the governor, who is seeking
   re-election this fall and preparing a 2016 Republican presidential run,
   as a master political operative who worked every angle to secure record
   amounts of money for his own campaign and for “independent” groups that
   were supportive of it. In one of the unsealed documents, a fund-raising
   aide consulting with Walker before he met with wealthy donors advised:
   “Let them know that you can accept corporate contributions and it is
   not reported.”

   The documents reveal details of a number of huge and previously
   unreported donations. Yet the one that raised the most eyebrows had to
   do with the mine project.

   As the recall fights heated up, Gogebic Taconite moved $700,000 to the
   Wisconsin Club for Growth, which in turn steered resources to other
   groups that cheered on Walker and his Republican allies.

   “Because Wisconsin Club for Growth’s fundraising and expenditures were
   being coordinated with Scott Walker’s agents at the time of Gogebic’s
   donation, there is certainly an appearance of corruption in light of
   the resulting legislation from which it benefited,” argued Dean Nickel,
   the former head of the state Department of Justice’s Public Integrity
   Unit who investigated the fund-raising scheme for the state Government
   Accountability Board.

   Walker has admitted that he helped steer money to the Wisconsin Club
   for Growth, but when asked whether he knew of the Gogebic money, he
   answered vaguely, “Not to my knowledge.” Pressed by reporters on
   whether “the previously undisclosed funds and subsequent legislation
   were part of some pay-to-play scheme,” the governor replied, “That’s a
   ridiculous argument.”

   The governor has every right to make that claim, as do his most ardent
   apologists.

   But in Wisconsin, a state that historically took great pride in its
   clean elections and high ethical standards, voters have a right to ask,
   based on records and revelations, whether it really is all that
   ridiculous to find in them “an appearance of corruption.”
   This story originally appeared in The Nation.
   Copyright © 2014 The Nation 2014 distributed by Agence Global.

John Nichols

   John Nichols, a pioneering political blogger, has written the Beat
   since 1999. His posts have been circulated internationally, quoted in
   numerous books and mentioned in debates on the floor of Congress.

   Nichols writes about politics for The Nation magazine as its Washington
   correspondent. He is a contributing writer for The Progressive and In
   These Times and the associate editor of the Capital Times, the daily
   newspaper in Madison, Wisconsin. His articles have appeared in the New
   York Times, Chicago Tribune and dozens of other newspapers.
     __________________________________________________________________

   Show Comments

   Hide Comments
   View the discussion thread. blog comments powered by Disqus
   back to top
   (BUTTON) Read more
   GET DAILY TRUTHOUT UPDATES
   Enter your email add Submit

   FOLLOW TRUTHOUT tog torss tot tofb

   IFRAME:
   //www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%
   2FTruthout.org&send=false&layout=button_count&width=120&show_faces=fals
   e&action=like&colorscheme=light&font&height=21&appId=174773479325394

   Follow @truthout
   This Changes Everything

Latest Stories

     * Uruguay's Legalization of Marijuana Makes Sense in a Senseless Drug
       War
       By Benjamin Dangl, teleSUR | News Analysis
     * Truthout Interviews Featuring Paul Armentano on Marijuana, Alcohol
       and the Law
       By Ted Asregadoo, Truthout | Video Interview
     * It's Time for a Real Debate on Reader Privacy
       By Josh Stearns, Freedom of the Press Foundation | Op-Ed
     * Pledges Can Work, But It Will Take International Law to Fight
       Climate Change
       By Luke Kemp, The Conversation | Op-Ed
     *

Buzzflash Headlines

     * Why Obama’s Assurance of "No Boots on the Ground" Isn’t So
       Reassuring - Washington Post
     * Hong Kong Police Use Teargas and Pepper Spray to Disperse
       Protesters - The Guardian
     * Police Officer Shot In Ferguson As Protests Continue - Crooks and
       Liars

   Peace Calendar
   Truthout Progressive Picks

Featured Videos

     * Freed After Hunger Strike, Egyptian Journalist in US to Campaign
       for Jailed Colleagues
    Freed After Hunger Strike, Egyptian Journalist in US to Campaign for
       Jailed Colleagues
       By Amy Goodman and Juan Gonzalez, Democracy Now! | Video Interview
     * "What's Possible," a New Film for World Leaders on the Urgency of
       Global Warming
    "What's Possible," a New Film for World Leaders on the Urgency of
       Global Warming
       By Bill Moyers, Moyers & Company | Video Report
     * No Charges in Ohio Police Killing of John Crawford as Walmart Video
       Contradicts 911 Caller Account
    No Charges in Ohio Police Killing of John Crawford as Walmart Video
       Contradicts 911 Caller Account
       By Amy Goodman and Juan Gonzalez, Democracy Now! | Video Interview
     *

Secret $700,000 Donation Has Scott Walker Scrambling to Address "Appearance
of Corruption"

   Thursday, 28 August 2014 16:20 By John Nichols, The Nation | News
   Analysis
     *
     * font size decrease font size decrease font size increase font size
       increase font size
     * Print
     *

   2014 828 scot st Scott Walker declared victory at the Wisconsin GOP
   gubernatorial primary, September 14, 2010. (Photo: Wis Politics)When
   Gogebic Taconite LLC began moving in November 2010—the same month Scott
   Walker was elected governor of Wisconsin—to develop an open-pit iron
   mine in one of the most environmentally sensitive regions of northern
   Wisconsin, the Florida-based mining firm got a lot of pushback.
   Residents of the region objected, along with Native American tribes.
   So, too, did citizens from across Wisconsin, a state that has long
   treasured the wild beauty of the Penokee Range. Environmental and
   conservation groups voiced their concerns, as did local and state
   officials from across the political spectrum.

   The outcry heightened as Gogebic Taconite and its allies promoted a
   radical rewrite of existing mining regulations in order to promote a
   project that could grow to be four miles long, more than a mile wide
   and 1,000 feet deep. Democratic and Republican legislators began to ask
   tough questions. Yet Governor Scott Walker -- who as a state legislator
   had supported strict mining regulations --  remained “eager to advance
   a mining bill.”

   Wisconsin media outlets reported extensively during the 2011 and 2012
   on the governor’s determination to overrule objections to the grand
   schemes of an out-of-state corporation. Now, those same media outlets
   are reporting on  newly released documents that show the mining firm
   secretly steered $700,000 into “independent” efforts to provide
   political cover for the embattled governor.

   The documents, released as part of legal wrangling over a “John Doe”
   investigation into alleged fund-raising abuses during the recall
   elections of 2011 and 2012, have revealed both big contributions and
   big concerns on the part of a key investigator about “an appearance of
   corruption.”

   Walker, of course, denies any wrongdoing, as does Gogebic and the group
   that managed the money.

   Yet there is no question that the governor provided substantial support
   for the mining company. During a long, high-profile battle, he
   dismissed and denied a broad array of objections to Gogebic’s plans.

   The Nature Conservancy argued that the proposed changes to Wisconsin
   mining regulations would “pose serious risks to the rivers, lakes,
   wetlands, groundwater and other natural resources.”

   The Sierra Club announced that “the largest ever mine proposed in
   Wisconsin presents unacceptable risks to Lake Superior and the
   sensitive and exceptional Bad River Watershed which includes…the
   largest freshwater estuary on Lake Superior.”

   “It’s devastating,” said Annie Maday, a member of the tribal council of
   the Bad River Band of Lake Superior Chippewa, which argued that the
   mine could destroy wild rice beds and pollute waters on its nearby
   reservation. “They’re going to destroy my home.”

   When the state Senate took up the bill, it was opposed by Bob Jauch,
   the Poplar Democrat who represents northwest Wisconsin. “Our job is not
   to be Santa Claus to the mining company and Scrooge to the taxpayers,”
   Jauch said. “This is a bill that offers a sweetheart deal for the
   mining company and shortchanges the taxpayer.”

   State Senator Dale Schultz, a Republican who broke with his party to
   oppose the mining legislation at several key points, said, “My
   conscience simply won’t allow me to surrender the existing
   environmental protections without a full and open debate.”

   When the controversial rule changes were approved by the legislature in
   2013, Walker announced that he was “thrilled” to sign the bill.

   What went unmentioned at the time was the extent to which Gogebic
   Taconite was “thrilled” with Walker.

   The documents that were briefly unsealed last week by the US Court of
   Appeals for the Seventh Circuit—which is weighing whether to permit the
   continuation of the “John Doe” probe into alleged illegal coordination
   between Walker’s campaign and so-called “independent” groups that
   supported the governor—shined light on the shadowy political networks
   that developed to aid Walker. The Milwaukee Journal Sentinel noted that
   the “hundreds of pages of documents that… showed Walker’s team sought
   to solicit funds for the Wisconsin Club for Growth from an array of
   nationally known donors to fend off his 2012 recall. Real estate
   developer Donald Trump, industrialist billionaire brothers Charles and
   David Koch, and casino mogul Sheldon Adelson were all targets.”

   The documents reinforce the image of the governor, who is seeking
   re-election this fall and preparing a 2016 Republican presidential run,
   as a master political operative who worked every angle to secure record
   amounts of money for his own campaign and for “independent” groups that
   were supportive of it. In one of the unsealed documents, a fund-raising
   aide consulting with Walker before he met with wealthy donors advised:
   “Let them know that you can accept corporate contributions and it is
   not reported.”

   The documents reveal details of a number of huge and previously
   unreported donations. Yet the one that raised the most eyebrows had to
   do with the mine project.

   As the recall fights heated up, Gogebic Taconite moved $700,000 to the
   Wisconsin Club for Growth, which in turn steered resources to other
   groups that cheered on Walker and his Republican allies.

   “Because Wisconsin Club for Growth’s fundraising and expenditures were
   being coordinated with Scott Walker’s agents at the time of Gogebic’s
   donation, there is certainly an appearance of corruption in light of
   the resulting legislation from which it benefited,” argued Dean Nickel,
   the former head of the state Department of Justice’s Public Integrity
   Unit who investigated the fund-raising scheme for the state Government
   Accountability Board.

   Walker has admitted that he helped steer money to the Wisconsin Club
   for Growth, but when asked whether he knew of the Gogebic money, he
   answered vaguely, “Not to my knowledge.” Pressed by reporters on
   whether “the previously undisclosed funds and subsequent legislation
   were part of some pay-to-play scheme,” the governor replied, “That’s a
   ridiculous argument.”

   The governor has every right to make that claim, as do his most ardent
   apologists.

   But in Wisconsin, a state that historically took great pride in its
   clean elections and high ethical standards, voters have a right to ask,
   based on records and revelations, whether it really is all that
   ridiculous to find in them “an appearance of corruption.”
   This story originally appeared in The Nation.
   Copyright © 2014 The Nation 2014 distributed by Agence Global.

John Nichols

   John Nichols, a pioneering political blogger, has written the Beat
   since 1999. His posts have been circulated internationally, quoted in
   numerous books and mentioned in debates on the floor of Congress.

   Nichols writes about politics for The Nation magazine as its Washington
   correspondent. He is a contributing writer for The Progressive and In
   These Times and the associate editor of the Capital Times, the daily
   newspaper in Madison, Wisconsin. His articles have appeared in the New
   York Times, Chicago Tribune and dozens of other newspapers.
     __________________________________________________________________

   Show Comments

   Hide Comments
   View the discussion thread. blog comments powered by Disqus
   back to top

   © 2014 Truthout
