
 [y18.gif] Hacker News [s.gif] new | comments | show | ask | jobs |
           submit                                                  login

 nullc 92 days ago | link | parent
 This is the full 120 minute long documentary. It's a heavy watch, but
 interesting to both audiences familiar with the background and ones who
 are not.

 In addition to the normal pay per view streaming on vimeo
 (https://vimeo.com/ondemand/internetsownboy/94238859), this film was
 also offered at an increased price under CC-By-NC-SA. I purchased a
 freely licensed copy and have placed it on archive.org allowing anyone
 to learn from it, share it with others, or build new works out of it
 without risk of prosecution and without going through US-only paywall.

 The official site for the film is at
 http://www.takepart.com/internets-own-boy and the there is a Wikipedia
 article at
 http://en.wikipedia.org/wiki/The_Internet%27s_Own_Boy:_The_S...


 [s.gif]

         jcr 91 days ago | link
         Thank You nullc. It's really tough to contribute something useful to
         the discussion about and around Aaron Schwartz. The best I can offer is
         a paper that I found a few hours ago. I haven't read it yet, but it was
         just released a few days ago. From what I can tell from the description
         quoted below by one of the authors, it may be good related research
         worth reading.

         WEIS 2014: Experimental Measurement of Attitudes Regarding Cybercrime

         http://weis2014.econinfosec.org/papers/GravesAcquistiAnderso...

         > "Online activists appear to be treated much more harshly by
         prosecutors than equivalent street protesters; meanwhile online
         fraudsters are often treated more leniently than the traditional
         variety. Over two thousand mTurkers participated in six different
         between-subjects experiments to assess the seriousness or cybercrimes
         by type of data (directory vs medical info), scope 10 to 1,000,000
         records) motivation (student, activist, profiteer) financial
         consequences, co-responsibility and whether the victim was a firm, a
         nonprofit or a government agency. Respondents saw more records as more
         sensitive than less; profiteers as much worse than students or
         activists; more expensive cases as more serious; that firms were less
         liable if servers were patched (but that the data were more sensitive
         in that case). In summary, participants recommend harsher sentences
         when cybercrimes involve more or more sensitive data, have costlier
         consequences, or are motivated by profit. This is much more rational
         than the reported behaviour of some prosecutors and judges."

 -----

 [s.gif]

         lhl 91 days ago | link
         I haven't gotten myself in the headspace to watch this yet, but perhaps
         also of interest for those who are is Quinn Norton's recent essay
         marking the release of the documentary:
         https://medium.com/message/the-internets-own-boy-c815ae07a41...

         The first half of the piece is a bit of a confessional/elegy- personal,
         poignant, and a bit heartrending, especially for those who knew Aaron.
         The second half turns decidedly more polemic, but feels all the more
         important for the HN crowd (or anyone thinking about the future and the
         society we live in).

         Aaron's death was tragic, yes, but it happened within a much (much)
         larger context of what feels like a waning in social justice and
         personal freedom around the world.

         I've certainly been thinking a lot harder about it in the past year,
         and I hope others are as well.

 -----

 [s.gif]

         rdhyee 91 days ago | link
         Thanks for posting the video on archive.org. Ever since I read
         http://boingboing.net/2014/06/19/aaron-swartz-documentary-th..., I've
         been looking for a place to download the CC-licensed video. If I want
         to send money to the producers of the video, how should I do so? Buy a
         copy of the video from vimeo?

         -----

 [s.gif]

         thinkcomp 91 days ago | link
         Yes, buying from Vimeo is probably the best way to support Brian and
         his colleagues.

         (I am technically one of the "executive producers" but I don't make any
         money from it.)

         -----

 [s.gif]

         emm 91 days ago | link
         I bought the video to support your team. Unfortunately it was
         geoblocked first and only available in SD. Please change that.

         -----

 [s.gif]

         muloka 91 days ago | link
         I live in a region where its geoblocked from purchasing this film.

         Would love to support this film/work.

         -----

 [s.gif]

         rational-future 91 days ago | link
         Here's a magnet link for torrent users:

         magnet:?xt=urn:btih:6b1c1f8476d0604d98e4a9d3d3bbf4cd131e3326&dn=The+Int
         ernet%27s+Own+Boy+-+The+Story+of+Aaron+Swartz+%282014%29&tr=udp://track
         er.openbittorrent.com:80/announce

         -----

 [s.gif]

         scrollaway 91 days ago | link
         Thank you.

         -----
 [s.gif]

  Guidelines | FAQ | Lists | Bookmarklet | DMCA | News News | Bugs and
       Feature Requests | Y Combinator | Apply | Library | Contact
                        Search: _________________
