   Subscribe Via Email
   __________________ Submit
   Markets for Event Blasts
   [ ] Austin Events
   [ ] Atlanta Events
   [ ] Bloomington Events
   [ ] Boston Events
   [ ] Chicago Events
   [ ] DC Events
   [ ] Dallas Events
   [ ] Denver/Boulder Events
   [ ] Kansas City Events
   [ ] Las Vegas Events
   [ ] Los Angeles Events
   [ ] Miami Events
   [ ] Minneapolis Events
   [ ] New Orleans Events
   [ ] NYC Events
   [ ] New York - OLD Events
   [ ] Tampa Bay Events
   [ ] Phoenix Events
   [ ] Pittsburgh Events
   [ ] Portland Events
   [ ] San Diego Events
   [ ] San Francisco Events
   Markets for News Blasts
   [ ] Atlanta News
   [ ] Austin News
   [ ] Boise News
   [ ] Chicago News
   [ ] Dallas News
   [ ] DC News
   [ ] Las Vegas News
   [ ] Los Angeles News
   [ ] Miami News
   [ ] NYC News
   [ ] San Francisco News
   (BUTTON) ×

Tech Cocktail San Francisco

   (BUTTON)
   Edition: [San Francisco] View
     * Go to the Celebrate Conference
     * Events
          + Current Events
          + TCWEEK
     * Advertise
          + Advertise
          + Sponsor an Event
     * About
          + About Tech Cocktail
          + Authors
          + Tech Cocktail Contributor of the Month
     * Jobs
     * Shop
     * Book

Tim O’Reilly Eloquently Explains How Tech Trends Happen

   Tim O'Reilly reddit ama

   Apr 22, 2014 - Kira M. Newman for the San Francisco Edition

   Tim O’Reilly, founder and CEO of O’Reilly Media, is currently answering
   questions about the Internet of Things in a Reddit AMA, a sort of open
   town hall.

   The Internet of Things refers to Internet-connected devices, sensors,
   and everyday objects that can send and receive data. Think of the Nest
   thermostat, which learns your temperature preferences and was acquired
   by Google in January.

   Someone wanted to know: what’s driving the Internet of Things movement?
   Why now? O’Reilly replied with an elegant explanation of how movements
   happen:

     “I think it’s a ‘perfect storm.’ Yes, there are lots of new sensors
     everywhere (especially in our phones – don’t make the mistake of
     thinking that IoT requires new devices – the phone can be one
     important half of the system). And yes, the maker movement has
     gotten people excited about hardware again. And yes, the big data
     infrastructure is in place to make use of the sensor data for useful
     applications.

     But it’s also a bit of what George Soros calls ‘reflexive truth.’
     Things become true to the extent people believe in them. And
     movements in technology are like that: self-reinforcing waves, where
     one success draws imitators. So it starts with makers doing it for
     love, but the investors and entrepreneurs pile on when they see an
     exit for a MakerBot, or a Tesla, or a Nest.”

   Did you like this article? Yes No
   Get more delivered to your inbox just like it!
   Subscribe Via Email
   __________________ Submit
   Markets for Event Blasts
   [ ] Austin Events
   [ ] Atlanta Events
   [ ] Bloomington Events
   [ ] Boston Events
   [ ] Chicago Events
   [ ] DC Events
   [ ] Dallas Events
   [ ] Denver/Boulder Events
   [ ] Kansas City Events
   [ ] Las Vegas Events
   [ ] Los Angeles Events
   [ ] Miami Events
   [ ] Minneapolis Events
   [ ] New Orleans Events
   [ ] NYC Events
   [ ] New York - OLD Events
   [ ] Tampa Bay Events
   [ ] Phoenix Events
   [ ] Pittsburgh Events
   [ ] Portland Events
   [ ] San Diego Events
   [ ] San Francisco Events
   Markets for News Blasts
   [ ] Atlanta News
   [ ] Austin News
   [ ] Boise News
   [ ] Chicago News
   [ ] Dallas News
   [ ] DC News
   [ ] Las Vegas News
   [ ] Los Angeles News
   [ ] Miami News
   [ ] NYC News
   [ ] San Francisco News
   Share this awesome article.
   Sorry about that. Try these articles instead!
   About the Author Kira M. Newman

   Kira M. Newman is a Tech Cocktail writer interested in
   entrepreneurship, work-life balance, and positive psychology. Since
   2011, she has been traveling around the world interviewing
   entrepreneurs in Asia, Europe, and North America. Follow her
   @kiramnewman or contact kira@tech.co.

   Tags: ama Internet of Things movements reddit Tim O'Reilly trends

Leave a Reply

   Cancel
     * Name (required)
       ____________________
     * Mail (required)
       ____________________ (will not be published)
     * Website
       ____________________


   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   Submit Comment

Search

   ____________________ (BUTTON) Search

San Francisco Events

     * Tech Cocktail Events
          + No Tech Cocktail Events
     * Industry Events
          + Oct 27, 2014 - Big Data TechCon
          + Nov 6, 2014 - RE.WORK Internet of Things 2014
          + Jan 29, 2015 - RE.WORK Deep Learning Innovation Summit 2015

   View All Events
   [INS: :INS]

Subscribe Via Email

   __________________ Submit
   Markets for Event Blasts
   [ ] Austin Events
   [ ] Atlanta Events
   [ ] Bloomington Events
   [ ] Boston Events
   [ ] Chicago Events
   [ ] DC Events
   [ ] Dallas Events
   [ ] Denver/Boulder Events
   [ ] Kansas City Events
   [ ] Las Vegas Events
   [ ] Los Angeles Events
   [ ] Miami Events
   [ ] Minneapolis Events
   [ ] New Orleans Events
   [ ] NYC Events
   [ ] New York - OLD Events
   [ ] Tampa Bay Events
   [ ] Phoenix Events
   [ ] Pittsburgh Events
   [ ] Portland Events
   [ ] San Diego Events
   [ ] San Francisco Events
   Markets for News Blasts
   [ ] Atlanta News
   [ ] Austin News
   [ ] Boise News
   [ ] Chicago News
   [ ] Dallas News
   [ ] DC News
   [ ] Las Vegas News
   [ ] Los Angeles News
   [ ] Miami News
   [ ] NYC News
   [ ] San Francisco News
   [INS: :INS]

Follow Tech Cocktail

   Follow @techcocktail

Check Out

   celebrate_general_250x125 Financial Model for Startups American
   Airlines

Find Jobs in Tech

   See All Jobs by Tech Cocktail

     * Startups & Apps
          + Mobile
          + Web
          + Games
          + Location Based Services
          + Social Media
          + Incubator
          + Social Good

     * Entrepreneur
          + Tips & How To’s
          + Interviews
          + Social Media
          + Dev & Design
          + Funding
          + Programs & Resources
          + Reports & Rankings

     * Business
          + News
          + Trends
          + Jobs
          + Books
          + Movies & Entertainment

     * Tech Cocktail TV
          + Speaker Series
          + Interviews
          + Episodes

     * Gear & Gadgets

     * Submit News Tip
     * Submit An Event
     * Advertise
     * Write for Us
     * Contact Us

   Tech Cocktail is a literal "cocktail of emerging technology news,
   people, startups, products, and innovations" for the true tech
   enthusiast.

   The media company, founded and lead by former Aol product strategist,
   long-time tech blogger and new media pioneer Frank Gruber, focuses on
   celebrating entrepreneurs, emerging technology and innovation. Along
   with the leadership of long-time technology producer, Jen Consalvo,
   Frank and his team of tech analysts and curators bring a unique point
   of view to tech.co as they scour the web and world in search of new
   products and services, fresh voices, interesting leaders, hot news and
   trends, how-to's and more.

   © 2014 Tech Cocktail LLC. All Rights Reserved
   Mobile Analytics
