   IFRAME: //www.googletagmanager.com/ns.html?id=GTM-K6HSK9

   Skip to main content

   Donate today »

Search form

   Search _______________
   Search

Stop the Secrecy

   Open Media International logo
   [fb_button_03.png] [twitter_button_transparent.png]
   [gplus_button_transparent.png] [tumblr_button_transparent.png]
   against fast tracking the secretive TPP

     Stop the Secrecy before it's too late

   Right now, industry lobbyists are pressuring key decision-makers of 12
   countries to sign a secretive agreement called the Trans-Pacific
   Partnership (TPP).

   The TPP threatens to censor your Internet^1, kill jobs, undermine
   environmental safeguards, and remove your democratic rights^2.

   Add your voice to the largest anti-secrecy campaign in history to send
   TPP decision-makers a clear message before it's too late.

   First name * _________________________
   Last name * _________________________
   Email * _________________________
   Country * [- Select -__________________________________]

   Add your voice!

   StopTheSecrecy is hosted by OpenMedia, Daily Kos, RootsAction and
   Demand Progress. We will keep you informed about this campaign and
   others.

   Click on each organization's name for their privacy policy.

   *UPDATE: Together we grabbed the attention of decision-makers by
   projecting a Stop The Secrecy petition number on key buildings in
   Washington D.C. Now we need you to amplify our action by making it go
   viral online. Congress Member Ron Wyden, who leads U.S. trade
   legislation, has just joined with us to stand against TPP Secrecy!  We
   haven't won yet so after you sign the petition please share the
   projection image below with everyone you know.



                 StopTheSecrecy total: over 3 Million signed

                  Share on Twitter!   Share on Google Plus

   The TPP is huge: It covers 40% of the global economy and will overwrite
   national laws affecting people around the world.^3

     The worst of the TPP threatens everything we care about: democracy,
    jobs, health, the environment, and the Internet.  That's why industry
   lobbyists are forcing decision-makers to meet under extreme secrecy and
          pushing 'Fast Track' laws to cement the plan into place.

   This is no way to make decisions in the 21st century. Every voice added
    now will make the Stop The Secrecy petition makes our call louder and
                                  stronger.

      Please add your voice to help us build one of the largest online
                     campaigns the world has ever seen.



After you sign the petition maximize your impact by spreading the word:

   StopTheSecrecy spotlight



   Click here if you haven't added your voice yet.
     __________________________________________________________________

   The StopTheSecrecy campaign is hosted by:
   https://openmedia.org http://www.dailykos.com/
   https://www.fightforthefuture.org/ http://rootsaction.org
   https://demandprogress.org/

   In collaboration with (click here for a full list of supporting
   organizations):

   *Your organization can sign on here.
   http://www.thenation.com/ http://www.reddit.com http://avaaz.org/
   http://nzoss.org.nz/ http://www.citizen.org/ http://imgur.com/
   http://credoaction.com/ http://front.moveon.org/
   http://www.sierraclub.org/ https://www.derechosdigitales.org/
   https://www.eff.org/ http://teamster.org/ http://www.pdamerica.org/
   https://duckduckgo.com/ http://www.tucows.com/ http://firedoglake.com/
   https://disconnect.me/ http://www.leadnow.ca/
   http://www.stopcorporateabuse.org/ http://www.flushthetpp.org/
   http://sumofus.org/ http://www.cwa-union.org/ http://www.world-psi.org/
   http://www.backbonecampaign.org/ http://www.canadians.org/
   https://www.tunnelbear.com http://smart-union.org/
   http://www.democracyinactionchicago.org/ http://www.globalexchange.org/
   http://www.scoop.co.nz/ http://350.org/
   http://www.popularresistance.org/ http://www.usft.org/
   http://tpp.jimdo.com/english/ http://www.atquebec.org/
   https://isoc-ny.org/ http://piwik.org/ http://www.itforchange.net/
   https://www.privateinternetaccess.com/ http://www.dolldivine.com/
   http://www.pin.sg/ https://www.opendemocracy.net/
   http://www.nupef.org.br/

   *Click here for a full list of supporting organizations.

   *Your organization can sign on here.

   Footnotes:

   *According to several reports "An early signing of the TPP is expected
   to be a key topic in a planned full meeting between Abe and Obama when
   the U.S. president visits Japan." The meetings are taking place right
   now.

   [1] Find more information on Internet censorship in the TPP from
   OurFairDeal.org and here. Also see "TPP Creates Legal Incentives For
   ISPs To Police The Internet. What Is At Risk?" Source: Electronic
   Frontier Foundation.

   [2] Leaked drafts of the Secret Trans-Pacific Partnership Agreement,
   Source: Wikileaks. Background on several issues pertaining to the TPP
   can be found on the Expose The TPP website and in our resources page.

   [3] U.S. “Bullying” TPP Negotiators Amid Failure to Agree. Source:
   Inter Press Service News Agency. *Note: The U.S. and the E.U. are
   already discussing a similar secretive agreement called "Transatlantic
   Trade and Investment Partnership (TTIP)". Once the TPP is finalized
   there will be pressure to harmonize and extend its provisions to TTIP
   -- meaning the E.U. There are also reports of many others countries
   being added to the TPP once it is finalized.



If you haven't taken action yet click here.



   Press: David Christopher | Cell: 1-778-232-1858 | Office:
   1-604-633-2744 | david@openmedia.org

     * Home
     * Contact Us
     * Press


      Creative Commons License  This site is licensed under a Creative
      Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
