   #New FAA rules class toy UAVs as illegal drones Blogging History: Jack
   Kirby spreads; Sweet microbat love; GWB vs real journo

   __________________
   Blog Features Podcasts Video Forums Follow Us
   Twitter Facebook Tumblr
   •Submit

[boingboing.jpg]

Internet's Own Boy, free CC-licensed download on Internet Archive

   [share.png] [share.png] [share.png]

   Cory Doctorow at 9:00 am Sun, Jun 29, 2014

   ADVERTISE AT BOING BOING!
   SHARE TWEET STUMBLE COMMENTS

   IFRAME:
   https://archive.org/embed/TheInternetsOwnBoyTheStoryOfAaronSwartz

   [TheInternetsOwnBoy_TheStoryofAaronSwartz-HD1.gif] The Creative
   Commons-licensed version of The Internet's Own Boy, Brian
   Knappenberger's documentary about Aaron Swartz, is now available on the
   Internet Archive, which is especially useful for people outside of the
   US, who aren't able to pay to see it online. It's a remarkable movie
   and I hope you make some time to watch it. The Internet Archive makes
   the movie available to download or stream, in MPEG 4 and Ogg. There's
   also a torrentable version.
   Discuss

Continue the discussion at bbs.boingboing.net

   5 replies

Read more at Boing Boing

New FAA rules class toy UAVs as illegal drones

Steampunk spring-heeled jack stiltwalker

World War One: on the peculiar geopolitics of passionate, armed teenagers

   ADVERTISEMENT

   About Us Contact Advertise Privacy TOS • Facebook Twitter RSS Email
