    ____________________

   Search Images Maps Play YouTube News Gmail Drive More »
   Send Feedback | Web History | Help | Sign in
   Home
   Home
   Profile
   People
   Photos
   Communities
   Events
   Hangouts
   Pages
   Local
   Settings
   Feedback
   Help  ·  Region
   Privacy & Terms  ·  Maps Terms
   [photo.jpg]
   Tim O'Reilly

Tim O'Reilly

   Shared publicly  -  2014-04-13
    #NPR
    #Obama

   Journalism vs. Punditry: NPR's Kelly McEvers on Why Reporting Matters
   There was a great segment on KQED Forum the other day with NPR
   correspondent Kelly McEvers.  Throughout the segment, she talked about
   the power of reporting.  She tells the story of when she was called to
   Bahrain for a government press conference about how all the protests
   were settled, and heard instead of how there was brutal crackdown going
   on in a nearby town that very day, rushed to the scene, and were able
   to report the substance rather than the government-controlled show.
   But perhaps the best moment comes at the end of the interview,
   reproduced below.  (It starts about about minute 47:48 in the audio
   file.)
   Caller:  I was in Syria too, and it really bothers me that people like
   you that have such a rare and important experience, that you don't give
   your own opinion.  For instance why President Obama... or criticize him
   for not getting rid of Assad like he got rid of Quaddafi.  And I know
   your editors and people try to control it and won't let you but I think
   you could do that now and maybe you could just give me your comments.
   It must be very frustrating that you don't give your opinion on what
   should be done.  You just report a story.
   McEvers:  Well, guess what?  The people's opinions are much more
   valuable than my opinion.  Like I was just a conduit.  I'll never
   forget this one woman.  I was at a funeral in a village in
   rebel-controlled Syria and it was the first guy to die in this village.
   And I was on the women's side, with the mourning, and this woman looked
   at me and she "Where is America? Where is Obama?  What? Syrian children
   aren't as good as Libyan children?"  She said "You know something?
   We're not going to forget this. We're not going to forget that you
   forgot about us." And all I had to do was report that line. I'm sorry
   but I feel like that's 10,000 times more powerful than me getting up
   like some TV pundit and spouting my opinion. That's who I am. I'm a
   journalist. That's my job."
   How right she is.  What you choose to report is, of course, an
   expression of your opinion.  But the power of doing it directly, with
   other people's voices, is profound. Being a channel for otherwise
   unheard voices that matter can be so much more effective than explicit
   editorializing.
   via +Jennifer Pahlka ﻿
   [iEyacySPVp4pVTd5VOiDx-aTtpLWY4v0fvzDSNHsy0GAIjHvd5A2aGHtuIEHDvzLXloeNQ
   LafjLriMWT0F1n=w506-h284]
   NPR's Kelly McEvers Recounts a 'Bad Year' as War Correspondent | KQED
   kqed.org
   64
   7
   Tanveer Moin's profile photo Dick Ross's profile photo John Enfield's
   profile photo Mike Calma's profile photo
   8 comments
   Brian Ahier
   +
   6
   7
   6
   Reply

   You can almost always find someone to quote who will express your own
   opinion (oftentimes better than you can yourself), the challenge can be
   reporting viewpoints with which you vehemently disagree...﻿
   Bill Anderson
   +
   2
   3
   2
   Reply

   Too many modern "journalists" were, and are being, taught their job is
   "to change the world". This leads them to thinking and behaving as if
   journalism is about them.
   It is isn't, and it isn't about changing the world. It is about
   reporting the world to itself.
   We as listeners, viewers, and readers tend to be party to this problem.
   As the caller unwittingly demonstrates in this exchange we tend to want
   to hear confirmation of our beliefs. We want our stories to serve as
   justification for our feelings and desires, rather than the facts.
   We see it in the dripping loathing issued over media and news outlets
   that don't give us the satisfaction of supporting our beliefs and we
   see it in this caller asking why the reporter didn't express an
   opinion.
   Thus it is quite refreshing to see this reporter not only expressing
   the viewpoint of being a reporter not a pundit, but to do so in
   response to a listener. ﻿
   Dick Ross
   +
   1
   2
   1
   Reply

   I don't believe that journalism is one thing whether +Bill
   Anderson "reporting the world to itself" or "the facts." or +Brian
   Ahier "express your own opinion."  Correct as these might be they are
   not the whole picture.  Allow me to quote Edmund Burke to bring up
   another point of view, "Your representative owes you, not his industry
   only, but his judgment; and he betrays instead of serving you if he
   sacrifices it to your opinion,"  Though from the point of view of a
   politician, the quote serves to highlight what seems most missing in
   contemporary journalism, "judgment" based on the evidence at hand for
   the journalist who risks his/her position on at times extraordinary
   complex issues.  The public needs not only to be informed but to be
   guided and guided  by the judgment of the journalist.  We've had a
   history of that kind of journalism that seems to me very much needed
   and very much missing.﻿
   John Enfield
   +
   0
   1
   0
   Reply

   They've got no business getting in there and reporting on wars and
   'police actions' live. They give our secrets away.﻿
   Arun Kannan
   +
   0
   1
   0
   Reply

   True that!﻿
   Patrick Ballenger
   +
   3
   4
   3
   Reply

   +John Enfield if your secret is out in the open for a journalist to see
   and report on then it's not a secret. Journalists are not tools of the
   state. They are there to report. They are also outside the government,
   and are there to keep the government in check.﻿
   Illarion Bykov
   +
   0
   1
   0
   Reply

   Wow. What a clever propaganda piece. What about reporting the other
   side of the story? The family members of people killed by US - supplied
   and NATO - supplied weapons wielded by fanatics and extremists who
   ritually mutilate their victims' bodies? What about the victims of CIA
   - sponsored snipers who had orders to shoot people on both sides but
   make it look like the other side did it to inflame conflict and break
   ceasefires and negotiations? US government news journalists do not
   report that kind of opinion. You have to go to independent journalists
   or foreign news media to get those stories. Thanks to the Internet, NPR
   no longer has the same power to disinform that it used to have.﻿
   Bill Anderson
   +
   0
   1
   0
   Reply

   +Dick Ross I agree with the Burke quote, but not how you apply it to
   this situation.
   On opinion isn't exercising judgment. The judgement if a journalist is
   in what they report. Their personal opinion on what they report is not
   journaling the events. Being objective is difficult in reporting
   because we all see the world through the filters of our experiences and
   opinions.
   When journalists provide their opinion as part of the report they not
   only escape what is going on, but increase the difficulty of being
   objective and letting their opinion color the story in a way that may,
   indeed likely often, lack veracity.
   The easy example is the reporter who is against an action being taken
   in the event he or she is reporting on. This bias can, and often does,
   prevent them from exploring "the whole picture" instead fixating on
   what they believe to be the negative aspects. This isn't usually
   conscious effort, the human brain seems wired to filter out that which
   causes cognitive dissonance.
   Consider further your apt use of the phrase "the whole picture". A
   reporter's opinion is not part of the picture in any way. It is an
   external concept brought to the scene or formed as a result of
   witnessing the scene.
   If a reporter feels the need to express their opinion, let it follow
   suit and be expressed outside of the context of reporting on the story.
   This isn't a new concept. The newspapers, for example, had news
   articles and editorials. The editorial was opinion expressed about
   articles, not in them. Given the abundance of ways and means for a
   journalist to express their opinion outside if a news report, there is
   no reason for it to be in the report. ﻿
   Add a comment...
   Start a hangout
