   [cooridorlogo.png]
   [AGA_HOME.png]
   Akron Global Business Accelerator
     * About
          + History
          + Overview
          + Management Team
          + Stake Holders
          + Global Commercialization
          + Product Development Fund
          + Rapid Commercialization Loan Fund
     * Facility
          + Amenities & Services
          + Int. Soft Landing
     * Clients
          + Success Stories
          + Company Websites
          + 7-Signal
     * News
          + Events
          + Awards & Recognition
     * Admission
          + Guidelines & Criteria
          + Admission Forms
     * FAQs
     * Partner Links
          + National Business Incubation Association (NBIA)
          + Ohio’s Thomas Edison Technology Program
          + JumpStart Inc
          + More...

     *
     *
     *
     *

   Founded in 1983 as an initiative of the City of Akron, the Akron Global
   Business Accelerator provides entrepreneurial support to
   technology-based start-ups in diverse fields, including: biomedical,
   energy, advanced materials, IT, instruments, controls and electronics.
   The Accelerator is nationally recognized for its innovation and has
   assisted client companies in securing $86 million in investment,
   generating 639 new high-paying jobs, $181 million in sales, and $104.5
   million in payroll since 2008.
     * About
          + History
          + Overview
          + Management Team
          + Stake Holders
          + Global Commercialization
          + Product Development Fund
          + Rapid Commercialization Loan Fund
     * Facility
          + Amenities & Services
          + Int. Soft Landing
     * Clients
          + Success Stories
          + Company Websites
          + 7-Signal
     * News
          + Events
          + Awards & Recognition
     * Admission
          + Guidelines & Criteria
          + Admission Forms
     * Partner Links
          + National Business Incubation Association (NBIA)
          + Ohio’s Thomas Edison Technology Program
          + JumpStart Inc
          + More...

Follow


Contact

   526 S. Main Street
   Akron, Ohio 44311
   P: (330) 375-2173
   F: (330) 762-3657
   tmartell@akronaccelerator.com

   Web solution brought to you by:

   Privacy Statement Terms Of Use ©2011 Akron Global Business Accelerator
   - All Rights Reserved. Login
