   #Roger Sollenberger's Posts - DIY Drones Comments - DroneCon recap vid:
   Daniel McKinnon, “What Do Farmers Really Want?” - DIY Drones Top
   Content - DIY Drones

   ____________________ Search

     * Sign Up
     * Sign In

DIY Drones

     * Home
     * Store
          + Ready-to-fly ArduCopter
          + Ready-to-fly ArduPlane
          + ArduCopter kits
          + Autopilots
          + GPS
          + RC Electronics
          + Sensors
          + Wireless Data
          + Video/OSD
          + Dealers around the world
     * Getting Started
          + Newbies guide to UAVs
          + About this site (rules)
          + How can I contribute?
     * Forum
          + Start a Forum topic
          + See all Forum topics
     * Blogs
          + Create a blog post
          + View all blog posts
     * ArduCopter
          + Get it!
          + ArduCopter Manual
          + Support Forum
          + ArduCopter User Group
          + Developers
     * ArduPlane
          + Get it!
          + ArduPlane Manual
          + Support Forum
          + ArduPlane User Group
          + Developers
     * ArduRover
          + Get it!
          + ArduRover Manual
          + Support Forum
          + ArduRover User Group
          + ArduBoat User Group
          + Developers
     * Members
          + Leaderboards
          + Local UAV groups
          + UAV DevBoard
     * MyPage
     * Videos
          + Photos
          + DIY Drones News Center

     * All Blog Posts
     * My Blog
     * Add

   3D Robotics

DroneCon recap vid: Daniel McKinnon, “What Do Farmers Really Want?”

     * Posted by Roger Sollenberger on July 2, 2014 at 5:24pm
     * View Blog

   IFRAME:
   //www.youtube.com/embed/bm07KAK1xo8?feature=player_detailpage&wmode=opa
   que

   Here’s the latest of our DroneCon 2014 recap vids: Daniel McKinnon on
   UAVs in agriculture.
   Here’s his abstract:
   The technology community has embraced UAVs as the solution to all of
   agriculture’s problems and inefficiencies. Drone-collected images can
   theoretically lead to reduced fertilizer, water, and chemical
   application; increased yields; reduced uncertainty; and ultimately
   increased profits for the farmers. However, while many of these
   hypotheses may be true, the advanced data currently being collected by
   drones is far ahead of the adoption of the precision agriculture
   technologies that enable farmers to act on the data. Through working
   with farmers and agronomists over the last 18 months, Agribotix has
   identified the types of data farmers are interested in and a number of
   different applications for UAV-collected imagery that any farmer can
   use immediately without strongly deviating from a standard workflow.

   Views: 1092

   Tags:
   Like
   8 members like this

   Share Twitter
     * < Previous Post
     * Next Post >

   Comment by Mike T on July 2, 2014 at 6:09pm
          video is private

   3D Robotics Comment by Roger Sollenberger on July 2, 2014 at 6:10pm
          Fixed!

   Comment by Mike T on July 2, 2014 at 6:31pm
          thanks for uploading :)

   Developer Comment by Kevin Hester on July 2, 2014 at 8:32pm
          That was my favorite talk of the convention!  Thanks for giving
          it.

   Comment by Guy McCaldin on July 2, 2014 at 10:52pm
          It was an excellent talk.  My only feedback is that is that it
          would have been interesting to have a closer look at the
          economics, particularly when compared to satellite imagery
          already in use in agriculture, but my guess it that this is a
          detail that is still being worked out.

   Admin Comment by Gary Mortimer on July 3, 2014 at 1:18am
          Realistic I like! This is a fantastic talk. I was speaking to a
          guy last night that who is taking his push pull Cessna several
          thousands of km to survey a huge area with a Lidar and I was
          floored when he said he was only being paid $1 a hectare for the
          processed data, aircraft time and accommodation. His over heads
          must be huge, if he is prepared to go out with a manned aircraft
          and commercial lidar at that rate how could I compete with
          simple data...

   Comment by Gerard Toonstra on July 3, 2014 at 4:31am
          Very good presentation, state-of-the-art in what you do with
          collected data using affordable systems.

          What you can do with multirotor is increasing. 35 minutes is
          well within reach now and also affordable. You'd want to work
          with those if you have complicated areas (lots of trees) or just
          a small farm where you don't want to fly over adjoined patches.
          its slower speed allows you to make much more detailed ortho's
          than fixed wing because you can fly a lot lower, so there are
          definitely uses for it.

          You can chop up large orthos using some tools:
          http://www.gdal.org/gdal2tiles.html  and tilemill for example.
          This allows you to manage the amount of data sent across or
          otherwise how many images are kept in memory at the same time.

   Comment by John Stuart on July 3, 2014 at 6:43am
          +1 for the improving prospects for multi-rotors, as the
          technology allows them to push flight times. In vineyards too,
          its not easy to find a decent spot to land a fixed-wing.

          Regarding the economics of the service, I found it interesting
          that you started out with offering the services for free, I've
          had to do the same thing and hope that the data is useful enough
          for the client to buy in at some point.

          Thanks for the presentation, its great to hear what you guys
          have already achieved in little over a year. Your willingness to
          share your experiences is truly appreciated.

   Comment by Daniel McKinnon on July 3, 2014 at 10:04am
          Thanks for all the great feedback! DroneCon was a lot of fun and
          I was really glad to have been given the opportunity to present.

          There have been a bunch of questions about economics and the
          answer is a little bit tautological. The data is worth the value
          it creates for the farmer. The small minority of farmers who buy
          satellite imagery pay around $2.50 an acre from Digital Globe,
          but the data are generally too dated for high value applications
          like fertilizer prescription maps and the farmers are left to do
          the interpretation. Crop consultants typically charge
          $10-$15/acre to provide general field recommendations that are
          based on weekly walk-throughs, without the spatial precision
          given by UAV-collected imagery. To really extract revenue out of
          imagery in agriculture, it's critical to show value to the
          farmer. We've found that value in, to a lesser extent,
          identifying weeds and quantifying coverage and, to a much
          greater extent, generating prescription maps for precision
          applicators.

          The software packages currently available to stitch images
          require a significant sidelap on canopied fields, which
          typically creates a linear flight of around 25 km for a quarter
          section (160 acres). We would love to use a multi-rotor for the
          ease of takeoff, landing, and planning, but have not encountered
          a system with this kind of endurance yet. I think future
          solutions for image processing will eliminate the need for so
          much sidelap and could allow us to reintroduce a multi-rotor,
          but that will be a little way down the road.

          Best,

          Daniel

   Comment by Andrew Rabbitt on July 4, 2014 at 8:31pm
          Fantastic presentation Daniel!  Congratulations.

          So, fixed-wing quasi-VTOL with 25+km range is a good target for
          a useful airframe/system?  That should be doable.  I assume
          you're carrying 2 x consumer cameras with this - a 350g-ish
          payload?

   Comment

You need to be a member of DIY Drones to add comments!

   Join DIY Drones
     * ‹ Previous
     * 1
     * 2
     * Next ›
     * Page 2_ [BUTTON Input] (not implemented)__

   RSS

   Welcome to
   DIY Drones

   Sign Up
   or Sign In

   Or sign in with:
     *
     *
     *
     *
     *

Top Content

   Edit
   1     PPM mixed up channels

      PPM mixed up channels

   2     ArduIMU V4 on Kickstarter

      ArduIMU V4 on Kickstarter

   3     SUPER DRONE !

      SUPER DRONE !

   4     ArduCopter-3.2 beta testing

      ArduCopter-3.2 beta testing

   5     How to discover a crash reason - APM

      How to discover a crash reason - APM

   6     AUAV-X2 ( the revised version of X1 ) is alive

      AUAV-X2 ( the revised version of X1 ) is alive

   7     AC-3.1 autotune support discussion

      AC-3.1 autotune support discussion

   8     My 3DR Y6 flipped and crashed when a motor died. Isn't the Y6 (and
         X8) supposed to compensate in this situation?

      My 3DR Y6 flipped and crashed when a motor died. Isn't the Y6 (and X8)
      supposed to compensate in this situation?

   9     Proposed 8-Prop Configuration - Is this practical or possible?

      Proposed 8-Prop Configuration - Is this practical or possible?

   10    Infrared-tracking Gimbal

      Infrared-tracking Gimbal

     * RSS
     * View All

Groups

     * PIXHAWK

PIXHAWK
       190 members
     * X-UAV Talon

X-UAV Talon
       58 members

     * ArduPlane User Group

ArduPlane User Group
       1080 members
     * Arducopter Y6 Owners

Arducopter Y6 Owners
       262 members

     * Agricultural UAVs

Agricultural UAVs
       546 members

     * View All

                                 [INS: :INS]

   [miniuavbadge_MED.jpg?width=120] Season Two of the Trust Time Trial
   (T3) Contest
   A list of all T3 contests is here. The current round, the Drone
   Delivery Challenge, is here

   © 2014   Created by Chris Anderson.   Powered by Ning

   Badges  |  Report an Issue  |  Terms of Service

Hello, you need to enable JavaScript to use DIY Drones.

   Please check your browser settings or contact your system
   administrator.
   [p?c1=2&c2=6770185&cv=2.0&cj=1]
