   #Atlas Obscura: Feed Your Wonder and Curiosity

   Issues with the site? Please let us know.
   Atlas Obscura
     * About Us
     * Work with Us

   Sign up / sign in
     * Places
       prev next
       Niah Caves
       Niah, Malaysia

Niah Caves
       26 Sep 2014
       Noble–Seymour–Crippen House
       Chicago , Illinois

Noble–Seymour–Crippen House
       26 Sep 2014
       95th Street Bridge
       Chicago, Illinois

95th Street Bridge
       26 Sep 2014
       Laboe Naval Memorial
       Laboe, Germany

Laboe Naval Memorial
       26 Sep 2014
     * Articles
       prev next
       [blank-dc8c0ef4803588f561adaaa11604bbaf.png]

Join Kcymaerxthaere and Atlas Obscura on the Road to a Parallel Universe in
the Midwest
       26 Sep 2014
       [blank-dc8c0ef4803588f561adaaa11604bbaf.png]

Holloways: Roads Tunneled into the Earth by Time
       25 Sep 2014
       [blank-dc8c0ef4803588f561adaaa11604bbaf.png]

Doomed Belgian Village Strives for Salvation by Inviting Street Artists into
the Ghost Town
       25 Sep 2014
       [blank-dc8c0ef4803588f561adaaa11604bbaf.png]

Turning Museums Inside-Out with Beautiful Visible Storage
       24 Sep 2014
     * Events
       prev next

Obscura Society NY and Other World Tours Present: Untold Secrets of Central
Park

October 1, 2014

The New York Transit Museum and Atlas Obscura Present: Power Play

October 2, 2014

Obscura Society NY Presents: From Sunshine to Shadow

October 4, 2014

Obscura Society LA: The Dark Side of Flora - A Tour of LA's Toxic Plants

October 5, 2014

     * Send a tip
       Sign in or Sign up to add a place, save your favorite entries,
       create a map of places you've visited, and more!
     * Random Place
       Close your eyes and spin the globe.

   what: ____________________ near: ____________________ Search

   Baia, Italy

The Sunken City of Baia

A submerged archeological park still holds the wonders of a Roman Sodom

   underwater, archaeology, statues, ruins
   2
   I've been here
   108
   I want to go here
   - Button-facebook-100x100
   - Button-twitter-100x100
     * [image.jpg]
       One of the many preserved statues beneath the water.
       Photo by The Underwater Archeological Park of Baia
     * [image.jpg]
       Some of the preserved tile work.
       Photo by SkareMedia
     * [image.jpg]
       Photo by Wikipedia | Copyright: Creative Commons

   Full screen
   Contributor: SkareMedia (Author)
   Edit this place

   In its heyday, the Classical Roman city of Baia was the hedonist Las
   Vegas of the time, but now its remains are partying beneath the waves.

   A prominent resort city for centuries, Baia catered to the recreational
   whims of the rich and powerful among the Roman elite. The city, which
   was located over natural volcanic vents, was famous for its healing
   medicinal hot springs which occurred all around the city and were quite
   easy to build spas over. Some of antiquity's most powerful figures such
   as Nero, Cicero, and Caesar were known to have visited the city and a
   number of them actually built permanent vacation villas there.

   Unfortunately, the good times were not to last and the city was sacked
   by Saracens in the 8th century. By 1500, the remains of the formerly
   luxurious town were abandoned. After the city remains were emptied, the
   water level slowly rose due to the same volcanic vents that were once a
   draw to the area, and most of the ancient ruins were drowned under the
   shallow waters of the bay.

   Today the ancient remains of Baia can be visited in one of the world's
   few underwater archeological parks. Visitors can view the crumbled
   structures and amazingly preserved statuary of the city through
   glass-bottomed boats, snorkeling, or even scuba dives which allow
   people to actually swim amongst the copious ruins. While the city is no
   longer a resort, its waters still hold wonders.
   Edited by: michelle (Admin), Martin, EricGrundhauser (Editor), Rachel
   (Admin)
   Share on Facebook (-) Twitter (-) Share
   Herodium

Herodium

Tall Furaydis, Israel

   Termessos

Termessos

Antalya Province, Turkey

   The Site of The Garden of the Hesperides

The Site of The Garden of the Hesperides

Larache, Morocco

Related Places:

   See 24 more places filed under underwater, 42 more places filed under
   archaeology, and 211 more places filed under ruins.
     * Hours
     * Website
          + The Underwater Archeological Park of Baia

     * Address
       via Napoli 1, Baia, Italy



Cost

   See an error? Know more? Edit this place.

Sources

    1. http://www.reidsitaly.com/destination...
    2. http://en.wikipedia.org/wiki/Baiae
    3. http://skaremedia.com/365/?p=1018ItI

Map/Directions

   Refresh results in this map
   Open in Google Maps

Users Who've Been Here

   2
   I've been here
   SkareMedia (Author), salfo

Users Who Like This Place

   108
   I want to go here
   cjosephbell, danielrthorne, Rin353, thomlang, photographernine, Ingigi,
   stoves186, alltheryans, arielshizzledizzle, whereismymnd, topalexx13,
   tobywatfa, Vanguard, epickering11, zephyr85, shelley582, Paulo da
   Silva, cbrown02, graemelennon, julnyes, duncanchappell, lokiracer,
   MinaKay, tadhgin, tprowset, tbar, annev, StevenNyikos, cptnxanarchy,
   xtashterror, cerulleal, n33n0, meganjones1, gwenleif, horneby,
   diseasefire, ayharkey, facebookbryana, heretik77, bwaggener,
   tuanhle1989, pinkiepromiss, ficklefairy, nemophilist, erinmelanson, C
   Schwartz, ch4roon, embentley1, vlight, mojotexas, gardinerp, njungck,
   sterlingh, summerjadekeen, andermas, jacqui, realindsey,
   lonelydreamergirl1718, johnrchay (Author), drevans2010, Captain FLAM,
   Anton, cattmross, mollyjohnh, philoursmars, okn0tok, hysul, claudious,
   lillypod, debbiesue, jbuchli, darkstalkerlord, Posmundo, gablerks,
   tchomp, agnedr, cynthiamonster, y2jenn, emgeedee, iamtrinket, stefF,
   kazzie, Britt Djmp, Luke Cata, p, suesviews, kristamsharp,
   jamesboneill, lmelachi, ronaldapadron, Shaynaaa, levant2645,
   shannonheaton (Editor), samanthapfleger, Kevin OKeeffe, Fina, zingara,
   moodbeast, wurzeltod, Queen Bee, sirhugh15, Tourniquette, hanna92,
   emanuelletomato, alliemattson, macfromak

   Want to go on an adventure?
   Sign up to hear about our events!
   ____________________ (BUTTON) Go

Nearby

   1 / 5
   Monte Nuovo

Monte Nuovo

Pozzuoli, Italy

   The entrance to the cave.

Cave of the Sibyl - Antro della Sibilla

Pozzuoli, Italy

Phlegraean Fields

Pozzuoli, Italy

Fontanelle Cemetery Caves

Naples, Italy

   "Venus Kallipygos" - "Venus with the lovely ass"

Gabinetto Segreto

Naples, Italy

Catacombs of San Gennaro

Naples, Italy

   close

I've Been Here

   Nice. This place has been added to your Traveler's Map, showing all the
   amazing places you've been.
   Icon-camera

   So, what was it like? Tell us about your experience!
   no thanks

   close

I want to go here

   Great! This has been added to your very own Compendium of Wonders: your
   collection of all the places that amaze you, inspire you, and that you
   want to travel to.
   Icon-plane
   Okay!

See Our Collection of
Curious Facts

   [image.jpg]
   Share:
   Tweet
   Refresh

This is what we believe:

    1. 01. There is something new under the sun, every day, all over the
       world.
    2. 02. Around the corner is something that will surprise the hell out
       of you.
    3. 03. Atlas Obscura is for people who still believe in discovery.

Our Popular Destinations:

   China Minnesota Boston Japan Nevada Illinois Texas Vermont
     * Home
     * About / Contact
     * FAQ
     * Join our team / Internships
     * Terms of Use

   © 2014 Atlas Obscura. All rights reserved.
   View Mobile Site

   close

Sign In

   or Sign Up
   Sign in with
   Facebook
   or
   Email ____________________
   Password ____________________
   Forgot your password?
   Sign in
   [ ] Remember me

   close

Sign Up

   already have an account?
   Sign In
   Sign up with
   Facebook
   or
   Email ______________________________
   Password ______________________________ ______________________________
   How many tentacles does an octopus have? ______________________________
   Sign up

   close

Join our mailing list!

   Join one of our regional event announcement lists for first crack at
   upcoming explorations near you. 100% spam free, we promise.
   [X] I love adventure, tell me about events near me!
   Confirm your city: [Austin________]
   Location: ____________________
   [X] I've got a curious mind. Send me weekly wonders!
   Submit

   Quantcast

   Quantcast

   [p?c1=2&c2=17564338&cv=2.0&cj=1]
