   #Daily Intelligencer

   NYMag.com Daily Intelligencer Vulture The Cut Science of Us Grub Street
   Bedford & Bowery

   FOLLOW:
   Facebook Twitter
     * UserName

   LOG IN REGISTER

New York Logo Intel

   NY Magazine cover Subscribe to New York Magazine Give a Gift
   Subscription of New York Magazine iPad Edition of New York Magazine

Sections

   Find a: Restaurant Bar Store

Sites

   NYMag.com Daily Intelligencer Vulture The Cut Science of Us Grub Street
   Bedford & Bowery Twitter Facebook

Sections

   Home News & Politics Daily Intelligencer Jonathan Chait Annie Lowrey
   Frank Rich Kevin Roose Chris Smith Entertainment Vulture Art Books
   Classical & Dance Movies Music Theater TV Agenda: To Do This Week
   Fashion The Cut Beauty Fashion News & Trends Fashion Shows Street Style
   Celebrity Style Designers Models Goods & Product Picks Love & War
   Restaurants Restaurants Search & Menus Grub Street Best of NY Food
   Cheap Eats Where to Eat 2013 Recipes Bars Bar Search Best of NY
   Nightlife Stores Store Search Best of NY Shopping Home Design Goods &
   Product Picks The Magazine Subscribe Now Give Gift Subscription
   Download iPad Edition Buy Back Issues View Current Issue Online Issue
   Archive Customer Service Media Kit

Search

   ____________________ (BUTTON)

Plus

   Travel Design Dates Weddings Real Estate Doctors NYC Tourist Guide Best
   of New York Issue
   Daily Intelligencerthe tech economy April 11, 2014 12:04 p.m.

The Problem With Profitless Start-ups

   By Kevin Roose Follow @kevinroose

   Should middle-class retirees be subsidizing my delivery meals and car
   rides?

5.9k Shares

   Share 3.3k Tweet 1.7k Share 782 Share 110 Share Email Print (BUTTON)
   Close Dialog Icon

Share

   Photo: Courtesy of Spoonrocket

   Yesterday, I ordered lunch from a gourmet meal-delivery start-up called
   SpoonRocket – a takeout container of sirloin au poivre and roasted
   cauliflower that was shuttled to my door in exactly 11 minutes, costing
   me $8. I then took an UberX car to a meeting across town, paying
   roughly $10 for a 15-minute ride. On my way, I pulled out my phone to
   see about getting my broken dryer fixed through Handybook, which
   provides on-demand repairs in the Bay Area for less than a local
   handyman would charge.

   There are dozens more services like these operating in and around San
   Francisco – Homejoy for cleaning, BloomThat for flowers, Postmates for
   courier service, and on and on. Most of them provide cheap, convenient
   amenities at the tap of a smartphone app. Few of them are profitable on
   a corporate level. And together, they’ve formed the backbone of a
   strange urban economy: one in which massive venture-capital injections
   allow money-losing start-ups to flourish, while providing services that
   no traditional, unsubsidized business can match. It’s an economy built
   on patience, and the hope that someday, after the land grab is over and
   the dust has settled, a better business model will emerge.

   It’s hard to know which of today’s new start-ups are unprofitable. But
   in some cases, losing money is kind of the point. I have no inside
   information on SpoonRocket's financials, for example, but I imagine
   that the company books a loss of a few cents every time I click the
   order button. (There’s just no way, short of a supply-chain miracle,
   that my $8 covers the cost of preparing a gourmet lunch, driving it to
   my house, and paying all the drivers and cooks and engineers and
   assorted other costs associated with running their business.) But
   SpoonRocket doesn’t have to make money, because it’s just raised $10
   million in venture capital expressly so it can keep its prices low. The
   metric its investors care about right now is user growth, not profits.
   And if, indeed, the company is selling meals for less than they cost to
   make, those investors are willing to fill the gap.

   This business model is great for consumers. As a result of start-ups’
   willingness to lose money for months or years at a time, I get cheap,
   fast services that come with an effective subsidy that can add up to
   thousands of dollars a year. But they're problematic for the businesses
   themselves. Unlike Amazon or Google (which have profitable core
   operations that subsidize the money-losing services elsewhere in their
   business), or Uber (which uses the profits from its high-margin Uber
   Black and Uber SUV lines to subsidize its low-margin UberX service),
   many of today’s start-ups have no profitable parent company pouring in
   money. They’re simply taking millions of dollars in venture capital
   with the hope of keeping prices low, pushing rivals out of the market,
   and eventually finding a way to turn a profit.

   There are several worrying things about this new, profitless-on-purpose
   way of doing business. First is that the while some of the money used
   to fund money-losing start-ups comes from rich Silicon Valley
   investors, some large amount of it comes from public pensions, college
   endowments, and other, more modest sources. Lyft backer Andreessen
   Horowitz, for example, has gotten investments from the Imperial County,
   California, Employee Retirement System and the University of Michigan;
   the Tennessee Consolidated Retirement System invests money with
   SpoonRocket backer General Catalyst. If you asked them, I'm sure that
   firefighters in Memphis and public schoolteachers in El Centro would
   have no idea that their retirement funds are being used to lower the
   price of my delivery lunches and rides across town. But that’s exactly
   what’s happening. And when these venture-backed price wars happen in
   dozens of high-end service sectors all at once, you have a strange
   cultural phenomenon in which Main Street dollars are being used to
   finance the lifestyles of cosmopolitan yuppies.

   The second issue with the venture-backed service economy is the Amazon
   problem – specifically, the practice of selling goods at or near a loss
   creates a deeply unfair competitive terrain for regular businesses. A
   start-up can sell a $10 lunch for $8 because it has money in the bank
   and investors who will rush in with more when the supply runs low. But
   if my local sandwich shop tries to do the same thing, it won’t make
   next month’s rent. The same goes with non-retail service businesses.
   Taxi companies had a decent chance of competing with UberX in its early
   days. But now that UberX and Lyft are both slashing prices to the bone
   with the assistance of millions of dollars in venture capital, the
   fight simply isn’t fair.

   In the context of international trade, this kind of predatory pricing
   (selling goods at or below cost in order to drive out rivals) is often
   illegal. There’s a reason why it should trouble us domestically, too
   – trying to compete in the VC-backed economy as a profit-conscious
   business is like running a triathlon with ankle weights.

   The third problem is that, as companies like Kozmo and Webvan learned
   in the first dot-com crash, the music stops eventually. At some point,
   investor patience wears thin, and the businesses that are still losing
   money on a per-unit basis tend to shrivel and die. When that happens,
   what’s left? A hole in the local economy where the local sandwich shop
   used to be, and nothing to fill the void. Given enough time and enough
   venture-backed land grabs, we could end up with an oddly configured
   service sector that contains a fraction of the jobs and utility it did
   before the subsidized prospectors moved in.

   Cushions for emerging business models aren't all bad – not every
   company should be forced to make a pretty P&L right out of the gate,
   and without patient investors and other forms of subsidy, we wouldn't
   have companies like Twitter or Amazon, or things like electric cars and
   solar panels. And, as I said, the venture-backed economy is amazing for
   the people who live in it. In the history of the world, there’s never
   been a better time to be a consumer in San Francisco or New York than
   today, what with our cornucopia of cheap, on-demand services. I would
   miss my cut-rate sirloin and cheap Ubers to the airport if a regulatory
   authority or a market crash took them away.

   But you can see how, on a grand scale, the existing model could become
   problematic. The only way the loss-making venture-backed economy can
   keep chugging along is if there is a constant supply of new money
   coming in at ever-higher valuations, subsidizing low prices and making
   earlier investors whole. Eventually, as in Amazon's case, the public
   markets may have to bear some of the subsidy. It’s a kind of benevolent
   Ponzi scheme, one that results in a lot of very cool services being
   provided at or below cost to a select group of urban consumers, and a
   lot of traditional businesses being forced to paddle hard to stay
   afloat. The profitless start-up model should worry us about the future
   of commerce and competition, even as we take advantage of its gifts.

Tags:

   the tech economybusinesstech

5.9k Shares

   Share 3.3k Tweet 1.7k Share 782 Share 110 Share Email Print (BUTTON)
   Close Dialog Icon

Share

Check out our new blog:

   Like UsFollow Us

Most Viewed Stories

   The Best Episode for Each Gilmore Girls Character

11.6k Shares

   Share Tweet

   How the 0.00003 Percent Lives

3.9k Shares

   Share Tweet

   Taylor Swift Achieves Meme-Inception

105.2k Shares

   Share Tweet

   The New York Post Wastes Absolutely No Time Attacking Chelsea Clinton's
   Baby

365 Shares

   Share Tweet

   10 Things I Learned at My First White-People Wedding

1.1k Shares

   Share Tweet

   Saturday Night Live Recap: Chris Pratt and the Guardians of 30 Rock
   Save the Day

150 Shares

   Share Tweet

   Rare Photos of Debbie Harry From the Early Days of Blondie

81.2k Shares

   Share Tweet

   Who Would Donate a Kidney to a Stranger? An ‘Anti-Psychopath’

5.4k Shares

   Share Tweet

   George Clooney and Amal Alamuddin Are Now Married

580 Shares

   Share Tweet

   Outlander’s Ronald D. Moore, Diana Gabaldon, and Others Break Down the
   Midseason Finale

187 Shares

   Share Tweet

Most Read

   How the 0.00003 Percent Lives

3.9k Shares

   Share Tweet

   The Best Episode for Each Gilmore Girls Character

   Taylor Swift Achieves Meme-Inception

   The New York Post Wastes Absolutely No Time Attacking Chelsea Clinton's
   Baby

   Tom Cotton Is Now the Perfect Republican

   Today in ‘Paul Krugman Is Definitely Not Arguing With David Brooks’

   Ferguson Police Chief’s Attempt to Make Peace Sparks New Clash With
   Protesters

From Rolling Stone

   Fight the Power: Spike Lee on 'Do the Right Thing'

From Newser

   Pope: No Legalizing Drugs

   ‘Telegenically Dead Palestinians’: Why Israel Is Losing the American
   Media War

   Does Anyone Outside Silicon Valley Even Want a Smartwatch?

   Sex Without Fear

2014 Summer Guide

   Things to Watch, Hear, Read, and Do, All Summer Long

Daily Intelligencer

   Who Would Donate a Kidney to a Stranger? An ‘Anti-Psychopath’

Daily Intelligencer

   Saturday Night Live Recap: Chris Pratt and the Guardians of 30 Rock
   Save the Day

Daily Intelligencer

   10 Things I Learned at My First White-People Wedding

Daily Intelligencer

   Why Men Never Remember Anything

Daily Intelligencer

   George Clooney and Amal Alamuddin Are Now Married

Latest News on Daily Intelligencer

   9/28/2014 at 10:39 p.m.Rikers Island Will Stop Putting Teens in
   Solitary Confinement

   It’s part of the “first round of changes” at the embattled facility.
   9/28/2014 at 8:51 p.m.Martin O'Malley Is Campaigning For...

   The Maryland governor is rallying the vote, for 2014 and beyond.
   9/28/2014 at 8:50 p.m.The Untold Story of How the Apple Store Cube
   Landed in Midtown

   Who came up with the idea of placing a 30-foot square glass cube — the
   world’s “smallest skyscraper” — in the middle of the GM Building plaza?
   9/28/2014 at 8:15 p.m.Tom Cotton Is Now the Perfect Republican

   Arkansas once again provides a glimpse of a party's future.
   9/28/2014 at 8:00 p.m.The Other Front in the Israel-Palestine Conflict:
   Hummus Ads

   "You're either a member or you're not," says the slogan.
   9/28/2014 at 6:24 p.m.The Chokehold Situation in NYC Is Not Good

   The Civilian Complaint Review Board has completed its report on the
   NYPD's use of the prohibited practice.
   9/28/2014 at 5:16 p.m.Three Arrested for Anti-LGBT Attack in Brooklyn

   It's being treated as a hate crime.
   9/28/2014 at 3:40 p.m.The New York Post Wastes Absolutely No Time
   Attacking Chelsea Clinton's Baby

   We wouldn't expect anything less.
   9/28/2014 at 2:00 p.m.Cops Searching for Suspect in Shooting of
   Ferguson Police Officer

   An off-duty St. Louis cop was also shot.
   9/27/2014 at 4:16 p.m.Fox News Bros Forced to Apologize for
   Middle-School-Style Sexist Jokes

   Well, one apologized — the other just made another dumb joke.
   9/27/2014 at 2:23 p.m.Governor Cuomo Is Spending the Weekend in
   Afghanistan

   Along with some other governors.
   9/27/2014 at 1:37 p.m.Woman Sexually Assaulted Inside Her Upper West
   Side Apartment

   Her assailant left his hat behind.
   9/27/2014 at 1:00 p.m.Mayor De Blasio Stands by Aide, Despite
   Boyfriend’s Sketchy Past

   Chirlane McCray's chief-of-staff, Rachel Noerdlinger, is in a longtime
   relationship with a convicted felon.
   9/27/2014 at 2:37 a.m.Chelsea Clinton’s Baby Is Here, and She Didn’t
   Name It Liam [Updated]

   Clinton and husband Marc Mezvinsky went with Charlotte.
   9/26/2014 at 5:58 p.m.Why Not Drug Test Everyone via Sewage?

   Genius.
   9/26/2014 at 5:54 p.m.Sarah Palin Almost Remembers the White House
   Address

   1400 Pennsylvania Avenue? So close.
   9/26/2014 at 4:29 p.m.Britain Agrees to Start Bombing ISIS As Well

   The campaign could take "not months but years," David Cameron warned.
   9/26/2014 at 4:02 p.m.The 3-Boob-Lady Is Already a Halloween Costume

   It's hilariously bad, too.
   9/26/2014 at 2:47 p.m.Palestinian Leader Mahmoud Abbas Uses U.N. Speech
   to Accuse Israel of ‘War of Genocide’

   Remember, this is the one Israel doesn't totally hate.
   9/26/2014 at 2:30 p.m.Man Dies As He Lived: Despising the Kardashians

   "He despised anything to do with the Kardashians."
   9/26/2014 at 1:35 p.m.What If the Regulators Are As Bad As the Banks?

   A whistleblower argues that the New York Fed's regulators defer to
   Goldman Sachs' bankers. And she has the tape to prove it.
   9/26/2014 at 12:58 p.m.Woman Beheaded by Co-worker at Oklahoma Food
   Plant

   The attacker is a disgruntled former employee.
   9/26/2014 at 12:13 p.m.Kim Jong-un Is Missing, Might Have Gout

   The only case in North Korea ...
   9/26/2014 at 12:11 p.m.The Future of Reading, According to Longform

   Can an app filled with aggregated content make both readers and writers
   happy?
   9/26/2014 at 11:34 a.m.Mail Carrier Actually Mail Hoarder

   That's a lot of undelivered mail.
   9/26/2014 at 10:10 a.m.Jon Stewart Aired That Contentious Washington
   Redskins Segment Last Night

   The Daily Show aired the segment despite the fact that some Redskins
   fans said they felt "in danger."
   9/26/2014 at 9:49 a.m.More Than 3,000 Europeans Are Now Fighting for
   ISIS

   Strikes continue against the group as the FBI identifies a beheading
   suspect.
   9/26/2014 at 9:26 a.m.ESPN Is Sick of Bill Simmons’s ‘Bad Boy,
   Let’s-Go-to-Vegas’ Attitude, But That’s Bill Simmons

   The network explains its punishment.
   9/26/2014 at 8:52 a.m.Today in ‘Paul Krugman Is Definitely Not Arguing
   With David Brooks’

   The world's most awkward debate continues.
   9/26/2014 at 8:43 a.m.Derek Jeter Can’t Go Home Again

   In his final game at Yankee Stadium, a last bit of life-giving naïveté
   for the fans.
   9/26/2014 at 4:33 a.m.In His Yankee Stadium Finale, Derek Jeter Adds to
   His Legend

   He got the game-winning hit in the bottom of the ninth.
   9/26/2014 at 4:05 a.m.Ferguson Police Chief’s Attempt to Make Peace
   Sparks New Clash With Protesters

   Also, police fired their PR consultant over a reckless homicide
   conviction.
   9/26/2014 at 3:51 a.m.Derek Jeter Ends Yankees Career With Dramatic,
   Game-Winning Hit

   Fans were just hoping it wouldn't rain.
   9/26/2014 at 2:07 a.m.Mayor de Blasio Has Ruined Groundhog Day Forever

   We now know the truth about Chuck. Can we ever trust his highly
   inaccurate weather predictions again?
   9/26/2014 at 12:00 a.m.How the 0.00003 Percent Lives

   Your typical American billionaire is a 63-year-old Wall Street type who
   went to Penn and owns four houses.
   9/25/2014 at 11:13 p.m.Ray Rice Video Was Sent to NFL’s Security Chief
   in April

   Unsurprisingly, the NFL still says no one ever saw it.
   9/25/2014 at 5:46 p.m.Local News Anchor Mocks Food Stamps, Drops F-Bomb

   Smooth, bro.
   9/25/2014 at 4:48 p.m.Brooklyn Teacher Arraigned for Sexual Abuse of 5
   Students

   At P.S. 249 in Brooklyn.
   9/25/2014 at 3:38 p.m.If Derek Jeter’s Last Home Game Gets Rained Out,
   the Yankees Automatically Make the Playoffs, Right?

   The forecast says rain in the Bronx tonight.
   9/25/2014 at 2:38 p.m.Iraq Claims ISIS Is Planning Subway Attacks in
   NYC and Paris

   U.S. officials don't seem too worried.
   9/25/2014 at 1:38 p.m.Ferguson Police Chief Finally Offers Slightly
   Awkward, PR-Scripted Apology for Killing Michael Brown, Abusing
   Protesters

   "For any mistakes I have made, I take full responsibility."
   9/25/2014 at 12:39 p.m.Teen’s Violent Rape Shared on Snapchat

   One suspect is still missing.
   9/25/2014 at 12:26 p.m.The Many Deaths of Abubakar Shekau, Boko Haram’s
   Mysterious, Immortal Leader

   But the group seems to be splintering.
   9/25/2014 at 12:06 p.m.Eric Holder Is Just About Done Being Attorney
   General

   He'll step down as soon as a successor is in place.
   9/25/2014 at 11:59 a.m.Fox News Host Calls Female Fighter Pilot ‘Boobs
   on the Ground’

   Get it? Because women have boobs?
   9/25/2014 at 11:13 a.m.‘Too Big of a Screen to Discreetly Look at
   Porn’: All the Reasons People Hate the iPhone 6 Plus

   "iPhone 6 Plus screen too big to look at smut on my phone in public.
   FML this train ride sucks."
   9/25/2014 at 10:06 a.m.9 Arrested in Overnight U.K. Terror Raids As
   Strikes Against ISIS Continue

   Members and supporters of a banned group.
   9/25/2014 at 9:59 a.m.Dzhokhar Tsarnaev’s Marathon Bombing Trial Will
   Be in Boston, Eventually

   Starting January 5 instead of November 3.
   9/25/2014 at 9:37 a.m.Teacher Resigns After Telling Students She Wants
   to Program Robots to Kill Them

   What's the big deal?
   9/25/2014 at 9:21 a.m.This Is What It Looks Like When a Cop Shoots an
   Unarmed Black Man Who Was Just Reaching for His Driver’s License

   Stopped for not wearing hit seat belt, then shot in the hip.
   (BUTTON) Load More

From Our Partners

The Daily Beast

   ‘The Fappening 3’: More Celeb Nudes LeakLena Dunham’s Most Shocking
   ConfessionsThe Most Hated Man in Books

BuzzFeed

   Your New Favorite Pug Is Named Weezer And He's Awesome17 Insanely
   Exciting Things You Could Definitely Do Tonight11 Celebrity Tweets You
   Missed Today

Newser

   Amazon Jungle's Nutrient Source: Dead African FishEbola Death Toll
   Passes 3KObituary: Man 'Despised' the Kardashians

Upworthy

   This Man Wrote 6 Rules For Partying. I'd Follow 'Em.How One Legendary
   Sitcom Handled Date Rape In The '80s Makes Me Wish I Had Sinbad On
   Speed DialJust Watch This Man Draw For 2 Minutes And 30 Seconds. I Dare
   You To Tell Me He's Wrong.
   NY Magazine News & Features Restaurants Bars Entertainment Fashion
   Shopping Agenda Daily Intelligencer Vulture The Cut Grub Street
   Marketplace
   Privacy Terms Site Map About Us Contact Us Media Kit RSS Newsletters

   Copyright © 2014, New York Media LLC. All Rights Reserved. Vulture®,
   Grub Street® and The Cut® are registered trademarks of New York Media
   LLC.
   Teen Snaps Hospital Selfie After Deadly Crash

   Mailman Sold Some Weed on the Side

   Ad will collapse in seconds… (BUTTON) CLOSE
