   #Health IT Buzz » Introducing the Blue Button Connector Comments Feed

   Skip to this page's content

Health IT Buzz

The Latest on Health Information Technology from ONC

Connect:

     * ONC on Google
     * Connect with ONC on LinkedIn
     * Find ONC Documents on Scrib'd
     * Check ONC's YouTube Channel
     * Follow ONC on Twitter
     * Subscribe to the HealthIT Buzz Blog RSS Feed

Visit HealthIT.gov

     * EHR/EMR
          + Electronic Health & Medical Records
          + Meaningful Use
          + EHR Case Studies
          + Local Implementation Support
          + Privacy and Security of EHRs
     * Health Innovation
     * From the ONC Desk
     * ONC Programs
          + Beacon Community Program
          + Federal Advisory Committees
          + Regional Extension Centers
          + SHARP
          + State HIE
          + Community College Consortia
          + Curriculum Development Centers
          + Competency Exam Program
          + University Based Training
          + Rural Health

   Search this site for: Search______________ Search
   Health IT Buzz > Consumer Engagement > Introducing the Blue Button
   Connector

Introducing the Blue Button Connector

   February 24, 2014, 2:03 pm / Lygeia Ricciardi / Director, Office of
   Consumer eHealth, ONC , and
   Adam Dole

   Today at the HIMSS conference in Orlando ONC demonstrated the Blue
   Button Connector. This early release of the Connector website is an
   invitation to members of the growing Blue Button community to help to
   improve the website before it is more widely marketed to consumers and
   developers.

   The Blue Button Initiative is a public-private partnership based at the
   Office of the National Coordinator (ONC) in close partnership with the
   White House, US Department of Veterans Affairs, The Centers for
   Medicare & Medicaid Services, and the Department of Defense. Its
   objective is to engage and empower consumers and patients through
   electronic access to their own health information, which they can use
   to manage and improve their health and health care.

   WHAT WILL THE BLUE BUTTON CONNECTOR BE?

   The Blue Button Connector will be a website that helps consumers and
   patients to find their own health information online, and will help
   developers build tools that respond to the readiness of the market. It
   also will provide links to apps and tools for consumers that use
   structured electronic health data.

   A CONSUMER TOOL AND AN OPEN DATA RESOURCE

   The Connector was born out of a need for consumers to have a single
   place to get started in accessing their personal health information
   online via Blue Button.

   Although the number of organizations providing Blue Button access to
   data for consumers is growing (and is expected to increase
   significantly via implementation by eligible providers and hospitals of
   the Meaningful Use Stage 2 requirements that patients be able to view,
   download and transmit their health records electronically), many
   consumers still do not have access to their health data from any
   source. Even for those that do, obtaining it from multiple places can
   be, even with the help of the Connector, a time consuming process. We
   expect that in the near future consumers will be able to get their data
   directly from multiple sources via more seamless mechanisms. In the
   meantime, the Connector will help consumers to navigate within a
   fragmented industry and raises general awareness about the growing
   availability of electronic access to health data. The site also enables
   consumers to “shop with their feet” – to find providers and others who
   are offering electronic access to data.

   While developing the Connector for a consumer audience, we realized it
   also has great appeal for entrepreneurs and developers in the
   transparency it provides about what type of data is being made
   available and how it’s being made available (in what format, using what
   transport mechanism).  We are making this data available to developers
   through an open API. The Connector is also supportive of developers in
   that it provides a platform through which consumers and others can find
   the tools they develop that use structured health data.

   The Connector is the first ever open data source delivered through an
   open API that makes transparent the health data that is increasingly
   available to the public, which we believe will help to fuel the
   creation of new products and services. This is part of a broader push
   for open data spearheaded by the White House to liberate both
   government data and voluntarily contributed corporate data to fuel
   entrepreneurship, create jobs, and improve the lives of Americans in
   tangible ways.

   HOW THE CONNECTOR WILL SUPPORT THE BLUE BUTTON INITIATIVE

   The Blue Button Initiative encompasses the following activities:
     * Community engagement through the 500 member Blue Button Pledge
       Program, a voluntary effort through which organizations pledge to
       share health data electronically with consumers, build useful
       digital consumer tools, and spread the word publicly about the
       value of access to information. Organizations that share data with
       consumers via the Blue Button Pledge Program include health care
       providers, health insurance companies, pharmacies, labs, and state
       immunization registries. Approximately half of Americans have
       access to their health information via one or more of these
       sources.
     * Development and promotion of technical standards (called Blue
       Button +) to support the structured exchange of health data, which
       enables technology developers to build engaging and useful consumer
       tools.
     * Marketing the Blue Button logo as a brand that signifies both the
       availability of health data from a particular source, and the
       growing social movement toward consumer empowerment in a health
       context.

   Through the Blue Button Initiative we and our colleagues are working to
   realize a vision in which all Americans have access to one or more
   sources of digital health data about themselves, and can use it
   effectively to meet their health goals. The Blue Button Connector helps
   to move us closer to that vision by providing greater transparency and
   information for both consumers and developers. Later this year we will
   to do a coordinated rollout of Blue Button PSAs in partnership with
   committed organizations in order to raise the profile of Blue Button
   among the general public. If you would like to participate, please
   contact us at bluebutton@hhs.gov

   WHAT YOU CAN DO

   Today we are demonstrating an early version of the Blue Button
   Connector.  The usefulness of this site will grow as the community
   contributes to it. We invite you to give us feedback on how to make it
   better, and let us know if you’d like to get your organization or app
   listed on it: bluebutton@hhs.gov

   Tags: Blue Buttonconsumer engag

   Posted under: Consumer Engagement
   « Patient matching findings released
   Practical Playbook Merges Public Health/Primary Care Using Health IT »

One Comment

    1. Chandresh J. Shah says:
       February 27, 2014 at 7:39 am
       A great initiative. I would just urge that we remain focused and
       true to the mission of building a single place that “helps patients
       find their health information online in a single place”. This will
       allow the second part of download, transmit and view.
       Reply to this comment

Leave a ReplyComment Policy

   Click here to cancel reply.

   ______________________ Name (required)

   ______________________ Email (will not be published) (required)

   ______________________ Website URL


   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   Enter your text comment

   Submit Comment
   CAPTCHA Image
   Refresh Image
   ____________________ CAPTCHA Code *
   Submit Comment

     * Most Popular
       Developing a Shared, Nationwide Roadmap for Interoperability
       SAFER Guides will help optimize for safety
       HITECH Turns 5
       EMR vs EHR – What is the Difference?
       Patients Play a Vital Role in Improving the Quality of Information
       in their Medical Records
     * Featured Author
       Karen B. DeSalvo, M.D., M.P.H., M.Sc.'s Avatar

Karen B. DeSalvo, M.D., M.P.H., M.Sc.
       View posts
       View all Authors
     * Archives
       [Select Month And Year]
     * Get Updates

Subscribe to Email Alerts
       Please submit your email address to receive alerts when new posts
       are published on HealthIT Buzz.
       ____________________ Enter email address
       Subscribe
     * RSS Feed

Subscribe to RSS
       Sign up to receive content updates to your My Yahoo!, Newsgator,
       Bloglines, and other news readers.
       Subscribe
     * Hot Topics
          + Consumer Engagement
          + Electronic Health Records
          + Federal Advisory Committees
          + Health Information Exchange
          + Rural Health
     * Tag Cloud
       beacon Blue Button consumer engagement EHR EHR adoption electronic
       health records health information exchange health innovation health
       IT health IT workforce HITECH interoperability Meaningful Use REC
       rural health

     * Home
     * Contributors
     * About
     * Archives
     * Blog Policy
     * Contact Us

     * Subscribe to the HealthIT Buzz Blog RSS Feed
     * Follow ONC on Twitter
     * Check ONC's YouTube Channel
     * Find ONC Documents on Scrib'd
     * ONC on LinkedIn
     * ONC on Google+

     * Accessibility
     * Privacy Policy
     * HHS.gov
     * WhiteHouse.gov
     * USA.gov
     * GobiernoUSA.gov
     * HealthIT.gov
