    #BillMoyers.com » Feed BillMoyers.com » Comments Feed BillMoyers.com »
   Preview: No Escaping Dragnet Nation Comments Feed

   IFRAME: //www.googletagmanager.com/ns.html?id=GTM-5FLXNP

     * Home
     * Topics
          + Activism
          + Arts & Culture
          + Civil Liberties
          + Democracy & Government
          + Economy & Work
          + Environment
          + Faith & Reason
          + Health & Science
          + History
          + Inequality
          + Justice
          + Media
          + Money & Politics
          + Society
          + War & Peace
     * Video
     * Take Action
     * Shows
     * Moyers Moments
     * Guests
     * TV Schedule

   BillMoyers.com
   ____________________ (BUTTON)
     * Home
     * Topics
          + Activism
          + Arts & Culture
          + Civil Liberties
          + Democracy & Government
          + Economy & Work
          + Environment
          + Faith & Reason
          + Health & Science
          + History
          + Inequality
          + Justice
          + Media
          + Money & Politics
          + Society
          + War & Peace
     * Video
     * Take Action
     * Shows
     * Moyers Moments
     * Guests
     * TV Schedule

     * SPOTLIGHT
     * Climate Change
     * Money & Politics
     * Economic Inequality
     * Bill’s Essays
     * Morning Reads

   ____________________ (BUTTON)

   IFRAME: player_embed_tag

Preview: No Escaping Dragnet Nation

   March 12, 2014

   Investigative reporter Julia Angwin talks to Bill about how America has
   become a dragnet nation where mass surveillance rules. Watch the full
   show now »
   View Comments

WATCH FULL SHOW

   The entire interview with Julia Angwin is available online. Watch now »

Related Features

     * Clip: Look Who Profits When You Sign up to Vote
     * Segment: Heidi Boghosian on Spying and Civil Liberties
     * Heidi Boghosian on Mass Surveillance

     * PODCAST
     * SHARE

Preview: No Escaping Dragnet Nation

   March 12, 2014

   This week, as the chairwoman of the Senate Intelligence Committee
   Dianne Feinstein publicly accused the CIA of spying on her committee’s
   computers, Bill talks with investigative reporter Julia Angwin, author
   of Dragnet Nation: A Quest for Privacy, Security and Freedom in a World
   of Relentless Surveillance.

   The book chronicles the indiscriminate tracking of our everyday lives —
   where government and business are stockpiling data about us at an
   unprecedented pace. Reporters are a prime target for internet snooping,
   says Angwin, “Journalists are the canary in the coal mine. We’re the
   first ones to seriously feel the impact of total surveillance, which
   means we can’t protect our sources. But what happens next? What happens
   next is we’re not good watch dogs for democracy. And that’s a very
   worrisome situation.”

   Julia Angwin covered the business and technology beat at The Wall
   Street Journal for 13 years, and is a Pulitzer Prize winner now working
   for the independent news organization ProPublica.

   Learn more about the production team behind Moyers & Company. Watch the
   full show »
   TOPICS: Democracy & Government, Economy & Work, Media
   TAGS: big brother, big data, cia, dianne feinstein, dragnet nation,
   edward snowden, FBI, julia angwin, mass surveillance, national
   security, privacy, propublica, security, senate intelligence committee
     * Share
     *
     *
     *
     *
     *

     *
     *
     *
     * submit to reddit
     *

   Are you aware of our Comment Policy?

   BillMoyers.com encourages conversation and debate around issues, events
   and ideas related to content on Moyers & Company and the BillMoyers.com
   website.
     * The editorial staff reserves the right to take down comments it
       deems inappropriate.
     * Profanity, personal attacks, hate speech, off-topic posts,
       advertisements and spam will not be tolerated.
     * Do not intentionally make false or misleading statements,
       impersonate someone else, break the law, or condone or encourage
       unlawful activity.

   If your comments consistently or intentionally make this community a
   less civil and enjoyable place to be, you and your comments will be
   excluded from it.

   We need your help with this. If you feel a post is not in line with the
   comment policy, please flag it so that we can take a look. Comments and
   questions about our policy are welcome. Please send an email to
   info@moyersmedia.com

   Find out more about BillMoyers.com's privacy policy and terms of
   service.
     * Anonymous
       And you are planning on airing this when?
     * NotARedneck
       The wealthy in the US have about the same proportion and disparity
       of wealth as the Russian upper classes had in the last half century
       of the Romanoffs. They both have a similar, minimal and largely
       detrimental effect on real wealth creation and use their position
       similarly to exploit the masses.
       Consequently, both require(d) a massive surveillance apparatus to
       keep the disaffection from bubbling over. The US has got to the
       point where it is very likely that, like Russia in 1917, democratic
       means will prove inadequate to reverse this crime.
     * http://www.billmoyers.com Theresa Riley
       WaveRunnerMN: Bill’s interview with Julie Angwin will air this
       weekend on many public television stations. You can check your
       local listings here: http://billmoyers.com/schedule. You can also
       watch the full interview here at BillMoyers.com starting Friday
       after noon.
       Thanks for your interest!
       Theresa @ Moyers

     * Connect With Us
     *
     *
     *
     *
     *

   [USEMAP:mco_widgette_sitewide.png]

House Ads

   [Landay-Hoh300x250b.jpeg]

   [House-ads-Bill-McKibben2.jpg]

   [Kumi.jpeg]
   Popular On Facebook
   SIGN UP FOR THE NEWSLETTER ____________________ (BUTTON) go
     * Home
     * About
     * Video
     * TV Schedule
     * Archives
     * Recent Shows
     * Widgets
     * Credits

footer widget

   Funding for Moyers & Company is provided by Anne Gumowitz; Carnegie
   Corporation of New York; Ford Foundation; The Herb Alpert Foundation,
   The John D. and Catherine T. MacArthur Foundation; Park Foundation; The
   Kohlberg Foundation; Barbara G. Fleischman; and by our sole corporate
   sponsor, Mutual of America.
   [foot-sig.gif]
   © 2014 Public Affairs Television, Inc. All rights reserved.
   Contact Us | Terms of Service | Privacy Policy

   Quantcast
