   #alternate RSS search

     * Fast Company logo
       Fast Company
     *

     * [fastcoexist-dark.svg] Exist
     *
     * [fastcodesign-dark.svg] Design
     *
     * [fastcocreate-dark.svg] Create
     *
     * [fastcolabs-dark.svg] Labs
     *

     *
     * Video
     *
     * Features
     *
     * Emails
     *
     * Issues
     *
     * Subscribe
     *
     *
     *
     *
          + Find Us
          +
          + Facebook
          + Twitter
     *
     *
          + Sign Out

   [Saul-Griffith-P4A0654.jpg] [fastcompany-dark-txt.svg] Fast Company

Saul Griffith

   Founder, Otherlab

   Australian-American inventor Saul Griffith has started seven companies,
   among them Makani Power, for which he invented an eco-friendly,
   efficient wind turbine. He received a MacArthur Grant in 2007.

   Quote

   "Energy literacy means you can see the waste in disposing of a plastic
   bottle after you've drunk water from some place on the other side of
   the world." »

   Key stories
   about Saul Griffith

   72. Saul Griffith
   Powering Down: Q&A With Saul Griffith, Makani Power

   Related People

     * Dale Dougherty

   More On Saul Griffith

   The Most Creative People In Business
     * Most Creative People
    [fastcompany-dark-notxt.svg]
       [3027624-poster-p-2-beyond-toy-story-how-to-build-a-creative-powerh
       ouse-the-pixar-way.jpg]
    Building The Next Pixar
     * Agendas
    [fastcompany-light-notxt.svg]
       [3028112-poster-p-2-austin-kleon-show-your-work.jpg]
    The 15-Minute Daily Habit That Will Change Your Career
     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3027019-poster-p-3-how-frozen-director-jennifer-lee-reinvented-the
       -story-of-the-snow-queen.jpg]
    How "Frozen" Director Jennifer Lee Reinvented The Story Of The Snow
       Queen
     * Creative Conversations
    [fastcompany-light-notxt.svg]
       [3023563-poster-p-1-jared-leto-on-creativity-commerce-and-lessons-f
       rom-surviving.jpg]
    Jared Leto On Creativity, Commerce, And Lessons From Surviving A $30
       Million Lawsuit
     * Most Creative People
    [fastcompany-dark-notxt.svg]
       [3025314-poster-p-1-can-creativity-be-taught-73-of-creative-people-
       say-yes.jpg]
    Can Creativity Be Taught? 73% Of Creative People Say Yes
     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3025566-poster-p-1-is-the-future-of-television-advertising-branded
       -tv-shows-chipotle-thinks-so.jpg]
    Chipotle Subtly Wraps The Future Of TV In A Warm Tortilla (Hold The
       Cheese?)
     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3026499-poster-p-1-complicated-what-teens-are-really-doing-on-thei
       r-protected-twitter-accounts.jpg]
    What Your Teen Is Really Doing All Day On Twitter And Instagram
     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3026162-poster-p-1-why-the-new-york-times-hired-a-biology-research
       er-as-its-chief-data-sci.jpg]
    Why The New York Times Hired A Biology Researcher As Its Chief Data
       Scientist
     * Most Creative People
    [fastcompany-dark-notxt.svg] [3025440-poster-p-mcp-1000-orange_0.jpg]
    Introducing Fast Company's Most Creative People In Business 1000

     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3025398-poster-p-1-how-isabelle-olsson-made-google-glass-beautiful
       .jpg]
    The Google Glass Redesign, And How Isabelle Olsson Made The Face
       Computer Into A Thing Of Beauty
     * Dialed
    [fastcompany-dark-notxt.svg]
       [3021377-poster-p-1-181-feature-pharrell-get-busy.jpg]
    Get Busy: Pharrell's Productivity Secrets
     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3025373-poster-p-1-broadli-networking-app-yay-nay.jpg]
    New Broadli App Will Help You Actually Use Your Sprawling LinkedIn
       Network

     * Most Creative People
    [fastcompany-dark-notxt.svg]
       [3024342-poster-p-1-nprs-first-ever-creative-director-on-the-inters
       ection-of-design-and-sto.jpg]
    A Glimpse Into The Future Of NPR, From Its First-Ever Creative
       Director
     * Most Creative People
    [fastcompany-dark-notxt.svg]
       [3024986-poster-p-1-etsy-creative-director.jpg]
    How Etsy's Creative Director Uses Intricate To-Do Lists To Free Up
       Big-Idea Brain Space
     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3024623-poster-p-1-the-30-day-challenge-how-googles-spam-king-tack
       les.jpg]
    The 30-Day Challenge: How Google's Spam King Tackles Constant
       Improvement

     * Most Creative People
    [fastcompany-light-notxt.svg]
       [3024681-poster-p-1-real-talk-about-work-life-balance-from-walking-
       dead-creator-robert-kirkman.jpg]
    "Walking Dead" Creator Robert Kirkman's Secret To Juggling Creative
       Projects
     * Most Creative People
    [fastcompany-dark-notxt.svg]
       [3025517-poster-p-1-allison-jones-the-woman-who-helped-spur-the-ris
       e-of-the-hollywood-geek.jpg]
    Allison Jones, The Woman Who Helped Spur The Rise Of The Hollywood
       Geek
     * Most Creative People
    [fastcompany-dark-notxt.svg]
       [3025254-poster-p-1-harpercollinss-chief-digital-officer-on-how-dat
       a-will-and-wont-save-pub.jpg]
    How HarperCollins's Chief Digital Officer Uses Big Data To Make
       Publishing More Profitable

     * Advertise
     * Privacy Policy
     * Terms
     * About Us
     __________________________________________________________________

   Fast Company & Inc © 2014 Mansueto Ventures, LLC.
