    #Quanta Magazine » Feed Simons Foundation » A New Physics Theory of
   Life Comments Feed

     * About Quanta Magazine
     * Biology (40)
     * Computer Science (12)
     * Mathematics (21)
     * Physics (39)
     * Q&A (8)

Quanta Magazine. Illuminating Science

   An editorially independent division of the Simons Foundation

   ____________________ Submit

   ( ) SimonsFoundation.org (*) Quanta Magazine

   Physics

A New Physics Theory of Life

   Jeremy England

   Katherine Taylor for Quanta Magazine

   Jeremy England, a 31-year-old physicist at MIT, thinks he has found the
   underlying physics driving the origin and evolution of life.

   By: Natalie Wolchover

   January 22, 2014

   Comments (134)

   print

   Why does life exist?

   Popular hypotheses credit a primordial soup, a bolt of lightning and a
   colossal stroke of luck. But if a provocative new theory is correct,
   luck may have little to do with it. Instead, according to the physicist
   proposing the idea, the origin and subsequent evolution of life follow
   from the fundamental laws of nature and “should be as unsurprising as
   rocks rolling downhill.”

   From the standpoint of physics, there is one essential difference
   between living things and inanimate clumps of carbon atoms: The former
   tend to be much better at capturing energy from their environment and
   dissipating that energy as heat. Jeremy England, a 31-year-old
   assistant professor at the Massachusetts Institute of Technology, has
   derived a mathematical formula that he believes explains this capacity.
   The formula, based on established physics, indicates that when a group
   of atoms is driven by an external source of energy (like the sun or
   chemical fuel) and surrounded by a heat bath (like the ocean or
   atmosphere), it will often gradually restructure itself in order to
   dissipate increasingly more energy. This could mean that under certain
   conditions, matter inexorably acquires the key physical attribute
   associated with life.
   Plagiomnium affine

   Kristian Peters

   Cells from the moss Plagiomnium affine with visible chloroplasts,
   organelles that conduct photosynthesis by capturing sunlight.

   “You start with a random clump of atoms, and if you shine light on it
   for long enough, it should not be so surprising that you get a plant,”
   England said.

   England’s theory is meant to underlie, rather than replace, Darwin’s
   theory of evolution by natural selection, which provides a powerful
   description of life at the level of genes and populations. “I am
   certainly not saying that Darwinian ideas are wrong,” he explained. “On
   the contrary, I am just saying that from the perspective of the
   physics, you might call Darwinian evolution a special case of a more
   general phenomenon.”

   His idea, detailed in a recent paper and further elaborated in a talk
   he is delivering at universities around the world, has sparked
   controversy among his colleagues, who see it as either tenuous or a
   potential breakthrough, or both.

   England has taken “a very brave and very important step,” said
   Alexander Grosberg, a professor of physics at New York University who
   has followed England’s work since its early stages. The “big hope” is
   that he has identified the underlying physical principle driving the
   origin and evolution of life, Grosberg said.

   “Jeremy is just about the brightest young scientist I ever came
   across,” said Attila Szabo, a biophysicist in the Laboratory of
   Chemical Physics at the National Institutes of Health who corresponded
   with England about his theory after meeting him at a conference. “I was
   struck by the originality of the ideas.”

   Others, such as Eugene Shakhnovich, a professor of chemistry, chemical
   biology and biophysics at Harvard University, are not convinced.
   “Jeremy’s ideas are interesting and potentially promising, but at this
   point are extremely speculative, especially as applied to life
   phenomena,” Shakhnovich said.

   England’s theoretical results are generally considered valid. It is his
   interpretation — that his formula represents the driving force behind a
   class of phenomena in nature that includes life — that remains
   unproven. But already, there are ideas about how to test that
   interpretation in the lab.

   “He’s trying something radically different,” said Mara Prentiss, a
   professor of physics at Harvard who is contemplating such an experiment
   after learning about England’s work. “As an organizing lens, I think he
   has a fabulous idea. Right or wrong, it’s going to be very much worth
   the investigation.”
   A computer simulation by Jeremy England and colleagues shows a system
   of particles confined inside a viscous fluid in which the turquoise
   particles are driven by an oscillating force. Over time (from top to
   bottom), the force triggers the formation of more bonds among the
   particles.

   Courtesy of Jeremy England

   A computer simulation by Jeremy England and colleagues shows a system
   of particles confined inside a viscous fluid in which the turquoise
   particles are driven by an oscillating force. Over time (from top to
   bottom), the force triggers the formation of more bonds among the
   particles.

   At the heart of England’s idea is the second law of thermodynamics,
   also known as the law of increasing entropy or the “arrow of time.” Hot
   things cool down, gas diffuses through air, eggs scramble but never
   spontaneously unscramble; in short, energy tends to disperse or spread
   out as time progresses. Entropy is a measure of this tendency,
   quantifying how dispersed the energy is among the particles in a
   system, and how diffuse those particles are throughout space. It
   increases as a simple matter of probability: There are more ways for
   energy to be spread out than for it to be concentrated. Thus, as
   particles in a system move around and interact, they will, through
   sheer chance, tend to adopt configurations in which the energy is
   spread out. Eventually, the system arrives at a state of maximum
   entropy called “thermodynamic equilibrium,” in which energy is
   uniformly distributed. A cup of coffee and the room it sits in become
   the same temperature, for example. As long as the cup and the room are
   left alone, this process is irreversible. The coffee never
   spontaneously heats up again because the odds are overwhelmingly
   stacked against so much of the room’s energy randomly concentrating in
   its atoms.

   Although entropy must increase over time in an isolated or “closed”
   system, an “open” system can keep its entropy low — that is, divide
   energy unevenly among its atoms — by greatly increasing the entropy of
   its surroundings. In his influential 1944 monograph “What Is Life?” the
   eminent quantum physicist Erwin Schrödinger argued that this is what
   living things must do. A plant, for example, absorbs extremely
   energetic sunlight, uses it to build sugars, and ejects infrared light,
   a much less concentrated form of energy. The overall entropy of the
   universe increases during photosynthesis as the sunlight dissipates,
   even as the plant prevents itself from decaying by maintaining an
   orderly internal structure.

   Life does not violate the second law of thermodynamics, but until
   recently, physicists were unable to use thermodynamics to explain why
   it should arise in the first place. In Schrödinger’s day, they could
   solve the equations of thermodynamics only for closed systems in
   equilibrium. In the 1960s, the Belgian physicist Ilya Prigogine made
   progress on predicting the behavior of open systems weakly driven by
   external energy sources (for which he won the 1977 Nobel Prize in
   chemistry). But the behavior of systems that are far from equilibrium,
   which are connected to the outside environment and strongly driven by
   external sources of energy, could not be predicted.

   This situation changed in the late 1990s, due primarily to the work of
   Chris Jarzynski, now at the University of Maryland, and Gavin Crooks,
   now at Lawrence Berkeley National Laboratory. Jarzynski and Crooks
   showed that the entropy produced by a thermodynamic process, such as
   the cooling of a cup of coffee, corresponds to a simple ratio: the
   probability that the atoms will undergo that process divided by their
   probability of undergoing the reverse process (that is, spontaneously
   interacting in such a way that the coffee warms up). As entropy
   production increases, so does this ratio: A system’s behavior becomes
   more and more “irreversible.” The simple yet rigorous formula could in
   principle be applied to any thermodynamic process, no matter how fast
   or far from equilibrium. “Our understanding of far-from-equilibrium
   statistical mechanics greatly improved,” Grosberg said. England, who is
   trained in both biochemistry and physics, started his own lab at MIT
   two years ago and decided to apply the new knowledge of statistical
   physics to biology.

   Using Jarzynski and Crooks’ formulation, he derived a generalization of
   the second law of thermodynamics that holds for systems of particles
   with certain characteristics: The systems are strongly driven by an
   external energy source such as an electromagnetic wave, and they can
   dump heat into a surrounding bath. This class of systems includes all
   living things. England then determined how such systems tend to evolve
   over time as they increase their irreversibility. “We can show very
   simply from the formula that the more likely evolutionary outcomes are
   going to be the ones that absorbed and dissipated more energy from the
   environment’s external drives on the way to getting there,” he said.
   The finding makes intuitive sense: Particles tend to dissipate more
   energy when they resonate with a driving force, or move in the
   direction it is pushing them, and they are more likely to move in that
   direction than any other at any given moment.

   “This means clumps of atoms surrounded by a bath at some temperature,
   like the atmosphere or the ocean, should tend over time to arrange
   themselves to resonate better and better with the sources of
   mechanical, electromagnetic or chemical work in their environments,”
   England explained.
   Self Replicating Microstructures

   Courtesy of Michael Brenner/Proceedings of the National Academy of
   Sciences

   Self-Replicating Sphere Clusters: According to new research at Harvard,
   coating the surfaces of microspheres can cause them to spontaneously
   assemble into a chosen structure, such as a polytetrahedron (red),
   which then triggers nearby spheres into forming an identical structure.

   Self-replication (or reproduction, in biological terms), the process
   that drives the evolution of life on Earth, is one such mechanism by
   which a system might dissipate an increasing amount of energy over
   time. As England put it, “A great way of dissipating more is to make
   more copies of yourself.” In a September paper in the Journal of
   Chemical Physics, he reported the theoretical minimum amount of
   dissipation that can occur during the self-replication of RNA molecules
   and bacterial cells, and showed that it is very close to the actual
   amounts these systems dissipate when replicating. He also showed that
   RNA, the nucleic acid that many scientists believe served as the
   precursor to DNA-based life, is a particularly cheap building material.
   Once RNA arose, he argues, its “Darwinian takeover” was perhaps not
   surprising.

   The chemistry of the primordial soup, random mutations, geography,
   catastrophic events and countless other factors have contributed to the
   fine details of Earth’s diverse flora and fauna. But according to
   England’s theory, the underlying principle driving the whole process is
   dissipation-driven adaptation of matter.

   This principle would apply to inanimate matter as well. “It is very
   tempting to speculate about what phenomena in nature we can now fit
   under this big tent of dissipation-driven adaptive organization,”
   England said. “Many examples could just be right under our nose, but
   because we haven’t been looking for them we haven’t noticed them.”

   Scientists have already observed self-replication in nonliving systems.
   According to new research led by Philip Marcus of the University of
   California, Berkeley, and reported in Physical Review Letters in
   August, vortices in turbulent fluids spontaneously replicate themselves
   by drawing energy from shear in the surrounding fluid. And in a paper
   appearing online this week in Proceedings of the National Academy of
   Sciences, Michael Brenner, a professor of applied mathematics and
   physics at Harvard, and his collaborators present theoretical models
   and simulations of microstructures that self-replicate. These clusters
   of specially coated microspheres dissipate energy by roping nearby
   spheres into forming identical clusters. “This connects very much to
   what Jeremy is saying,” Brenner said.

   Besides self-replication, greater structural organization is another
   means by which strongly driven systems ramp up their ability to
   dissipate energy. A plant, for example, is much better at capturing and
   routing solar energy through itself than an unstructured heap of carbon
   atoms. Thus, England argues that under certain conditions, matter will
   spontaneously self-organize. This tendency could account for the
   internal order of living things and of many inanimate structures as
   well. “Snowflakes, sand dunes and turbulent vortices all have in common
   that they are strikingly patterned structures that emerge in
   many-particle systems driven by some dissipative process,” he said.
   Condensation, wind and viscous drag are the relevant processes in these
   particular cases.

   “He is making me think that the distinction between living and
   nonliving matter is not sharp,” said Carl Franck, a biological
   physicist at Cornell University, in an email. “I’m particularly
   impressed by this notion when one considers systems as small as
   chemical circuits involving a few biomolecules.”
   Snowflake

   Wilson Bentley

   If a new theory is correct, the same physics it identifies as
   responsible for the origin of living things could explain the formation
   of many other patterned structures in nature. Snowflakes, sand dunes
   and self-replicating vortices in the protoplanetary disk may all be
   examples of dissipation-driven adaptation.

   England’s bold idea will likely face close scrutiny in the coming
   years. He is currently running computer simulations to test his theory
   that systems of particles adapt their structures to become better at
   dissipating energy. The next step will be to run experiments on living
   systems.

   Prentiss, who runs an experimental biophysics lab at Harvard, says
   England’s theory could be tested by comparing cells with different
   mutations and looking for a correlation between the amount of energy
   the cells dissipate and their replication rates. “One has to be careful
   because any mutation might do many things,” she said. “But if one kept
   doing many of these experiments on different systems and if
   [dissipation and replication success] are indeed correlated, that would
   suggest this is the correct organizing principle.”

   Brenner said he hopes to connect England’s theory to his own
   microsphere constructions and determine whether the theory correctly
   predicts which self-replication and self-assembly processes can occur —
   “a fundamental question in science,” he said.

   Having an overarching principle of life and evolution would give
   researchers a broader perspective on the emergence of structure and
   function in living things, many of the researchers said. “Natural
   selection doesn’t explain certain characteristics,” said Ard Louis, a
   biophysicist at Oxford University, in an email. These characteristics
   include a heritable change to gene expression called methylation,
   increases in complexity in the absence of natural selection, and
   certain molecular changes Louis has recently studied.

   If England’s approach stands up to more testing, it could further
   liberate biologists from seeking a Darwinian explanation for every
   adaptation and allow them to think more generally in terms of
   dissipation-driven organization. They might find, for example, that
   “the reason that an organism shows characteristic X rather than Y may
   not be because X is more fit than Y, but because physical constraints
   make it easier for X to evolve than for Y to evolve,” Louis said.

   “People often get stuck in thinking about individual problems,”
   Prentiss said.  Whether or not England’s ideas turn out to be exactly
   right, she said, “thinking more broadly is where many scientific
   breakthroughs are made.”

   Emily Singer contributed reporting. This article was reprinted on
   ScientificAmerican.com.

   Correction: This article was revised on January 22, 2014, to reflect
   that Ilya Prigogine won the Nobel Prize in chemistry, not physics.
   Share This Article

Share This Article

   print
     * Under Pressure, Does Evolution Evolve?
     * Perfecting the Art of Sensible Nonsense
     * More Articles

   Add a Comment

   View Comments (134)

Comments for this entry

     * Otto says:
       January 22, 2014 at 2:24 pm
       Nice. Now it’s time to test this and gather data to support it.
     * win says:
       January 22, 2014 at 3:20 pm
       I believe England has discovered a door and is just beginning to
       step inside the room. I agree somewhat with Louis’ comments. I
       would call the process, Energy Force constraints.
       Imagine trying to isolate the “energy force” dissipation source
       impacting a lab experiment when this dissipation driver takes a
       direction of its own choosing without any clues as to why.
       ps….are we talking the probabilities of the dead /live cat again.
     * Karo Michaelian says:
       January 22, 2014 at 3:52 pm
       The theory for the origin and evolution of life as presented above
       and accredited to Jeremy England is not new. It was published by
       myself in 2009, K. Michaelian, arXiv:0907.0042 [physics.gen-ph]
       http://arxiv.org/abs/0907.0042
       and again in 2011, K. Michaelian Earth Syst. Dynam., 2, 37-51, 2011
       http://www.earth-syst-dynam.net/2/37/2011/doi:10.5194/esd-2-37-2011
       The observation that under a generalized chemical potential
       material self-organizes into systems which augment the dissipation
       of that potential should be accredited to Ilya Prigogine,
       “Introduction to Thermodynamics of Irreversible Processes”, John
       Wiley Sons Inc., 1968. I have written a number of other papers on
       the thermodynamic dissipation theory for the origin of life,
       including an explanation of homochirality. These papers are freely
       available by searching for my name “Karo Michaelian” on
       ResearchGate. I welcome Jeremy’s contribution to the effort to
       understand life from a thermodynamic perspective.
     * Karo Michaelian says:
       January 22, 2014 at 4:01 pm
       A more direct access to the above mention article is;
       http://www.earth-syst-dynam.net/2/37/2011/esd-2-37-2011.html
       Best regards, K. Michaelian.
     * dar7yl says:
       January 22, 2014 at 4:19 pm
       “a heritable change to gene expression called methylation,
       increases in complexity in the absence of natural selection”
       – I disagree with that statement. Methylation is definitely under
       natural selection. IMHO, methylation epigenetics is nature’s way of
       overcoming the long generation period of DNA replication.
     * Jim says:
       January 22, 2014 at 5:22 pm
       What am I missing? Isn’t this the same as Ilya Prigogine’s
       “dissipative systems” and a good deal of subsequent chaos theory?
     * Smith says:
       January 22, 2014 at 5:26 pm
       Has Jeremy revealed the equation for this phenomena?
     * Diego says:
       January 22, 2014 at 5:30 pm
       “You start with a random clump of atoms, and if you shine light on
       it for long enough, it should not be so surprising that you get a
       plant,” Seriously??? it reminds me of Stanley Miller back in 1953,
       this sounds nice but its far away from being true. Great
       Mathematician Harold Morowitz after a long and exhaustive
       mathematical and statistical study computed that merely to create a
       bacterium would require more time than the universe might ever see
       if chance combinations of its molecules were the driving force,
       spontaneous emergence of single cell organism from random coupling
       of chemical is as Sir Freud Hoyle said “such an occurrence is about
       as likely as the assemblage of a 747 by a tornado whirling through
       a junkyard”. Thermodynamics tells us that all nonmanaged, or
       random, systems ALWAYS pass to a state of greater disorder.
       Disorder is the statistical trend of nature simply because for any
       given collection of atoms the number of disorderly combinations is
       vastly greater than the number of orderly combinations.
     * Giorgio Torrieri says:
       January 22, 2014 at 5:41 pm
       I read the paper based on the press release, and then the paper,
       and to be honest I found this argument really unconvincing as it
       depends on a fallacy:
       Essentially, the author claims that the most efficient way to
       increase entropy in a large system is to populate it with
       self-replicating long-lived subsystems. Each subsystem is a low
       entropy state, but is very efficient at creating entropy in the
       rest of the system.
       I might believe these statements for bacteria, as large organisms
       such as ourselves, elephants or whales are clearly irrelevant for
       the total entropy production of the earth.
       However, this is irrelevant, for there is no principle that says
       “entropy should be created as efficiently as possible”.
       Entropy should increase on average, that is a corollary of the
       principle that all macrostates increase. Statistical mechanics
       itself, with no further assumptions, has nothing to say at how
       entropy increases. That varies from system to system, and needs to
       be calculated from microscopic theory. For some systems
       (“semiclassical” ones) this works, but for most systems doesen’t,
       and certainly a system with many entropy maxima and fluctuations
       between them (the protein folding problem , for example), this
       should not be the case.
       Equations such as (6)-(8) in the paper look very much like those of
       the Metropolis algorithm, widely used in Montecarlos. This
       algorithm is guaranteed to get at the right minimum, but (and this
       is something stressed to all students doing computational physics)
       one should be careful not to confuse “montecarlo time” and “real
       time”: Running the montecarlo gives you the finish, but not how the
       system gets there.
     * interguru says:
       January 22, 2014 at 5:58 pm
       Could this be the force behind emergent behavior, such as a
       disorganized warm ocean-atmosphere system producing a highly
       organized hurricane?
     * Ted Pavlic says:
       January 22, 2014 at 6:28 pm
       I agree with some other contents that this research direction is
       far from new. We ahve been working on similar directions in our
       group, with the cosmologist and astrobiologist Paul Davies. This is
       a very active area, and it’s pretty silly to focus on this one
       latecomer.
     * Ted Pavlic says:
       January 22, 2014 at 6:55 pm
       I should also point out that these kind of arguments are not really
       qualitatively different than what ecologist Ramon Margalef used to
       talk about in the 90’s.
       I’m generally upset about the pedestal this piece of press puts
       this relatively average article.
     * IL says:
       January 22, 2014 at 7:02 pm
       ^ Except of course that he is not showing that ‘most likely state
       II is proven to be self-replication’ (which is what you are
       implying). It simply uses eq. 8 to establish that the entropy cost
       of self-replication is low enough to be feasible (i.e., so that the
       more flexible thermodynamic bound is not violated) in a variety of
       systems.
       In fact eq. 8 does not have that information– it requires that we
       have (carefully) decided what transitions to measure a priori. (The
       same holds true of the usual Second Law by the way. There is always
       the implicit axiom that our microstates exist in some preexisting
       space to be counted by a partition function.)
     * Shaun Johnston says:
       January 22, 2014 at 7:05 pm
       Around 1950 in a lecture at UCL on biochemistry I heard of a theory
       proposed by a Russian to the effect that energy will be diffused at
       right angles to the direction of its flow. This brought to my mind
       convection currents, and that such processes would induce the
       emergence of organized forms of matter that would more effectively
       dissipate that energy.
     * Behzad Mohit says:
       January 22, 2014 at 7:29 pm
       I enjoyed reading the cogent comment of Mr. Giorgio Torrieri. It is
       indeed true that entropy tends to increase in a closed system as
       per second law of thermodynamics. However, by trapping energy in
       the form of information , complex adaptive systems such as life ,
       indeed if anything retard the flow of energy into its ultimate
       destination of maximal entropy in our closed system,”The universe”
       although living matter dispenses a large part of the energy
       captured in its organized matter as heat, a good portion of energy
       is trapped in its information networks a part of its structure.
       ultimately, in due time this energy also joins the broader entropic
       ocean,the universe but later. All this is succinctly elucidated in
       the first chapter of the book comprehensive theory of evolution
       ,Thermoinfocoplexity, A new theory (Amazon 2013 ). The math in the
       first chapter describe a progressive , scale free ,micro state,
       macro state in the emergence Of complex adaptive systems.
     * Niels Compernolle says:
       January 22, 2014 at 7:48 pm
       Nice article!
       But there’s one little mistake: Ilya Prigogine won the nobel prize
       for chemistry not physics;)
     * thomas says:
       January 22, 2014 at 8:16 pm
       @Niels Compernolle: Thank you. The error has been fixed.
       Best,
       Thomas Lin, Quanta Magazine
     * Beatrice says:
       January 22, 2014 at 10:09 pm
       I like this theory – something I can work on. Darwin theory of
       evolution always felt incomplete – like something hidden or missed.
       My thoughts are that both theories will compliment each other once
       proven. Love science.
     * roger erickson says:
       January 22, 2014 at 11:40 pm
       I don’t see the difference.
       just restating thermodynamics, with different words
       biologists & system theorists have said this for decades;
       is a math equation different from a logical or linguistic equation?
     * Daniel Guerriere says:
       January 23, 2014 at 12:20 am
       If the hypothesis be verified, then Darwinism would have a major
       problem. For Darwinism presupposes that all of life has a single
       origin. The hypothesis, however, allows for, indeed makes
       plausible, multiple origins. But if life has multiple origins, then
       what explains the same molecular structure across all of life? What
       explains the fine-tuning of the universe for life?
     * Travis says:
       January 23, 2014 at 12:28 am
       1. Isn’t it counterintuitive to say that the most ordered physical
       structures we know of come about because of a law saying disorder
       always increases?
       2. Isn’t saying that structures that absorb and dissipate heat in a
       highly efficient way will arise because they have a survival
       advantage a little like saying that if there is enough demand for
       the process, a way of spinning gold out of straw will surely be
       found?
     * sv says:
       January 23, 2014 at 2:58 am
       If life is the thermodynamically preferred state, then why death?
       Doesn’t the transience of life and universal, permanent death
       directly contradict this model? Barring death, wouldn’t have people
       thought of something like this before?
     * Ash Raymond says:
       January 23, 2014 at 8:00 am
       Clay mineralogists and Metamorphic petrologists are unlikely to be
       surprised by this idea. “’It is very tempting to speculate about
       what phenomena in nature we can now fit under this big tent of
       dissipation-driven adaptive organization,’ England said. ‘Many
       examples could just be right under our nose, but because we haven’t
       been looking for them we haven’t noticed them.’” Try, just right
       under our feet. It will be interesting to see who picks up this
       ball…unfortunately, it must be someone other than me, someone
       actually working in a thermo lab.
     * Vincent Lewi says:
       January 23, 2014 at 8:26 am
       don’t forget to add the development of sentience as another
       contributor to increase in order, possibly even as important as
       life itself.
     * Gus says:
       January 23, 2014 at 8:43 am
       Where does the Fibonacci sequence tie into this?
     * FrankNorman says:
       January 23, 2014 at 8:51 am
       This looks like a lot of hand-waving to me. Cell membranes,
       enzymes, DNA, ribosomes, ATP, etc etc do not just pop together
       because energy gets added. People like him are begging the
       question.
     * Harrison Crecraft says:
       January 23, 2014 at 9:09 am
       I agree that this appears to be yet another stab at a new law of
       thermodynamics to explain self-organization. Perhaps this is
       different and will be proven correct. As recognized by Prigogine,
       however, any proposed law will run into conflict with physics until
       physics and irreversibility can be reconciled. For anyone
       interested, I offer this reconciliation at
       http://www.evolvingcomplexity.com
     * Vincenzo says:
       January 23, 2014 at 9:17 am
       Aren’t those some ideas from Fearful Symmetry: Is God a Geometer?,
       a book by Stewart Ian and Golubitsky Martin?
     * Josh says:
       January 23, 2014 at 9:52 am
       Usually the comment section is full of idiots arguing back and
       forth. I was expecting the usual Creationism vs.
       Darwin/Science/Physics/Chemistry, but these are great. Looks like
       chemists and scientists debating and what not… Actual sources being
       cited. What if the whole internet was like this?
     * leila says:
       January 23, 2014 at 10:16 am
       with all due respect to the previous commenters who point out
       “similar” theories that have come out prior to this one, these
       early theories are all basically musings written in prose that lack
       the kind of mathematical rigor this scientist is applying to
       formulate and tackle the stated question. i don’t think anyone is
       surprised that people have generally pondered repeated patterns in
       nature and their connections to the laws of thermodynamics, etc.
       i’m sure darwin wasn’t the first to notice that monkeys defecate in
       the same manner as humans. that didn’t make these early observers
       of the natural world trailblazers in biology.
     * peti says:
       January 23, 2014 at 10:17 am
       Giorgio Torrieri: “I might believe these statements for bacteria,
       as large organisms such as ourselves, elephants or whales are
       clearly irrelevant for the total entropy production of the earth.”
       Except, humans prove to excel at dispersing energy. We even go as
       far as to dig up clustered energy sources (carbon, oil) and burn
       them large scale across the planet. We even cause global warming to
       further increase entropy :) I’d say we are masters of energy
       dispersion.
     * Steve Glines says:
       January 23, 2014 at 10:19 am
       There is nothing new here. It’s been obvious for a long time that
       living organisms consume more energy than non living things and the
       fact that they obey the laws of thermodynamics falls in to the
       “duh!” category. It should also be no surprise that given enough
       time, molecules in a closed system will organize themselves to
       reduce available energy. Perhaps what is new here is the added
       concept that they will organize in such a fashion as to reduce
       available energy at an ever increasing rate.
       That obviously puts humans at the top of the evolutionary food
       chain. We have mastered the ability to consume massive amounts of
       available energy and at an ever increasing rate. Of course any
       closed system eventually reaches maximum entropy and becomes as
       lifeless as the dust under our feet.
     * Granite Sentry says:
       January 23, 2014 at 10:19 am
       But if the principle can apply to lots of systems, including
       non-living ones (“England argues that under certain conditions,
       matter will spontaneously self-organize. This tendency could
       account for the internal order of living things and of many
       inanimate structures as well. ‘Snowflakes, sand dunes and turbulent
       vortices all have in common that they are strikingly patterned
       structures that emerge in many-particle systems driven by some
       dissipative process,’ he said.”), it’s pretty plain this fact may
       be true, but it’s not a distinguishing characteristic of life. In
       other words, there’s much more to reality than we can capture in an
       equation, a formula or a sentence. Physicists are always forgetting
       this simple fact that every poet knows.
     * Tomp says:
       January 23, 2014 at 10:27 am
       so if the sun and ocean were essential for creating life (in the
       example mentioned by the scientist) then how did the sun and ocean
       get created?
     * Frontelly says:
       January 23, 2014 at 10:44 am
       leila is correct. It’s one thing to make a claim. It’s another to
       support it with equations that allow for empirical scrutiny.
     * tiapa says:
       January 23, 2014 at 11:25 am
       ““He is making me think that the distinction between living and
       nonliving matter is not sharp,” said Carl Franck”. Brings to mind
       the oft debated quote in Luke 19:40 “I tell you,” he replied, “if
       they keep quiet, the stones will cry out.”
       I am looking outside my office window now with a possible answer to
       a question I always ask: How do the trees know how to space their
       branches for optimal sun exposure for leaves yet to come. Benoit
       Mandelbrot said “So the goal of science is starting with a mess,
       and explaining it with a simple formula, a kind of dream of
       science.”
     * Connor Rowe says:
       January 23, 2014 at 11:35 am
       “…on the emergence of structure and function in living things, many
       of the researchers said.”
       Anthropology punts the ball back to physics. (Franz Boas, “Father
       of American Anthropology,” having been a physicist himself.)
     * Vinicius Romanini says:
       January 23, 2014 at 11:40 am
       Love the article.
       As far as I know, Prigogine was a chemist and not as said: “In the
       1960s, the Belgian physicist Ilya Prigogine made”
     * Mark Plutowski says:
       January 23, 2014 at 11:49 am
       @Josh, my thoughts exactly.
       Could Quanta magazine do a piece on how they receive such a high
       level of commentary? It is like being able to attend the conference
       at which the research is presented, but without the travel
       arrangements and lost wages.
       I was at a local cosmology lecture last night. It is typically
       attended by professional researchers, former researchers, amateur
       hobbyists, and lay people like myself and my son who are there just
       because we’re fascinated by the topic. Some of the best questions
       were from old-timers who spent a career on the topic but no longer
       actively involved, and some were from pre-teen kids.
       A great Q&A session is just as helpful in allowing me to fully
       appreciate the subject matter as the presentation itself.
       Thanks also to the commentators who provided references. I just
       added a half dozen quality articles on this topic to my reading
       list.
       Back to topic, does this theory depend on high energy gradients? If
       so, I wonder, given that we have still have regions of earth
       immersed in extreme energy gradients, then as Daniel Guerriere
       says: “But if life has multiple origins, then what explains the
       same molecular structure across all of life? ”
       I also wonder what is the connection or reliance if any between
       these dissipative systems theories and the availability of
       negentropy.
     * sidonie sawyer, journalist says:
       January 23, 2014 at 12:34 pm
       Bravo Mr. England!
     * Abas says:
       January 23, 2014 at 2:37 pm
       I think the reason for high quality comments is due to the title of
       the article, some articles titled to attract users regardless of
       their background and aim at quantity rather than quality and
       background of readers, its obvious common and uninterested
       individuals won’t come here to discuss physics theory and
       thermodynamics or such specialized issues, I hope to see such
       articles even more
     * cbranch says:
       January 23, 2014 at 2:48 pm
       Just to add another source for those interested, this sounds
       similar to the ideas discussed in the book “What is Life?: How
       Chemistry becomes Biology” by Addy Pross.
     * Behzad Mohit says:
       January 23, 2014 at 2:53 pm
       Leila please read the books “into the cool ” by Schneider etal,
       “information theory of evolution by John Avery ,2003 ,also 2012 and
       my own book ” a comprehensive theory of evolution 2013 ” before
       making a not true statement that the previous authors had not have
       mathematical treatment or rigor of mr. England . Both you and mr.
       England benefit by reading the writing of these eminent
       scholars(present author excepted) which are mathematically truly
       rigorous. When and if this necessary reading is done it will become
       clear that the encounter of sun,s photons and matter in converting
       energy to information inbeded in the structure of molecules or more
       complex matter,life, John Avery shows with rigorous math that at
       298.15 kelvin(room temperature) 1 jule will produce 56.157 bits of
       informatin(entropy change). In my book,( a comprehensive theory of
       evolution) on page45 , chapter one the concept of retardation of
       flow of entropy thru living matter in the form of captured Gibbs
       free energy is rigorously and mathematically presented . Therein
       the confusion regarding whether life increases or decreases entropy
       flow has been clarified with the conclusion that life retards the
       flow of energy into entropy universe. This issue has been confusing
       to many scientists including Mr. england but was resolved after
       detail personal communication with John Avery and its math and
       assumptions are clearly discussed in the comprehensive theory of
       evolution, ( Thermoinfocomplexity ) book, chater one. The debate is
       not about priority of credit (who cares, we will all join the ocean
       of universal entropy soon) . The debate is about the truth of
       physical evolution.
     * CrazedLeper says:
       January 23, 2014 at 3:29 pm
       Ok, perhaps he was being glib but if “shining light” on a rock were
       enough to make a plant, Mercury and Venus should be teeming with
       life. Methinks that Mars has been there long enough to have at
       least grown some moss–according to the theory. It’s more likely
       that he wants to believe something and this theory will simply
       serve as his very own “cosmological constant.”
     * S. Sun says:
       January 23, 2014 at 4:52 pm
       This is a very amazing discovery if proven true.
       I am a Ph.D. student in physics. I just wanted to say that what he
       proposes does not run into any conflict with the existing law of
       thermodynamics. The existing law of thermodynamics only applies to
       systems in equilibrium that many people are familiar with
       (increases in disorder (entropy) etc). They all have one
       fundamental assumption: that the system is already in equilibrium.
       Non-equilibrium systems are not very understood at all.
       Non-equilibrium statistical mechanics is a huge open question in
       physics. Its why we don’t understand every day things such as
       underwater bubble formation. Because such phenomenon can only
       happen under non-equilibrium conditions.
       The Earth is certainly not an equilibrium system, we take in energy
       from the sun the day and emit our entropy at night to the emptiness
       of space. If this proves to be correct it will be a huge in the
       step of understanding non-equilibrium systems.
     * James Cross says:
       January 23, 2014 at 5:14 pm
       This made me think of Into the Cool as some others have noted but
       there are probably a number of others.
       However, I think there is a missing piece in these theories-
       information. Living systems accumulate and preserve information.
       Information allows reproduction, evolution, and even metabolism.
     * Charles Hall says:
       January 23, 2014 at 5:41 pm
       I agree with the many responders that these ideas are not new at
       all (such as I can tell), including to this systems ecologist.
       Indeed Ecologist(s) Ramon Margalef discussed this and so did Howard
       Odum in a way that is far more satisfying to me (although perhaps
       not as elegantly written as some). Life does not dissipate energy
       just to do that; it is a necessary requirement for building
       structure, capturing more energy than that required for maintaining
       that energy and for energy acquisition, and propelling one’s genes
       into the future. (“Evolution is an existential game, the object of
       which is to keep playing”: Ecologist L B Slobodkin). Hurricanes too
       feed on the free energy of warm water to maintain structure which
       can capture more energy in a positive feedback. These are very old
       ideas. There continues to be confusion between mathematical and
       scientific rigor. They are (generally) different issues. Newton and
       Maxwell were lucky: The rest of us have to struggle with the more
       mathematically recalictrant leftovers.
     * Mihai Nadin says:
       January 23, 2014 at 6:04 pm
       Read: Walter M. Elsasser, Reflections on a Theory of Organisms.
       After reading it, you will reconsider your premises. The
       echo-chamber of science produces many formal proofs, but not yet
       the theory of life.
     * M Mahin says:
       January 23, 2014 at 6:06 pm
       Some explanation of the origin of life — no mention of the genetic
       code, no chemistry, but only physics. You can’t explain the origin
       of life with just physics.
       See my explanation of why this supposed “breakthrough” falls short.
       http://www.futureandcosmos.blogspot.com/2014/01/the-origin-of-life-
       breakthrough-that.html
     * Graniteman says:
       January 23, 2014 at 7:41 pm
       For those of you who doubt that Dr. England has produced something
       new, please read his recent publication in J. Chem. Physics:
       http://www.englandlab.com/uploads/7/8/0/3/7803054/2013jcpsrep.pdf
       If you bother to read this publication in a well regarded journal,
       you will see that he has offered a valuable framework for
       conducting future research about thermodynamic constraints on
       biological processes. This doesn’t mean, of course, that other
       authors haven’t offered similar thoughts in a less formal way.
     * James Cross says:
       January 23, 2014 at 8:35 pm
       M Mahin –
       Pretty much agree.
       I think this needs to be looked at as a sort of companion piece to
       Tegmark’s Consciousness as a state of matter
       http://arxiv.org/abs/1401.1219
       So these are in some ways very different but I think there is a
       connection.
       Tegmark tries to derive consciousness from physics as this tries to
       derive life from physics. Tegmark, however, skips life in his
       states of matter going pretty much from solid, liquid, gas to
       computation.
       In fact, I think there is very much a direct connection.
       Consciousness arises from life as an advanced form of information
       processing that first arose in life – an evolutionary development
       from more primitive life processes.
       The missing factor in both is information. But there seems to be
       some relationship between information and energy in that as more
       advanced organisms are more intelligent – can process more
       information, have more throughput, and hold more information – they
       also dissipate more energy.
     * mark says:
       January 23, 2014 at 8:35 pm
       This idea is not new. Perhaps the equations shed some new light and
       allow for empirical predictions. See the following book: Brooks and
       Wiley, Evolution as Entropy, U Chicago Press (1986, 2nd edition
       1988)
     * Brandon says:
       January 23, 2014 at 10:07 pm
       Some similar ideas have been advanced by chemist Addy Pross.
       This introduces and goes into depth about a concept known as
       dynamic kinetic stability.
       http://www.bgu.ac.il/~pross/PDF-10.pdf
       This paper goes more into depth about the relevance of dynamic
       kinetic stability to biology.
       http://www.jsystchem.com/content/2/1/1
     * Dorion Sagan says:
       January 23, 2014 at 10:17 pm
       On the face of it this would seem to be a simplistic
       mathematization without ecological phenomenological grounding. “You
       start with a random clump of atoms, and if you shine light on it
       for long enough, it should not be so surprising that you get a
       plant,” Well not quite but living systems do produce more entropy,
       as do complex thermodynamic systems in general. I discuss
       naturalistic teleology in the Introduction to this book, in the
       section, “Turing Gaia” :
       http://www.amazon.com/Foray-into-Worlds-Animals-Humans/dp/081665900
       1/ref=sr_1_1?s=books&ie=UTF8&qid=1390529955&sr=1-1&keywords=von+uex
       kull There are some mistakes in the article, e.g., the conflation
       of “closed” and “isolated” systems. Eric Schnedier and I even
       discussed life as primarily a metabolic and thermodynamic system,
       stabilized by genetics, at MIT, at the Joseph Keenan conference
       organized by Hatsopoulos. There are three stages of a scientific
       theory. 1) You are dead wrong, 2) You are right but it’s trivial,
       3) You are right and it’s important and we knew it all along.
       Welcome to stage three haha If you are really interested in this
       subject, please read Into the Cool; Eric D. Schneider collects
       great data about how more complex ecosystems (e.g., rainforests are
       better energy dissipators than old growth fir forests which are in
       turn better dissipators of energy than newly planted forests,
       grasslands better than cities and so on); we also have a chapter on
       the origins of life. Global warming can be looked at as literal
       biospheric dysfunction as heat remains closer to the complex
       system’s surface, impairing its function. And if you are interested
       in naturalistic teleology, I discuss it in detail in several places
       in http://www.amazon.com/dp/081668135X . Notice also this paper,
       “Life as a Manifestation of the Second Law of Thermodynamics,”
       which precedes England’s would-be pride of place in this area by
       some years:
       http://www.sciencedirect.com/science/article/pii/0895717794901880.
       What is different about Schneider’s work is the careful application
       of nonequilibrium thermodynamics to living systems.
     * Karthik says:
       January 23, 2014 at 10:39 pm
       A very interesting and exciting idea of energy dissipation. Its
       good to see the definitions of energy transfer from external to
       internal and vice-versa, getting clearer. Looking forward for this
       experiment.
     * Lee Foreman says:
       January 23, 2014 at 11:40 pm
       These mathmateical rules for all or any potential life are great
       but they only seem to apply to one tiny planet in one tiny galaxy.
       However, if the laws of physics are truly universal as most of us
       believe to be the case, why then are there no other life forms as
       of yet discovered except on earth? Wouldn’t this spontenaiety
       theory create life in abundance around the universe, the
       mathmateical probabilites would have to be all aligned somewhere
       just like they have been here on earth. How can this theory hold
       true if it does not apply outside of our great little planet?
     * Kittylit says:
       January 23, 2014 at 11:43 pm
       All I know is that the 2nd law of Thermodynamics is really #3.
     * Karl says:
       January 24, 2014 at 1:52 am
       “We can show very simply from the formula that the more likely
       evolutionary outcomes are going to be the ones that absorbed and
       dissipated more energy from the environment’s external drives on
       the way to getting there”
       This, IMO, is the core of why all this is a completely theoretical
       exercise and not (as it has been reported elsewhere) “proof that
       life is inevitable” or even “as unsurprising as rocks rolling
       downhill”. In a non-evolutionary system, there is no selective
       pressure for the “best” dissipation outcome that they have
       calculated. The system can simply continue to heat up, like Venus,
       until it reaches its own equilibrium without life. Even if simple
       self-replicating molecules form, they may develop into life merely
       by the fact that they reproduce and start to evolve, but the fact
       that they disperse energy from the planet better does not help them
       “outcompete” other molecules on the planet.
     * Uthup says:
       January 24, 2014 at 3:45 am
       Like Mr. Mahin states it might be ages till they find ‘The’ reason
       for the origin of life and the complexity of DNAs, but what I love
       about this article is that it opens up the thought that origin of
       life is not just a random and lucky lighting strike in the
       primordial soup. Whether this theory proves itself accurate(wholly
       or partly) remains to be seen, least it has opened up a line of
       thought which is scientifically valid rather than depending on
       sheer chance.
       And so enjoyed the comment section! :)
     * Frederik Vanhoutte says:
       January 24, 2014 at 5:09 am
       One comment that comes back is: if life has several origins, what
       explains the common molecular foundation of all currently known
       life?
       One answer to this could be: perhaps there is no other choice… or
       at least not one that can adequately compete. I have the feeling
       that we sometimes tend to forget that the “dominance of the best
       replicator” is unescapeably fundamental, not a law we invent to
       explain observations but a logical consequence of limited
       resources.
     * Robert G. Johns says:
       January 24, 2014 at 8:17 am
       I am interested in the ability of archaic life and it’s ability to
       use calcite to redistribute energy. The cases of extremeophiles in
       both caves and deep ocean environments as well as in the fossil
       record show that calcite has been used for numerous uses by early
       life forms.The tendency of many calcite salts to be easily mutable
       into more or less energy conservative forms is unique due to the
       ability of calcite to be able to take over 500 crystal forms. The
       helical forms are very interesting too because they could perhaps
       have a role in the formation of our helical genetic bases. This is
       not my area of study but it has become very interesting in light of
       this research and I would like to hear any ideas on this from any
       who may have related information.
     * KOJohnson says:
       January 24, 2014 at 8:43 am
       I may be missing something here–I’m sure that I’m missing a lot of
       things here–but this sounds like good old-fashioned spontaeneous
       generation. And if this happens, then why isn’t it happening now?
       Or is it? Why isn’t this the normal way for new life-forms to
       appear here?
       Still, interesting.
     * Dan Karlan says:
       January 24, 2014 at 9:54 am
       I’m surprised that in all this discussion there was not one
       instance of the word that for centuries has demonstrated these very
       principles: crystallization. The formation of a crystal involves
       gaining local order at the expense of surrounding disorder.
       The secret with life is not this process, because without the
       producer of the gain benefiting from the imbalance, there can be no
       selection for improvements, and reversibility is unavoidable. The
       critical step in establishing life was the formation of a shell
       between inside and outside, so the inside could capture the
       benefits of the process while expelling the waste, and could
       accumulate the raw materials without the risk of losing them to the
       disorder. Everything prior to that step was chemistry; everything
       after that step was biology.
     * Rod Richardson says:
       January 24, 2014 at 10:59 am
       If this theory is true that life evolves to disperse energy more
       efficiently, then a glass of pond water or sea water should
       dissipate energy and reach thermodynamic equilibrium more
       efficiently and quickly than a glass of distilled water, because
       the former contains life.
       Does that make sense?
       I wonder if that is a measurable test that would constitute proof
       of England’s theory.
     * JEFinch says:
       January 24, 2014 at 12:08 pm
       “One comment that comes back is: if life has several origins, what
       explains the common molecular foundation of all currently known
       life?”
       One answer could be extinctions. Those species alive today
       represent a miniscule fraction of those that have lived.
       Why isn’t it happening today? I’ll leave that one to better brains.
     * Ard Louis says:
       January 24, 2014 at 12:27 pm
       Just to say that the sentence about methlylation is not from me.
       Although methylation is a fascinating and complex epigentic
       phenomenon, I think that the propensity for methylation can be
       under selection. So it is not a good example of something that
       natural selection can’t explain.
       That being said, it is an interesting example of how heredity is
       more complex than the old textbook pictures.
     * RObert McCOnnell says:
       January 24, 2014 at 1:06 pm
       hooray for Josh’s comment: the first comments section I’ve seen in
       years that is on-topic all the way thru, regardless of your opinion
       about it’s correctness or currency..
     * MF says:
       January 24, 2014 at 1:10 pm
       Intuitively, this makes a lot of sense to me. A simple example
       comes to mind- the formation of ice crystals with the consequential
       release of energy.
     * Nalliah Thayabharan says:
       January 24, 2014 at 2:08 pm
       If life can be formed by continually putting energy into a system
       then Mercury & Venus should have more life on it than the earth.
     * Cody Burleson says:
       January 25, 2014 at 2:32 am
       Hat’s off to the author; this was one of the most interesting
       things I’ve read online in a long time – including the complete
       thread of comments, which on the whole pays fine respect to
       constructive debate and the scientific method. I wish I had
       something smart to contribute, but all I can give is my gratitude.
     * mlvlvr says:
       January 25, 2014 at 4:15 pm
       I met Prigogine at a physics conference in 1977. I don’t think he’d
       have minded if someone said he worked on physics problems. That
       said, I’m not convinced that Harold Morowitz’s calculation about
       spontaneous emergence of a bacterium (if he actually did such a
       calculation) has much bearing on the paper discussed here, and BTW,
       Harold was a biophysicist who as I recall—but cannot
       confirm—received the first biophysics PhD. He would probably not
       agree with the characterization of himself as a great
       mathematician. I’m guessing what’s new in England’s work is that he
       differs with previous authors about reaction rates. He probably
       does not claim that the idea that energy flowing through a system
       tends to organize it, a phrase I heard from Morowitz and Prigogine
       independently, is original to him.
     * Glen says:
       January 25, 2014 at 6:31 pm
       This is a nice job of quantifying the direction and flow rates of
       entropy generation in far-from-equilibrium systems. That’s what
       much of physics is about- quantizing physical behavior so that we
       can use our best mathematical tools to predict the behavior of
       those systems in time.
       Interesting (to me) is that the principal that systems evolve to
       maximize the rate of entropy production was also foreshadowed in a
       recent book published by a Duke engineering professor: Adrian
       Bejan; “Design in Nature”; anchorbooks (2012).
       He terms this principle the “constructal law”, and generalizes to
       any system in which “flow” is present…heat flow, mass flow,
       information flow and also, presumably, the flow of entropy.
     * Adrian Tuck says:
       January 25, 2014 at 8:12 pm
       The observed scale invariance in atmosphere and ocean can be linked
       to entropy production, via the thermodynamic formalism of
       statistical multifractality. Appealing to the molecular dynamical
       emergence of organized fluid flow from a randomized molecular
       population (Alder & Wainwright, Phys Rev A, 1, 18-21 [1970]) leads
       to the idea that natural selection is a property inherent in
       molecular populations, and therefore operates on all scales
       (Griffith et al., Accounts of Chemical Research, 45, 2106-2113
       [2012]). The most energetic molecules have negative entropy and
       produce organization, while the larger number closer to average are
       responsible for dissipation and allow the maintenance of an
       operational temperature in non-equilibrium systems. For a
       definitive account of atmospheric scale invariance, see “The
       Weather and Climate: Emergent Laws and Multifractal Cascades”,
       Lovejoy & Schertzer, 2013, CUP, ISBN-13: 9781107018983. Weather and
       climate are, and must have been in the Archaean, prime agents of
       natural selection.
     * Jonathan Simonoff says:
       January 26, 2014 at 12:45 pm
       Much of this reminds me of some of the implications of Stephen
       Wolfram’s reproducing pattern theory expounded in “A New Kind of
       Science.” Do you see any connection?
     * jim douthit says:
       January 26, 2014 at 1:58 pm
       A quote in the opening paragraph of Natalie’s article really hit
       me: “…the origin and subsequent evolution of life follow from the
       fundamental laws of nature and ‘should be as unsurprising as rocks
       rolling downhill’.”
       I’m a philosopher and not a physicist or chemist, so most of
       England’s theorizing is beyond me. However, I get the gist of his
       theory and, as others have noted, it stimulates thinking.
       In our philosophy discussion group (an Ayn Rand group), we’ve been
       debating whether consciousness is material or non-material. I say
       that nothing exists but matter, which includes electro-magnetic
       fields, light waves, etc.. Consciousness is not something which
       emanates from the electro-chemical activity of the brain, but
       rather, consciousness IS this electro-chemical activity.
       Matter, after billions of years of evolution, becoming aware of
       itself in the complexity of the human brain is “as unsurprising as
       rocks rolling downhill.”
       To those concerned about free will, I say this: in the complex
       electro-chemical activity of the human brain, matter reaches such a
       degree of complexity that it escapes being determined or
       predictable. The essence of freedom is its unpredictability–the
       unknowability of its future state. (For a fine discussion of the
       brain’s activity and free will, see E.O. Wilson, “On Human Nature,
       Chp. 4, “Emergence,” where Wilson discusses the brain’s “schemata”
       and “feed-back loops.” )
     * WiSz says:
       January 26, 2014 at 2:31 pm
       I find simple thermodynamic theories of life rather disappointing.
       They appear like a naive explanation of living things by saying
       that they are not really living, just being similar to tornados,
       monsunes, the Great Spot on Jupiter, or computers keeping low
       entropy and dissipating heat. But the fact that some systems
       conform well to certain laws can hardly explain the existence of
       such systems or their nature. This is a kind of manipulation,
       because we had been surprised by seeing those things and could not
       have predicted their existence.
       The problem with such theories may be that the most likely random
       transformation of an ordered system is usually its destruction. As
       regards stones rolling downhill, they are soon stopped, or just
       remain there finding no path down, or their path is uninteresting.
       Some theories say that life must exist because carbon atoms tend to
       form complex molecules. We may speculate that rational and
       intelligent systems must spontaneously appear throughout the
       Universe just because the best use of the laws of logic gives the
       best chance of persistence. Is it true, or are we still missing
       some very deep key points?
     * Yenny says:
       January 26, 2014 at 8:17 pm
       Does this indeed “liberate biologists from seeking a Darwinian
       explanation for every adaptation” or is it rather a new way to
       think of fitness? And it is interesting to think of it in terms of
       the ubiquity of convergent evolution to similar pressures, as well
       as possible ramifications for xenobiology.
     * Howard A. Landman says:
       January 27, 2014 at 2:03 am
       I’ve been looking at England’s theory. I haven’t quite figured out
       whether it’s completely trivial or actually saying something
       useful. The equation appears to be correct though. One way of
       interpreting it is just that the entropy generated by creating
       molecule(s) B from molecule(s) A, minus the entropy removed by the
       reverse reaction B to A, must be greater than or equal to the
       entropy from releasing the appropriate amount of free energy into
       the heat bath at the current temperature. That’s pretty much a
       no-brainer, since no reaction can be greater than 100% efficient.
       (Note, however, that the forward and reverse reaction rates are in
       general not the same except at equilibrium. The equation is true
       even very far from equilibrium.)
       Now, whether you can go from that equation to his broader claims
       that more efficient reactions out-compete less efficient reactions
       in the Darwinian sense, is I think less clear. It appears to
       require additional assumptions, which he doesn’t really make
       explicit. It may be true, but it’s not as obvious.
       I would thank previous commenters for their many excellent
       references. The Michaelian paper seems to be mainly a historical
       survey of previous work, and doesn’t contain any equations. I
       haven’t had time to read most of the others yet.
       John Avery’s Information Theory and Evolution (2nd ed. 2012) is a
       good solid introduction to this area of inquiry. One nice nugget of
       wisdom from it is that the natural unit of temperature is “energy
       per bit of entropy”. This means that the unit of England’s
       $\beta=1/T$ is “bits of entropy per unit of energy”. The equation
       is easier to understand dimensionally that way.
     * Torbjörn Larsson, OM says:
       January 27, 2014 at 6:48 am
       Thanks for this! With all due respect to some of the forerunners I
       have had time to check and some comments here of “what is new”,
       this is quantitative work derived directly from earlier work on
       non-equilibrium thermodynamics (NET).
       And it ties nicely in with Russell et al work on alkaline
       hydrothermal systems and how such disequilibrium system as life
       arises out of them due to NET. However, they argue convincingly (to
       me) that the metabolic bottleneck isn’t disequilibrium and
       dissipation as such, but the increased dissipation that comes from
       positive feedback in “Atwood engines” of dissipating free energy
       (disequilibrium) flows (free energy conversion, FEC, engines).
       More precisely, the simplest such FEC engine of electron
       bifurcating metal atoms that we still see in the core enzymes of
       the metabolic UCA. ["Turnstiles and bifurcators: The disequilibrium
       converting engines that put metabolism on the road", Branscomb and
       Russell, Biochimica et Biophysica Acta (BBA) - Bioenergetics,
       Volume 1827, Issue 6, June 2013, Page 806.]
       The thermodynamics of replicators may or may not supplement the
       metabolic achievement, but the result favoring RNA primacy is
       suggestive so far.
       And here I always claimed that entropy has nothing to do with life
       as such, since the entropy produced by evolution during selection
       at each generation is miniscule compared to the entropy produced
       during organism growth. And if snow flakes can grow, so can cells.
       But England turns that around to face me. =D
     * Torbjörn Larsson, OM says:
       January 27, 2014 at 8:14 am
       @Diego, Travis, Glen: “Thermodynamics tells us that all nonmanaged,
       or random, systems ALWAYS pass to a state of greater disorder.”
       “maximize the rate of entropy production”.
       It is exactly the opposite that people all the way back to
       Boltzmann has noted. Nitpick: In very constrained systems when
       entropy increases order does too. It is facile, but not correct, to
       say that entropy = disorder.
       If you read England’s talk, he derives from the 2nd law that
       “driven stochastic evolution” of systems will necessitate terms
       (system parts) of order, durability, dissipation and fluctuation.
       [slide 47] The kicker is that if you have low activation barriers
       (so not far from equilibrium) you favor disorganized states. But if
       not, you favor increased dissipation and, with the exception of
       freak fluctuation events, that is achieved by order and durability.
       Without even having replication or selection getting into play!
       [slide 48]
       Biological evolution just happens to be a most effective process,
       as he also discuss. He shows actual experiments that seems to test
       his hypothesis too (“resonant adaptation”).
     * Torbjörn Larsson, OM says:
       January 27, 2014 at 8:15 am
       @Giorgio Torrieri: I have to read the paper, but in his talk
       England doesn’t seem to claim that is the only way. [And see IL's
       comment.] Slide 51:
       “No doubt, self-replication is a way to make this work because
       discrete exponential growth reliably causes lots of dissipation
       But it seems like we expect to see organization that is ‘adapted’
       from an energetic standpoint emerge on its own, even without
       heredity and selection, and just from underlying
       Newtonian/Hamiltonian mechanics”.
     * Torbjörn Larsson, OM says:
       January 27, 2014 at 8:15 am
       @Beatrice: Evolution has been well tested for 150+ years. It is
       still the reigning contender. England may complement the current
       theory, in the same way genetics did.
       @Daniel Guerriere: It is well known for 150+ years that Darwin
       never “presupposed” anything and explicitly stated that possibly
       there were many, or one, original ancestor.
       But FWIW Theobald showed from the replication process that there
       were only one universal ancestor population in our case, with a
       likelihood > 10^2000 against many UCAs. (Nature 2010). It is the
       best observation in all of science!
       Note that protocells could still originate multiply times, since
       early evolution was likely communal. It was the surviving
       replication process that bottlenecked this, either by allowing
       lineages to diverge or by killing of alternate lineages. This is
       long known. (See Joyce et al.)
       @FrankNorman, M Mahin: “do not just pop together because energy
       gets added.”
       More precisely, becase free energy (disequilibrium) gets added.
       Yes, the evolutionary seed may, see Prigogine and Russell et al
       verification in a previous comment of mine. England assumes
       evolution is one way to realize his theory.
     * Jason Fordham says:
       January 27, 2014 at 10:15 am
       The author writes:
       ‘Eventually, the system arrives at a state of maximum entropy
       called “thermodynamic equilibrium,” in which energy is uniformly
       distributed.’
       One of the most pervasive and difficult to displace misconceptions
       about Entropy is that the distribution of energy in a system at
       thermodynamic equilibrium is a uniform distribution. It is not: the
       distribution is the Boltzmann distribution, and follows exp(-kE).
       It is a very easy trap to fall into, because it seems obvious,
       simple, and easy to understand: but it’s not what happens in
       reality.
     * William Seeley says:
       January 27, 2014 at 10:41 am
       While England’s research may point the way to specific mechanisms
       for increasing order in disordered systems and may thus play some
       upstream role in the reproduction of macro-molecules, it doesn’t
       address the critical role of “functional” information in both the
       origin of life and its continued enrichment through evolution. By
       functional information I mean something more than just repeated
       patterns of inorganic or organic molecules, but rather patterned
       information in one component of a living system that is homologous
       to patterns in one or more other components in the system. This
       type of information is the basis for message transmission and
       feedback loops between components of a living system and thus the
       synchronization of all of the subsystems that comprise it. The
       classic (oversimplified) example is
       … Transcription factors–>DNA–>RNA
       Polymerase–>Spliceosomes–>mRNA–>Nucleotide
       triplets–>RibosomestRNAAmino Acids–>Polypeptides–>Folded
       Proteins/Enzymes–>Transcription factors …
       That all of these subsystems somehow evolved in tandem and have
       highly coordinated functions in the metabolism and reproduction of
       living organisms is truly astounding. IMHO this type of information
       system depends on much more than the principles of thermodynamics
       and is the great unexplained mystery of Biology. While England’s
       work may be relevant to this at some level, I don’t believe that it
       begins to explain this central problem.
     * William Seeley says:
       January 27, 2014 at 1:32 pm
       The term “RibosomestRNAAmino Acids” in my previous post should read
       “Ribosomes–>tRNA–>Amino Acids”
     * Nezih Oktar says:
       January 28, 2014 at 8:12 am
       England’s notion puts Darwinian takeover, chaos theory, Jarzynski
       and Crooks’ formulation, Nobel Laurate Ilya Prigogine’s behavior of
       open systems, Boltzmann probabiliy all together.
       We have to test and gather data and to run experiments on living
       systems to support to understand life from a themodynamic
       perspective.
     * Pluri Bara says:
       January 28, 2014 at 10:37 am
       Interesting stuff, but not biology.
       Biology, life, is not just replicating matter. Rather it is
       replicating coded information.
       As long as information is not included, this is merely physics
       devoid of any biology, and irrelevant to solving the origin of
       biological systems.
       This is in no respect whatsoever a precursor of a living system.
       Science, in the first place biology, has to deal with the
       information content of biosystems. Denying or ignoring that life is
       based on information, is denying or ignoring science facts.
       Pluri
     * Ron Haley says:
       January 28, 2014 at 8:45 pm
       Re: “..it [group of atoms] will often gradually restructure itself
       in order to dissipate increasingly more energy.”
       Could the above read: Groups of atoms when steadily absorbing
       energy from an external source at a more rapid rate than their
       environment (e.g. an immersing fluid) will be restructured or
       reorganized by that energy in a manner that will dissipate the
       energy as heat to their immersing fluid (or intimately contacting
       substance) at a higher rate than their original structure allowed.
       RE: “Scientists have already observed self-replication in nonliving
       systems.”
       Given that many now question the meaning of “self” in humans, let
       alone animals or inanimate things, would it not be prudent to
       delete “self-“ from “self-replication”?
     * Doc the Dog says:
       January 29, 2014 at 12:19 pm
       In weak criticism of Granite Sentry, you state ” . . . there’s much
       more to reality than we can capture in an equation, a formula or a
       sentence. Physicists are always forgetting this simple fact that
       every poet knows.” I demur, to the extent that unexplained does not
       mean unexplainable. You seem to be saying that knowledge and its
       interpretation cannot advance past what we now know and accept. I
       suggest that Dr. England’s scientific progeny will, perhaps only a
       few tens of years from now, smile indulgently at your statement.
     * Lex says:
       January 30, 2014 at 1:22 pm
       It would seem that the same logic supporting the assertion that
       life occurs spontaneously as a result of the thermodynamic
       imperative of entropy would mean that at least some “living” things
       should be immortal. Or, put another way, what is the thermodynamic
       causation for death of the living things that successfully
       contribute to entropy?
     * Karo Michaelian says:
       January 30, 2014 at 8:18 pm
       In defense of my work, and that of many others, and particularly of
       my paper entitled “Thermodynamic Dissipation Theory for the Origin
       of Life” (arXiv:0907.0042[physics.gen-ph]2009; Earth Syst. Dynam.,
       2, 37-51, 2011), I would have to disagree strongly with the comment
       of Howard A. Landman (Jan. 27, 2:03) that my paper is “mainly a
       historical survey of previous work”. The introduction is certainly
       such, as should be the case in all papers, but if one bothers to
       read the remaining 8 sections, one would discover that it presents
       a detailed theory for the origin and early stages of the evolution
       of life as governed by the general non-equilibrium thermodynamic
       principle of structuring driven by dissipation. The paper first
       presents an explanation for the spontaneous formation of
       dissipative structures under a generalized thermodynamic potential,
       referring the reader to the original ideas of Boltzmann and
       rigorous demonstrations which go back to the 1930´s through to the
       1960´s with the work of Lars Onsager and Ilya Prigogine and their
       groups. England has provided a tentative statistical mechanics
       version of dissipative structuring, but a statistical version of a
       general principle concerning entropy production rates, rather than
       entropy, is what is really needed. Here there are earlier
       statistical results which do consider entropy production rates,
       e.g. R. Dewar, J. Phys. A, 36, 631-641, 2003, although the verdict
       is still out on the validity of these results.
       My paper then goes on to give empirical evidence for increases in
       the entropy production of the biosphere and its components over
       time in its interaction with the solar environment and relates this
       to Onsager’s principle (Onsager, Phys. Rev., 37, 405–426, 1931) of
       coupling of irreversible processes when this coupling augments the
       global entropy production (see also Morel and Fleck, J. Theor.
       Biol., 136, 171–175, 1989 and K. Michaelian, Hydrol. Earth Syst.
       Sci., 16, 2629-2645, 2012). I provide a physical explanation for
       the proliferation of RNA and DNA and other pigments in the Archean
       environment using a non-linear non-equilibrium thermodynamic
       result, similar to what Prigogine derived for a product catalyst in
       autocatalytic chemical reactions (see K. Michaelian, J. Phys. Conf.
       Series 12/2013; 475:012010 and J. Theor. Biol., 237, 323-335, 2005
       if you must see equations Howard Landman … I hope, however, that
       you don’t rest relevance from “On the Origin of Species” because of
       its lack of equations!).
       Later in the paper, I provide a mechanism for enzyme-less
       replication of RNA/DNA based on the dissipation of UV photons of
       around 260 nm, where RNA and DNA absorb and dissipate efficiently,
       on a gradually cooling sea surface at a temperature slightly below
       the denaturing temperature of strands of RNA/DNA ~70-80°C (a
       process similar to PCR which I call UVTAR — UltraViolet and
       Temperature Assisted Replication). My article also suggests a
       mechanism for the homochirality of RNA/DNA based on asymmetric
       (morning-afternoon) circularly polarized photon-induced denaturing
       of these molecules (see also K. Michaelian, Nature Precedings
       (2010) ) and suggests how information became encoded in RNA/DNA
       through the affinity of the aromatic amino-acids to their DNA
       anti-codons, suggesting that these amino-acids may have acted as
       antenna molecules to augment RNA/DNA – amino acid complex photon
       dissipation). Any theory purporting to describe the origin of life
       must necessarily explain homochirality and information
       accumulation. My student Norberto Santillan and I have obtained
       preliminary experimental evidence for the first part of the
       enzyme-less replication, the UVTAR mechanism suggested above, that
       of photon induced denaturing (see K. Michaelian and N. Santillan,
       “Fundamentos Termodinámicos del Origen de la Vida”, available on
       ResearchGate).
       With Oliver Manuel, we have shown how the thermodynamic dissipation
       theory for the origin of life places constraints on the solar model
       (K. Michaelian and O. Manuel, J. Mod. Phys, 2, 6A, 587-594, 2011).
       With Alex Simeonov we have shown how dissipative pigments have
       appeared over the evolutionary history of life following the
       evolution of the solar spectrum at Earth’s surface (A. Simeonov and
       K. Michaelian, to be available shortly from ResearchGate). Finally,
       the example of population dynamics given in England’s paper was
       treated by myself under a non-equilibrium thermodynamic formalism
       in 2005 (K. Michaelian, J. Theor. Biol., 237, 323-335, 2005.).
       Here, a plausible thermodynamic fitness function for selection was
       shown to be the ratio of global dissipation of the system over the
       change of entropy of the system, i.e. diS/dt/|deS/dt – diS/dt|,
       which selects highly dissipating systems with the stability of the
       stationary state. It is important to remark here that on the real
       time scales of biosphere evolution it is the whole system, biotic
       plus coupled abiotic irreversible processes, that is being
       thermodynamically selected, not the individual living entities.
       With Vasthi Alonso we have studied the thermodynamic stability of
       such systems under perturbation (V. Alonso and K. Michaelian, J.
       Mod. Phys, 2, 6A, 627-635, 2011).
       Finally, many of my students have contributed importantly to this
       work on the thermodynamic dissipation theory for the origin and
       evolution of life. Some of the most related thesis that should be
       mentioned are by Julian González, Vasthi Alonso, Noemi Hernández,
       Patrcia Jacome, Jessi Gatica, and Norberto Santillan. These thesis
       can be accessed directly from the central library at the UNAM.
       As you can see, we have an extensive research program on this
       subject involving many researchers which goes back at least 12
       years. That we present merely “a historical survey of previous
       works” on dissipative structures is a completely unfair caricature
       of our work. While we are on the subject, as other contributors to
       these comments have pointed out, there is a long list of workers to
       whom credit should be given with respect to the association of life
       with dissipation and thermodynamics. Some of the most important
       works that come to mind (I’m sure I am forgetting others) are
       Boltzmann, Onsager, Prigogine, Nicolis, Babloyanz, Wicken, Zotin,
       Ulanowicz, Lloyd, Pagels, Swenson, Morel, Fleck, Kay, Schneider,
       Dewar. The references to these works can be found in our articles
       or by doing a Google search.
       The journalistic report in Quanta on the paper of England has given
       public exposure to these ideas and that is a good thing. Papers of
       this kind are usually rejected by the traditional origin of life
       journals, principally because of a general lack of appreciation for
       non-equilibrium thermodynamics. That is now starting to change and
       we must be grateful for the publicity, but, at the same time, it is
       important to be fair in attributing credit where credit is due. It
       represents, after all, many years of hard work performed by many
       generations of scientists throughout the world on this subject.
     * William Seeley says:
       January 30, 2014 at 9:09 pm
       Doc:
       While I agree that just because a phenomenon is currently
       unexplainable doesn’t mean it that it always will be, I would hope
       that Dr. England’s scientific progeny will hold their indulgent
       smiles until the solution is actually in the bag. We can never know
       in advance whether “hard problems” will ultimately be explainable.
       This is example of what Alan Turing called the “halting problem”
       http://en.wikipedia.org/wiki/Halting_problem
       It is not unreasonable therefore to consider the possibility that a
       given problem cannot be solved, or can only be solved after
       paradigm shifts of the sorts that we saw with the advent of
       relativity and quantum mechanics. My sense of Dr. England’s
       discovery is that it is well within the comfort zone of the current
       biological paradigm for life’s origin, as resulting from a long
       series of physio-chemical reactions slowly occurring over billions
       of years (hence all the encomium in response to his finding). This
       has been the consensus of many of the greatest scientific minds
       since the emergence of the “Modern Evolutionary Synthesis” in the
       first half of the 20th century, and which was apparently confirmed
       in 1953 with the discovery of the structure of DNA. However the
       discoveries of molecular biology over the succeeding 60 years have
       not been kind to this synthesis, and in the consensus of many
       others it is in a shambles (this statement may strike some as
       outlandish, but I’m afraid I’ll have to leave it to our readers’
       curiosities to validate or disprove it for themselves). Suffice it
       to say IMHO that a paradigm shift in this area will probably
       require the death of the current generation of evolutionary
       biologists (see Thomas Kuhn’s “The Structure of Scientific
       Revolutions”) and the rise of their scientific progeny, who will
       not likely remember Dr. England as the next Charles Darwin, if they
       remember him at all.
     * Igor Fodor says:
       January 31, 2014 at 9:39 am
       It would interest me, how does the work of Jeremy English tie up
       with the following:
       Carl Woese published in 2004 in the journal „Microbiology and
       Molecular Review“ an article „A new biology for a new century“.
       There he described 3 phases of the evolution: predarwinian,
       Darwinian and postdarwinian era.
       We have here the so-called Woesian revolution (changed perspectives
       of the origin of the eukaryotes) and the discovery of Dimitar
       Sasselov, professor for astronomy at Harvard Univ. who is the
       director of the multidisciplinary „Harvard Origins of Life
       Initiative“.
     * Doc the Dog says:
       February 1, 2014 at 7:07 pm
       Mr Seeley:
       I am a curious reader and follower of science, but not a scientist.
       My training is in social science, namely in the formulation and
       assessments of urban policies, and I stay away from disciplines I’m
       not qualified to comment on. What I can do, however, is see and
       evaluate macro positions assumed by recent knowledge, as such
       positions are subsumed by all phases of inquiry. Your paragraphs
       are well received and enjoyed, but I submit that the long history
       of the pursuit of knowledge is, a bit like the stock market,
       upward, and builds (as Isaac Newton offered) upon the shoulders of
       giants.
       It is immense fun for me to read the proponents of one position or
       another in fields I haven’t studied since sophomore biochemistry,
       and that was, indeed, a long time ago. Judging, however, from the
       great advances in virtually every field (my own notwithstanding),
       It’s pretty difficult to admit of very many insoluble problems.
       Additionally, I hardly think Dr. England would describe himself as
       earth-shaking as Darwin. Who is. As for me, I side with Edward O.
       Wilson’s famous ant, encased in lucite with a banner protruding,
       which says, “Onward and Upward!”
     * Wayne Farmer says:
       February 1, 2014 at 7:38 pm
       I did not see gravity mentioned in the above comments, so I’ll ask
       this. What is gravity’s effect upon the systems described by Jeremy
       England? Is the life-spawning “heat bath” that Jeremy describes
       most often created in a gravity well? Is there evidence that any
       other attractive forces encourage self-organization? Some
       physicists might be able to quickly tell me whether organized
       atomic and sub-atomic structures dissipate energy more readily than
       would a sea of their smallest components?
     * GG says:
       February 3, 2014 at 3:21 am
       Great fan fiction!
       PS: “The reason that an organism shows characteristic X rather than
       Y may not be because X is more fit than Y, but because physical
       constraints make it easier for X to evolve than for Y to evolve.”
       I wonder what Louis’ definition of fitness is. Because my
       definition of fitness includes thriving better under physical
       constraints, and thus evolving easier under physical constraints.
     * Daniel Shawen says:
       February 4, 2014 at 10:36 am
       The description of the process and the mathematics associated with
       it is a bit too general to provide insight into the detailed
       processes of life. Protists like Euglena and Volvox are more
       prolific and better at harnessing vast amounts of energy near the
       ocean’s surface through photosynthesis, so why go to all of the
       trouble to eventually make itself into a something like a tree? I
       rather think that the process is driven by other forces more
       compelling than simply to “dissipate energy”, or even competition
       with other individuals for energy from the same or even a different
       source. Is there an expression for the maximum efficiency of such a
       system, or does the environment impose its own or other
       limitations? Why would efficiency (such as in the thermodynamic
       sense) be the ultimate goal of life? It doesn’t even explain the
       reason for the near infinite variety of snowflakes, does it really?
       Mathematics is just another symbolic language that human beings
       have created to communicate with each other. It is entirely
       possible to scribble out as many kinds of silly ideas using math as
       it is in any other human language. More’s the pity, many people
       can’t tell the difference, in any language. But by all means, keep
       trying.
     * Michael Syvanen says:
       February 4, 2014 at 8:36 pm
       Daniel Guerriere wonders:
       “If the hypothesis be verified, then Darwinism would have a major
       problem. For Darwinism presupposes that all of life has a single
       origin. The hypothesis, however, allows for, indeed makes
       plausible, multiple origins. But if life has multiple origins, then
       what explains the same molecular structure across all of life? ”
       Well wonder no more, here is an explanation. One minor correction:
       Darwin never presupposed that all of life had a single origin, that
       came later under what was called neoDarwinism. An explanation for
       the biological unities is that horizontal gene transfer is the
       agency that maintains unity. As is described in papers 1, 9, and 15
       at:
       http://www.vme.net/hgt/
       and an attempt to describe this to an interested lay audience at:
       http://www.pandasthumb.org/archives/2005/08/the_last_univer.html
     * Garvin H Boyle says:
       February 6, 2014 at 10:21 am
       What a great article, and a powerful and important idea. The study
       of this idea is long overdue.
       It strikes me that it is a variant on the ideas of H. T. Odum as
       described by his former student Charles Hall (“Maximum Power: The
       Ideas and Applications of H. T. Odum”, Charles A. S. Hall, Ed.,
       University Press of Colorado, 1995). Odum came to believe that all
       ecosystems self-organized to use (consume or dissipate) energy at a
       maximum rate. In Darwinian terms, the organism that garners the
       largest share of the available flow of energy will out-compete the
       others at the same trophic level, so those mutations that enable
       higher rates of consumption of energy, in every generation, and at
       every trophic level, have competitive advantage. Ultimately, as the
       ecosystem approaches a stationary state far from equilibrium (one
       of Prigogne’s dissipative structures) it reaches a state of maximum
       power.
       I also see this as closely aligned, intellectually, with the
       concept of the Maximum Entropy Production Principle, as discussed
       by Martyushev ( http://arxiv-web3.library.cornell.edu/abs/1311.2068
       ) and many other places on the web.
       I, personally, also believe that it can be used to explain why the
       modern global economy has evolved over time to be such an
       exceedingly wasteful engine of ecological destruction, consuming
       mass and energy at ever higher rates, until we reach a maximal rate
       of consumption. Unfortunately for us, the Earth’s resources are
       limited, and our consumption rate is now largely supported by
       extraction of immense quantities of non-renewable energy resources.
       Charles Hall’s concept of EROI, and the rapidly declining value of
       this indicator for all modern fossil fuel resources, tells us that
       the end is coming too soon. This can only end badly for us. I
       believe it is absolutely critical that we come to understand this
       phenomenon much better, and understand its implications for how we
       live and organize ourselves.
     * Mark Ciotola says:
       February 9, 2014 at 12:35 am
       Similar ideas have been floating around for decades, but it is hard
       to get this stuff published in physics journals. I’m glad to see
       Rod Swenson mentioned, and Arto Annila at University of Finland has
       done much work in this area as well. I am pleased that others such
       as Karo Michaelian are familiar with the development of this area
       and have made their own contributions.
       I have used this idea since 2001 for modelling history and
       economics, using the name “Principle of Fast Entropy” or “e th Law
       of Thermodynamics” since it drives exponential growth. One way to
       word the e th law is that “an isolated system will tend to maximize
       its rate of entropy production.”
       Nevertheless, I prefer alternative wording: “an isolated system
       will tend to maximize its achievement of thermodynamic potential”.
       (People hate entropy but love achievement and potential).
     * Mark Ciotola says:
       February 9, 2014 at 12:40 am
       @Ted Pavlic, do you have links to your work?
     * lara says:
       February 10, 2014 at 8:38 pm
       This is really interesting. Once this is researched more, I wonder
       how it could be applied to cell behavior…specifically related to
       tumor growth, etc. If cell behavior can be linked to resonance,
       there could be some exciting new fields of medicine open up?! Or am
       I totally mis-understanding the implications of this?
     * Cobes says:
       February 12, 2014 at 5:32 pm
       The theory indicates that life is more likely to form? In this case
       would life which exists on earth now have been enriched by multiple
       starting points? I guess life being depleted by competing starting
       points is as likely as life being enriched.
       Is there a way to determine life starting points? Is there any
       indication that there have been multiple starting points. I am
       guessing that no one ever checked because we all believed that life
       is a unique occurrence.
     * Mike says:
       February 13, 2014 at 3:46 pm
       Interesting and wonderful article. Fun thought: Are stars living
       things? They are an assortment of atoms that have assembled
       themselves (low entropy) by the force of gravity and use that force
       to disperse/convert nuclear energy into its surroundings (higher
       entropy) with light and heat. They reproduce themselves- ejection
       of planetary nebula seeds and induces further star formation.
     * Henry Harrison says:
       February 18, 2014 at 1:19 pm
       I see Rod Swenson has been mentioned, I would like to point out
       that there is a group at the University of Connecticut following up
       on his work, closely related to England’s. They call their project
       “Physical Intelligence” and for a short time were funded by DARPA
       before DARPA became convinced the goals of PI were too lofty.
       In 2012 they published their perspective over a couple of special
       issues in the journal Ecological Psychology:
       http://www.tandfonline.com/toc/heco20/24/1
       Special Issue: On Intelligence from First Principles I: Dissipative
       Structures, Impredicativity, and Intentional Dynamics
       http://www.tandfonline.com/toc/heco20/24/3
       Special Issue: On Intelligence from First Principles II:
       Information Perspectives, Formalizing Autocatakinetics, Physical
       Pattern Formation, and Plant Perception-Action
       I think this is a good entry point into these theories, since this
       group contains psychologists in addition to physicists (and
       others), so some of their writings are perhaps a bit more
       accessible than those in a more purely physical traditional.
       In any case, I am excited to see the same insights happening
       elsewhere, and I hope to see more collaboration in the future
       between these various groups.
       Disclaimer: I am a Ph.D. student in Ecological Psychology at UConn,
       however I don’t work on the Physical Intelligence project myself.
     * wayne lambright says:
       March 2, 2014 at 5:21 pm
       In my opinion, life was brought to our planet. Meteor or other
       method. At this point its a guess.
     * Mikoman says:
       March 5, 2014 at 10:46 am
       This sounds really similar to an idea I read in a book: _Design in
       Nature: How the Constructal Law Governs Evolution in Biology,
       Physics, Technology, and Social Organization_ by Adrian Bejan which
       ultimately came down to flow dynamics, too. So I agree, the idea is
       not really new. But we all stand on the shoulders of giants, right?
       I do applaud Dr. England for being true to the scientific
       enterprise and giving us a testable hypothesis. At a minimum, it’s
       an intriguing conceptual framework. At least at the chemical level
       where proto-life merges into life. I am still struggling to see how
       this would really apply for large-scale (meaning multicellular)
       organisms.
       I don’t think I can agree that a self-replicating configuration of
       atoms like a plant should be better at dissipating energy than a
       random compilation of the same atoms. Isn’t the whole idea of
       photosynthesis that plants use solar energy to build carbon-based
       molecules to _store_ energy? I would think plant life will retard
       the dissipation of energy over longer time frames than an inert
       grouping of similar mass which will simply reflect or radiate the
       energy away. But again, that’s the great thing about this kind of
       work; we can actually test it!
     * Shivam Saxena says:
       March 6, 2014 at 8:09 am
       It is a big step towards the micro understanding of universe.
     * jay cohen says:
       March 7, 2014 at 8:11 pm
       - I don’t think we have, as yet, evolved the intellectual
       brainpower to understand the origin of life. It’s like trying to
       explain differential equations to a frog. There is something that,
       as humans, we cannot yet see.
     * Pentti S. Varis says:
       March 8, 2014 at 10:46 am
       http://www.helsinki.fi/~aannila/arto/
       Professor of biophysics Arto Annila (Univ. of Helsinki) has
       developed a partly similar evolution theory as Dr England. Both are
       based on Prigogine and second law of thermodynamics. Annila has
       however discovered an universal formula wich contains the principle
       of least action (de Maupertuis) too ( Proc.R.Soc. A (2008) 464,
       3055-3070).
     * Tomasz Helenowski, M.D. says:
       March 13, 2014 at 12:00 am
       Since all “living” things are physical, the fact that they follow
       laws of thermodynamics is not surprising. All physical things
       should, whether they are alive or not. This does not explain the
       evolution of “life”, which is not even defined here. I am a
       neurosurgeon having studied biology and living things for decades,
       yet have never found a satisfactory definition of “life.” One of
       the questions raised above asks if stars are alive. By biological
       criteria, no, because they are not made of cells and all living
       things are typically defined to be made of cells. By that
       definition, viruses are not alive also, because they are not made
       of cells. They just cause changes in living things. Before we talk
       about the evolution or origin of life scientifically, it would be
       best to define what we mean by “life.”
     * Steven Solomon says:
       March 19, 2014 at 12:01 pm
       Wonderful discussion!
       @Jim Douthit: in the complex electro-chemical activity of the human
       brain, matter reaches such a degree of complexity that it escapes
       being determined or predictable.
       It’d be great if the transition to self-consciousness could be more
       quantifiably related to the “2ed Law.” This inter-disciplinary
       forum would be a perfect “ideation factory” to accomplish this.
     * John F. says:
       April 2, 2014 at 1:21 pm
       This theory begins with a major presupposition. The theory begins :
       “You start with a random clump of atoms…”
       You’re presupposing the existence of the atoms which have no reason
       to be presupposed. How did the atoms come into existence out of
       nothing in the first place to create life?
     * Antony Upward says:
       April 2, 2014 at 4:57 pm
       I’m so glad the connections got made between Mr. England’s work and
       Non-Equilibrium Thermodynamics (NET).
       I’ve read Into the Cool: Energy flow, thermodynamics, and life by
       Schneider and Sagan – which was a wonderful introduction to the
       subject. These others papers are also good
       Kay, J. J., & Schneider, E. D. (1994). Embracing complexity: The
       challenge of the ecosystem approach. Alternatives, 20(3), 32-39.
       Schneider, E. D., & Kay, J. J. (1994). Life as a manifestation of
       the second law of thermodynamics. Mathematical and Computer
       Modelling, 19(6-8), 25-48. doi:10.1016/0895-7177(94)90188-0
       But personally I found Supply Side Sustainability by Allen, Tainter
       and Hoekstra far more compelling – since it worked through NET not
       only in the natural sciences (physics, chemistry, biology, ecology)
       but into the social sciences too (history, sociology, economics)
       and then into management.
       I have short summary of this book (and the key paper) some may be
       interested in here:
       http://www.slideshare.net/AntonyUpward/supply-side-sustainability-s
       ummaryupward-av102
       Allen, T. F. H. (2003). In Hoekstra T. W., Tainter J. A. (Eds.),
       Supply-side sustainability. New York City, New York, U.S.A.:
       Columbia University Press.
       Allen, T. F. H., Tainter, J. A., & Hoekstra, T. W. (1999).
       Supply-side sustainability. Systems Research and Behavioral
       Science, 16(5), 403.
     * Antony Upward says:
       April 2, 2014 at 4:59 pm
       But I have a question for the community: who is continuing the work
       on Non-Equilibrium Thermodynamics (NET)? Who are the current
       leaders in the this field?
       For example Dr. Brian Cox appears to align with in Mr. England in
       his excellent recent BBC Series the Wonders of Live, but is all
       this work now dotting the i’s and crossing the t’s of NET – or is
       their still yet fundamental work to confirm of falsify? Who is
       doing this important work?
     * Neal Shannon says:
       April 18, 2014 at 11:10 pm
       This is great, I feel like I have been thinking this for quite some
       time, but hadn’t the scientific education enough to make anything
       of it. Everything is all apart of an intelligent design, wether you
       believe that design was created or naturally occurring. Physics,
       Chemistry, Biology, all of these branches of science are still just
       our definitions used to communicate what we have learned about
       reality, but the reality never changes. If we already had the
       answers, it would be like a palm thump to the forehead like “that
       is so simple!” (not that I am saying it is easy). Everything is the
       same, maybe expressed differently at times, but the more we zoom
       out the easier it is to see this. I’d suspect that the grand cosmos
       and even beyond our universe there are similar systems at work to
       the ones we have already uncovered. Evolution was good, but if this
       theory can be used to more accurately predict reality, it wouldn’t
       surprise me. There could be scales of reality below even the
       smallest quantum mechanics we know of, that have been building up
       to create this reality, which in turn is apart of something even
       much greater. Everything is relative. It is our responsibility as
       living beings to keep expanding our existence and knowledge and
       dissipate it across the universe until we can truly understand.
     * jim Davis says:
       April 29, 2014 at 8:37 pm
       If I understand this correctly , inanimate matter exposed to light
       , under the right or probable circumstances causes or makes it
       possible for systems to evolve to a point at which they can absorb
       and dissipate energy efficiently enough to evolve to ever
       increasingly complex systems . Would this process be one of
       necessity or probability , but each following a physical law ?
     * michael yaros says:
       April 30, 2014 at 2:20 pm
       I am not a physicist, but I have enjoyed the discussion. The most
       interesting questions for me are:
       Is life required to produce consciousness, or can a machine or
       supercomputer that can pass a Turing test achieve consciousness?
       Is consciousness an “all-or nothing” phenomenon, or are there
       gradations?
       From all I have read, consciousness seems to require both access to
       (sensory) inputs from the external environment as well as models of
       that environment coded in a form of memory. Additionally, the
       conscious portion must have an underlying subconscious support that
       filters and determines what aspects of the world reach
       consciousness.
       Life as I understand it involves both the replication of coded
       information, as stated above, but also an ability to maintain an
       energy gradient such that energy flows through the system and never
       reaches an equilibrium state.
       It would also seem to me that the evolution of consciousness is
       more likely determined by it’s Darwinian advantages than energy
       dissipation constraints.
       Overall, I’d say that based on what I’ve read, the evolution of
       matter and life can be best described as the sum of interaction
       between both the Darwinian and the energy dissipation hypotheses,
       as applied to the raw materials (i.e. environment) under
       consideration. Thus, radically different forms of life or
       organizations might occur depending on the environmental
       constraints. Our Earth has a particularly favorable environment for
       what has evolved here, not unexpectedly.
     * Jacques de gerlache says:
       May 7, 2014 at 6:58 pm
       this “new theory” is indeed mainly the theory of “maximal entropy
       production” already proposed in 1922 by Alfred Lotka and more
       particularly developed by Rod Swenson in the nineties on the basis
       of Prigogine’s work before its “demonstration” by Roderick Dewar in
       2003, even if the demonstration is not perfect. It was also
       developed by many others including Kleidon and others mentionned in
       the comments. The is also a very intersting book (in French) by the
       astrophysician François Roddier called “Thermodynamique de
       l’évolution” which is largely based on the MEP law and goes quite
       far in its biological and ecological implications, including in the
       evolution of human culture
       Often useful to make some literature review before claiming to have
       made a “great discovery”
     * Jacques de gerlache says:
       May 7, 2014 at 7:18 pm
       here the link to a short animation movie explaining the maximum
       entropy production principle ,available since about 3 years :
       https://www.youtube.com/watch?v=_WLYOYE8a5o
       and its complement explaining how difficult are paradigm shifts …
       Enjoy ! https://www.youtube.com/watch?v=DdvkOXN2KvA
     * Kevin McCulley says:
       May 22, 2014 at 9:33 pm
       Such civil and intelligent discourse!? Is this truly still the
       Internet?
       As a lay person with an insatiable information addiction,
       especially when physics are involved, I find this article very
       intriguing. Perhaps it even offers a solution to Fermi’s paradox in
       that a self inflicted nuclear war of extinction would dissipate a
       significant amount of energy. Judging from humanity’s own
       propensities for war and my predictions on man’s demise, this may
       be the natural endstate for sentient life thus in the same breath
       demonstrating that life is common and also why the sky is so quiet.
       -KPM
     * Tim Borkowski says:
       May 31, 2014 at 1:43 am
       Great article about a potentially wonderful idea. Only one
       question: where is the formula? I didn’t see in the article (maybe
       I overlooked it). HELP!!!
     * Andrei Laszlo says:
       June 7, 2014 at 1:16 am
       Hi..I am at the end of the line, but I have a few things to say….I
       agree with most people, that at least as this work is presented, it
       is an expansion of the ideas of Prigogine, which is fine. (And
       other theories). However, there is a utter confusion between
       ensemble properties and the nature of the components of that
       ensemble. The principles mentioned here concern the optimization of
       thermodynamic stability far from equilibrium; but where to the
       molecules come from ? the amino acids, the nucleotides, lipids,
       sugars, etc ? the notion that “rna is a cheap building material”
       totally misses the point….RNA is thought to have evolved because it
       has the chemical property to cut and edit itself. It is difficult
       to reverse engineer the origin of life…we only have what worked. It
       seems to have happened slowly..the earth is thought to be 4.6
       billion years old, with the evidence of earliest life forms
       3.8-3.48 billion years ago. The rest of the time we went from
       bacteria to men…how the building blocks and the self replicating
       systems arose is still a mystery. But say that the earlies
       lifeforms has the right thermodynamic properties….it still took ~
       1.5 million years to evolve simple prokarotes, 1 billion for
       primitive eukaryotes, and 1.55 billion years to get primates….the
       evolution of biological systems is very slow…
     * Neptune says:
       June 21, 2014 at 8:10 pm
       I was wondering on how complex carbon based chemicals started
       replicating…I was not believing that RNA and DNA can replicate by
       themselves…suddenly while working on other issues…I realised
       thermodynamics!! I googled if anyone has done work on this or
       thought about it before and found this article.
       I appreciate the work and my intution says that we will be able to
       find thermodyanmic condition for creation of life from chemicals!!
     * william c wesley says:
       July 16, 2014 at 12:40 am
       the late theoretical physicist my father Dr James Paul Wesley wrote
       a book called ECOPHYSICS that was published in the 70’s which
       provided an “ecophysical definition of life” based on the laws of
       thermodynamics. this book was very detailed and contained a great
       deal of mathematics to support the same ideas seen here, but
       further it applied those ideas to the evolution of technology as
       well as biological life.
     * Richard G. Lanzara says:
       July 19, 2014 at 6:44 am
       Does life equal dynamical equilibrium systems that can sense net
       perturbations from their equilibrium states? Life also senses and
       recruits molecules/energy from the environment into its coupled
       dynamical systems.
       Therefore what is missed? -Well the thermodynamics of these systems
       explains the change of state, but not how they got there (by what
       path), nor how they might be maintained (by oscillating
       reactions?). Differential equations describe the rate of change in
       these systems, but not the net change into new dynamical
       equilibrium states. Therefore there exists an in between area that
       requires a better understanding.
       A physical example of this is a simple, two-pan balance. A balance
       in perfectly horizontal equilibrium with masses on each side can be
       shifted or perturbed by the addition of an asymmetric force in the
       form of an additional mass or an external force on one side of the
       balance. These perturbations can shift the equilibrium position of
       the balance either temporarily via an oscillation around its
       original equilibrium or permanently to a new position of
       equilibrium whereby the balance is shifted. The thermodynamics or
       differential equations describing such a system as a simple balance
       misses an essential physical property of this system – its net
       change. This is fundamentally how living systems sense and respond
       to changes in their environments (see: Weber’s Law Modeled by the
       Mathematical Description of a Beam Balance, Mathematical
       Biosciences 122: 89-94 (1994) (
       http://www.bio-balance.com/Weber's_Law.pdf )).
       The net changes within their coupled dynamical systems are embedded
       within the framework of their organized states, which may propagate
       these net changes to other parts of these networks, thereby
       prompting these networks to change. As a simple example, two or
       more coupled chemical equilibria could be shifted by a net change
       (Le Chatelier’s principle) that could be propagated from one to the
       other (ie. as occurs in cellular receptors, such as the G
       protein-coupled receptors -see: Molecular dynamics of a biophysical
       model for beta-2-adrenergic and G protein-coupled receptor
       activation Journal of Molecular Graphics and Modelling 25: 396-409
       (2006) ( http://www.bio-balance.com/JMGM_article.pdf )).
       Several good points were made previously in this comments section
       (which is one of the best discussions that I’ve seen anywhere). The
       fact that other planets in our solar system are bombarded by energy
       and have similar chemical constituents suggests that life on earth
       is unique or at least at a more advanced stage of life than the
       other planets. What might account for this? Could it be that there
       is a certain resonance within and among these coupled equilibrium
       systems that enhance their expression? One possible guess is that
       there are certain cycle-resonances among these coupled systems that
       best match the cyclical changes of the surrounding physical
       systems. Once these physical and chemical systems are aligned, they
       may evolve into more complex systems through periods of repeated
       iterations. (This suggests that one should study the synergies
       between and among coupled chemical/physical systems to observe how
       they might evolve.)
       After all, we have reached the point where we can breakdown living
       systems into their basic chemical/molecular components and
       reassemble them as new living systems (Dr. Venter’s work on
       artificial life).
       This suggests that we’re beginning to understand the fundamental
       chemical/molecular foundations for life. This is truly an exciting
       time.
     * s.k. mazumder says:
       July 31, 2014 at 4:36 pm
       Am an old timer not computer savvy who stumbled upon this wonderful
       discussion. Dr.
       England seems to have missed out on the work at Santa Fe
       institution, especially that
       of Stuart Kauffman. Somewhat surprising.
     * Caroline Hitch says:
       August 5, 2014 at 11:28 am
       The picture I’m getting these days is that, at all scales, matter
       organizes to channel flows of energy. Just finished the wonderful
       book by Alexei Kurakin, “The Self-Organizing Fractal Theory as a
       Universal Discovery Method: The Phenomenon of Life,” in which he
       makes the chemical case for flow. Adrian Bejan makes, primarily, an
       engineering case for it in, “Design in Nature How the Constructal
       Law Governs Evolution in Biology, Physics, Technology and Social
       Organization”–although the book does get bogged down in quite a bit
       of tedium. I also loved Eric Schneider and Dorian Sagan’s, “Into
       the Cool: Energy Flow, Thermodynamics and Life.” It appears to me
       that thermodynamics, since it does control the flow of energy,
       would be the “big” prime mover. While I agree with many others that
       this is not a new line of thinking, since Ilya Prigogine had
       already set this ball in motion some time ago, if Jeremy England
       has come up with an equation that can map this and, therefore, get
       the concept into the good graces of the establishment–well, bless
       his soul!
     * tarick says:
       August 9, 2014 at 4:38 am
       The discussion is more than wounderful . I enjoyed it so much . My
       comments are : – England considered that the essence of life is ”
       replication ” i.e once matter is continuously replicating ,it can
       be considered life . Replication is only one of the characters of
       life . crystals are replicating but are not considered living at
       all . The idea of energy dissipation and conservation can’t by
       itself explain the vast compexity of life structure and function ,
       in all stages life has passed through . for example the evolution
       of multicellularity , the evolution of sex , the evolution of ”
       consiousness .
     * Caroline Copley says:
       August 12, 2014 at 8:17 am
       This is an area that interests me but I confess my level of
       understanding does not reach that of some of the other posts but I
       think that it is important to clarify some things. There is the
       requirement of the state or situation in which the early progenitor
       to the protocell arose. This is where the concepts of England and
       others regarding entropy must be invoked, if not later to describe
       ecological systems. The original state was a physical state and not
       a biological one until life prevailed and as such must obey all
       known physics rules. However the possibility exists that early
       organisms may have initially overcome some of the constraints of
       the physical universe, or at least to minimise them.
       I have been greatly perturbed by the constant use of “equilibrium”
       forest ecosystems etc. and it is very difficult going from the
       molecular (such as Jason Fordham above describing Boltzmann), to
       the macro level of organisation of microbial communities or
       forests. Thanks for all the links by the way although noone
       mentioned Harte’s or Ichuru Aoki’s books, but Kauffman was
       mentioned who described the possibility that dynamical
       non-equilibrium systems could be stable, which seems to me a better
       description for forests. Whatever consensus is eventually reached
       the molecular to the ecosystem level should be consistent in the
       final thesis. Except that we all know that Einstein/gravity and the
       quantum world aren’t that consistent! So do we have to await the
       outcome of those investigations before we assign Boltzmann to the
       wider world of soil bacterial communities? It seems to me that
       until physics resolves that dilemma it will be quite plausible to
       differentiate macro and micro systems as Mikoman suggested above,
       especially in the biological world which attempts to control the
       physical (albeit with various success levels).
       The new theories of life based on entropy could be maligned, but
       then that is what was done to the chemical theory of life 50 years
       ago I heard. Some of the posts above note that there is a chemical
       and physical state or condition which occurred when life first
       arose. This is very important and Richard Lanzara made good points
       about coupled physical and chemical systems. Biology is a third
       system that interacts with the physicochemical surroundings, and
       very often overcomes or utilizes them or improves conditions for
       its own purposes. Of course it must ultimately be accountable to
       physics processes such as entropy and this may indeed be a driving
       factor in the organisation of some or most ecosystems and
       communities, but perhaps not in ways proposed.
       There is still the problem of the original and yes I heard the word
       sentient, organism.
       Much investigation has been done on chemical factors involved such
       as the ATP system and H systems, and also on heavy metals, so that
       early organisms could have arisen primarily in response to chemical
       factors. The fundamental nutrient requirements of nascent life
       really needs to be clarified before we can make any estimates
       regarding chemical equations etc. and thus energy and entropy. The
       truth is we don’t have THE equation or cycle involved really,
       although everyone acknowledges that RNA was involved very early in
       the piece.
       Personally I think the entropy outcomes of the ADP/ATP system which
       is shared by all lifeforms is important. Back when life began I
       don’t know if you’d be able to call the first precursor of the
       protocell an “ecosystem”, so we are definitely not very much at the
       macro level there. My view is that it probably arose as a chemical
       system under a membrane, say strung between two rocks, which became
       so coordinated that it eventually acted as one. Water readily forms
       a filmy membrane between surfaces. However one is a lonely number,
       so that if a number of such chemical “bubbles” existed and they
       began to “trade” scarce nutrients with each other, perhaps you do
       have a nascent ecosystem, perhaps some kind of efficiency is
       involved, and did someone mention necessity?? So what nutrient was
       missing on the rockfaces of volcanic vents that starving semi-alive
       bubbles would need that may instigate trading?
       The other thing I found interesting I owe to good old Lehninger I
       think who describes in his biochem books the HUGE AMOUNT OF energy
       that plants have to deal with. And strangely enough not only
       photosynthesis, but the entire mitochondrial and ATP system is set
       up to deal with exactly what the article described, dissipating
       energy, but not in the sense proposed. The problem is too much
       energy. If our cells dealt with all the energy we give them in one
       hit they would die. Plants cannot deal with the amount of solar
       energy provided daily, so deal with it in a stepped process, as
       animal cells do in mitochondria. Do two of the most major biology
       energy production systems ultimately produce a net entropy or not?
       One thing I do agree on is that after the nascent filmy bubble of
       chemicals coalesced and later formed a protocell complete with RNA,
       they were no longer, I’m sorry, physical in the true sense of the
       word. That is why I do not worship crystals, even if you do.
       Because they are just solid objects. I really have trouble with the
       split in science where entire systems are studied by either
       physical scientists or biologists and never the twain shall meet.
       This is most noticeable in carbon chemistry where in spite of the
       urgency of the matter, some see the problem as a purely
       physical/chemical study, and others are only interested in
       microbial or plant production systems. Any theory that proposes to
       describe life cannot be a purely physical theory, because then it
       is about a rock.
       Lifeforms are not purely physical objects, they are indeed
       sentient. Even the most primitive bacteria has sophisticated
       responses, and one of these is to move away from the pipette- to
       survive. What rock does that? It is as though life is a response
       system, a response to the physical environment, a way of overcoming
       it. Which by the way is why it is so dangerous to degrade the
       biosphere, because the physical environment will take its planet
       back with no “by your leave” for any of us. Only by maintaining
       biosphere resilience can we avoid its worst excesses, and even then
       not always, such as in the case of earthquakes etc.
       So if life is seen as a response system, perhaps its function is to
       diminish entropy, not increase it, but as I do not know the results
       of the entropy production in the ATP or photosynthesis systems
       which would give a clue, I can’t be sure. Thus self-organisation in
       a community or ecosystem would be in order to decrease entropy
       found in the physicochemical surroundings, and this could be seen
       as a form of efficiency.
       In that type of scenario, organism death would be when the (body)
       system can no longer provide a response (literally) and when in
       fact entropy does increase. However this is simplistic because
       apostasis (cell death) appears to be some sort of necessary
       component of bodily systems so that cell growth (cancer) can
       actually cause illness and death.
       My final thought is that Einstein’s E=mc2 leaves out entropy, and
       that there is a second term giving a different equation which
       probably includes the circular/squared term but also an exponential
       one representing demise. That would give you energy and matter as
       well as decline and destruction, all of which are represented in
       the Universe and on this planet. That is, especially when watching
       the lion killing the buffalo, I can’t see how other than with
       trophic energy explanations (which was an important addition above)
       anyone can see too much order in that.
     * Matthew Kosak says:
       September 4, 2014 at 5:00 pm
       If it is true that chemical systems will as claimed here, progress
       towards more energetically dissipative states, that would be a real
       finding, let alone one that’s relevant to the origin of life. There
       are really two responses I can think of, one chemical or
       ‘experimentally’ based, the other is more theoretical. If the
       paper’s theory holds, then I would expect to see some new chemistry
       presented, at a very basic level. Chemical systems that tend to
       dissipate heat are known as chemical systems, that is what
       molecules do when they combine. Exothermic or endothermic etc. If a
       system will become complex because it tends toward a dissipative
       one, then my question would be, OK are the molecules of DNA and
       proteins in an organism at the most dissipative level? Because,
       intuitively I’d say they’re not. And that’s because they are not at
       their lowest energy state possible, meaning no more energy can be
       absorbed, and thus maximum energy would be dissipated. The second
       point, is theoretical. In short, the paper begins with the premise
       that reversing entropy is like “unscrambling eggs,” and we all have
       an intuitive sense of entropy. And yet, we are to imagine that
       given enough time, or with long enough energy input, the egg will
       unscramble itself? I wanted clarification on that point, but
       unfortunately the paper itself, which I’ve read, is unclear on this
       conclusion. So I’m frankly not really sold on the notion that “if
       you shine light long enough on atoms, it forms a plant,” which I
       assume means a thousand million years or so.
     * Caroline Hitch says:
       September 6, 2014 at 2:16 am
       Ms. Copley,
       If I properly understood your last comment, there is actually
       plenty of order in a lion killing (eating) a buffalo; i.e., the
       uptake of essential nutrients by the lion and the continuation of
       its organization. The buffalo, too, has it’s own energy sources. In
       fact, how could there be any ecology if there wasn’t such an
       auto-catalytic cycle occurring amongst all the parts? Just the
       same, it does seem so very cruel to me, as perhaps it may to you.
       However, as raw as the whole thing is, I think that the cruelty
       view is mistaken; that is, there really isn’t a separate lion and
       buffalo, just the cycle of an evolving universe in the process of
       becoming aware of itself. Of course, that includes humans feeling
       repugnance over such apparent barbarity, but humans judge it as
       such only on account of their increased sentience. The proposal (of
       the universe becoming aware of itself) might seem too new-agey for
       most on this forum, but then what theoretical argument can make a
       good case against it? I realize that it’s not the topic under
       discussion, but it might help serve to clarify the role of all
       processes, thermodynamics included.
     * Jeremy England says:
       September 15, 2014 at 9:50 am
       In case readers are interested in more details, here is a link to a
       video-recorded lecture that I gave in Stockholm in September 2014
       on the research referred to in this article:
       https://www.youtube.com/watch?v=e91D5UAz-f4
       Jeremy England
     * Phil Greenfield says:
       September 19, 2014 at 3:58 am
       So humans are charged by 2LoT to destroy every world that they
       populate? And as efficiently as possible whilst maintaining their
       own integrity? We are the most efficient agents of entropy that
       have yet emerged. The best thermal soup chefs in town. Nothing
       more. I like that.

Leave a Comment Cancel reply

   Your email address will not be published. Your name will appear near
   your comment. Required *

   Name * ______________________________

   Email * ______________________________

   Website ______________________________

   Comment
   _____________________________________________
   _____________________________________________
   _____________________________________________
   _____________________________________________
   _____________________________________________
   _____________________________________________
   _____________________________________________
   _____________________________________________

   Post your comment

   More Articles
     * Most viewed
     * Recent

     * ‘Big Bang Signal’ Could All Be Dust ‘Big Bang Signal’ Could All Be
       Dust
     * Unheralded Mathematician Bridges the Prime Gap Unheralded
       Mathematician Bridges the Prime Gap
     * A New Physics Theory of Life A New Physics Theory of Life
     * The Thermodynamic Theory of Ecology The Thermodynamic Theory of
       Ecology
     * Finding Dark Energy in the Details Finding Dark Energy in the
       Details

     * [Lizards_Thumb.jpg&w=48&h=48&zc=C] Lizard Stowaways Revise
       Principle of Ecology
     * [cosmic_dust_thumb.jpg&w=48&h=48&zc=C] ‘Big Bang Signal’ Could All
       Be Dust
     * [blanco-telescope2_thumb.jpg&w=48&h=48&zc=C] Finding Dark Energy in
       the Details
     * [yeast_thumb.jpg&w=48&h=48&zc=C] Evolution’s Random Paths Lead to
       One Place
     * [MaxEnt_thumb.jpg&w=48&h=48&zc=C] The Thermodynamic Theory of
       Ecology

Archives

   [Select month____]

Categories

     * Biology (40)
     * Computer Science (12)
     * Mathematics (21)
     * Physics (39)
     * Q&A (8)

   Video
   [LongSword.jpg&w=240&h=135&zc=C]

   Mathematical Impressions

   George Hart

Long Sword Dancing

Quanta Magazine

   Quanta Magazine is an online publication whose mission is to enhance
   public understanding of research developments in mathematics and the
   physical and life sciences. Quanta articles do not necessarily
   represent the views of the Simons Foundation.

   About Quanta Magazine

     * Thomas Lin
       Managing Editor
       tlin(replace this with the @ sign)simonsfoundation.org | Twitter
     * Michael Moyer
       Deputy Editor
       mmoyer(replace this with the @ sign)simonsfoundation.org | Twitter
     * Emily Singer
       Senior Writer/Editor
       esinger(replace this with the @ sign)simonsfoundation.org | Twitter
     * Natalie Wolchover
       Writer
       nwolchover(replace this with the @ sign)simonsfoundation.org |
       Twitter
     * Olena Shmahalo
       Visual Designer/Producer
       oshmahalo(replace this with the @ sign)simonsfoundation.org

Contributing Writers

     * Carrie Arnold
       Veronique Greenwood
       Kat McGowan
       Wynne Perry
       Carl Zimmer
     * Peter Byrne
       Erica Klarreich
       Jennifer Ouellette
       Tom Siegfried

Advisory Board

     * Sean Carroll
       Benedict H. Gross
       Howard Schneider
       Michael S. Turner
     * Laura Chang
       Vincent Racaniello
       Steven Strogatz
       Leslie B. Vosshall

Syndication

   The Guardian | National Geographic
   Scientific American | Wired

Contact

   Quanta(replace this with the @ sign)SimonsFoundation.org

Stay Connected & Informed

   facebook twitter feed

Sign Up for the Simons Foundation newsletter

   Thank you! You will receive one confirmation email per selection. You
   will receive a confirmation email.
   Email: Email_______________ Subscribe

   Back to top

   Visit Simonsfoundation.org

     * About Simons Foundation
     * Mathematics & Physical Sciences
     * Life Sciences
     * Autism Research
     * Education & Outreach
     * Funding
     * Contact Us
