    #alternate

   (BUTTON) ____________________
     * Sign In
     * Username
     * PostTV
     * Politics
     * Opinions
     * Local
     * Sports
     * National
     * World
     * Business
     * Tech
     * Lifestyle
     * Entertainment
     * Classifieds
     * Jobs
     * Real Estate
     * Events
     * Rentals
     * Cars
     * WP BrandConnect
     * Subscribe

   washingtonpost.com © 1996-2014 The Washington Post

   Help and Contact Us

   Terms of Service

   Privacy Policy

   Submissions and Discussion Policy

   RSS Terms of Service

   Ad Choices

   Sections
   The Washington Post
   Artificial sweeteners could cause spikes in blood sugar
   ____________________ (BUTTON)
   Sign In
   Username
   Subscribe
   Health & Science

Artificial sweeteners could cause spikes in blood sugar

   Share on Facebook
   Share on Twitter
   Share on Google Plus
   Share via Email
   More Options
   Share on LinkedIn
   Share on Pinterest
   Share on Tumblr
   Resize Text
   Print Article
   Comments
   [iStock_000016293067Large.jpg?uuid=8vnnfD6ZEeSw6oFBcDu_bw]
   Researchers say consumption of artificial sweeteners such as saccharin,
   sucralose and aspartame led to increased risk of glucose intolerance, a
   condition linked to diabetes. Sweet ‘N Low contains saccharin. Equal
   original contains aspartame. Splenda contains sucralose. (iStockPhoto)
   By Brady Dennis September 17 Follow @brady_dennis

   Artificial sweeteners might be triggering higher blood-sugar levels in
   some people and contributing to the problems they were designed to
   combat, such as diabetes and obesity, according to new findings
   published Wednesday in the journal Nature.

   Although the precise reasons behind the blood-sugar changes remain
   uncertain, researchers suspect that artificial sweeteners could be
   disrupting the microbiome, a vast and enigmatic ecosystem of bacteria
   in our guts.

   In a series of experiments, researchers found that several of the most
   widely used types of non-calorie sweeteners in food and drinks —
   saccharin, sucralose and aspartame — caused mice to experience
   increased risk of glucose intolerance, a condition that can lead to
   diabetes.

   “We are talking about very dramatic increases,” said one of the study’s
   co-authors, Eran Segal, a computational biologist at the Weizmann
   Institute of Science in Israel.

   The same scientists also monitored what happened to seven human
   volunteers who did not typically use artificial sweeteners but were
   given regular doses of saccharin over the course of a week. Four
   developed significant glucose intolerance. Separately, the researchers
   analyzed nearly 400 people and found that the gut bacteria of those who
   used artificial sweeteners were noticeably different from people who
   did not.
   [w-ArtificialSweeteners_promo.jpg?uuid=CMJL8D5_EeSkMLgqPme3Yg] View
   Graphic
   Using some artificial sweeteners might cause glucose intolerance.

   “This huge and poorly understood microbial world, which resides in each
   and every one of us starting from birth, has been shown to play a
   fundamental role in many aspects of our physiology, as well as in [our]
   susceptibility to common human diseases,” said Eran Elinav, another of
   the study’s co-authors and an immunologist at the Weizmann Institute.

   Wednesday’s findings add an intriguing new dimension to the
   long-running, contentious debate over the potential health benefits and
   risks of artificial sweeteners, which are among the most common food
   additives and are consumed by hundreds of millions of people around the
   globe.

   While some past studies have found that the products pose no health
   risks and effectively help people cut calories and sugar intake, other
   research has suggested that certain artificial sweeteners might
   actually contribute to obesity and other problems, including cancer.

   Segal and Elinav insisted that their findings are preliminary and
   shouldn’t be taken as a recommendation on whether people should
   reconsider using artificial sweeteners.

   “We do not view that as our role,” Segal said. “Rather, as scientists,
   we simply point to the immense body of experiments that we carried out
   in both humans and in mice. . . . This study and these results should
   prompt additional debates and study into what is currently a massive
   use of artificial sweeteners.”

   Elinav added: “This issue is far from being resolved.”

   Lisa Lefferts, a senior scientist at the nonprofit Center for Science
   in the Public Interest, agreed. She praised the rigor behind
   Wednesday’s study and the “very provocative results” it produced, but
   she said the findings don’t negate past studies showing that people are
   more likely to gain weight when drinking sugar-sweetened beverages than
   when using artificial sweeteners.

   Rather, she said, the various ways the scientists measured the effect
   of saccharin on the gut microbiota suggest a definite, if unresolved,
   link.

   “We have more confidence now that there really is something going on,
   at least in animals,” Lefferts said. “What does that mean over the long
   term for the population? We still don’t have that answer.”

   In addition, Lefferts and the study’s authors said people shouldn’t see
   the findings as a suggestion that sugar-sweetened drinks are somehow
   preferable to artificial sweeteners.

   “We must stress, by no means are we saying that sugary drinks are
   healthy and that sugary drinks should be brought back as a healthy part
   of our nutrition,” Elinav said

   The Food and Drug Administration has approved six different types of
   sugar substitutes, or “high-intensity” sweeteners, with the most recent
   coming this year. The three types included in Wednesday’s study
   involving mice — saccharin, sucralose and aspartame — are more commonly
   known by the popular brand names Sweet n’ Low, Splenda and Equal,
   respectively. However, the researchers relied primarily on saccharin in
   their mouse and human experiments.

   Perhaps no sweetener has proven more controversial than saccharin,
   which was discovered not long after the end of the Civil War. In 1977,
   the FDA tried to ban saccharin because of safety concerns after studies
   showing that rats had developed bladder cancer after receiving high
   doses of the chemical sweetener.

   Congress blocked that effort, instead passing legislation that required
   a warning label on products containing saccharin. In 2001, federal
   legislation removed the requirement for a warning label altogether.

   The American Medical Association and the American Diabetes Association
   have cautiously backed the use of non-caloric sugar substitutes as a
   way to fight obesity and diabetes, saying that the products can be part
   of a healthy diet as long as the calories saved aren’t replaced by
   consuming more food over the course of a day.

   More from The Washington Post:

   Food labels get first makeover in 20 years. New emphasis on sugar

   Is sugar a toxin? Experts debate the role of fructose in our obesity
   epidemic

   Study: Sugar even at moderate levels is toxic for mice health,
   reproduction

   Even hummingbirds want the sweet stuff. If they don’t get it, they get
   mad
   [bradydennis.JPG&h=90&w=90]
   Brady Dennis is a national reporter for The Washington Post, focusing
   on food and drug issues.
     *   Share on FacebookShare
     *   Share on TwitterTweet

   SECTION: {section=national, subsection=health-science}!!!
   INITIAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!!
   UGC FROM ARTICLE: {allow_comments=true, allow_photos=false,
   allow_videos=false, comments_period=14, comments_source=washpost.com,
   default_sort=, default_tab=, display_comments=true,
   is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}!!!
   FINAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!
   customFields- published 1410973320/1410973320000/1410973320 tracking:
   {authors=Brady Dennis, content_category=Health-Environment-Science,
   in_url_headline=study-suggests-sweeteners-could-contribute-to-obesity-a
   nd-diabetes, section={section=national, subsection=health-science},
   show_ads=true, show_comments=true, ugc={allow_comments=true,
   allow_photos=false, allow_videos=false, comments_period=14,
   comments_source=washpost.com, default_sort=, default_tab=,
   display_comments=true, is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}}
   allow_comments: true published_date:Sep 17, 2014 5:02:00 PM close date:
   Oct 1, 2014 5:02:00 PM
   Comments
   SECTION: {section=national, subsection=health-science}!!!
   INITIAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!!
   UGC FROM ARTICLE: {allow_comments=true, allow_photos=false,
   allow_videos=false, comments_period=14, comments_source=washpost.com,
   default_sort=, default_tab=, display_comments=true,
   is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}!!!
   FINAL commentConfig: {includereply=true,
   canvas_permalink_id=washpost.com/8bvh5zpd9k, allow_comments=true,
   commentmaxlength=2000, includeshare=true, display_comments=true,
   canvas_permalink_app_instance=m6yzjj840m, display_more=true,
   moderationrequired=false, includefeaturenotification=true,
   defaultsort=reverseChronological,
   canvas_allcomments_id=washpost.com/km4ey0dajm, comments_period=14,
   includevoteofftopic=false, allow_videos=false, includesorts=true,
   markerdisplay=post_commenter:Post Commenter|staff:Post
   Writer|top_commenter:Post
   Forum|top_local:Washingtologist|top_sports:SuperFan|fact_checker:Fact
   Checker|post_recommended:Post Recommended|world_watcher:World
   Watcher|cultuer_connoisseur:Culture Connoisseur|weather_watcher:Capital
   Weather Watcher|post_contributor:Post Contributor,
   childrenitemsperpage=3, includeheader=true,
   includeverifiedcommenters=true, defaulttab=all, includerecommend=true,
   includereport=true, maxitemstop=3, source=washpost.com,
   allow_photos=false, maxitems=15, display_ugc_photos=false,
   includepause=true, canvas_allcomments_app_instance=6634zxcgfd,
   includepermalink=false}!!
   customFields- published 1410973320/1410973320000/1410973320 tracking:
   {authors=Brady Dennis, content_category=Health-Environment-Science,
   in_url_headline=study-suggests-sweeteners-could-contribute-to-obesity-a
   nd-diabetes, section={section=national, subsection=health-science},
   show_ads=true, show_comments=true, ugc={allow_comments=true,
   allow_photos=false, allow_videos=false, comments_period=14,
   comments_source=washpost.com, default_sort=, default_tab=,
   display_comments=true, is_ugc_gallery=false, max_items_to_display=15,
   max_items_to_display_top=3, moderation_required=false, stream_id=}}
   allow_comments: true published_date:Sep 17, 2014 5:02:00 PM close date:
   Oct 1, 2014 5:02:00 PM

   SuperFan Badge

   SuperFan badge holders consistently post smart, timely comments about
   Washington area sports and teams.

   More about badges | Request a badge

   Culture Connoisseur Badge

   Culture Connoisseurs consistently offer thought-provoking, timely
   comments on the arts, lifestyle and entertainment.

   More about badges | Request a badge

   Fact Checker Badge

   Fact Checkers contribute questions, information and facts to The Fact
   Checker.

   More about badges | Request a badge

   Washingtologist Badge

   Washingtologists consistently post thought-provoking, timely comments
   on events, communities, and trends in the Washington area.

   More about badges | Request a badge

   Post Writer Badge

   This commenter is a Washington Post editor, reporter or producer.

   Post Forum Badge

   Post Forum members consistently offer thought-provoking, timely
   comments on politics, national and international affairs.

   More about badges | Request a badge

   Weather Watcher Badge

   Weather Watchers consistently offer thought-provoking, timely comments
   on climates and forecasts.

   More about badges | Request a badge

   World Watcher Badge

   World Watchers consistently offer thought-provoking, timely comments on
   international affairs.

   More about badges | Request a badge

   Post Contributor Badge

   This commenter is a Washington Post contributor. Post contributors
   aren’t staff, but may write articles or columns. In some cases,
   contributors are sources or experts quoted in a story.

   More about badges | Request a badge

   Post Recommended

   Washington Post reporters or editors recommend this comment or reader
   post.

   You must be logged in to report a comment.
   Sign in here

   You must be logged in to recommend a comment.
   Sign in here

   Comments our editors find particularly useful or relevant are displayed
   in Top Comments, as are comments by users with these badges: . Replies
   to those posts appear here, as well as posts by staff writers.

   All comments are posted in the All Comments tab.
   More about badges
   Get a badge

   To pause and restart automatic updates, click "Live" or "Paused". If
   paused, you'll be notified of the number of additional comments that
   have come in.
   Comments our editors find particularly useful or relevant are displayed
   in Top Comments, as are comments by users with these badges: . Replies
   to those posts appear here, as well as posts by staff writers.
     * Spam
     * Offensive
     * Disagree
     * Off-Topic

     *
          + Facebook
          + Twitter
          + Reddit
          + StumbleUpon
          + Digg
          + Delicious

   Most Read National
     * 1
       [imrs1.jpg]
       Scientists confess to sneaking Bob Dylan lyrics into their work for
       the past 17 years
     * 2
       Watching a tattoo needle in slow motion reveals the physics of
       getting inked
     * 3
       [20140927_MICHAELBROWN_EDIT4.jpg]
       Michael Brown's mother: 'They robbed my son of his future'
     * 4
       Neil deGrasse Tyson admits he botched Bush quote
     * 5
       Arrest made in Indiana State University shooting

   The Most Popular All Over
     * [400x225&h=60&w=80]
       The Baltimore Sun
       Unseld steps into spotlight to announce Wizards preseason game
     * [10620961236_5bd233aa5d_z.jpg?itok=G5e9o8Wd&h=60&w=80]
       PRI
       China says no to a shipment of US corn contaminated with GMOs — and
       surprising lawsuits follow
     * [farmersmarketBB3.jpg&h=60&w=80]
       WNYC - New York Public Radio
       ABCs: Apples; Bans; Cell Phones
     * [300x.jpg&h=60&w=80]
       The Dodo
       Brilliant German Shepherd Jailbreaks His Little Friend From Her
       Crate
     * [20140925__jeffoc-students-protests-columbine-high~p1_200.jpg&h=60&
       w=80]
       The Denver Post
       Massive protest near Columbine High School marks fourth day of
       Jeffco school walk outs
     * [Khorasan_Group-0f06e.jpg&h=60&w=80]
       The Washington Post
       FBI director: U.S. has identified the killer of two beheaded
       American journalists
     * [523f010d5177d.preview-300.jpg&h=60&w=80]
       St. Louis Post-Dispatch
       Starter cut-off devices keep car payments coming
     * [3036090-poster-p-1-190-bourdain-we-wil-have-what-he-is-having.jpg&
       h=60&w=80]
       Fast Company
       Anthony Bourdain Has Become The Future Of Cable News, And He
       Couldn't Care Less
     * [140924_bb_KThompson-montage.jpg.CROP.rectangle-large.jpg&h=60&w=80
       ]
       Slate
       Why Saturday Night Live Writers Lean on Kenan Thompson
     * [lead_large.jpg?ncest2&h=60&w=80]
       The Atlantic
       Murder in a Time Before Google
     * [b4s_fakebreast092414_13919185.jpg&h=60&w=80]
       Tampa Bay Times
       Tampa woman with three breasts? Suitcase find points to false front
     * [lowe-jpgStanley-Lowe.jpg&h=60&w=80]
       The Toledo Blade
       Ex-Pathway exec investigated
     * [20140924_brk_hal01.jpg&h=60&w=80]
       Honolulu Star-Advertiser
       Prosecutor: Hawaii prison gang 'kings of castle'
     * [phil_hartman-300x200.jpg&h=60&w=80]
       Salon
       Phil Hartman's final night: The tragic death of a "Saturday Night
       Live" genius

   [themost-290x60.png]
     * washingtonpost.com
     * © 1996-2014 The Washington Post
     *
     * Help and Contact Us
     * Terms of Service
     * Privacy Policy
     * Submissions and Discussion Policy
     * RSS Terms of Service
     * Ad Choices

   [p?c1=2&c2=3005617&cv=2.0&cj=1]
