   #The Long Now Blog RSS Feed Blog of the Long Now » Brian Eno’s Selected
   Books for the Manual for Civilization Comments Feed Colonel Matthew
   Bogdanos Seminar Media Mariana Mazzucato Seminar Tickets

     * Home
     * About
          + About
          + Community
          + Support
          + Essays
          + Press
          + Jobs
          + Store
          + Contact
     * Projects
          + The Interval
          + Seminars
          + Special Events
          + 10,000 Year Clock
          + Nevada
          + The Rosetta Project
          + PanLex
          + Long Bets
          + Revive & Restore
          + Long Server
          +
              _________________________________________________________

          + View all projects...
     * Blog
     * Seminars
          + Seminar Home page
          + Next Seminar
          + Seminar List View
          + Audio Podcast
          + Special Events
     * Membership
          + Become a Member
          +
              _________________________________________________________

          + Community
          + Dashboard
          + Newsletters
          + Settings
     * Donate
     * People
          + Board Members
          + Staff
          + Associates
     * Contact

Brian Eno’s Selected Books for the Manual for Civilization

   Posted on Friday, February 28th, 02014 by Alexander Rose - Twitter:
   @zander
   link Categories: Long Now salon (Interval), Manual for Civilization,
   The Interval   chat 0 Comments
   Brian Eno - Manual For Civilization
   Brian Eno visited San Francisco to see the site where the Manual for
   Civilization shelves will be
   Photo by Alexander Rose


   Twenty books suggested by Long Now’s Founding Board Member Brian Eno
   form the first in a series of reports on additions to our Manual for
   Civilization collection. This library will eventually include 3,500
   books you would most want to sustain or rebuild civilization. The
   Manual needs your help to get built!  Please make a donation so we can
   purchase these books and the shelves they go on.  The Manual will be a
   central feature of our new space that opens later this year. Here are
   Brian Eno’s recommendations:
     * Seeing Like a State by James C Scott
     * The Mind in the Cave: Consciousness and the Origins of Art by David
       Lewis-Williams
     * Crowds and Power by Elias Canetti
     * The Wheels of Commerce by Fernand Braudel
     * Keeping Together in Time by William McNeill
     * Dancing in the Streets by Barbara Ehrenreich
     * Roll Jordan Roll by Eugene Genovese
     * A Pattern Language by Christopher Alexander et al
     * The Face of Battle by John Keegan
     * A History of the World in 100 Objects by  Neil MacGregor
     * Contingency, Irony and Solidarity by Richard Rorty
     * The Notebooks by Leonardo da Vinci
     * The Confidence Trap by David Runciman
     * The Discoverers by Daniel Boorstein
     * Mother Nature: A History of Mothers, Infants, and Natural Selection
       by Sarah Hrdy
     * War and Peace by Leo Tolstoy
     * The Cambridge World History of Food (2-Volume Set) by Kenneth F.
       Kiple & Kriemhild Coneè Ornelas
     * The Illustrated Flora of Britain and Northern Europe by Marjorie
       Blamey & Christopher Grey Wilson
     * Printing and the Mind of Man by John Carter & Percy Muir
     * Peter the Great: His Life and World by Richard Massie

   We need your help to finish this library. There are only weeks left to
   finish our fund raising and we need to raise at least another $100,000.
   Please make a donation to support this project and get direct access to
   the book recommendation and voting engine for the Manual for
   Civilization.

   ManualGraphic

   Some of the other contributor lists we will be sharing soon include
   selections from Stewart Brand, Neal Stephenson, Violet Blue, Kevin
   Kelly, Danny Hillis, Megan and Rick Prelinger and many more.

   Once the Salon is open we hope to have events where people can argue a
   new book in OR out of the collection.  It will be a living collection
   that evolves over time.  The Internet Archive has generously agreed to
   serve as the digital backup repository of the collection so that anyone
   with internet access can “check out” the books, or use the list to help
   create their version of the archive.

   You can see more about this project on the original Manual for
   Civilization blog post.  Soon we will need to begin collecting the
   actual books for our shelves, and will be asking for book donations
   from our edited list.  We hope that we can get many of these books from
   our community so that we don’t have to purchase too many new books.

                       ManualForCivilizationLogoSource




     * Evan Machugh
       Origin of The Species? I’d also suggest ” The Better Angels of our
       Nature” by Steven Pinker.
     * Stuart Sovatsky
       Advanced Spiritual Intimacy (Inner Traditions 2014) Stuart Sovatsky
     * Jeremy Si
       The Law by Bastiat
     * Jeremy Si
       On the Shoulders of Giants by Stephen Hawking. ” World-renowned
       physicist and bestselling author Stephen Hawking presents a
       revolutionary look at the momentous discoveries that changed our
       perception of the world with this first-ever compilation of seven
       classic works on physics and astronomy. His choice of landmark
       writings by some of the world’s great thinkers traces the brilliant
       evolution of modern science and shows how each figure built upon
       the genius of his predecessors. On the Shoulders of Giants
       includes, in their entirety, On the Revolution of Heavenly Spheres
       by Nicolaus Copernicus; Principia by Sir Isaac Newton; The
       Principle of Relativity by Albert Einstein; Dialogues Concerning
       Two Sciences by Galileo Galilei with Alfonso De Salvio; plus
       Mystery of the Cosmos, Harmony of the World, and Rudolphine Tables
       by Johannes Kepler. It also includes five critical essays and a
       biography of each featured physicist, written by Hawking himself.”
       Amazon
     * handymatt
       What, no Pocket Ref?
     * Geertje Geertsma
       Anne Frank … to learn about love and compassion
     * Wpmarcy
       Animal Farm, for every government to come and the people who will
       live under them.
     * Alan Davies
       Richard Tarnas – Cosmos & Psyche
     * Marilia
       Origins of Totalitarianism by Hannah Arendt
     * Nelis Willers
       Meaning of life, Victor Franklin. Written during WWII in a Nazi
       concentration camp. Frankl shows us how to find significant meaning
       in the darkest of circumstances.
     * Riana Willers
       Little Prince by Antoine de Saint-Exupéry which teaches us about
       love, friendship and responsibility.
     * CRBoiler
       Things Fall Apart by Chinua Achebe to learn one needs to consider
       risks of unintended consequences before acting.
     * jojothepojo
       Maps of consciousness by Ralph Metzner
     * lslapiko
       The Souls of Black Folk by W.E.B. DuBois
     * Emmanuele Padilla
       Book of Five Rings by Miyamoto Musashi
     * https://twitter.com/Nietthuisgever Niet-thuisgever
       Ideas about long-term thinking as a manual for civilization? Brian
       Eno couldn’t have chosen better: Elias Canetti “Crowds and Power”.
     * https://twitter.com/Nietthuisgever Niet-thuisgever
       Ideas about long-term thinking as a manual for civilization? Brian
       Eno couldn’t have chosen better: Elias Canetti “Crowds and Power”.
     * Kent Durvin
       It was traditionally considered wrong because you can’t do it in
       Latin. There is no good reason to prohibit it in English.
     * Nick W
       The Better Angels of our Nature is probably the book I recommend
       the most to anyone. I picked it up initially because the premise
       seemed very interesting, but as I kept reading, I was astonished at
       what I learned. Not only does it exhaustively argue its point so
       well that only the most hardened cynic would try to disagree, it
       culminates in what almost seems like a “how to guide” for humanity.
       Couldn’t think of a more relevant book for a collection with this
       goal. If it doesn’t make it into the collection, I would be
       surprised and disappointed.
     * concerned Buddhist
       Bhikkhu Bodhi’s translations of the Majjhima, Samyutta & Anguttara
       Nikayas, Maurice Walshe’s translation of the Digha Nikaya, all of
       the Pali Canon, the collections of the spoken word of the
       historical Buddha.
       This grand collection can teach man everything there is to know
       about morality, meditation and how to live a life free of inner
       turmoil.
     __________________________________________________________________

   navigateleft Previous Article
   Colonel Matthew Bogdanos Seminar Media

   Next Article navigateright
   Mariana Mazzucato Seminar Tickets

Blog of the Long Now

   Ideas about Long-term Thinking
   ____________________
               

   The Long Now Foundation was established to creatively foster long-term
   thinking and responsibility in the framework of the next 10,000 years.
   More navigateright
   Become a Member

Categories

     * Announcements
     * Clock of the Long Now
     * Digital Dark Age
     * Events
     * Futures
     * Long Bets
     * Long News
     * Long Now salon (Interval)
     * Long Shorts
     * Long Term Art
     * Long Term Science
     * Long Term Thinking
     * Long-term Quotes
     * Manual for Civilization
     * Millennial Precedent
     * PanLex
     * Revive & Restore
     * Rosetta
     * Seminars
     * Technology
     * The Big Here
     * The Interval

Archives

     * 2014
     * 2013
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * 2007
     * 2006
     * 2005
     * 2004
     * 2003
     * 2002
     * 1999
     * 1996

   The Long Now Foundation  •  Fostering Long-term Responsibility  •  est.
   01996      Top of Page
