   #Code for America » Feed Code for America » Comments Feed Clara
   Gonzalez Sueyro: Why I’m Coding for America Guest Post from Accela |
   Looking for the Next Great Civic Startup

     * Blog
     * Library
     * ____________________ (www.codeforamerica.org) Search

     * Home
     * Blog

Blogging For America

   [logo.png]

   Menu
     * About
     * Governments
     * Citizens
     * Companies
     * Our Work
     * Donate

   Jennifer
   Pahlka
   @pahlkadot

   Jennifer Pahlka is the founder and executive director of Code for
   America. She recently served as the US Deputy Chief Technology Officer
   in the White House Office of Science and Technology Policy. She is
   known for her TED talk, Coding a Better Government, and is the
   recipient of several awards, including the Oxford Internet Institute's
   Internet and Society Award, MIT’s Kevin Lynch Award, and National
   Democratic Institute’s Democracy Award. She spent eight years at CMP
   Media where she ran the Game Developers Conference and related
   properties. Previously, she ran the Web 2.0 and Gov 2.0 events
   for TechWeb, in conjunction with O'Reilly Media. Jennifer’s early
   career was spent in the non-profit sector. She is a graduate of Yale
   University and lives in Oakland, Calif. with her daughter, fiance, and
   seven chickens.
   Filed Under
     * News

Jon Stewart, you’re getting your wish.

   June 28, 2014 by Jennifer PahlkaShare
   Tweet
   Share

   In one of the many (justified) rants that Jon Stewart has treated us to
   on The Daily Show, he asked the question:

   If we could take the same urgency, enthusiasm, and clarity of vision
   you need to get elected to government and apply those to governing,
   could we fix some things? Yes, we [expletive deleted] can!

   In a news item Stewart and most others around the country probably
   missed this week, Jascha Franklin-Hodge was appointed the Chief
   Information Officer of the City of Boston. Jascha is one of the first
   people I talked to about my idea for Code for America, back at FooCamp
   in 2009. More importantly, Jascha is one of the co-founders of Blue
   State Digital, the platform often given credit for getting Barack Obama
   elected in 2008; one of his former colleagues, Macon Phillips, started
   the Office of Digital Strategy in the Obama White House and brought a
   breath of fresh air to how the President communicated with the public.
   Score one more for the Stewart agenda.

   I’m thrilled for Bostonians, and for the community of CIOs around the
   country with whom I hope Jascha will collaborate and share ideas. But
   the reason I’m writing about this is actually this: I would like
   everyone reading this post who knows an entrepreneur like Jascha
   (wicked smart, kind, level-headed, and deeply committed to making the
   world a better place) to send a link to this post to that entrepreneur
   with the subject line, “You should do this.”

   Brett Goldstein became a cop, and then the Chief Data Officer and CIO
   of Chicago, after a career at OpenTable, because he wanted to serve his
   country after 9/11. Rachel Haot founded GroundTruth, and is now Deputy
   Secretary of Technology for the State of New York after pioneering the
   role of Chief Digital Officer of New York City. Mark Schwartz now
   serves as CIO of US Citizenship and Immigration in the Department of
   Homeland Security; he was previously CEO of Auctiva. And of course,
   Todd Park leads digital strategy for the US government after founding
   Athena Health and Castlight. Many public servants have backgrounds in
   the private sector.

   I am not one of those people who believes the private sector (or its
   people) can or will save the public sector (or its people). I’ve met
   hundreds of brilliant, dedicated public servants (CIO and others) in
   whose hands I would gladly put my city’s technology and citizen
   services, and I’ve met several (not hundreds, thank goodness) of
   entrepreneurs whom I would not want anywhere near a city’s
   infrastructure. And I’m as excited about many of my colleagues from the
   White House moving into startups (they will kick ass!) as I am about
   Jascha’s move. But the kind of move Jascha made is not common enough,
   and needs to be the norm.

   There’s a shortage of talent in technology. I got an
   email yesterday offering me an all expenses-paid trip to the Four
   Seasons in Hawaii if any engineer I referred was hired at a particular
   start up. (That’s a gift no public servant could probably accept, by
   the way.) That seemed like a great offer, until I realized that other
   startups are offering $10,000 cash for the same. I know a lot of
   engineers, and while I’m slightly tempted, there’s something even more
   valuable to me that I have in mind for the talented engineers I know:
   fixing our country.

   Mikey Dickerson, of healthcare.gov rescue fame, has been saying lately
   that there are at least 12 startups right now working on disrupting
   laundry. Not how laundry is done, just how to make it easier for those
   of us who still have a few annoying chores in our lives now that
   problems like food and transportation have been solved. With all due
   respect for the intellects that will be brought to bear on the laundry
   challenge, I’d pay $50K to have those people work on making government
   work for the people, by the people. Oh wait, we already do that.

   But getting back to Jascha, it’s not that there aren’t amazing people
   in the public sector doing great things. Boston has had no shortage of
   amazing public servants working on technology and innovation; at the
   start of the CfA Fellowship in 2010, we had the pleasure and privilege
   of working with Bill Oates, who left the CIO post some time ago to take
   his talents to the state of Massachusetts, and his colleagues in the
   Mayor’s Office of New Urban Mechanics, Nigel Jacob and Chris Osgood.
   After that fellowship year was over, Michael Evans, who had served as a
   fellow with the City of Philadelphia, took his remarkable skills to
   Boston to join Nigel and Chris, and the results speak for themselves.
   And now Jascha will take the baton from this remarkable group. This is
   a great welcome back present to me and the civic tech community.

   The problem is that the same talent shortage that makes startups go to
   such lengths to recruit affects the public sector even more seriously.
   And while we target mostly mid-career developers and designers through
   the Code for America Fellowship, entrepreneurs who’ve had recent exits
   are in the perfect position to take leadership roles in city, state,
   and federal government, and to take seriously the business of making
   government work the way we need it to. Entrepreneurs, you have your
   pick of what to do next. Choose wisely.

   Update: Twitter this morning informs me that the San Francisco Unified
   School District is looking for a Chief Technology Officer. For more San
   Francisco jobs, follow @civicjobsf.

   Questions? Comments? Hit us up at @codeforamerica
   ← Back To All Articles
   ____________________
     * Home
     * About
          + Fellowship
          + Brigade
          + Civic Startups
          + Peer Network
          + International
          + Board
          + Team
          + Supporters
          + Press
          + Jobs
          + Contact
     * Governments
          + Atlanta, GA
          + Charlotte, NC
          + Chattanooga, TN
          + Denver, CO
          + Lexington, KY
          + Long Beach, CA
          + Mesa, AZ
          + Rhode Island
          + San Antonio, TX
          + San Juan, PR
          + Alumni Partners
          + Peer Network
          + Data Standards
     * Citizens
          + Our Geeks
          + Our Code
          + Our Startups
          + Events
          + Civic Tech Issue Finder
     * Companies
          + Our Companies
          + Newsletter
          + Incubator FAQ
          + Accelerator FAQ
          + Apply
     * Our Work
          + Local Service Apps
          + Citizen Engagement Apps
          + Free Apps
          + Paid Apps
          + Initiatives
          + Data Formats
     * Donate
          + Supporters
          + Donate Now
     * Social
          + Facebook
          + Twitter
          + YouTube
          + GitHub
          + Tumblr
          + Flickr
          + Vimeo
          + RSS

   [logo-inversed.png] Code for America Labs, Inc is a non-partisan,
   non-political 501(c)(3) organization. EIN number 27-1067272. Content is
   licensed through Creative Commons.
   Provide website feedback on GitHub or to info@codeforamerica.org.
