SXSW PanelPicker

Create and submit and idea for a panel

     * Sign in
     *

   Search, Filter and Vote
     * Search/Vote
     * About
     * FAQ
     * Help

   Voting period for this idea type has passed

Revamp Traditional Lectures with Interactive Tools

   Yawn! There's little that can bore students more than the traditional
   lecture. When instructors don't take the simple steps to help them
   interact with the content, why should they care? If you're looking to
   wake up your students and infuse your classroom with more engagement,
   it's time to tap a new generation of classroom tools driven by
   assessment and mastery. Founders from edtech companies will offer tips
   on choosing tools. Plus, you'll get the learner perspective from a
   student survivor!

Additional Supporting Materials

   http://cl.ly/image/2z0U1q1I0x05

Questions Answered

    1. Understand how edtech tools can transform a passive lecture
       experience into a setting similar to smaller, interactive
       classrooms.
    2. Understand how technology can make formative assessment a
       fundamental part of large classroom settings, not just small ones.
    3. Understand what students are looking for in classroom engagement
       tools, and how the student experience is changing.

Speakers

     * Ariel Diaz Boundless
     * Mike Silagadze Top Hat
     * Arjun Balaji Northeastern University
     * Dian Schaffhauser T.H.E. Journal and Campus Technology

Organizer

   Jessica Owen Boundless
     __________________________________________________________________

Add Comments

   Please enable JavaScript to view the comments powered by Disqus .
   comments powered by Disqus
     __________________________________________________________________

   Show me another

SXSWedu 2015
     __________________________________________________________________

   Show me another
     __________________________________________________________________

   Tags: lecture, education technology, classroom technology

Meta:

   Event -
          EDU

   Category -
          Panel Discussion

   Theme -
          Instructional Strategies & Best Practices

   Level -
          Basic Understanding
     __________________________________________________________________

Share this idea

   All SXSW art and text on this website are copyrighted. © 2011-2014
   SXSW, LLC.
   Privacy Policy  |  Terms of Use
     * Search/Vote
     * About
     * FAQ
     * Help
