   #Search MIT Technology Review

     * Global Edition
     * Insider
     * Magazine
     * Business Reports
     * Lists
     * Events
     * More
          + About
          + Newsletters
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum

     * Connect

Select your localized edition:

   Close ×
     * English
     * Español
     * Deutsch
     * Italiano
     * Português
     * 中文

Filter by:

     * (*) News and Analysis
     * ( ) Magazine
     * ( ) List: Innovators Under 35
     * ( ) Conferences and Events

     * Argentina
     * Brasil
     * Colombia
     * Deutschland

     * Italia
     * México
     * Portugal
     * España

     * United States
     * Uruguay
     * 中国大陆

More Ways to Connect

   Discover one of our 28 local entrepreneurial communities »

   Be the first to know as we launch in new countries and markets around
   the globe.

   Interested in bringing MIT Technology Review to your local market?
   Search Search________________________
   Search
   Log In / Join
     * New
     * Popular
     * Login / Join

MIT Technology Review MIT Technology Review - logo

   Home News & Analysis ▾
     * Features
     * Views
     * Multimedia
     * Discussions
     * Topics

     * Popular:
     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

   cover of latest MIT Technology Review magazine issue Subscribe

     * Home
          + Home
          + Biomedicine
          + Business
          + Computing
          + Energy
          + Materials
          + Mobile
       Top Stories

News

Google’s Management Tips

Brian Bergstein
       0
          +

New Nuclear Fuel Could Boost Old Reactors
         David Talbot
          +

A Cheaper Way to Store Solar
         Kevin Bullis
          +

BitTorrent Adds a Paywall for Music
         Tom Simonite
          + See More Top Stories
     * Menu
          + News & Analysis
          + Magazine
          + Lists
          + Events
          + About
          + More
          + Features
          + Views
          + Multimedia
          + Discussions
          + Topics
          + Popular:
          + Storing Sunlight
          + Rat Control
          + Google’s Balloon Shot
          + Smarter Watson
          + Quantum Computing Questions
          + Gene Sequencing Soars
          + Printed Kidneys
       cover of latest MIT Technology Review magazine issue Subscribe
          + Current Issue
          + Past Issues
          + MIT News Magazine
          + International Editions
          + Business Reports
          + Special Publications
          + Subscriptions »
          + Smartest Companies
          + Innovators Under 35
          + Breakthrough Technologies
          + Nominations »
          + Upcoming Events
          + Partner Events
          + Emtech MIT
          + MIT Enterprise Forum
          + Our Team
          + Join Us
          + Press Room
          + Awards
          + Advertise
          + Permissions
          + Contact Us
          + Customer Support »
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum
     * Insider
     * Connect

     * The Latest
     * Popular
     * Most Shared
     * My Profile

   Unsupported browser: Your browser does not meet modern web standards.
   See how it scores »

     * Comments
     * Email
     * Service
     * Service
     * More Share
     * Print

Tesla Motors’ Over-the-Air Repairs Are the Way Forward

View

     * 7 comments

Kevin Bullis

January 14, 2014

Tesla Motors’ Over-the-Air Repairs Are the Way Forward

   Tesla and GM have both issued fire-related recalls, but Tesla’s fix
   doesn’t require owners to bring their cars in.

   Tesla Motors is using over-the-air software updates to quickly fix the
   sort of problems that often arise when bringing a new car to market.
   This forward-looking approach is an important part of the company’s
   success (see “How Tesla is Driving Electric Car Innovation”).

   Today the National Highway Safety Administration officially published
   two recall announcements, one from Tesla Motors and one from GM. Both
   are related to problems that could cause fires. In the case of GM,
   trucks left idling can overheat and catch fire—eight fires have been
   reported. In Tesla’s case, an overheating charger plug seems have to
   have been the cause of a fire in a garage (it’s not clear if the
   problem had to do with miswiring of the wall charger, damage to the
   plug, or something else).

   Both problems can be addressed with software updates–in Tesla’s case,
   the software detects charging problems and decreases charging rates to
   avoid overheating (GM hasn’t provided details). Owners of 370,000
   Chevrolet Silverado and GMC Sierra pickups will need to find time to
   take their pickups to the dealer to get the software fixed. But because
   of its ability to send software updates to its vehicles wirelessly, the
   29,222 Tesla Model S electric cars that were affected have already been
   fixed. (While Tesla says the software update addresses the issue, it is
   also mailing Tesla owners new charger plugs that have a thermal fuse
   designed to provide another layer of safety.)

   Indeed, Tesla’s CEO Elon Musk argues the fix shouldn’t be called a
   recall at all, although it technically is from the point of view of
   NHTSA. On Twitter he noted that no vehicles were being “physically
   recalled” and said, in light of the over-the-air software updates, “The
   word ‘recall’ needs to be recalled.”

   This isn’t the first time Tesla has taken advantage of its software
   update system—it has become common for Tesla to send out updates that
   address problems and enhance performance. One of the most notable
   examples happened last year after three Tesla Model S’s caught fire in
   collisions, two with objects in the road. Tesla sent out an update that
   changed the suspension settings, giving the car more clearance at high
   speeds. No further fires have been reported, although it’s difficult to
   know if that’s because of the update (see “Are Electric Vehicles a Fire
   Hazard?” and “Why Electric Cars Could be Safer Than Gasoline Powered
   Ones”).

   Of course, some problems can’t be fixed with software updates. A
   manufacturing defect on 1,098 Model S’s last year required a trip to
   the service station to repair a problem with the way seats were
   attached.

   Expect over-the-air updates to become more common, although companies
   will need to work to make sure they can be done securely. Not only are
   they more convenient, they can also improve safety, since the updates
   can be made right away. And the updates may be critical for Tesla’s
   success, not just by giving the ability to respond to big issues like
   fires, but also to small ones—annoying but not dangerous software
   bugs—that could give the car a bad name if they persisted or were
   difficult for owners to have fixed. For example, Tesla was able to
   update the car’s estimates for how far it could go in cold weather (the
   use of a heater decreases battery range), avoiding a problem where the
   car underestimated how far it could go. In the future, software updates
   could make such predictions even more accurate by figuring in weather
   forecasts.

7 comments. Share your thoughts » 0 comments about this story. Start the
discussion »

   Tagged: Energy, Tesla Motors, Elon Musk, Model S, GM, electric
   vehicles, Chevrolet

   Reprints and Permissions | Send feedback to the editor
     * Related stories
     * You may have missed
     * More from this author

     *

New Nuclear Fuel Could Boost Reactors, But Also Safety Worries
       A new fuel rod design will be tested in a full-size reactor, but
       some worry it could bring fresh safety problems.
       Continue
       0

     *

Solar City and Tesla Hatch a Plan to Lower the Cost of Solar Power
       63
     *

Technology Stalled in 1970
       55
     *

Panasonic Agrees to Help Tesla Build Its Gigafactory
       33
     *

The Search For Extraterrestrial Civilizations' Waste Energy
       8

     *

U.N. Predicts New Global Population Boom
       33
     *

Construction Begins at a Carbon-Capture Plant, but Will It Ever Be Completed?
       23
     *

Surging Carbon Dioxide Shows Clean Tech Failure
       159
     *

China’s Shale Gas Bust
       9

     *

The New Chinese Factory
       Leading manufacturers in China combine the country’s historical
       labor advantages with expertise in automation, design, and...
       Continue
       1
     *

Making Innovation
       The hubs of advanced manufacturing will be the economic drivers of
       the future because innovation increasingly depends on...
       Continue
       5
     *

Three Questions with the CEO of D-Wave
       The CEO of quantum computing startup D-Wave says its machines are
       helping companies analyze Wall Street data and search for...
       Continue
       1
     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
       Controlled by software, paralyzed rats walk and climb stairs.
       Continue
       2
     * Francis de Souza, president of Illumina

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
       Record number of genomes being decoded, but cost of DNA sequencing
       might not fall much further, says Illumina president.
       Continue
       3
     *

EmTech: IBM Tries to Make Watson Smarter
       IBM executive says Watson could find success with commercial apps
       in wealth management, call centers, and medicine.
       Continue
       2

   Kevin Bullis Editor

   View Profile »

   Follow @KevinBullis
     * Google+
     * RSS

     *

A Promising Step Toward Round-the-Clock Solar Power
       0
     *

EmTech: 3-D Printing Complex Kidney Components
       1
     *

EmTech: A Hybrid Solution for Cheap Desalination
       5
     *

Solar City and Tesla Hatch a Plan to Lower the Cost of Solar Power
       63

     *

Turbocharging Photosynthesis to Feed the World
       11
     *

Motorized Pants to Help Soldiers and Stroke Victims
       2
     *

Gene-Silencing Drugs Finally Show Promise
       2
     *

Cheap, Scratch-Resistant Displays
       19
     * See all from this author

     * The Latest
     * Popular
     * Most Shared

     *

10 min ago

Don’t Ask Google’s Eric Schmidt How to Achieve “Work-Life Balance”
     *

10 min ago

Virginian Reactor Will Test an Output-Boosting Fuel Design
     *

1 day ago

Other Interesting arXiv Papers (Week ending September 27, 2014)
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

Innovation Series: The Connected Home
       Brought to you by
     *

2 days ago

Thom Yorke Album Sold Through BitTorrent in Attempt to Make File Sharers Pay
     *

3 days ago

Seven Stories You Shouldn’t Miss
(Week Ending September 27, 2014)
     *

3 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

3 days ago

Radio Interference Adds Gesture Recognition to Smartphones
     *

3 days ago

Recommended from Around the Web (Week Ending September 27, 2014)
     *

Revolution in Progress: The Networked Economy
       In partnership with SAP
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

3 days ago

Best Tweets from EmTech: Day 2
     *

3 days ago

Best Tweets from EmTech: Day 1
     *

Technology Insights - Portability vs. Privacy: Striking the Right Balance in
the Mobile Era
       Free download courtesy of Symantec
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

4 days ago

EmTech: Risks of Gene-Editing Drugs Need Study
     * See full archive

     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

5 days ago

EmTech: Google’s Astro Teller Says Its “Loon” Balloons Will Ring the Globe in
2015
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     *

3 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

1 month ago

35 Innovators Under 35 | 2014
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

1 week ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

1 week ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

6 days ago

Uber’s Driver Poach Shows Lack of Respect for Workers
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

5 days ago

EmTech: Three Questions with a “Meat Brewer”
     *

5 days ago

App Talko Hopes to Get You to Use Phone to Actually Talk
     * See full archive

     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

1 week ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

1 week ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

1 week ago

Solar City and Tesla Combine Manufacturing Plans
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

1 week ago

The Hidden World of Facebook "Like Farms"
     *

2 months ago

Forget the Shortest Route Across a City; New Algorithm Finds the Most
Beautiful
     *

1 month ago

35 Innovators Under 35 | 2014
     *

3 years ago

Astronomers Find First Evidence of Other Universes
     *

1 year ago

Innovators Under 35
     *

1 year ago

Given Tablets but No Teachers, Ethiopian Children Teach Themselves
     *

1 year ago

Astrobiologists Find Ancient Fossils in Fireball Fragments
     *

1 year ago

First Teleportation from One Macroscopic Object to Another
     *

1 year ago

Government Lab Reveals It Has Operated Quantum Internet for Over Two Years
     * See full archive

   Show comments »
   Conversation powered by Livefyre

New & Trending

     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

     * Google Execs Have Ideas on How to Run Your Business
     * New Nuclear Fuel Could Boost Reactors, But Also Safety Worries
     * Other Interesting arXiv Papers (Week ending September 27, 2014)
     * First Quantum Logic Operation For An Integrated Photonic Chip

From the Archives

     * The Art of the Possible
    8 years ago
     * The Hottest VC on the Planet
    10 years ago
     * Nanotech Goes to Work
    13 years ago
     * Computing's Johnny Appleseed
    14 years ago

     * more
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * ...1899
     * more

   Close

Introducing MIT Technology Review Insider.

Already a Magazine subscriber?

   You're automatically an Insider. It's easy to activate or upgrade your
   account.
   Activate Your Account

Become an Insider

   It's the new way to subscribe. Get even more of the tech news,
   research, and discoveries you crave.
   Sign Up

Learn More

   Find out why MIT Technology Review Insider is for you and explore your
   options.
   Show Me

   News and Analysis
     * Home
     * Popular
     * Today's News
     * Blogs
     * Photo Galleries
     * Videos

   Back to Top

   The mission of MIT Technology Review is to equip its audiences with the
   intelligence to understand a world shaped by technology.
     * Editions
       Find your preferred version. Choose from six languages and in 13
       regions worldwide.
     * Archives
       Explore 115 years of innovation from the most respected technology
       publication.
     * Lists
       Discover the most important people, companies and technologies
       shaping our future.
     * Events
       Attend one of our over 400 thought-provoking live events worldwide.
     * Subscribers
       Have MIT Technology Review delivered to your doorstep, desktop, or
       tablet.

     * More
     * Newsletters
     * MIT Enterprise Forum
     * MIT News Magazine
     * EmTech

     * Company
     * About Us
     * Work for Us
     * Advertise with Us
     * Reprints and Permissions

     * Your Account
     * Join
     * View Profile
     * Manage Account
     * Manage Subscription

     * Customer Support
     * Help / Support
     * Contact us
     * Feedback
     * Sitemap

Connect

     * Twitter
     * LinkedIn
     * YouTube
     * Google+
     * StumbleUpon
     * Facebook
     * RSS
     * Mobile

MIT Technology Review

     * Ethics Statement
     * Terms of Service
     * Privacy
     * Commenting Guidelines

     * © 2014
     * v1.13.05.10

   [p?c1=2&c2=16198136&cv=2.0&cj=1]

   Quantcast
