     * Sign In / Sign Up

     * Home
     * Editors' picks
     * All the stories

     * Welcome committee
     * About Hi
     * feedback@hi.co

Capture. Write. Publish.

1,306,191 words
2,622 cities

     * Sign in

   [horiz_fill_trans.png?v=1410671946]
   [horiz_fill_trans.png]

   Solo Travel, Best Travel Advice

Travel to passions, not destinations

   [5332792c01d768211e57d75d.jpg ]
   Kevin Kelly in Nashik, India

April 6th, 2014, 10am

   I have never been disappointed by a visit to London. Paris or Tokyo. Or
   for that matter, by a tour of the hill towns of Italy, or India. In
   addition to the thousands of destinations I have visited in a life-time
   of travel, I have a list of a thousand more I would like to visit
   someday. And maybe I will.

   But about two decades ago, I discovered a better target for travel than
   destinations. Rather than organize my trip around places — the iconic
   cities, monuments, streets, regions, countries — I’ve learned that I
   get 10 times the reward when I organize my travel around passions.

   I follow some personal obsession and then I go to the places it takes
   me. I go where the love is. For a while I kept bees in our backyard and
   when I traveled I would track down native beekeepers. Getting to
   regions where beekeeping flourished and then seeking out local
   beekeepers to see how they kept bees brought me to people and places I
   would not have chosen otherwise. But more importantly, I was rewarded
   with intimacy, adventures, and enjoyment beyond what I had been seeing
   before. Each year for family vacation we try to follow one of our
   children’s passions, so one year we chased dinosaurs. We rented an RV
   and drove around the US West to see as many active dinosaur digs as we
   could. Those overlooked archeological sites acted as a lens to focus
   our attention so that when we passed through the iconic places, they
   appeared brighter and more interesting. In Asia I am totally obsessed
   by pilgrimage sites, like Nashik in India (photo above).

   That’s what happens when you travel around interests. You’ll skip some
   of the canonical destinations (how can you not stop in Rome?) but wind
   up in a place you’ll find even far better than Rome. And if there are
   beekeepers in Rome (and there are!) or dinosaurs in Beijing (there
   are!), when you do arrive there your interests will make these
   destinations far more interesting.

   There is no end to what kind of obsessions you can follow around the
   world. Food is a very popular passion, and justifiably so because it
   can lead deep and true to an inner core of culture. I have friends who
   hunt down cheeses in Europe. But other follow different sirens. I’m
   thinking of the guy who bikes canal paths. I met a couple bent on
   visiting every map store in the world they could find. Of course there
   are trainspotters, and boutique hotel fans, almost cliches. But the
   stranger, more distinctly unique, more weirdly YOU your passion is, the
   more it will reward your travels.

   Surely there is something that would thrill you to encounter in another
   place? Seek it out — it’ll take some planning — and let it shape your
   meanderings. I can guarantee you, it’ll be the trip you most remember.
   ____________________ (BUTTON) Thanks
   (BUTTON) Subscribe

   Liked that moment?
   Subscribe to Kevin and get their extensions as they publish them.
   [530b2b18c19cc247718b9747.jpg] [5366827bc21363fd288b4866.jpg]
   [535d8af4c21363f7288b4690.jpg] [530b2abec19cc247718b8a07.jpg]
   [533355a3409a6e2b3f4a8aa9.jpg] [530b2b23c19cc247718b999d.jpg]
   [530b2b0ec19cc247718b95c8.jpg] [53d931427480b4f1448b46be.jpg]
   [531cbe07409a6ebd7c72ffbf.jpg] [53baa68a7480b48e518b4774.jpg]
   [530b2b28c19cc247718b9a32.jpg] [5318825001d768725b9c2531.jpg]
   [530b2b6bc19cc247718ba413.jpg] [5334f726c213632a1e8265c6.jpg]
   [530b2ab8c19cc247718b8935.jpg] [530b2b38c19cc247718b9c79.jpg]
   [530b2b93c19cc247718ba92b.jpg] [530b2b38c19cc247718b9c82.jpg]
   [530b2b63c19cc247718ba2fa.jpg] [53186f58409a6e3977585492.jpg]
   [530b2ab7c19cc247718b892e.jpg] [5334d50b409a6e263f2f0766.jpg]
   [530b2ae2c19cc247718b8e51.jpg] [5338fb9401d768506a5d5a90.jpg]
   [530b2b0ac19cc247718b94d9.jpg] [530bfe2b01d768145c4f7fb3.jpg]
   [534655ea01d768db682665bb.jpg] [530b2af8c19cc247718b918b.jpg]
   [530b2b35c19cc247718b9c07.jpg] [530b2ba0c19cc247718bab40.jpg]
   [534acd2701d768516d69a3cd.jpg] [530b2b2cc19cc247718b9ae3.jpg]
   [default-profile.jpg] [534b5eb301d768097c3c737e.jpg]
   [5332a14801d768a622a3524a.jpg]
   Andrew, Mark, Daniel, Christine and 31 others said thanks.

Share this moment

   [5332792c01d768211e57d75d.jpg ] Kevin Kelly

   Techno-philosopher, editor, obsessive photographer, tinkerer, father,
   futurist, chauffeur, and global vagabond. I make books, magazines,
   websites, and art. Come visit my library in Pacifica, CA along the
   coast.
   (BUTTON) Subscribe

Filed Under

   Solo Travel 9 writers and 8,561 words
   Best Travel Advice 1 writers and 3,786 words
     * About Hi / Contact
     * Privacy Policy
     * Terms of Service

   © 2013–2014 Moments Management Corp.
   Managing your moments, so you don't have to.

Proudly in collaboration with

Create an account

Have an account? Sign in.

   Sign up with Facebook

   or
   ____________________
   ____________________
   ____________________
   ____________________
   ____________________
   [ ] I agree to the Terms of Use and Privacy Policy
   (BUTTON) Sign Up

Sign in

No account? Sign up for free.

   Sign in with Facebook

   or
   ____________________
   ____________________
   (BUTTON) Sign in
   Forgot your password?
