   #publisher Politics RSS feed Scottish independence RSS feed Scottish
   politics RSS feed World news RSS feed Bob Geldof RSS feed UK news RSS
   feed Scotland RSS feed

   Turn autoplay off

   Turn autoplay on

   Please activate cookies in order to turn autoplay off
     * Jump to content [s]
     * Jump to site navigation [0]
     * Jump to search [4]
     * Terms and conditions [8]

Edition:

   UK US AU

     * Your activity
     * Email subscriptions
     * Account details
     * Linked services
     * Sign out

   Profile Beta
   The Guardian home
   ____________________ Search
     * News
     * US
     * World
     * Sports
     * Comment
     * Culture
     * Business
     * Money
     * Environment
     * Science
     * Travel
     * Tech
     * Media
     * Life & style
     * Data

     * News
     * Politics
     * Scottish independence

Scottish independence

Bob Geldof implores Scottish voters not to break up 'family'

   Plea made at Let's Stay Together campaign, where thousands gather in
   attempt to encourage no vote in referendum
     * Share
     * Tweet this
     *
     * [pin_it_button.png]
     *
     * Email

     * Hannah Ellis-Petersen
     *
     * The Guardian, Monday 15 September 2014 16.33 EDT

   Bob Geldof
   Bob Geldof said we are the closest of cousins and that 'when one of our
   blood spills then it all spills'. Photograph: Lefteris Pitarakis/AP

   Bob Geldof made an emotional plea to voters in Scotland not to break up
   the "family" at a London rally hoping to convince the country to stay
   in the UK.

   At a public event for the Let's Stay Together campaign, organised by
   historian Dan Snow, thousands of people gathered in Trafalgar Square,
   waving union flags in a final attempt to persuade Scottish voters that
   the rest of Great Britain wanted them to stay in the union and to vote
   no in Thursday's referendum.

   Comedians Eddie Izzard, Al Murray and Jenny Colgan and presenter June
   Sarpong were among the celebrities who took to the platform.

   As the sounds of the song Let's Stay Together drifted across the
   square, Geldof addressed his speech directly to voters, describing
   England and Scotland as the "closest of cousins". "I'd just like to
   tell everybody in Scotland we're all fucking fed up with Westminster
   and it's even more frustrating for us because we don't even get to do
   the argument that you've begun," he said. "This argument needs to be
   had among us all, you can't selfishly resolve it amongst yourselves by
   taking an easy opt-out clause.

   "Before there was a United States, before there was a United Nations,
   before there was a united this, that and the other there was a United
   Kingdom and it was an extraordinary meeting of very different minds of
   two extremely close cousins. And what a construct this thing is.
   Because Scotland is a feeling. England is a feeling. Wales is a
   feeling, Ireland a feeling. But the United Kingdom is one of the
   greatest ideas for the modern age. Between the native genius of the
   Scots and the pure pragmatic drive of the English we made a world
   beater. The pity of this is that we are the closest of cousins – when
   one of our blood spills then it all spills. There is such thing as a
   big glorious no. No is not always a negative."

   Speaking after the rally, Geldof added: "Obviously a lot of people will
   be saying that we want to break up, but I just want to know why? The UK
   is a phenomenal modern idea, invented by the Scots. They invented our
   age and the 21st century really needs to be reinvented, which I think
   is at the heart of the argument. We are all fed up with Westminster but
   they've got an option and we should be able to work out, together, a
   new constitution. But breaking up one of the most genius ideas of the
   modern political times is not the way to go. 82% of people in England
   want Scotland to stay, that should show that this is a union that
   works."

   As the crowds roared "let's stay together" in unison, Snow paid tribute
   to the important role Scotland had played in forming modern Britain and
   British society and said the "legacy of shared endeavour" between
   Britain and Scotland was evident even in Trafalgar Square.

   Speaking to the Guardian, Snow disputed that holding the rally in
   London sent a negative message up to Scottish voters. He said: "Our
   opinion is that unity is better than division. Cooperation is better
   than competition. We've come here to London to the heart of our city,
   not to tell the Scottish people how to vote. We have no business
   marching round a Scottish city and telling them how to vote. We do what
   Brits have always done, we gather in Trafalgar square. When we
   celebrate, we commiserate, we memorialise as a nation, this is where we
   do it. What we want to do is for the rest of the United Kingdom to
   gather together and say please, when you are voting, remember one
   thing. We want you to stay."

   Izzard echoed his sentiments: "We thought it was important for in
   Scotland to know what people outside feel about independence. It just
   seems to sad, and I say this to the people of Scotland, to break up our
   family and build a border. It's Scotland's choice. We cannot say
   anything to you other than that we do care. You are part of the United
   Kingdom family and we'd love you to stay."
   Daily Email
   close

Sign up for the Guardian Today

   Our editors' picks for the day's top news and commentary delivered to
   your inbox each morning.
   Sign up for the daily email
     * Print this Print this
     * Share
     * Contact us

Send to a friend

   Close this popup

   Sender's name
   ____________________

   Recipient's email address
   ____________________

   Send

   Your IP address will be logged

Share

   Close this popup
   Short link for this page: http://gu.com/p/4xtdp
     * StumbleUpon
     * reddit
     * Tumblr
     * Digg
     * LinkedIn
     * del.icio.us
     * Facebook
     * Twitter

Contact us

   Close this popup
     * Contact the Politics editor
       politics@theguardian.com
     * Report errors or inaccuracies: reader@theguardian.com
     * Letters for publication should be sent to:
       guardian.letters@theguardian.com

     * If you need help using the site: userhelp@theguardian.com
     * Call the main Guardian and Observer switchboard:
       +44 (0)20 3353 2000
     *
          + Advertising guide
          + License/buy our content

   Article history

About this article

   Close this popup

   Bob Geldof implores Scottish voters not to break up 'family'
   This article was published on the Guardian website at 16.33 EDT on
   Monday 15 September 2014. A version appeared on p7 of the Main section
   section of the Guardian on Monday 15 September 2014. It was last
   modified at 16.36 EDT on Monday 15 September 2014.

Politics

     * Scottish independence ·
     * Scottish politics

World news

     * Bob Geldof

UK news

     * Scotland

   More news
     * More on this story
     * Nicola Sturgeon
       Nicola Sturgeon launches campaign to succeed Alex Salmond
       SNP deputy first minister vows to work in good faith with pro-union
       parties on delivering new powers for Scottish parliament
     * Nicola Sturgeon faces cuts and hard choices as domestic realities
       bite at Holyrood
     * After the referendum: the 10 most pressing questions facing the
       union
     * Cameron's remark about 'effing Tories' hints at what he really
       thinks
     * Scottish referendum: people are energised – and this new way of
       doing politics is not going to change
     * Alex Salmond accepts defeat and presses for new Holyrood powers
     * Scottish referendum: David Cameron and the Queen seek to ease
       tensions
     * The 'vision thing' competes with the fear factor on Scotland's big
       day
     * Scottish independence
     * Scottish politics
     * Scottish referendum on TV: graphs and talky-talk can't hide a sense
       of occasion
     * Scottish independence: the results to watch out for as votes come
       in
     * Shetland may reconsider its place in Scotland after yes vote, says
       Carmichael
     * Scottish independence: when will the referendum result be
       announced?
     * Comment & debate
     * Alistair Darling at a polling place
       Scotland votes no: the union has survived so put away the flags
       Martin Kettle: The new settlement will be on the table next month
       and the SNP, despite a cruel and crushing anticlimax, must decide
       what to do about devo max
     * Our 15 most popular pieces on the Scottish referendum
     * Scotland's yes campaigners are voting to leave the Titanic
     * After the referendum, the reckoning: why Cameron should fear for
       his future
     * Who swung the Scottish vote? Thanks to a skinflint media, we'll
       never know
     * Ten news stories you might have missed as Scotland dominates the
       media
     * Awkward no more: how Gordon Brown found his voice
     * This is Scotland's velvet revolution and we should listen to the
       people shouting
     * Don't let Alex Salmond blind you to the yes campaign's dark side
     * In Scotland's romcom, who wants to wake up with David Cameron on
       Friday?

     * Share
     * Tweet this
     *
     *
     * Email

     * Own the weekend offer
       In this weekend's Guardian and Observer
       - Observer Sex special
       - Weekend magazine
       - Cook
       Sign up now and instantly receive vouchers for £10 off the Guardian
       and Observer papers. Redeemable for today's paper and every paper
       for two weeks.
       Get your voucher

Buy Steve Bell's Alex Salmond stress figure exclusively from the Guardian

     * steve bell - guardianoffers - promo
       Steve Bell squeezy figures
       Steve Bell's Alex Salmond squeeezy stress figure, emulating Marilyn
       Monroe's famous 'air-vent pose', is perfect for relieving the tense
       responsibility of making history. £12.99 plus p&p.
       Learn more and buy

Today's best video

     * Mia Wasikowska in Maps to the Stars
    The Guardian film show
       Our critics review Maps to the Stars, Ida, I Origins and The
       Equalizer
     * Mariam al-Mansouri
    Meet UAE's first female fighter pilot
       Major Mariam al-Mansouri says it is a dream to serve her country
     * Footage of US-led air strikes on Isis base in Syria Footage of air
       strikes on Isis base
       Air strikes destroy an Isis building and two armed vehicles near
       Kobani, Syria
     * George Clooney and Amal Alamuddin
    Clooney weds in Venice
       Hollywood A-lister marries human rights lawyer Amal Alamuddin in
       lavish ceremony

Soulmates

   The Guardian's
   online dating site
     * Red_Moon, 34
     * Jupiter_Jools, 42

   Meet someone worth meeting
     * I am a[Man__]
     * Seeking[Women______]
     * Aged[25] to [45]
     * In[United Kingdom______________________________]
     * Within[20 miles_]
     * Of ____________________

   (BUTTON) Search

Find your MP

   Find your constituency [Aberavon___________________________________] Go
   Enter an MP's name ____________________ Go
   Enter postcode ____________________ Go

   About this search | Browse the map

On Politics

     * Most viewed
     * Latest

   Last 24 hours
    1. [Brooks-Newmark-resigns-004.jpg] 1.  Sunday Mirror under pressure
       to reveal details of Tory minister ‘sexting’ sting
    2. 2. George Osborne bets on pensions vow to quell Tory panic over
       Ukip
    3. 3. Tory whips issue threat to MPs tempted to join Nigel Farage and
       Ukip
    4. 4. Ukip defector ‘lied and lied and lied’, say senior Conservatives
    5. 5. The grand delusions of Tory chairman Grant Shapps
    6. More most viewed

   Last 24 hours
    1. [UKIP-Leader-Nigel-Farage--006.jpg] 1.  Tory whips issue threat to
       MPs tempted to join Nigel Farage and Ukip
    2. 2. George Osborne bets on pensions vow to quell Tory panic over
       Ukip
    3. 3. Sunday Mirror under pressure to reveal details of Tory minister
       ‘sexting’ sting
    4. 4. The grand delusions of Tory chairman Grant Shapps
    5. 5. Tories left wide-eyed and Reckless
    6. All today's stories

Sponsored feature

   guardian jobs

   Find the latest jobs in your sector:
     * Arts & heritage
     * Charities
     * Education
     * Environment
     * Government
     * Graduate

     * Health
     * Marketing & PR
     * Media
     * Sales
     * Senior executive
     * Social care

   Browse all jobs

   ____________________ Search

Today in pictures

     * sports peronality 2012
    BBC Sports Personality of the Year – in pictures
       Bradley Wiggins capped his remarkable sporting year by taking home
       the big prize at the ceremony in London
     * Martin Parr's M Video Christmas party photograph
    Dinner, dusk and dancing Russians: my best winter shot
       A glass of wine with a rough sleeper, Santa in trunks, a thousand
       partying Muscovites … in a My Best Shot special, top photographers
       pick the image that sums up winter for them
     * Kimon, a long-tailed monkey grooms a kitten, whom, she treats as
       her baby, Bintan Island, Indonesia
    Monkey adopts kitten – in pictures
       Kimon, an eight-year-old pet female long-tailed monkey, treats a
       kitten as her baby in Bintan Island, Indonesia

     * Hot topics

     * David Cameron
     * Ed Miliband
     * Nick Clegg
     * George Osborne
     * Coalition

     * License/buy our content |
     * Privacy policy |
     * Terms of service |
     * US advertising |
     * A - Z index |
     * About us

     * © 2014 Guardian News and Media Limited or its affiliated companies.
       All rights reserved.

     * Share
     * Tweet this
     *
     *

   Quantcast

   ;
