   #Search MIT Technology Review

     * Global Edition
     * Insider
     * Magazine
     * Business Reports
     * Lists
     * Events
     * More
          + About
          + Newsletters
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum

     * Connect

Select your localized edition:

   Close ×
     * English
     * Español
     * Deutsch
     * Italiano
     * Português
     * 中文

Filter by:

     * (*) News and Analysis
     * ( ) Magazine
     * ( ) List: Innovators Under 35
     * ( ) Conferences and Events

     * Argentina
     * Brasil
     * Colombia
     * Deutschland

     * Italia
     * México
     * Portugal
     * España

     * United States
     * Uruguay
     * 中国大陆

More Ways to Connect

   Discover one of our 28 local entrepreneurial communities »

   Be the first to know as we launch in new countries and markets around
   the globe.

   Interested in bringing MIT Technology Review to your local market?
   Search Search________________________
   Search
   Log In / Join
     * New
     * Popular
     * Login / Join

MIT Technology Review MIT Technology Review - logo

   Home News & Analysis ▾
     * Features
     * Views
     * Multimedia
     * Discussions
     * Topics

     * Popular:
     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

   cover of latest MIT Technology Review magazine issue Subscribe

     * Home
          + Home
          + Biomedicine
          + Business
          + Computing
          + Energy
          + Materials
          + Mobile
       Top Stories

Business Report

China’s Factory of the Future

Christina Larson
       1
          +

A Cheaper Way to Store Solar
         Kevin Bullis
          +

BitTorrent Adds a Paywall for Music
         Tom Simonite
          +

Using Phones’ Radio Signals to Detect Gestures
         Rachel Metz
          + See More Top Stories
     * Menu
          + News & Analysis
          + Magazine
          + Lists
          + Events
          + About
          + More
          + Features
          + Views
          + Multimedia
          + Discussions
          + Topics
          + Popular:
          + Storing Sunlight
          + Rat Control
          + Google’s Balloon Shot
          + Smarter Watson
          + Quantum Computing Questions
          + Gene Sequencing Soars
          + Printed Kidneys
       cover of latest MIT Technology Review magazine issue Subscribe
          + Current Issue
          + Past Issues
          + MIT News Magazine
          + International Editions
          + Business Reports
          + Special Publications
          + Subscriptions »
          + Smartest Companies
          + Innovators Under 35
          + Breakthrough Technologies
          + Nominations »
          + Upcoming Events
          + Partner Events
          + Emtech MIT
          + MIT Enterprise Forum
          + Our Team
          + Join Us
          + Press Room
          + Awards
          + Advertise
          + Permissions
          + Contact Us
          + Customer Support »
          + Support
          + Contact Us
          + Emtech MIT
          + MIT Enterprise Forum
     * Insider
     * Connect

     * The Latest
     * Popular
     * Most Shared
     * My Profile

   Unsupported browser: Your browser does not meet modern web standards.
   See how it scores »

Genome Surgery

Review

     * 8 comments

Genome Surgery

   Precise and easy ways to rewrite human genes could finally provide the
   tools that researchers need to understand and cure some of our most
   deadly genetic diseases.
     * By Susan Young Rojahn on February 11, 2014

     * 8 comments

     * Comments
     * Email
     * Service
     * Service
     * More Share
     * Print

   Also featured in:
   MIT Technology Review magazine
   March/April 2014
   More in this issue »

Why It Matters

   Researchers’ new ability to edit the genome will likely have profound
   consequences for disease treatments.

   Over the last decade, as DNA-sequencing technology has grown ever
   faster and cheaper, our understanding of the human genome has increased
   accordingly. Yet scientists have until recently remained largely
   ham-fisted when they’ve tried to directly modify genes in a living
   cell. Take sickle-cell anemia, for example. A debilitating and often
   deadly disease, it is caused by a mutation in just one of a patient’s
   three billion DNA base pairs. Even though this genetic error is simple
   and well studied, researchers are helpless to correct it and halt its
   devastating effects.

   Now there is hope in the form of new genome-engineering tools,
   particularly one called CRISPR. This technology could allow researchers
   to perform microsurgery on genes, precisely and easily changing a DNA
   sequence at exact locations on a chromosome. Along with a technique
   called TALENs, invented several years ago, and a slightly older
   predecessor based on molecules called zinc finger nucleases, CRISPR
   could make gene therapies more broadly applicable, providing remedies
   for simple genetic disorders like sickle-cell anemia and eventually
   even leading to cures for more complex diseases involving multiple
   genes. Most conventional gene therapies crudely place new genetic
   material at a random location in the cell and can only add a gene. In
   contrast, CRISPR and the other new tools also give scientists a precise
   way to delete and edit specific bits of DNA—even by changing a single
   base pair. This means they can rewrite the human genome at will.

   It is likely to be at least several years before such efforts can be
   developed into human therapeutics, but a growing number of academic
   researchers have seen some preliminary success with experiments
   involving sickle-cell anemia, HIV, and cystic fibrosis (see table
   below). One is Gang Bao, a bioengineering researcher at the Georgia
   Institute of Technology, who has already used CRISPR to correct the
   sickle-cell mutation in human cells grown in a dish. Bao and his team
   started the work in 2008 using zinc finger nucleases. When TALENs came
   out, his group switched quickly, says Bao, and then it began using
   CRISPR when that tool became available. While he has ambitions to
   eventually work on a variety of diseases, Bao says it makes sense to
   start with sickle-cell anemia. “If we pick a disease to treat using
   genome editing, we should start with something relatively simple,” he
   says. “A disease caused by a single mutation, in a single gene, that
   involves only a single cell type.”

     In little more than a year, CRISPR has begun reinventing genetic
     research.

   Bao has an idea of how such a treatment would work. Currently,
   physicians are able to cure a small percentage of sickle-cell patients
   by finding a human donor whose bone marrow is an immunological match;
   surgeons can then replace some of the patient’s bone marrow stem cells
   with donated ones. But such donors must be precisely matched with the
   patient, and even then, immune rejection—a potentially deadly
   problem—is a serious risk. Bao’s cure would avoid all this. After
   harvesting blood cell precursors called hematopoietic stem cells from
   the bone marrow of a sickle-cell patient, scientists would use CRISPR
   to correct the defective gene. Then the gene-corrected stem cells would
   be returned to the patient, producing healthy red blood cells to
   replace the sickle cells. “Even if we can replace 50 percent, a patient
   will feel much better,” says Bao. “If we replace 70 percent, the
   patient will be cured.”

   Though genome editing with CRISPR is just a little over a year old, it
   is already reinventing genetic research. In particular, it gives
   scientists the ability to quickly and simultaneously make multiple
   genetic changes to a cell. Many human illnesses, including heart
   disease, diabetes, and assorted neurological conditions, are affected
   by numerous variants in both disease genes and normal genes. Teasing
   out this complexity with animal models has been a slow and tedious
   process. “For many questions in biology, we want to know how different
   genes interact, and for this we need to introduce mutations into
   multiple genes,” says Rudolf Jaenisch, a biologist at the Whitehead
   Institute in Cambridge Massachusetts. But, says Jaenisch, using
   conventional tools to create a mouse with a single mutation can take up
   to a year. If a scientist wants an animal with multiple mutations, the
   genetic changes must be made sequentially, and the timeline for one
   experiment can extend into years. In contrast, Jaenisch and his
   colleagues, including MIT researcher Feng Zhang (a 2013 member of our
   list of 35 innovators under 35), reported last spring that CRISPR had
   allowed them to create a strain of mice with multiple mutations in
   three weeks.

   Because a CRISPR system can easily be designed to target any specific
   gene, the technology is allowing researchers to do experiments that
   probe a large number of them. In December, teams led by Zhang and MIT
   researcher Eric Lander created libraries of CRISPRs, each of which
   targets a different human gene. These vast collections, which account
   for nearly all the human genes, have been made available to other
   researchers. The libraries promise to speed genome-wide studies on the
   genetics of cancer and many other human diseases.

   Genome GPS

   The biotechnology industry was born in 1973, when Herbert Boyer and
   Stanley Cohen inserted foreign DNA that they had manipulated in the lab
   into bacteria. Within a few years, Boyer had cofounded Genentech, and
   the company had begun using E. coli modified with a human gene to
   manufacture insulin for diabetics. In 1974, Jaenisch, then at the Salk
   Institute for Biological Studies in San Diego, created the first
   transgenic mouse by using viruses to spike the animal’s genome with a
   bit of DNA from another species. In these and other early examples of
   genetic engineering, however, researchers were limited to techniques
   that inserted the foreign DNA into the cell at random. All they could
   do was hope for the best.

   It took more than two decades before molecular biologists became adept
   at efficiently changing specific genes in animal genomes. Dana Carroll
   of the University of Utah recognized that zinc finger nucleases,
   engineered proteins reported by colleagues at Johns Hopkins University
   in 1996, could be used as a programmable gene-targeting tool. One end
   of the protein can be designed to recognize a particular DNA sequence;
   the other end cuts DNA. When a cell then naturally repairs those cuts,
   it can patch its genome by copying from supplied foreign DNA. While the
   technology finally enabled scientists to confidently make changes where
   they want to on a chromosome, it’s difficult to use. Every modification
   requires the researcher to engineer a new protein tailored to the
   targeted sequence—a difficult, time-consuming task that, because the
   proteins are finicky, doesn’t always work.

   TALENs, another significant advance in gene editing, came along in
   2010. TALENs are also proteins that find and cut a desired DNA
   sequence—but tailoring them to new gene targets is much easier. While
   they represented a great improvement over zinc fingers, however, TALENs
   are large proteins that are cumbersome to work with and deliver into
   cells.

   CRISPR changed everything. It replaces the DNA-targeting proteins with
   a short bit of RNA that homes in on desired genes. Unlike the complex
   proteins, RNA—which has nearly the same simple structure as DNA—can be
   made routinely in the lab; a technician can quickly synthesize the
   roughly 20-letter-long sequences the method requires. The system makes
   it easy for medical researchers to modify a genome by replacing,
   deleting, or adding DNA.

   CRISPR stands for “clustered regularly interspaced short palindromic
   repeats”—clusters of brief DNA sequences that read similarly forward
   and backward, which are found in many types of bacteria. Scientists
   first observed the puzzling DNA segments in the 1980s but didn’t
   understand for almost two decades that they are part of a bacterial
   defense system. When a virus attacks, bacteria can incorporate
   sequences of viral DNA into their own genetic material, sandwiching
   them between the repetitive segments. The next time the bacteria
   encounter that virus, they use the DNA in these clusters to make RNAs
   that recognize the matching viral sequences. A protein attached to one
   of these RNAs then cuts up the viral DNA.

   In 2012, Emmanuelle Charpentier, a medical microbiologist who studies
   pathogens at the Helmholtz Centre for Infection Research, and Jennifer
   Doudna, a collaborator at the University of California, Berkeley,
   showed they could use a single RNA in conjunction with the cutting
   protein, an enzyme called Cas9, to slice any desired sequence of DNA in
   test tubes. It was still uncertain whether the method would work in
   animal cells, but in January 2013 came a dramatic breakthrough. Zhang
   and George Church, a Harvard Medical School geneticist, separately
   reported that the CRISPR/Cas9 system could be used for gene editing in
   the cells of animals, including humans.

   Now a researcher who wants to go after a new gene need only synthesize
   the Cas9 protein and a bit of RNA that matches the sequences of the
   targeted region. The RNA then guides the enzyme to the DNA the
   researcher wants to cut. And because the same cutting protein is used
   regardless of the target, researchers can design experiments in which
   they change multiple genes in an organism simultaneously using Cas9 and
   multiple RNA guides. “It offers the potential to do experiments that in
   the past were very difficult or essentially not possible,” says Doudna.

   Complex Mysteries

   MIT’s Zhang, who is a member of the Broad Institute and the McGovern
   Institute for Brain Research, is interested in the genetics behind
   mental illness. To try to understand these complex conditions, Zhang
   has helped develop multiple gene- and neuron-modifying tools, including
   TALENs and optogenetics, a technique that involves controlling neuron
   activity with laser light. When he first heard about CRISPR, in 2011,
   he began to engineer it for use in human cells. Now he’s using CRISPR
   to help reveal the genetic secrets behind such devastating and poorly
   understood conditions as schizophrenia and autism.

   The tool allows Zhang to begin systematically testing some of the DNA
   variants that have been linked to the illnesses. While much progress
   has been made over the last decade toward identifying genes that are
   common in people with these conditions, understanding how these genes
   relate to the symptoms is a daunting challenge. “What you learn from
   sequencing is only an observation,” says Zhang: in order to understand
   whether a suspected gene is actually causing the condition, you have to
   introduce the specific mutation into healthy cells or organisms and see
   what goes wrong. If the mutated cell or organism has features that
   mimic the human disease, that’s evidence implicating the gene.

   Zhang can re-create, in both lab mice and cultured human cells, genetic
   variants found in people with autism and schizophrenia. “You can put a
   human mutation into the corresponding gene in a lab animal and then
   see: does that animal become less social or have a learning deficit?”
   he says. Then, he adds, you can study differences in the behavior and
   physiology of lab-cultured neurons grown from stem cells that have been
   modified with the same mutation. “With single-gene mutations, we will
   start to see aspects of the biological function that are involved in
   autism,” he says.

     Perhaps scientists could rewrite normal genes so that humans could
     better fight infections.

   Zhang is also using CRISPR to make multiple genetic changes at once.
   That becomes particularly important with complex diseases like autism
   and schizophrenia, which for the most part are not caused by the type
   of single DNA change behind sickle-cell anemia. Different patients are
   affected by different collections of mutations. Solving a puzzle of
   such immense complexity will require large, systematic studies on the
   effects of various genes and the way they interact. CRISPR makes such
   studies possible, says Zhang, and will be important in finding
   treatments for a variety of complex diseases. “We will understand more
   about pathways and disease mechanisms,” he says. “This knowledge will
   inform all kinds of drug development.”

   Designer Babies

   Late last year, Doudna, Zhang, Church, and two other pioneers of genome
   editing founded a startup that will develop novel treatments for human
   genetic diseases. In November the company, Editas Medicine, announced
   that it had raised $43 million in venture capital and said it plans to
   use genome-editing technologies against a broad range of illnesses.

   The launch of Editas should benefit from a resurgence of interest in
   gene therapy thanks to years of technological improvements, including
   safer mechanisms for delivering treatment. “The landscape has changed
   for gene therapy,” says Church. (There are still no gene therapies
   approved in the United States, though a number are in human trials.)
   But he says the therapies that Editas will develop will be
   fundamentally different from the older approaches that use a virus to
   insert a gene into cells.

   “Making a change or a deletion is out of range for most of those simple
   viral methods,” Church says. And deleting a bit of DNA, rather than
   adding a gene, may indeed be the key to treating many illnesses. Take
   Huntington’s disease. The fatal brain condition arises from a buildup
   of a toxic protein in neurons. Adding a healthy copy of the gene to the
   cell would not affect that protein’s poisonous activity: the original
   dysfunctional version must be rewritten. With the new genome-editing
   tools, says Church, rewriting the defective DNA may be possible: “You
   aren’t limited to adding back something that is missing.” And, he adds,
   “when you start realizing that the most common versions of genes are
   not necessarily the ideal versions, then you realize this is a much
   bigger field.” Perhaps scientists could rewrite normal genes so that
   humans can better fight infectious diseases. They might even be able to
   shake up the molecular pathways involved in aging.

   Church also predicts that if genome editing is used to cure childhood
   diseases, some scientists will be tempted to use it to engineer embryos
   during in vitro fertilization. Researchers have already shown that
   genome editing can rewrite DNA sequences in rat and mouse embryos, and
   in late January, researchers in China reported that they had created
   genetically modified monkeys using CRISPR. With such techniques, a
   person’s genome might be edited before birth—or, if changes were made
   to the eggs or sperm-producing cells of a prospective parent, even
   before conception.

   These possibilities raise ethical questions. But if researchers prove
   they can safely correct diseases by editing the genome, it’s inevitable
   that some parents will also want to alter the genomes of healthy
   embryos. “If you can prevent mental retardation with gene therapy,
   presuming that that’s permissible, then there’s a whole spectrum of
   intellectual challenges that will be discussed,” says Church.

   Such discussions are likely to heat up as CRISPR becomes more widely
   used. For now, though, the technology is still evolving: while
   researchers like Bao, Church, and Zhang ultimately hope to cure some of
   our most intractable diseases, much of their time is still spent simply
   fine-tuning the tool and exploring its possibilities. But even in these
   early days, CRISPR has already transformed how these researchers think
   about manipulating the genome. They are ham-fisted no longer.

8 comments. Share your thoughts » 0 comments about this story. Start the
discussion »

   Credit: Illustration courtesy of Wellcome Library, London

   Tagged: Biomedicine, DNA, genetics, RNA, genes, genome editing, CRISPR

   Reprints and Permissions | Send feedback to the editor
     * Related stories
     * You may have missed
     * More from this author

     *

Research Reveals Structure of Key CRISPR Complex
       Work reveals how a genome-editing tool works to correct errors in
       the genetic code.
       Continue
       0

     *

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
       3
     *

Radical New DNA Sequencer Finally Gets into Researchers’ Hands
       8
     *

The History Inside Us
       2
     *

Spotting Cancer in a Vial of Blood
       15

     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
       2
     *

EmTech: 3-D Printing Complex Kidney Components
       1
     *

EmTech: Risks of Gene-Editing Drugs Need Study, Pioneer Warns
       1
     *

EmTech: Three Questions with the Man Who Grows Meat
       13

     *

Making Innovation
     *

Three Questions with the CEO of D-Wave
     *

Paralyzed Rats Take 1,000 Steps, Orchestrated by Computer
     *

EmTech: Illumina Says 228,000 Human Genomes Will Be Sequenced This Year
     *

EmTech: IBM Tries to Make Watson Smarter
     *

EmTech: Google’s Internet “Loon” Balloons Will Ring the Globe within a Year

   Susan Young Rojahn Editor

   View Profile »

   Follow @slyoung11
     * RSS

     *

Modernizing the Medical Record
       1
     *

Blood Sugar Crash
       1
     *

Neuroscience’s New Toolbox
       6
     *

Biotech Makes Personalized Cancer Vaccines Using Tumor Samples
       2

     *

Genome Editing to Reverse “Bubble Boy” Syndrome
       0
     *

DNA-Based Research May Have Unveiled Long-Sought Diabetes Treatment
       3
     *

We Need a MERS Vaccine, but High Costs, Regulations Make One Unlikely
       7
     *

Nerve-Stimulating Implant Could Lower Blood Pressure
       2
     * See all from this author

     * The Latest
     * Popular
     * Most Shared

     *

1 day ago

Other Interesting arXiv Papers (Week ending September 27, 2014)
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

2 days ago

Thom Yorke Album Sold Through BitTorrent in Attempt to Make File Sharers Pay
     *

2 days ago

Seven Stories You Shouldn’t Miss
(Week Ending September 27, 2014)
     *

Innovation Series: The Connected Home
       Brought to you by
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

2 days ago

Radio Interference Adds Gesture Recognition to Smartphones
     *

3 days ago

Recommended from Around the Web (Week Ending September 27, 2014)
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

3 days ago

Best Tweets from EmTech: Day 2
     *

Revolution in Progress: The Networked Economy
       In partnership with SAP
     *

3 days ago

Best Tweets from EmTech: Day 1
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

Technology Insights - Portability vs. Privacy: Striking the Right Balance in
the Mobile Era
       Free download courtesy of Symantec
     *

4 days ago

EmTech: Risks of Gene-Editing Drugs Need Study
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     * See full archive

     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

5 days ago

EmTech: Google’s Astro Teller Says Its “Loon” Balloons Will Ring the Globe in
2015
     *

4 days ago

IBM Adds New Features to Make Watson Smarter
     *

2 days ago

Startups Seek Cancer Drugs and Wall Street Riches Using Quantum Machines
     *

4 days ago

EmTech: Record Number of Genomes Sequenced in 2014
     *

4 days ago

EmTech: How to 3-D Print Complex Kidney Parts
     *

1 month ago

35 Innovators Under 35 | 2014
     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

3 days ago

The Coming Era Of Self-Assembly Using Microfluidic Devices
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

6 days ago

Uber’s Driver Poach Shows Lack of Respect for Workers
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

5 days ago

EmTech: Three Questions with a “Meat Brewer”
     *

5 days ago

App Talko Hopes to Get You to Use Phone to Actually Talk
     * See full archive

     *

2 days ago

First Quantum Logic Operation For An Integrated Photonic Chip
     *

2 days ago

A Potentially Cheap Way to Store Solar
     *

6 days ago

Startup Brain Corporation Offers a Way to Train Robots by Demonstration, Not
Coding
     *

3 days ago

Zaps to Spinal Cord Have Rats Walking Again
     *

6 days ago

Lifelogging App Knows When You’re Depressed, Stressed or Lonely
     *

1 week ago

Solar City and Tesla Combine Manufacturing Plans
     *

1 week ago

Peter Thiel Says Computers Haven’t Made Our Lives Significantly Better
     *

1 week ago

The Hidden World of Facebook "Like Farms"
     *

2 months ago

Forget the Shortest Route Across a City; New Algorithm Finds the Most
Beautiful
     *

1 month ago

35 Innovators Under 35 | 2014
     *

3 years ago

Astronomers Find First Evidence of Other Universes
     *

1 year ago

Innovators Under 35
     *

1 year ago

Given Tablets but No Teachers, Ethiopian Children Teach Themselves
     *

1 year ago

Astrobiologists Find Ancient Fossils in Fireball Fragments
     *

1 year ago

First Teleportation from One Macroscopic Object to Another
     *

1 year ago

Government Lab Reveals It Has Operated Quantum Internet for Over Two Years
     * See full archive

   Show comments »
   Conversation powered by Livefyre

New & Trending

     * Storing Sunlight
     * Rat Control
     * Google’s Balloon Shot
     * Smarter Watson
     * Quantum Computing Questions
     * Gene Sequencing Soars
     * Printed Kidneys

     * Other Interesting arXiv Papers (Week ending September 27, 2014)
     * First Quantum Logic Operation For An Integrated Photonic Chip
     * A Promising Step Toward Round-the-Clock Solar Power
     * Pirate Favorite BitTorrent Offers a New Way to Pay for Music

From the Archives

     * The Art of the Possible
    8 years ago
     * The Hottest VC on the Planet
    10 years ago
     * Nanotech Goes to Work
    13 years ago
     * Computing's Johnny Appleseed
    14 years ago

     * more
     * 2012
     * 2011
     * 2010
     * 2009
     * 2008
     * ...1899
     * more

   Close

Introducing MIT Technology Review Insider.

Already a Magazine subscriber?

   You're automatically an Insider. It's easy to activate or upgrade your
   account.
   Activate Your Account

Become an Insider

   It's the new way to subscribe. Get even more of the tech news,
   research, and discoveries you crave.
   Sign Up

Learn More

   Find out why MIT Technology Review Insider is for you and explore your
   options.
   Show Me

   News and Analysis
     * Home
     * Popular
     * Today's News
     * Blogs
     * Photo Galleries
     * Videos

   Back to Top

   The mission of MIT Technology Review is to equip its audiences with the
   intelligence to understand a world shaped by technology.
     * Editions
       Find your preferred version. Choose from six languages and in 13
       regions worldwide.
     * Archives
       Explore 115 years of innovation from the most respected technology
       publication.
     * Lists
       Discover the most important people, companies and technologies
       shaping our future.
     * Events
       Attend one of our over 400 thought-provoking live events worldwide.
     * Subscribers
       Have MIT Technology Review delivered to your doorstep, desktop, or
       tablet.

     * More
     * Newsletters
     * MIT Enterprise Forum
     * MIT News Magazine
     * EmTech

     * Company
     * About Us
     * Work for Us
     * Advertise with Us
     * Reprints and Permissions

     * Your Account
     * Join
     * View Profile
     * Manage Account
     * Manage Subscription

     * Customer Support
     * Help / Support
     * Contact us
     * Feedback
     * Sitemap

Connect

     * Twitter
     * LinkedIn
     * YouTube
     * Google+
     * StumbleUpon
     * Facebook
     * RSS
     * Mobile

MIT Technology Review

     * Ethics Statement
     * Terms of Service
     * Privacy
     * Commenting Guidelines

     * © 2014
     * v1.13.05.10

   [p?c1=2&c2=16198136&cv=2.0&cj=1]

   Quantcast
