TEDxMarketStreet

   bait apparel logo

May 10th 2014
10am-5pm
San Francisco, CA
at Digital Garage, 717 Market Street

     * Civic Innovation
     * Speakers/Performers
     * Sponsors/Donate
     * About
     * Team

Civic Innovation

The TEDxTalk videos from this event are now online! View our playlist below:

   IFRAME:
   //www.youtube.com/embed/videoseries?list=PLsRNoUx8w3rOQPVRk1Wa0SSpeghAC
   1U22

Photos from TEDxMarketStreet

   IFRAME:
   https://www.flickr.com/photos/tedxmarketstreet/14154408411/in/set-72157
   644700765059/player/

TED^xMarketStreet: Civic Innovation

   There is a rising tension between the tech startup ecosystem and the
   pre-existing residents and social infrastructure of the city of San
   Francisco. At the geographical heart of these shifting tides is Market
   Street, a major thoroughfare that splits the city diagonally and houses
   old and new residents of the city. As we witness the creation of a
   continually changing, inimitably eccentric urban history, how can we
   make sure that technology and innovation are helping this
   transformation occur in a responsible way that benefits the entire
   community?

   At TEDxMarketStreet, we're spotlighting creative ways of tackling the
   income disparity in gentrifying cities by inviting a variety of voices
   to the stage in order to catalyze this important conversation.

   While we are hosting this event, we are fully aware that our stage
   alone cannot represent all the important voices in the community. We
   welcome all those who have an opinion on this matter to join and help
   steer the conversation here. We also have a few speaker slots left, so
   please feel free to suggest other powerful voices whose views are not
   yet represented on this speaker roster.

   We welcome all those who have an opinion on this matter to join and
   help steer the conversation via our discussion page.

Speakers and Performers

   Brandon Santiago

Brandon Santiago

   Brandon Santiago is a Lead Artist at Youth Speaks. As a Puerto Rican
   poet, radical educator and San Francisco native, he has traveled across
   the country to perform in venues such as the San Francisco Opera House
   and the Kennedy Center for Performing Arts in Washington D.C.. He has
   led workshops for both college and high School students as well as
   pedagogical, and artistic development for Teachers and Educators.
   Brandon Santiago’s main focus is to empower urban communities of color
   by using the arts as a tool to illuminate issues that have been
   marginalized by mainstream culture. After dropping out of High School,
   Brandon went on to Graduate from San Francisco State, earning a degree
   in Anthropology. He is currently on scholarship at the University of
   San Francisco’s School of Education pursuing a Masters degree in
   International and Multicultural Education. Brandon is recently happily
   married and he maintains his faith in Christ as the most important
   reality in his life.
   Caleb

Caleb Hunter

   Born, raised and educated in California, Caleb is fueled by all things
   digital and is a lover of entrepreneurism, architecture, urban design,
   and music. He has also had the opportunity to be a part of the
   technology groups within several organizations, including Autodesk,
   Cadence, Shaman, BlueWireless, and NASA. In addition, Caleb have the
   honor of being a member of the board of directors of The Learning
   Shelter as well as continuing to support the endeavors of The Last
   Mile. He is also a learner of languages (programming and linguistic), a
   voice on Quara, a Tweeter of the mundane, and a plucker of the guitar.
   Del

Deleano Seymour

   Del knows the Tenderloin better than anyone. The 65-year old army
   veteran spend many years on the very streets in which he now conducts
   his tours. He launched the Tenderloin Walking Tours in 2009 to share
   his extensive knowledge - both historic and firsthand - of the infamous
   Tenderloin district. Del's connection to the TL creates a rich and
   vibrant experience to everyone who joins him. The tours are held by
   appointment.
   Eric

Eric Rodenbeck

   Eric Rodenbeck founded Stamen Design in 2001 and has since then he has
   been working to extend the boundaries of online media and live
   information visualization. He led the interactive storytelling and
   data-driven narrative effort at Quokka Sports, and illustrated and
   designed at Wired Books and Wired Magazine, for which he has also
   written. He is a sought-after speaker and has spoken at Yale, Columbia,
   Harvard, Stanford, and multiple design and technology conferences, and
   has been a judge in the Smithsonian's National Design Awards. Eric has
   been named one of Esquire Magazine's "Best and Brightest" new designers
   and thinkers, and one of ID Magazine's top 40 designers to watch. His
   work is in the permanent collection of the Museum of Modern Art in New
   York City, and he sits on the Board of Directors of the Kenneth Rainin
   Foundation and the Grey Area Foundation for the Arts.
   Gregg

Gregg Cassin

   Gregg, a survivor of HIV for nearly 30 years, is a powerfully
   charismatic speaker and facilitator, working with universal themes of
   how life’s challenges and suffering present us with growth-filled
   opportunities. He has worked with the LGBT, HIV/AIDS and youth
   communities for over 25 years with his lectures, retreats and
   workshops. During the height of the epidemic Gregg began facilitating
   groups for people affected by HIV/AIDS. He founded the San Francisco
   Healing Circle, and the San Francisco Center for Living, as well as
   leading conferences and retreats around the country with AIDS, Medicine
   and Miracles. He is currently offering "Honoring Our Experience", a
   retreat program addressing the issues of long term survivors of the
   epidemic.
   Ingrid

Ingrid Sanders

   Ingrid Sanders is the Founder and CEO of popexpert.com, a platform that
   inspires and enables lifelong learning by making it easy to meet with
   experts over live face-to-face video sessions that help you get better
   at: life, work & play.
   Jenny

Jenny Odell

   Born just a few miles from where the Google Headquarters would
   eventually be, Jenny Odell studied English at UC Berkeley and Design
   and Technology at the San Francisco Art Institute. Her work utilizes
   cutouts from Google Maps screen shots in an effort to show human
   environments -- particularly their fragile infrastructural elements --
   from a new and clarifying perspective. Odell's work has been exhibited
   internationally and has appeared in TIME's LightBox, The Atlantic, The
   Economist, Wired, Rhizome, ESPN the Magazine, the NPR Picture Show,
   Esquire Russia, and Die Zeit. She currently teaches a class on the
   implications of cell phone photography for art and experience at
   Stanford University, and is working on a series of work enabled by a
   grant from the San Francisco Arts Commission.
   Tim

John Paul Farmer

   John served as Senior Advisor for Innovation at the White House Office
   of Science and Technology Policy under President Barack Obama, where he
   co-founded and directed the Presidential Innovation Fellows program to
   save lives, save taxpayer dollars, and promote economic growth. He
   previously served as Senior Advisor for Healthcare Reform. Prior to
   Washington, John build new businesses in the investment industry and
   played professional minor league baseball for the LA Dodgers and the
   Atlanta Braves. He is a graduate of Harvard University and has an MBA
   from Columbia University.
   Karen

Karen Cheng

   Karen learned to dance in a year. Her dance video has been seen by over
   4 million people and has inspired thousands to pursue their passions.
   She's the co-founder of Giveit100, a video site where you choose
   something to get better at and take a video of your progress every day.
   Carey

Rose Broome

   Rose believes in using the power of technology to create health,
   happiness, and positive transformation in the world. She's the
   cofounder of HandUp, a direct donation system for homeless people and
   neighbors in need. She lives in San Francisco and loves cats and dark
   chocolate.
   Theon Johnson III

Theon Johnson III

   Theon Johnson III is the Associate Pastor at GLIDE. A native of
   Mississippi, Theon came to GLIDE from serving as a campus minister at
   Jackson State University. With a background in Philosophy, Religion and
   Education from Millsaps College, Theon studied Theology and Ethics at
   Wesley Theological Seminary in Washington DC. During his time in
   Washington, he served as an Advocacy Associate with the General Board
   of Church Society on Capitol Hill. Theon is currently a doctoral
   student in Educational Leadership at Jackson State University in
   Mississippi. Theon believes music traverses many barriers and is
   particularly passionate about music as a vehicle for both personal
   expression and communal witnessing. Likewise, he also considers sharing
   meals a spiritual practice – of which Indian and Thai food are some of
   his favorites. He finds a strong connection between these experiences
   and the Mission and Core Values of GLIDE.
   Tim

Tim O’Reilly

   Tim is the founder and CEO of O'Reilly Media, a technical book
   publisher who learned that the right way to market books was to market
   the technologies behind them. His company played a crucial role in
   evangelizing the world wide web, the Perl programming language, Linux,
   open source, and xml, and later expanded into online publishing,
   conferences, magazine, and early stage venture investing. He is
   interested in getting to know people on the cutting edge. "I think of
   my role as changing the future by helping to capture and spread the
   knowledge of innovators," Tim writes. "I sometimes call my company's
   edge in trendspotting 'watching alpha geeks.'"
   Viviana

Viviana Guzman

   Described by the New York Times as "an imaginative artist,"
   Chilean-born flutist, Viviana FluteQueen Guzmán performs over 50
   concerts a year throughout the world. Her most recent recording
   “Traveling Sonata” received a Grammy Nomination. She has been featured
   on programs for PBS, NBC, and NPR, seen on the cover of Latina Style
   Magazine, and in COSMOPOLITAN en Español and has performed in 123
   countries, and in all 7 continents. Viviana is CEO & Director of the
   San Francisco Flute Society & Festival. This season Viviana includes
   performances in Argentina, Philippines, Peru, Chile, Japan, China,
   Taiwan, Tahiti, Easter Island, California and as a soloist with the
   Southeast Missouri Symphony Orchestra as well as with the San Jose
   Chamber Orchestra.

Sponsors

   If you are a company committed to seeing civic innovation take place in
   a healthy way in San Francisco and beyond, please consider becoming a
   sponsor for our event. Your brand will be acknowledged in materials
   relevant to the event, and we are happy to work with you to come up
   with creative ways to get you involved. Please email
   info[at]tedxmarketstreet.com for more information.

   This event is sponsored by:
   [digital-garage.jpg]

   with in-kind donations from:
     * [four-barrel.png]
     * [pilar.png]
     * [snakebite.jpg]
     * [spicy-wines.jpg]

Donate

   TED^xMarketStreet is entirely self-funded. We don't receive any funding
   from TED or TED^x; all of our event expenses are paid for through
   ticket sales, sponsors, and out of the pockets of our event team.
   Please consider making a tax-deductible PayPal donation through our
   fiscal sponsor, The Tofu Project.
   PayPal

About TED^x: x = independently organized event

   TED^x is a program of local, self-organized events that bring people to
   together to share a TED-like experience. At a TED^x event, TEDTalks
   video and live speakers combine to spakr a deep discussion and
   connection in a small group. These local, self-organized events are
   branded TED^x, where x = independently organized TED event. The TED
   conference provides general guidance for the TED^x program, but
   individual TED^x events are self-organized.

About TED

   TED is a nonprofit organization devoted to Ideas Worth Spreading.
   Started as a four-day conference in California 25 years ago, TED has
   grown to support those world-changing ideas with multiple initiatives.
   The annual TED Conference invites the world’s leading thinkers and
   doers to speak for 18 minutes. Their talks are then made available,
   free, at TED.com. TED speakers have included Bill Gates, Al Gore, Jane
   Goodall, Elizabeth Gilbert, Sir Richard Branson, Nandan Nilekani,
   Philippe Starck, Ngozi Okonjo-Iweala, Isabel Allende and former UK
   Prime Minister Gordon Brown. The annual TED Conference takes place each
   spring in Vancouver, Canada, along with the TEDActive simulcast in Palm
   Springs; the annual TEDGlobal conference is held each summer in
   Edinburgh, Scotland.

Team

Steering Committee

Brady Forrest

Lisa Katayama

Alli Magidsohn

Peter Shanley

Event Team

Heather Cochran

Eddie Codel

Ariena Kaneshima

Tomo Saito

Tact Sasajima

Minori Toyoi

Mitsuo Yoshizawa

   Copyright © 2014 TED^xMarketStreet
