   #alternate TechCrunch » Feed TechCrunch » Comments Feed TechCrunch »
   Fastly Growing Quickly Snags $40M As VCs Give Generously Comments Feed
   Mail.ru Takes Over ‘Russia’s Facebook’ Vkontake In $1.47B Deal, Settles
   Durov Suit Visual Search Company Slyce Buys Pounce For $5M To Build
   “Amazon Firefly” For The Rest Of Retail alternate alternate TechCrunch
   WordPress.com

   TechCrunch
   Got a tip? Let us know.
   Menu Search
     * News
          + Channels
          + Startups
          + Mobile
          + Gadgets
          + Enterprise
          + Social
          + Europe
          + Asia
          + CrunchGov

     * Trending

     * Tinder
     * NSA
     * Android
     * Google
     * Microsoft
     * Apple
     * Twitter
     * Facebook

   All Topics
   All Galleries

     TCTV

   Shows

     * TCTV News
     * CrunchWeek
     * Fly Or Die
     * Gadgets

     * Incubated
     * Inside Jobs
     * One Lap
     * TC Cribs

   All Shows

   All Videos

     Events

     * TechCrunch Events

     * Disrupt
     * Crunchies
     * Meetups
     * International City Events
     * Hackathon
     * Hardware Battlefield

     * News About

     * Google I/O 2014
     * CES
     * SXSW
     * WWDC 2014

   All Events

   Search TechCrunch

   Search TechCrunch ____________________ (BUTTON) Search

   CrunchBase

     * Follow Us
     * Facebook
     * Twitter
     * Google+
     * LinkedIn
     * Youtube
     * RSS
     * Email
     * More
          + LinkedIn
          + Youtube
          + RSS
          + Email

   Disrupt Europe 2 Weeks Left to Save £300 on Disrupt Europe Tickets -
   Register Now!
   AOL Privacy Policy and Terms of Service

   Enterprise
     * Free Windows 9 For Some Isn’t Too Crazy

Free Windows 9 For Some Isn’t Too Crazy
     * Enterprise App Marketplaces Respond To Pain Points In Corporate IT

Enterprise App Marketplaces Respond To Pain Points In Corporate IT
     * Social Platform Hootsuite Adds $60M To Its Coffers, Buys Zeetl To
       Integrate Voice

Social Platform Hootsuite Adds $60M To Its Coffers, Buys Zeetl To
Integrate Voice
     *

Browse more...

   CDN
     * Instart Logic Bags $26M in Series C Funding To Continue Reinventing
       Content Delivery Networks

Instart Logic Bags $26M in Series C Funding To Continue Reinventing Content
Delivery Networks
     * Apple’s CDN Plans Would Give It Greater Control Over Streaming For
       Expanded Offerings

Apple’s CDN Plans Would Give It Greater Control Over Streaming For
Expanded Offerings
     * Verizon Confirms EdgeCast Acquisition, Adding Over 6K Customers To
       Its Content Delivery Business

Verizon Confirms EdgeCast Acquisition, Adding Over 6K Customers To Its
Content Delivery Business
     *

Browse more...

   funding
     * Andreessen Goes On Tweet Storm About Burn Rates, Says To Worry

Andreessen Goes On Tweet Storm About Burn Rates, Says To Worry
     * The Long Fall

The Long Fall
     * When The Funding Bubble Bursts It Doesn’t Have To Mean Disaster

When The Funding Bubble Bursts It Doesn’t Have To Mean Disaster
     *

Browse more...

   fastly
     * Fastly Raises $10M For Content Delivery Network Built For Mobile,
       Real-Time World

Fastly Raises $10M For Content Delivery Network Built For Mobile,
Real-Time World
     *

Browse more...

Fastly Growing Quickly Snags $40M As VCs Give Generously

   Posted Sep 16, 2014 by Ron Miller (@ron_miller)
     *
     *
     *
     *
     * More
          + Add to Flipboard Magazine.
          +
          + submit to reddit
          +

   Next Story

Mail.ru Takes Over ‘Russia’s Facebook’ Vkontake In $1.47B Deal, Settles
Durov Suit

   [canstockphoto3715991.jpg?w=738]

   Fastly, a fast-growing content delivery network, snagged $40M in Series
   C funding today. The round was led by August Capital with previous
   investors Battery Ventures, O’Reilly AlphaTech Ventures and Amplify
   Partners also participating along with new investor IDG Ventures. The
   investment brings the total raised to date to $54M.

   Company CEO and founder Artur Bergman says they set out to build a
   better content delivery network by concentrating on the types of
   traffic that meet modern content requirements such as API traffic,
   mobile content and user generated content. What’s more, Bergman says
   they do it blazingly fast claiming speed of 150MS (which is essentially
   instant), for example to purge a cache. He claims it can take minutes
   with competitors (although I was unable to confirm that).

   As an example, one of their clients is The Guardian, the UK news
   company, which often needs to publish breaking news or update
   existing stories on the fly. This could involve taking down the old
   story, purging the cache so no trace of the old version exists and
   putting up the new one as quickly as possible to beat the competition.
   Bergman says that requires instant processing and he says that’s what
   his company offers.

   Simply put, content delivery networks are networks of servers
   distributed throughout the world to reduce delivery latency and
   increase performance. The idea is to deliver the content as close as
   possible to the device on which it’s being viewed. The closer the
   content, the lower the latency and the faster it gets delivered.

   Bergman says the chief competition in the CDN market is Akamai, but he
   believes his company has differentiated itself from the long-time
   market leader. “We believe in how we work with customers -to be
   transparent and open.” He added, “That’s a pretty noble concept in the
   CDN space, which has traditionally been a black box that does magic
   stuff for you.”

   He says customers are used to having a certain level of transparency
   and visibility in their own data and his company wants to provide a
   similar level of visibility in Fastly.

   The idea for the company was born when he was working at Wikia. “We
   come from a background of running large websites with lots of
   user-generated content,” he told me. He explained the content usually
   remained unchanged for a long time, but when it changed, it needed to
   be updated quickly, such as when a famous person died to enter their
   death date and refresh the page.

   They built the product that became Fastly in-house at Wikia to deal
   with their own content delivery issues. It worked so well they decided
   to start a company.

   With $40M in their pockets, Fastly has lots of room to expand. The
   company is currently employs around 100 people, up from 60 at the
   beginning of the year, and have their main offices in San Francisco
   with satellite offices in New York and London.

   Bergman plans to hire more people and continue to grow their worldwide
   markets. He says they already have strong presence in Europe and the
   US, but hope to expand to other markets, particularly Asia and South
   America, but it’s a business that requires a lot of cash to build out
   data centers throughout the world.

   He said one of the reasons the company caught the eye of the funders is
   because its growth trajectory has been going up steadily whether they
   are talking about employees, customers or traffic on the network.

   Customers besides The Guardian include other high profile companies
   such as Twitter, Pinterest, and Shazam among others.

   PHOTO CREDIT: (c) Can Stock Photo
     *
     *
     *
     *
     *
     * submit to reddit

   Advertisement

   Advertisement

CrunchBase

     * Fastly
          + Founded 2011
          +
          + Overview Fastly is changing the way the world experiences the
            Internet. Our flexible, transparent content delivery network
            (CDN) enables businesses to scale their websites, mobile
            applications, and APIs -- without sacrificing performance. At
            Fastly, we think slow is unacceptable. That’s why we built our
            global network for the future, with 10Gb Ethernet, multi-core
            CPUs, and all Solid State Drives (SSDs). …
          + Location San Francisco, California
          + Categories Content, Web Hosting, Content Delivery
          + Founders Artur Bergman
          + Website http://www.fastly.com/
          + Full profile for Fastly

TechCrunch Daily

   Latest headlines delivered to you daily

   Subscribe to TechCrunch Daily

   Enter Email Address ____________________ (BUTTON) Subscribe

Related Videos

     * Personal Stylist Startup Stitch Fix Announces $12 Million in New
       Funding
       Play Video
    Personal Stylist Startup Stitch Fix Announces $12 Million in
       New Funding
       5:22
     * DogVacay CEO Announces $15 Million Funding Round
       Play Video
    DogVacay CEO Announces $15 Million Funding Round
     * Apple's Big Announcement
       Play Video
    Apple’s Big Announcement

   More Related Videos
     * CDN
     * funding
     * fastly
     * Enterprise
     * Popular Posts

   Up Next

Mail.ru Takes Over ‘Russia’s Facebook’ Vkontake In $1.47B Deal, Settles
Durov Suit

   Posted Sep 16, 2014

CrunchBoard

Job Listings

     *

Enterprise Database Manager
       Foundation Center
     *

Programmer
       Foundation Center
     *

Manager/Director of User Growth
       Figure 1
     *

Software Engineer, Search Engine Optimization
       PayScale
     *

Program Manager, Search Engine Optimization
       Payscale

   More from CrunchBoard

   Advertisement

TechCrunch

[crunch-network.jpg?m=1410805882g]

     * News
     * TCTV
     * Events
     * CrunchBase

About

     * Staff
     * Contact Us
     * Advertise With Us
     * Send Us A Tip

International

     * China
     * Europe
     * Japan

Follow TechCrunch

     * Facebook
     * Twitter
     * Google+
     * LinkedIn
     * Youtube
     * Pinterest
     * Tumblr
     * Instagram
     * StumbleUpon
     * Feed

TechCrunch Apps

     * iOS
     * Android
     * Windows 8

Subscribe to TechCrunch Daily

   Latest headlines delivered to you daily

   Subscribe to <span class="no-mobile">Subscribe to </span>TechCrunch
   Daily

   Enter Email Address ____________________ (BUTTON) Subscribe

   © 2013-2014 AOL Inc. All rights reserved. Aol Tech Privacy Policy About
   Our Ads Anti Harassment Policy Terms of Service
   Powered by WordPress.com VIP
   Fonts by <Webtype>

   [b?c1=2&c2=6036210&c3=&c4=&c5=&c6=&c15=&cv=1.3&cj=1]

   Follow

Follow “TechCrunch”

   Get every new post delivered to your Inbox.

   Join 93,047 other followers

   Enter your email add

   Sign me up
   Powered by WordPress.com
