     * Insider Shop
     * Insight Community
     * Step2
     * Search Techdirt_ Search

   Techdirt Techdirt
     * Sign In
     * Register
     * Preferences

     * Techdirt
     * Wireless News
     * Innovation
     * Case Studies
     * Startups
     * Net Neutrality

     * Main
     * Submit a Story
     * rss RSS

   Behind The Veil Part 3: Comcast Rep Confirms... >>
   << The Copyright Folly: Making A Living As A...
     tdicon

   Copyright

   by Glyn Moody

   Tue, Aug 12th 2014 11:03am
   Techdirt recently wrote about Spain's imminent and almost unbelievably
   foolish new copyright law designed to prop up old and failing business
   models in the publishing sector. Mike mentioned that...

   Filed Under:
   copyright, digital commons, google news, google tax, inalienable right,
   open access, snippets, spain

   Companies:
   google

   Permalink.

Spain's Ill-Conceived 'Google Tax' Law Likely To Cause Immense Damage To
Digital Commons And Open Access

from the digital-cluelessness dept

   Techdirt recently wrote about Spain's imminent and almost unbelievably
   foolish new copyright law designed to prop up old and failing business
   models in the publishing sector. Mike mentioned that it was potentially
   disastrous for things like fair use, Creative Commons and public domain
   material -- so broad is the reach of this new law's "inalienable right"
   for publishers to be paid when snippets of works appear elsewhere. Now
   Paul Keller has put together a great post on Communia's blog exploring
   the details of this particular threat:

     The law creates a right for 'electronic content aggregation
     providers' to use 'non-significant fragments of aggregated content
     which are disclosed in periodic publications or on websites which
     are regularly updated' without the permission of the rights holder.
     However such uses require payment of a 'fair remuneration' to the
     rights holder (via a collecting society). This is a right that
     content providers already have and can choose to license or waive
     assuming the non-significant fragments are copyrightable and absent
     an applicable exception or limitation. What this new legislation
     does is eliminate the ability of providers to choose how to exercise
     this right, and impose a mandatory royalty on reusers even for
     content that has been made available under a public license such as
     Creative Commons or that is otherwise available under an exception
     to copyright or in the public domain.

   It's that last fact -- that the mandatory royalty can't be turned off,
   even for works released under Creative Commons licenses that are
   explicitly designed to encourage payment-free sharing -- which is so
   disturbing. It threatens to undermine not only Creative Commons
   licenses by negating one of their key features, but also the central
   feature of a digital commons -- that anyone can draw upon it freely in
   order to create new works that are then returned to an enriched commons
   for the benefit of all.
   I can't believe even the Spanish legislators who put together this
   misguided law really intended this attack on the Creative Commons
   world, but that simply suggests they are largely clueless about how the
   digital world and its commons operate. That's confirmed by another post
   on this topic, this time from Renata Avila, writing for Global Voices.
   She explores the likely impact of this new law on another
   uniquely-digital phenomenon -- open access publishing:

     The current reform of Spain's copyright law incorporates a new levy
     on universities that is related to open access to publications.
     Under the policy, universities that want to share research or other
     content for free will be prohibited from doing so beyond the
     confines of their institution and personnel. In other words, if you
     are an author from a university and you want to share beyond the
     academic world and someone links to your journal article, that
     person must pay even if you do not even want the payment. A
     percentage of these fees will be collected by the Spanish agency
     CEDRO (Centro Español de Derechos Reprográficos) and the virtual
     campuses of universities will be required to comply.

   The new law's provisions thus negate the whole point of open access,
   which is to facilitate the free sharing of academic materials on a
   global scale so as to accelerate research and its benefits.
   That's naturally a tragedy for the researchers who want to share their
   work so that others can build on it, but it's also a tragedy for
   Spanish society. If this law is passed, it means two of greatest
   benefits arising from the widespread use of the Internet -- the
   creation of a digital commons that can be shared by all, and the wider
   dissemination of knowledge thanks to open access -- will be seriously
   harmed. As a consequence, gifted entrepreneurs and academics in Spain
   are likely to move to other countries with a greater understanding of
   these matters, helping to drive innovation and intellectual discovery
   there instead, while Spain may well find itself turning into a digital
   backwater.
   Follow me @glynmoody on Twitter or identi.ca, and on Google+
   21 Comments | Leave a Comment
   If you liked this post, you may also be interested in...
     * Jimi Hendrix Biopic Opens Today... Without Any Jimi Hendrix Music,
       Thanks To Copyright
     * Awful Spanish Copyright Law May Be Stalled Waiting For EU Court
       Ruling On Plans To Change Spain's Copyright Levy System
     * Revealed: How To Get The IFPI To Issue Bogus DMCA Takedowns On Just
       About Anything, With No Questions Asked And No Review
     * FUD: Former FBI Guy Lies, Claiming New Mobile Encryption Would Have
       Resulted In Dead Kidnap Subject
     * Law Enforcement Freaks Out Over Apple & Google's Decision To
       Encrypt Phone Info By Default

Reader Comments (rss)

   (Flattened / Threaded)
    1.
       identicon
       Michael, Aug 12th, 2014 @ 11:09am
       Don't attack a windmill unless you know what to do when it falls
       your way.

       [ reply to this | link to this | view in thread ]
    2.
       identicon
       Anonymous Coward, Aug 12th, 2014 @ 11:25am
       Assuming the law covers user-submitted content as well as that
       which is posted (manually or automatically) by a website's
       operators, this will hurt not only Google and academia, but also
       Spanish citizens themselves who will no longer be able to comment
       on news by citing relevant portions of an article.
       If the Spanish people have any sense at all, they will soon rid
       themselves of the idiots who voted for this bullshit.

       [ reply to this | link to this | view in thread ]
    3.
       icon
       ChurchHatesTucker (profile), Aug 12th, 2014 @ 11:38am

Don't cave again, Google
       The best thing for everyone (outside of Spain, temporarily) is to
       let this play out.

       [ reply to this | link to this | view in thread ]
    4.
       icon
       Gracey (profile), Aug 12th, 2014 @ 11:54am
       Sooooo, when does Spain disappear from the internet?

       [ reply to this | link to this | view in thread ]
    5.
       identicon
       Almost Anonymous, Aug 12th, 2014 @ 12:03pm

Re:
       Yes, exactly. Let Google and two or three other "aggregators" make
       the decision to turn off their Spain operations, observe the howls
       of anguish and protest from Spain's citizens, then watch Spain's
       legislators race back to the table and strike this foolish law.

       [ reply to this | link to this | view in thread ]
    6.
       identicon
       David, Aug 12th, 2014 @ 12:03pm

Re:
       Embrace the windfall.
       That would appear to be the idea.

       [ reply to this | link to this | view in thread ]
    7.
       identicon
       Anonymous Coward, Aug 12th, 2014 @ 12:04pm
       it seems reasonable to assume that the entertainment and publishing
       industries have been prominent in getting this bill to the point of
       becoming law. this is the problem when any and all amounts and
       lobbying can be used to force something through. the politicians
       involved aren't interested because they have received their
       envelopes and will get favoritism anyway.

       [ reply to this | link to this | view in thread ]
    8.
       identicon
       Anonymous Coward, Aug 12th, 2014 @ 12:15pm
       As I've said before, copyright isn't a spectrum ranging from
       abolition at one end through minimalism and on to maximalism at the
       other end, it's more like a moebius strip where copyright
       maximalism actually results in creators having less rights. Under
       this law, the right of creators to charge what they want is being
       abridged. It's ironic and hypocritical in the extreme and it's
       probably the result of these people not so much believing in the
       rights of creators to control copies of their work as believing in
       the maximization of profit.

       [ reply to this | link to this | view in thread ]
    9.
       identicon
       John Cressman, Aug 12th, 2014 @ 12:38pm

Fools...
       Yah... the Spanish politicians are about as clueless as they
       come... possibly only exceeded by the French.
       But hey... you elect fools, you get foolish laws.
       Now the Russians, at least you know where they are coming from.
       They want COMPLETE CONTROL of EVERYTHING.

       [ reply to this | link to this | view in thread ]
   10.
       identicon
       Anonymous Coward, Aug 12th, 2014 @ 1:27pm
       This just seems like a freakishly weird thing to legislate.

       [ reply to this | link to this | view in thread ]
   11.
       identicon
       Zootcast, Aug 12th, 2014 @ 2:20pm

Tax madness
       Oh my gosh, this goes far beyond the recent law approved in Italy,
       virtually dictated to the government by the SIAE (the equivalent of
       the CEDRO Spanish agency), which estabilishes a tax even heavier
       than the current as a "fair compensation" due for private copying.
       A deal worth 150 million euros per year. I'm only glad that our
       "politicians" did not think first of this madness...

       [ reply to this | link to this | view in thread ]
   12.
       identicon
       Anonymous Coward, Aug 12th, 2014 @ 5:39pm
       "...(via a collecting society)..." meaning the greedy bloody middle
       men who will no doubt take their cut, most likely a major portion
       of that payment before passing on whatever is left to the holder.
       Greed by any other name.
       In this case the Spanish lawmakers are idiots for this piece of
       crap.

       [ reply to this | link to this | view in thread ]
   13.
       icon
       techflaws (profile), Aug 12th, 2014 @ 10:26pm

Re: Re:
       Unfortunately, as we've seen in the fight over the German
       Leistungsschutzrecht, Google - despite all its money - just hasn't
       the balls to take the necessary radical steps.

       [ reply to this | link to this | view in thread ]
   14.
       icon
       Seegras (profile), Aug 12th, 2014 @ 11:30pm

A Ban on Scientific discourse
       This is nothing less than a ban on scientific discourse, and also,
       a ban on participation in open source projects.
       Plus of course, it's a license to kill the public domain. Everyone
       can just republish something either under the public domain or
       under a free license and gets a new right on it.

       [ reply to this | link to this | view in thread ]
   15.
       identicon
       Anonymous Coward, Aug 13th, 2014 @ 12:00am

Re:
       As far as U can tell, the collecting agencies take their cut and
       pass the remainder onto the labels who take their cut and the
       charge the artists for the administrative overheads, which are
       always more then the amount they receive
       /Hollywood and label accounting 101.

       [ reply to this | link to this | view in thread ]
   16.
       identicon
       Anonymous Coward, Aug 13th, 2014 @ 4:47am

Conflicting rights
       I often see this paradox when others claim something is a moral
       right. For example, artist resale royalties are often legislated as
       "inalienable" rights, to "protect" the artist from the temptation
       of selling his future interest in resale royalties while he is poor
       and "vulnerable". Making that right "inalienable" however, means
       that the artist cannot exercise his right to donate his works
       "without strings attached". So what does this mean? Obviously, both
       rights cannot simultaneously be moral rights, because they are
       mutually exclusive.
       One person's "moral" rights are another's arbitrary rights.

       [ reply to this | link to this | view in thread ]
   17.
       icon
       ahow628 (profile), Aug 13th, 2014 @ 6:35am

Not too worried
       I wouldn't worry too much about this. Spain has some pretty onerous
       laws but their enforcement is minimal to non-existent. This one is
       going to fall by the wayside very quickly.

       [ reply to this | link to this | view in thread ]
   18.
       identicon
       Sierra Padre, Aug 13th, 2014 @ 9:46am

Re: sense (non variety)
       Sense? We don't need no stinking sense!

       [ reply to this | link to this | view in thread ]
   19.
       identicon
       john walker, Aug 13th, 2014 @ 4:17pm

Re: Conflicting rights
       The resale royalty proposed for the US, would be transferable (but
       not extinguishable) . It is a certainty that many artists will
       agree to transfer the 'right' to the purchaser of the artwork, in
       return for a better first sale price and therefore when or if that
       art work is eventually resold, the person paying the royalty, would
       be the, 'rightholder'!

       [ reply to this | link to this | view in thread ]
   20.
       icon
       John Fenderson (profile), Aug 14th, 2014 @ 8:55am

Re: Re: Conflicting rights
       None of which makes the idea any better.

       [ reply to this | link to this | view in thread ]
   21.
       identicon
       john walker, Aug 15th, 2014 @ 6:43pm

Re: Re: Re: Conflicting rights
       totally agree

       [ reply to this | link to this | view in thread ]

Add Your Comment

   Have a Techdirt Account? Sign in now. Want one? Register here
   Name    __________________________________________________
   Email   __________________________________________________ [ ] Get
           Techdirt’s Daily Email
   URL     __________________________________________________
   Subject __________________________________________________
   Comment
           this is for spambots, do not use this_______________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________

           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
   Options [ ] Save me a cookie
           Submit Preview
     * Note: A CRLF will be replaced by a break tag (<br>), all other
       allowable HTML will remain intact
     * Allowed HTML Tags: <b> <i> <a> <em> <br> <strong> <blockquote> <hr>
       <tt>

   Close
   Have a Techdirt Account? Sign in now. Want one? Register here
   Name    __________________________________________________
   Email   __________________________________________________ [ ] Get
           Techdirt’s Daily Email
   URL     __________________________________________________
   Subject __________________________________________________
   Comment
           this is for spambots, do not use this_______________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________

           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
           ____________________________________________________________
   Options [ ] Save me a cookie
           Submit Preview
     * Note: A CRLF will be replaced by a break tag (<br>), all other
       allowable HTML will remain intact
     * Allowed HTML Tags: <b> <i> <a> <em> <br> <strong> <blockquote> <hr>
       <tt>

   Behind The Veil Part 3: Comcast Rep Confirms... >>
   << The Copyright Folly: Making A Living As A...
     tdicon
   Follow Techdirt

Techdirt's Daily Email Newsletter

   Enter Your Email Address_ Subscribe
   Advertisement
   Essential Reading

Hot Topics

     * 5.3 Another Story Of A 'Fake' Brilliant Inventor? Is 'Scorpion
       Walter O'Brien' A Real Computer Security Genius?
     * 5.2 FBI Director Angry At Homebuilders For Putting Up Walls That
       Hide Any Crimes Therein
     * 5.1 Funniest/Most Insightful Comments Of The Week At Techdirt
     __________________________________________________________________

New To Techdirt?

   Explore some core concepts:
     * Advertising Is Content; Content Is Advertising
     * How Being More Open, Human And Awesome Can Save Anyone Worried
       About Making Money In Entertainment
     * Infinity Is Your Friend In Economics

   read all »
   Techdirt Reading List
   Amazon.com Widgets
   Techdirt Insider Chat

   Get the Insider Chat!
   Advertisement
   Recent Stories

   Sunday

   12:00 Funniest/Most Insightful Comments Of The Week At Techdirt (3)

   Saturday

   12:00 This Week In Techdirt History: September 20th - 27th (5)
   09:00 Awesome Stuff: Simple And Small Stuff (8)

   Friday

   19:39 Nine Epic Failures Of Regulating Cryptography (41)
   18:11 Apparently The Reason Comcast Has Crappy Customer Service Is
         Because It Was Lacking A 'Customer Experience' VP (25)
   17:00 DailyDirt: That's A Spicy Meatball, But It's Not Italian...? (5)
   15:48 Health Experts Issue Call To Prevent ICANN's Commercialization Of
         New .health Domain Leading To Exclusive Control Of Online Health
         Information (11)
   14:40 Eric Holder Was The Worst Attorney General For The Press In A
         Generation: We Deserve Better (28)
   13:39 Jimi Hendrix Biopic Opens Today... Without Any Jimi Hendrix
         Music, Thanks To Copyright (74)
   12:29 Cameras Watching Cops: Still A Good Idea (25)

More  arrow

   Advertisement

   [td_logov140.png]

Company

   About Us
   Advertising Policies
   Privacy

Contact

   Help & Feedback
   Media Kit
   Sponsor/Advertise
   Submit a Story

Tools & Services

   Twitter
   Facebook
   RSS
   Techdirt for Mobile
   Research & Reports

More

   Insight Community
   Step2
   Insider Shop
   Brought to you by Floor64

   Close

   Email This
     * To Address this is for spambots ____________________
     * Your Name this is for spambots ____________________
     * Your Address this is for spambots ____________________
     * Send It

   [p?c1=2&c2=6036036&cv=2.0&cj=1] Quantcast
