    #TIME » Garry Kasparov: It’s a War, Stupid! Comments Feed Michael
   Sam’s March to NFL History Derailed — but Only for Now EU Sets Russia
   Ultimatum, Threatens Sanctions alternate alternate TIME WordPress.com

   TIME

Time.com

   Subscribe
   Sign In Sign Out
   Home U.S. Politics World Business Tech Health Science Entertainment
   Newsfeed Living Sports History Magazine Ideas
   Money LIFE
   Photography Videos
   Next Generation Leaders Above and Beyond Biz Tech Tips Data Security
   New Energy Reality TIME 100 TIME Explains Top of the World
   Subscribe Newsletters Feedback Privacy Policy Your California Privacy
   Rights Terms of Use Ad Choices Ad Choices
   RSS TIME Apps TIME for Kids Media Kit Advertising Reprints and
   Permissions Site Map Help Customer Service © 2014 Time Inc. All rights
   reserved.
   Subscribe

   (BUTTON) U.S. Edition
     * U.S. Edition
     * Europe, Middle East and Africa Edition
     * Asia Edition
     * South Pacific Edition

   TAP

Pro-Democracy Protesters Swarm Hong Kong, Violent Clashes With Police

Obama Admits U.S. Intelligence Didn’t See ISIS Coming

India’s Modi Comes Full Circle At Madison Square Garden

Julian Assange Speaks in Nantucket — as a Hologram

Jeter Leaves With Hit and 9-5 Win Over Red Sox

Report: Secret Service Bungled White House Shooting Response in 2011

Obama: Ferguson Exposed ‘Gulf of Mistrust’ Between Cops and Communities

   More Ferguson Coverage

Denzel Washington Rules Box Office With The Equalizer

This Curry Spice Might Help the Brain Heal Itself

George Clooney and Amal Alamuddin Get Married in Venice

Police Officer Shot in Ferguson

   More Ferguson Coverage

What Are the 3 Quick and Easy Ways to Boost Self-confidence?

Recovery of Bodies Under Way at Japanese Volcano

‘Contradictory’ Syria Policy Helps Assad

The Simpsons Watch: Heaven, I’m in Jewish Heaven

The Simpsons Kills Off Krusty’s Dad in Season Premiere

The War Against ISIS: Operation Fingers Crossed

Sometimes the Government Puts Money in Our Pockets

See Hong Kong Pro-Democracy Protesters Clash With Police

Eating Scotland’s Favorite Fatty Snack Can Heighten Stroke Risk in Minutes,
Study Finds

Larry Summers: Obama and Clinton Are Very Different Bosses

   SCROLL TO SEE MORE
   Loading
   TIME Opinion foreign affairs

Garry Kasparov: It’s a War, Stupid!

     * Garry Kasparov @Kasparov63

   Aug. 30, 2014
   SHARE
   AP10ThingsToSee- Ukraine A pro-Russian rebel walks in a passage at a
   local market damaged by shelling in the town of Donetsk, eastern
   Ukraine, on Aug. 26, 2014 Mstislav Chernov—AP

This vocabulary of cowardice emanating from Berlin and Washington is as
disgraceful as the black-is-white propaganda produced by Putin’s regime, and
even more dangerous

   As Russian troops and armored columns advance in eastern Ukraine, the
   Ukrainian government begs for aid from the free world it hoped would
   receive it and protect it as one of its own. The leaders of the free
   world, meanwhile, are struggling to find the right terminology to free
   themselves from the moral responsibility to provide that protection.
   Putin’s bloody invasion of a sovereign European nation is an incursion,
   much like Crimea — remember Crimea? — was an “uncontested arrival”
   instead of anschluss. A civilian airliner was blown out of the sky just
   six weeks ago — remember MH17? — and with more than 100 victims still
   unidentified, the outrage has already dissipated into polite
   discussions about whether it should be investigated as a crime, a war
   crime or neither.

More

   Dear Fellow Liberals: I’m Done Apologizing for IsraelThe State
   Department’s Twitter War With ISIS Is Embarrassing'Long Fight': Hong
   Kong Protests Grow, Despite Tear Gas NBC NewsCowboys Stun Saints With
   Offensive Might NBC NewsSearch for Trooper-Slay Suspect Shifts, Booby
   Traps Feared NBC News

   This vocabulary of cowardice emanating from Berlin and Washington today
   is as disgraceful as the black-is-white propaganda produced by Putin’s
   regime, and even more dangerous. Moscow’s smoke screens are hardly
   necessary in the face of so much willful blindness. Putin’s lies are
   obvious and expected. European leaders and the White House are even
   more eager than the Kremlin to pretend this conflict is local and so
   requires nothing more than vague promises from a very safe distance. As
   George Orwell wrote in his 1946 essay on language right before starting
   work on his novel 1984 (surely not a coincidence): “But if thought
   corrupts language, language can also corrupt thought.” The Western
   rhetoric of appeasement creates a self-reinforcing loop of mental and
   moral corruption. Speaking the truth now would mean confessing to many
   months of lies, just as it took years for Western leaders to finally
   admit Putin didn’t belong in the G-7 club of industrialized
   democracies.

Popular Among Subscribers

   General Motors CEO Mary Barra Time Magazine Cover

Mary Barra’s Bumpy Ride at the Wheel of GM

   Subscribe

The Tragic Risks of American Football

Denzel Goes Old Testament

   Ukrainian President Petro Poroshenko just met with U.S. President
   Barack Obama in Washington, but Obama’s subsequent statement showed no
   sign he’s willing to acknowledge reality. Generic wishes about
   “mobilizing the international community” were bad enough six months
   ago. Hearing them repeated as Ukrainian towns fall to Russian troops is
   a parody. (If legitimacy is what Obama is after, Russia is clearly in
   violation of nearly every point of the 1974 U.N. Resolution 3314,
   “definition of aggression.”) Perhaps Poroshenko should have matched
   Obama’s casual wardrobe by wearing a T-shirt that read, “It’s a War,
   Stupid.” As Russian tanks and artillery push back the overmatched
   Ukrainian forces, Obama’s repeated insistence that there is no military
   solution in Ukraine sounds increasingly delusional. There is no time to
   teach a drowning man to swim.

   The U.S., Canada and even Europe have responded to Putin’s aggression,
   it is true, but always a few moves behind, always after the deterrent
   potential of each action had passed. Strong sanctions and a clear
   demonstration of support for Ukrainian territorial integrity (as I
   recommended at the time) would have had real impact when Putin moved on
   Crimea in February and March. A sign that there would be real
   consequences would have split his elites as they pondered the loss of
   their coveted assets in New York City and London.

   Then in April and May, the supply of defensive military weaponry would
   have forestalled the invasion currently under way, or at least raised
   its price considerably — making the Russian public a factor in the
   Kremlin’s decisionmaking process much earlier. Those like me who called
   for such aid at the time were called warmongers, and policymakers again
   sought dialogue with Putin. And yet war has arrived regardless, as it
   always does in the face of weakness.

   As one of the pioneers of the analogy I feel the irony in how it has
   quickly gone from scandal to cliché to compare Putin to Hitler, for
   better and for worse. Certainly Putin’s arrogance and language remind
   us more and more of Hitler’s, as does how well he has been rewarded for
   them. For this he can thank the overabundance of Chamberlains in the
   halls of power today — and there is no Churchill in sight.

   As long as it is easy, as long as Putin moves from victory to victory
   without resistance, he gains more support. He took Crimea with barely a
   shot fired. He flooded eastern Ukraine with agents and weaponry while
   Europe dithered. The oligarchs who might have pressured Putin at the
   start of his Ukrainian adventure are now war criminals with no way
   back. The pressure points now are harder to reach.

   The Russian military commanders, the ones in the field, are not fools.
   They are aware that NATO is watching and could blow them to bits in a
   moment. They rely on Putin’s aura of invincibility, which grows every
   day the West refuses to provide Ukraine with military support. Those
   commanders must be made to understand that they are facing an
   overwhelming force, that their lives are in grave danger, that they can
   and will be captured and prosecuted. To make this a credible threat
   requires immediate military aid, if not yet the “boots on the ground”
   everyone but Putin is so keen to avoid. If NATO nations refuse to send
   lethal aid to Ukraine now it will be yet another green light to Putin.

   Sanctions are still an important tool, and those directly responsible
   for commanding this war, such as Defense Minister Sergei Shoigu must be
   held accountable. Sanctions must also broaden. The chance to limit them
   only to influential individuals and companies is over. The Russian
   people can change Putin’s course but have little incentive to take the
   great risks to do so under current conditions. Only sanctions that
   bring the costs of Putin’s war home can have an impact now. This was
   always a last resort, and it wouldn’t be necessary had the West not
   reacted with such timidity at every step. (The other factor that is
   already dimming the Russian people’s fervor is the Russian military
   casualties the Kremlin propaganda machine is trying so hard to cover
   up.)

   As always when it comes to stopping dictators, with every delay the
   price goes up. Western leaders have protested over the potential costs
   of action Ukraine at every turn only to be faced with the
   well-established historical fact that the real costs of inaction are
   always higher. Now the only options left are risky and difficult, and
   yet they must be tried. The best reason for acting to stop Putin today
   is brutally simple: it will only get harder tomorrow.

   Kasparov is the chairman of the New York City–based Human Rights
   Foundation.
   SHARE THIS ARTICLE
   0
   http://ti.me/Y0CNkS_
   0
     * HOME
     * U.S.
     * POLITICS
     * WORLD
     * BUSINESS
     * TECH
     * HEALTH
     * SCIENCE
     * ENTERTAINMENT
     * NEWSFEED
     * LIVING
     * OPINION
     * SPORTS
     * HISTORY
     * MAGAZINE
     * NEWSLETTERS
     * SITE MAP

   © 2014 Time Inc. All rights reserved. Powered by WordPress.com VIP

   Sign In
   Not a memeber? Sign Up
   Email address or Password is incorrect
   EMAIL
   ____________________
   PASSWORD
   ____________________
   SIGN IN
   [ ] Remember Me
   Forgot Password?

Want the Full Story?

   SUBSCRIBE

   Your browser, Internet Explorer 8 or below, is out of date. It has
   known security flaws and may not display all features of this and other
   websites.
   Learn how to update your browser

   [p?c1=2&c2=6035728&c3=&c4=&c5=&c6=&c15=&cv=2.0&cj=1]
