   #A Blogger and a Father - Atom A Blogger and a Father - RSS A Blogger
   and a Father - Atom publisher

A Blogger and a Father

   Talking about modern fatherhood, and featuring the voices of involved,
   active dads

Tuesday, June 3, 2014

Cancer

   Boom.
   On Friday, 5/30/14, I found out I had a Stage 4 lung cancer. People in
   my condition have about a year to live on average, and treatment is now
   limited to making the next year more bearable. There are other options
   that may be discussed later, including experimental treatments, and I'm
   staying optimistic, but frankly, I think I know where I stand.
   4 years ago, in the summer of 2010, we were at Bethany Beach, and
   everyone was having a great time. Our family and some friends were
   building sand castles, going in and out of the water, and just relaxing
   in general--everyone except anxious old me. I had hundreds of unread
   emails and dozens of ideas for blog posts I didn't have time to write,
   and I was surrounded by too much sand and not enough coffee. I tried to
   pretend I was having a good time, but people could see I was out of my
   comfort zone, and worse, that I didn't want to be there.
   It was only on the drive back home that I had the epiphany. It was only
   on the drive back that I realized what I had been missing out on. It
   was only on the drive back that I realized I had been experiencing the
   biggest tragedy of human existence: I was having the time of my life,
   and I didn't even know it.
   That was a good day, since once you make that decision, man... You're
   in Heaven every single second of your life. And it went on and on, and
   things only got better, because I made a conscious decision one summer
   day, on the drive home from Bethany Beach, and was able to repeat that
   decision subconsciously from that moment on. It made the difference
   between a living Hell, where I was always behind, always unhappy, and
   always unfulfilled--always a step behind on my writing, my relationship
   with my wife, with my friends, and with my kids, and a living Heaven,
   where even if I had wanted more out of life, I also knew I had it all.
   I believe in Heaven on Earth, and I believe it's found anywhere you
   seek it. Here's where I found it:
   I found Heaven on long car rides with the kids. I could have felt bad
   about having to drive my kids back and forth to school for hours every
   day, but instead, I used those car trips to chat with my kids about
   their worlds and about mine, to introduce them to music, and to make up
   music with them, to talk about values as well as about nonsense.
   And I found Heaven on the dirty floor of a basketball court. My then
   2-year-old daughter used to finish the JCC preschool at 12, so we were
   stuck for hours, waiting for her brother to finish school before we
   could head back home. And those days of waiting with my girl will be
   remembered forever by me and hopefully by her. For 4 hours, we sat
   around and we shared lunch, and we went to a playroom at the JCC, where
   she made me plastic sandwiches and tea, and we raced to the basketball
   court and played basketball, which meant she was leading the parade of
   two by only stepping on the black line, and I was behind her,
   dribbling. She made up that game, calling it "Going to the birthday
   party." Then we would sit down on the floor in front of each other,
   spread our legs, and roll the ball to each other. Then she wanted to
   hug, so we hugged on the floor of the basketball court while people
   played around us.
   Even Heaven on Earth includes some caveats. We moved to a new house in
   March. It's a beautiful house. It's a dream house. It's the house where
   my kids will grow up, and it breaks my heart. I don't care about
   myself, I really don't. I've had the most amazing life anyone could
   ever wish to have, but there's one thing... There's one thing I would
   give anything for: watching my kids grow up.
   I've raised happy kids. Sure, they sometimes whine, but in general,
   they're happy. They're my masterpiece: two loving, smart, intelligent,
   funny, happy kids. And I can't let that end. I can't allow them to grow
   up sad. I can't allow them to grow up with a hole in their hearts in
   the shape of the dad they barely remember. I want them to be happy. I
   want to be around to make them happy.
   And I want my wife to be happy. She deserves to be happy. I wish I
   could make her happy right now.
   So acceptance, and sadness--well, I believe they can coexist. Sadness
   is inevitable--I'm only human, and trying too hard to rise above it
   only hurts more. But I do accept. I accept that life is finite, and I
   accept that my time will come soon. I accept that my life had been and
   still is a gift, and I accept the likely possibility that I won't see
   my kids grow older.
   Should I complain, though? Should I cry out to the empty sky and say,
   "Why me?" Or should I feel that now, even now, especially now, a little
   confused, a little tired, and a little sad, I'm having the time of my
   life?
   Whatever happens to my body in the next few months is still relatively
   unknown. Here's what we do know, though:
   We know I'm the luckiest sonofabitch who's ever walked this earth, and
   we know I will be loved until my last moment by people it has been my
   utmost privilege to know: by a wife I adore and two kids I'm in awe of
   every single moment.
   Just let me make this request of you.
   My girl--she's a shy one. You'll see her play by herself sometimes, and
   you'll be tempted to step back and say, "She plays so nicely by
   herself!" Go to her. Play with her. She needs you.
   My boy--he's so freakin' sensitive. Everything you say will be
   remembered by him and analyzed for months in that genius head of his.
   Don't joke with him just to make yourself smile--you'll ruin him.
   Answer every question he has, or at least direct him to a place with
   answers. He likes to play and he likes to fool around, but you need to
   treat him like a grown up. He's smarter than I am, and he's probably
   smarter than you are.
   And my wife--just give her a break. Please, allow her to take a break.
   She's a type-A personality at work, but at home she's always just
   wanted to relax and have fun. Help her have fun. She'll want to take
   all the responsibilities over everything herself--don't let her. Tell
   her to relax. Tell her to take it easy. Help her enjoy life. And don't
   label her or limit her in any way. Don't use the W- word with her.
   She's not that word. She's not an easy simplification. You know who she
   is? She's the daughter any parent could wish for, and the mother any
   kid would long to have. Although I've stayed home and took a great
   share of the credit for raising these amazing kids, nothing could have
   been done without her. And she'll continue to raise them, and they will
   continue to grow and be even more amazing teens and adults because of
   their mother.
   And she's the woman of my dreams.
     __________________________________________________________________

   Share

324 comments:

    1. [anon36.png]
       Mike ReynoldsJune 3, 2014 at 10:00 AM
       Take care Oren. We're thinking of you and I have two little girls
       who are always on the lookout for friends to play with. You're an
       inspiration man and I'm glad I know you.
       ReplyDelete
    2. [anon36.png]
       MikeJune 3, 2014 at 10:11 AM
       This was the most beautiful, thoughtful thing I've read in a long,
       long time -- a masterpiece. Sending you my very best and wishing
       you many, many days in your perfect heaven on earth. Big hugs at
       you.
       ReplyDelete
    3. [anon36.png]
       Robert DufferJune 3, 2014 at 10:11 AM
       Boom is right. This image crystalizes what you're urging, what now
       means. Such sweet liberation to embrace now. Thanks, Oren.
       ReplyDelete
    4. [anon36.png]
       Robert DufferJune 3, 2014 at 10:15 AM
       Why didn't image load? I try again
       ReplyDelete
    5. [anon36.png]
       Alissa | CleverCompass.comJune 3, 2014 at 10:15 AM
       Thinking of you and your family at this tough time. Your wife and
       children are so lucky to have you in their lives for all the time
       you have to share with them.
       ReplyDelete
    6. [anon36.png]
       OneGoodDadJune 3, 2014 at 10:15 AM
       Owen, I wish I lived down the street from you. I wish I could give
       you a hug and let our kids play together. I think they're about the
       same age. Thank you for all you've done for the dad blogging world.
       ReplyDelete
    7. [anon36.png]
       Kenny BodanisJune 3, 2014 at 10:17 AM
       Thank you for this. Thank you for you.
       ReplyDelete
    8. [anon36.png]
       jimhigleyJune 3, 2014 at 10:17 AM
       Oren - once again, you have shown all of us the path. Here's to
       every bit of Heaven we all chose to embrace right here on Earth.
       Yours, mine, all of ours.
       ReplyDelete
    9. [anon36.png]
       Jay - Dude of the HouseJune 3, 2014 at 10:19 AM
       Oren, since I met you virtually severaly years ago I've wondered
       what the title of your blog, A Blogger and a Father, really meant.
       This explains it beyond perfectly. Thank you for sharing it with
       us.
       ReplyDelete
   10. [anon36.png]
       Cynthia @ You Signed Up For WhJune 3, 2014 at 10:20 AM
       This is beautifully written and my heart is with you and your
       family.
       ReplyDelete
   11. [anon36.png]
       DiarydadJune 3, 2014 at 10:22 AM
       Beautiful words, and beyond them thank you for bringing so many of
       us together to share our stories of fatherhood. I'll have you and
       your family in my thoughts. Here's to the heaven you have and the
       heaven you'll know.
       ReplyDelete
   12. [anon36.png]
       Seamus Curtain-MageeJune 3, 2014 at 10:24 AM
       Brave and beautiful Oren. Whatever the journey holds for you with a
       spirit like this you'll march through with strength and love, all
       the while reminding us to pay attention to our own little slices of
       heaven.
       ReplyDelete
   13. [anon36.png]
       THE Diaper DadJune 3, 2014 at 10:25 AM
       You handle adversity with an aplomb and grace that few people can
       muster in times of good. You, sir, are now, and will always be an
       inspiration and a driving force in all things 'good dad' related.
       Thank you for the reminder that, no matter where we are, no matter
       what's going on, Heaven is all around us, but it's up to us to
       reach out and grab it. Thank you for that.
       ReplyDelete
   14. [anon36.png]
       WhitJune 3, 2014 at 10:26 AM
       Sending you and yours lots of love, Oren.
       ReplyDelete
   15. [anon36.png]
       DaDa Rocks!June 3, 2014 at 10:26 AM
       Oren this brought tears to my eyes. I hope whatever time you have
       left is heaven on earth for you. If there is anything I can do. Or
       we can do as a community please ask.
       ReplyDelete
   16. [anon36.png]
       Jeff StephensJune 3, 2014 at 10:28 AM
       Wishing you the best. Stay as strong as possible. Know that your
       words will forever fill their hearts by the inspirational work
       you've done here. You are an inspiration to all dads my friend.
       ReplyDelete
   17. [anon36.png]
       The JackBJune 3, 2014 at 10:31 AM
       Oren, you are a thoughtful guy and I appreciate that. If I am not
       mistaken, Hebrew is your first language so I am always impressed
       with how well you write in English because you do a fine job of
       expressing yourself and touching the nuances of the language.
       Time is fleeting and whatever we get is finite but I can promise
       you that whatever path you are on you are not walking it alone
       because you are a mensch and you touched lives.
       Not everyone can say that, it is worth a lot. רפואה שלמה
       ReplyDelete
   18. [anon36.png]
       DaddysinchargeJune 3, 2014 at 10:31 AM
       Much love to you and the family. Thank you for this.
       ReplyDelete
   19. [anon36.png]
       Trudi GalblumJune 3, 2014 at 10:40 AM
       Oren - Remember me? Larry's wife, Caite's mom? It's hard, even 12
       years later. I think about Larry every day. But I'm okay and my
       kids are too. You obviously have so many people who love you
       sharing the journey.
       ReplyDelete
   20. [anon36.png]
       Chris BernholdtJune 3, 2014 at 10:41 AM
       So amazing and thank you for the reminder that things don't have to
       be a spectacle to be extraordinary. We will keep you in our
       thoughts and prayers.
       ReplyDelete
   21. [anon36.png]
       ihopeiwinatoasterJune 3, 2014 at 10:46 AM
       You are so beloved, Oren. The words men write are windows into
       their very souls and the brightness that shines from your window is
       blinding and everlasting. May God's love rain down on you.
       ReplyDelete
   22. [anon36.png]
       Johnny T (That's ME!)June 3, 2014 at 10:47 AM
       Oren, I know there are no right words to say here. There is nothing
       I can say that will make anything any better or change any of the
       facts surrounding this. Our stories differ quite a bit when it
       comes to cancer. I cannot say I relate, though I can say I
       understand the fear and the defining moment when one must accept
       the finite reality of life.
       I cannot put into words what this post has done for me this
       morning. What emotions and thoughts ran through my mind as tears
       flowed down my face. I can say that I could only aspire to be a
       fraction of the man you are, and if I achieved that, I would be
       exponentially a better person than I am at this moment.
       I've never stood in your presence. I've never shaken your hand,
       given you a bro hug, or bought you a drink. But Oren, none of that
       matters when I look at the impact you have had in my life, and the
       lives of so many others who have never stood in your presence. You
       are loved because you are. You are treasured because you are. And
       we are because you are.
       ReplyDelete
   23. [anon36.png]
       Josh MisnerJune 3, 2014 at 10:47 AM
       I'm bawling in the coffee stand drive through as I write this. It
       is a profound thing to realize what you did before the news,
       because far too many don't get it until it's too late. Here's to
       savoring every moment you have left. Let us know if we can help in
       any way.
       ReplyDelete
   24. [anon36.png]
       Mary JohnsonJune 3, 2014 at 10:52 AM
       My dad died of lung cancer when I was a freshman in high school.
       Your children and wife are so lucky that you had your epiphany not
       only when you did but that you are making a conscious effort not to
       be selfish now. It will mean the world to them later.
       ReplyDelete
   25. [anon36.png]
       Scary MommyJune 3, 2014 at 10:53 AM
       Oh, Oren, I don't even know what to say, but I am so glad you had
       that moment on the ride home. Your family is so blessed to have
       you.
       ReplyDelete
   26. [anon36.png]
       DadOnTheRunJune 3, 2014 at 10:57 AM
       I am absolutely impressed with your acceptance of a nightmarish
       situation, I'm even more impressed with your optimism. People make
       mincemeat of these predictions often and I feel that you are great
       a candidate for such a triumph. I'm happy to know you, I'm
       privileged to have met you and I just know it won't be the only
       time. I will say this: No matter what happens, I am your friend. I
       will be any kind of friend that you need. Any kind of friend that
       your family needs and I hope you know that you have one supreme
       council of dads who care about you all. Live life, write when you
       can without pressure but with the understanding that the words we
       put to paper can go on forever. Thank you for moving and refocusing
       me this morning as you have on occasions before. You make us all
       want to be better men, better husbands, better fathers. Power and
       peace to you, Oren.
       ReplyDelete
   27. [anon36.png]
       Marty ColemanJune 3, 2014 at 11:05 AM
       Thanks Oren for helping us all to see not just what is important
       now but into the future. Your children will one day face their end,
       young or old, and they will have the memory and the oral story
       telling of how their father was when it appeared he might be at his
       end. But more importantly they will see and hear about your
       epiphany in living as well. They will follow your lead in their
       time of living into the future, when they are adults, as well. Your
       work and your love will last a long, long time.
       ReplyDelete
   28. [anon36.png]
       John KinnearJune 3, 2014 at 11:06 AM
       Beautiful words. Thinking of you, man. All my love and thoughts and
       prayers are with you and your family.
       ReplyDelete
   29. [anon36.png]
       DfilesJune 3, 2014 at 11:07 AM
       I'm amazed but completely not surprised at the grace with which
       you're dealing with this nightmare, Oren. And I know throughout
       this ordeal you'll somehow manage to be there for your family and
       somehow put an unspeakable tragedy into beautiful words for the
       rest of us. And that, my friend, is the sign of a masterpiece in
       and of itself.
       Your family is lucky to have you and I'm lucky to know you and
       count you as a friend. I understand the future looks grim, but it's
       a future you won't face alone. And that's got to count for
       something.
       We love you Oren.
       ReplyDelete
   30. [anon36.png]
       FadraNJune 3, 2014 at 11:07 AM
       I don't know what to say. I just don't. Usually I can add something
       witty or turn your post back around to me and talk about how I can
       relate. I feel like anything I say right now will sound trite or
       even worse, make you feel bad. I guess I just can't even get my
       head around this and I'm so sorry for what is to come - sorry for
       your wife and kids and more importantly, sorry for you. You have a
       selfless love that makes it even more difficult to think about
       leaving. No matter how pointless it may seem, I'm still going to
       pray for a miracle for you, in whatever form it chooses to take
       shape.
       ReplyDelete
   31. [anon36.png]
       Caitlin KennedyJune 3, 2014 at 11:12 AM
       Oren, this is beautiful - simple, true, and moving us all to think
       about our own heavens on earth. Thank you for opening up my heart
       on this Tuesday morning.
       ReplyDelete
   32. [anon36.png]
       Fruits and NutsJune 3, 2014 at 11:14 AM
       I wish I had words to make it better. I will never understand this
       cancer thing. The world is a better place with you in it. Sending
       positive vibes and good luck from Potatoland.
       ReplyDelete
   33. [anon36.png]
       Chris ReadJune 3, 2014 at 11:23 AM
       I love you, man. You have taken a scattered group of dads and given
       them a place to grow into even more amazing fathers. Your
       contributions to this community are beyond words.
       ReplyDelete
   34. [anon36.png]
       dadofdivasJune 3, 2014 at 11:32 AM
       Oren, thank you for sharing these beautiful words and know that all
       of us are behind you. I echo Chris' sentiments saying thank you for
       bringing together a rag tag group of dads into a thriving
       community. Know that you are in my family and my thoughts and
       prayers
       ReplyDelete
   35. [anon36.png]
       RaquelJune 3, 2014 at 11:36 AM
       Oren, These words are beautiful and please know that you have been
       in my every waking thought for the last week. I want to Thank You
       for this post. For helping me have the epiphany. For helping
       recognize what is important. Love and hugs, Raquel
       ReplyDelete
   36. [anon36.png]
       John EdenJune 3, 2014 at 11:38 AM
       Amazing courage. Powerful piece of writing.
       ReplyDelete
   37. [anon36.png]
       Russ JonesJune 3, 2014 at 11:38 AM
       Thanks for this post, Oren. I wish you all manner of inner
       gladiator over the next few months as you take on this battle. You
       deserve better than this.
       ReplyDelete
   38. [anon36.png]
       Seattledad1June 3, 2014 at 11:40 AM
       Amazingly beautiful post Oren, given the circumstances. We've all
       been privileged to have you as part of our lives and I will be
       holding out hope for you. in the meantime, I will continue to learn
       from your grace, dignity, and love for your family. And perhaps I
       won't be as worried about the unread emails either.
       ReplyDelete
   39. [anon36.png]
       michael from dadcationJune 3, 2014 at 11:44 AM
       So glad to hear from you again...just wish the underlying news
       you're communicating were happier. I love your perspective and
       gratitude; I'm not sure I could be that mature were I in your shoes
       right now.
       ReplyDelete
   40. [anon36.png]
       NoahJune 3, 2014 at 11:46 AM
       Thank you for sharing this. Thank you.
       ReplyDelete
   41. [anon36.png]
       AngadJune 3, 2014 at 11:46 AM
       I am new to this blog, and I am sorry to hear about the Cancer.
       Please stay strong, and happy. Everything always works out in the
       end. Thank you for your words, and for making other dads think.
       ReplyDelete
   42. [anon36.png]
       CatherineJune 3, 2014 at 11:47 AM
       Beautiful post. Much love to you and your family, Oren.
       ReplyDelete
   43. [anon36.png]
       Creed AnthonyJune 3, 2014 at 11:51 AM
       I love you for your words, actions, and character. Thank you for
       sharing. You got many things right, but probably the biggest is
       that you will be loved very moment of your life. Sending you
       thoughts, prayers, and love, brother.
       ReplyDelete
   44. [anon36.png]
       Martin FitzgeraldJune 3, 2014 at 11:56 AM
       I really don't know what to say. I've been reading you in various
       guises for 6, maybe 7 years. I'm sorry, I'm in awe, I'm grateful,
       and god only knows what else.
       I've typed and backspaced a dozen times now so I'll leave it at
       that.
       ReplyDelete
   45. [anon36.png]
       Leigh AnnJune 3, 2014 at 12:05 PM
       I'm thinking of you and your family. Thank you for sharing.
       ReplyDelete
   46. [anon36.png]
       Beth RoseJune 3, 2014 at 12:07 PM
       Heartfelt. Powerful. Unbelievably moving.
       Stay strong and as positive as you can given what you are going
       through.
       You are a tough, strong (yet gentle) man.
       xo
       ReplyDelete
   47. [anon36.png]
       Andrea LoveJune 3, 2014 at 12:09 PM
       I have read this many times with anguish and tears. I wish I had
       some words of wisdom but alas I do not. I can't add to what has
       already been said. Just know your words have touched my heart and I
       will try being inthe moment with my family and friends. You and
       your beautiful family will be in my thoughts often even though we
       are far away. My hope for you Oren is this that you find peace and
       comfort with your loved ones. Your Philly family is on your side
       ReplyDelete
   48. [anon36.png]
       Katherine WilliamsonJune 3, 2014 at 12:09 PM
       I came here through Kevin McKeever and I just want to wish you and
       your family the best. I will keep you guys in my thoughts.
       ReplyDelete
   49. [anon36.png]
       Danielle SmithJune 3, 2014 at 12:24 PM
       So truly beautiful. Your wife, your small people.... they are
       incredibly lucky to have a husband and father with such
       perspective, such strength and wisdom. I wish I had words that
       could make ANY of this an ounce easier, but you and your family
       will be in my thoughts. I will be wishing you continue to have the
       time of your life.
       ReplyDelete
   50. [anon36.png]
       Christopher J. TuckerJune 3, 2014 at 12:31 PM
       Man. Oren, I hardly know what to say. I was staying hopeful that
       your prognosis would be a bit better. I'm genuinely crestfallen. I
       appreciate you and your outlook on life more than I know how to
       say.
       This is a wonderful post, and I will be following your journey.
       Your family is just as blessed to have you as you are to have them.
       With sincere gratitude, respect, and adoration,
       Chris
       ReplyDelete
   51. [anon36.png]
       Christopher J. TuckerJune 3, 2014 at 12:33 PM
       F*ck, yeah, John. ^^^this^^^
       ReplyDelete
   52. [anon36.png]
       Katie BrownJune 3, 2014 at 12:33 PM
       There IS hope and help for people diagnosed with lung cancer. Visit
       www.lungevity.org to learn more. You can also request a support
       mentor to connect with a stage 4 long term survivor for support.
       There is also a Survivor Resource Center that helps navigate people
       from the moment of diagnosis to life after treatment. Best Hopes,
       Katie Brown, Director of Support and Advocacy
       ReplyDelete
   53. [anon36.png]
       Alex MusticoJune 3, 2014 at 12:38 PM
       Oren, I've never met you in person and only know you through
       various Facebook groups. But, I just wanted you to know how much
       this post meant to me. As a fellow SAHD, I'm guilty of sweating the
       small things at times. Your post really helped me put into
       perspective what's really important in life. Needless to say I
       hugged my daughter just a little tighter when I just put her to
       sleep. I want you to know myself and all the other Philly Dads will
       be pulling for you! Love to you and your family!
       ReplyDelete
   54. [anon36.png]
       Jennifer HallJune 3, 2014 at 12:38 PM
       I am so sorry for your diagnosis. You sound a lot like my husband,
       though. He is a type 1 diabetic on dialysis with heart disease. His
       heart has stopped several times. I thought we were going to lose
       him in 2010 and again in 2012. I'm frankly surprised almost every
       day that he's still with us. He thinks a lot about dying and he too
       hates the idea of leaving our kids. I tell him I will love them
       enough for the both of us, but while he's still here, he tries to
       live just like you are. God bless you.
       ReplyDelete
   55. [anon36.png]
       neal callJune 3, 2014 at 12:42 PM
       Oren, figuring out how to find good in the midst of the bad is
       probably the most important thing anyone can do. I'm not so great
       at it myself; but if there's one thing I'd want to instill in my
       daughter, it'd be that ability. You're a good man, Oren, and I
       think your kids are going to see that quality in you, and they're
       gonna be able to make the world a better place because of it.
       You're not at the end of your road, yet, though, dude. Keep on
       truckin'. And keep on finding those good moments.
       ReplyDelete
   56. [anon36.png]
       Didactic PirateJune 3, 2014 at 12:46 PM
       Every good thought and hopeful prayer I have is going straight to
       you and your family, Oren.
       ReplyDelete
   57. [anon36.png]
       Ryan E. HamiltonJune 3, 2014 at 12:50 PM
       Well done, Oren Miller. Continue having the time of your life,
       inspiring us all, and making the world a better place. I often take
       stock of what you have done in this world, and it is massive,
       momentous, meaningful. You are a true inspiration. The lasting
       effects of your works are immortal. We love you, man.
       ReplyDelete
   58. [anon36.png]
       Cormac McCannJune 3, 2014 at 12:51 PM
       I find this both a difficult and an inspiring post. You are lucky
       in that you have such a loving family and has your epiphany,
       finding peace with my kids is challenging but you have inspired me
       to make more of an effort to enjoy the preset with them in what
       ever time we have.
       You and your family are in my prayers, and i hope you find peace
       and comfort.
       ReplyDelete
   59. [anon36.png]
       Hilary RatnerJune 3, 2014 at 12:58 PM
       Oren, beautiful post. Sending positive thoughts your way...
       ReplyDelete
   60. [anon36.png]
       iansmithdahlJune 3, 2014 at 12:59 PM
       Thank you so much for taking the time to share this with us, a
       total group of strangers. I know you have a lot going on right now,
       and you're probably very rightly focusing inward and on your
       family. But you took the time to broadcast something very personal,
       in the hopes that it would help a stranger. I wanted to let you
       know that it has. You hit me very deep in my heart, and I won't
       quickly forget what you're trying to teach me, if I ever do. Just
       now, even while I was typing this, my older son said, "Hey dad".
       He's home sick on his birthday, opening presents and playing with
       them while coughing. I think if I hadn't read this, I would have
       said, "Hold on a minute," to finish typing a comment on a random
       blog. But, this time, choking back some tears, I said, "What's up,
       buddy?" and helped him find a random doohickey for his new Ninja
       Turtles toy. And I gave my wife a hug while I was up. It's only
       been a couple of minutes since I read this, but you've already
       inspired me to focus on the mundane moments, which are also the
       sublime moments. You've already changed my life, and the life of my
       son in a small, huge way. Thank you. I don't know you, but I love
       you, and will be thinking of you.
       ReplyDelete
   61. [anon36.png]
       Francis LinardoJune 3, 2014 at 1:12 PM
       We should all display such grace in the moment of truth. Humbling
       to read this Oren.
       ReplyDelete
   62. [anon36.png]
       SantosandcharlieJune 3, 2014 at 1:13 PM
       Hi, you don't know me I hope you won't mind if I stop by and say a
       few words . MY husband is also a stage 4 lung cancer survivor. He
       was told he had 3 months 6.5 years ago. Don't believe everything
       you read. Clinical trials are working better , chemo treatments are
       less harsh. Look into organizations strictly for LC . There are
       plenty . I wish you well. God Bless you and your Family!
       ReplyDelete
   63. [anon36.png]
       Vincent DiCaroJune 3, 2014 at 1:16 PM
       Oren - please know that all of us at National Fatherhood Initiative
       are thinking about you and praying for you and your family. Thanks
       for this very moving post. God bless you and yours.
       ReplyDelete
   64. [anon36.png]
       LarryJune 3, 2014 at 1:38 PM
       My heart was pounding as I read that post. I'm finding it hard to
       type a response that is worthy. I'm feeling it. The grace, dignity,
       love - it's beautiful. Overwhelming. I pray for you and your
       family.
       ReplyDelete
   65. [anon36.png]
       Ryan Sanders June 3, 2014 at 1:55 PM
       Thank you for reminding me how great, and simple life should be.
       God's best to you brother.
       ReplyDelete
   66. [anon36.png]
       Doug FrenchJune 3, 2014 at 2:20 PM
       That's about as brave and graceful a way as possible to contemplate
       oblivion. The group you've brought together will be with you on
       this fight as much as we can.
       ReplyDelete
   67. [anon36.png]
       Hogan HillingJune 3, 2014 at 2:27 PM
       Oren, you're one amazing dude! I'm so glad to have had the pleasure
       of meeting and knowing you. You've raised two incredible kids and
       have one awesome wife. I pray your family and you will receive the
       loving support you all deserve through this challenging ordeal.
       Please keep us posted and Keep On Daddying!
       ReplyDelete
   68. [anon36.png]
       Matt NormanJune 3, 2014 at 2:37 PM
       Oren, thanks for reminding me to cherish every moment, even the
       tough ones, with my kids and wife. Fight the good fight. You'll be
       in my thoughts and prayers.
       ReplyDelete
   69. [anon36.png]
       lisasmissingkidneyJune 3, 2014 at 2:40 PM
       You're about 2 months behind me in your diagnosis. It's huge news
       to digest, and I wish you the best - the best days of your life,
       the best love you can give and get, and the best luck with the
       prognosis and progression of the disease.
       ReplyDelete
   70. [anon36.png]
       MileHighDadJune 3, 2014 at 3:35 PM
       Oren, I have never met you or read your .com before, great work by
       the way and I got here via Hogan on Facebook.
       Dude, I got misty reading your words. I too am at stay at home dad
       and have overcome a significant life challenge of my own. I have
       learned some things over the time and there are 2 that I will
       share.
       1. Accept it and it looks like it have. I on the other hand are
       still coming to terms with myself.
       2. The Dr. is a smart man but don't take his word as the final word
       because he has never met you or knows you outside his practice, and
       you've done big things before and just might do it again.
       Good luck my friend and I am here if you ever need support.
       Mike
       Project Engineer at Domestic-Engineering.com/ will divulge what my
       challenge was/is.
       I did not
       post it in this reply on purpose, don't need the pity, and have no
       time.
       ReplyDelete
   71. [anon36.png]
       Audra AJune 3, 2014 at 3:39 PM
       This is such a beautiful piece Oren. You and your family have been
       in my thoughts since I found out you were in the hospital. If there
       is anything I can do to help your family so that you can focus on
       your time together, please do not hesitate to ask.
       ReplyDelete
   72. [anon36.png]
       AnnieJune 3, 2014 at 4:11 PM
       I'm so sorry. I can't imagine that diagnosis as a father with
       children still at home. My mother-in-law was diagnosed with stage 4
       pancreatic cancer on March 7 and passed away on May 8. It was such
       a wild ride for our family. I wrote a lot about our journey through
       those two months, but I thought I'd share a post I wrote towards
       the end, which actually shares some of the same sentiments as
       yours. I can't imagine what this is like for you as the one going
       through it, but it might help to see how this process can be
       experienced by your loved ones as more than just tragic. All the
       best to you and your family as you navigate these strange, painful,
       beautiful waters.
       http://www.motherhoodandmore.com/2014/04/the-beauty-in-tragedy.html
       ReplyDelete
   73. [anon36.png]
       Susan BurrowsJune 3, 2014 at 4:13 PM
       I have no words - but keep on keeping on. Or something like that.
       Keep kicking ass and being you. Sorry I don't have something more
       eloquent to say.
       ReplyDelete
   74. [anon36.png]
       Zach RosenbergJune 3, 2014 at 4:14 PM
       Continue to be yourself, Oren, because you are amazing.
       ReplyDelete
   75. [anon36.png]
       Darrell - modernfatheronline.cJune 3, 2014 at 4:28 PM
       Some people hope when they go they reach Heaven. I've always hoped
       that I achieve immortality. Immortality is not living forever
       inside this earthly body of ours with its faults and ability to let
       us down, immortality is being someone who touched the lives of many
       they did not even meet and having that person remember them as long
       as they live.
       Hendrix achieved it. Lennon achieved it. Da Vinci, Edison, Einstein
       achieved it. Even Kurt Cobain, dirty, smelly, scruffy haired, and
       all; he achieved it.
       So you found YOUR Heaven on Earth. You've also achieved MY
       immortality and you're still with us.
       Now more than ever I must head to the States in February so that I
       can buy you that beer, or soy mocha latte Americana, whatever you
       prefer.
       In the meantime, much love to you and your family. Hold them tight,
       and I bet they'll hold you tighter.
       ReplyDelete
   76. [anon36.png]
       CarterJune 3, 2014 at 4:35 PM
       Can it really have only been 16 months since Houston? Remember the
       Four Seasons lobby? We stood around telling anyone who'd listen
       about this Facebook group you'd just started a couple of months
       earlier, how it was a place for dads who write to virtually
       congregate, socialize, aggravate and empathize. At the time, there
       were about 70 people in the new group. You came to Dad 2.0 Summit
       *hoping* to boost membership into triple digits. Hoping. Today,
       there are 761 members. Every continent is represented. Many faiths,
       many ethnic groups, many political persuasions, many generations.
       But we share these things: We are bloggers, and we are fathers. We
       love to create, and we love our children. We love a good
       discussion, even a good argument, even a bad argument. We love
       jokes and reading and reading jokes. We love meeting each other "in
       real life" when we can, and we love shooting the breeze --
       sometimes for hours, like kids at a slumber party -- on shared live
       video feeds. We love. The community, the extended, worldwide family
       you built and nurtured has wildly exceeded the hopes you expressed
       - cautiously - that first time we met so many of one another
       face-to-face in Houston. All this love? That's you. You did that.
       You made a family out of a group of men who live all over the
       world. You fashioned a social haven for us out of pixels and radio
       waves. The interaction might be virtual, but the love: That's real.
       ReplyDelete
   77. [anon36.png]
       Mommys_BusyJune 3, 2014 at 5:15 PM
       Beautiful post, Oren. So sorry to hear the details and here's
       hoping you can buck the trend. Thank you for sharing and reminding
       me how very special family is and always should be.
       ReplyDelete
   78. [anon36.png]
       CharlieSeymourJrJune 3, 2014 at 5:58 PM
       Oren,
       I'm one of the new guys on the block, having only recently been
       welcomed into the tightly-knit community of caring dads that you
       helped create. Here's what I wish for your kids and wife: that they
       enjoy you with all their energy over the months to come AND that
       you capture your life with them on video.
       My Dad died just over two years ago and oh how I wish I had been on
       my crusade before he left. I think God created us with the ability
       to forget things so that the pain we feel won't be as strong
       tomorrow as it is today. But with that comes the loss of what a dad
       sounded like, how tightly he squeezed me when he hugged me, and how
       great his laugh was. Oh, sure: we have photos and we talk about
       him, but I have almost no video with him in it.
       It's one of the reasons I started LessonsFromMyGrandson.com - so my
       grandson would always remember what I looked like, sounded like,
       and how much I love him. And that's my crusade - to get all of us
       INTO the videos with our kids so we all can remember they joys of
       life even if we aren't here to enjoy them any longer.
       So find those little moments in life and record them with your
       family. Not the big moments, necessarily... the ordinary, little
       moments. They will cherish them forever and remember the joy you
       brought to them.
       Bless you for sharing so much with all of us. Thinking about you.
       Charlie Seymour Jr
       ReplyDelete
   79. [anon36.png]
       MeganSayersJune 3, 2014 at 7:40 PM
       I think this is one of the most beautiful and bravest things I've
       ever read. My mom died of lung cancer three years ago, and the
       thing I remember most is her laughter, even at the end. Thank you
       for sharing your grace and courage in the face of an indescribable
       situation. Sending thoughts and love, even though we don't know
       each other.
       ReplyDelete
   80. [anon36.png]
       Liz GumbinnerJune 3, 2014 at 8:49 PM
       Oren, your words are going to be with me forever. I am sure I'm not
       alone in saying this.
       Keep fighting. You are remarkable.
       ReplyDelete
   81. [anon36.png]
       Kelly WhalenJune 3, 2014 at 9:12 PM
       I've read this post several times today, as it keeps getting shared
       by friends and loved ones. I keep coming back to read it and really
       let it sink in.
       We vacation in that area pretty regularly (and I grew up going to
       Bethany) so I can literally visualize you in those moments. I've
       literally been there trading beach time for a conference call or a
       blog post.
       What I can't do no matter how hard I try is imagine being in your
       shoes right now and writing such a beautiful tribute to your life
       and legacy. You've given everyone that reads this a gift of looking
       at their world with new eyes and more importantly it's clear you've
       given the best gift you could to your children and wife-the very
       best of yourself.
       ReplyDelete
   82. [anon36.png]
       Jay WisniewskiJune 3, 2014 at 9:31 PM
       Oren, my brothers and sisters recently lost their mother (we share
       the same father) to lung cancer. She fought until the end and made
       each day with her children and grandchildren count. I am new the
       blogger scene, but your site is one of the few that inspired me to
       take this leap. So many of us, whether we've met you or not, are
       moved by your posts and your current situation. Know that we're all
       thinking of you and your family. #dads4oren
       ReplyDelete
   83. [anon36.png]
       Colby ShipwashJune 3, 2014 at 10:34 PM
       Oren, I can only imagine how difficultly it was to write this post.
       What yo are going through would be my worst nightmare, as far as
       having to leave my family behind. My prayers go out to your whole
       family. Big Hug!
       ReplyDelete
   84. [anon36.png]
       DsmithJune 4, 2014 at 12:19 AM
       Oren, thank you for sharing your life story with us. May 30th was
       only a few days ago. This proves how quickly our lives can change.
       I am sorry for your sickness. I admire your courage and strength
       during your illness, and your desire to love and enjoy time with
       your dear family. I feel encouraged to do the same with my family
       from reading your kind words. I will be in prayer for you and your
       family.
       ReplyDelete
   85. [anon36.png]
       Atlanta's Frugal MomJune 4, 2014 at 1:30 AM
       A dear sweet friend of my family also recently was diagnosed with
       stage 4 lung cancer this winter. While the entire idea still chokes
       me up, I am nothing but touched by her optimism and her spirit. Her
       peace with the journey that lies ahead.
       And yet, I have no idea what the journey is like. I won't even
       pretend to know.
       However, I will hold you and your beautiful family in my prayers,
       and pray that His warm strength and loving arms are felt by you all
       at this time. May God bless you and your family.
       ReplyDelete
   86. [anon36.png]
       Matt DiazJune 4, 2014 at 7:31 AM
       Oren, selfishly, I hope to get to know you better very soon. You
       amaze me and your words resonate with me, and with many of us. I'm
       sad of the future things that are being taken away from you, and
       your family. Because of you, I will not waste my days. I will not
       miss the best moments of my life. Because of you I'll make sure to
       live better, and in the moment. I will not forget you, Oren Miller.
       ReplyDelete
   87. [anon36.png]
       THJune 4, 2014 at 8:37 AM
       Please keep fighting, and don't lose hope. My father lost his
       battle with cancer when I was 5 years old. Your blog posts will be
       a gift to your children, please consider writing notes for them to
       read as they get older. Hopefully, you will be here to read them
       together.
       ReplyDelete
   88. [anon36.png]
       mamakatslosinitJune 4, 2014 at 11:01 AM
       I just fell in love with your entire family...I don't know how you
       did that in so few words, but what an amazing little crew of
       supporters you have. They are so lucky to have these words.
       Medicine makes huge strides everyday. I have every ounce of faith
       in the world, you will beat this and your family will be stronger
       having weathered the storm together.
       ReplyDelete
   89. [anon36.png]
       blurbJune 4, 2014 at 1:11 PM
       This is amazing writing. Sending good energy, thoughts and hope
       your way.
       ReplyDelete
   90. [anon36.png]
       ATHJune 4, 2014 at 1:29 PM
       Maya Angelou said, "people don't remember what you do, they
       remember how you made them feel". This post made me feel. I will
       remember that. It will have a lasting impact on me. Thank you for
       sharing your story.
       ReplyDelete
   91. [anon36.png]
       Idaho DadJune 4, 2014 at 1:39 PM
       I don't know how many years I've been reading your blog. It's
       always been there in my feed, and I have no idea how much help and
       support you've been for me as a dad. But your words have been an
       integral part of my journey over the years. So, here's another dad
       blogger who just wants to say thank you, and to let you know you're
       in my thoughts at this time. Stay strong and be positive, and don't
       hesitate to ask anything of your fellow dads. There are a lot of us
       out here. Some are just a little quieter than others.
       ReplyDelete
   92. [anon36.png]
       MomoFaliJune 4, 2014 at 2:52 PM
       Damn the finite life. Just, damn. My wish for you would be peace,
       but it seems like you've already found it and leave it to you to
       make us all more aware of the beauty we take for granted. Thank
       you. For so much.
       ReplyDelete
   93. [anon36.png]
       Tanis Miller: Redneck MommyJune 4, 2014 at 4:34 PM
       Keep fighting Oren. May joy fill you and your loved ones lives.
       Thank you for sharing and know that I, along with so many others,
       are sending energy, love and hope your way.
       ReplyDelete
   94. [anon36.png]
       Ulf HannemannJune 5, 2014 at 6:50 AM
       I really got speechless as I read your posting. All the best for
       you and your family from Munich, Germany.
       ReplyDelete
   95. [anon36.png]
       Kay_MarDilJune 6, 2014 at 4:49 PM
       Oren, you don't know me. I'm a friend of your cousin Ilene. Here's
       what I say: Fight. Fight, fight, fight. Tell cancer to suck it, and
       fight. Stay optimistic, stay positive, stay focused on the true
       happiness you've found. Bask in its glow, fill yourself with the
       light of love that surrounds you from family and friends and keep
       putting one foot, literally or figuratively, in front of the other.
       Don't accept defeat. You know you won't have the years that a
       cancer-free man does, but that man might get hit by a bus tomorrow,
       know what I mean? Knowing your time will end sooner than you want
       it to give you freedom to be expressive with your emotions on a
       level that American men never attain. Hell, tell the grocery store
       check out lady you love her, if that's what you are feeling at the
       moment. Run with it. Be the entire YOU that you are, and your wife
       and kids will glory in it. Let your love of life and all that is in
       it be your legacy. Don't accept the timeframe given to you by
       doctors. One of my besties had a mother diagnosed with Stage 4
       breast cancer and given 6 months to live. She told cancer to eff
       off, and had 5 more great years. Sending you light & love, Kay.
       ReplyDelete
   96. [anon36.png]
       ahoovaJune 8, 2014 at 8:49 AM
       Wishing love and strength for you, your family and everyone who
       cares about you.
       ReplyDelete
   97. [anon36.png]
       D SchmidtJune 8, 2014 at 4:52 PM
       No words and yet I am writing them but nothing I say could be
       fitting. Beautifully written post, you are an inspiration (even
       though I wish you were not in this situation to be one). Keep
       believing you can get through this.
       ReplyDelete
   98. [anon36.png]
       cindymerrillJune 8, 2014 at 5:04 PM
       Homeopathic Remedies? Talk to someone in charge at your nearest
       Organic Health food store. Maybe this is a long shot, but in your
       condition, it's worth trying, even if the results only give you a
       few extra weeks to be with your family. Also, If your doctor hasn't
       already, insist to be seen by a dietitian as well.
       Don't go into that dark Valley gracefully- Fight it.
       ReplyDelete
   99. [anon36.png]
       Jill MyrickJune 8, 2014 at 5:23 PM
       Please know that I will be keeping you and your family in my
       thoughts and prayers.
       ReplyDelete
   100. [anon36.png]
       Justin KnightJune 8, 2014 at 7:22 PM
       Wow, Oren, wow. I have no words. Your words, however, are
       beautiful. This just gave me a kind of Frank Capra, It's A
       Wonderful Life moment. Two minutes ago, I was "too tired" to go
       play with my son and was annoyed with my wife for something
       infinitely unimportant. Thanks for the wake-up call. You and your
       family have my thoughts and prayers.
       ReplyDelete
   101. [anon36.png]
       Kimberly BolañosJune 8, 2014 at 8:55 PM
       Prayng.
       ReplyDelete
   102. [anon36.png]
       Bonnie MacFarlane-CombsJune 8, 2014 at 9:10 PM
       TWO TIME CANCER SURVIVOR HERE! First, I will not say I'm sorry
       you're going through this because there is a bigger meaning behind
       why you have cancer than you think.
       Since its been about a week for you I think we can say you've gone
       through the 5 stages of grief and you are now at acceptance. What
       you have been given is a gift, I know it sounds crazy, but you have
       what us cancer family like to call is the gift of "choosing
       happiness" and "choosing life"!
       You are a smart man with a readership far and wide, so you know now
       the only difference between YOU, and the people you see on a daily
       basis or communicate with is that you MIGHT have your "time coming"
       a little sooner than you thought, most people don't get that gift.
       They carelessly forget that life is a gift, and miss the MOMENTS,
       just like you said. When I leave this earth, it won't matter about
       my job status, money, or if I grabbed gas....LOVE AND FAMILY is it.
       CHOOSE HAPPINESS AND LIFE EVERYDAY, and you will already have
       survived but most will never. Until a final breath comes, "live
       like you're dying and don't die while you're living"!!
       Sincerely,
       Bonnie
       SAYVILLE NY
       ReplyDelete
   103. [anon36.png]
       BarbaraJune 8, 2014 at 9:21 PM
       I wanted to let you know your kids will remember you. I lost my Dad
       to lung cancer when I was young. Like you he stayed home with us
       and I remember riding in his car, singing songs at the top of our
       lungs and talking about the most important nonsense in the world. I
       remember him teaching me to play chess. I remember him hugging me
       and knowing I was completely safe. My older brother and my Mom told
       me stories of other times, and of course there are pictures, and
       cheesey 1980s movies of holidays, but those memories are mine. You
       will not be a bare memory, you will be their Dad, and they will
       know that they were the loves of your life. Your daughter will grow
       up and find a man that loves her the way she remembers you loved
       her mother, and your son will grow up striving to be a man you
       would be proud of.
       I hope you beat this, I hope you dance at your granddaughter's
       wedding and laugh, but in the event you don't, don't ever worry
       that your babies will not remember you, they will never forget.
       ReplyDelete
   104. [anon36.png]
       NicoleJune 8, 2014 at 9:38 PM
       I read your post and felt compelled to tell you that there is hope.
       My dad was diagnosed with Stage 4 lung cancer last fall. It had
       spread quite far - his bones - including the spine, lymph nodes,
       liver - pretty much everywhere. He has adopted a totally vegan diet
       and spends a lot of time in meditation along with chemo. Here we
       are almost a year later and the cancer is gone with the exception
       of a few small spots of activity too small to show up on the CT
       scan. He feels great. It has been hard for sure but there is hope.
       He recommends the book Radical Remission and swears that his
       mindset and faith have largely led him through this. Don't give up!
       ReplyDelete
   105. [anon36.png]
       TrishFrJune 8, 2014 at 11:11 PM
       Oren, I am so sorry to hear of your diagnosis. You certainly have
       everything in the world to live for. I hope you don't mind me
       saying this but I just watched a 6 night presentation on Cancer and
       alternative treatments. I have been chronically ill for 20 years
       with Lyme disease and I just thought perhaps watching this series
       about cancer would help me find something I can apply to my own
       health. I just got an email from the series and I see they are
       offering a free replay marathon, it will probably be 6-10 hours
       long on Sat. June 14th. I found it very informative and it has
       inspired me in many ways regarding my own health. Here is the link:
       http://thetruthaboutcancer.com/ I also would look into B-17
       (apricot seeds). I have never used them personally nor do I know
       anyone who has, but there are many testimonials on Amazon. I wish
       you all the healing in the world, so that you can be there for your
       kids and wife for a long time. Happy Father's Day.
       ReplyDelete
   106. [anon36.png]
       VioletJune 8, 2014 at 11:52 PM
       I just came across your blog via Heather Spohr's blog. My Dad last
       his battle to stage for cancer which had metastisized to his lungs
       in December. All four of his kids are grown, but reading this I
       felt like it was something he would have written if he were a
       writer. Clinical trials bought us time with my dad. Precious
       cherished time. I wish the same and more for your family. One thing
       I know, your love will always be with them. I'm so sorry you all
       have to walk this road.
       ReplyDelete
   107. [anon36.png]
       CandyDandyJune 9, 2014 at 12:45 AM
       Keep finding heaven on Earth, and you may be amazed at the
       extension that the universe may give you! You will also leave a
       legacy in your writing. Encourage your kids and wife to do the
       same. Sharing is the best way to formulate.
       If people could only remember the intricate details of everyday
       smiles and forget the big worries that we can do so little
       about---the world would be a lot more moments of Heaven. Thanks for
       reminding us! Cheers to you and your bold steps ahead. Thanks for
       putting it out there for us...Thanks for taking the noble route.
       ReplyDelete
   108. [anon36.png]
       Autumn CanterJune 9, 2014 at 7:35 AM
       Oh, Oren. Please let me know if there is any way I can help. I love
       your attitude. Doesn't stop me from weeping all over the freaking
       place. You've always fascinated me with the way you care from your
       children. I always knew a selfless Dad was possible, but had little
       experience seeing one in action! I didn't get one and neither did
       my husband! It's been a wonder for me to see a man do just as well
       as a woman being the one home raising young children. I always
       picture you holding your sleeping girl in your arms effortlessly. I
       wondered if I would look so calm and natural with Sage when she
       finally came. For what it is worth, you and your family as in my
       prayers.
       ReplyDelete
   109. [anon36.png]
       Kristin WheelerJune 9, 2014 at 10:26 AM
       Praying for you and your family! Your kids are gorgeous! I will be
       looking back for the post titled, "It's a Miracle!"
       ReplyDelete
   110. [anon36.png]
       Melissa LombardJune 9, 2014 at 1:38 PM
       I want to say something, yet have nothing to say. Nothing that
       feels right after that beautiful, eloquent, honest post. Except
       thank you. Thank you for the reminder. And thank you for seeing
       your children; knowing them so - that you can capture exactly what
       they need in a line or two. Thank you for loving your family with
       all of your heart and for the courage to keep doing so despite the
       fear and uncertainty. Thank your for your courage - to share this
       with all of us. You are loved, prayed for and supported - by those
       who know you and those who wish they did.
       ReplyDelete
   111. [anon36.png]
       perri_verdinoJune 9, 2014 at 2:03 PM
       Thank you for sharing your epiphany-it is one I needed to hear
       today.
       I will be holding you and your family in prayers. May you continue
       to "have the time of your life" for many, many more days to come.
       ReplyDelete
   112. [anon36.png]
       renadJune 9, 2014 at 3:47 PM
       Thank you for sharing your story. I'm saying a prayer for you and
       your family, and I hope the rest of your journey is filled with
       much more love and peace. My daughter is sensitive like your son,
       and needs to be treated like an adult! Ill share with you a funny
       little story that happened today, and maybe it will brighten your
       day like it did mine. My daughter Layla is 3 and she had her
       cousin, Jinan, over today. This is what went down. Jinan: Aunty,
       can we put nailpolish on? Me: Nope, not today. Layla: its ok Jinan
       I can speak mom. She comes up to me and starts carressing my face
       and says ok mama here's the deal. Were gonna put nailpolish on and
       then were gonna go to summer camp ok. You better believe they got
       to put nailpolish on haha. God bless you and your family. With
       love, Renad.
       ReplyDelete
   113. [anon36.png]
       MaryJune 9, 2014 at 7:24 PM
       There is a clinical trial going on right now for lung cancer at
       Johns Hopkins.
       Please contact them to see if you might qualify.
       ReplyDelete
   114. [anon36.png]
       Martha-Gail MooreJune 9, 2014 at 9:08 PM
       Oren, We don't know each other, but you have a relative whom I do
       know. So, if I could, I wanted to encourage you to explore other
       options than what the peeps in white coats have to offer. My friend
       told me about this website. The man who created the website cured
       himself of stage 4 colon cancer. Hence, the name of the site:
       http://www.chrisbeatcancer.com/
       But that said, researchers have made incredible advances in cancer
       therapy.
       This post is a beautiful testament to what a loving person you are,
       and I hope with all my heart that are are cured. Hugs, mgm
       ReplyDelete
   115. [anon36.png]
       OrenJune 9, 2014 at 10:42 PM
       Thank you! And continued good luck to your husband!
       ReplyDelete
   116. [anon36.png]
       OrenJune 9, 2014 at 10:44 PM
       Thanks, Man. I don't think I'm worthy of all or of any of that, but
       I sure appreciate it.
       ReplyDelete
   117. [anon36.png]
       OrenJune 9, 2014 at 10:45 PM
       Thank you! Back at you!
       ReplyDelete
   118. [anon36.png]
       OrenJune 9, 2014 at 10:48 PM
       Thanks! I'm proud to be a member of the council.
       ReplyDelete
   119. [anon36.png]
       OrenJune 9, 2014 at 10:49 PM
       Thank you! I will definitely look into that.
       ReplyDelete
   120. [anon36.png]
       OrenJune 9, 2014 at 10:51 PM
       Thanks. So far, I'm taking it one step at a time. There was a huge
       blood clot in the heart, and we took care of it. Then this week we
       start taking care of the brain tumors, and then we just take the
       fight to the lungs. Not losing hope here.
       ReplyDelete
   121. [anon36.png]
       shelviaJune 10, 2014 at 2:08 AM
       You struck me as a survivor, cause we all need more people like you
       around. Thank you for a wonderful reminder post on what is
       important in life. Best of luck. Pfft cancer - you can beat it.
       ReplyDelete
   122. [anon36.png]
       OrenJune 10, 2014 at 9:02 PM
       Thank you. And really, don't worry about what to say. I don't have
       the experience of people who've been sick for a while, but judging
       by this past week+, 0% of people know how to react and what to say.
       I appreciate your thoughts and your prayers!
       ReplyDelete
   123. [anon36.png]
       OrenJune 10, 2014 at 9:03 PM
       Thank you! And thanks for the republishing. It's nice to see the
       comments on your site too.
       ReplyDelete
   124. [anon36.png]
       OrenJune 10, 2014 at 9:05 PM
       Thank you! I remember being a terrible salesman for the group... My
       "It's really cool!" didn't go far. In the end, word-of-mouth did
       everything right, because people can recognize something real. You
       know I take 1/761 of the credit, though.
       ReplyDelete
   125. [anon36.png]
       OrenJune 10, 2014 at 9:06 PM
       Thank you!
       ReplyDelete
   126. [anon36.png]
       OrenJune 10, 2014 at 9:07 PM
       Ha, I remember that moment. I was tired, and it was really hot, but
       when a little kid climbs on you, you can't complain.
       ReplyDelete
   127. [anon36.png]
       OrenJune 10, 2014 at 9:08 PM
       Thank you, and same to you!
       ReplyDelete
   128. [anon36.png]
       OrenJune 10, 2014 at 9:09 PM
       Thank you! Although I don't feel too remarkable... But thank you!
       ReplyDelete
   129. [anon36.png]
       OrenJune 10, 2014 at 9:09 PM
       Thanks, Doug!
       ReplyDelete
   130. [anon36.png]
       OrenJune 10, 2014 at 9:11 PM
       Thanks. I think I'm more tired than I hoped I'd be, but I'm still
       trying to find moments, even if the moments are just watching Care
       Bears with my girl.
       ReplyDelete
   131. [anon36.png]
       OrenJune 10, 2014 at 9:12 PM
       Thank you!
       ReplyDelete
   132. [anon36.png]
       OrenJune 10, 2014 at 9:20 PM
       Ha, I don't know if I'm mature--it's just things that make sense to
       me. It's like the cancer-surviving cousin who came up to me
       yesterday and said, "Fuck, fuck, fuck! That was all I could think
       while I had cancer!" And frankly, although that's a valid way of
       thinking about cancer--it's just not my way.
       ReplyDelete
   133. [anon36.png]
       OrenJune 10, 2014 at 9:23 PM
       Thanks! Although Hebrew is my first language, I've been in
       London/US since '95, so I picked up the language eventually... And
       thanks about the mensch thing. It's important for me to be one (and
       for my son to be one as well).
       ReplyDelete
   134. [anon36.png]
       OrenJune 10, 2014 at 9:31 PM
       Thank you!
       ReplyDelete
   135. [anon36.png]
       OrenJune 10, 2014 at 9:31 PM
       No, you!
       ReplyDelete
   136. [anon36.png]
       OrenJune 10, 2014 at 9:31 PM
       Thank you! Same here!
       ReplyDelete
   137. [anon36.png]
       OrenJune 10, 2014 at 9:32 PM
       Thank you!
       ReplyDelete
   138. [anon36.png]
       OrenJune 10, 2014 at 9:32 PM
       Thank you! And thanks again for including me in the book!
       ReplyDelete
   139. [anon36.png]
       OrenJune 10, 2014 at 9:32 PM
       Thanks!
       ReplyDelete
   140. [anon36.png]
       OrenJune 10, 2014 at 9:33 PM
       Thanks, Larry!
       ReplyDelete
   141. [anon36.png]
       OrenJune 10, 2014 at 9:33 PM
       Thanks! And thanks for all the work you do!
       ReplyDelete
   142. [anon36.png]
       OrenJune 10, 2014 at 9:33 PM
       Thank you!
       ReplyDelete
   143. [anon36.png]
       OrenJune 10, 2014 at 9:34 PM
       Thanks, Hilary!
       ReplyDelete
   144. [anon36.png]
       OrenJune 10, 2014 at 9:35 PM
       Thank you! I think comfort may be the harder part, but I hope for
       the best on that front too...
       ReplyDelete
   145. [anon36.png]
       OrenJune 10, 2014 at 9:36 PM
       Thanks!
       ReplyDelete
   146. [anon36.png]
       OrenJune 10, 2014 at 9:36 PM
       That's great. Good luck to both of you!
       ReplyDelete
   147. [anon36.png]
       LarryJune 10, 2014 at 9:36 PM
       I made my wife read it as well as I've mentioned your situation to
       her. She was also very moved.
       ReplyDelete
   148. [anon36.png]
       OrenJune 10, 2014 at 9:39 PM
       Thank you, Chris. The whole prognosis stage, which actually lasted
       a few days, seemed to have been happening to someone else, frankly,
       but once I realized there was no one else around, all I could do
       was accept it as my own.
       ReplyDelete
   149. [anon36.png]
       OrenJune 10, 2014 at 9:39 PM
       Thank you!
       ReplyDelete
   150. [anon36.png]
       OrenJune 10, 2014 at 9:40 PM
       Thanks, Andrea!
       ReplyDelete
   151. [anon36.png]
       OrenJune 10, 2014 at 9:41 PM
       Thanks, Beth! We will see you soon!
       ReplyDelete
   152. [anon36.png]
       OrenJune 10, 2014 at 9:41 PM
       Thanks for reading!
       ReplyDelete
   153. [anon36.png]
       OrenJune 10, 2014 at 9:43 PM
       Thanks, Martin. I've written more and less personal stuff or even
       genuine stuff over these years, and it's good to know I can still
       have a place for "true" writing. I hope you come back to writing
       soon too!
       ReplyDelete
   154. [anon36.png]
       OrenJune 10, 2014 at 9:43 PM
       Thanks, Creed!
       ReplyDelete
   155. [anon36.png]
       OrenJune 10, 2014 at 9:45 PM
       Thanks!!!
       ReplyDelete
   156. [anon36.png]
       Hogan HillingJune 10, 2014 at 9:53 PM
       You're welcome. But it is Al and I who should thank you and the
       rest of the dads. Keep the faith and get well. My best to the you
       and your family.
       ReplyDelete
   157. [anon36.png]
       OrenJune 10, 2014 at 10:11 PM
       Thanks!
       ReplyDelete
   158. [anon36.png]
       OrenJune 10, 2014 at 10:12 PM
       Thank you for reading!
       ReplyDelete
   159. [anon36.png]
       OrenJune 10, 2014 at 10:13 PM
       Thank you! I appreciate that!
       ReplyDelete
   160. [anon36.png]
       OrenJune 10, 2014 at 10:14 PM
       Thank you! And it was great to meet you in NOLA!
       ReplyDelete
   161. [anon36.png]
       OrenJune 10, 2014 at 10:14 PM
       Thanks, Chris!
       ReplyDelete
   162. [anon36.png]
       OrenJune 10, 2014 at 10:15 PM
       Thank you! I don't quite get it either, to be honest...
       ReplyDelete
   163. [anon36.png]
       OrenJune 10, 2014 at 10:16 PM
       Thank you, Caitlin!
       ReplyDelete
   164. [anon36.png]
       OrenJune 10, 2014 at 10:18 PM
       Thanks, man. And you know, if you're ever in Baltimore, give us a
       call!
       ReplyDelete
   165. [anon36.png]
       OrenJune 10, 2014 at 10:21 PM
       Thanks, John!
       ReplyDelete
   166. [anon36.png]
       OrenJune 10, 2014 at 10:33 PM
       Thank you! I hope that's true.
       ReplyDelete
   167. [anon36.png]
       OrenJune 10, 2014 at 10:38 PM
       Thank you!
       ReplyDelete
   168. [anon36.png]
       OrenJune 10, 2014 at 10:44 PM
       Thank you!
       ReplyDelete
   169. [anon36.png]
       TrishFrJune 12, 2014 at 1:54 AM
       I just have to add this link about Beta Glucan.
       http://www.betaglucan.org/A-C.htm
       ReplyDelete
   170. [anon36.png]
       LoraJune 12, 2014 at 10:15 AM
       When I was in high school, I assisted on the set of a production of
       Thornton Wilder's "Our Town." I've never consciously thought about
       it since, but after reading your story, the end of one quote kept
       repeating in my head: "live it - every, every minute." I had to
       look up the rest, which I've copied below. It could have been
       written for/by you. I wish you all the happiness in the world. And
       I thank you for sharing this perspective. It is invaluable.
       "Goodbye to clocks ticking — and my butternut tree! And Mama's
       sunflowers — and food and coffee — and new-ironed dresses and hot
       baths — and sleeping and waking up! Oh, earth, you're too wonderful
       for anyone to realize you! Do any human beings ever realize life
       while they live it — every, every minute?"
       ReplyDelete
   171. [anon36.png]
       OrenJune 12, 2014 at 11:06 AM
       Thanks! Not sure I'm worthy of all that, but thanks.
       ReplyDelete
   172. [anon36.png]
       OrenJune 12, 2014 at 11:18 AM
       Thank you!
       ReplyDelete
   173. [anon36.png]
       OrenJune 12, 2014 at 11:27 AM
       Thanks, Jeff!
       ReplyDelete
   174. [anon36.png]
       OrenJune 12, 2014 at 11:30 AM
       Thank you!
       ReplyDelete
   175. [anon36.png]
       OrenJune 12, 2014 at 12:20 PM
       Thank you!
       ReplyDelete
   176. [anon36.png]
       Aidan MorganJune 12, 2014 at 2:21 PM
       These are generous and beautiful words, Oren. It's a privilege to
       be able to read them.
       ReplyDelete
   177. [anon36.png]
       OrenJune 12, 2014 at 2:39 PM
       Thanks!
       ReplyDelete
   178. [anon36.png]
       OrenJune 12, 2014 at 2:48 PM
       Thanks, Jim!
       ReplyDelete
   179. [anon36.png]
       OrenJune 12, 2014 at 2:55 PM
       Thanks for reading!
       ReplyDelete
   180. [anon36.png]
       OrenJune 12, 2014 at 3:16 PM
       Hey, any time you're in the neighborhood!
       ReplyDelete
   181. [anon36.png]
       OrenJune 12, 2014 at 3:45 PM
       That was great. Thank you!
       ReplyDelete
   182. [anon36.png]
       OrenJune 12, 2014 at 3:50 PM
       Thank you!
       ReplyDelete
   183. [anon36.png]
       DonnaJune 12, 2014 at 11:22 PM
       My husband died from brain cancer. 15 months and poof. Never saw
       his son learn to speak in sentences or use Legos to build houses or
       ride a tricycle. Relish every moment. I sure we'd done that.
       ReplyDelete
   184. [anon36.png]
       DadapaloozaJune 13, 2014 at 9:11 AM
       I said this on Facebook, and I'll say it again here-- you are
       handling this with so much grace. I've cried both times I've read
       this post-- partially for you and for your family, and thinking
       about my inevitable end and my family. When it is my turn to get
       this news, I hope I can be as graceful and as eloquent.
       Keep strong, keep your grace, and I hope to see you at next year's
       Dad 2.0 Summit (and you can rest assured, you won't have to buy a
       single drink!)
       ReplyDelete
   185. [anon36.png]
       OrenJune 13, 2014 at 11:54 AM
       Thank you! I don't rule out anything yet!
       ReplyDelete
   186. [anon36.png]
       OrenJune 13, 2014 at 12:00 PM
       Thanks, Mary. I'm actually at Johns Hopkins, so hopefully all good
       options will be available to me.
       ReplyDelete
   187. [anon36.png]
       Aaron's DadJune 13, 2014 at 12:17 PM
       Hi Oren - I'm Aaron's dad (incase the name didn't give it away).
       Just felt the need to tell you our whole family wishes you well and
       our hearts are with you and your kids and wife. Must be strange to
       get stuff like this from clowns like me who don't even know you,
       but somehow it just felt right. Keep fighting the good fight. Bill.
       ReplyDelete
   188. [anon36.png]
       OrenJune 13, 2014 at 12:19 PM
       Thank you! This comment is much better than any advice.
       ReplyDelete
   189. [anon36.png]
       OrenJune 13, 2014 at 12:20 PM
       Thank you, Bill! And thank you for all your support!
       ReplyDelete
   190. [anon36.png]
       OrenJune 13, 2014 at 12:48 PM
       Thank you!
       ReplyDelete
   191. [anon36.png]
       OrenJune 13, 2014 at 12:52 PM
       Thank you! The kids--they are so more than these two lines,
       though... They're a whole world I can never do justice to. But at
       least I got those two lines out. The more urgent stuff.
       ReplyDelete
   192. [anon36.png]
       OrenJune 13, 2014 at 1:15 PM
       Thank you!
       ReplyDelete
   193. [anon36.png]
       TJune 13, 2014 at 3:07 PM
       Oren, I know we've never met, but I grew up with Beth and just
       wanted to stop by and say what an inspiration you are! My heart
       breaks for you all. I'm sending prayers and wishing a miracle comes
       your way! Sadly yours....
       ReplyDelete
   194. [anon36.png]
       JessJune 13, 2014 at 4:10 PM
       Hi Oren, thank you for writing such a touching, authentic and
       honest post. I'm not even sure those are the right words to
       describe your post or that they even do it justice, but I am truly
       inspired after reading it. Thank you for the reminder to stop and
       enjoy every moment and to not get caught up in the things that seem
       pressing or "serious" at the time, but later are trivial
       distractions from what matters most. It robs us of the precious
       moments you remind us are finite, and of the happiness available to
       us at any time. I wish you and your family well.
       ReplyDelete
   195. [anon36.png]
       Martha-Gail MooreJune 13, 2014 at 4:22 PM
       Way to go, Oren! With high hopes, mgm
       ReplyDelete
   196. [anon36.png]
       Melissa LombardJune 13, 2014 at 4:30 PM
       Of course they are. It's what those two lines say about you, as
       their father, that I was struck by. It says, "I know these two
       incredible beings on the deepest level possible." To be known like
       that, especially by a father...what an amazing and rare gift. I
       know people with 90 year-old dads who haven't experienced that. We
       may not be able to control the length of our lives, but we can
       control the depth.
       ReplyDelete
   197. [anon36.png]
       MicheleJune 13, 2014 at 6:24 PM
       So many new advances in Lung Cancer Treatment my Dad was 65 and
       diagnosed Stage 4 Lung Cancer he was given 3 months he almost made
       it 5 years and his death was not from the cancer. Stay strong!!
       ReplyDelete
   198. [anon36.png]
       HeatherJune 13, 2014 at 6:26 PM
       Simply inspiring. I will keep you and your family in my positive
       thoughts and prayers.
       ReplyDelete
   199. [anon36.png]
       OrenJune 13, 2014 at 7:00 PM
       Thank you!
       ReplyDelete
   200. [anon36.png]
       OrenJune 13, 2014 at 7:02 PM
       Thank you!!! I find it a little hard to write now, but maybe soon,
       even if it's not published.
       ReplyDelete

   Add comment
   Load more...

   ‹
   ›
   Home
   View web version
   Powered by Blogger
