   Microsoft Research
   Data Science Summer School
   home :: program :: instructors :: students :: projects :: faq :: apply
   Microsoft Research
   Data Science Summer School

   The Data Science Summer School (DS3) is an intensive, eight-week
   hands-on introduction to data science for college students in the New
   York City area. As we are committed to increasing diversity in computer
   science, we strongly encourage women, minorities, and individuals with
   disabilities to apply.

   Each student receives a $5,000 stipend for participating in the
   program, as well as a laptop.

   DS3 includes both course work in data science and group research
   projects. The summer school is taught by leading scientists at
   Microsoft Research, and is held at the new Microsoft Research office in
   the heart of New York City.

   To learn more about DS3, please look at the program details and the
   frequently asked questions. You can also email us at ds3@microsoft.com.

   We are accepting applications until April 18, 2014.

   Contact us Privacy and Cookies Terms of use Code of Conduct © Microsoft
   Corporation. All rights reserved. Microsoft
