    #Food The Salt

   Skip to Main Content subnav toggle NPR

   ____________________
   Toggle search
     * Stations
     * Donate
     * Shop
     * Sign In/Register
     *
     * Logout

     * Topics
          + News
          + U.S.
          + World
          + Politics
          + Business
          + Technology
          + Science
          + Health
          + Race & Culture
          + Arts & Life
          + Movies
          + Pop Culture
          + Food
          + Art & Design
          + Performing Arts
          + Photography
          + Books
          + Book Reviews
          + Author Interviews
          + Music
          + First Listen
          + Music Articles
          + Studio Sessions
          + Videos
     * Programs
          + News and Conversations
          + Morning Edition
          + All Things Considered
          + Fresh Air
          + Here & Now
          + The Diane Rehm Show
          + Latino USA
          + On The Media
          + On Point
          + Weekend Edition Saturday
          + Weekend Edition Sunday
          + Storytelling & Humor
          + Ask Me Another
          + Car Talk
          + Radiolab
          + Snap Judgment
          + StoryCorps
          + TED Radio Hour
          + Wait Wait...Don't Tell Me!
          + Music
          + All Songs Considered
          + Alt.Latino
          + First Listen
          + Metropolis
          + Microphone Check
          + Mountain Stage
          + From The Top
          + JazzSet
          + Piano Jazz
          + Song Travels
          + The Thistle & Shamrock
          + World Cafe
     * Listen

   NPR logo NPR
   The Salt What's On Your Plate
     * Eating And Health
     * Foodways
     * Producers
     * Food For Thought
     * For Foodies

     * Twitter

   Eating And Health

Got Gas? It Could Mean You've Got Healthy Gut Microbes

   by Michaeleen Doucleff
   April 28, 2014 1:43 PM ET
   Sulfur-rich foods, such as cabbage, bok choy and kale, can be popular
   with gut bacteria. And we all know how much the critters enjoy beans. i
   i

   Sulfur-rich foods, such as cabbage, bok choy and kale, can be popular
   with gut bacteria. And we all know how much the critters enjoy beans.
   Meg Vogel/NPR hide caption
   itoggle caption Meg Vogel/NPR
   Sulfur-rich foods, such as cabbage, bok choy and kale, can be popular
   with gut bacteria. And we all know how much the critters enjoy beans.

   Sulfur-rich foods, such as cabbage, bok choy and kale, can be popular
   with gut bacteria. And we all know how much the critters enjoy beans.
   Meg Vogel/NPR

   Not long ago, we heard about a catchy idea for a cookbook: "Fart-free
   food for everybody."

   In theory, these recipes would be helpful for some people — and those
   in their vicinity.

   But being a bit gassy may actually be a small price to pay for a lot of
   benefits to our health.

   We know that air often comes after eating nutrient-packed vegetables,
   such as cabbage, kale and broccoli. And researchers have found that
   fiber-rich foods, like beans and lentils, boost the levels of
   beneficial gut bacteria after only a few days, as we reported in
   December.

   So all this got us wondering: Could passing gas, in some instances, be
   a sign that our gut microbes are busy keeping us healthy?
   Volunteers went on two extreme diets.

The Salt

Chowing Down On Meat, Dairy Alters Gut Bacteria A Lot, And Quickly

   Absolutely, says Purna Kashyap, a gastroenterologist at the Mayo Clinic
   in Rochester, Minn.
   While no one's sure which foods are good for our microbiomes, eating
   more veggies can't hurt.

The Salt

Can We Eat Our Way To A Healthier Microbiome? It's Complicated

   "Eating foods that cause gas is the only way for the microbes in the
   gut to get nutrients," he says. "If we didn't feed them carbohydrates,
   it would be harder for them to live in our gut."

   And we need to keep these colon-dwelling critters content, Kashyap
   says. When they gobble up food — and create gas — they also make
   molecules that boost the immune system, protect the lining of the
   intestine and prevent infections.

   "A healthy individual can have up to 18 flatulences per day and be
   perfectly normal," he adds.

   Gas gets into the digestive tract primarily through two routes:
   Swallowing air (which we all do when we eat and chew gum) and your
   microbiome. That's the collection of organisms in the GI tract that
   scientists and doctors are currently all fired up about. (Check our
   colleague Rob Stein's recent series on it.)

   That microbiome includes hundreds of different bacteria. But there are
   also organisms from another kingdom shacking up with them: the archaea.
   Illustration by Benjamin Arthur for NPR

Shots - Health News

Gut Bacteria Might Guide The Workings Of Our Minds

   All these microbes are gas-making fools. They eat up unused food in
   your large intestine, like fiber and other carbohydrates we don't
   digest, and churn out a bunch of gases as waste.

   But that's not all they make. They also produce a slew of molecules
   (called short chain fatty acids) that may promote the growth of other
   beneficial bacteria and archaea.

   And the more fiber you feed these friendly inhabitants, the more types
   of species appear, studies have found. This bump in microbial diversity
   has been linked to a slimmer waistline.

   "Undigested carbohydrates allow the whole ecosystem to thrive and
   flourish," Kashyap says.

   Most gas made by the microbiome is odorless. It's simply carbon
   dioxide, hydrogen or methane. But sometimes a little sulfur slips in
   there.

   "That's when it gets smelly," Kashyap says.

   But here's the hitch: Many of the smelly sulfur compounds in vegetables
   have healthful properties.

   Take for instance, the broccoli, mustard and cabbage family. These
   Brassica vegetables are packed with a sulfur compound, called
   sulforaphane, that is strongly associated with a reduced risk of
   cancer.

   Another possible benefit of a little smelly gas? It may reduce the
   total volume of air in the gut, Kashyap says.

   Why? Because bacteria and archaea make the sulfur gas from other gases
   in the gut, like hydrogen.

   "Bacteria that make sulfide gas are really important," Kashyap says.
   "They can cause smelliness, but they can reduce the total amount of gas
   flow."

   Of course, having too much of anything can be bad. If gas and bloating
   start interfering with your quality of life, Kashayps recommends seeing
   a doctor.

   But don't immediately blame your diet, Kashyap says.

   In many cases, people who complain about too much gas actually don't
   generate more than others, he says. Instead, they perceive the passing
   more intensely. Or they pass it more often.

   "Yes, a more fiber-rich diet will produce more gas," Kashyap adds. "But
   completely eliminating fiber from the diet should not be the first
   option. You don't want to starve your microbes."

   So go ahead. Enjoy those lentils. Chow down on the cabbage. Then if you
   stink a little, think of it as a thank you gesture from your
   microbiome.
     * microbiome
     * gastrointestinal
     * diet

     * Share
          + Facebook
          + Twitter
          + Google+
          + Email
     * Comment

   Fire-Setting Ranchers Have Burning Desire To Save Tallgrass
   PrairieApril 28, 2014 Sandwich Monday: The Poutine BurgerApril 28, 2014

More From The Salt

Food

Culinary Diplomacy Takes Texan Chef To The Land Of Grilled Yak

   Chef Tim Byres teaches a master class for culinary students in Bishkek,
   Kyrgyzstan.

Food

GMO Wheat Investigation Closed, But Another One Opens

   How did that genetically modified wheat end up in a field in Oregon?
   Investigators still don't know, but now they've found GMO wheat in
   Montana, too.

Food

Belgium Likes Underground Beer. No, Literally

   The De Halve Maan Brewery plans to build a pipe beneath the streets of
   Bruges to carry its brew from its historic brewery to a bottling plant
   2 miles away.

Food

Supermarkets Waste Tons Of Food As They Woo Shoppers

   Ready-to-eat meals found in the prepared food aisle are a growing
   source of waste, as it is difficult to reuse meals that aren't sold but
   are fully cooked.

   More From The Salt

Comments



You must be signed in to leave a comment. Sign In / Register

   Please keep your community civil. All comments must follow the NPR.org
   Community rules and Terms of Use. NPR reserves the right to use the
   comments we receive, in whole or in part, and to use the commenter's
   name and location, in any medium. See also the Terms of Use, Privacy
   Policy and Community FAQ.
   Please enable JavaScript to view the comments powered by Disqus.
   NPR logo NPR
   The Salt What's On Your Plate
   The Salt What's On Your Plate

About

   With a pinch of skepticism and a dash of fun, The Salt covers food news
   from the farm to the plate and beyond. You can connect with senior
   editor and host Maria Godoy, or editors Eliza Barclay and April Fulton,
   via our contact form or directly by email.

Subscribe

     * RSS
     * @NPRFood
     * @AubreyNPRFood
     * @elizabarclay
     * @fultonhere
     * @mgodoyh
     * @nprDanCharles

NPR Food Twitter

   [twitter-bird-light-bgs.png]

Follow @NPRFood

   NPR thanks our sponsors

   Become an NPR sponsor

   Search ____________________
     * Home
     * Topics
     * Programs
     * Donate
     * Stations
     * NPR Shop
     * Sign In / Register

     *
     * Logout

   Back

News

     * U.S.
     * World
     * Politics
     * Business
     * Technology
     * Science
     * Health
     * Race & Culture

Arts & Life

     * Movies
     * Pop Culture
     * Food
     * Art & Design
     * Performing Arts
     * Photography

Books

     * Book Reviews
     * Author Interviews

Music

     * First Listen
     * Music Articles
     * Studio Sessions
     * Videos

Our Blogs

Corrections

All About NPR

   Back
     * news & conversations
     * storytelling & humor
     * music
     * also heard on npr stations

   Back
     * Morning Edition
     * All Things Considered
     * Fresh Air
     * Here & Now
     * The Diane Rehm Show
     * Latino USA
     * On The Media
     * On Point
     * Science Friday
     * Weekend Edition Saturday
     * Weekend Edition Sunday

   Back
     * Ask Me Another
     * Car Talk
     * Radiolab
     * Snap Judgment
     * StoryCorps
     * TED Radio Hour
     * Wait Wait...Don't Tell Me!

   Back
     * All Songs Considered
     * Alt.Latino
     * First Listen
     * Metropolis
     * Microphone Check
     * Mountain Stage
     * From The Top
     * JazzSet
     * Piano Jazz
     * Song Travels
     * The Thistle & Shamrock
     * World Cafe

   Back
     * A Prairie Home Companion (APM)
     * Marketplace (APM)
     * Science Friday
     * This American Life (PRX)
     * Public Radio Programs A to Z

   Support comes from:

Support NPR

   Support NPR

NPR Shop

   Support The Programs You Love

     *
     * News
          + U.S.
          + World
          + Opinion
          + Politics
          + Business
          + Technology
          + Science
          + Health
          + Sports
     * Arts & Life
          + Books
          + Movies
          + Pop Culture
          + Food
          + Performing Arts
          + Games & Humor
     * Music
          + Music Articles
          + Music Videos
          + NPR Music Radio
          + Browse Artists A-Z
          + All Songs Considered
          + Alt.Latino
          + First Listen
          + Metropolis
          + Microphone Check
          + Mountain Stage
          + From The Top
          + JazzSet
          + Piano Jazz
          + Song Travels
          + The Thistle & Shamrock
          + World Cafe
     * Programs
          + All Things Considered
          + Ask Me Another
          + Car Talk
          + The Diane Rehm Show
          + Fresh Air
          + Here & Now
          + Latino USA
          + Morning Edition
          + On The Media
          + On Point
          + Science Friday
          + TED Radio Hour
          + Wait Wait...Don't Tell Me!
          + Weekend Edition Saturday
          + Weekend Edition Sunday
     * Listen
          + Hourly News
          + NPR Program Stream
          + Find Station Streams
          + Podcasts
          + More Ways To Listen
     * About
          + Contact Us
          + NPR Shop
          + Visit NPR
          + Careers at NPR
          + Press Room
          + 'This Is NPR' Blog
          + Support and Sponsor
          + Corrections
          + NPR Ombudsman
          + Permissions
          + Email Newsletters
          + RSS Feeds
          + The NPR API

   © 2014 NPR
     * Help
     * Contact
     * Terms of Use
     * Privacy
     * Sponsorship Choices
     * Text-Only

   © 2014 NPR
