   Skip to main content

     * About Us
     * Contact Us
     * FAQs
     * language icon Language Assistance
          + English
          + español
          + 中文: 繁體版
          + Việt-ngữ
          + 한국어
          + Tagalog
          + Русский

   Ed.gov Logo

   U.S. Department of Education
   Search for:
   ____________________ (Search)

     * Student Loans
     * Grants
     * Laws
     * Data


ConnectED: Learning Powered by Technology

Learning Powered by Technology

   President Obama and students with laptops

   “[T]oday, we're going to take a new step to make sure that virtually
   every child in America’s classrooms has access to the fastest Internet
   and the most cutting-edge learning tools. And that step will better
   prepare our children for the jobs and challenges of the future and it
   will provide them a surer path into the middle class.”

    President Barack Obama, June 6, 2013

The need

   A fast-growing world of technologies, and the extraordinary quantity
   and reach of content on the Internet, have the potential to bring
   remarkable new possibilities to teaching and learning—helping teachers
   work smarter and making learning more engaging for students.
   [expand/collapse]

   New technologies allow students to learn more, at their own pace and
   irrespective of geography, and to develop the knowledge and skills
   employers demand. Technology can provide teachers with opportunities to
   share best practices and personalize learning for students, and it
   allows parents to engage more deeply and immediately in their
   children’s learning. Yet, despite the great potential of technology to
   increase access and opportunity, too often, school is the least
   connected part of a student's life. Additionally, many teachers and
   principals are not getting the support that they need to use technology
   in ways that transform student learning.

   IFRAME:
   //www.youtube.com/embed/videoseries?list=PLRJNAhZxtqH-faGfkt99TzvPsvTgv
   tAqK

   IFRAME:
   //www.youtube.com/embed/videoseries?list=PLRJNAhZxtqH8GgDYtGJWfDidcAnae
   X2fs

The goal

   A wide range of technological innovations can help teachers make
   schools into incubators of exploration and invention. Such innovations
   also can help educators to become collaborators in learning, seeking
   new knowledge while continuously acquiring new skills alongside their
   students. [expand/collapse]

   All of that is possible when schools have appropriate technology, fast
   Internet connections, and supports that train educators to use new
   technologies and allow them to ensure the security and privacy of
   students’ information.

   Today, however, less than a third of educators say their school's
   Internet connection meets their teaching needs. Although 91 percent of
   teachers have access to computers in their classrooms, less than a
   quarter say they have the right level of technology. And teachers do
   not get enough training and support to integrate technology in their
   classrooms and lessons. President Obama has called for a bold, 5-year
   effort, with the goal of providing high-speed broadband and wireless to
   99 percent of students and improving the skills of teachers—providing
   every educator in America with support and training to integrate
   technology into classroom lessons.

The plan

   In 2010, the National Educational Technology Plan established a vision
   for how technology could provide students with access to engaging
   digital resources, opportunities to collaborate with peers and experts,
   and powerful tools to solve real problems as an integral part of their
   learning experience. The plan also aims to ensure that affordable
   devices are available to support students' digital learning, teachers
   are prepared to thrive in connected classrooms, and high-quality
   digital learning resources are available to teachers and students at
   any time and any place. [expand/collapse]

   Our schools must have modern technology infrastructure and our students
   must have access to the best resources—regardless of where they live—so
   that they are prepared to thrive in a globally connected world.

   In 2013, President Obama announced the ConnectED initiative, which aims
   to make the vision outlined in the National Educational Technology Plan
   a reality by ensuring classrooms across the country are connected to
   high-speed internet. The Federal Communications Commission (FCC)
   answered the President’s call to action, announcing efforts to
   modernize and expand the E-Rate program to more fully meet the needs of
   schools and libraries as they connect to high-speed broadband.

   In January 2014, the President announced that—with the support of the
   FCC—America will make a major down-payment on the goals of the National
   Educational Technology Plan and ConnectED, connecting more than 15,000
   schools over the next two years—without adding a dime to the deficit.

   And to help educators leverage new technologies and high-speed
   Internet, the Obama administration has announced the ConnectEDucators
   program, which would help educators to leverage technology and data to
   personalize learning and improve instruction, ensuring that—as schools
   increase access to broadband Internet through the ConnectED
   initiative—teachers and principals are prepared to use these resources
   in a way that increases student learning and achievement. This new
   proposed program would complement the efforts of local school districts
   to personalize learning through the Race to The Top-District program.

Partnerships

   The U.S. Department of Education will work with states and school
   districts to better use existing funding through the Elementary and
   Secondary Education Act to strategically invest in professional
   development for teachers, to help them keep pace with changing
   technological and professional demands.[expand/collapse]

   The FCC has begun the process to meet ConnectED goals by modernizing
   its E-Rate program to upgrade broadband speeds and Wi-Fi networks in
   our nation’s schools. As a down payment toward those goals, the FCC
   will take swift action to secure $2 billion over the next two years
   that will support high-speed upgrades. This down payment will ensure
   that up to 20 million more students will have access to 21st century
   technologies in their schools.

   Additionally, commitments from the private sector will allow our
   nation’s teachers and students to take full advantage of high-quality
   educational software (including applications) and feature-rich
   educational devices that are increasingly price-competitive with basic
   textbooks.

Learn more

     * White House ConnectED Fact Sheet [PDF]
     * Bringing America’s Students into the Digital Age – White House Blog
     * Closing the Broadband Gap for Students and Teachers – ED.gov Blog
     * ConnectEDucators
     * Race to the Top-District
     * Teachers and Leaders

   Tweet

   IFRAME:
   http://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.ed.gov%
   3A443%2Fconnected&layout=button_count&show_faces=false&width=250&action
   =like&font=arial&colorscheme=light&height=21

How Do I Find... ?

     * Student loans, forgiveness
     * College accreditation
     * No Child Left Behind
     * FERPA
     * FAFSA
     * More...

Information About...

     * Transforming Teaching
     * Family and Community Engagement
     * Early Learning
     * K-12 Reforms
     * More...


Connect

   Visit Secretary Arne Duncan on Facebook Facebook
   Visit Education on Twitter Twitter
   Visit Education on YouTube YouTube
   Sign Up for Email Updates Email
   Follow our RSS feed RSS
   Visit Education on Google+ Google+

   More >
   Our mission is to promote student achievement and preparation for
   global competitiveness by fostering educational excellence and ensuring
   equal access.
     * Student Loans
          + Repaying Loans
          + Defaulted Loans
          + Loan Forgiveness
          + Loan Servicers
     * Laws & Guidance
          + No Child Left Behind
          + FERPA
          + Civil Rights
     * About Us
          + Contact Us
          + ED Offices
          + Jobs
          + News
          + FAQs
          + Budget, Performance
     * Grants & Programs
          + Apply for Pell Grants
          + Grants Forecast
          + Open Grant Competitions
          + Find Grant Programs by Eligibility
     * Data & Research
          + Education Statistics
          + Integrated Postsecondary Education Data System
          + Nation's Report Card
          + What Works Clearinghouse

     * Notices
     * FOIA
     * Privacy
     * Security
     * Information quality
     * Inspector General
     * Whitehouse.gov
     * USA.gov
     * Benefits.gov
     * Regulations.gov
