
Govtech Fund

We harness the power of ◤transformers, ◤technology, and ◤capital to help
government become more efficient, responsive, and better able to serve
society.

   Menu Close

Govtech Fund

     * Home
     * Mission
     * Portfolio
     * Team
     * Search

   ‹ ›

   Founder of @GovtechFund @ronboug discusses the emerging govtech startup
   ecosystem on stage #cfasummit: http://t.co/dvLsHLvSXy via @YouTube

   September 24th, 2014

   A $23 million venture fund for the government tech set
   http://t.co/UJCy2hT7MA via @washingtonpost

   September 15th, 2014

   The @GovtechFund launches, raises $23M: first-ever VC fund dedicated to
   #govtech startups http://t.co/q7hSv8dhf7

   September 15th, 2014

   I Didn’t Always Code for America – http://t.co/ybwJSNx76g via
   @codeforamerica

   September 14th, 2014

   White House Announces Google Megan Smith As The Next Chief Technology
   Officer of the United States http://t.co/gxcWgaWKhR via @TechCrunch

   September 4th, 2014

   MindMixer Raises $17 Million to Build Better Communities — MindMixer
   BlogMindMixer Blog http://t.co/T7BF1yE45B #mindmixer

   September 2nd, 2014
   Follow @GovtechFund
   GovtechFund_Logo

Govtech Fund Launches, Raises $23M

   September 15, 2014

   Some great news to share today! We’re thrilled to announce the launch
   of the $23 Million Govtech Fund – the first-ever venture fund dedicated
   to government technology startups. Govtech startups we invest in build
   hardware and software tools for governments that are significantly
   better than existing technologies — built using modern application
   development practices and technology stacks, inspired from…
   GovtechFund_Logo

What Is Govtech?

   September 9, 2014

   At the Govtech Fund, we’re proud to be the first-ever venture capital
   fund dedicated to government technology startups. But what exactly do
   we mean by “govtech”?
   Logo

MindMixer Raises $17M To Build Better Communities

   September 2, 2014

   We love when Transformers are recognized for their effort. Our very own
   portfolio company, MindMixer, deserves this latest recognition and
   more.
   seamless docs

Turning Frustration Into Fantastic

   August 15, 2014

   CEO Jonathon Ende never imagined he would be building a govtech startup
   until a late night phone call changed everything.
   jonathon+Chachi

Get to know Jonathan + Chachi of SeamlessDocs

   August 7, 2014

   Govtech Fund What is your occupation? Jonathan Ende I am CEO of
   SeamlessDocs. I make sure that everything that goes on at SeamlessDocs
   is in line with our vision. Chachi Camejo As the CTO of SeamlessDocs,
   I’m responsible for building a robust yet easy to use application that
   will change the way the government collects…
   eyes

The $450B Govtech Market

   August 7, 2014

   As venture capitalists, we love big markets that are ripe for
   disruption – they’re where startups can create and capture the most
   value. A half-trillion dollar market is desperate for innovation and
   our startups are happy to deliver.
   jeff rubenstein

Get to know Jeff Rubenstein, Founder of SmartProcure

   August 6, 2014

   Jeff is an accomplished technology executive, entrepreneur, attorney,
   patent holder, government procurement expert, data transparency
   evangelist, and public safety officer.
   kansas city

Going to Kansas City

   July 10, 2014

   Our portfolio company MindMixer is settling into new digs in Kansas
   City, Mo., after moving its headquarters from Omaha, Neb. to Kansas
   City, where it already had a small operation.
   UK GDS

Inspiration From Across the Pond

   June 9, 2014

   If you’re looking for inspiration when it comes to government and
   technology, take a glance at the United Kingdom.
   Page12

   ^◤ Get in touch

   Name ____________________
   Email ____________________
   Message
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________
   submit

View Press Assets

     * Logo Files
     * Press Photos
     * and more
     __________________________________________________________________

   for Govtech Fund and
   our portfolio companies
     * Email
     * Facebook
     * Twitter
     * Newsletter
     * RSS

   © 2014 Govtech Fund

   Govtech Fund
   912 Cole St. #174
   San Francisco, CA 94117
