    ____________________

   Search Images Maps Play YouTube News Gmail Drive More »
   Send Feedback | Web History | Help | Sign in
   Home
   Home
   Profile
   People
   Photos
   Communities
   Events
   Hangouts
   Pages
   Local
   Settings
   Feedback
   Help  ·  Region
   Privacy & Terms  ·  Maps Terms
   [photo.jpg]
   Tim O'Reilly

Tim O'Reilly

   Shared publicly  -  2014-06-14

   "We don't need new policies. We need better implementation."
   Last night, I hosted Oakland City Councilor and mayoral candidate Libby
   Schaaf at a house party to introduce her to my neighbors. In response
   to a question about what to do about one of Oakland's many problems,
   she said "We don't need new policies.  We need better implementation."
    And in response to a question about disengaged city employees, she
   talked about the ones who really want to make a difference, and are
   just waiting to be activated.
   That resonated so strongly with me, because just the night before, I'd
   been at a talk by +Mikey Dickerson about the healthcare.gov rescue
   effort, which sounded almost exactly the same notes.  It's easy to
   imagine heroic Silicon Valley coders riding to the rescue, but Mikey
   pointed out that they wrote very little code.  Much of the rescue work
   was done by the same people who built the broken site.  What the
   Silicon Valley team provided was clear management focus from people who
   knew what they were doing. They were able to debug all the bad process
   and broken communications between the various contractors who'd built
   the site, figure out what they needed from each of them, and then
   encourage and bring out the best in those people. They also had the
   guts and the force of will to get the recalcitrants on board.  (I wrote
   more about this at http://bit.ly/healthcare_rescue )
   So much of the work we do at Code for America is drawn from the same
   playbook (though we usually don't have the kind of mandate that the
   "Code Red" healthcare.gov rescue team did!)  It's about debugging a
   process, making small tech interventions, but even more about helping
   "the system" to work better by understanding needs and figuring out why
   they aren't being met.  (See for example Jake Solomon's brilliant post
   about his work in San Francisco last
   year: https://medium.com/@lippytak/people-not-data-47434acb50a8)
   We have a constant parade of politicians who tell us what we want to
   hear: that they have a new policy idea, and that if we follow their
   advice, everything will be great.  This kind of "magic bullet" thinking
   is what gets us the same dismal results, over and over.  To be sure,
   there are times when we do need new policies, and I'm sure Libby has
   her share of policy ideas too.  But getting away from policy and
   digging into implementation is so important! So much of the problem
   isn't what we set out to do, it's how we do it.  I love hearing someone
   speak truth about that.
   P.S. As a city councilor, Libby is in a non-executive role.  If she is
   in charge of actual implementation, I'm super-excited to see what she
   can do.  If you're an Oakland city resident, I hope you turn out and
   vote for her in November.  If you'd like to learn more, I'm co-hosting
   another, bigger event for Libby at the new (still under construction)
   BlueSprout Maker space in Oakland next Sunday.  Sign up to attend here:
   http://www.eventbrite.com/e/libbyraiser-tickets-11878702519﻿
   [IMG_20140613_184628374_HDR.jpg]
   Tim O'Reilly's photos
   188
   23
   Matt Barger's profile photo Chris Kirby's profile photo Erickerik
   Rubio's profile photo jeff williams's profile photo
   12 comments
   Brian Bulkowski
   +
   3
   4
   3
   Reply

   Yes, yes on this message. When the people I'm working with get fired
   up, there's nothing we can't do. I see it in myself.
   When I'm dragged down with "oh, no one cares", "oh, even if I work hard
   this will get F'ed up", "oh, life is just a crap shoot", nothing gets
   done right --- or gets done at all.
   At a government level, we need to remove the infighting and poor
   incentives that drag people down. If just putting in your time gets you
   a pension, and your manager is just putting in their time, all the way
   up the line, of course we won't be accomplishing anything.
   This political idea of "personal responsibility" - where we are all out
   for ourselves, no sense of community, no idea of helping each other,
   just dog-eat-dog, I don't get inspired. When I work to help other
   people, I simply feel taken advantage of. They're getting my time and
   energy, there's no reciprocity.
   Politically, we need to collectively break the dislike and distrust
   that capitalism breeds. There must be a blend of competition and rules
   - a fair playing field - that we all, as a society, agree with ---
   agree that as a society we will accomplish more, live better, not just
   make the 0.01% richer.
   Such is the pernicious nature of inequality and inequity America has
   drifted toward.﻿
   Timothy W
   +
   0
   1
   0
   Reply

   Anybody would be an improvement over Quan. Good luck!﻿
   Linda G
   +
   0
   1
   0
   Reply

   Excuse my french but im in france﻿
   Timothy W
   +
   0
   1
   0
   Reply

   +Melinda Gice Congratulations ﻿
   jeff williams
   +
   0
   1
   0
   Reply

   for blue sprout next week can you guys prep more ham & less spam on the
   "made in oakland" thing? i.e. specific, non-policy action items. as a
   creator of high tech oakland mfg jobs i want to understand.﻿
   Tim O'Reilly
   +
   0
   1
   0
   Reply

   +jeff williams Do you have specific prescriptions yourself?  I have
   asked Libby to come prepared to talk to these issues.  But it's also a
   great opportunity to inform her position. It sounds like you have
   things that you wish Oakland would be doing.  I'd love to hear them
   too.﻿
   Tim O'Reilly
   +
   0
   1
   0
   Reply

   +Melinda Gice Sorry about that.  It would be nice if there were an easy
   way to geotarget posts, but there isn't.  And I do think that the
   points I made apply generally to government everywhere.  I would
   imagine especially in France :-)﻿
   Brian Sexton
   +
   0
   1
   0
   Reply

   This reminds me of my own frustration about how a team upon which I
   have worked has been grown and utilized. The team has repeatedly added
   people when it has seemed to me that there has been plenty of capacity
   for improving project productivity, quality, and process with existing
   engineering resources. Adding parts to a machine is not always the most
   efficient or effective way to go achieve better results; sometimes the
   machine just needs a little realignment, a little oil, and perhaps to
   be used a little differently.﻿
   Erickerik Rubio
   +
   0
   1
   0
   Reply

   THIS MORNIN,,,I HOSTED A LIL LIFE VENTURE,,WITH MY NEPHEWS SON.HES ONLY
   2.﻿
   jeff williams
   +
   0
   1
   0
   Reply

   i look forward to hearing her plan on the 22nd! you're probably on the
   right track to good-wage mfg jobs growth. (my hint: protect mini
   factory/fab pockets in-and-around housing & offices. i.e. don't allow
   conversion of every old building into a loft.)﻿
   Chris Kirby
   +
   0
   1
   0
   Reply

   Every time people try to make govt work better the rich get richer.
   Democracy was a scam sold to the weak minded and weak willed. ﻿
   keiko saito
   +
   0
   1
   0
   Reply

   Desde que o Mundo existe foi assim: Ricos ficam cada vez mais
   Ricos...*< Democracia? 0 que e isto?﻿
   Translate
   Add a comment...
   Start a hangout
