   #Politics

   Quantcast

   [p?c1=2&c2=7420740&c3=&c4=&c5=&c6=&c15=&cv=2.0&cj=1]

   The Week Logo
   RSS
   ________________________________________
   [magazines.png?209]
   Subscribe
   Give a gift
   Digital subscription
     * World
     * U.S.
     * Politics
     * Business
     * Tech
     * Science
     * Arts
     * Lifestyle
     * Speed Reads
     * Idea Factory
     * Cartoons
     * Puzzles
     * [shopping_cart1.png?209] STORE



   The GOP's lame attempt to blame Obama for the failure of immigration
   reform
   Surprise! Republicans aren't serious about reform.
   By Jon Terbush | February 7, 2014


   Just point the blame away.
   Just point the blame away. (Drew Angerer/Getty Images)

   This week, it became all too clear that House Republicans don't really
   want to address immigration reform in any meaningful way this year. And
   if the reform effort does wither on the vine, Republicans know just who
   to blame: themselves.

   Ha, just kidding. They're going to blame President Obama.

   A mere week after unveiling a list of immigration "principles" that the
   GOP would pursue, Speaker of the House John Boehner (R-Ohio) said
   Thursday that handling immigration this year would be "difficult,"
   because many Republicans don't trust Obama.

   "There's widespread doubt about whether this administration can be
   trusted to enforce our laws," he said. "And it's going to be difficult
   to move any immigration legislation until that changes."

   Of course, a bipartisan immigration reform package has already passed
   the Senate, which includes an eye-popping $40 billion for border
   security. Obama has even signaled that he would be prepared to sign
   into law a more modest package, including one that bestowed only legal
   status — as opposed to citizenship — to undocumented workers.

   The obstacle to reform has always been in the GOP-controlled House,
   where hardcore conservatives have opposed any law that bears even a
   whiff of amnesty. That, in turn, has spooked potential reform
   supporters who are wary of a primary challenge.

   Indeed, Boehner's so-called principles can be seen as a trial balloon
   that was quickly deflated by members of his own party, including
   influential conservative writers like The Weekly Standard's William
   Kristol, who argued that the issue unnecessarily divided the GOP ahead
   of the 2014 midterms.

   Boehner's remarks were still notable, though, in that they are part of
   a ridiculous attempt to pin the blame on Obama, a strategy that
   Republicans have been testing out for months.

   Back in October, Sen. Marco Rubio (R-Fla.), who helped author the
   Senate's immigration bill before fleeing to chase down his lost
   conservative credibility, said Obama poisoned immigration reform by
   standing firm through the government shutdown and debt ceiling fight.
   By not agreeing to the GOP's fantastical demands that he gut his
   health-care law, Rubio said, Obama made immigration reform "harder to
   achieve."

   "The president has undermined this effort, absolutely, because of the
   way he has behaved over the last three weeks," he said.

   To be sure, some on the right have charged all along that the White
   House can't be trusted to meet tough border security and verification
   requirements, necessitating "specific enforcement triggers" before a
   path to citizenship or legal status could even come into play. What's
   different now is that the claim has gone mainstream, a reflection of
   how desperate the GOP is to convey to Latino voters that they would do
   something on immigration were it not for Obama.

   A sampling from the past week:
     * Rep. Paul Ryan (R-Wis.): "Here's the issue that all Republicans
       agree on — we don't trust the president to enforce the law."
     * House Majority Leader Eric Cantor (R-Va.): "There's some real
       question of trust here and the White House continues to really
       thumb its nose up, if you will, at the Congress."
     * Rubio (again): "We just don't think government will enforce the law
       anyway."

   As Slate's David Weigel explains, the argument is pretty much bunk:

   Say the Senate bill was passed in the House tomorrow, conferenced, and
   signed by the president. He's got three years left in office. The
   legalization component of the Senate bill depends on a border security
   standard that's going to be determined by a panel of state governors.
   They have five years to sign off. If you think about the timing of the
   Affordable Care Act — passed in 2010, implemented at the end of 2013 —
   there's no real danger of Obama using a new immigration law to grant
   more amnesty. He could do that right now.

   So, file these talking points under "Republicans Looking Busy." [Slate]

   But Boehner can't spike immigration reform without first finding a
   scapegoat to blame for its failure. And since Senate Republicans are on
   board, who else is there to blame but the ultimate conservative
   bogeyman?


   Jon Terbush
   Follow @jonterbush
   Jon Terbush is an associate editor at TheWeek.com covering politics,
   sports, and other things he finds interesting. He has previously
   written for Talking Points Memo, Raw Story, and Business Insider.


   Sponsor content


EDITORS' PICKS

THE WEEK'S AUDIOPHILE PODCASTS: LISTEN SMARTER

   IFRAME:
   https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/users
   /37514747&color=ed1b24&auto_play=false&hide_related=false&show_artwork=
   true&show_user=false

   Hide Comments
   GET 4 FREE ISSUES of THE WEEK
   CLICK HERE
   MOST POPULAR ON THE WEEK
    1. How to be the most productive person in your office — and still get
       home by 5:30 p.m.
    2. 43 TV shows to watch in 2014
    3. How our botched understanding of 'science' ruins everything
    4. Save the world... by changing how you pee
    5. Why the Chinese military is only a paper dragon
    6. 6 things the happiest families all have in common
    7. Christian conservatives have a terrifying new bogeyman: The
       Christian leftist
    8. Libertarianism's terrible, horrible, no good, very bad idea
    9. The battle over e-cigarettes
   10. How ancient DNA is rewriting human history


   Sponsor content


   CARTOONS
   Sign up for our free email newsletters
   ____________________ Sign Up
   AND FOLLOW US ON

   [fb_subscribe.png?209]

   [twitter_subscribe.png?209]

   [subscribe_rss.png?209]
   [blank_between.png?209]
   MOST POPULAR ON THE WEEK
    1. How to be the most productive person in your office — and still get
       home by 5:30 p.m.
    2. 43 TV shows to watch in 2014
    3. How our botched understanding of 'science' ruins everything
    4. Save the world... by changing how you pee
    5. Why the Chinese military is only a paper dragon
    6. 6 things the happiest families all have in common
    7. Christian conservatives have a terrifying new bogeyman: The
       Christian leftist
    8. Libertarianism's terrible, horrible, no good, very bad idea
    9. The battle over e-cigarettes
   10. How ancient DNA is rewriting human history

   Subscribe to the Week
              [subscribe_footer_updated_arrows_order1.jpg?209]
              [subscribe_footer_updated_arrows_order2.jpg?209]
              [subscribe_footer_updated_arrows_order3.jpg?209]
   unknown

   /   CURRENT ISSUE / GIVE A GIFT / BACK ISSUES / CLASSROOM SUBSCRIPTIONS
   / RSS
   AD INFO / PRIVACY POLICY / TERMS & CONDITIONS / THE WEEK UK / SITE MAP
   / CUSTOMER SERVICE / CONTACT US

   © 2014 THE WEEK Publications, Inc. All rights reserved. THE WEEK® is a
   registered trademark owned by Felix Dennis. THEWEEK.COM is a trademark
   owned by Felix Dennis.
