   #Sauropod Vertebra Picture of the Week » Feed Sauropod Vertebra Picture
   of the Week » Comments Feed Sauropod Vertebra Picture of the Week » Can
   PeerJ really be only a year old? Comments Feed Photography and
   illustration talk, Part 3: Backdrops and lighting Horrible sauropod
   skulls of the Yale Peabody Museum, part 1: Morosaurus lentus, the
   world’s most foolish sauropod alternate alternate Sauropod Vertebra
   Picture of the Week WordPress.com

Sauropod Vertebra Picture of the Week

   SV-POW! … All sauropod vertebrae, except when we're talking about Open
   Access

Can PeerJ really be only a year old?

February 12, 2014

   Today (12th February) is the one-year anniversary of the first PeerJ
   papers! As Matt put it in an email this morning:

     Hard to believe it’s been a year already. On the other hand, it’s
     also hard to believe that it’s only been a year. PeerJ is just such
     an established part of my worldview now.

   That’s exactly right. PeerJ has so completely rewritten the rule-book
   (on price, speed and quality of service) that now when I’m thinking
   about new papers I’m going to write, the question I ask myself is no
   longer “Where shall I send this?” but “Is there any reason not to send
   it to PeerJ?”
   dorsals-ab-composite

   Dorsals A and B (probably D8 and D9) of NHM R5937, “The Archbishop”, a
   still-undescribed brachiosaurid sauropod from the Upper Jurassic
   Tendaguru Formation of Tanzania, which I will get done this year, and
   which is destined for PeerJ. Top row: dorsal view with anterior to the
   right. Bottom row, from left to right: left lateral, posterior, right
   lateral, anterior.

   Yesterday in the comments of a post on The Scholarly Kitchen, Harvey
   Kane asked me “I am curious as to where you get the notion that
   publishing OA is less expensive and in some way “better” than the
   traditional model?” My reply was (in part):

     My notion that OA publishing yields better results than traditional
     is rooted in the online-only nature of articles, which allows them
     to ignore arbitrary limits on word-count, number of figures, use of
     colour, etc., and to exploit online-only formats such as video, 3d
     models, CT-slice stacks, etc. In my own field of vertebrate
     palaeontology, it’s now routine to see in PLOS ONE descriptive
     articles that are many times more comprehensive than their
     equivalents in traditional journals — see for example the recent
     description of the frog Beelzebufo.

     Of course there is nothing specific to open-access about this: there
     is no technical reason why an online-only subscription journal
     shouldn’t publish similarly detailed articles. But my experience so
     far has been that they don’t — perhaps because they are tied to the
     mindset that pages and illustrations are limited resources.

   For Beelzebufo in PLOS ONE, read baby Parasaurolophus in PeerJ, which
   we described as “the world’s most open-access dinosaur“. This paper is
   83 pages of technicolour goodness, plus all the 3d models you can eat.
   And the crazy thing is, this sort of detail in descriptive papers is
   not even exceptional any more — see for example the recent description
   of Canardia in PLOS ONE, or this analysis of croc respiration in PeerJ

   Years ago, I said that in the Archbishop descriptions I wanted to raise
   the bar for quality of illustration. Well, I’ve taken so long over
   getting the Archbishop done that the bar has been raised, and now I’m
   scrambling to catch up. Certainly the illustrations even in our 2011
   description of Brontomerus are starting to look a bit old-fashioned.

   And of course, the truly astonishing thing about PeerJ is that it does
   this so very cheaply. Because I’m already a member (which cost me $99),
   the Archbishop description is going to be free to me to publish this
   year. (This year for sure!) If we also get our Barosaurus neck preprint
   published properly this year,then I’ll have to find $100 to upgrade my
   Basic membership to Enhanced. That’s cheap enough that it’s not even
   worth going through the hassle of trying to get Bristol to pay for me.
   And if I ever hit a year when I publish three or more papers, I’ll
   upgrade once more (for another $100) to the Investigator plan and then
   that’s it: I’m done paying PeerJ forever, however many papers I publish
   there. (Matt jumped straight to the all-you-can-eat plan, so he
   wouldn’t even have to think about it ever again.)
   Barosaurus lentus holotype YPM 429, Vertebra Q (C?13). Top row: left
   ventrolateral view. Middle row, from left to right: anterior view, with
   ventral to the right; ventral view; posterior view, with ventral to the
   left. Bottom row: right lateral view, inverted. Inset shows
   diapophyseal facet on right side of vertebra, indicating that the
   cervical ribs were unfused in this individual despite its great size.
   Note the broad, flat prezygapophyseal facet visible in anterior view.
   (Taylor and Wedel 2013b: figure 6)

   Barosaurus lentus holotype YPM 429, Vertebra Q (C?13). Top row: left
   ventrolateral view. Middle row, from left to right: anterior view, with
   ventral to the right; ventral view; posterior view, with ventral to the
   left. Bottom row: right lateral view, inverted. Inset shows
   diapophyseal facet on right side of vertebra, indicating that the
   cervical ribs were unfused in this individual despite its great size.
   Note the broad, flat prezygapophyseal facet visible in anterior view.
   (Taylor and Wedel 2013b: figure 6)

   PeerJ’s pricing is making PLOS ONE’s $1350 APC look distinctly
   old-fashioned; and the $3000 charged by the legacy publishers (for a
   distinctly inferior product) is now frankly embarrassing. You might
   expect that as such low prices, PeerJ’s quality of service would
   suffer, but that’s not been our experience: editing, reviewing,
   typesetting and proofing for our neck-anatomy paper were all up there
   with the best we’ve received anywhere.

   And it’s great to see that it’s not just minor researchers like Matt
   and me who are persuaded by PeerJ: they’ve now accumulated a frankly
   stellar list of 20 universities (so far) with institutional plans for
   researchers to publish there. When I say “stellar” I mean that the list
   includes Harvard, MIT, Cambridge, Berkeley, Stanford, Johns Hopkins,
   UCL, Carnegie Mellon, Duke … the list goes on.

   We can only hope that the next year, and the next ten and twenty, are
   as successful for PeerJ as the first has been; and that other New
   Generation publishers will join it in pushing the field forward.

   I leave the last word to Matt:

     I’m getting Vicki a lifetime membership for Valentine’s Day. Because
     I’m a romantic.

   She’s a lucky, lucky woman.
   About these ads

Share this:

     * Facebook
     * Reddit
     * Twitter
     * Google
     *

Like this:

   Like Loading...

Related

   Posted by Mike Taylor
   Filed in Barosaurus, Gratuitously awesome images, open access, PeerJ,
   PeerJ Preprints, The Archbishop
   Leave a Comment »

Leave a Reply Cancel reply

   Enter your comment here...

   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________

   Fill in your details below or click an icon to log in:
     *
     *
     *
     *
     *

   Gravatar
   Email (required) (Address never made public)
   ____________________
   Name (required)
   ____________________
   Website
   ____________________
   WordPress.com Logo

   You are commenting using your WordPress.com account.
   ( Log Out / Change )
   Twitter picture

   You are commenting using your Twitter account. ( Log Out / Change )
   Facebook photo

   You are commenting using your Facebook account. ( Log Out / Change )
   Google+ photo

   You are commenting using your Google+ account. ( Log Out / Change )
   Cancel

   Connecting to %s

   [ ] Notify me of new comments via email.

   [ ] Notify me of new posts via email.

   Post Comment

   « Photography and illustration talk, Part 3: Backdrops and lighting
   Horrible sauropod skulls of the Yale Peabody Museum, part 1: Morosaurus
   lentus, the world’s most foolish sauropod »
     * Search for: ____________________ Search
     * Creative Commons License
       Sauropod Vertebra Picture of the Week by Mike Taylor, Matt Wedel,
       Darren Naish is licensed under a Creative Commons Attribution 3.0
       Unported License.
       [c141.png] RSS Feed
       T-shirt, front
       Get your relative-lengths-of-sauropod-necks T-shirt!
     * Pages
          + About SV-POW!
          + The Shiny Digital Future
          + Tutorials
          + Human anatomy study materials
          + Things to Make and Do
          + Your noun is adjective
          + How adjective was taxon?
          + Posts on Paleoart
          + What they’re saying about SV-POW!
          + Papers by SV-POW!sketeers
               o Taylor (2014 for 2004) on dinosaur diversity
               o Wedel and Taylor (2013b) on caudal pneumaticity
               o Taylor and Wedel (2013c) on neck cartilage
               o Taylor and Wedel (2013b) on the neck of Barosaurus
               o Wedel and Taylor (2013) on sauropod neural
                 spine bifurcation
               o Taylor and Wedel (2013a) on sauropod neck anatomy
               o Wedel (2012) on long nerves of sauropods
               o Yates, Wedel, and Bonnan (2012) on
                 prosauropod pneumaticity
               o Taylor, Hone, Wedel and Naish (2011) on sexual selection
                 of sauropod necks
               o Taylor, Wedel and Cifelli (2011) on Brontomerus
               o Taylor (2010) on the history of sauropod research
               o Taylor (2009) on the inevitability of electronic
                 publishing of nomenclatural acts
               o Taylor (2009) on Brachiosaurus and Giraffatitan
               o Taylor, Wedel and Naish (2009) on neck posture
               o Upchurch, Martin, and Taylor (2009) on Cetiosaurus
                 nomenclature
               o Wedel (2009) on air sacs
               o Taylor and Naish (2007) on Xenoposeidon
          + Checklist for new zoological genus and species names
            [DRAFT v3]
          + Open Access Bio and Paleo [UNMAINTAINED]
     * Recent Posts
          + Does anyone want a project? How can we understand sauropod
            neck cartilage better?
          + Tutorial 28: how to remember the branches of the internal
            iliac artery
          + Wheelbarrow handles for vertebrae? The cervical rib bundles of
            Sauroposeidon and other sauropods
          + Move over, All Yesterdays: It’s time for
            #MikeTaylorAwesomeDinoArt!
          + The CC By licence does not let people distort and misrepresent
            your work
     * Recent Comments

       Bryan Riolo on Guest post: the genesis of Dav…
       John Scanlon on Guest post: the genesis of Dav…
       Mike Taylor on Gender balance at SVPCA
       Victoria Arbour (@Vi… on Gender balance at SVPCA
       Phil Cox on Gender balance at SVPCA
     * Archives
          + September 2014
          + August 2014
          + July 2014
          + June 2014
          + May 2014
          + April 2014
          + March 2014
          + February 2014
          + January 2014
          + December 2013
          + November 2013
          + October 2013
          + September 2013
          + August 2013
          + July 2013
          + June 2013
          + May 2013
          + April 2013
          + March 2013
          + February 2013
          + January 2013
          + December 2012
          + November 2012
          + October 2012
          + September 2012
          + August 2012
          + July 2012
          + June 2012
          + May 2012
          + April 2012
          + March 2012
          + February 2012
          + January 2012
          + December 2011
          + November 2011
          + October 2011
          + September 2011
          + August 2011
          + July 2011
          + June 2011
          + May 2011
          + April 2011
          + March 2011
          + February 2011
          + January 2011
          + December 2010
          + November 2010
          + October 2010
          + September 2010
          + August 2010
          + July 2010
          + June 2010
          + May 2010
          + April 2010
          + March 2010
          + February 2010
          + January 2010
          + December 2009
          + November 2009
          + October 2009
          + September 2009
          + August 2009
          + July 2009
          + June 2009
          + May 2009
          + April 2009
          + March 2009
          + February 2009
          + January 2009
          + December 2008
          + November 2008
          + October 2008
          + September 2008
          + August 2008
          + July 2008
          + June 2008
          + May 2008
          + April 2008
          + March 2008
          + February 2008
          + January 2008
          + December 2007
          + November 2007
          + October 2007
     * 100% totally real Apatosaurus Art brachiosaurids Brachiosaurus
       caudal cervical collections diplodocids Diplodocus dorsal
       Giraffatitan goofy life restorations mounts museums necks open
       access papers by SV-POW!sketeers pneumaticity rants Sauroposeidon
       Shiny digital future size stinkin' heads stinkin' mammals stinkin'
       publishers stinkin' theropods titanosaur Tutorial
     * Top Posts
          + Human anatomy study materials
          + Tutorial 25: How to Study for Gross Anatomy (and Just About
            Everything Else)
          + Does anyone want a project? How can we understand sauropod
            neck cartilage better?
          + Guest post: the genesis of Davide Bonadonna's
            <i>Spinosaurus</i> painting
          + Elsevier is taking down papers from Academia.edu
          + Tutorial 15: the bones of the sauropod skeleton
          + Tutorial 28: how to remember the branches of the internal
            iliac artery
          + The world's longest cells? Speculations on the nervous systems
            of sauropods
          + <i>Spinosaurus</i> fishiness, part <i>n</i>
          + <i>Brachiosaurus</i>: both bigger and smaller than you think
     * Blogroll
          + 10 Minute Astronomy
          + @MikeTaylor on Twitter
          + Darren Naish
          + Echo Station 5-7
          + Matt Wedel
          + Mike Taylor
          + Scholarly Closed Access
          + The Open Dinosaur Project
          + The Reinvigorated Programmer
     * Blog Stats
          + 2,361,209 hits

   Blog at WordPress.com. The Simpla Theme.

   Follow

Follow “Sauropod Vertebra Picture of the Week”

   Get every new post delivered to your Inbox.

   Join 397 other followers

   Enter your email add

   Sign me up
   Powered by WordPress.com

   IFRAME: likes-master

   %d bloggers like this:
