    #YouTube Video Search alternate alternate alternate TechSummit 2014 -
   Message from Jennifer Pahlka TechSummit 2014 - Message from Jennifer
   Pahlka

   YouTube home
   (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
   [pixel-vfl3z5WfW.gif]
   Upload (BUTTON) Sign in
   (BUTTON) Search
   ____________________

   Loading icon Loading...

This video is unavailable.

   [pixel-vfl3z5WfW.gif]

Watch Queue

TV Queue

   [pixel-vfl3z5WfW.gif]
   Watch QueueTV Queue
   (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
     * Remove all
     * Disconnect

   (BUTTON) Previous video (BUTTON) Play (BUTTON) Pause (BUTTON) Next
   video
       Loading icon Loading...

   Watch Queue
   TV Queue
   __count__/__total__

   [pixel-vfl3z5WfW.gif]
   Find out why (BUTTON) Close

TechSummit 2014 - Message from Jennifer Pahlka

   CIO Estado Libre Asociado de Puerto Rico
   CIO Estado Libre Asociado de Puerto Rico
   (BUTTON) [pixel-vfl3z5WfW.gif] SubscribeSubscribedUnsubscribe (BUTTON)
   [pixel-vfl3z5WfW.gif] 37

Subscription preferences

   Loading...

   Loading icon Loading...
   Working...
   (BUTTON) [pixel-vfl3z5WfW.gif] Add to

Want to watch this again later?

   Sign in to add this video to a playlist.
   Sign in
   (BUTTON) [pixel-vfl3z5WfW.gif] Share
   (BUTTON) [pixel-vfl3z5WfW.gif] More
     * (BUTTON) [pixel-vfl3z5WfW.gif] Report
     * (BUTTON) [pixel-vfl3z5WfW.gif] Transcript
     * (BUTTON) [pixel-vfl3z5WfW.gif] Statistics

   117 views
   (BUTTON) [pixel-vfl3z5WfW.gif] 2

Like this video?

   Sign in to make your opinion count.
   Sign in
   (BUTTON) I dislike this 0

Don't like this video?

   Sign in to make your opinion count.
   Sign in

   Loading icon Loading...

   Loading icon Loading...

Transcript

   The interactive transcript could not be loaded.

   Loading icon Loading...

   Loading icon Loading...
   Sign in
   Ratings have been disabled for this video.
   Rating is available when the video has been rented.
   This feature is not available right now. Please try again later.
   (BUTTON) [pixel-vfl3z5WfW.gif]

   Published on Jun 4, 2014

   Message from Jennifer Pahlka for the Tech Summit 2014.
   Jennifer Pahlka is the founder and Executive Director of Code for
   America, currently serving as the United States Deputy Chief Technology
   Officer for government innovation.
     * Category
          + Science & Technology
     * License
          + Standard YouTube License

   (BUTTON) Show more (BUTTON) Show less

   Loading icon Loading...

     * 21:51 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Dave
       Troy Data Visualization by CIO Estado Libre Asociado de Puerto Rico
       31 views
     * 28:24 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Code
       For America Panel by CIO Estado Libre Asociado de Puerto Rico 18
       views
     * 12:45 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Magic's 'Rush' special by magicfm1054 79,353 views
     * 14:38 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Alberto Lazaro The Gigabit Island by CIO Estado Libre Asociado de
       Puerto Rico 18 views
     * 16:09 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Code
       For America Biz Wallet by CIO Estado Libre Asociado de Puerto Rico
       17 views
     * 7:46 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Rocky
       vs Ivan Drago (Rocky IV) - Training Montage HD 720p by Sting WCW
       76,620 views
     * 8:07 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Jean-Claude Van Damme: Bloodsport Final Fight (1988) - High Quality
       by KSVideos 17,975,104 views
     * 57:15 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Coding
       the Next Chapter of American History with Jennifer Pahlka by The
       Aspen Institute 119 views
     * 36:56 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue UI no
       es lo mismo que UX by Mejorando.la 15,657 views
     * 3:41 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Rush:The Real Meaning of RUSH (James Hunt Final Race) by Yasser
       Saeed 27,772 views
     * 35:18 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Edward
       Snowden: Here's how we take back the Internet by TED 933,700 views
     * 3:38 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue A
       Man's Brain - Studio C by BYUtv 185,093 views
     * 6:38 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Larry
       Bird - Trash Talking by BasketballJones48021 660,556 views
     * 6:10 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue Tech
       Summit 2014 by CIO Estado Libre Asociado de Puerto Rico 1,580 views
     * 3:42 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue The
       Pretender Pencil! by kipkay 1,601,240 views
     * 4:56 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Understanding Limited Slip Differential by Learn Engineering
       168,929 views
     * 48:24 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       @Google & YouTube present A Conversation with Conan O'Brien by
       Talks at Google 1,801,944 views
     * 7:53 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Coulthard and Hakkinen celebrate 50 years of McLaren by driving
       classic championship winning cars by James Love 343,179 views
     * 2:36 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Introducing the NutriBullet Pro - 900 Series by NutriBullet 53,582
       views
     * 6:51 (BUTTON) [pixel-vfl3z5WfW.gif] [pixel-vfl3z5WfW.gif]
          + [pixel-vfl3z5WfW.gif] Play next
          + [pixel-vfl3z5WfW.gif] Play now
       (BUTTON) Watch Later [pixel-vfl3z5WfW.gif] (BUTTON) TV Queue
       Michael Schumacher shatters the morale! by fadedsideways 717,504
       views
     * Loading more suggestions... (BUTTON) Show more

   [pixel-vfl3z5WfW.gif]
     * (BUTTON) [pixel-vfl3z5WfW.gif] Language: English
       [pixel-vfl3z5WfW.gif]
     * (BUTTON) Country: Worldwide [pixel-vfl3z5WfW.gif]
     * (BUTTON) Safety: Off [pixel-vfl3z5WfW.gif]

   (BUTTON) [pixel-vfl3z5WfW.gif] Help

   Loading icon Loading...

   Loading icon Loading...

   Loading icon Loading...
     * About
     * Press & Blogs
     * Copyright
     * Creators & Partners
     * Advertising
     * Developers
     * +YouTube

     * Terms
     * Privacy
     * Policy & Safety
     * Send feedback
     * Try something new!
     *

   Loading...
   Working...

   Sign in to add this to Watch Later

Add to

   IFRAME:
   //p2-glu65gpwp4nve-nxnr3mh6tvf5w4rf-if-v6exp3-v4.metric.gstatic.com/v6e
   xp3/iframe.html
