   #RSS

   Content Tabs

Download Safari Books Online apps: Apple iOS | Android | BlackBerry

   Entire Site [BUTTON Input] (not implemented)_____
     * Entire Site
     * Titles Only
     * Short Cuts
     * Rough Cuts

   ____________________ Submit

   Advanced Search

   Advanced Search

Safari Books Online

     * Help
       Help
          + Support Home
          + Alerts
          + Top Knowledge Items
          + Frequently Asked Questions
          + Account Management
          + Billing
          + Content
          + Content Reader
          + Mobile
          + Offline Reading
     * Sign In
     * Reactivate
     * Sign Up

   Free Trial

   Safari is a digital library providing on-demand subscription access to
   thousands of learning resources.
   Share
   Fluent Conference 2014: JavaScript & Beyond Complete Video Compilation
     * Video
     * Fluent Conference 2014: JavaScript & Beyond Complete Video
       Compilation
     * By: O'Reilly Media, Inc.
     * Publisher: O'Reilly Media, Inc.
     * Pub. Date: April 01, 2014
     * Running Time: 46 hours 18 minutes 7 seconds
     * Subscriber Rating: 4.714285714285714 out of 5 rating
       4.714285714285714 [7 Ratings] Subscriber Reviews

   en

   Flash Player 10 or higher is required.
   Please download the Flash Player and install the latest version before
   continuing.

   Flash Player 10 or higher is required.
   Please download the Flash Player and install the latest version before
   continuing.

Fluent Conference 2014: JavaScript & Beyond Complete Video Compilation

     * Overview
     * Table of Contents
     * Extras
     * Help

   Subscriber Reviews • Browse Similar Topics

Overview

Other Videos in This Category

   If you missed the 2014 Fluent Conference in San Francisco this past
   March, you can still take in every workshop, session, and keynote with
   this complete video compilation of the event. Catch up with this year’s
   lineup of speakers—seasoned pros as well as notable newcomers—as they
   share their experience and expertise on the emerging methods, tools,
   and technologies of the Web Platform: JavaScript, HTML5, CSS3, and
   more.

Subscriber Reviews

   Average Rating: 4.714285714285714 out of 5 rating  Based on 7 Ratings

   "A good video collection." - by Shamal Jayakody on 02-MAY-2014
   Reviewer Rating: 1 star rating 2 star rating 3 star rating 4 star
   rating 5 star rating
   A good video collection. Very nice.
   Report as Inappropriate

   "Very good, fast overview for experienced devs" - by gluis on
   22-APR-2014
   Reviewer Rating: 1 star rating 2 star rating 3 star rating 4 star
   rating 5 star rating
   The four videos cover a lot of ground and do so in a way that doesn't
   insult the viewer. The target audience is someone experienced with JS
   and who is interested in learning some of the ways this framework
   operates. If you know very little about AngularJS and already know JS,
   this is a good place to start.
   Report as Inappropriate

Browse Similar Topics

   Top Level Categories:
   Information Technology & Software Development

   Sub-Categories:
   Information Technology & Software Development > Web Development

Table of Contents

   Chapter/Selection

   Time

   Keynotes

   O'Reilly Web Platform Award Winners Announced

   Description:
   The winners of the first annual O'Reilly Web Platform Awards are
   announced.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:04:16

   The Humble Border-Radius - Lea Verou

   Description:
   Lea Verou, Developer Relations, W3C

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:13:59

   Speed, Performance, and Human Perception - Ilya Grigorik

   Description:
   Performance is a feature, but what exactly is performance? Should UX be
   part of it and are there design principles that will help us deliver
   experiences that "feel faster"? What does it mean for a site to "feel
   fast" anyway and what is fast enough?

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:15:58

   Keynote with Paul Irish - Paul Irish

   Description:
   Paul Irish, Chrome Developer Advocate, Google

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:23:24

   Keynote with Jen Simmons - Jen Simmons

   Description:
   Jen Simmons, Designer, Jen Simmons Design

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:12:17

   Understand Your User's Experience - Christine Sotelo

   Description:
   Front-end performance bottlenecks and errors leave a lasting impression
   on your customers. This is not the impression you want. Christine will
   show you how to quickly identify problems in your front-end code and
   make sure your users stay happy and keep visiting your web app.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:03:51

   Beyond Pushing "Play": Interactive, Data-driven Videos for a Web-based
   World - Susan E. McGregor

   Description:
   It's time for video narratives to truly be of the web. Video shouldn't
   just be a one-way stream: it should create a dynamic, interactive,
   responsive visual narratives that leverage all the resources of the
   web, whether those are simply text, or complex visualizations or
   localized data.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:08:58

   The Goodness of JavaScript - Aaron Frost and Dave Geddes

   Description:
   Across the board, the JavaScript community is thriving. This last year
   has seen unprecedented levels of adoption. Dave and Aaron will take a
   look at some of the reasons for the success of the JavaScript
   community, while also exploring some of the painful bits along the way.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:12:21

   Keynote with Yehuda Katz and Tom Dale - Yehuda Katz and Tom Dale

   Description:
   Yehuda Katz and Tom Dale, Co-founders, Tilde Inc.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:23:25

   Tutorials

   Automate All the Front-End Things! - Part 1 - Kitt Hodsden

   Description:
   Today's front end developers have more work to do than ever to create a
   functioning, responsive, fast, good-looking website. We have differing
   screen resolutions, browser support, network speeds and other
   considerations all buzzing around, jockeying for highest priority and
   attention during development. Fortunately for us, we also have more
   tools than ever before to help us begin, develop, test and refine those
   good-looking sites. Using those tools to automate the development
   process will help keep us sane, so let's do just that: automate all the
   front-end development things!

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:44:34

   Automate All the Front-End Things! - Part 2 - Kitt Hodsden

   Description:
   Today's front end developers have more work to do than ever to create a
   functioning, responsive, fast, good-looking website. We have differing
   screen resolutions, browser support, network speeds and other
   considerations all buzzing around, jockeying for highest priority and
   attention during development. Fortunately for us, we also have more
   tools than ever before to help us begin, develop, test and refine those
   good-looking sites. Using those tools to automate the development
   process will help keep us sane, so let's do just that: automate all the
   front-end development things!

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:43:12

   Web Components in Action - Part 1 - Michael Bleigh

   Description:
   3-Hours: Web Components are the building blocks of tomorrow's web
   applications, but you can start working with them today. Learn about
   how the various pieces of the spec work together to create awesome,
   reusable, and well-encapsulated components and put it into practice
   today using Google's Polymer library.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:55:24

   Web Components in Action - Part 2 - Michael Bleigh

   Description:
   3-Hours: Web Components are the building blocks of tomorrow's web
   applications, but you can start working with them today. Learn about
   how the various pieces of the spec work together to create awesome,
   reusable, and well-encapsulated components and put it into practice
   today using Google's Polymer library.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:39:55

   Web Components in Action - Part 3 - Michael Bleigh

   Description:
   3-Hours: Web Components are the building blocks of tomorrow's web
   applications, but you can start working with them today. Learn about
   how the various pieces of the spec work together to create awesome,
   reusable, and well-encapsulated components and put it into practice
   today using Google's Polymer library.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:42:32

   WebRTC: Realtime Communication for Everyone - Part 1 - Lisa
   Larson-Kelley

   Description:
   90-Minutes: WebRTC is a powerful open-source project that enables
   real-time communication (RTC) baked right into modern web browsers.
   This means you can now incorporate video, voice and data sharing using
   peer-to-peer connectivity via simple JavaScript APIs, with no plugins
   or additional installs.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:38:12

   WebRTC: Realtime Communication for Everyone - Part 2 - Lisa
   Larson-Kelley

   Description:
   90-Minutes: WebRTC is a powerful open-source project that enables
   real-time communication (RTC) baked right into modern web browsers.
   This means you can now incorporate video, voice and data sharing using
   peer-to-peer connectivity via simple JavaScript APIs, with no plugins
   or additional installs.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Play Video

   00:39:09

   Attacking Web Applications - Part 1 - Sasha Goldshtein

   Description:
   In this session, we'll review common attacks on web applications: SQL
   injection, cross-site scripting (XSS), broken authentication,
   cross-site request forgery, information disclosure, and insecure
   password storage.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:45:40

   Attacking Web Applications - Part 2 - Sasha Goldshtein

   Description:
   In this session, we'll review common attacks on web applications: SQL
   injection, cross-site scripting (XSS), broken authentication,
   cross-site request forgery, information disclosure, and insecure
   password storage.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:37:04

   AngularJS Fundamentals - Part 1 - Mark Bates

   Description:
   3-Hours: In three hours participants will go from zero knowledge of
   AngularJS to being able to write full and complex AngularJS apps.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:41:18

   AngularJS Fundamentals - Part 2 - Mark Bates

   Description:
   3-Hours: In three hours participants will go from zero knowledge of
   AngularJS to being able to write full and complex AngularJS apps.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:48:56

   AngularJS Fundamentals - Part 3 - Mark Bates

   Description:
   3-Hours: In three hours participants will go from zero knowledge of
   AngularJS to being able to write full and complex AngularJS apps.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:36:47

   AngularJS Fundamentals - Part 4 - Mark Bates

   Description:
   3-Hours: In three hours participants will go from zero knowledge of
   AngularJS to being able to write full and complex AngularJS apps.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:46:56

   Creating Interactives with D3.js - John Williams - Part 1

   Description:
   3-Hours: This workshop will introduce you to the basics of the D3
   library. D3 lets you create rich, custom interactive pieces driven by
   data, but the learning curve can be difficult to navigate. We'll cover
   the fundamental concepts of the library as well as SVG the most common
   illustration tool for D3 and enough functional programming to get by.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:42:27

   Creating Interactives With D3.js - John Williams - Part 2

   Description:
   3-Hours: This workshop will introduce you to the basics of the D3
   library. D3 lets you create rich, custom interactive pieces driven by
   data, but the learning curve can be difficult to navigate. We'll cover
   the fundamental concepts of the library as well as SVG the most common
   illustration tool for D3 and enough functional programming to get by.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:22:21

   Creating Interactives With D3.js - John Williams - Part 3

   Description:
   3-Hours: This workshop will introduce you to the basics of the D3
   library. D3 lets you create rich, custom interactive pieces driven by
   data, but the learning curve can be difficult to navigate. We'll cover
   the fundamental concepts of the library as well as SVG the most common
   illustration tool for D3 and enough functional programming to get by.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:17

   Creating Interactives With D3.js - John Williams - Part 4

   Description:
   3-Hours: This workshop will introduce you to the basics of the D3
   library. D3 lets you create rich, custom interactive pieces driven by
   data, but the learning curve can be difficult to navigate. We'll cover
   the fundamental concepts of the library as well as SVG the most common
   illustration tool for D3 and enough functional programming to get by.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:34:23

   JavaScript Smackdown! Choosing Your MVC between Angular, Ember, and
   Backbone - Part 1 - Brian Holt

   Description:
   90-Minutes: Choosing an MVC framework for you next project is a
   daunting task; there are so many options with fervent supporters that
   it seems there is no one exclusively right path. This workshop won't be
   a pitch for any one of them: it aims to give you context for each of
   the three frameworks so that you can make your own informed decision.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:37:33

   JavaScript Smackdown! Choosing Your MVC between Angular, Ember, and
   Backbone - Part 2 - Brian Holt

   Description:
   90-Minutes: Choosing an MVC framework for you next project is a
   daunting task; there are so many options with fervent supporters that
   it seems there is no one exclusively right path. This workshop won't be
   a pitch for any one of them: it aims to give you context for each of
   the three frameworks so that you can make your own informed decision.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   01:00:47

   Sessions

   JavaScript: Taking both the High and the Low Roads - Brendan Eich

   Description:
   I'll update everyone on ES6, ES7, and how JS is evolving quickly under
   a fairly balanced and competitive/cooperative browser market structure,
   and the consequent rise of the lead web developers and github.com.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:51

   Reading, Writing, Arithmetic...and JavaScript? - Pamela Fox

   Description:
   What if everyone learnt to program in middle school? How would that
   change the way that they learnt other subjects? How would it affect
   their personal life? Their career? It's kind of a crazy idea, but it
   might be crazy in a good way. In this talk, I'll lay down my ideas for
   how this could happen and what it might mean, based on my experience
   teaching programming online on Khan Academy.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:10:52

   Virtual Machines, JavaScript and Assembler - Scott Hanselman

   Description:
   How does the pervasiveness of JavaScript on the client change how we
   architect applications? We can create hundreds of virtual machines in
   the cloud, but we are using the millions of visual machines that visit
   our sites every day?

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:25:56

   Polymer: Web Components in Action - Eric Bidelman

   Description:
   Web Components make web development fun again! Learn how to use Polymer
   and its UI components to create beautify component-based applications.
   Let's bring composability, reusability, and maintainability to the web.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:38:53

   Leveling Up in Angular - Alicia Liu

   Description:
   After you've developed that first demo app using the Angular JavaScript
   framework, now what? This presentation covers patterns and strategies
   for developing more complex apps using Angular, avoiding pitfalls, and
   how to write your own directives and components the "Angular Way".

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:24:02

   Media APIs for the Web - Chris Wilson

   Description:
   We've all come to expect audio, video and realtime communication from
   apps, games and sites on all our devices. This session will help you
   build dynamic, multi-device web applications using video, WebRTC, Web
   Audio and more. We show you how to maximize performance, avoid common
   gotchas, and deliver great experiences on mobile and desktop, using
   powerful new media APIs.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:34:29

   Practical Workflows for ES6 Modules - Guy Bedford

   Description:
   See how to use ES6 modules and syntax in browsers today, with a focus
   on writing truly modular code. An overview of approaches will be
   covered, including a workflow for the ES6 Module Loader polyfill from
   development to production. Finally see an overview of the JSPM loader
   and CDN, demonstrating some of the possibilities of browser package
   management.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:36:45

   Closing the Web Platform Gap with Native - Moh Haghighat

   Description:
   We present some exciting results from Intel's ongoing joint work with
   Google and Mozilla on bringing SIMD to JavaScript, enabling development
   of high performance web apps including game engines and apps that
   require efficient image/video/speech processing. We also cover the
   portable Crosswalk HTML5 runtime and Intel XDK that lowers the
   development costs of web and hybrid apps for major app stores.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:53

   Design Strategies for JavaScript API - Ariya Hidayat

   Description:
   The quality of modular web applications can be improved by having the
   right set of APIs. This talk highlights the recent API design best
   practices, from using static polymorphism for consistent naming,
   preventing dangerous convenience (e.g. Boolean trap), and avoiding
   unreadable code due to confusing semantics. Real-world examples and
   automated tools to recognize bad API will be shown as well.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:27:49

   Interface Design Considerations for Data Visualization - Scott Murray

   Description:
   This talk will illustrate the design process behind Kindred Britain
   (kindred.stanford.edu), an interactive network visualization and
   digital humanities project, made with Nicholas Jenkins and Elijah Meeks
   of Stanford University.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:27:57

   Technical and Social Progress Toward ECMAScript 6 at Facebook - Ben
   Newman

   Description:
   At Facebook we take the future of JavaScript seriously, and we go to
   great lengths to accelerate the adoption of new language features both
   within the company and without. Join us for a close look at some of our
   techniques for transpiling, desugaring, refactoring, and otherwise
   improving a very large JavaScript codebase.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:33:07

   Measuring App Performance in the Browser - Nathan Taggart

   Description:
   During this session discover the ways you can impact the application
   performance for your end user - pin pointing time spent within layers
   of the application, and end user demographics through geography,
   browser types, and page views. In addition to the application
   visibility we will be showing you how to dive into the time being spent
   within AJAX as well as the impact of JavaScript errors.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:25:52

   Creating 8-bit Game Music in the Browser - Brian Rinaldi

   Description:
   8-bit gaming is back, big time! Recreating the look and feel of an
   8-bit game in the browser isn't complete without that classic 8-bit
   sound. In this session we'll look at how you can create 8-bit
   soundtracks in the browser using the Web Audio API and some help from a
   library called Band.js.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:27:37

   Managing JavaScript Complexity in Teams - Jarrod Overson

   Description:
   Learn what tools exist to assess and visualize JavaScript complexity
   and learn how to manage ever enlarging codebases. There are loads of
   tools out now that go a long way to managing your code (and other's) so
   you have more time to deal with what is important. Learn how to make
   the best of them.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:36

   Responsive Web Design with @viewport and Other New CSS Features -
   Andreas Bovens

   Description:
   In this talk, I will look at two of the technologies that lie at the
   basis of responsive web design: the viewport meta tag and CSS media
   queries. I will explain how viewport is being standardized as viewport,
   and how many other new features in CSS, such as the resolution media
   query, object-fit, relative length units etc., can be used to create
   even more compelling responsive designs.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:53

   Callable Entities in ECMAScript 6 - Axel Rauschmayer

   Description:
   Functions in ECMAScript 5 are mostly replaced by new callable entities
   in ECMAScript 6: arrow functions, classes and method definitions. This
   talk explains how they work and what existing problems they fix.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:21

   Debugging (AKA Screaming, Crying, and Raging) Your PhoneGap Apps -
   Raymond Camden

   Description:
   A look at debugging techniques (some helpful, some desperate) for
   PhoneGap applications.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:52

   In Pursuit of the Holy Grail: Building Isomorphic JavaScript Apps -
   Spike Brehm

   Description:
   While the client-side JavaScript app approach can provide snappy,
   interactive UIs, it presents challenges, including initial page-load
   performance, SEO, and duplication of application logic between client
   and server. Let's explore the budding community around isomorphic
   JavaScript apps and the tools and libraries you can use to run your app
   on the client and server with a single codebase.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:55

   Where's My Straw? - Kyle Simpson

   Description:
   What does a drive-thru have to teach us about optimizing tools and
   processes?

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:33:46

   Building Customer Applications Using the Salesforce1 Platform APIs -
   Wade Wegner

   Description:
   Behind every app, every device, and every connection, is a customer.
   Using the Salesforce1 Platform there's no limit to what you can build
   for your customers. In this talk Wade Wegner, Senior Director at
   salesforce.com, will demonstrate how to build your own applications
   using the Salesforce1 APIs. Heavy in code, light in slides, you'll
   leave ready to build your own applications on Salesforce1.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:33

   Speed and Magic Sharding - Jesse Noller

   Description:
   Rackspace Performance Cloud Servers

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:43

   Static Types are Overrated: The Dynamic Duo - Loose Types and Object
   Extension - Eric Elliott

   Description:
   How loose typing makes generic functions easier - how generic functions
   are better for code reuse and functional programming - how object
   extension makes inheritance easier - novel uses for dynamic objects,
   including a flexible, less error-prone alternative to switch / case

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:12

   Developing Web Graphics with WebGL - Tony Parisi

   Description:
   WebGL's hardware-accelerated 3D rendering enables the creation of
   high-performance, visually stunning web content for advertising,
   entertainment, e-commerce, and social media. This session covers the
   basics of developing web graphics using WebGL. Topics include
   rendering, animation, interactivity, behaviors, and integrating 3D into
   HTML5 pages using open source WebGL libraries.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:31:13

   So Easy A Child Could Do It - Kathryn Rotondo

   Description:
   Young children playing with mobile devices don't have a preconceived
   idea of what it means to tap, or swipe, or talk into the mic, or that
   only one little point of one hand should touch the screen at a time.
   They rely on trial and error and cues from the app. This session will
   cover intuitive gestures, interactivity cues, and element placement, as
   well as legal considerations for children's apps.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:26:23

   Using BladeRunnerJS to build front-end JavaScript apps that scale -
   Phil Leggetter

   Description:
   Developing large apps is difficult. Ensuring that code is consistent,
   well structured, tested and has an architecture that encourages
   enhancement and maintainability is essential. But, how do you achieve
   this when building HTML5 single page apps? In this talk, you'll learn
   the main concepts to apply when building a front-end app that scales
   and how BladeRunnerJS can support the development process.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:33:00

   JavaScript Loves Unicode - Mathias Bynens

   Description:
   In this presentation well take a look at the various ways JavaScript
   relies on Unicode, what the consequences are for JavaScript developers
   wishing to support full Unicode in their apps, and how ECMAScript 6
   will make our lives a bit easier in this regard.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:31

   The Perception of Speed - Steve Souders

   Description:
   Which would you rather have: a website that's fast or a website that's
   perceived as fast? The answer is Both! The list of performance best
   practices is long and well known, but there's been less focus on the
   users perception of speed. In this presentation, Steve Souders provides
   examples of how the perception of speed is completely independent of
   actual speed, and techniques for leveraging this perception gap to
   create websites that feel fast.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:52

   Inside JavaScript Execution - Chase Douglas

   Description:
   Have you ever wondered how JavaScript runtime engines actually execute
   your code? JavaScript as a language has many interesting facets and
   features, and this has led to innovative techniques for executing code
   efficiently. Learn all about how modern runtime engines work, and
   hopefully gain some insight on how you can better leverage the language
   for your projects.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:34

   Code Risk Management at Twitter - Andres Ornelas

   Description:
   In this talk, you will learn about a system we have built that
   quantifies and tracks the risk of files in any given codebase to
   empower all the levels of the organization to make informed decisions
   regarding code changes and accurately evaluate the health of their
   projects.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:54

   Continuous Integration in JavaScript - Rob Richardson

   Description:
   JavaScript has come of age, and with it, the maturity of the software
   development lifecycle. No matter the scale or publish platform for your
   app, you'll need a consistent build. We'll discuss standard CI best
   practices and techniques, and walk through two approaches to Continuous
   Integration in JavaScript: Travis CI and gulp.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:34:18

   Everything is a Polyfill: Automate Deleting Code for Front End
   Performance - Rachel Myers and Emily Nakashima

   Description:
   Successful applications often get slow because they include "all the
   code"- even if it isn't needed for a particular client or in the given
   circumstances. Embracing module loading tools (like Require.js) creates
   smaller, faster, cleaner applications. We'll talk about how to extend
   this paradigm to all the components of our app for better performance
   and maintainability.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:32:22

   jQuery-free JavaScript - Elijah Manor

   Description:
   Do you still need jQuery? Has it become a crutch? Can you get away with
   dropping jQuery as a dependency and use native browser APIs instead?
   For the majority of this session we will be looking at common jQuery
   snippets and show how to convert them either using native browser APIs
   or utilizing popular micro-libraries.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:50

   Top Overlooked Security Threats To Node.js Web Applications - Chetan
   Karande

   Description:
   If not programmed and configured in a security conscious manner,
   Node.js web applications expose attack vectors that can be exploited
   for severe technical and business impact. In this presentation,
   attendees will learn about possible security pitfalls and walk out with
   a cohesive action plan to effectively address these concerns and build
   resilient Node.js web applications.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:27:18

   6 Bottles of RUM: Surprising Stories of Mobile Behavior in the Real
   World - Peter McLachlan

   Description:
   Real world measurement at scale is the only reliable way for web
   engineers to understand the performance behaviour of routine
   techniques, considered to be best practices in desktop web development,
   on smartphones running on cellular data networks. In this talk we will
   review common performance memes and evaluate them in the context of
   real world mobile performance.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:54

   The Secrets of React's Virtual DOM - Pete Hunt

   Description:
   At Facebook and Instagram, we're trying to push the limits of what's
   possible on the web with React. My talk will start with a brief
   introduction to React and then dive into three controversial topics:
   Throwing out the notion of templates and building views with
   JavaScript, re-rendering your entire application when your data
   changes, and a lightweight implementation of the DOM and events.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:48

   Invisible Visualization: Accessible Information Graphics on the Web -
   Doug Schepers

   Description:
   Data visualizations is increasingly popular. This talk will cover
   well-known challenges and pitfalls for accessible data visualization,
   and describe techniques to overcome them, and even to enhance
   accessibility by using Web solutions like SVG, HTML, ARIA, and the Web
   Audio API and Web Speech API.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:31:59

   Reusable Libraries for Hypermedia Clients - Mike Amundsen

   Description:
   Based material from the book "RESTful Web APIs", this talk walks you
   through the creation of a great UI for a Collection JSON media type API
   and then shows how minor changes on the server are automatically
   handled by the client without rewrites or redeploys. The same library
   can even used for different APIs with the same smooth results. Reusable
   libraries for hypermedia clients is a reality.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:31:44

   Measuring App Performance in the Browser - Nathan Taggart

   Description:
   During this session discover the ways you can impact the application
   performance for your end user - pin pointing time spent within layers
   of the application, and end user demographics through geography,
   browser types, and page views. In addition to the application
   visibility we will be showing you how to dive into the time being spent
   within AJAX as well as the impact of JavaScript errors.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:31:22

   The Mindblowing Power of Sass 3.3 - Chris Eppstein

   Description:
   Overview of all the new features of Sass 3.3 and how they can be used
   to supercharge your stylesheets by one of the creators of Sass.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:33:36

   Introduction to ExpressJS - Guy Ellis

   Description:
   Learn how to use the ExpressJS framework to select the right structure
   and paradigm for your NodeJS application. You will leave this
   presentation with the knowledge to immediately build a well structured
   ExpressJS web application.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:33:41

   Performance Tips when Developing with jQuery Mobile - Ralph Whitbeck

   Description:
   jQuery Mobile is one of the easiest ways to create a mobile site today.
   Mobile development brings performance to the forefront. Well explore a
   few ways to get the most out of jQuery Mobile and your site. These tips
   were used in building a conference mobile site, which was built with
   performance in mind. Well learn how to make jQuery Mobile fast on any
   device.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:35:50

   Building Ambitious Web Applications with Ember.js - Michael Jackson

   Description:
   Ember.js is an exceptionally powerful and exciting technology for
   building rich, native-feeling experiences on the web. It combines some
   of the best ideas from classic UI frameworks like Cocoa and UIKit with
   cutting-edge HTML 5 standards like web components.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:35:13

   Meteor: A Full-stack JavaScript Framework for Modern App Development -
   Matt DeBergalis

   Description:
   Meteor is a distribution of open-source packages that makes it
   radically faster to build modern apps. All the parts are there: a
   reactive template engine, powerful data synchronization primitives, a
   standard wire protocol, and a database API that works the same on both
   the client and the server. This talk will demonstrate making an app
   from scratch, showing how it all fits together.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:31:58

   Frames Per Second - Paul Bakaus

   Description:
   If you want to get your brain stuffed with every bit of info on runtime
   perf, then this is your talk. In-depth information on how many frames
   the human eye can process, differences between refresh rates and frame
   rates, motion blur, jitter, responsiveness, input lag and hands-on
   advice on profiling and debugging, all obviously from a games
   perspective, but applicable to all web development.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:59

   Supercharge Your Mobile Emails - Lee Mallabone

   Description:
   Email consumption on mobile devices is growing at an unprecedented
   rate, and the HTML capabilities of those devices is a step-change from
   their desktop counterparts. This talk will demo some lessons learned
   building delightful mobile experiences at LinkedIn, and present
   specific HTML and CSS3 authoring techniques for creating remarkable
   best-in-class mobile emails.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:32:17

   Manipulating Space-Time Fabric by Rewriting Javascript AST - Nate
   Murray

   Description:
   Thinking procedurally is one of the hardest concepts to grasp for the
   beginning programmer. By using a new-breed of tools we can visualize
   how programs run and reason about our programs in new ways. In this
   talk, you will learn how to use tools like esprima to programmatically
   rewrite javascript and visualize the space-time fabric of javascript
   execution.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:53

   Asynchronous Promises - Kris Kowal

   Description:
   A promise is a proxy for an eventual result, like an asynchronous
   version of return or throw, but they can also pipeline messages
   asynchronously to and from remote objects. A Promise type will likely
   be in ECMAScript 6, and many modern libraries use them already. In this
   talk, I will bring you up to speed with what they are and what you can
   do with them today and what they promise for tomorrow.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:34:28

   AngularJS - Top 10 Tips - John Lindquist

   Description:
   Come learn the top AngularJS tips to improve your workflow and enhance
   your AngularJS experience. John will talk about "Best Practices",
   debatable approaches, and code smells that he's found from teaching and
   training on AngularJS since it hit 1.0.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:09

   UX Research Methods for API Design - Jeremiah Lee

   Description:
   The field of user experience has proven in the last decade how research
   methodologies can significantly improve the usability, intuitability,
   and enjoyment of products. Yet API design is dominated by discussion of
   how one technology (HTTP) is most purely applied (REST/Hypermedia).
   User research and testing can elevate the level of design for APIs. I
   will present strategies for building great APIs.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:51

   JavaScript as a First-Class Citizen on iOS 7 - Kevin Whinnery

   Description:
   In iOS 7, JavaScript has become a first-class citizen for iOS
   development. The new JavaScriptCore system framework provides a bridge
   between JS and Objective-C code, opening up the entire Cocoa Touch
   platform to JavaScript developers. This talk will explore this new API,
   and demonstrate how developers can take advantage of it with a demo
   that uses JavaScript to drive a simple 2D SpriteKit game.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:52

   JavaScript and Embedded Devices - Jon McKay

   Description:
   The co-founders of Technical Machine talk about what the future has in
   store for the developer experience of embedded devices and the software
   architecture behind their JavaScript-powered microcontroller, Tessel.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:27:44

   Unpacking Technical Decisions - Sarah Mei

   Description:
   Every day, we make hundreds of small technical decisions: what's the
   best way to implement this? Where should this function live? Less
   often, we make a larger decision: would a different framework make us
   more productive? Should we rewrite the whole thing in C? We'd all like
   to make better decisions, at all of these scales. Let's unpack the
   decision-making process and see what we can extract.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:27:19

   AngularJS And The Computer Science Of JavaScript - Burke Holland

   Description:
   AngularJS is a fascinating framework for web developers. It's really a
   completely different way to build applications. There is no DOM
   selection and mutation, there are only Directives.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:50

   Whirlwind Tour of Scalable Vector Graphics - Marc Grabanski

   Description:
   Take a whirlwind tour of a the graphics format that looks as good on
   small devices as it does on high resolution (retina) and large
   displays. We'll take a look at much of the SVG API as well as how to
   interact with vector graphics through the use of transforms,
   transitions, matrices and JavaScript libraries such as RaphaelJS and
   D3.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:29:13

   Leaflet, Node.JS, and MongoDB for a easy and fun web mapping experience
   - Steven Pousty

   Description:
   You have seen the stuff that FourSquare has done with spatial and you
   want some of that hotness for your app. Well this session will give you
   all the tools you need. We will combine MongoDB, Node.JS, and Leaflet
   to create full mapping application. When you go home you will be able
   to amaze your friends and supervisors with some spatial magic goodness
   you can control.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:40:07

   JavaScript, Linux and Open Hardware: A Recipe for Rapid Internet
   Devices - Jason Kridner

   Description:
   An affordable open hardware platform provides entrepreneurial software
   developers an easy path for wrapping their services with customized and
   dedicated devices to sell as consumer or industrial appliances.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:39:15

   Designing for Front-End Page Speed - Lara Swanson

   Description:
   Good page load time begins with good design. As web performance grows
   in importance in the industry, many page speed tutorials focus on the
   back end. This presentation focuses on performance from a design and
   front end perspective.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:26:58

   Functional Programming Patterns for the Non-Mathematician - Brian
   Lonsdorf

   Description:
   Abstractions in FP can be daunting if you're not familiar with set
   theory or lambda calculus or category theory and all that. I'm
   certainly not. I'll translate some of the most important functional
   patterns and interfaces in JS directed towards us object orienters who
   may not have majored in math. You'll leave with a killer toolset and
   you'll weep at the beauty...if you have a heart.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:30:29

   Tools and Techniques for Securing JavaScript Applications - Emily Stark

   Description:
   Modern applications written in JavaScript are vulnerable to many of the
   same attacks, like XSS and CSRF, that threaten traditional web apps.
   But defending against them requires new tools and techniques. This talk
   will illustrate best practices for securing these apps, and introduce
   some of the security conventions and tools we've built into Meteor, a
   full-stack JavaScript framework.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:28:27

   Writing Real Time Web Apps - Wesley Hales

   Description:
   This is not another session using Node and Socketio to demonstrate
   sending an receiving real time data. This presentation will cover what
   it takes to stand up production ready WebSocket clients and how to
   manage and gracefully degrade for non-supporting browsers.

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:31:08

   GSS - Layouts Not Possible Even with Tomorrow's CSS Using Polyfills
   from the Future - Dan Tocchini

   Description:
   Web developers are expected to build increasingly sophisticated UIs
   faster, cheaper, with tools that have not evolved with the times. Why
   is the trivial task of centering an element with CSS so obtusely
   complex?

   Closed Captioning: Unavailable

   Mobile-Friendly Format: Available on m.safaribooksonline.com

   Example Files: Available on Extras tab

   Preview

   00:40:58

Extras

   The publisher has provided additional content related to this title.
   Description
   Content

   Visit the catalog page for Fluent Conference 2014: JavaScript &amp;
   Beyond Complete Video Compilation
     * Catalog Page

   Visit the errata page for Fluent Conference 2014: JavaScript &amp;
   Beyond Complete Video Compilation
     * Errata
