   Skip to main content


   Advertisement
   CED
   CED
     * Home
     * News
          + Show Daily
     * Articles
     * Blogs
          + And Another Thing
          + It's Kuhl
          + Write Stuff
     * E-Reports
          + Multi-screen September 2014
          + Fiber Optics March 2014
     * Multimedia
          + Videos
          + Demystifying Tech
          + Webcasts
     * Current Issue
     * Resources
          + Wallcharts
          + White Papers
          + Company Directory
          + Add Your Company
          + Digital Edition
          + Events
     * Free Subscriptions

     * Company Profile Search
     * Log in
     * Register

   Advertisement
   News
   Advertisement

FCC names network neutrality expert as CTO

   Tue, 08/26/2014 - 1:11pm
   Brian Santo
   Today's top stories for broadband professionals - Sign up now!

   Scott Jordan, a professor at University of California at Irvine with a
   strong history working on network neutrality issues, was named the new
   chief technology officer (CTO) of the FCC.

   For those who try to read tea leaves, Jordan’s appointment might be a
   signal that FCC chairman Tom Wheeler is serious about exploring the
   possibility of reclassifying broadband as a telecommunications service,
   even as the Republican contingent among his fellow Commissioners have
   been vehemently dismissing the idea.

   Jordan succeeds Henning Schulzrinne, who will return to Columbia
   University and continue to serve the Commission in a part-time capacity
   as a technology advisor.

   Jordan is a professor of computer science at UC Irvine. His research
   interests include communications policy, pricing and differentiated
   services in the Internet, and resource allocation in wireless
   multimedia networks, the FCC said.

   Jordan has also developed specific expertise in network neutrality
   issues, developing what one bio calls “moderate” network neutrality
   policies. That includes proposals for policy founded on network
   architectures that encourage development of network management for
   multimedia applications while prohibiting anti-competitive behavior or,
   as one of his papers puts it, the extraction of oligopoly rents. In
   other words, he’s been attempting to help formulate policy that would
   have strong consumer protections but which would not interfere with
   network operations or management.

   He has not advocated for reclassifying broadband as a
   telecommunications service, but he has considered the question and has
   developed recommendations for how the policy might most fairly be
   applied by making careful distinction between the network layer and
   below (layers 1-3 on the OSI stack) and the transport layer and above
   (OSI layers 4-7). (Comments here.)

   He has served as an IEEE Congressional Fellow, working in the United
   States Senate on Internet and telecommunications policy issues, and on
   the FCC Open Internet Technical Advisory Committee.

   In the technology arena, Jordan works to further integrate voice, data,
   and video on the Internet and on wireless networks, the FCC said.

   “Scott’s engineering and technical expertise, particularly with respect
   to the Internet, will provide great assistance to the Commission as we
   consider decisions that will affect America’s communications platforms.
   We are delighted that he is joining us,” said FCC Chairman Tom Wheeler.

   “Scott has big shoes to fill, as the contributions of outgoing Chief
   Technology Officer Henning Schulzrinne, are innumerable. Henning played
   an invaluable role within the Commission in making sure our tech
   transition efforts have a sound grounding in technology. Most recently
   his research and advice were key in the Commission’s decision to hold
   carriers accountable by adopting rules requiring text-to-911 services,”
   Wheeler said.

   Jordan will be based in the FCC’s Office of Strategic Planning and
   Policy Analysis.

Topics

     * Broadband
     * Policy
     * Video

   Advertisement

Share This Story

   Printer-friendly version Send by email PDF version

Comments

   View the discussion thread.

Search form

   Search _______________
   Search
   Advertisement
     * White Papers

   Moving Cable to the Cloud
   September 22, 2014 10:16 am | by Susan Crouse, Director of Product
   Management
     * Recent Blogs

   [Santo%20Brian-blog_19.jpg?itok=bEMJ5p_O]

FCC chair makes firmest case yet that broadband competition is lacking

   September 4, 2014 2:11 pm | by Brian Santo
   [Santo%20Brian-blog_18.jpg?itok=H57p4-ot]

Senate video promotes broadcaster a la carte

   August 26, 2014 12:34 pm | by Brian Santo
     * Videos
     * Webinars

Conviva: Live From the Show: Conviva

   May 21, 2014 8:01 pm | by CED

Envivio: Live From the Show

   May 19, 2014 8:42 pm | by CED

Napco Security: Live From the Show

   May 19, 2014 8:29 pm | by CED

NCTA: Live From the Show

   May 19, 2014 8:12 pm | by CED

Live From the Show: SCTE

   November 1, 2013 3:50 pm | by CED

Managing the Transition to CCAP and DOCSIS 3.1

   September 8, 2014 5:17 pm | by CED

Successful Strategies for Wi-Fi Deployments

   July 9, 2014 7:27 pm | by CED

DOCSIS 3.1 Checklist

   June 17, 2014 5:29 pm | by CED

Operation DOCSIS 3.1

   February 14, 2014 6:18 pm | by CED
   Advertisement
     * Trending

FREE
Broadband Industry
Subscriptions

     * E-newsletters
     * Magazine

   SUBSCRIBE

   [CEDcover.gif]
   Advertisement
   Advertisement
   Advertisement
   Advertisement
   Advertisement
   Advertisement
   Advertisement

CED

     * About Us
     * Advertising Info
     * Contact Us
     * Directory FAQ
     * Subscriptions
     * Privacy Policy
     * Terms & Conditions

Resources

     * Articles
     * Blogs
     * Wallcharts
     * Events Calendar
     * News
     * Sitemap
     * Video
     * Webcasts
     * White Papers

Topics

     * Broadband
     * Business
     * Multi-screen
     * Networking
     * Policy
     * Video
     * Voice
     * Wireless

Connect With Us

     * Facebook
     * Twitter
     * YouTube
     * RSS

Newsletters

   IFRAME:
   http://subscribe.advantagemedia.com/ced-footer_ods/subscription3.aspx

Our Partner Sites

     * Wireless Week
     * ECN
     * Wireless Design & Developmen

   Advantage Business Media © Copyright 2014 Advantage Business Media

Top Stories and Headlines
EVERY DAY!

   [btnClose.png]
   [logoBroadbandDirect.png]

FREE Email Newsletter

   IFRAME:
   http://subscribe.advantagemedia.com/ced_ods/ModalSubscriptionDrp.aspx

   View Sample »
   Quantcast
   Advertisement

   X
   Username or e-mail address *
   ____________________________________________________________
   You may login with either your assigned username or your e-mail
   address.
   Password * ____________________________________________________________
   The password field is case sensitive.
   [ ] Remember me
   Log in
     * Create new account
     * Request new password

   Loading
