   #publisher

     * Homesearch
     * Collections
     * Sign in or create an account

   (BUTTON) Medium site navigation
   Steven Levy Steven Levy on Jun 25
   3 min
   (BUTTON)
     * (BUTTON) Info
     * (BUTTON) History

   (BUTTON) (BUTTON) Publish
   Change the title or subtitle to customize how your story is presented
   across Medium.

   Welcome to the new, more flexible Medium editor
   Learn about the new editor features

   Don’t write alone

   Copy and send this draft link to anyone. They’ll be able to leave you
   notes before you publish.
   ____________________
   (BUTTON) Set as featured in collection

I’m moving to Medium

Creating a new hub for tech stories that matter
     __________________________________________________________________

   Anyone who’s been in journalism for even a short time has become
   intimately familiar with the “change of venue” memo from a colleague.
   I’ve been in the field for more than a short time, and I admit that,
   after all these years, every time I see one of them, I fantasize what
   mine might be like.

   Today, I’m thrilled to share the news with you that one of my most
   presumptuous fantasies is coming true. I’m joining Medium to establish
   a tech hub that strives to bring well-reported, lively, and meaningful
   reporting and writing to what is already shaping up as a terrific
   platform for the written word. I’ll be the editor-in-chief and senior
   writer for this (as yet unnamed) hub.

   One of the things that I love about Medium is its commitment to
   experimentation, one that I fully embrace. So a precise description of
   what this new venture is going to eventually become is gleefully
   elusive. But I can tell you this—it will feature not only my own best
   writing but the work of contributors who share my belief in deeply
   reported, colorfully rendered stories in and around the tech explosion.
   We will also draw on some of the amazing contributions that are already
   flowing into Medium—not only professional writers but also smart people
   chiming in spontaneously—and bring in outside voices of authority who
   will express their concerns, share their thoughts, and generally
   provoke our readers. (In other words, barbed opinions that don’t cross
   the line to trolldom.)

   For more than 30 years, I’ve been telling the true and truly
   jaw-dropping stories of the people who are changing the world with
   tech, and I’ve been extremely lucky in finding homes for my work. I
   first began writing about the subject for Rolling Stone, a magazine I
   idolized ever since my high school years. My twelve years at Newsweek
   provided an amazing front row seat to the dawn of the Internet era. And
   Wired, where I’ve been full time for the last six years—after
   freelancing for the magazine since its birth—is the gold standard of
   reporting on the parts of the world where the future is already
   distributed. Now, after hanging out at great startups since forever,
   I’m finally joining one, hoping to create a chunk of that future
   myself.

   I can’t wait to start at Medium, where I’ll be able to help invent new
   ways to tell those stories, collaborating with people like Ev Williams,
   Evan Hansen (with whom I worked at Wired), and Kate Lee. However, I
   will wait for at least a little bit. I have to finish a couple of great
   stories I’ve put into motion at Wired, and then take a breather before
   I jump into my new job.

   Watch for the tech hub to appear this fall. If you follow me on Medium,
   of course, you’ll be the first to know when we go live. In the
   meantime, if you think you might have something to offer this new
   enterprise, please get in touch. Even if you don’t apply for work, I
   welcome you to use the wonderful platform here at Medium to express
   yourself. And maybe I’ll find you.
   Steven Levy

Steven Levy

   Photo by Michael Bulbenko
   (BUTTON) Follow author (BUTTON) Share

   Email me when Steven Levy publishes or recommends stories
   (BUTTON) Follow
