   #New Titles Feed Upcoming Titles Feed O'Reilly Ebook Deal of the Day
   Feed

   O'Reilly Media, Inc. - About

   Your Account
   Shopping Cart
   Shopping Cart

   Search______________
   SEARCH

     * Home
     * Shop Books & Videos
     * Blogs
          + Programming
          + Radar
          + Strata
          + Animals
     * Safari Books Online
     * Conferences
     * IT Courses & Certificates
     *

     * Contacts
     * Tim O'Reilly
     * Labs
     * Press Room
     * Jobs
     * Academic Solutions
     * Writing for O'Reilly
     * RSS Feeds
     * Terms of Service

   Print Subscribe to Newsletters

Buy Where You Shop

   by Tim O'Reilly
   May 2003

   Like all technology revolutions, the Internet is profoundly disruptive.
   For all its promise, it can destroy old ways of life before we realize
   the value of what we're losing. Part of the process of integrating new
   technology is developing social norms for its proper use. We have much
   to learn about how to use the Internet properly--how to avoid abuses
   such as spam, invasions of privacy, attempts by large corporations to
   control how we use technology, and the like. But there's also a more
   humble area of disruption that I'd like to bring to your attention. Let
   me start with a story.

   A few months ago, I was talking with one of my most loyal retail
   customers, a specialty computer bookstore in Massachusetts. "We
   survived the chains, and we survived Amazon," he said, "but I don't
   know if we're going to survive the online discounters. People come in
   here all the time, browse through the books on display, and then tell
   me as they leave that they can get a better price online."

   Now, you might say, as the Hawaiian proverb notes, no one promised us
   tomorrow. Businesses, like individuals and species, must adapt or die.
   And if the Internet is bad for small, local retailers, it's good for
   the online resellers and it's good for customers, right?

   But think a little more deeply, and you realize that my friend wasn't
   complaining that people were buying books elsewhere. He was complaining
   that people were taking a service from him--browsing the books in his
   store--and then buying elsewhere. There's a world of difference between
   those two statements. Online shopping is terrific: you can get detailed
   product information, recommendations from other customers, make a
   choice, and have the product delivered right to your door. But if you
   aren't satisfied with the online shopping experience, you want to look
   at the physical product, for example browsing through a book in the
   store, you owe it to the retailer--and to yourself--to buy it there,
   rather than going home and saving a few dollars by ordering it online.

   Think about it for a minute: the retailer pays rent, orders and stocks
   the product, pays salespeople. You take advantage of all those
   services, and then give your money to someone else who can give you a
   better price because they don't incur the cost of those services you
   just used. Not only is this unfair; it's short-sighted, because it will
   only be so long before that retailer closes his or her doors, and you
   can no longer make use of those services you enjoy.

   If you like shopping in bookstores, remember this: many independent
   booksellers are on the ropes. (One store owner we know resorts to
   ordering books on personal credit cards when she is put on credit hold
   by publishers because she can't pay her bills.) Even in the chains,
   computer book sections are in danger of shrinking in favor of other
   sections where sales are more robust. If you value the bookstore
   experience, my advice is this: buy where you shop. I buy lots of books
   online. I read about them on a blog or a mailing list, and buy with one
   click. But when I shop for books in bookstores, I buy them there, and
   so should you. Don't just look for the best price. Look for the best
   value. And if that value, for you, includes the ability to page through
   a book, support your local bookseller.

   This story is the tip of an iceberg, of course. As with the unintended
   consequences of previous revolutions (pollution from automobiles and
   industrialization, for instance), it takes a strenuous forethought to
   make sure we don't inadvertently damage parts of our world that we take
   for granted. It's easy to get fired up about large technical, social,
   and political issues, but the future we create is even more the result
   of small decisions we make every day.
   Comments on this article
   Full Threads Oldest First

   Showing messages 1 through 33 of 33.
     * A tech booksellers opinion on having stock, new releaases, pricing
       and exclusivity
       2005-07-26 12:44:03  kateatthattechnicalbookstore.com [View]
       Does anyone have any idea how much money it costs to STOCK books.
       Every book in stock is money spent by the bookseller waiting for
       the sale....
       Also, Amazon would get new releases before us--how can we compete
       with that? (by most publishers)
       Also, O'Reilly signed an exclusivity deal for the Magazine "Make"
       with AMAZON for the first month on a every 2 month periodical.
       So....we stand in front of our O'Reilly wall as a Team O'Reilly
       Bookseller and say "Sorry O'Reilly won't sell us Make for another
       month."
       WE ORDERED OURS FROM AMAZON!
       What happened to buy where you shop?
       Also, the publisher assigns a price and sets the discount so our
       profit is completetly controlled by the publisher.
       Our store, thattechnicalbookstore.com, ran in to that problem at
       the old (and out of business) San Diego Technical Books
       (booksmatter.com). Too much inventory to keep the customer happy
       and not enough of it moving out the door.
       We may have to adjust is our *need it now* attitude. We can get
       most computer books in 2 days so if it isn't in stock why not wait
       2 days...
       What is fair about all of this and how much responsibility do the
       publishers have in helping us compete?
       My answer is A LOT.
       There is very little profit in bookselling unless you have the
       capital to maintain inventory and warehouses like the chains do.
       As the daughter of a technical bookstore owner it is more than just
       the browsing or the pricing. It is our family's survival and there
       is nothing more in the world that we want than a store full of
       inventory and customers but with the economy how it is and the
       publisher's passive complicity....

     * Tim O'Reilly photo A tech booksellers opinion on having stock, new
       releaases, pricing and exclusivity
       2005-07-26 13:48:34  Tim O'Reilly | O'Reilly Author O'Reilly
       Blogger [View]
       Kate,
       I completely agree with your comment that it costs a lot to keep
       books in stock -- that was the whole point of my "buy where you
       shop" piece. Being able to walk around a store and look at books
       before buying them is a service that costs a retailer a lot to
       deliver, and the customer ought to be willing to pay for it.
       I think you're muddying the water, though, by bringing in the
       Amazon exclusive subscription window for Make. That may stick in
       the craw of brick and mortar booksellers, but we actually think it
       doesn't hurt you as much overall as you might think. Here's why:
       1. We are trying to position Make as a long-term keeper, not just
       as a magazine that disappears from the newsstand. So far, the
       results demonstrate that we were right. Issue 1 is still selling
       strongly -- as subscription starts move to issue 2, and now issue
       3, people go back to buy the previous issues as a book. The fact
       that Make back issues have been book bestsellers demonstrates the
       validity of that strategy.
       2. Amazon committed a *lot* of marketing support in return for that
       exclusive. That has helped to establish the magazine as a success
       out of the gate, which ultimately helps everyone. What's more,
       Amazon was willing to commit to selling Make as both a magazine and
       a book, which was cental to our long term strategy. That
       willingness allowed us to bring other major players to the same
       position, which has enabled the long term book opportunity for
       everyone.
       3. The Amazon exclusive starts ticking as soon as the issue is
       released, which is the day Make comes back from the printer. Half
       of the thirty day exclusive is likely over before you'd likely have
       the issue in your store.
       This decision with Make was in the best interest of growing the
       success of the product. The fact that Make has grown so fast out of
       the gate is a sign that we made the right decision. Overall, we
       think the plans we've made to help Make succeed are good for
       booksellers.

     * A tech booksellers opinion on having stock, new releaases, pricing
       and exclusivity
       2005-07-27 13:51:04  kateatthattechnicalbookstore.com [View]
       Thank you Tim for responding. O'Reilly Media, out of all of the
       publishers, have been the most kind to us in our struggle to stay
       in business. When we first called about the exclusivity on Make we
       weren't turned away OR given a pat answer but were compensated and
       treated like an "Amazon" rather than a 1,600 sq.ft. indy bookstore
       on the rocks! :)
       You can imagine though it was just embarrasing for us.
       I also understand that a store like ours may not have the broad
       reach Amazon has nor the abilities for subscription services.
       My main point was to educate the customers that as an independent
       there are many reasons why things are the way they are and that
       often is the case that we just don't have control. We want stock,
       but money is tight. We want the new releases just as quick but a 3
       book order doesn't stand a chance against a 10,000+ book order in
       expediance. We want to discount but can't compete with a online
       retailer who most likely makes NO money.
       We are proud to sell your books and very happy with O'Reilly. You
       folks send us new releases hot off the press and provide cute :)
       animals to decorate our store!
       Most of my comments are in regards to other publishers that
       bloggers might buy.
       Just you responding so quickly shows your support for us and
       reinforces our importance in the book world. I am just nervous for
       my family and may have flown off the handle. My Mom and Dad have
       been selling technical books since the 70's and you can imagine as
       they approach the retirement age with our situation being so
       unstable, that every little thing is magnified by our fear of
       having to close shop and apply for regular day jobs.
       We appreciate everything you do for us Tim and your staff responded
       to us as you would have (and did here) regarding Make.
       Best of luck and keep the good books coming!

     * Tim O'Reilly photo A tech booksellers opinion on having stock, new
       releaases, pricing and exclusivity
       2005-07-27 21:31:52  Tim O'Reilly | O'Reilly Author O'Reilly
       Blogger [View]
       Kate, I really understand where you're coming from. It's great to
       see you getting involved in your parents' business. It's one of the
       best technical bookstores there is, and I hope that we're still
       working together to get books to the people on the cutting edge
       till I'm having this conversation with YOUR kids.

     * Thanks Tim
       2004-01-12 09:12:38  anonymous2 [View]
       As an on-line store that competes with the "big Guys" (until their
       stock prices shrivel up and they have to close their doors) I
       appreciate your comments and only hope that people will listen. We
       like your books and your people even better.
       You like us compete in a mad world!
       Thanks!

     * Sales must be earned
       2004-01-09 16:52:08  scottellsworth [View]
       Howdy, Tim.
       I have bought most of my tech books online, partially because of
       discounts, but more often for the reviews. Bookstores, because they
       own the stock, rarely have any indication of what the purchasers
       thought of the books. To get that kind of feedback, I have to go
       online, and once there, well, it is often easier to just buy from
       where I am.
       A deeper issue, though, is the age of stock. Bookstores near me are
       very bad about keeping their stock up to date, or getting in the
       latest and greatest. Amazon and B&N, on the other hand, note
       upcoming editions. Thus, if I spot the fourth edition of a title on
       the shelf, I have to drop by somebody's website, just to see if
       there is a more recent version out there that applies to my task.
       So, how can a brick and mortar store fight back? Primarily by
       providing a service that earns the sales. The Tattered Cover has
       topic managers that actually know what stock is current, and that
       keep tabs on what is up and coming. Barnes and Noble should
       consider linking their online reviews to the brick and mortar
       store, then hyping it. Having sales staff that I want to talk to
       might help - I pay $4 a cup for Starbucks lattes because I like the
       people there. A bookstore can earn business the same way.
       This is not terribly cheap, but it is needed for a brick and mortar
       store to justify its usually higher prices.
       Scott

     * I research online and purchase from brick and mortar
       2003-12-14 11:28:29  anonymous2 [View]
       I find I do my research online, and then I go to a Brick and Mortar
       store to see what I am planning on buying, and complete the sale. I
       find that avoiding shipping costs and getting the book I want NOW
       makes online shopping less attractive.

     * I research online and purchase from brick and mortar
       2003-12-31 01:24:21  jwenting [View]
       I often do that too IF there is a local (within reasonable
       distance) store where they will have it in stock or can get it
       quickly (more quickly that is than I could get it shipped from for
       example Amazon).
       Problem is the nearest English language and computer specialised
       bookstores are over an hour away from where I live by train and bus
       (or similar by car) and the trip over and back would cost me more
       than Amazon charges in shipping fees...

     * not just books...
       2003-11-25 06:56:59  anonymous2 [View]
       It's just about everything that can be purchased online.
       I own several aquariums, it's getting almost impossible to get good
       supplies for them as it's no longer profitable to stock them (just
       get them online right? But what if you need support on a $200 pump
       right now instead of having to wait 3 weeks for shipping while your
       fish die?).
       As an avid amateur photographer I see camera stores going slowly
       under.
       Just about anything can be purchased more cheaply online and people
       are indeed doing the same with photographic equipment as you
       describe about bookstores.
       Except here the damage is worse and more immediate. If I want to
       see and compare equipment in a store I'm tying up their staff
       directly because they're demonstrating the stuff to me. In that
       interval a real customer might leave because there's noone to help
       them...
       But it is sometimes hard I agree. With prices online being often
       30-40% lower than in stores (and in severe cases over 50% lower)
       stores can't compete anymore.
       I've spoken about this with several storeowners. They say openly
       that the prices they are charged by importers and manufacturers are
       often higher than the prices online stores charge to end users.
       Add the store's markup (salestax here is included on items
       purchased online as well) and the situation becomes impossible for
       the independent store owners.
       For example, at one point I was offered online an expensive lens
       for 1800 (including shipping).
       The only local supplier after a big discount and tradein of several
       hundred Euro worth of old equipment was able to go down to no less
       than 2500.
       I purchased neither item, instead opting for an alternative that
       the store could offer at a decent price...
       With books (and especially computer books) the differences are
       often similar (especially with US imports where the prices in Euros
       often in no way reflect the dollar price).

     * Buying Online
       2003-11-11 11:36:45  anonymous2 [View]
       What an important message, whether about books or any other product
       where we like to take advantage of the opportunity to truly 'shop'
       before we buy. Thanks, Tim!
       Carla Evans
       Ft. Worth, TX

     * Value Beyond Price
       2003-11-04 14:47:36  dgodgo [View]
       Often times I do not know exactly which book I'm looking for; a
       resource such as SoftPro is truly wonderful. I can walk in the
       Boulder store, say "I need a good book on X", where X can be
       anything from Oracle references to obscure T-carrier protocols, and
       the people there know what I'm asking... look at a selection of
       books, then walk out of the store with the best book for my needs
       in my hands - this is a great service and a real time saver.
       With support and service like that, what's a few bucks one way or
       another? We should do all that we can to reduce the McPerson,
       'walmartization' of our world - and ensure that such knowledgeable
       stores, people, and services are around in the future.

     * I agree, in theory, but...
       2003-10-07 09:55:22  saj951 [View]
       I've been a software engineer for over 24 years. Those of you, like
       me, know that continued skill upgrade is key to survivial. We buy
       books - lots of them. And most of them are obsolete within 12 - 18
       months. Technical books are expensive - VERY expensive, and far
       more so than they've ever needed to be. One of the my biggest
       gripes has always been that I shouldn't be paying $75.00 for a
       paperback tech book that's 200 pages long. Sorry, but tech books
       have been a gold mine to publishers every since we emerged from the
       mainframe - and engineers have spent a fortune on them. I, for one,
       love Softpro - I can't even walk past the door for less than
       $100.00. And I do enjoy browsing. But, generally, I know what I
       need to get without going into a store and, the bottom line is, I'm
       going to buy it at the cheapest price I can get it at because it's
       still outrageously over-priced. If I go into Softpro and pick up a
       book I'm not familiar with, flip through it, and decide it's a good
       book to pick up, I buy it there - I found it there and used their
       facilities - I'll pay the premium. But, when I know I need a
       specific technology, I'm going online. We're not, in many cases,
       talking about 1 or 2 dollar differences - in many cases we're
       talking 8 - 12 dollars difference and more. Maybe that's not much
       to you, but given the fact that I have to do this some 12 - 20
       times a year, depending on project, I simply can't ignore that.
       Maybe the book stores should start getting on the publishers to get
       a bit more realisting in their pricing so that they could compete
       more effectively with the online giants - O'Reilly included. You
       guys are prolific - your books are generally good though they
       generally contain too much side material. If you took any one of
       your Java books, tooks out the "side" material that really isn't
       relevant to the topic, and cut the prices by about 25%, you'd
       probably put the stores in a position to better compete. Until
       then, you don't get a better selection, review set or price, in my
       experience, than Amazon.com. I hate to say it - it sounds cold and
       I'm really not that way, but, I'll take Amazon over Softpro any day
       of the week. It's just too expensive in this day and age to be
       paying those premium prices.

     * As a Former Employee of Borders...
       2003-08-12 11:02:28  anonymous2 [View]
       I've seen many people leafing through the books and then leaving
       them in the cafe to go to ruin. The problem with tech books is that
       some of them have a short life span, so I can see why someone would
       want to go through it and choose to purchase it cheaper online.
       I used to purchase them in the store with my employee discount.
       Sometimes what I would buy would be a book that has a little wear
       due to people looking through it. I've gotten the same result from
       supposedly "new" books from Amazon.
       The fact that the store even lets employees get discounts on it
       suggests that the markup is too high. The brick and mortar stores
       need to come down a little bit on the price if they want to
       compete, at least give a discount equal to the amount of sales tax.

     * Buy where you shop
       2003-08-05 11:45:38  anonymous2 [View]
       I mourn the loss of the many, many independent
       bookstores of my youth.

     * Shop bricks 'n mortar, buy online from same chain
       2003-07-31 21:54:11  anonymous2 [View]
       Tim,
       I recently read your editorial in the Spring 2003 O'Reilly catalog
       regarding buying books where you shop. It was thought provoking and
       I agree with the point you were making.
       I would like to solicit your thoughts on a common practice of mine:
       I will go to my local Borders bookstore, browse, then go to
       Borders.com (I know, they're teamed up with Amazon now; you could
       substitute Barnes & Noble for sake of example) and order the
       book(s). The main point here is that I buy at the online store of
       the brick and mortar bookstore I visited. In my case, that is
       almost always Borders (since they use Unix) as opposed to Barnes
       and Noble (which uses Windows). Please also note that I do not
       purchase online exclusively; more often than not my wife and I walk
       out of Borders with something under our arm.
       Why do I frequently buy online after shopping at the local
       bookstore? Two main reasons. First, I save significant money
       because the book is typically discounted online, I don't have to
       pay sales tax, and I buy enough to get free shipping. Second, I get
       to thumb my nose at the idiots in the Tennessee State Legislature
       who want to impose a repressive 9.25% sales tax on me because
       they're too stupid (and cowardly) to fix our tax system.
       What I'd like your thoughts on, since I don't have a lot of
       knowledge about the publishing industry, is am I really harming
       Borders (or Barnes and Noble) by this practice? I would think that
       the major chains would realize that I'm not the only one doing this
       and therefore "subsidize" the brick and mortars with the profits
       from the online store. Am I wrong about that?
       I certainly see how I would be harming a local Mom and Pop
       bookstore if I browsed there, then went to Amazon.com to buy, but I
       don't see how buying at the online store of the brick and mortar I
       browsed at harms them. Please enlighten me if I'm wrong...
       Kevin Buterbaugh - Systems Engineer

     * Tim O'Reilly photo Shop bricks 'n mortar, buy online from same
       chain
       2003-08-01 08:23:39  Tim O'Reilly | O'Reilly Author O'Reilly
       Blogger [View]
       I'd say that this is a fair compromise on the issues I raise.
       You're making sure to patronize the store whose services you use,
       but choosing their lowest cost channel. This seems entirely
       legitimate to me.

     * Shop bricks 'n mortar, buy online from same chain
       2003-11-25 06:41:37  anonymous2 [View]
       It's not a good compromise at all.
       Though you do indeed support their business, the store itself will
       end up in the red and in the end be closed or scaled back to sell
       other things only.
       Or do you make a note in the comments field on your online order
       that you noticed the book in their real store in XXXXX and liked it
       so much (and then hope someone actually takes note of that)?
       The net effect is still that physical stores are loosing business
       due to web orders, a loss that will translate into reduced
       floorspace and manpower and in the end closure of those physical
       stores.

     * Value of customer service
       2003-07-02 14:26:28  anonymous2 [View]
       I grew up in a retail store with my family. I learned the value of
       "customer service" and see so much of it missing today. I agree
       with your premise of buying where you shop but only if they deserve
       your business. I went to buy a computer book at full price recently
       at Borders. The cashier did not say hello, goodby, thank you, or
       even manage to look at me during the entire transaction. I don't
       mind spending the money but I want the service to go along with it.
       Otherwise, buying online is much easier and quicker and I even get
       a thank you email!
       Henry Fleischman

     * Tim O'Reilly photo Value of customer service
       2003-07-04 09:01:52  Tim O'Reilly | O'Reilly Author O'Reilly
       Blogger [View]
       No question. People really don't realize how much the personal
       contact matters. But I do want to say that the article was inspired
       by conversations with stores that do impeccable customer service.
       The owners of most of the tech independents are in the store,
       knowledgeable, talking to customers all the time. And still people
       shop there, then go off to buy online for the discount!
       As to the chains, it's a tough situation for them. Sales decline,
       so it's harder for them to stay interested in an area, so they hire
       people with less and less skill. And of course, it's always harder
       to scale something to that size and keep the quality up. The people
       in the original Borders stores were just like the people at the
       independents. And the founders of B&N still have enormous passion
       for the business and the customer. But building a truly
       customer-centric culture at a company is hard.
       I struggle with that at O'Reilly, reminding people all the time
       that engagement matters. I figure if I have the time to respond to
       random emails and proposals, have an occasional blog, and answer
       talkbacks on articles, other people ought to have time too. But
       it's hard to make it part of everyone's regular practice.

     * Price matters, sometimes
       2003-06-19 15:00:04  anonymous2 [View]
       Being blind the whole issue of browsing through bookstores doesn't
       apply (but I 100% agree with the article). However, I do use a
       bookstore when I want to pay by cash, or if I want the book
       immediately (I guess you could consider these services of the
       store).
       Yesterday I went to the local Waterstones to buy an O'Reilly CD
       bookshelf - I wanted it before I went on holiday. But in this case
       the store was selling the book for 30 more than Amazon. For the
       first time in my life I said "no thanks" and bought it on Amazon.
       This set me off thinking that the price difference depends on how
       expensive the book is. For most computer science books (costing
       about 30-40) you're only paying about 5 for the convenience of
       shopping in a store. This, I am willing to pay. For non-technical
       books you only pay 2 or 3 more than Amazon, so I don't even think
       twice about buying in a store.
       So, while I agree with the article, there's a bit of a moral
       dilemma when the amount you save is substancial.

     * Tim O'Reilly photo Price matters, sometimes
       2003-07-04 09:07:55  Tim O'Reilly | O'Reilly Author O'Reilly
       Blogger [View]
       I don't disagree that sometimes there's "a bit of a moral dilemma"
       although I think it's less of a moral dilemma and more of a
       practical one. The question you have to ask yourself is if you'd
       miss the brick and mortar retailer more than you'd miss the extra
       dollars. And of course, you can weigh how much of a difference you
       think your dollars will make, and how big the spread is, and make
       different decisions at different times based on that calculus.

     * Browsing as a service
       2003-06-17 10:35:38  yabdi [View]
       Instead of having people pay more money for books they can buy
       cheaper online, Bookstore owners should rethink their business
       model.
       Personally, I think they should move from a model of selling books
       to a model where they become a hybrid of coffee
       house+library+learning center with yearly membership fees(ala Gym
       membership) or $10 for 3 hours (like going to the movies). I buy a
       lot of computer books and I can't afford to pay the full price $60
       or more when I can get 30% off with free shipping.

     * I bought my first O'Reilly book at Softpro
       2003-05-31 20:49:07  anonymous2 [View]
       in Burlington
       Using C on the UNIX System. Spiral binding...
       In those days, going to that store was usually how I found out what
       titles existed on a particular topic.
       I can pretty much always find what I'm looking for there, and if
       I'm in a hurry, the staff will point me to exactly where it is on
       the shelves. I still discover new titles I hadn't known about as
       I'm browsing. And occasionally my browsing leads me to forego a
       title that really looked good from it's cover, but just wasn't what
       I needed when I looked inside. Other times I'll find which author
       of a Java networking book has addressed a problem very similar to
       something I need to do.
       As I look at my bookshelves, I would estimate 85-90% of the books
       are from Softpro

     * I bought my first O'Reilly book at Softpro
       2003-07-18 13:47:13  anonymous2 [View]
       That's the same store where my own O'Reilly books are mostly from
       too (I have 2 or 3 from a local B&N where I first disovered
       O'Reilly years ago). A friend showed me SoftPro (the Burlington, MA
       store) last year, I joined the "Team O'Reilly" program there, and
       I've bought enough books to already have several free ones from
       that program. All the books were discounted 20% off the top, and
       the employees there (sometimes the store owner is there too) are
       really knowledgeable about what they stock. Although I haven't been
       able to attend one yet, the store also hosts live talks by many of
       the authors whose books they carry.
       I would never get this kind of service and enjoyable shopping
       experience online, and I don't think I've paid much more for my
       books there than Amazon was selling them for. Mostly, I love
       knowing I'm supporting an "indie" business which cares about its
       offerings and its customers.
       I realize not everyone is fortunate to have a store like this close
       by, but I agree, if you can get in there to browse, and they have
       what you need, keep them in business and make the purchase there
       too.

     * Long-term consequences
       2003-05-27 09:55:47  anonymous2 [View]
       It's quite true that the bookstore owners should not have to
       subsidize the browsing and selection process of people who have no
       intention of actually buying those books from the stores. It
       reminds me of an observation made by Henry Hazlitt, in his classic
       "Economics in One Lesson": A key to correct economic analysis is
       thinking through the long-term and unintended consequences of all
       actions in the marketplace.
       Another way in which the brick-and-mortar booksellers are hurt, is
       the damage done to technical books when they are used repeatedly as
       reference books by techies seeking answers to questions, or
       students spreading them out on the floors and doing their homework.
       Even worse is the practice of slitting open the plastic sleeves in
       the back, extracting the CD-ROMs, and burning a copy using their
       laptop computers. A similar practice is actually stealing the CD
       (which alone does not have any sort of theft-deterrence magnetic
       tag). Just the other day I opened up a large technical book at
       Bookstar, flipped open the back cover to see if the book had an
       accompanying CD, and found the sleeve to be empty.
       Let's hope that owners of bookstores do not have to resort to
       closing their doors to get the message across to folks who are
       taking them for granted.

     * Use it or lose it
       2003-05-25 03:16:17  mted19 [View]
       Maybe we need to change our attitude to buying certain things. If
       you use a bookstore as a library, then it's not a store, it's a
       service. Every so often you should pay for that service by buying a
       book. If you use the reviews on Amazon a lot, or use the wish list
       service to keep track of everything you need to read, then every so
       often you should buy from them.
       You could also say that smaller local stores offer a service just
       by their existance, just by being convenient and offering you a
       choice. Every so often, you should buy from them. You shouldn't
       feel obliged to buy from every store you ever browse in. But when
       you cross that line of using them as a service, and wanting them to
       continue providing that service, you should be prepared to pay a
       little towards that.

     * Responsible browsing
       2003-05-23 05:47:09  mariox19@mac.com [View]
       I see people bringing their laptops to the coffee tables at Barnes
       & Nobles and pulling computer books off the shelves. Never mind
       writing term papers, these people are obviously coding, which is
       just unconscionable.
       But "extreme browsing" is often a way of gaining a general
       education through gleaning. I've spent many hours browsing, leafing
       through computer books on many topics in an effort to gain an
       overview of programming and computer science. (I'm a self-taught
       hobbyist who has purchased hundreds of dollars worth of books in
       the last two years from bookstores.)
       Am I supposed to buy books on assembly programming, networking in
       C, Smalltalk, operating systems and so forth, when I have no
       interest, currently, in using that knowledge in my programming? I
       put what I can into my brain, knowing that years from now I may
       have an interest in it and the experience to begin to study
       advanced topics. The only way I will be able to judge that, though,
       is by surveying the vast material now.
       I am careful and respectful in my handling of books, and find
       myself straightening the shelves. I'm sure there are many others
       who act the same.
       The average computer book is running around $40. There is no way I
       could buy every book without searching for online bargains. By the
       time I have decided to purchase a book, I have leafed through it in
       a bookstore and read reader reviews from one or more online
       booksellers.
       Who should get the sale?
       The market is getting complicated, and where loyalty should lie is
       not as clear as you make it seem, I'm afraid.

     * Book Stores
       2003-05-22 09:28:52  rkovars [View]
       I enjoyed reading your article about buying where you browse. I
       live in the Northeast United States, a rather tech savy area.
       I agree that a bookstore is not a library. I too see far too many
       people 'lounging' in bookstores. It is one thing to go tothe
       bookstore to browse because you are killing time or out shopping.
       It is quite another to use it as a resource without giving anything
       back.
       There is also something to be said about the large chain vs the
       small independant. I have been frequenting a small independant
       store in my area. I try to get anything I can from them. They are
       kind curteous and responsive to my needs. They continually listen
       to the input to improve the store. They get my vote over the big
       stores any day. One thing I can say is that anyone who shrugs and
       tells me they rely on corporate for their business would lose a
       customer.
       I think in a situation like this you have to think about the author
       too. Sometimes that good deal online is too good to be true and the
       author is left out of the loop. Publishing is a strange and wild
       game.
       The bottom line to any of this, I think, is that if we want to see
       more books on the shelves, we have to pony up for the privelage.

     * Wei-Meng Lee photo The situation in Singapore
       2003-05-17 07:16:08  Wei-Meng Lee | O'Reilly Author [View]
       The situation in Singapore is slightly different. In Singapore,
       because of its size a
       bookstore is always within half-an-hour drive (on average) away. We
       have a couple of computer bookstores which are well-stocked with
       computer books and I am always able to get what I want from one
       particular computer bookstore. My observation is that computer
       people tend to avoid bigger chains like Borders due to its straight
       conversion from US dollar to Sing dollar. We could get a better
       bargain through the computer bookstores as they get their books
       from a local distributor, which is always able to give a better
       price.
       Online bookstores has never really taken off in Singapore. A couple
       of businesses have gone online and failed miserably. This is not
       surprising since finding a bookstore is really easy in Singapore
       and people would always want to get a book fast. Moreover, buying
       books online does not get any cheaper and ordering online from
       Amazon.com is really expensive. The delivery charge is sometimes
       higher than the cost of the book itself. It is only when a book
       cannot be found in Singapore that you would order online.
       But the scenario that Tim mentioned is very common in Singapore (I
       think it happens everywhere). People go to bookstores and spend
       their whole afternoon browsing through the books, mostly with no
       intentions of buying. Worst, the books would often end up with have
       dog-ears, rendering it unsaleable. Magazine sections are the worst
       hit, but I guess that is a slightly different problem as their
       business model is different from the book market. In general, the
       mentality of most people is that a bookstore is just like a library
       - they are free to browse with no social obligation to buy.
       Bookstores are not doing well in this difficult time. A number of
       big names have closed down. A critical factor to realize in this
       difficult time is that the consumer dollars is shrinking. With a
       shrinking budget and an increasing pool of new titles (do a count
       of the number of .NET titles published by other publishers and see
       if you can decide on which one to buy), the eventual party to
       suffer is still the publisher. But on the other end the publisher
       is also facing financial pressures - stop doing new titles and the
       revenue will stop. I think O'Reilly's strategy of doing
       non-overlapping titles (and making that just one title really good)
       will pay off in the long term and allow it to stay afloat in this
       tough time.
       Wei-Meng Lee

     * Tim O'Reilly photo Re. Intro
       2003-05-07 14:54:05  Tim O'Reilly | O'Reilly Author O'Reilly
       Blogger [View]
       I agree with B&N. And I know that this was part of Steve Riggio's
       reluctance to add wifi to the B&N stores. (I talked to him about
       it.)
       I also agree that the selection could be better at many bookstores.
       But that's precisely my point: if you are forced to shop online
       because of the poor brick and mortar selection, that's where you
       should buy. But there are a lot of people who spend time in local
       bookstores looking at books, and then, adding insult to injury,
       tell the bookseller they plan to buy online for a better price.

     * Buy where you shop
       2003-05-07 14:48:15  anonymous2 [View]
       Just finished this piece on the inside cover of your spring 2003
       catalog. You're right on target--for books and for other stuff. I
       have sold musical instruments on E-bay, but when I want to try one
       out before I buy it, I go to my local retailer. Then I buy it from
       him if I buy it at all. "The future we create is [even more] the
       result of small decions we make every day." --quotable.
       David Bolsover

     * Buy Where You Shop
       2003-05-07 14:46:38  anonymous2 [View]
       Greetings, sir! I just got my catalog and read your opening comment
       and felt I had to respond. It hit a nerve.
       I've heard a lot about how "the big bad Internet is hurting
       brick'n'mortar shops" and from my experience it's mostly the shop's
       fault.
       For me, it's not the prices, it's the awful service and selection.
       Let me explain that I live in Orlando, Florida. A reasonably large
       city, famous for the Mouse, and a place where you'd expect a lot of
       well-stocked bookstores (and stores in general).
       However, this is definately not the case. For instance I have a
       large Barnes & Noble next door. We're 45 minutes from the Kennedy
       Space Center, and there's maybe a half dozen space books on the
       shelf, all of which are glossy no-tech picture books on the
       Shuttle. We never went to the Moon, I guess.
       There are very few non-Microsoft-related computer books... none on
       Python or Oracle, maybe a copy of the Camel book, and one thin
       Linux book.
       I've asked the owner why, and she just shrugs and says "we have
       what corporate sends us" - no interest in my suggestions or in
       improving her store at all.
       It's a pain to order anything as they never call to let you know
       your book arrived, so *you* end up calling repeatedly. Why would I
       put up with this when I can click a couple of links and have a book
       miraculously on my doorstep a few days later?
       That's what drives me to buy from the Internet. And to stop even
       browsing in the bookstores. I don't even have the choice of
       browsing then going home to buy on-line.
       Of the dozen bookstores in town, there's one shining exception,
       which is a Borders near work (a major Oracle Corp. support center)
       where the manager has obviously realized he'd make major money by
       stocking lots of computer books. He buys wacky offbeat stuff too,
       like very technical digital photography books, so that I've spent a
       lot of time and money there. I make sure to buy all my O'Reilly
       books there. I've gotten him interested in stocking space books
       too, and from him I've bought almost every single Apogee book that
       www.cgpublishing.com makes.
       It's not just books, either. I've been an avid motorcyclist for
       about 20 years, and there are 3 big bike dealerships in town that I
       frequent. All of them stock from the same Tucker-Rocky catalog, and
       have the exact same Olympia gloves, Joe Rocket jackets, Tourmaster
       rainsuits, Shoei helmets, etc hanging from the walls. They complain
       that people try on their helmets then buy on-line. I respond that
       the last time I had them order a helmet in my size, it took 2
       months to arrive. They don't even stock the lines of jackets &
       gloves that I would buy, so I end up buying sized apparel from the
       'net, which I hate.
       They complain that they hate mounting tires that people buy from
       the 'net, when their prices are double what you'd find online. Why
       would I buy a rear stand for $319 when I can buy a matched
       front/rear set of stands online for $100??
       I have to buy luggage racks for my bike from Germany, the hard
       luggage from Italy, and an automatic chain oiler from Scotland, as
       it's not even available from the dealer at any price. And this is a
       dealer where I've bought 2 used bikes and a new one, so it's not
       like I'm an infrequent
       customer that doesn't spend money.
       I understand that every item in stock counts against the bottom
       line, but if they don't stock anything, how am I buy it or to find
       out about it so I can have it ordered?
       Heck, I still have a copy of "Managing UUCP and Usenet" that I
       bought in '89, and I remember I had to drive 190 miles to get it. I
       remember those dark days... it was like the quest for the Holy
       Grail, and not the funny Monty Python version either! I remember
       lusting over a coworker's X11 reference books, and not having
       anywhere to buy them as the local response was "O'Reilly who? We
       don't order from people we don't know."
       I'm extremely grateful for the selection that the Internet gives
       me. I'd be totally out of luck without it.
       Thanks for letting me vent a little steam. I hope I've shared a
       little of what it's like to be on the other side of the sales
       counter. And thank you for your company's excellent line of books
       that have saved my butt too many times to count.
       Gene

     * Buy where you shop intro
       2003-05-07 14:40:46  anonymous2 [View]
       Just read through this, and it made me want to get another opinion
       on the whole B&N phenomenon, where there are clearly people who go
       there to read books and lounge around in the chairs for hours, with
       no intention of buying anything. I often see people in there
       writing notes as if preparing a report, using it as a library. It
       is really quite appalling if you think about it. I've got no
       problem with browsing a book for a few minutes to see if it suits
       your needs, but this is clearly over the top. When the Computer
       literacy chain in Silicon Valley got sucked up, I was depressed.
       I've since discovered San Diego technical Books since I moved to
       San Diego, and will do what I can to keep them going.
       Brian
       The path to a desireable destination is often more difficult than
       the path to stay where you are.




   Sign up today to receive special discounts,
   product alerts, and news from O'Reilly.
                                              Enter Email_ submit
   Privacy Policy >
   View Sample Newsletter >
     * Twitter
     * YouTube
     * Slideshare
     * Facebook
     * RSS
     * View All RSS Feeds >

   © 2014, O’Reilly Media, Inc.

   (707) 827-7019 (800) 889-8969

   All trademarks and registered trademarks appearing on oreilly.com are
   the property of their respective owners.

About O'Reilly

     * Academic Solutions
     * Jobs
     * Contacts
     * Corporate Information
     * Press Room
     * Privacy Policy
     * Terms of Service
     * Work with Us
     * Editorial Independence

Community

     * Authors
     * Webcasts
     * Community & Featured Users
     * Forums
     * Newsletters
     * O'Reilly Answers
     * RSS Feeds
     * Meetups & User Groups
     * O'Reilly Atlas (beta)

Partner Sites

     * makezine.com
     * makerfaire.com
     * craftzine.com
     * igniteshow.com
     * PayPal Developer Zone
     * O'Reilly Insights on Forbes.com

Shop O'Reilly

     * Customer Service
     * Contact Us
     * Shipping Information
     * Ordering & Payment
     * Affiliate Program
     * The O'Reilly Guarantee
