   #RSS alternate

   PeerJ
     *
     * Submit your work today
     *
     * Signup & Pricing

     * Twitter
     * Facebook
     * Google+

PeerJ - the blog

   Official blog of PeerJ. Publisher of PeerJ a peer-reviewed, open access
   journal and PeerJ PrePrints an innovative 'pre-print' server. Your
   Peers, Your Science. Academic Publishing is Evolving.

     * 3rd February 2014
     * Permalink
     *
     * Tweet this

   AMA ask me anything

Get PeerJ article alerts

   ____________________

   It's Free. Enter your email or learn more.
   Next →
   A TEXT POST

Ask Me Anything - Correcting the Scientific Record in Plant Science

   Live Event – ‘Ask Me Anything’ session with Prof. Pamela Ronald, Dr.
   Ofir Bahar​, Dr. Rory Pruitt​, Dr. Benjamin Schwessinger, and Dr.
   Arsalan Daudi

   Who & What: Ask Prof. Ronald, Dr. Bahar, Dr. Pruitt, Dr. Schwessinger,
   and Dr. Daudi will discuss their PeerJ article and their retraction
   experience.

   When: Tuesday, February 18th, 9 am – 10 am PST

   Where & How: Visit https://www.peerj.com/ask/PlantMicrobeInteractions

   We are pleased to announce that Tuesday, February 18th, 9 am – 10 am
   PST (5 pm – 6 pm UK time), we will be holding our third ‘Ask Me
   Anything’ live session, with Prof. Ronald, Dr. Bahar, Dr. Pruitt, Dr.
   Schwessinger, and Dr. Daudi.

   image

   Prof. Ronald has spent 25 years studying how plants respond to disease,
   and how they can defend themselves against infections. Plants, like
   animals, have immune receptors that detect microbial invasion and
   initiate innate immune defenses. In 1995, Prof. Ronald’s group isolated
   a rice immune receptor, called XA21, which drives resistance to a
   disease-causing bacterium called Xanthomonas oryzae. The researchers
   hypothesized that the receptor XA21 was activated via a molecule
   secreted by the bacterium.

   Nearly 15 years later, the team published two papers showing that the
   receptor XA21 recognizes a small bacterial protein called Ax21. They
   also showed that a mutant strain of Xanthomonas oryzae, which lacked
   the gene for Ax21, could successfully infect rice leaves.

   But new lab members could not repeat the earlier results, and the group
   started to question its own findings. The group members eventually
   discovered that a bacterial strain they had been using was contaminated
   and a bioassay they had relied on was flawed, so they retracted their
   PLOS ONE and Science papers.

   Prof. Ronald and her group members have now published a new PeerJ paper
   investigating the function of the bacterial protein Ax21, and they
   present data that corrects their previous model.

   If you want to learn about microbial infection of plants, or if you are
   curious about ‘clean-up operation’ when you uncover experimental
   mistakes, visit https://www.peerj.com/ask/PlantMicrobeInteractions,
   leave your questions at any time - before, during, and after the event
   - and get all your questions answered!

   Prof. Ronald, Dr. Bahar, Dr. Pruitt, Dr. Schwessinger, and Dr. Daudi
   will be online and interacting on Tuesday, February 18th, 9 am – 10 am
   PST.
   Please enable JavaScript to view the comments powered by Disqus. blog
   comments powered by Disqus

   PeerJ / Archives / Feed / Follow on Twitter

   [impixu?T=1411963545&J=eyJ0eXBlIjoidXJsIiwidXJsIjoiaHR0cDpcL1wvYmxvZy5w
   ZWVyai5jb21cL3Bvc3RcLzc1NDk3Mzg1NjI2XC9hc2stbWUtYW55dGhpbmctY29ycmVjdGl
   uZy10aGUtc2NpZW50aWZpYy1yZWNvcmQiLCJyZXF0eXBlIjowLCJyb3V0ZSI6IlwvcG9zdF
   wvOmlkXC86c3VtbWFyeSIsIm5vc2NyaXB0IjoxfQ==&U=OOABBJFLLK&K=6979f70da670b
   01a71a00f6e7b9eca4cbd1c9b3dae63fb6072039a24ad164052&R=]
   [impixu?T=1411963545&J=eyJ0eXBlIjoicG9zdCIsInVybCI6Imh0dHA6XC9cL2Jsb2cu
   cGVlcmouY29tXC9wb3N0XC83NTQ5NzM4NTYyNlwvYXNrLW1lLWFueXRoaW5nLWNvcnJlY3R
   pbmctdGhlLXNjaWVudGlmaWMtcmVjb3JkIiwicmVxdHlwZSI6MCwicm91dGUiOiJcL3Bvc3
   RcLzppZFwvOnN1bW1hcnkiLCJwb3N0cyI6W3sicG9zdGlkIjoiNzU0OTczODU2MjYiLCJib
   G9naWQiOiIzNTI3MDAzMyIsInNvdXJjZSI6MzN9XSwibm9zY3JpcHQiOjF9&U=MGGJBEJBB
   F&K=aec84bc232aa728a2b6ccc55d1661e85ddce6e1124494048def1f74d08b21afe&R=
   ]

   IFRAME:
   https://secure.assets.tumblr.com/assets/html/iframe/o.html?_v=a3c986ced
   f26e801e27d7606000d9429#src=http%3A%2F%2Fblog.peerj.com%2Fpost%2F754973
   85626%2Fask-me-anything-correcting-the-scientific-record&pid=7549738562
   6&rk=kZ7hGyF6&lang=en_US&name=peerj&brag=false&avatar=http%3A%2F%2F33.m
   edia.tumblr.com%2Favatar_41b0b94c24d0_64.png&title=PeerJ+Blog&url=http%
   3A%2F%2Fblog.peerj.com%2F&page_slide=slide

   IFRAME:
   https://www.tumblr.com/assets/html/iframe/teaser.html?_v=5943241a53f291
   2a3a7626ce147a56c6#src=http%3A%2F%2Fblog.peerj.com%2Fpost%2F75497385626
   %2Fask-me-anything-correcting-the-scientific-record&pid=75497385626&rk=
   kZ7hGyF6&lang=en_US&name=peerj&brag=false&avatar=http%3A%2F%2F33.media.
   tumblr.com%2Favatar_41b0b94c24d0_64.png&title=PeerJ+Blog&url=http%3A%2F
   %2Fblog.peerj.com%2F&page_slide=slide
