   #publisher The Atlantic Best of The Atlantic Politics Channel




   Continue to TheAtlantic.com [arrow.png]
   Advertisement

The Atlantic

   Subscribe Now
   [medium.jpg?nc2mvq]
   [shop_JUL09_2014_cards.jpg] [shop_JUL09_2014_Mtee.jpg]
   [shop_JUL09_2014_mugs.jpg] [shop_JUL09_2014_Wtee.jpg]
   ____________________ (BUTTON)
   Get The Atlantic on Facebook
     * Politics
          + Top Stories
          + The Supreme Court Is Looking Out for the Rights of the
            Majority
          + Eric Holder's Legacy as Attorney General
          + The Little Rock 9: How Far Has the Country Come?
          + The Mystery Candidate Shaking Up Kansas Politics
          + How Politics Breaks Our Brains
          + Books for the Horde: The New Jim Crow, Chapters 2 and 3
          + Sponsor Content The Brooklyn Navy Yard Is Creating a New Model
            for Urban Revitalization
            [adServer.bs?cn=tf&c=19&mc=imp&pli=11099584&PluID=0&ord=%%CACH
            EBUSTER%%&rtu=-1]
          + Sponsor Content Hologic Enables Better Outcomes for Patients
          + Sponsor Content Solazyme Is Producing a New Source of
            Renewables
          + Sponsor Content MRC Global: A Leading Supplier to the Energy
            Industry
          + Sponsor Content How Titan International Is Creating American
            Manufacturing Jobs
     * Business
          + Top Stories
          + Saving Paris's Oldest Bookstore
          + Christmas Ads Already?! Actually, Most People Don't Seem to
            Mind
          + Is Bike Sharing Just for Gentrifiers?
          + Peter Thiel's Zero to One Might Be the Best Business Book I've
            Read
          + "Kleenex Is a Registered Trademark" (And Other Desperate
            Appeals)
          + America, the Plannable: How Banks Affect Family Size
          + Sponsor Content The Extinction of Spectator Sports
          + Sponsor Content The Search for the Next Yellow Line
          + Sponsor Content How Apps Might Change Your Swing
          + Sponsor Content Protecting the World's Most Valuable Human
            Real Estate
          + Sponsor Content Blood, Sweat and Data
     * Tech
          + Top Stories
          + Beyond GMOs: The Rise of Synthetic Biology
          + The Woman With the Bionic Eye
          + How to Stop a Rumor Online (Before the Rumor Becomes a Lie)
          + When Everything Works Like Your Cell Phone
          + Ello Says You're Not a Product, But You Are
          + Peering Ever Deeper Into Matter
          + Sponsor Content The Art and Science of Our Senses
            [B8161992.110556643;sz=1x1;ord=%n]
          + Sponsor Content Solving for Sound
     * Entertainment
          + Top Stories
          + The Equalizer: The Ultimate Denzel Washington Role
          + Did Clayton Kershaw Just Have the Best Summer in Baseball
            History?
          + 30 Years of Coens: True Grit
          + "Can a TV Show Save Lives?"
          + Lost, Bill Simmons, and Denzel: The Week in Pop-Culture
            Writing
          + Dave Matthews Band, Happy Rebels
     * Health
          + Top Stories
          + How to Test a Couch for Toxins
          + Toward an Effective Tuberculosis Vaccine
          + The World War II Campaign to Bring Organ Meats to the Dinner
            Table
          + The Health Effects of Leaving Religion
          + France's Troubled Romance With Beef
          + How Exercise Could Erode Teeth
     * Education
          + Top Stories
          + B.J. Novak Proves That Kids' Books Don't Need Pictures
          + How to Make Teachers More Like Doctors
          + Why Girls Tend to Get Better Grades Than Boys Do
          + The Little Rock Nine: How Far Has the Country Come?
          + Where Girls Get Kidnapped on Their Way to School
          + What Do You Wish You Had Learned in College?
          + Sponsor Content The Solution to the US Skills Gap Isn't What
            You Think
          + Sponsor Content This is the Future of Your Commute
          + Sponsor Content How Smart Grids Could Transform the Developing
            World
     * Sexes
          + Top Stories
          + Where Girls Get Kidnapped on Their Way to School
          + Pop Culture's Transgender Moment: Why Online TV Is Leading the
            Way
          + The Economic Case for Paternity Leave
          + When Bosses Discriminate Against Pregnant Women
          + Will "Cisgender" Survive?
          + No, Hope Solo Is Not "Like" Ray Rice
     * National
          + Top Stories
          + The “Other” America
          + Kosher Meets Hipster
          + When Philosophy Becomes Therapy
          + The Health Effects of Leaving Religion
          + Cop Asks for Man's License, Shoots Him When He Reaches for It
          + Saving Wukchumni
          + Sponsor Content Cities Need Small Business Growth Strategies
            [B8212757.15;dc_trk_aid=284503546;dc_trk_cid=59471219;ord=%%CA
            CHEBUSTER%%]
     * Global
          + Top Stories
          + Songdo, South Korea: City of the Future?
          + France's Troubled Romance With Beef
          + Why Is the U.S. Yielding to Iran Now?
          + Saving Paris's Oldest Bookstore
          + Dismantling Empires Through Devolution
          + China's Other Food-Safety Problem
     * Video
          + Top Stories
          + Famous Movies Recreated With Stock Footage
          + What Is a City?
          + The Flight of a Moth, In Extreme Slow Motion
          + What Do You Wish You Had Learned in College?
          + Saving Wukchumni
          + CrossFit Versus Yoga: Choose a Side
     * Magazine
          + In This Month's Issue
          + What Happens When We All Live to 100?
          + Why I Hope to Die at 75
          + How Gangs Took Over Prisons
          + [medium.jpg?nc2mvq]
               o Subscribe
               o Renew
               o Give a Gift
               o Digital Editions

     * Subscribe
     * Events
     * Newsletters
     * Books
     * Apps
     * Features
     * In Focus
     * Just In
       The Health Effects of Leaving Religion

     * [skybox-thumb.jpg?ncif2m]

The Supreme Court: Looking Out for the Majority
       By Garrett Epps
     * [skybox-thumb.jpg?ncif2m]

30 Years of Coens: True Grit
       By Christopher Orr
     * [skybox-thumb.jpg?ncif2r]

Dismantling Empires With Devolution
       By Parag Khanna
     * [] Sponsor Content The Search for the Next Yellow Line
     * [] Sponsor Content How Apps Might Change Your Swing
     * [] Sponsor Content Protecting the World's Most Valuable Human Real
       Estate
     * [skybox-thumb.jpg?ncj3ob] Sponsor Content Blood, Sweat and Data
     * [skybox-thumb.jpg?ncj41i] Sponsor Content The Extinction of
       Spectator Sports

Campaign-Finance Reform Has to Be Cross-Partisan

   Democrats love to talk about cutting the influence of money in
   politics, but are they actually any more eager to fix it than
   Republicans?
   Lawrence Lessig Jun 18 2014, 10:43 AM ET
   Tweet
   More
   Email
   Print
   [lead.jpg?n7dcvx]
   takomabibelot/Flickr

   The vast majority of Americans—more than 90 percent in recent
   polls—believe it “important” to “reduce the influence of money in
   politics.” But is the business model of the reformers actually
   consistent with winning reform?

   This is the fair but hard question raised by the strategy planned by
   Senate Democrats this summer to force a vote on New Mexico Senator Tom
   Udall’s proposed constitutional amendment to give Congress the power
   “to regulate the raising and spending of money” in elections.
   Forty-three Senate Democrats have cosponsored the resolution. Zero
   Republicans have. Zero is the same number of Republicans who have
   joined any of the proposed constitutional amendments now floating about
   in Congress to, as they are described, “reverse Citizens United.”
   Constitutional reform to give Congress the power to further regulate
   campaign cash is the exclusive domain of the Democrats (excepting, of
   course, the ACLU Democrats; the ACLU opposes such amendments).
   The Senate debate this August will not change a single GOP vote. But it
   is certain to raise a ton of campaign cash for Democrats—just in time
   for the midterms.

   I suspect Democrats like it this way. These amendments are catnip to
   the Democratic base, the equivalent of Obamacare for Republicans. The
   Senate debate this August will not change a single Republican vote. But
   it is certain to raise a ton of campaign cash for Democrats—just in
   time for the 2014 elections.

   For Congress to actually propose an amendment to the Constitution
   requires 67 votes in the Senate (and 290 votes in the now
   Republican-controlled House). On the current count, that means at least
   a dozen Republicans would need to cross the aisle to join Udall
   (assuming what certainly isn’t given—that he could get a unanimous vote
   from his own party). And though I am no leader of the U.S. Senate, it
   seems to me unlikely that forcing a partisan fight on the eve of an
   election is a winning strategy for flipping at least a third of Senate
   Republicans. Nor does it seem likely—unless annexing Canada is in the
   works—that Democrats are going to gain a two-thirds majority in the
   Senate anytime soon.

   Instead, if there is going to be fundamental reform, that reform must
   be cross-partisan. And in the upset election that removed Eric Cantor,
   the seeds to that cross-partisan reform are clear.

   The single central flaw in American democracy today is not the speech
   within elections—not how much or how nasty or by whom. The single
   central flaw is the fundraising. America has outsourced the funding of
   campaigns to the tiniest fraction of the 1 percent. That tiny fraction
   then leverages its power to enormous effect. It turns otherwise
   conservative Republicans into “crony capitalists”—the tag David Brat
   successfully attached to Eric Cantor. It turns otherwise progressive
   Democrats into the “tools of Wall Street”—think Clinton-led
   deregulation in the 1990s. Bending goes both ways, pushing the
   principles on both the right and left off the table. The reality of the
   need to fundraise is the reality of everything in D.C. And thus it is
   no surprise that the largest empirical study of policy decisions ever
   in the history of political science finds a government responsive to
   the wants of the “economic elite” and “business interests,” but finds
   “average citizens ... have little or no independent influence.”

   Restricting the money spent in elections won’t change this. (Wherever
   the limit is set, the cash still needs to be raised.) Neither will
   declaring that “corporations are not persons” change this. (The tiny
   fraction of the 1 percent that funds campaigns includes no
   corporations.) The only way to change this is to change the way we fund
   elections. Both Democrats and Republicans have offered strategies for
   spreading out the funder influence, consistent with the Constitution as
   interpreted by this Supreme Court.

   Maryland Democratic Representative John Sarbanes’s Government by the
   People Act, for example, introduced in February, would provide matching
   funds for small-dollar-funded campaigns—enough to make it possible for
   a candidate to win without becoming dependent upon this tiny fraction
   of the 1 percent. And more than two years ago, George W. Bush’s ethics
   czar, Richard Painter, proposed the Taxation Only With Representation
   Act, which would give every voter a $200 voucher to fund small-dollar
   campaigns.
     __________________________________________________________________

Related Story

   Campaign Finance and the Nihilist Politics of Resignation
     __________________________________________________________________

   These two strategies are actually the same. They both reduce the
   enormous leverage that large contributors have. And they both would
   thus remove the ongoing temptation within both parties to compromise
   their basic commitments to make their (few) funders happy. Robert
   Kaiser’s great book, So Damn Much Money, tells the story of the
   Gingrich revolution, derailed by its dependence on crony cash. Cantor’s
   “cronyism” is that story retold. And no Democrat who is honest could
   look back at the last 20 years and see a pattern for that party that’s
   much different. Both sides are held hostage by this system of campaign
   funding. Both sides have a reason to change it.

   But could either pursue a cross-partisan a strategy?

   It’s no secret that I believe that there is such a strategy. It begins
   outside of Washington; it stays firmly committed to putting partisan
   differences to one side; it remains fiercely focused on the first step
   to making every other change possible—electing a Congress committed to
   fundamental reform in the way campaigns are funded. That’s the
   objective of the MaydayPAC that I started with Republican Mark
   McKinnon. That’s the reason over 15,000 people have contributed now
   almost $3 million to demonstrate its potential in 2014.

   Yet it’s not clear that any within the political mainstream could give
   up a fundamental commitment to partisanship enough to embrace such a
   change. It’s not even clear that any of them can even utter “this is so
   good,” without adding “because they are so bad.” So if this movement
   needs to be cross-partisan, it cannot be theirs. And whether without
   them it can succeed is a question no one can answer—at least yet.
   Jump to comments
   Tweet

   IFRAME:
   http://www.reddit.com/static/button/button2.html?width=51&url=http%3A%2
   F%2Fwww.theatlantic.com%2Fpolitics%2Farchive%2F2014%2F06%2Fcampaign-fin
   ance-reform-has-to-be-cross-partisan%2F372983%2F

     * Email
     * Print

   Presented by
   [author-headshot.jpg?m8tdgh]

   Lawrence Lessig is a contributing writer for The Atlantic, the Roy L.
   Furman Professor of Law and Leadership at Harvard Law School, director
   of Harvard's Edmond J. Safra Center for Ethics, and founder of
   Rootstrikers, an activist network opposed to corruption in government.
   More

   Lessig's books include Republic, Lost: How Money Corrupts Our Congress
   -- and a Plan to Stop It, One Way Forward: The Outsider's Guide to
   Fixing the Republic, and the recent Le$terland: The Corruption of
   Congress and How to End It. He serves on the Board of Creative Commons,
   MapLight, Brave New Film Foundation, The American Academy, Berlin, AXA
   Research Fund and iCommons.org, and on the advisory board of the
   Sunlight Foundation. Lessig holds a B.A. in economics and a B.S. in
   management from the University of Pennsylvania, an M.A. in philosophy
   from Cambridge, and a J.D. from Yale. Prior to rejoining the Harvard
   faculty, Lessig was a professor at Stanford Law School, where he
   founded the school's Center for Internet and Society, and at the
   University of Chicago. He clerked for Judge Richard Posner on the 7th
   Circuit Court of Appeals and Justice Antonin Scalia on the United
   States Supreme Court.
     * All Posts
     * Books
     * Follow @lessig

   [ebook-banner-zen.jpg] [TAL_WWI_Layout1.gif]
   Try 2 Free Issues! Go
     * Subscribe
     * Renew
     * Give a Gift
     * Digital Edition

   Get Today's Top Stories in Your Inbox (preview)
   Email Address ____________________ [X] Sign Up
     * Dismantling Empires Through Devolution
       Parag Khanna Sep 26, 2014
     * Toward an Effective Tuberculosis Vaccine
       Natalie Shure Sep 26, 2014
     * The Supreme Court Is Looking Out for the Rights of the Majority
       Garrett Epps Sep 26, 2014
     * The Equalizer: The Ultimate Denzel Washington Role
       Katie Kilkenny Sep 26, 2014

Video

   More video
   [video-featured.png?nciosb]

Famous Movies Recreated With Stock Footage

   From Apocalypse Now to The Lord of the Rings, this clever video puts a
   new spin on Hollywood's greatest hits.
     * Share on Facebook
     * Tweet
     *

   [home-article-curation-405x234.jpg?ncmvsw]

When Everything Works Like Your Cell Phone

   [home-article-curation-405x234.png?ncmvsw]

The Woman With the Bionic Eye

   [home-article-curation-405x234.jpg?ncmvsw]

Pop Culture's Transgender Moment

   [home-article-curation-405x234.jpg?ncmvsw]

The Economic Case for Paternity Leave

   ‹ ›
     __________________________________________________________________

Join the Discussion

   After you comment, click Post. If you’re not already logged in you will
   be asked to log in or register. Please enable JavaScript to view the
   comments powered by Disqus. blog comments powered by Disqus
   Close

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

What Do You Wish You Learned in College?

   Ivy League academics reveal their undergrad regrets

Video

   [play-button.png] [curation-special-report-thumb.png?nciy7c]

Famous Movies, Reimagined

   From Apocalypse Now to The Lord of the Rings, this clever video puts a
   new spin on Hollywood's greatest hits.

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

What Is a City?

   Cities are like nothing else on Earth.

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

CrossFit Versus Yoga: Choose a Side

   How a workout becomes a social identity

Video

   [play-button.png] [curation-special-report-thumb.jpg?nciy7c]

In Online Dating, Everyone's a Little Bit Racist

   The co-founder of OKCupid shares findings from his analysis of millions
   of users' data.

Writers

   Up
     * Julie Beck
       How Exercise Could Erode Teeth Sep 27, 2014
     * Molly Ball
       The Mystery Candidate Shaking Up Kansas Politics Sep 27, 2014
     * Megan Garber
       How to Stop a Rumor Online (Before the Rumor Becomes a Lie) Sep 26,
       2014
     * David Frum
       Why Is the U.S. Yielding to Iran Now? Sep 26, 2014
     * Joe Pinsker
       Christmas Ads Already?! Actually, Most People Don't Seem to Mind
       Sep 26, 2014
     * Chris Heller
       Famous Movies Recreated With Stock Footage Sep 26, 2014
     * Derek Thompson
       Did Clayton Kershaw Just Have the Best Summer in Baseball History?
       Sep 26, 2014
     * Conor Friedersdorf
       Cop Asks for Man's License, Shoots Him When He Reaches for It Sep
       26, 2014
     * Christopher Orr
       30 Years of Coens: True Grit Sep 26, 2014
     * James Fallows
       Iron Pigs Rising Sep 25, 2014
     * David A. Graham
       With Eric Holder's Exit, Obama Loses a Key Ally Sep 25, 2014
     * Olga Khazan
       Why Don't We Treat Teeth Like the Rest of Our Bodies? Sep 25, 2014
     * Bourree Lam
       Quantifying Americans' Distrust of Corporations Sep 25, 2014
     * Uri Friedman
       3 Men Visited 19 Countries in 24 Hours—or Did They? Sep 24, 2014
     * Robinson Meyer
       Facebook's Mood Manipulation Experiment Might Have Been Illegal Sep
       24, 2014
     * Jeffrey Goldberg
       A Pugnacious Obama Takes on (Most of) the World Sep 24, 2014
     * Ta-Nehisi Coates
       Books for the Horde: The New Jim Crow, Chapters 2 and 3 Sep 24,
       2014
     * Jennie Rothenberg Gritz
       B.J. Novak Proves That Kids' Books Don't Need Pictures Sep 24, 2014
     * Kathy Gilsinan
       The U.S. Has Bombed Two Different Sides in Syria's Civil War Sep
       23, 2014
     * Emma Green
       Half of Americans Believe Gay Sex Is a Sin Sep 22, 2014
     * Adrienne LaFrance
       Humanity's Most Famous Mixtape Is Now 11 Billion Miles From Earth
       Sep 22, 2014
     * Matt Ford
       The United States of Great Britain? Sep 19, 2014
     * Peter Beinart
       How to Defeat ISIS, According to Ted Cruz Sep 19, 2014
     * James Bennet
       “I Never Dreamed It Would Turn Out This Way” Sep 17, 2014

   Down

More in Politics

     * [channel-curation-featured-small.jpg?ncihnt]

The Supreme Court Is Looking Out for the Rights of the Majority
       Garrett Epps
     * [channel-curation-featured-small.jpg?ncihnt]

Eric Holder's Legacy as Attorney General
       David A. Graham
     * [channel-curation-featured-small.jpg?ncihnw]

The Little Rock 9: How Far Has the Country Come?
       Noah Gordon

[camera-white.png] In Focus

   [highlight_2014092609.jpg]

Photos of the Week: 9/20-9/26

From This Author

   [author-book.jpeg?mnil32]

Republic, Lost:
How Money Corrupts Congress--and a Plan to Stop It

   [author-book.jpg?n3tye1]

The USA Is Lesterland

Most Popular

   1
          Life as a Nonviolent Psychopath

   2
          Steve Kroft's Softball Obama Interviews Diminish '60 Minutes'

   3
          Peter Thiel's Zero to One Might Be the Best Business Book I've
          Read

   4
          The Health Effects of Leaving Religion

   5
          When Everything Works Like Your Cell Phone

   6
          Songdo, South Korea: City of the Future?

   7
          Why I Hope to Die at 75

   8
          The Miracle of Writing

   9
          Photos of the Week: 9/20-9/26

   10
          Dismantling Empires Through Devolution

Just In

     * The Health Effects of Leaving Religion Jon Fortenbury
     * "Can a TV Show Save Lives?" Ali Liebegott
     * When Everything Works Like Your Cell Phone Alexis C. Madrigal and
       Robinson Meyer

ATLANTIC MEDIA

CityLab

     * My 5 Favorite Maps: Bill Rankin
     * 10 Big Ideas From CityLab 2014 Attendees
     * For Bee-Friendly Parks, Head For the Great Unmown

   More from CityLab

The Wire

     * Al Qaida Leader Vows Revenge for Airstrikes in Syria
     * Hong Kong Police Unleash Tear Gas on Protesters
     * Ferguson Police Officer Shot, Two Suspects Wanted

   More from The Wire

Quartz

     * “Hands up, don’t shoot” comes to Hong Kong’s pro-democracy movement
     * Democracy activists’ plan to disrupt Hong Kong is starting to work
     * Why global commodity prices are crashing and what it means for
       India

   More from Quartz

National Journal

     * Political TV Ads Will Soon Reach Facebook-Level Creepiness
     * Ted Cruz Banks on Foreign Policy as His 2016 Differentiator
     * Democratic House Candidates Are Walloping Republicans in the
       Small-Money Game

   More from National Journal

Defense One

     * This Site Tracks the Guns Going Into Syria
     * Our Best Bet Against ISIL: Kurdish Crude
     * How American Precision Weapons Opened the Door to an Arab Coalition

   More from Defense One

Follow The Atlantic

     * App store
     * Google Play
     * Facebook
     * Twitter
     * Linkedin
     * Google Plus
     * Tumblr
     * RSS

E-Newsletters

     * Today's Top Stories
     * This Week
     * This Month
     * New at In Focus
     * CityLab
     * 5 Best Columns
     * Today's News

Information

     * FAQ
     * Subscribe Help
     * Masthead
     * Store
     * Emporium
     * Jobs
     * Privacy
     * Site Map
     * Terms and Conditions
     * Advertise
     * Advertising Guidelines
     * Press
     * Contact Us
     * Special Reports
     * Atlantic Scene
     * Books
     * Events
     * Atlantic Media

Subscribe

   [large.jpg?nc2mvq] Get 10 issues a year and save 65% off the cover
   price
   ______________________________
   ______________________________
   ______________________________
   ______________________________
   ______________________________
   [STATE]         __________
   ______________________________
   (Submit) Next ►

Fraud alert regarding The Atlantic
     __________________________________________________________________

   Copyright © 2014 by The Atlantic Monthly Group. All Rights Reserved.
   CDN powered by Edgecast Networks. Insights powered by Parsely .

   Powered by the Parse.ly Publisher Platform (P3).

   [img]
