   #RSS Feed

     * « Back to MakeSpace.com
     * or Get Started »

     * « Back to MakeSpace.com
     * or Get Started »
     * Menu

MakeSpace Blog - Your Closet in the Cloud

Posts

Tim O'Reilly Features MakeSpace At The 2014 Solid Conference

   June 5, 2014

   We’re honored that Tim O’Reilly featured MakeSpace as an example of a
   start-up that’s rethinking how real-world things work in his talk “The
   Internet of Things and Humans” at the 2014 Solid Conference. O'Reilly
   has also blogged about us. Here's a quote from the talk.

     Try to think about new things. Think about things that might have
     seemed hard or impossible before you had these new capabilities.
     Because one of the things I’m most excited about in this technology
     revolution is that it’s giving us amazing, amazing capabilities to
     affect the physical world. And the physical world, in the end, is
     where we all live, and where the biggest problems we face as a
     society are to be found. We have to feed the world, we have to
     generate energy, we have to deal with climate change, and we have to
     fix the problems of our society. I want you not just to make cute,
     cool consumer devices but to think about hard problems that you can
     solve, take this technology and make the world a better place.

   In MakeSpace News Tags The Internet, Internet of Things and Humans,
   Solid Conference, Tim O'Reilly, MakeSpace, Technology, Tech, Startups,
   Digital Future, Real World, Problem Solving, Investor, Investing, Apps,
   Innovation
   ← Tiny Apartment News And Design RoundupSeems Insane! New Yorkers
   Resort To Sleeping Their Babies In Bathrooms And Closets →

Schedule your Free Pickup »

Learn more about MakeSpace »

FOLLOW US ON SOCIAL MEDIA!


   pinterest.png pinterest.png
   instagram instagram
   twitter twitter
   facebook facebook
     __________________________________________________________________
