   #interfluidity RSS Feed interfluidity » “Incentives to produce” are
   incentives to rig the game Comments Feed Followup: Pro-family,
   pro-children, anti-”marriage promotion” VC for the people

[interfluidity_handwritten_small_black_bluish_halo4.gif]

   interfluidity
   Steve Randy Waldman

“Incentives to produce” are incentives to rig the game

   That’s obvious, right? But let’s belabor the point.

   All too often in discussions about the vast dispersion of circumstance
   we call “inequality”, people concede a kind of trade-off. Yes, reducing
   rewards to those at the top of the wealth/income distribution might
   blunt their incentives to produce. But the cost of that might be offset
   by utilitarian benefits of transfers to the less well off, or by
   greater prosperity engendered by MPC effects on aggregate demand, or by
   whatever.

   That’s all well and good as far as it goes. But at current margins, I
   suspect (with Paul Krugman) there is no tradeoff. There might be a
   tradeoff in measured GDP, but GDP happily tallies economic coercion and
   rent-capture along with genuinely productive activity. Suppose that a
   comic-book evil pharmaceutical company secretly unleashes a disfiguring
   virus for which — miracle of miracles! — it has an expensive, patented
   treatment. After the pandemic, consumers would have a choice: tolerate
   an odiferous oozing eczema (but remain otherwise healthy and
   productive!), or pay for the treatment. GDP would likely rise! In
   macroeconmic terms, this kind of thing is an example of the “broken
   window fallacy“. Causing a disease and then expensively treating it
   does not in fact make the world richer. But it may well inspire
   economic activity — the mass production of a new drug, visits to
   doctors, extra hours people choose to work in order to afford the
   treatment, etc. In aggregate, we work harder just to stay in place. But
   the distributional effects of the operation are very real. The extra
   personal income enjoyed by the conspirators spends nicely.

   In real life, it’s not so common for comic-book villains to release
   icky pathogens and then charge for a cure. But it is very common for
   doctors to restrict entry into their profession and to act politically
   to inflate the cost of their services. Goaded by “incentives to
   produce”, participants in the financial industry do a lot of
   “innovating” that amounts to finding ways of skimming invisible or
   unexpected fees from people or persuading them to bear underappreciated
   and undercompensated risks or maximizing the value to them (and costs
   to others) of guarantees implicitly or explicitly provided by the
   state. Nearly every industry hires lobbyists to carve out favorable
   loopholes and subsidies and regulatory schemes at everyone else’s
   expense. Tech firms make a business model of invasive surveillance and
   selling information about people who are their users but not their
   customers. Patent trolls send extortion letters to users and creators
   of new technology. Politicians “revolve” out of government into
   perfectly legal, extravagantly compensated sinecures in the private
   sector, and then often back into government. Senior members of the
   military become “private sector entrepreneurs”, garnering contracts
   from friends and former colleagues in a burgeoning defense and
   intelligence industry, often for work that used to be performed more
   cheaply internally. Executives collude with friendly boards who rely
   upon transparently idiotic consulting practices to extract huge
   salaries. Some of these things contribute to measured GDP, to “growth”,
   but their effect on the actual well-being of those outside their
   industries is, um, questionable.

   This stuff isn’t marginal, nor should we expect it to be. In fact, we
   should expect the prevalence of rent capture (or worse) as a source of
   economic profit to increase with technological progress. Why? Because,
   absent chicanery, technology increases the ease of production and the
   efficiency of distribution. As Schumpeter pointed out, the source of
   profit in real-life capitalism is the fact that monopoly power is
   ubiquitous because of natural barriers to competition. The corner store
   has a monopoly on the convenience of its neighbors, and so can capture
   some of the surplus that might otherwise be bid away to customers by
   competitors. On-demand delivery drones would eliminate that monopoly.
   Yet the corner store industry might lobby to prevent residential
   rooftop deliveries, in which case it is no longer exploiting a natural
   inefficiency but capturing a rent. In business school, students are
   taught that a successful business has a “moat” that makes it difficult
   for competitors to bid away ones margins. Technological progress
   renders moats that derive from nature harder to come by. Instead,
   successful businesses — and successful people (since under capitalism,
   a human is just a small business) — must rely increasingly on moats
   that result from social and political arrangements. We choose to grant
   monopoly rights to “creators” in the form of intellectual property and
   to expand their scope. We choose to limit the taxi business to
   medallion holders. We choose to prevent Indian doctors from competing
   in American hospitals, even though airplanes have eliminated locals’
   natural monopoly. We choose to hire from the Ivy League. The
   distribution of profits is determined by social choices rather than by
   natural scarcities.

   None of this is to say that any particular such choice is “wrong”. The
   static inefficiency inherent in patent monopolies at least under some
   circumstances may be overcome by the incentives to invent they yield.
   Minimum wage laws are restraints on competition that I enthusiastically
   support precisely because of to whom the “rents” are directed. Maybe
   sending a gigantic, very random fountain of money to producers of
   health-care inputs via an inscrutable hodge-podge of public and private
   payers really is the best way to ensure our cancers are cured before we
   are diagnosed with them. Who knows?

   But the distribution of affluence is less and less a matter of direct
   attachment to production, and more and more a function of winning
   social games and political contests that determine to whom the fruits
   of production will be allocated. There’s no conspiracy in that. Nor is
   it an answer to say “capital” now determines who enjoys wealth. As
   technology improves, capital goods become mere commodities like
   everything else. Financial capital, whatever it is, is not an input
   into any material production process. It is a construct and artifact of
   a huge and ever-changing array of social and legal institutions. “Human
   capital”, “social capital”, and “organizational capital” are things we
   impute ex-post to winners of distributional contests as an explanation
   of observed returns. They do not straightforwardly exist in the world.

   “Inequality” — high dispersion of outcome — creates a strong incentives
   to be on the side of winners. There are some circumstances where being
   on the side of winners means making an outsize contribution to economic
   production. There are other circumstances where winning means aligning
   oneself with coalitions capable of winning legal and political contests
   that may be orthogonal to, or much worse than orthogonal to, any
   contribution to production. The two strategies don’t preclude one
   another. Perhaps outsize rewards are shared between those who make
   unusual contributions to production and those who participate in
   politically potent guilds. But, at best, increased dispersion increases
   the incentive to engage in both sorts of behavior. Incentives to
   produce are also incentives to contest for rents. And at any given
   time, for any given person, one may be an easier or more reliable means
   of gaining outsize rewards than the other.

   Suppose, reasonably I think, that ceteris paribus humans prefer to “be
   good”. That is, we prefer to do work that is productive and engage in
   behavior that is ethical. Suppose, also reasonably, that a well ordered
   society depends upon people sometimes making choices opposed to their
   material interests on ethical or other grounds. Then it is obvious how
   inequality might be costly. Instead of talking about “incentives to”
   (produce, extract rents, whatever), we might describe outcome
   dispersion as a tax on refraining from mercenary behavior. If the
   difference between economic winners and losers is modest, people of
   ordinary virtue might refrain from participating in activities they
   consider corrupt, might even be willing to “blow the whistle”, because
   the cost of doing so is outweighed by their preference for behaving
   well. But as outcome dispersion grows, absenting oneself from or even
   opposing activities that would be personally remunerative but socially
   undesirable becomes too costly. The required sacrifice eventually
   overcomes a ceteris paribus preference for virtue. Preventing the
   misbehavior of large coalitions is a collective action problem. An
   isolated malcontent or whistleblower is likely to be evicted from the
   coalition without meaningfully improving behavior, if others choose to
   “circle the wagon”. Outcome dispersion both increases the costs to
   individuals of engaging in pro-social behavior, and diminishes the
   likelihood that bearing those costs will be fruitful, since others will
   have strong incentives not to follow.

   Wouldn’t it be odd to live in a country where, say, bankers
   individually acknowledge that their industry often behaves
   destructively, where insiders perceptively describe the conditions that
   create incentives for people to take bad risks or fleece “muppets“, but
   continue to work in those places and do nothing about it? Wouldn’t it
   be odd to live in a country where doctors privately apologize for the
   way their services are “priced“, but nevertheless take home their
   paychecks and pay AMA dues? Or in a country where economics instructors
   teach agency costs with case study of textbook pricing, during a course
   for which students were required to purchase a $180 textbook?

   I don’t mean to criticize anyone in particular. (I used to be the
   economics instructor.) In all of these cases, there really isn’t
   anything any one individual can do to remedy the bad practices. Making
   a big issue of them would lead to useless excommunication. Instead we
   shrug ironically. In our society, an ironic attitude is a token of
   sophistication (a telling word, which once meant corruption but now
   implies competence). An ironic attitude towards collective ethics is
   adaptive. It helps basically decent individuals participate in
   coalitions that ruthlessly contend for rents. But perhaps we’d have a
   better society if, rather than turning our ethical discomfort into an
   object of aesthetic consideration, lots of us worked straightforwardly
   to remedy it. And perhaps more of us would do so if the risk of losing
   our place were not so terrible. Ethical behavior is endogenous.
   “Inequality” renders it costly.

   Update History:
     * 29-Mar-2014, 6:00 p.m. PDT: Struck near duplicate: “…treatment,
       etc. [DEL: GDP rises! :DEL] In aggregate…”; “hodge-podge of public
       and private [DEL: institutions :DEL] payers“

   This entry was posted on Friday, March 28th, 2014 at 7:38 am PDT.
   You can follow any responses to this entry through the RSS 2.0 feed.
   Both comments and pings are currently closed.
   « Followup: Pro-family, pro-children, anti-”marriage promotion”
   VC for the people »


31 Responses to ““Incentives to produce” are incentives to rig the game”

    1. Becky Hargrove writes:
       “…reducing rewards to those at the top of the wealth/income
       distribution might blunt their incentives to produce.”
       It helps to place this in a framework of what they are producing.
       Are they working with random resources which might not gain further
       production without additional societal incentive? Or have they
       gained supremacy within finite resource structure such as our
       extremely limited time use. True, it’s hard to think of aggregate
       time this way when so much valuable time potential today is simply
       wasted or otherwise lost, but consider. There are people in this
       world who are much, much smarter then me. Hence, their time value
       is appropriated in ways that I can’t rely on the use of my own
       time, to compensate them for product which may in fact be necessary
       for my survival.
       That in turn makes me not only “irresponsible”, but I become an
       element which could further weaken my community. Here’s the
       problem. The valuable doctor makes a convincing moral argument for
       his time value. But he has already taken advantage of many random
       resource quantities in the economy, to fill the holes of lost value
       that he has created in others by his superior value. See, the good
       doctor also negated the time value (in aggregate) of many people
       such as myself, who as a result over time become “irresponsible”
       and further weaken their community.
       This is why I ask for the right to use time as an portal of equal
       entry for knowledge use, so that we can all assist one another
       instead of having to stand in line for the doctor. Time use is the
       only chance at equality that any of us have. No, we’re not all
       equally smart or talented. But there is no way to bring balance
       back to society if we are not all allowed to use our time equally
       to help one another.

       March 28th, 2014 at 11:35 am PDT
                                       link
    2. Steve Roth writes:
       Just picking out one (tangential or cruxial?) bit from all the good
       stuff here:
       “Financial capital, whatever it is, is not an input into any
       material production process.”
       Thank you very much for that. Piketty has me thinking very hard
       about this again. Real + financial capital = total capital. But
       hey: financial “capital” is claims, at some remove(s), on real
       capital. ?? The Homogeneous Lump of Capital fallacy?
       He addresses this only is one passing paragraph in the context of
       “public” capital on p. 124, far removed from his definition of
       capital on p. 46.
       Would love to see SRW’s mind brought to bear on that “whatever it
       is” question…

       March 28th, 2014 at 11:53 am PDT
                                       link
    3. Bob Stevens writes:
       Thank you for this brilliant post.

       March 28th, 2014 at 1:00 pm PDT
                                      link
    4. Kuas writes:
       Nice. Best thing I’ve read all week.

       March 28th, 2014 at 1:14 pm PDT
                                      link
    5. Bryan Willman writes:
       I think you misunderstand the game.
       Money is a claim on the traded part of the economy, and has meaning
       only as a claim on other people. It is the most formal of a variety
       of mechanisms that assign physical well being to people. If you
       think that money is the only mechanism, or that redistributing it
       will somehow even out the real status or real outcomes of citizen’s
       lives, your thinking is too narrow. Government may well change the
       distribution of “outcomes”, but what it mostly does it change which
       group of people manipulate which set of rules to hold the most
       status.
       And finally, in your world in which bankers admit they are not
       special and doctors admit that pricing is bizarre, will taxi
       drivers admit they are not special? Will politicians their
       fundamentally manipulative nature? Will voters suddenly see the
       error of voting always for low taxes and high spending on
       themselves? Will citizens suddenly decide that the vast collection
       of structures that keep the US very unequal with the rest of the
       world, imposing a variety of rents on the entire world, are at
       least morally questionable?
       Then that is also a fantasy land where pigs fly.

       March 28th, 2014 at 9:20 pm PDT
                                      link
    6. stone writes:
       Steve Roth @2, I’m totally with you on your “Homogeneous Lump of
       Capital fallacy” idea.
       I’ve wondered whether an analogy can be drawn between financial
       capital and the pheromones that bees or ants use to organize their
       colonies. An insect colony collapses if the insects lack pheromones
       and likewise we need financial capital to organize human society at
       a scale larger than a small tribe. Financial capital can be created
       with the stroke of a pen (or a scratch on a tally stick) -it is a
       purely social construct. If we screw up our system of financial
       capital then human talents, machines and natural resources will not
       provide what they otherwise could. A nation of people teleported
       with no possessions to an uninhabited planet could draw up
       financial capital to help direct each other to create a new
       civilization from scratch. After WWII the new Deutsche Marks
       initially were just handed out to every German along with ration
       cards -every person got 60DM and the economy got its “financial
       capital”. Financial capital both allows people to direct each other
       to provide what everyone wants but also potentially empowers people
       to cause other people to sit idle on the sidelines even when they
       have the will and capability to contribute or to force people to
       slave away doing pointless “bullshit jobs”. It is all about
       distribution -if it is all commanded by a handful of people then
       perhaps that is like political power being commanded by a handful
       -most people’s needs and wants will be overlooked. I think the most
       tragic failing of financial capital comes from the fact that it can
       be “stored” even though it is basically a claim over human and
       machine time and time of course can not be “stored”. If a bee
       managed to store up pheromones as a way to claim more honey once
       the flowers were over and lots of the bees did that rather than
       storing honey -then they would really be more like us.

       March 29th, 2014 at 6:36 am PDT
                                      link
    7. Noni Mausa writes:
       Bryan said: “Money is a claim on the traded part of the economy,
       and has meaning only as a claim on other people. It is the most
       formal of a variety of mechanisms that assign physical well being
       to people…”
       Yes. To take it further, money is one of the mechanisms for
       mobilizing and directing human time, effort and attention. That
       power to mobilize and direct others is the source, the only source,
       of wealth.
       Money is a nice, anonymous way of doing this, preventing some of
       the bad side effects of other methods like overt slavery, war and
       conquest, totalitarian rule, and so on. The possession of big piles
       of money looks neutral, whereas other methods of using other people
       for your own benefit are unmistakable. But the “sharp end of the
       stick” is still there, it is merely distanced and made less
       immediate.
       Another result of a very unequal society is that violence of the
       guard professions (police, security guards, and so on) will become
       more intense and less rational as the gradient they patrol becomes
       steeper. Thus, even though crime rates in the US have fallen
       steadily for decades, prisons have proliferated and encounters with
       police by innocent people can increasingly lead to injury or death.
       Noni
       http://tea-analysis.blogspot.ca trying to analyze economics purely
       in terms of human time, energy and attention. As economists say,
       “It’s complex.”

       March 29th, 2014 at 7:03 am PDT
                                      link
    8. Noni Mausa writes:
       PS of course, it follows that if money is a lever to direct the
       efforts of others, than a steeply unequal society will consist of a
       majority of people whose seed stock of personal energy is not even
       available to themselves. Rather, it is directed via a system that
       values or devalues them and their personal preferences and holds
       their lives and their families as impersonal hostages.
       No wonder we see outbursts of aggression and self-harm in such a
       society, and no wonder those outbursts seem senseless. Putting a
       finger on the exact clump of mud that’s pulling you down when
       you’re in a patch of quicksand isn’t possible, so flailing about is
       one sensible, though fruitless, response.
       Noni

       March 29th, 2014 at 7:16 am PDT
                                      link
    9. stone writes:
       SRW, you say “In fact, we should expect the prevalence of rent
       capture (or worse) as a source of economic profit to increase with
       technological progress.”
       -Is it possible that “rent capture (or worse)” increases not so
       much directly with technological progress but rather with
       accumulation of financial capital? If financial capital becomes an
       ever greater multiple of everything real there is to buy, then
       perhaps that induces more of the chicanery you describe? If our
       financial system were set up in such a way that what made sense
       financially aligned with what would make sense if money were
       ignored, then we would have a good system -if it doesn’t, then we
       get chicanery. Accumulation of financial capital has entailed the
       financial system constructing a financial system designed for the
       self interest of the financial system. That’s what makes it
       dysfunctional.

       March 29th, 2014 at 7:52 am PDT
                                      link
   10. stone writes:
       Perhaps part of the political impetus towards facilitating rent
       capture is due to competition between nations. If the USA say
       didn’t have massive rent capture in the US health care system, then
       perhaps health care providers would be less of a draw for capital
       inflows from sovereign wealth funds and the like. So having a
       seemingly awful system means that the Abu Dhabi and Norwegian
       sovereign wealth funds buy shares in US health care provider
       companies and so it is the USA that gets the currency strength to
       buy stuff that most of the rest of the world can’t afford. Likewise
       in the UK with our rent extracting utility companies and banks.
       Perhaps that’s partly why we seem to get a better economy
       (nationally but not globally) when its run to ensure that business
       can “make money” rather than merely provide real goods and services
       efficiently.

       March 29th, 2014 at 8:58 am PDT
                                      link
   11. Lawrence D'Anna writes:
       And yet, life has never been better than it is now. Humanity has
       never been better than it is now.
       Maybe tech has tech has made rent seeking rise in importance
       relative to real production in determining the distribution of
       rewards. But the total size of those rewards has been growing
       exponentially for centuries. Exponentially. For centuries. Is a
       15th century farmer less dependent on coalition politics for his
       livelihood than we are today? If you measure the rewards in
       dollars, maybe he is, after you average in billionaires. If you
       measure the rewards in life, happiness, and log-dollars, there’s no
       question. He’s way more reliant on politics than us.
       I’m not saying you’re wrong, I’m saying, “cheer up”.
       PS: If you want to talk about distributional justice, you should
       talk about Open Borders. The borders issue is a whale, and the
       stuff you’re talking about is plankton.

       March 29th, 2014 at 1:53 pm PDT
                                      link
   12. Charlie Baker writes:
       To Stone:
       I think you’ve identified the key element in the whole process in
       Waldman’s excellent discussion:
       “Financial capital, whatever it is, is not an input into any
       material production process.”
       Yet the rise of financialization in the last 40 years has been the
       catalyst of the rent seeking and international arbitrage. I keep
       returning to Minsky’s financial instability hypothesis, and
       wondering how that analysis could gain traction in our current
       environment. I think it was the post-war stability that lured
       policymakers to let Big Finance out of the constraints imposed as a
       result of the Great Depression. Due to the failure of policymakers
       to truly reimpose (or redesign) a constraint on finance in response
       to the Great Recession, it is as Waldman put it: “there really
       isn’t anything any one individual can do to remedy the bad
       practices.” Moreover, I’d also offer that the power of Big Finance
       has overwhelmed any attempt on the part of any popular or elite set
       of factions to constrain it.
       As to “what to do about it,” I’m at a loss to describe a set of
       actions, other than to further analyze the current dysfunctional
       market system, and seek a point around which to gather a populist
       effort. I think inequality might be such an issue, but at present I
       still see a set of abstractions on one side versus the realities of
       individual survival in our current economic environment.

       March 29th, 2014 at 3:25 pm PDT
                                      link
   13. multiplayer app android writes:
       Hmm it appears like your website ate my first comment (it was
       extremely long) so I guess
       I’ll just sum it up what I submitted and say, I’m thoroughly
       enjoying your blog.
       I as well am an aspiring blog blogger but I’m still new to
       everything. Do you have any points for novice blog writers?
       I’d really appreciate it.

       March 29th, 2014 at 3:57 pm PDT
                                      link
   14. stone writes:
       Lawrence D’Anna, I don’t think there is much room for complacency.
       Apparently more people starved in 2009 than ever before:
       http://www.fao.org/news/story/en/item/20568/icode/
       Like you, I’d also love to hear Steve’s view on Open Borders.
       Personally I think it is a deeply misguided idea. As things stand,
       I fear it would make poor countries poorer and further undermine
       the bargaining power of workers versus owners. To my mind if rich
       countries weren’t trying so hard to increase inequality between
       countries, then there would not be hoards of people needing to
       migrate to get a decent living. The current closed borders are a
       symptom of the purposefully imposed gross inequality between
       countries. eg:
       http://library.uniteddiversity.coop/Money_and_Economics/confessions
       _of_an_economic_hitman.pdf
       I’ve had a go posting my doubts about the Open Borders idea
       http://directeconomicdemocracy.wordpress.com/2013/08/02/more-on-ope
       n-borders/

       March 29th, 2014 at 4:33 pm PDT
                                      link
   15. stone writes:
       Charlie Baker @12, The drum I’m always beating when it comes to
       “what to do about it”, is to replace current taxes with a tax on
       gross assets. Then financial capital would only get concocted to
       the extent that it actually helped to serve the real economy. To my
       mind such a tax change would also align financial incentives with
       the underlying reality that every unused hour of machine or human
       time is permanently lost -financial power would need to be
       constantly put to productive use in order to pay such a tax.

       March 29th, 2014 at 4:42 pm PDT
                                      link
   16. Sanscelerien writes:
       The formating of the text renders it absolutely illegible.
       The text would deserve a better presentation.

       March 29th, 2014 at 6:02 pm PDT
                                      link
   17. Lawrence D'Anna writes:
       Stone: population has also been growing exponentially, though at a
       slower rate than production. More people did X in recent years than
       ever before for almost any value of X.
       As for open borders being “deeply misguided”, you could not be more
       wrong. Rich countries are not trying to keep poor countries poor.
       That is a ridiculous, paranoid conspiracy theory. They are trying,
       halfheartedly and ineffectually, to help them to develop. The
       biggest issue of distributional justice today is the fact that
       billions of people are stuck, imprisoned in dysfunctional countries
       that make it impossible for them to reach their economic potential.

       March 29th, 2014 at 11:31 pm PDT
                                       link
   18. JW Mason writes:
       Have you seen this?
       http://papers.ssrn.com/sol3/papers.cfm?abstract_id=662242
       Makes very similar points, but at the level of the firm rather than
       the economy as a whole.

       March 29th, 2014 at 11:59 pm PDT
                                       link
   19. JW Mason writes:
       Piketty has me thinking very hard about this again. Real +
       financial capital = total capital. But hey: financial “capital” is
       claims, at some remove(s), on real capital. ?? The Homogeneous Lump
       of Capital fallacy?
       Yes, I think this is the big flaw in Piketty’s argument.

       March 30th, 2014 at 12:01 am PDT
                                       link
   20. Richard Treitel writes:
       Part of the problem is that lobbying has such high returns. Charlie
       Keating spent $1.3M on senators and ripped the taxpayer off for
       roughly 2,000 times that sum. So here’s a wild idea: make it
       perfectly legal to buy votes … from the voters, retail. Anybody who
       wanted to raid the treasury would have to pay for that privilege,
       and in a competitive market they would have to pay through the
       nose.
       Oh, wait, that has been tried. In Venezuela.
       Still and all, my heart says that if political and financial power
       are going to be interchangeable, neither should be attainable
       without the people having their say. Reminds me of the reason why
       (most) churches are glad to be insulated from the government …
       these days. Yup, there was a time when kings held their thrones by
       divine right. Until 1649, to be precise.

       March 30th, 2014 at 12:05 am PDT
                                       link
   21. Thornton Hall writes:
       Right on. One point captures a thought I’ve had about slavery. We
       sometimes say, you have to judge a man–James Madison, say–based on
       the morality of his time. What we really should do is imagine that
       morality is unchanged and that, like ourselves, James Madison was a
       good person. Now, what would it take for a good person like you or
       I to own slaves and to not free them in our will? And to think
       about what it would cost: our livelihood, and the well being of our
       widow. And to understand that faced with that choice, the cost will
       be too much, and the good person will do the wrong thing.

       March 30th, 2014 at 12:51 am PDT
                                       link
   22. stone writes:
       Lawrence D’Anna @17 “Rich countries are not trying to keep poor
       countries poor.”
       The primary aim may not be to keep poor countries poor but rather
       to ensure that we maintain our advantage. Nevertheless that boils
       down to the same thing. Rich countries put up trade barriers and
       subsidies to ensure that domestic agriculture is supported. That
       has the primary aim of supporting rents and values for farm land
       BUT the consequence is impoverishing poor countries. Rich countries
       do everything they can to entice capital flight from poor countries
       to financial centers in rich countries. That has the primary aim of
       giving us strong currencies so that we are the ones that can afford
       the oil BUT the consequence is to devastate the economies of poor
       countries. Supporting leaders of poor countries who take on debts
       denominated in USD is the most insidious tactic of all. Poor
       countries (just like any other countries) can only prosper if they
       only borrow in their own currency. The cycle of USD denominated
       debt and austerity guts the economies of poor countries. It ensures
       that real commodities flow from poor countries to the developed
       world and nothing but electronic account statements flows in the
       other direction.

       March 30th, 2014 at 2:54 am PDT
                                      link
   23. Links 3/30/14 | naked capitalism writes:
       […] “Incentives to produce” are incentives to rig the game
       Interfluidity […]

       March 30th, 2014 at 6:56 am PDT
                                      link
   24. Donald Pretari writes:
       http://www.corporatecrimereporter.com/realityignored04022011.htm
       “The Chicago School began with the view that in order to have a
       properly functioning free market, the government must drastically
       curtail the ability of businesses to build and maintain
       concentrated economic power,” writes Kenneth Davidson in his new
       book Reality Ignored: How Milton Friedman and Chicago Economics
       Undermined American Institutions and Endangered the Global Economy
       (2011). “Early incarnations advocated forbidding corporations to
       retain their earnings or to purchase other businesses. The explicit
       fear was that the disproportionate power of big businesses would
       distort commercial markets and corrupt political freedoms.”
       That sounds more like Ralph Nader than the Chicago School.
       “It was Henry Simons and Aaron Director,” Davidson told Corporate
       Crime Reporter in an interview last night.”
       Henry Simons owns the field of Limited Government and Equality.
       Hawtrey and Coase call him Utopian, while Michael Oakeshott and
       Herb Stein have much more positive printed views of him. It is not
       that he is Utopian, but the fact that he is not a lackey to the
       Fooling Class, who will still be wealthy under his proposals, but
       not illiberally so, that he is called Utopian. I like Hawtrey and
       Coase, but they need to step outside and smell the stench ( I know
       Hawtrey is dead, thanks. ).

       March 30th, 2014 at 11:53 am PDT
                                       link
   25. Charles Monneron writes:
       Brilliant post, as usual.
       I would have three remarks :
       1) It is much easier to go for the “ethical” path when one has not
       yet accumulated liabilities (financial or societal) that deeply
       constrain choices. It is at that time than the “fear of loosing
       one’s place” is at its lowest. This window of opportunity should be
       located at the end of formal studies, but is progressively shrunk
       to nothing thanks to student loans (for young doctors, certainly a
       bigger issue than AMA checks), unaffordable housing and ever
       increasing unfunded liabilities at the sovereign level . At
       forty-something like the author of this blog, and, I guess, most of
       its readers, it is a bit too late…
       2) If, as I believe, more ethical behavior flows from lower
       liabilities, or liabilities that are easier to default from (such
       as equity financing), the main solution of the problem you describe
       in this post is deleveraging. Yes, GDP will come down as a result,
       but as you mention, most of the GDP that would disappear is of the
       “broken window” sort.
       3) It is interesting that you think that a 180$ textbook is
       overpriced, considering that a good textbook gives 80 to 100% of
       the useful knowledge one acquires in University until graduation
       (and indeed MOOC can be viewed as fancy interactive textbooks).
       What is really overpriced is the accreditation process, usually
       combined with forced selling of hosteling and catering business !

       March 30th, 2014 at 11:28 pm PDT
                                       link
   26. vlade writes:
       Steve,
       A nice post, few remarks:
       I disagree with your “humans prefer to be good”. That’s a wishful
       thinking on part of the humans. I’d say “most humans want to see
       themselves as good”. Now it gets interesting, because “to see
       yourself as good” very much depends on the background of the scene,
       unlike “to be good”, which is much less context sensitive. Hence
       people in Nazi Germany could see themeselves as good and yet do
       things which we now don’t understand. Human mind is first and
       foremost concerned with its survival, which most often things
       getting on with whatever society they are part of (that doesn’t
       mean there are no exceptions, but they are exceptions). If humans
       do have one infinitely large capability, it’s the capability to
       rationalise their past decisions.
       A second remark on the “production”. Humans (and not just them)
       follow the path of least resistance and effort. It’s much more
       effort to spend your life inventing a new thing that most likely
       will fail than to spend your time lobbying for a legal, meta
       advantage (even more so if you lobby smart, so if someone else does
       succeed with their invetion you still manage to get the most of the
       gains). Our laws are only as good as the people who enforce them,
       and as a result, changing that to get an advantage will be always
       easier than doing anything else. Incidentally, this also has its
       “Minsky” moment, i.e. we actually manage to enforce the laws
       efficiently for a while (for whatever reason), which weakens our
       alertness and ability to do so in the future until we get another
       critis, which again will make us more alert and hopefully efficient
       (if we survive).

       March 31st, 2014 at 5:37 am PDT
                                      link
   27. Mercury writes:
       “But the distribution of affluence is less and less a matter of
       direct attachment to production, and more and more a function of
       winning social games and political contests that determine to whom
       the fruits of production will be allocated.”
       ————————————————————–
       Is that a light bulb I see? Because in other words, the larger and
       more powerful government becomes (despite “common-good” intentions)
       the less rewards are determined by anything related to
       productivity, merit or market forces.
       By the way, doctors generally don’t set prices for their services,
       the government sets the pace with Medicare and insurance companies
       base off of that. It is illegal to undercut Medicare.
       It’s OK –and good- for an individual to look up and criticize (at
       least that’s what all the smart-set bumper stickers said when Bush
       was president) and there’s no shame in being an infidel in respect
       to the Church of Crony. One good habit to adopt might be to refrain
       from reflexively agreeing that the answer to every problem is even
       more government. Another might be to do what you can to discourage
       the next generation from discarding their souls and the better
       aspects of their human nature in favor of ironic sensibilities:
       “He had some measure of the infuriating trait that causes a young
       man to be a nonconformist for its own sake and found that the
       surest way to shock most people, in those days, was to believe that
       some kinds of behavior were bad and others good, and that it was
       reasonable to live one’s life accordingly.”
       ― Neal Stephenson, The Diamond Age

       March 31st, 2014 at 10:32 am PDT
                                       link
   28. reason writes:
       Wow!
       I love this post. I never really thought about it, but you are
       right, Mafias arise in very unequal societies. Where winning is
       everything, it crowds out playing the game.
       But there is another side of this – what does being “very
       productive” actually mean in a very unequal society. Doesn’t it
       just mean producing extraordinary entertainment for the sated and
       ignoring the unpaying needs of the masses?

       April 1st, 2014 at 5:13 pm PDT
                                     link
   29. lotuseater writes:
       For the past 6 years I have worked in aspirational retail, aka fine
       wine. Most definitely the rich are being subsidized by the young,
       poor, badly organized and socially mal-adjusted. This is proven by
       how credit and debit cards are processed. At a minimum a retailer
       must account for the average processing charge administered by a
       few giant payment networks. Online is controlled by Authorize.net
       and the world of swiped cards is dominated by Chase Paymentech and
       Wells Fargo. These networks (with ineffectual federal regulation)
       charge a dizzying number of ‘rates’ dependent on the type of card
       used, and to a much lesser extent the amount of the transaction.
       So, a Visa Signature Business Card takes a higher percentage of a
       sale than a standard Visa credit card or Visa debit card (ok, I’m
       over simplifying but there are more than 50 different ‘rates’). The
       better your credit, the more rewards your card gives you. The worse
       your credit, the less rewards your card gives you. All those miles
       or 1.5% cash rebates Alec Baldwin and Samuel Jackson promise you on
       TV are being paid for by the poor. So much for Hollywood
       progressives.

       April 7th, 2014 at 2:38 pm PDT
                                     link
   30. david writes:
       Financial capital derives its value via maturity transformation
       (i.e., recombination of real, physical capital that has different
       maturities and risk) – it is the additional value created by
       ‘deepening’ the real capital with such abstractions.
       Of course SRW has already written on the social need for false
       confidence in this transformation, etc.

       April 8th, 2014 at 8:06 pm PDT
                                     link
   31. Thornton Hall writes:
       Fresh from reading an article in HBR from June 2013 called
       “Transient Advantage” by Columbia Prof Rita Gunther McGrath. I
       wonder if her business school thinking has insights for Econ, I
       came back to this post.
       She argues that “moats” are a thing of the past in most industries,
       like you do. She suggests that the answer is a series of transient
       advantages that are short lived but profitable instead of one big
       moat. The hurdle is basically two fold: the inertia of large
       successful enterprises and the fact that the creative people who
       develop new advantages are not the same set of people who run
       “mature” companies.
       Is there a dynamic where the less creative people see rent seeking
       as the only option for continued profits where a more nimble
       organization which hasn’t alienated all the start-up/ramp-up
       employees is able to see and develop other more productive
       advantages?

       April 9th, 2014 at 12:37 pm PDT
                                      link

   « Followup: Pro-family, pro-children, anti-”marriage promotion”
   VC for the people »
     * interfluidity
     * Steve Randy Waldman
     * subscribe
     * twitter | rss
     * archives
          + September 2014
          + July 2014
          + June 2014
          + May 2014
          + April 2014
          + March 2014
          + January 2014
          + December 2013
          + November 2013
          + October 2013
          + September 2013
          + August 2013
          + June 2013
          + April 2013
          + March 2013
          + February 2013
          + January 2013
          + November 2012
          + October 2012
          + September 2012
          + July 2012
          + June 2012
          + April 2012
          + March 2012
          + February 2012
          + January 2012
          + December 2011
          + November 2011
          + October 2011
          + September 2011
          + August 2011
          + July 2011
          + June 2011
          + May 2011
          + April 2011
          + March 2011
          + February 2011
          + January 2011
          + December 2010
          + November 2010
          + October 2010
          + September 2010
          + August 2010
          + July 2010
          + June 2010
          + May 2010
          + April 2010
          + March 2010
          + February 2010
          + January 2010
          + December 2009
          + November 2009
          + October 2009
          + September 2009
          + August 2009
          + May 2009
          + April 2009
          + March 2009
          + February 2009
          + January 2009
          + December 2008
          + November 2008
          + October 2008
          + September 2008
          + August 2008
          + July 2008
          + June 2008
          + May 2008
          + April 2008
          + March 2008
          + February 2008
          + January 2008
          + December 2007
          + November 2007
          + September 2007
          + July 2007
          + June 2007
          + May 2007
          + April 2007
          + March 2007
          + January 2007
          + December 2006
          + November 2006
          + October 2006
          + September 2006
          + July 2006
          + June 2006
          + May 2006
          + April 2006
          + March 2006
          + earliest posts
     * categories
          + uncategorized
     * Search

     * ______________
