KICKSTARTER

     * Discover
     *
     * Start

     *
     * Log in
     * Sign up

   ____________________

   ____________________ Go

Explore

     * an inspiring
     * a colorful
     * a superhuman
     * an innovative
     * a homespun
     * an incredible
     * an extraordinary
     * a thrilling
     * an awesome
     * an amazing
     * an eclectic
     * a surprising
     * a loud
     * an eccentric
     * a curious
     * a novel
     * an outrageous
     * a brand-new

   creative universe

   15 diverse categories. Thousands of amazing projects.
   451 live projects
   Art
   150 live projects
   Comics
   221 live projects
   Crafts
   64 live projects
   Dance
   518 live projects
   Design
   412 live projects
   Fashion
   846 live projects
   Film & Video
   665 live projects
   Food
   520 live projects
   Games
   113 live projects
   Journalism
   739 live projects
   Music
   232 live projects
   Photography
   733 live projects
   Publishing
   745 live projects
   Technology
   130 live projects
   Theater
   Photo full
   Project of the day on September 20, 2014

Nahanni Reforestation

   by Nahanni Arntzen

   A book of my dad's photographs from 1977-87 while he was a treeplanting
   contractor on the west coast and in northern British Columbia.
     * 90% funded
     * $18,022 pledged
     * 277 backers
     * Funded
     *

   Photo full
   Project of the day on September 21, 2014

Midwestern Knits

   by Allyson Dykhuizen and Carina Spencer

   Midwestern Knits is a knitting pattern collection inspired by the rich
   history and culture of the American Midwest.
     * 108% funded
     * $10,835 pledged
     * 300 backers
     * Funded
       Sep 24, 2014
     *

   Photo full
   Project of the day on September 22, 2014

The Writing On The Wall

   by Roger Perry

   The original book of London graffiti. Out of print since 1976, now
   reissued and expanded, with new text and unseen photographs.
     * 145% funded
     * £9,432 pledged
     * 235 backers
     * Funded
     *

   Photo full
   Project of the day on September 23, 2014

Wondermark’s Jigsaw Puzzles of Fictional Victorian Charts

   by David Malki !

   What if the Victorian era had more jokes AND was more diagram-based AND
   was made of jigsaw puzzles?? WONDER...NO MORE
     * 124% funded
     * $14,294 pledged
     * 318 backers
     * Funded
     *

   Photo full
   Project of the day on September 24, 2014

The Manual, Everywhere

   by Andy McMillan

   The Manual is a design journal for the web. We want to create a
   sustainable publishing model built on generosity—and we need your help.
     * 37% funded
     * £15,103 pledged
     * 289 backers
     * Funded
     *

   Photo full
   Project of the day on September 25, 2014

Thongdrol: Liberation Through Seeing - The Feature Film

   by David Cherniack

   A visually stunning, feature length, theatrical documentary on the
   magical Tibetan sacred art form that was developed by the Karmapas.
     * 100% funded
     * $37,143 pledged
     * 181 backers
     * Funded
       Sep 26, 2014
     *

   Photo full
   Project of the day on September 26, 2014

The Mortons Gap Muffler Man Restoration Project

   by Joel Baker

   This fiberglass Muffler Man statue in rural Kentucky can use your help.
   Donations will help us restore this roadside attraction.
     * 119% funded
     * $1,875 pledged
     * 54 backers
     * Funded
     *

   Photo full
   Project of the day on September 27, 2014

Free For All: Inside the Public Library

   by Dawn Logsdon & Lucie Faulknor

   Help us make our film about America's amazing public libraries and the
   urgent need to keep them open, innovating, and free for all.
     * 22% funded
     * $16,546 pledged
     * 209 backers
     * Funded
     *

   Photo full
   Project of the day on September 28, 2014

Imperial Proper Coffee Drip

   by Bill Abbe

   The perfect brewing drip that extracts the most body and essence out of
   the coffee bean. Finely tune your own custom brew and flavor!
     * 80% funded
     * $8,051 pledged
     * 39 backers
     * Funded
     *

   Photo full
   Project of the day

Build a Better Printshop

   by La Cucaracha Press

   La Cucaracha Press has started their biggest project ever! They're
   building a new shop with a renewed focus on community.
     * 35% funded
     * $7,048 pledged
     * 80 backers
     * Funded
     *

What’s popular

   See more
   Project image

URBANCE

   by Steambot

   Help us produce a kick-ass PILOT EPISODE and URBANCE complete
   Transmedia series will follow...
     * Montreal, Canada

   Successfully funded!
     * 39% funded
     * $74,844 pledged
     * Funded
     *

   Project image

Moth Theater Lives

   by Moth Artistic Director John Markland

   Help Moth Live! Support Moth and its artist collective to achieve its
   2014/15 season.
     * Hollywood, Los Angeles, CA

   Successfully funded!
     * 35% funded
     * $14,128 pledged
     * Funded
     *

   Project image

Fall of Gods

   by MOOD

   A fully illustrated book about the warrior Vali and his adventures. A
   tale that brings the Norse mythology to life.
     * Copenhagen, Denmark

   Successfully funded!
     * 32% funded
     * $13,028 pledged
     * Funded
     *

New & Noteworthy

   See more
   Project image

Dillos Vegan Snack Cakes - Growing And Expanding

   by Kaelene Colobella

   We need professional packaging to get our Dillos into more stores
   across the country, as well as bring to you our awesome Granny cookie
     * Salt Lake City, UT

   Successfully funded!
     * 6% funded
     * $771 pledged
     * Funded
     *

   Project image

Infinity Dance Arts- The BIG Move

   by Jennifer Solomon

   After 6 Years and 12,672 classes, Infinity Dance Arts has unexpectedly
   lost its space. We need your help to build our new home.
     * El Cajon, CA

   Successfully funded!
     * 10% funded
     * $1,015 pledged
     * Funded
     *

   Project image

Nancy Drew Board Game

   by Quincy MacShane

   I have designed this trivia board game to be a fun way for girls to
   learn about Nancy Drew. She is strong, confident, and smart.
     * Concord, MA

   Successfully funded!
     * 13% funded
     * $2,725 pledged
     * Funded
     *

   Tag libraries

In the Stacks

   These projects are bringing libraries into the 21st century.
   Explore Library projects
   Tag bikes

Pedal Powered

   Two wheels. Limitless possibilities.
   Explore Bike projects

Eureka! You've found
our little secret.

   Sign up for our Happening email for all the inside info about arts and
   culture in the Kickstarter universe and beyond.

   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   ____________________________________________________________
   Email address ____________________
   Submit

About us

     * What is Kickstarter?
     * 2013 highlights
     * Who we are
     * Jobs
     * Press
     * Stats
     * Projects we love

Help

     * FAQ
     * Our Rules
     * Creator Handbook
     * Trust & Safety
     * Support
     * Terms of Use
     * Privacy Policy

Discover

     * Art
     * Comics
     * Crafts
     * Dance
     * Design
     * Fashion
     * Film & Video
     * Food

     * Games
     * Journalism
     * Music
     * Photography
     * Publishing
     * Technology
     * Theater

Hello

     * Twitter
     * Facebook
     * Tumblr
     * Instagram
     * Vine
     * Kickstarter Blog
     * Engineering Blog

   KICKSTARTER

   © 2014 Kickstarter, Inc.

   Quantcast

   IFRAME: https://api.kickstarter.com/xdreceiver/4523.html
