   #Crooked Timber » Political Economy is Political Comments Feed The
   Ethics of Immigration Symposium: The Theory of Social Membership The
   Ethics of Immigration Symposium: Movement within and between states
   Crooked Timber RSS Feed

     * Home
     * Comments policy
     * Subscribe

Political Economy is Political

   by Henry on May 27, 2014

   The best explanation of the current Piketty-Financial Times brouhaha
   was written by Mike Konczal a few weeks before it actually happened.

     As Foucault argued, the ability of social science to know something
     is the ability to anthropologize it, a power to define it. As such,
     it becomes a problem to be solved, a question needing an answer,
     something to be put on a grid of intelligibility, and a domain of
     expertise that exerts power over what it studies. With Piketty’s
     Capital, this process is now being extended to the rich and the
     elite. Understanding how the elite become what they are, and how
     their wealth perpetuates itself, is now a hot topic of scientific
     inquiry.

     Many have tried to figure out why the rich are freaking out these
     days. Their wealth was saved from the financial panic, they are
     having a very excellent recovery, and they are poised to reap even
     greater gains going forward. Perhaps they are noticing that the
     dominant narratives about their role in society—avatars of success,
     job creators for the common good, innovators for social betterment,
     problem-solving philanthropists—are being replaced with a social
     science narrative in which they are a problem to be studied. They
     are still in control, but they are right to be worried.

   Political economy is political – a fact which many of its most
   prominent practitioners have ignored, or actively sought to bury.
   Although it appears technical, it starts from a set of political
   premisses. It radically emphasizes questions of (purported) economic
   efficiency, and discounts or actively deprecates questions of
   who-gets-what, even though theories that emphasize distribution have
   microfoundations that are quite as solid as the dominant mode of
   economic thinking. Furthermore, the dominance of these economic
   theories has had profound political consequences, as scholars as
   different as Jack Knight and Jim Johnson, Mark Blyth and Steve Teles
   have documented in various ways.

   The reason that Piketty’s book has gotten such a reaction – both from
   its advocates and its critics – is because it threatens to upset the
   current equilibrium in economic thinking. As Mike says, it threatens to
   open up new questions – questions which are profoundly and politically
   uncomfortable for dominant approaches in economic thinking. The result
   is that it isn’t only the rich that are freaking out. I would guess
   that one can explain the immediate reaction of 85% of economists and
   public writers to the book by looking to their priors on this question
   – whether they like to emphasize efficiency questions over
   distributional concerns, or vice versa (another 10% can be explained by
   whether the writer in question thinks that he/she and his/her mates do
   or don’t get sufficient citations and respect). People who might have
   found the book interesting had it been an academic exercise, and
   perhaps even agreed with large parts of it, are freaking out because
   they worry that it has serious implications for political debate. If
   people start debating whether capitalism is inherently rigged, so that
   those with a lot of capital will naturally do better than those who
   won’t, … well who knows where they might go next.

   To be clear – this doesn’t invalidate criticisms of Piketty’s book, any
   more than it means that his arguments are necessarily correct. Even if
   the actual reason why people are casting around for Devastating
   Critiques is because they don’t like the book’s political implications,
   they may actually find good criticisms, and uncover real mistakes.
   Motivated reasoning, if properly harnessed, can be epistemologically
   very valuable. That methodological critics of Piketty (and people
   insistently suggesting that there’s nothing very interesting to be
   learned from studying the distribution of wealth) nearly all clump
   together in one ideological camp, and people defending the methodology
   clump together in another, doesn’t mean that the dispute between the
   two isn’t useful. Argument about politically divisive topics is only
   disinterested in rare and isolated instances – yet it still can have
   great benefits. What it does mean is that the dispute, in the end, is a
   directly political one – over what constitutes the proper subject
   matter of economics and the other social sciences. Plausibly, it’s the
   people who are least willing to acknowledge the political aspects of
   the debate who are most completely captured by them. Practical
   economists, who believe themselves to be quite exempt from any
   political influences, are usually slaves of some defunct political
   philosopher.

Share this:

     *

       IFRAME:
       http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fcrookedt
       imber.org%2F2014%2F05%2F27%2Fpolitical-economy-is-political%2F&layo
       ut=button_count&show_faces=false&action=like&colorscheme=light&heig
       ht=21&locale=en_US&width=90

     *

       IFRAME:
       http://platform.twitter.com/widgets/tweet_button.html?url=http%3A%2
       F%2Fcrookedtimber.org%2F2014%2F05%2F27%2Fpolitical-economy-is-polit
       ical%2F&counturl=http%3A%2F%2Fcrookedtimber.org%2F2014%2F05%2F27%2F
       political-economy-is-political%2F&count=horizontal&text=Political%2
       0Economy%20is%20Political%3A

     *

   { 177 comments }

   1

          Shirley0401 05.27.14 at 3:13 pm

          “The reason that Piketty’s book has gotten such a reaction –
          both from its advocates and its critics – is because it
          threatens to upset the current equilibrium in economic thinking.
          As Mike says, it threatens to open up new questions – questions
          which are profoundly and politically uncomfortable for dominant
          approaches in economic thinking.”
          As a complete non-expert, this is what’s struck me about the
          attention Picketty’s been getting. (I think I “get” r > g,
          conceptually, but I have to tap out as soon as someone raises
          concerns about the models or math.) Suddenly, we have people
          with valid credentials suggesting that the underlying
          assumptions upon which we’ve built our economic systems are
          worth investigating. If people are willing to take seriously the
          possibilty that distribution matters as much, if not more, than
          efficiency — and that optimizing for efficiency won’t result in
          some sort of of golden mean — that means not only moving the
          goalposts, but maybe fundamentally changing how we keep score.
          Personally, I find myself incredibly interested in, and
          encouraged by, the conversation that’s being had. There seems to
          be a real possibility we’re moving towards mainstream acceptance
          of the idea that maybe we’ve developed our economic priorities
          around a less-than-optimal framework. It’s hardly surprising
          that there would be some pushback, especially from those whose
          reputations depend upon the validity of that possibly-faulty
          framework. (That the possibility it might also affect them on a
          personal level would influence their judgement is something
          else, and I’ll leave that to the Guardian to consider.)

   2

          Cade DeBois (@cadedebois) 05.27.14 at 3:28 pm

          “If people start debating whether capitalism is inherently
          rigged, so that those with a lot of capital will naturally do
          better than those who won’t, … well who knows where they might
          go next.”

          Systems of privilege rely on controlling the narrative, by
          making sure the more “creditable” voices are only those who
          benefit from that system while anyone hurt by the system is
          branded too biased or flawed to be listened to. If we allow
          those people who have been systematically dismissed and excluded
          from the discusssion–women, disabled people, POC, people who
          work in fields normally not blessed by a capitalist economy–by
          asking these kinds of questions–like, whether capitalism really
          perpetuate privilege, as opposed to assuming people who are
          economic “losers” have only themselves to blame (a common way of
          discrediting their voices)–then they lose control of the
          narrative, a narrative that has allowed them to justify the
          wrongs of the system. So yes, people be freaking out. They ought
          to be. This is how revolutions start.

   3

          Sandwichman 05.27.14 at 3:32 pm

          Frederic Harrison summed it up eloquently in 1872:

     Political economy professes to be a science based on observation.
     But the bitter pedantry which often usurps that name usually assumes
     its facts, after it has rounded off dogmas to suit its clients. In
     practice this magazine of untruth escapes detection for two reasons.
     One is that the facts relating to labour are invariably seen through
     the spectacles of capital. … The second reason which obscures the
     truth about industry is, that the facts about capital are almost
     never honestly disclosed.

   4

          William Berry 05.27.14 at 3:53 pm

          “Political economy is political”.

          Aphorism of the year, so far!

   5

          marcel 05.27.14 at 4:12 pm

          William Berry wrote:

          “Political economy is political”.

          Aphorism of the year, so far!

          And very economical too.

   6

          A H 05.27.14 at 4:19 pm

          The Giles critique of Piketty in the FT is really weak. Maybe
          Piketty committed some mistakes in collecting and preparing his
          data, but a far worse sin is to just take different raw data
          series and combine them together with no analysis or
          preparation, which is exactly what Giles does in his graphs that
          supposedly prove Piketty was wrong. I bet there were some
          interesting editorial discussion about how hard to push this.

   7

          Vladimir 05.27.14 at 4:25 pm

          It would be interesting to compare the reaction of the various
          pundits in regard to the discovery of errors in the work of
          Rienhart and Rogoff vs. Piketty. I’d put my money on one’s
          priors determining the reaction, with the role reversal that
          implies. On the issue of political economy being political:
          Branko Milanovic , who makes studying inequality his main area
          of research has written about an experience he had talking to
          someone from a well funded, well known think tank. The official
          told him that he could fund research about reducing poverty –
          wealthy donors do like to fund such things – inequality however
          was another matter. The rich don’t like to fund research that
          might delegitimize the basis of their wealth.

   8

          Rakesh Bhandari 05.27.14 at 4:43 pm

          I posted this reply to Konczal’s piece at Boston Review:

          This is an insightful review.
          I think there is an additional problem with Piketty’s measure of
          r. It is an aggregate measure of return across all types of
          capital or assets.
          But consider this piece by Justin Fox

          http://blogs.hbr.org/2010/11/the-real-story-behind-those-re/

          Here Fox shows that while the rate of profit and the mass of
          profits can appear to be at historical highs, the rate of return
          on domestic non-financial investments can still be low. Profits
          are being made on foreign operations and by financial firms. We
          have to disaggregate capital to see this. Piketty does not do
          this.

          But if the r not on capital in general but on domestic,
          non-financial or industrial investments is not high enough to
          motivate capital accumulation–and this seems to be the case in
          the US–we get not patrimonial capitalism in economic equilibrium
          but an economic crisis or secular stagnation that can only be
          resolved if capital can restructure industrial and labor
          relations to raise again not r in general but r on domestic
          industrial investments.

          There is simply no industrial class conflict in Piketty’s model,
          It’s of course in industrial class conflict to raise r through
          speed-ups and wage reductions that capital reveals itself not to
          be a quantifiable thing with a marginal physical product but as
          a class relation.

          Piketty himself admits that r was sufficiently low circa 1910 to
          have Germany and France fight for investment outlets in Morocco.
          He draws from Lenin! Wasn’t expecting that.

          Tthe risk adjusted rate of return on capital has been low as
          Tyler Cowen notes, and that profitability on even extant
          non-financial domestic industrial investments is low if Fox is
          right, to say nothing of anticipated profitability on marginal
          investments, which is really what matters. If that is low, then
          firms will use cash to buy back their own stock and merge and
          perhaps even speculate when they are not investing abroad.

          Piketty is so focused on r being relatively higher than g that
          he may neglects whether r is robust enough to sustain real
          capital accumulation; r can still be positive, and even greater
          than g, and still not robust enough to sustain real capital
          accumulation.

          A second big problem may be Piketty’s non-engagement with Branko
          Milanovic though Milanovic has reviewed the book favorably.
          Still Milanovic shows that the rise of inequality within nations
          has been dwarfed by the rise in inequality between nations since
          1850 and that therefore the most important form of capital that
          someone can inherit is not property but citizenship in a wealthy
          country. Piketty has little to say about global inequality.

          All that said, Piketty’s work sets a whole new context for
          understanding the rise of social Darwinism in the 19th century.
          With the increased importance of inherited wealth, it was
          ideologically important to assert that it was being inherited by
          those who had the natural abilities to make use of all that
          rentier income. Property followed the natural talent in the
          blood, it was asserted; when in fact the myth of blood was
          created to justify the inheritance of property. The biological
          followed the social.

          Interestingly Piketty does not mention Galton, Sumner and that
          horrid cast of characters in Andre Pichot’s The Pure Society.

   9

          Plume 05.27.14 at 5:01 pm

          I can see this going to extremes. Congress, under pressure from
          the NRA and the gun industry, made it basically impossible for
          the CDC to do gun violence studies. There are hundreds of laws
          on the books that make it next to impossible to expose polluters
          via the study of chemical compounds they use. “Trade secrets”
          are legion, and pretty much make it illegal for agencies like
          the EPA to do their jobs. In some states, people can be thrown
          in jail for exposing horrific practices used on animals,
          especially “beef cattle,” or even saying “bad things” about
          those practices.

          One day, perhaps, studies like Piketty’s will be subject to
          similar restrictions, silenced, legally. If that sounds too much
          like a bad dystopian novel, again, consider what has already
          been done in the name of protecting corporations and the rich.

   10

          Bruce Wilder 05.27.14 at 5:22 pm

          “methodological critics”

          The conservatives in political economy have won, because they
          have always fought for, and over, methodology. Respectable
          methods are what make work, “rigorous”. What’s respectable has
          been determined largely by aggressive conservatives. And,
          respectable methodology has always provided convenient excuses
          for ignoring reality. Centrists have often taken reality for
          granted, never really pressing the need for a critical method to
          discern what reality is, often taking the conservative
          methodological programs seriously, accepting them for the sake
          of argument, without effective counter criticism.

          The FT critique exposes this standard division. First, there’s
          the claim that the criticism is “methodological” — technical,
          arcane, something experts may testify on and have respectable
          disagreements among themselves about. The mandarins are donning
          their robes, and we hoi polloi must look on in hushed silence as
          they debate among themselves. Surely, we are entitled to any
          opinion approved by at least some of the robed wonders. The
          slander of “flawed methodology” is meant to make rejection of
          Piketty, and rejection of the reality he’s shone a light on,
          respectable. “Spreadsheet error” — where have we heard that
          before? — oh, well, that’s that, no need to read the book, I saw
          the movie.

          The second move manifest in the FT critique — more ridiculous on
          its face — is to simply claim that re-working the numbers
          reveals no trend in wealth inequality. It’s a remarkable
          indication of self-confidence, a bold bluff in the face of 30
          years of newspaper headlines and numerous manifestations in
          everyday life, but also a clear indication of the ambition of
          the right, an ambition that has been realized before.

          It is the second move that potentially turns this into the Monty
          Python dead parrot routine, and conservatives depend on the
          centrists not wanting to be part of a joke, of wanting “serious”
          debate so badly, that they will overlook the most blatant
          indications of bad faith, with solemn declarations about the
          epistemological value of motivated reasoning, and so on.

          We know where this path leads. There’s no limit to the madness.

   11

          Jim Harrison 05.27.14 at 5:26 pm

          You write “Motivated reasoning, if properly harnessed, can be
          epistemologically very valuable.” Yep, but in this instance I
          predict it won’t be or won’t be for very long. We’ve seen how
          this plays out in the climate change wars where denialist
          critiques of mainstream climatology have long since become mere
          PR devices. Unfortunately, we can expect the intellectual
          discussion of inequality to be even more distorted by interest
          than debates about climate because the powers behind the sides
          are, well, unequal. There were business and government groups
          that wanted to prevent or mitigate global warming for their own
          benefit, and these balanced the other interests. I don’t expect
          a similar correlation of forces when it’s every kind of
          privilege that is being made uncomfortable. I recall Freud
          saying something to the effect that the voice of reason was soft
          but persistent. That may be; but money is also persistent and
          it’s very loud.

   12

          Main Street Muse 05.27.14 at 6:10 pm

          “The reason that Piketty’s book has gotten such a reaction –
          both from its advocates and its critics – is because it
          threatens to upset the current equilibrium in economic
          thinking.”

          I cannot believe it took this book to “upset the current
          equilibrium in economic thinking.” I would have thought the
          crash of 2008 might have encouraged such an upset. This was a
          crash created in part when the US housing market became chips in
          a new form of black jack developed by “innovative” and well-paid
          bankers. I would have thought that such “innovation” in finance
          would have forced economists to recognize the ideology of models
          is not based in reality, that just because housing prices never
          tanked, astronomical rises in housing prices might not be
          sustainable, etc. and so on.

          It is wrong to say that “people with a lot of capital will
          naturally do better than those who don’t” – there is nothing
          natural about the growing income inequality. The political
          economy tipped many years ago on the side of theories like
          “trickle down” and the Laffer Curve. And what do we see as a
          result? Wealth flowing upward, a pretty fountain of money nearly
          as big as that diamond of Fitzgerald’s. None of that money flows
          downward, however.

          Are there economists who fervently believe capitalism (as
          practiced in the US) is NOT a rigged game? Shame on them.
          Super-PACS pick the candidates who win, not voters. And today,
          SCOTUS protects corporations, not citizens.

          For an idea on where people will go next, Google the Moral
          Monday protests in North Carolina…

   13

          adam.smith 05.27.14 at 6:11 pm

          I couldn’t disagree more with Bruce on “methodology”—getting the
          facts right is important in its own right, but it’s also
          important because overall the left tends to be on the right side
          of a lot of economic data.
          What Giles did – working through spreadsheets and their sources
          – is enormously useful and should be rewarded. Even peer review
          practically never provides that type of scrutiny. Sure, you’re
          more likely to spend hours&hours pouring over Excel if you’re
          hoping to find something, but that doesn’t make it wrong (the
          two main sources of “hoping” is a graduate student hoping to
          score a publication or someone ideologically motivated. It seems
          that, e.g., in the less publicized data dispute about AJR’s
          settler colonialism data it was the former, in the R&R case it
          was a mix of both).
          It’s also mostly _not_ arcane – Giles explains everything he
          identifies as errors in pretty lay terms.

          In this case, specifically, the only meaningful difference in
          the data – i.e. the development of wealth inequality in the UK –
          is about how to chain different data series and that’s really a
          crucial issue if you want to patch together long-term data and
          we should care about getting this right.
          And if it turns out that wealth inequality in the UK hasn’t
          actually increased, that would be a really important thing to
          know, especially given the fact that no one denies that income
          inequality at the top has increased dramatically: it could be
          that it has increased, but the British wealthy are just
          spectacularly good at hiding it. It could be that there are some
          policies in place that do decrease wealth inequality – if so,
          we’d want to know which, etc. etc.
          Like Piketty and Krugman I’d be shocked if Piketty’s general
          wealth-trend findings turn out to be false, but because I’d be
          shocked, I’d really want to know if that were the case.

   14

          David 05.27.14 at 7:14 pm

          If you look at what Piketty actually says, much of it is not
          especially radical. But the problem (and it is a methodological
          one, albeit at a higher level of abstraction) is that someone is
          even subjecting current economic orthodoxy to actual empirical
          validation by, you know, researching and presenting data. So the
          smug assertion that a rising tide lifts all boats is heavily
          qualified in practice by the pragmatic findings that the tide
          hasn’t risen very much, that it depends on how many boats you
          have, and that a lot of people don’t own boats anyway. As
          Piketty notes (with some understatement) a lot of people don’t
          realise just how incredibly artificial the assumptions that
          contemporary economists make actually are. He is working
          explicitly in the French social sciences tradition (he refers to
          a number of his illustrious predecessors) which implies long and
          painstaking collection and analysis of data over extended
          periods of time. Imagine if other people started studying
          economic issues using the same methodology? Where would it end?
          There’s one other area that’s important as well, politically,
          and that’s agency. Apologists for the current system like to say
          that it’s natural, it’s just the way things are. People get rich
          by making intelligent economic choices and working hard, and
          successful companies are those that best interpret market
          signals and follow them blindly. Piketty makes it very clear
          that the real reason for the increasing inequalities in
          ownership of capital are firmly rooted in actual political
          decisions about taxation and spending. Which means, of course,
          that in principle those inequalities could be reversed in the
          same way …. What a thought.

   15

          Bruce Wilder 05.27.14 at 8:11 pm

          if it turns out that wealth inequality in the UK hasn’t actually
          increased, that would be a really important thing to know

          “if”?!?

          especially given the fact that no one denies that income
          inequality at the top has increased dramatically

          “no one denies” ?!? (makes that “if” strangely ironic)

          My point was that there’s a danger of too much in the way of
          concessions of good faith at the center and on the center-left
          turning this whole discussion into an exercise in agnatology
          (i.e. ” the study of culturally induced ignorance or doubt”),
          and it seems to me that the usually reasonable adam.smith is
          demonstrating that danger in his comment.

          It’s not reasonable to suppose that wealth inequality has not
          increased. If you concede that kind of unreality, even in the
          subjunctive, you’ve passed thru the looking glass. And, it is
          also not reasonable to suppose that there are not plenty of
          people, whose political druthers or self-interest, won’t lead
          them to deny it, if they are given any chance. There are plenty
          of economists, who will happily deny the existence of
          involuntary unemployment, even while millions go without work or
          income, or deny the failure or inefficiency of financial
          markets, even in the wake of a global financial crisis. The
          precedents are clear. There are no limits and there are
          consequences.

          I’d be really shocked if Piketty’s general wealth-trend findings
          were not “false” in some particulars or at some level of
          discrimination or resolution. Piketty’s said as much, in
          acknowledging that there’s quite obviously a lot of measurement
          error in the various series, and judgment calls in the process
          of stringing them together. And, that’s not to mention the deep
          conceptual issues about what constitutes wealth or capital and
          what we think the nature of the thing we are measuring is.

          My view is that methodology is very, very important — too
          important to be left to lunatics like Robert Lucas or Edward
          Prescott or — in earlier eras, Milton Friedman or Vilfredo
          Pareto (or really scary, Mises). It isn’t enough to just claim
          that “no one denies” whatever seems obvious in the large. It
          isn’t enough to claim that financial markets are obviously not
          efficient or that prices are obviously sticky or that wealth is
          obviously increasing in size relative to the economy and in
          concentration (Piketty’s two claims.)

          If we acknowledge the obvious, and then try to measure it — to
          turn subjective perceptions and experience into common,
          objective measurements, we are creating a shared reality. And,
          as the OP eloquently explains, then it becomes a social science
          problem to solve, and a problem that politics cannot ignore.
          That’s what’s at stake here. Method matters, because methods are
          how we get measurement, and measurement is subject to caveats
          and doubt and error and judgment and conceptual prejudice, so we
          take methodology seriously, but conservative hacks to be jokes,
          or we lose.

          Done right, method and measurement take us from vague and
          subjective perceptions to a common understanding, informed by
          detailed understanding. It equips institutions of governance
          with competent staff and conceptual frameworks. If it all
          becomes a dust cloud of denial and confusion, we end up with a
          social science and politics of learned helplessness.

          We’ve had thirty or forty years of a politics based in large
          part on a successful effort to debase academic policy economics,
          so that people do not hold the government responsible for the
          performance of the economy. And, the result is political cover
          for disastrous policies, and no political consequences for the
          purveyors of disaster. (Krugman had a piece today on how bizarre
          ideas about economic causality drive Euro policy forward from
          catastrophe to serial disaster.)

   16

          adam.smith 05.27.14 at 8:50 pm

          Bruce – as Piketty says, out wealth data is incredibly bad. I’m
          not going to assume bad faith in any attempt to take a closer
          look at Picketty’s findings in that respect. Because the data is
          so bad, I think it’s certainly possible, if unlikely, that we’re
          not seeing much of an increase in wealth inequality in some
          cases.*

          Our income data, on the other hand, is good enough to declare
          anyone who doubts that income inequality is increasing in the UK
          (and almost all other advanced industrialized countries) outside
          of fact-based discourse.

          * and I also don’t think the FT is exactly the opinion pages of
          the WSJ ideologically, nor does Chris Giles seem like an
          ideological attack dog, though both he and the FT certainly skew
          neoliberal.

   17

          shah8 05.27.14 at 8:52 pm

          Bruce Wilder, one of the frustrations with Piketty that has been
          sounded ever since the start of talk is that Piketty
          demonstrated through standard economic lenses things that
          heterodox economists have always known or could show to be valid
          for whatever constraints they name. Even then there was that
          peculiar “lump of capital” fallacy that “rigorous” economists
          always say “sure” and shrug it off, embedded in Piketty’s
          analysis.

          I don’t really think that Piketty is all that revolutionary, and
          I don’t think Piketty leads to any revolutionary reanalysis of
          class relations or any other thought modes that might reset who
          are winners and who are losers. We have a very sophisticated
          propaganda apparatus that creates lots of sinks with which
          frustrated energy can go into talking about, but can never go
          anywheres. I always think of ZeroHedge, Testosterone Pit, and
          likeminded sites as exemplars where dissent is twisted into
          angry confusion rather than any sort of effectual thinking. Much
          of the talk about 1%’ers and inequality is similarly
          ineffectually crude. You can’t make meaningful policy from
          “millionaire taxes”, for any number of reasons. The sort of talk
          that has always been carefully excluded is usually about power,
          and usually about how rentiers can directly impose power on the
          people around them. So, strong nudges away from single payer or
          single insurer. Strong nudges away from restructuring bankruptcy
          rules so that normal people have more economic rights. Strong
          nudges away from talking about access to legal resources,
          particularly against the powerful (and plenty of talk about evil
          tort lawyers), or of even collective action against bad actors
          with power.

          A compensationary state where people get a minimum living
          allowance of some sort is allowed in public forums. An
          egalitarian state where the poor can testify against the rich at
          any sort of remotely equal level in the legal system is not
          truly allowed. That would interfere with Geithner making it all
          better for his friends.

   18

          Bruce Wilder 05.27.14 at 8:56 pm

          On past performance, I’d be less concerned about how the clowns
          on the right try to shape the narrative of Piketty with denial
          and “spreadsheet errors”, than about soi-disant liberals, like
          Brad DeLong, Larry Summers or, unfortunately, the not so
          reliable Krugman. With them, it isn’t the measurements, per se,
          but the conceptual issues that will cause confusion. They will
          cling to the idea of capital as a factor of production, to
          diminishing returns, to strange views about substitution between
          capital and labor (robots, the “virtue” of skills and
          education), and experience the greatest difficulty in seeing
          political conflict over distribution as anything but a
          misunderstanding.

          r > g as a trend is a huge conceptual challenge, because it
          implies that increasing wealth (nevermind increasing
          concentration of wealth) is, at the margin, a bad thing for
          society and for social welfare. That’s a tough thing for
          mainstream economists to wrap their heads around. Seeing
          imaginatively how that could be the case could have a profound
          impact on politics, as the OP indicates. But, it will be most
          destabilizing, I think, for the vaguely center-left mainstream
          establishment, as it challenges their sincere faith in the
          “market economy” as an unjust world that could be made more just
          with just a few tweaks and adjustments and oil on points of
          friction.

   19

          casino implosion 05.27.14 at 9:14 pm

          lol @ konczal. If the doings of social scientists had any effect
          on the world of wealth we’d have all been on big rock candy
          mountain for a century now.

   20

          shah8 05.27.14 at 9:14 pm

          Wait, the center-left, in the technocratic guise, has never had
          a “tweak” ideology, except when they want to appease sentiment
          they view as being too far to their left. What folks like Arne
          Duncan and Samantha Power wants to really do are not “tweaks”,
          but remaking of entire power structures. The ACA is not a
          “tweak”. However, what usually happens is that the center-left
          will always construct, in conservative terms, the market
          narrative, and ply “tweaks” for that, like the cadillac tax on
          health insurance, or lotteries for entrance into good charter
          schools (of course, only so many seats).

   21

          Bruce Wilder 05.27.14 at 9:26 pm

          shah8 @ 17

          All true.

          I do think think there’s something to the idea that Piketty
          signals a change in the zeitgeist, just the beginning of an
          awakening by the upper middle class that the megarich are eating
          the economy from the bottom up. As the consciousness spreads
          among the presently complacent that they might be next on the
          menu — and as the U.S. economy takes the next big step in its
          downward trajectory of income — the character of political
          protest will change and we will see if the apparatus of the
          surveillance state is up to the job put to it.

          adam.smith @ 16 Because the data is so bad, I think it’s
          certainly possible, if unlikely, that we’re not seeing much of
          an increase in wealth inequality in some cases

          I’m not sure what work you imagine “in some cases” is doing for
          you, so maybe you have some understanding of your statement,
          which is not ridiculous foolishness. There are necessary
          relationships between income and wealth, such that it simply
          isn’t possible, given what we know about changes in income
          inequality and readily observed indicators of wealth like the
          property market or the financial markets, for there to be no
          appreciable increase in wealth inequality. The more than
          proportional increase in the claims of wealth on national income
          are not in doubt, and that increase, given that a very large
          part of the population is known to have no appreciable wealth,
          implies increased inequality of wealth. In fact, it implies, I
          think, that the rich are eating the poor — to put it in plainer
          terms than the mild and neutral “inequality” usually indicates.

   22

          John Garrett 05.27.14 at 9:33 pm

          There is definitely a change in the zeitgeist, but it really
          began (or perhaps exploded) with the occupy movement. I don’t
          think those brave few have ever been sufficiently recognized by
          us older folks on the left.

          JG

   23

          adam.smith 05.27.14 at 9:57 pm

     I’m not sure what work you imagine “in some cases” is doing for you,
     so maybe you have some understanding of your statement, which is not
     ridiculous foolishness.

          I mean country cases, in this case the UK. I’m sure you regard
          my position as ridiculous foolishness, but there is no necessary
          relationship between income and wealth. If the high earners
          spent a larger share of their income on (conspicuous)
          consumption, for example, you can have an increase in income
          inequality without an increase in wealth inequality. If (and I’m
          taking your word for it) wealth as a share of national income is
          increasing, that could also be true because of middle-class
          wealth increases (which would still be wealth inequality, but
          not show up in Piketty’s 90%/99% data). Do I think that’s
          terribly likely? no.
          But given how little we really know about wealth, I I think it’s
          a bit early to shut down the debate and assume anyone who raises
          a doubt about this is acting in bad faith.

   24

          Bruce Wilder 05.27.14 at 10:18 pm

          shah8 @ 19

          Yes. All true. Except I’d question whether Arne Duncan and
          Samantha Power genuinely constitute center-left, and not
          center-right; the pro-plutocracy conservatism of the Obama
          Administration is confusing — I expect it’s their main selling
          point relative to their political funders.

          And, privatizing education would be the classic case of what
          drives r > g, the rich eating the poor, with no robots or
          technologically determined marginal productivity of capital
          dictating a natural distribution of income. Will any centrist
          establishment economist notice? Draw a connection? Of course,
          the accepted methodologies define “microfoundations” in terms
          that make such connections between the detail and the general
          impossible. The methodologies insisted upon by conservative
          ideologues.

          I just finished reading Larry Summer’s review of Piketty —
          pointed to by DeLong, natch. It’s everything you’d expect,
          including the bits of brilliant irony interjected to make parody
          impossible. He opens by comparing Piketty’s Capital to Kennedy’s
          Rise and Fall of the Great Powers in its ability to seemingly
          capture the zeitgeist, characterizing Kennedy’s work as a
          warning against the danger of imperial overreach, but instead of
          noting the imperial overreach and the economic squandering of
          the second Bush Administration that fulfilled Kennedy’s
          prophecy, he tells us,

     . . . recall that Kennedy seemed to hit the zeitgeist perfectly but
     turned out later to have missed his mark as the Berlin Wall fell and
     the United States enjoyed an economic renaissance in the decade
     after he wrote

          Really, what can you do with that? Summer’s peroration includes
          a call for a policy of increased public investment in
          infrastructure — the very policy he effectively opposed in
          office in 2009.

          Most people have only the vaguest idea what economists are
          talking about in the best of times — and that’s by design.
          Economists actually count obscurity of terms and framework as
          desirable features of their disciplinary discourse, and this
          extends to accepted customs of popularization, which reduce Econ
          101 and op-ed policy economics to tales of a just world, the
          magic of the market, and the fairy dust of business confidence.
          I’m not confident that I understand how the hard grit of reality
          grinds away at that kind of ideological nonsense, or how crisis
          affects it, but of grinding and crisis, I’m confident enough.

   25

          Bruce Wilder 05.27.14 at 10:26 pm

          there is no necessary relationship between income and wealth

          If wealth is not a claim on income, what is it?

   26

          Agog 05.27.14 at 10:47 pm

          The Citigroup ‘Plutonomy’ notes remain a useful and charmingly
          amoral resource on these issues of course.

   27

          elm 05.27.14 at 11:08 pm

          adam.smith:

          Giles claims:

     However, whichever level one picks, the lines in red in the graph
     show that – unlike what Prof. Piketty claims – wealth concentration
     among the richest people has been pretty stable for 50 years in both
     Europe and the US.

          That result, and his central claim: “wealth concentration among
          the richest people has been pretty stable for 50 years in both
          Europe and the US” is strikingly at odds with what the bulk of
          academid researchers on the subject have found, especially
          regarding the U.S.

   28

          Bruce Wilder 05.27.14 at 11:33 pm

          . . . given how little we really know about wealth, I think it’s
          a bit early to shut down the debate and assume anyone who raises
          a doubt about this is acting in bad faith.

          I’m not going to belabor the point any further than this
          comment; other people have things to say, I’m sure. If you don’t
          realize that doubts will be raised in bad faith, . . . well,
          nothing I say is going to help you. FT, in addition to (nearly
          but not quite) denying wealth trends identified by multiple
          studies as well open-eyed observation, has, itself, come very
          close to alleging data fabrication, with no basis I can see, so
          I think we can dispense with high-minded posturing. We do know
          some things about wealth, and what we know ought to put some
          bounds on what we find worthy of deep skepticism.

          We also know some things about propaganda, and I’m surprised by
          how many have gleefully picked up on “spreadsheet errors” to
          make the comparison with Rogoff and Reinhart, and to take a
          swipe at Krugman for tribalism, with a sniff of “see, both sides
          do it”.

          We should be suspicious. We have every reason to believe that
          some entering in the debate will do so with the intention of
          destroying all knowledge and any truth they find inconvenient.
          This is nothing new.

   29

          adam.smith 05.27.14 at 11:54 pm

          elm – I do think he’s overstating and I think his argument about
          the US is pretty weak, but he is right that, if you look at the
          Kopczuk/Saez data which runs until 2000, you see surprisingly
          little movement for the wealth share of the 1% after WWII:
          https://www.documentcloud.org/documents/1165408-kopczuksaez2004.
          html (table on p. 67) and Saez isn’t a suspect for wanting to
          cover up inequality. That said, I would have imagined – and
          other results seem to show – that there’s a clearer upwards
          trend since, probably starting out in the 1990s. So I think it’s
          highly unlikely that there’s no upward trend in the US, but
          Giles isn’t completely off-base here given the cited datasource.
          In the UK, I’m much less certain. If I had to bet, I’d still
          think you’d find an upwards trend. What’s confusing there is
          that Picketty seems to use data for 1990 that Giles has first
          appearing at 2002 so someone has to be wrong here, and
          substantially so. And if the strong upwards trend in the UK is
          based on three data points from the 2000s from a series with
          dubious comparability, that’d be bad. Of the various things that
          Giles raises, that seems to be the one that most requires a
          response.

   30

          Tabasco 05.28.14 at 1:18 am

          If income inequality has been increasing, and the FT is not
          denying this, then the only way that wealth inequality could not
          also be increasing is if the (absolute, not proportionate)
          dollars that the rich have left over after they spend is their
          income is the same as the dollars left over by the non-rich .
          This seems unlikely. Or, if the non-rich have made much bigger
          dollar capital gains on their houses than the rich. Again,
          unlikely.

          Which is Piketty’s point, of course.

   31

          adam.smith 05.28.14 at 1:57 am

     If income inequality has been increasing, and the FT is not denying
     this, then the only way that wealth inequality could not also be
     increasing is if the (absolute, not proportionate) dollars that the
     rich have left over after they spend is their income is the same as
     the dollars left over by the non-rich .

          no, that’s incorrect.
          1) what matters for wealth shares are proportions, not absolute
          values. Simple example:
          A owns $1000 and earns $200 and spends 100; B owns $100, earns
          $20, and spends 10. Wealth inequality remains the same. Now
          increase income inequality and have A earn $300 but spend $200.
          Wealth inequality still remains the same, though A still saves
          10 times as much as B.

          2.) Another example – mostly hypothetical, but still – is a
          reversal of fortune. Take the example above, but now have B earn
          $300 and A fall down to $20. Obviously wealth inequality falls,
          while income inequality increases.

          Again, as I say from the start, I find it more plausible that
          wealth inequality is increasing, but I don’t think we have the
          data to be as confident about this across the board as most here
          seem to be; and the income data we have doesn’t necessarily mean
          increasing wealth inequality—it just means it’s more likely.

   32

          geo 05.28.14 at 2:04 am

          adam.smith@13: it could be that [wealth inequality in the UK]
          has increased, but the British wealthy are just spectacularly
          good at hiding it

          How about the American wealthy? I once came across a passing
          comment by (I think) Robert Kuttner that around $9 trillion of
          wealth was hidden. Does anyone know?

   33

          roger nowosielski 05.28.14 at 2:12 am

          Good job, Henry. I wish, however, that your valiant effort to
          return the “dismal science” to its humble beginnings, though
          certainly on the right track, had a bit more bite to it. The
          citation from Foucault is all to the good, of course, for any
          challenge to the dominant narrative by speaking truth to power
          is certainly a good place to start. In light of the fact,
          however, that our capitalism-driven political system is so
          intertwined with and codependent upon the prevalent economic
          paradigm, there isn’t really much reason to hope that anything
          worthwhile might ensue from recasting our economic disagreements
          in terms of the political. As Mike’s review makes it rather
          clear, the limits of the potential universe of discourse will
          continue to be defined by the right and the left wingers — all
          the usual suspects, really. Nothing new and different there.

          May I suggest a much more radical approach to the problem.
          Benjamin Kunkel’s Utopia or Bust —
          http://www.versobooks.com/blogs/1566-exclusive-extract-chapter-o
          ne-of-utopia-or-bust-by-benjamin-kunkel — is certainly a good
          place to start. Also see Richard D. Wolff’s “Beyond Piketty’s
          Capital: Richard Wolff Warns us Not to Band-Aid Capitalism,” as
          per link:
          http://www.rdwolff.com/content/beyond-piketty%E2%80%99s-capital-
          richard-wolff-warns-us-not-band-aid-capitalism

   34

          Bruce Wilder 05.28.14 at 2:27 am

          . . . hidden. Does anyone know?

          if anyone knew, it wouldn’t be hidden, would it?

          A great deal of wealth is hidden in plain sight, in the sense
          that the totals or the income streams are more or less known,
          just the equities are hidden, but some of the big numbers are
          attached to contingencies that really obscure who owns what.
          That’s what derivatives do and the numbers there are huge.
          Piketty argues, I believe, that one of the reasons to impose
          wealth taxes is to clarify the equities.

   35

          Cranky Observer 05.28.14 at 2:45 am

     = = = A great deal of wealth is hidden in plain sight, in the sense
     that the totals or the income streams are more or less known, just
     the equities are hidden, but some of the big numbers are attached to
     contingencies that really obscure who owns what. That’s what
     derivatives do and the numbers there are huge. = = =

          Not all US wealth is found in the big coastal cities, nor
          necessarily trades on Wall Street. I’d suspect that very large
          amounts are tied up in real estate and local mid-sized corporate
          entities, family controlled across multiple generations.
          Although manufacturing in general isn’t what it was,
          historically a midsized machine shop serving the
          aerospace/military industries, and its associated properties
          accumulated over 30-50 years, could comprise $200 million of
          family wealth that appears on no researcher’s ledger.

          Cranky

   36

          Tabasco 05.28.14 at 3:28 am

          Adam.smith

          Point taken, but for your first counter example to work in
          practice, the super rich would have to consume an awful lot.
          Now, of course, there are a lot of stories around of ultra
          conscious consumption, and wall streeters who put their entire
          incomes up their noses, but there also a lot of stories of rich
          people who live off the interest on their interest.

   37

          Dr. Hilarius 05.28.14 at 3:34 am

          First, John Garrett@22, your observation is consistent with my
          own. The Occupy movement and news coverage of it brought the
          issue of income/wealth inequality into the mass media. I recall
          watching Brian Williams of NBC covering the issue and thinking
          “this is amazing.”

          Not being any kind of an economist I can ‘t weigh in on data
          about whether wealth inequality has increased or remained stable
          for the top 1%. My daily experiences says yes.

          But another important factor is the geographic distribution of
          income. Concentrated wealth in major urban areas prices out even
          the middle class. Housing costs are a major factor. A friend had
          40+ groups of would-be renters show up for an open house. A
          potential renter needed at least $9600 cash up front to get into
          this modest 2-bedroom house. It was rented to an Amazon employee
          making over $125K. Increases in commercial rents exclude
          businesses that don’t market luxury goods. Hardware stores are
          replaced with Restoration Hardware. Neighborhood bars are
          replaced with bars featuring 50 different single malts (not to
          malign single malt, but it is expensive). Can’t afford $20 to
          park your car while shopping? It’s off to the suburbs with you,
          you aren’t our type any longer.

   38

          Manta 05.28.14 at 9:52 am

          “the dominance of these economic theories has had profound
          political consequences”: is it true? It seems to me that
          Frederick’s maxim is more accurate:
          “I begin by taking. I shall find scholars later to demonstrate
          my perfect right.”

   39

          reason 05.28.14 at 10:27 am

          Rakesh Bandari @8
          “But if the r not on capital in general but on domestic,
          non-financial or industrial investments is not high enough to
          motivate capital accumulation–and this seems to be the case in
          the US–we get not patrimonial capitalism in economic equilibrium
          but an economic crisis or secular stagnation that can only be
          resolved if capital can restructure industrial and labor
          relations to raise again not r in general but r on domestic
          industrial investments.”

          Why do you think “restructure industrial and labour relations”
          is the answer rather than realign exchange rates?

          Rakish B

   40

          Barry 05.28.14 at 12:18 pm

          Henry: “…whether they like to emphasize efficiency questions
          over distributional concerns, or vice versa…”

          Last I heard, the people trumping ‘efficiency’ (1) gave not been
          able to actually show any lost of growth or output at the levels
          of distribution even slightly achievable, and (2) have quite
          carefully missed the fact that the developed world has not seen
          increases in growth after adopting numerous right-wing changes.
          They use a specter of ‘weapons of mass economic destruction’
          which is just as fraudulent as Saddam’s.

   41

          Barry 05.28.14 at 12:22 pm

          Vladimir 05.27.14 at 4:25 pm
          “It would be interesting to compare the reaction of the various
          pundits in regard to the discovery of errors in the work of
          Rienhart and Rogoff vs. Piketty. “

          Note that R&R didn’t just have a spreadsheet error, they trimmed
          their data, with all points removed being against st their
          hypothesis.

          When a grad student does that, there are nasty words used,
          concluding with ‘you are expelled’. When elite economists do it,
          that’s not even to be mentioned in the field.

   42

          reason 05.28.14 at 12:38 pm

          oops
          Sorry I have no idea where the “Rakish B” at the bottom came
          from. It is not meant to be there (in case anybody thinks I was
          being rude).

   43

          TM 05.28.14 at 1:48 pm

          BW 18: “r > g as a trend is a huge conceptual challenge, because
          it implies that increasing wealth (nevermind increasing
          concentration of wealth) is, at the margin, a bad thing for
          society and for social welfare.”

          I’m sorry but none of this makes sense. r>g actually doesn’t
          imply what Piketty says it implies and it certainly doesn’t shed
          any light on why “increasing wealth is a bad thing for society”,
          and neither is it empirically well founded. It is unfortunately
          an immense distraction away from the empirical accomplishment of
          Piketty’s work, I assume born out of the desire to be seen as a
          theoretician rather than “just” a data cruncher. What people (e.
          g. Krugman) now take away from it is the entirely misconceived
          idea that we need to focus even more on raising g by any means
          possible.

   44

          Rakesh 05.28.14 at 3:03 pm

          @39 important point.
          Possible considerations.

          1. Strength of US exports less sensitive to relative value of
          dollar than the strength of growth abroad (there is old
          econometric research by Andrew Warner on this); growth abroad
          may depend on raising r through restructuring of labor
          relations.

          2. Currency politics could result in beggar-thy-neighbor
          dynamics.e.g. a weakened dollar could compound problems of
          insufficient profitability in, say, Japan to sustain real
          investment. This is the dynamic that Robert Brenner had
          emphasized.

          3. Lastly QE seems to have already had the effect of pushing the
          dollar down without solving the underlying secular stagnation,
          though the dollar seems to be strengthening at the moment.

   45

          TM 05.28.14 at 4:18 pm

          AS 29: Krugman cites a data series by Emmanuel Saez and Gabriel
          Zucman that looks very different from Kopczuk/Saez:
          http://krugman.blogs.nytimes.com/2014/03/24/american-patrimony

   46

          Bruce Wilder 05.28.14 at 5:28 pm

          TM @ 41

          Perhaps you could commit yourself to what you think r > g as a
          sustained trend implies.

          Because I’m getting nothing out of open-ended negatives.

   47

          elm 05.28.14 at 6:38 pm

          TM@43: Piketty himself referred to that newer, more
          comprehensive series in his response to FT.

     For instance, my US series have already been extended and improved
     by an important new research paper by Emmanuel Saez (Berkeley) and
     Gabriel Zucman (LSE). This work was done after my book was written,
     so unfortunately I could not use it for my book. Saez and Zucman use
     much more systematic data than I used in my book, especially for the
     recent period. Also their series are constructed using a completely
     different data source and methodology (namely, the capitalisation
     method using capital income flows and income statements by asset
     class). The main results are available here:
     http://gabriel-zucman.eu/files/SaezZucman2014Slides.pdf.
     As you can see by yourself, their results confirm and reinforce my
     own findings: the rise in top wealth shares in the US in recent
     decades has been even larger than what I show in my book.

   48

          Agog 05.28.14 at 7:22 pm

          I’d love to see a thorough dissection of Chris Giles’
          contributions to the FT over the past few years. In recent years
          it has become predictable to read in his pieces that deficits
          must be reduced and that interest rates must be raised, almost
          as if he were shilling for rentier interests.

   49

          elm 05.28.14 at 7:51 pm

          Agog, I’d noticed the same about Giles. Relentless criticism of
          any anti-austerity research and boosting of pro-austerity data.
          I wonder if and how he covered Reinhard & Rogoff’s paper in
          2010?

          The problems with Reinhart/Rogoff’s 2010 paper, of course,
          extended beyond excel mistakes:

     While using RR’s working spreadsheet, we identied coding
     errors, selective exclusion of available data, and unconventional
     weighting of summary
     statistics.

          By “unconventional weighting of summary statistics” and
          “exclusion of available data”, they mean that R&R threw out 4
          out of 5 high-debt years worth of data for New Zealand and then
          weighted the one remaining year (oddly, with negagive growth)
          equal to 19 years of high-debt U.K. data.

   50

          TM 05.28.14 at 7:57 pm

          BW, “Perhaps you could commit yourself to what you think r > g
          as a sustained trend implies.”

          If r is the return on capital, as it is then r > g doesn’t
          really imply anything because it is meaningless. g is a growth
          rate but r is not. Also, g is a growth rate of a flow, not a
          stock.

          If r is the rate of net reinvestment, which is what people
          generally seem to take it to mean even though that’s not the
          definition given (namely, rate of return), then the numbers
          Piketty cites cannot be empirically right for reasons that I
          explained on an earlier thread, to wit: there is no way growth
          rates on the order of 5% can be sustained over time spans of
          centuries. Furthermore, I find it implausible to believe that
          aggregate capital in the US for example has been growing at a
          high rate since the 1970s or so. What we have seen is not a
          fantastic rate of investment but the opposite: deinvestment,
          deterioration and deindustrialization. I don’t see any evidence
          for the theory that rising inequality has been driven by capital
          investment – the opposite is true!

   51

          Bruce Wilder 05.28.14 at 8:43 pm

          TM @ 48

          r > g forces you to see — as you clearly do see already — that
          income from wealth can not be exclusively or primarily income
          from (socially) productive capital investment.

          r is a rate of return on accumulated wealth, which can not be
          the same as accumulated capital in the sense of synthetic
          factors of production. Private wealth may be socially parasitic,
          and its accumulation socially pernicious.

          Given the dominance of neoliberal interpretations of
          neoclassical economics, which is basically an economics of
          virtue triumphant, in which investment in innovation and skills
          earn their just rewards, this is a considerable challenge. In a
          policy regime determined to reduce taxes on wealth, in order to
          encourage accumulation, Piketty has stepped in to advocate taxes
          on wealth to rein in its accumulation, before its accumulation
          dooms us.

          If you can see how accumulating concentrations of wealth drive
          disinvestment, then you can understand our world.

   52

          TM 05.29.14 at 5:50 pm

          I’m afraid I disagree with your interpretation. Not with
          statements like “Private wealth may be socially parasitic, and
          its accumulation socially pernicious”, but with the claim that
          this is what follows from, or is “proven” by, Piketty’s
          conceptual framework.

   53

          TM 05.29.14 at 6:08 pm

          Just got this petition solicitation:

          “I support using Thomas Piketty’s powerful new framework to
          evolve progressives’ fight against the concentration of
          political and economic power.”
          http://www.progressivesunited.org/action/piketty-capital

          No idea what that means, and who is supposed to read that
          petition… It’s probably just me.

   54

          Neil in Chicago 05.30.14 at 12:31 am

          . . . one can explain the immediate reaction of 85% of
          economists very simply: You don’t get tenure by telling the
          emperor he’s naked.

   55

          adam.smith 05.30.14 at 2:15 am

          For those still interested, Piketty’s comprehensive, and
          entirely convincing imo, reply is here:
          http://piketty.pse.ens.fr/files/capital21c/en/Piketty2014Technic
          alAppendixResponsetoFT.pdf
          He does say that the UK data is of terrible quality overall and
          that is, of course, a problem, but his arguments against using
          the UK wealth series preferred by the FT is very convincing.

   56

          reason 05.30.14 at 8:00 am

          Rakest @44
          1. Exports are not the point. Net exports are the point (and
          remember the J-Curve adjustment, where initial movements may be
          in the wrong direction)
          2. Yes, currency politics are a problem which why the whole
          disfunctional international financial system needs (which has
          caused the problem) needs to be sorted out.
          http://www.theguardian.com/commentisfree/2008/nov/18/lord-keynes
          -international-monetary-fund
          3. I’m not sure that this isn’t a point in my favour. It sounds
          suspiciouly like the story about how stimulus didn’t work
          because we still haven’t fully recovered, ignoring that the
          supporters of stimulus said from the start that it wasn’t big
          enough.

          The point is that an overvalued dollar, hurts workers everywhere
          in that it pushes demand for labour down domestically, and
          reduces the value of money wages elsewhere. Japanese citizens
          (and German citizens) benefitted from a long run process
          increasing their purchasing power as their currencies
          appreciated. We need that process to happen again. It seems to
          me that modern international financial system systematically
          responds incorrectly, creating vicious rather than virtuous
          circles (leading to stagnation and disinvestment in highly
          productive countries and limiting the gains less productive
          ones). Capital should flow from rich to poor countries not the
          other way.

   57

          Corey Robin 05.30.14 at 1:37 pm

          Folks in this thread may be interested in this piece by Seth
          Ackerman, over at Jacobin, on Piketty, his defenders, and his
          critics. It may be the best, and certainly the most
          comprehensive, that I’ve seen. Definite must reading.

          https://www.jacobinmag.com/2014/05/pikettys-fair-weather-friends
          /

   58

          elm 05.30.14 at 3:36 pm

          Corey Robin @56: Thank you/curse you for the link.

          The material is fascinating and challenging, as are the articles
          it references (spoiler alert, Larry Summers is still a jackass).

          On the other hand, I had planned to tend my lawn and paint the
          guest bedroom this weekend, and it seems like I’ll be otherwise
          occupied now, with 1000+ pages of reading to catch up on
          (including Piketty, whose book I have not yet read).

   59

          Rakesh 05.30.14 at 4:08 pm

          OK so we have the question of whether the decline in r will be
          small enough as the capital-output ratio rises that capital
          income relative to labor income will in fact rise too.
          Piketty concedes that r could fall but insists on the basis of
          historical evidence and technological optimism that it’s not
          likely to fall enough for distributional shares to remain
          constant. He predicts greater inequality or the return of
          patrimonial capitalism as the capital-outcome ratio rises.
          Piketty has been focused on distribution, and so have his
          critics.
          But after the discussion of this and the Cobb-Douglas function,
          Piketty does turn to Marx, though there is very little direct
          commentary on this section.
          And the point that I am making is that Marx did not argue that r
          had to fall to zero to create convulsions, and Piketty
          recognizes that a falling r has historically caused convulsions,
          e.g. imperial conflict over investment outlets.
          Piketty concedes that r can or even likely will fall. He only
          insists that it’s not reasonable to assume that r will fall
          below g. But what he does not recognize is this: r does not have
          fall to zero for surplus value to be inadequate to sustain
          accumulation if minimum capital requirements are rising and/or
          depreciation schedules are short.
          If insufficient surplus value is produced to sustain real
          investment, we will find not the return of patrimonial
          capitalism but a different set of problems, e.g. groping or even
          radical attempts to reorganize production to raise
          profitability, struggle over the control of investment outlets,
          the use of otherwise idle surplus value in the world economy
          turned into a global casino. This will create more immediate and
          sharper problems for the capitalist system than slowly growing
          distributional inequality.
          Marx’s Capital remains more relevant than Piketty’s Capital.

   60

          Ronan(rf) 05.30.14 at 4:31 pm

          Ackerman’s review is interesting, and is the best explanation
          Ive read (although I havent searched high and low for an
          explanation, I have to admit) of the Cambridge capital
          controversy.
          I have a (slightly tangential) question though. He makes a
          comparison between the ‘leisure class’ of the late 19th century
          and today’s elite (who are driven, hard working etc) Was the
          perception of a ‘leisure class’ a fact, or was it an image they
          cultivated/a caricature that was asigned to the elite ? If the
          modern elite is more (superficially) representative of the
          population at large, and more concerned about their position
          (more willing to work hard to maintain it) , does that imply
          that there is a lot more competition amongst the elite than
          there was ? (Is it the case that movement within the elite is
          now more fluid, and wealth more transient ? Is there more
          mobility within and between deciles, particularly at the top and
          bottom? )
          Ackerman seems to assume that “mores have changed”, could it be
          that they changed as a reaction to greater competition within
          the elite ?
          Note: Im sure someone out there knows a lot about this subject
          and the question doesn’t make a huge amount of sense as framed,
          so Im just spitballing really ..

   61

          William Timberman 05.30.14 at 4:45 pm

          Bruce Wilder @ 51

          I find this interpretation persuasive, even if TM doesn’t. I
          think you’ve nailed it, and such additional gloss as needs to be
          applied to Piketty’s work from the left is amply provided by the
          Seth Ackerman piece linked by Corey@56. The elements of a
          coherent narrative are all more or less in place, but some
          crucial questions remain. Taking the Kochs as the symbolic
          stand-ins for the entire class of Piketty’s noveaux riches, and
          referring specifically to conditions in the U.S., I would ask:

          1. Do the Koch brothers really want to run the country? Will
          their heirs be equally sanguine about the task bequeathed to
          them? Somehow, despite the unholy tincture of egotism and
          prudery which has driven them so far, I doubt they have any real
          idea what they’d be getting themselves into.

          2. Will their bedfellows among the libertarian and social
          conservatives stay where they’ve been put? As the strains we can
          already see opening fissures in their united front are
          intensified by the consequences of their own influence on public
          policy, this doesn’t seem a foregone conclusion.

          3. What about the entrenched interests of the x/industrial
          complexes which hitherto have been to such a great extent
          creatures of the capture of government by private wealth? Will
          they continue to acknowledge their true masters, or will they
          engage in their own essentially unmanageable enterprises? When
          the entire staff of the state department would be hard put to
          crew our existing fleet of aircraft carriers, I think one has a
          right to ask.

          Needless to say, this is a partial list, but even so we can’t go
          far wrong in suspecting that 1980-2014 amounts at best to a bit
          of busking while we wait in line for our tickets to the main
          event.

   62

          LFC 05.30.14 at 4:53 pm

          TM @50:

          Question: what future time frames is Picketty dealing with? Is
          he dealing with centuries (in which case I tend to understand
          your point)? Or is he projecting out only in terms of decades
          (for which time span I would disagree w you that r>g is
          meaningless)?

   63

          LFC 05.30.14 at 5:15 pm

          Ok, I read the Ackerman piece to this point:

     its gloomy forecast of a return to “patrimonial capitalism” is based
     on the prediction that over the next decades, the gap between r and
     g will widen

          So P’s projections are in terms of decades, not centuries, and I
          therefore disagree w/ TM’s conclusion that r>g is meaningless.
          If the time frame is decades (as opposed to centuries), I don’t
          think it’s meaningless.

   64

          LFC 05.30.14 at 5:32 pm

          The Ackerman piece (down to where I read) is good, tho I had a
          bit of trouble following the factory/McDonald’s analogy, which
          is prob my deficiency, not his (plus I didn’t follow the
          internal link).

   65

          bob mcmanus 05.30.14 at 5:45 pm

          63: Anybody want to crunch some numbers?

          At our current conditions, well under 1.0% growth, flat to
          declining wages, high underemployment, middle class expenses
          rising, and the gains to the top continuing as they have since
          2009, I would expect patrimonial capitalism to get here pretty
          quickly. To the extent it is not already here.

          The question at any time is whether this generation of rich
          decide this is the time to lock it in for their progeny.

   66

          elm 05.30.14 at 6:18 pm

          On the controversy about r>g, I guess Keyes’s quote comes to
          mind:

     But this long run is a misleading guide to current affairs. In the
     long run we are all dead. Economists set themselves too easy, too
     useless a task if in tempestuous seasons they can only tell us that
     when the storm is long past the ocean is flat again.

          Perhaps, as Summers, et. al. assert r>g will eventually stop
          holding. If it takes a long time for those imagined forces to
          assert themselves, or if the mechanism requires another couple
          of world wars, then it’s not particularly relevant.

          LFC@64: The McDonalds training materials state/assume that
          worker productivity is constant, rather than declining with
          increasing worker-count. I.e. the Econ 101 story of diminishing
          worker output doesn’t match how real world businesses work and
          observational evidence.

   67

          LFC 05.30.14 at 7:02 pm

          The McDonalds training materials state/assume that worker
          productivity is constant, rather than declining with increasing
          worker-count.

          That’s what I took Ackerman to be arguing, but if you read the
          way he phrases that passage it’s not as clear as it might be,
          imo: he refers to “how busy the restaurant is,” which is a
          measure of how many customers are in the place, not how many
          workers, leaving the reader who doesn’t follow the link to infer
          (reasonably enough, i suppose) that there are usu. more workers
          at peak hrs. Anyway, not a big deal.

   68

          TM 05.30.14 at 7:09 pm

          LFC, have a look at the diagram showing Piketty’s estimates for
          r and g, figure 1 in the Krugman review:

          http://www.nybooks.com/articles/archives/2014/may/08/thomas-pike
          tty-new-gilded-age/

          This goes way back, implying that r has been around 5% for
          millennia, which is nonsensical if r is supposed to be a growth
          rate. (*) So yes, Piketty is dealing with centuries. I made this
          very point in an earlier thread
          (http://crookedtimber.org/2014/04/26/how-we-do-intellectual-hist
          ory-at-the-new-york-times/comment-page-9/) you even asked why I
          considered such sustained growth rates impossible and I
          explained it. I would also point out that by Piketty’s argument,
          and given his estimate r – g estimate for the last 20000 years
          (about 4%!) , society should have gotten exponentially more
          unequal since Roman times and up until the early 20th century. A
          scientific theory should be evaluated by comparing its
          predictions with empirical reality and it doesn’t seem that it
          fares well in that test – unless you make a lot of ad-hoc
          adjustments.

          (*) Ignorance of the implications of growth rates is a standard
          characteristic of ALL mainstream economic discourse and the
          Piketty debate is another deeply frustrating case in point
          (http://www.slideshare.net/amenning/growth-in-a-finite-world-sus
          tainability-and-the-exponential-function). Incidentally, George
          Monbiot just published an excellent take-down of the growth
          mantra:
          http://www.monbiot.com/2014/05/27/the-impossibility-of-growth/

          “Let us imagine that in 3030BC the total possessions of the
          people of Egypt filled one cubic metre. Let us propose that
          these possessions grew by 4.5% a year. How big would that stash
          have been by the Battle of Actium in 30BC? … Go on, take a
          guess. Ten times the size of the pyramids? All the sand in the
          Sahara? The Atlantic ocean? The volume of the planet? A little
          more?”

          This is almost the scenario indicated in Piketty’s diagram.

   69

          LFC 05.30.14 at 7:18 pm

          @bob mcmanus 65

          TM’s argument, if I understand it, is that given
          resource/physical/other constraints, g (and therefore r, which
          may outpace g but remains dependent on it to some extent) can’t
          grow exponentially (or even steadily) over a long time period:
          it’s physically impossible, b/c the planet, if not
          environmentally completely collapsed, eventually runs out of
          space (miniaturization and whatever other technological fixes
          notwithstanding).

          For that argument, which TM has made here quite insistently, the
          time period wd seem to be crucial: Is P. talking about centuries
          or decades? If he’s talking about centuries, TM’s argument seems
          to have some force. If decades, not so much. (Tho no doubt TM
          will appear at some pt and tell me I’m full of sh*t and that I
          don’t understand the math or whatever…)

          Your (mcmanus’s) comment is on a somewhat different pt; nothing
          wrong w that of course. But i was spec. trying to address TM’s
          argument. (You (mcmanus) have read the Piketty bk and I haven’t,
          so i assume your not bothering to respond to TM may be an
          indication that you think TM has gotten things wrong. But I’m
          speculating…)

   70

          TM 05.30.14 at 7:18 pm

          LFC, have a look at the diagram showing Piketty’s estimates for
          r and g, figure 1 in the Krugman review:

          http://www.nybooks.com/articles/archives/2014/may/08/thomas-pike
          tty-new-gilded-age/

          This goes way back, implying that r has been around 5% for
          millennia, which is nonsensical if r is supposed to be a growth
          rate. (*) So yes, Piketty is dealing with centuries. I made this
          very point in an earlier thread
          (http://crookedtimber.org/2014/04/26/how-we-do-intellectual-hist
          ory-at-the-new-york-times/comment-page-9/) you even asked why I
          considered such sustained growth rates impossible and I
          explained it. I would also point out that by Piketty’s argument,
          and given his estimate r – g estimate for the last 20000 years
          (about 4%!) , society should have gotten exponentially more
          unequal since Roman times and up until the early 20th century. A
          scientific theory should be evaluated by comparing its
          predictions with empirical reality and it doesn’t seem that it
          fares well in that test – unless you make a lot of ad-hoc
          adjustments.

          (*) Ignorance of the implications of growth rates is a standard
          characteristic of ALL mainstream economic discourse and the
          Piketty debate is another deeply frustrating case in point.
          Incidentally, George Monbiot just published an excellent
          take-down of the growth mantra:
          http://www.monbiot.com/2014/05/27/the-impossibility-of-growth/

          “Let us imagine that in 3030BC the total possessions of the
          people of Egypt filled one cubic metre. Let us propose that
          these possessions grew by 4.5% a year. How big would that stash
          have been by the Battle of Actium in 30BC? … Go on, take a
          guess. Ten times the size of the pyramids? All the sand in the
          Sahara? The Atlantic ocean? The volume of the planet? A little
          more?”

          This is almost the scenario indicated in Piketty’s diagram.

   71

          TM 05.30.14 at 7:21 pm

          Corr: given his r – g estimate for (most of) the last *2000*
          years (about 4%!)

   72

          LFC 05.30.14 at 7:21 pm

          (plus haven’t read whole thread closely, i must confess)

   73

          TM 05.30.14 at 7:36 pm

          Also LFC here’s a quote from Ackerman:

          “Coupled to this is an amazing empirical finding: that the “raw”
          rate of return (this is not Piketty’s term) has in fact always
          stood much higher than the growth rate. *Astoundingly, it’s been
          largely steady for centuries*.”

   74

          LFC 05.30.14 at 7:41 pm

          I happened to read the Monbiot piece (even referred indirectly
          to it at my blog).

          I’ve looked at Fig. 1 in the Krugman piece (reproduced from P’s
          book, presumably).

          I’m going to bow out b/c I remain confused on this pt and I
          don’t think further dialogue here is going to alleviate my
          confusion.

          It is interesting to me though that your argument — which is
          that r>g is either impossible (if r is a “growth rate”) or
          meaningless (if r is not a “growth rate”) doesn’t seem to have
          been made by anyone else. Or perhaps it has been made by someone
          else and I’m unaware of it.

   75

          Bruce Wilder 05.30.14 at 7:46 pm

          I thought the Seth Ackerman piece was excellent.

          I’d be even more emphatic about one of his principal themes:
          administrative hierarchy.

          Production processes are managed by bureaucracies. In a managed
          production process, the wage will be equal to the marginal
          product of labor because management makes it so.

          As Ackerman emphasizes, skyrocketing top executive pay appears
          to have driven both the rise in capital’s share of income, as
          well as had its own effect in driving inequality.

          If technology has an influence, it is the technologies of
          communication and computing, which would seem to reduce the
          resource cost of monitoring and control. (Color me skeptical
          about drawing any linear trend line in these early days — see
          the Snowden thread to see how little we understand.)

          Administrative hierarchies have to eat — they require large
          surpluses of energy — and, contra Tim Worstall — I think we are
          at a resource extraction plateau: peak oil, certainly, but more
          general. And, anything that eats has to do something else, which
          Queen Victoria would prefer I not mention, and we’re running low
          on our capacity in that regard as well.

          I’m not optimistic. The most straightforward interpretation of
          trends, istm, is the emergence of a neo-feudalism, which will
          handle resource constraints by reducing the requirements of the
          excess population, and then, reduce the excess population.

   76

          LFC 05.30.14 at 7:49 pm

          Monbiot’s colorful example doesn’t fit P’s diagram. (1) M. is
          doing a bit of fudging betw economic growth and growth in “total
          possessions,” which is a little different. (2) M’s example
          covers 3000 yrs.

          That said, I thought the Monbiot piece made some
          good/interesting pts.

   77

          TM 05.30.14 at 8:02 pm

          Yes it’s 3000 years instead of 2000. It’s a great illustration
          but has nothing in particular to do with Piketty.

   78

          TM 05.30.14 at 8:24 pm

          Note also that Piketty’s estimates for g make sense: there was
          very little economic growth until the 19th century (of course,
          population growth also was very slow). It truly is amazing that
          nobody else asks the obvious question – how can capital grow at
          4-5% rates when there is almost zero growth in production? And
          also, if r fell so dramatically in the 20th century as a result
          of “exceptional factors” (Ackerman) due to the world wars, why
          didn’t the wars, epidemics and so on in earlier centuries have
          similar effects?

          It seems to me, after reading a whole bunch of Piketty reviews,
          that nobody really analyzes this as a scientific theory to be
          tested. I guess economists just don’t think that way.

   79

          Bruce Wilder 05.30.14 at 9:36 pm

          nobody else asks the obvious question – how can capital grow at
          4-5% rates when there is almost zero growth in production?

          I thought I was asking that question, above. Or, I was making
          the point that it is an obvious question, with an answer that
          tends to upend the neoclassical assumptions.

          Did someone say that capital is growing ad infinitum? That’s no
          part of Piketty’s theses. His r is a rate of return on wealth,
          not a growth rate.

          Piketty imagines that wealth accumulation and slow growth tend
          toward an equilibrium in which wealth claims a large portion of
          income. But, he imagines an equilibrium as the target (though
          not necessarily a target achieved, given wars, epidemics, etc.).

          Formally:
          Define r as the rate of return on capital, s as the savings rate
          and g as the growth rate.
          Define ɑ as the share of capital income in national income
          Define ß as the capital / income ratio.

          Piketty comes up with these two “laws”:

          ɑ = r x β (The share of capital income in national income is
          equal to the average rate of return on capital time the
          capital/income ratio. This is an accounting identity.)

          β = s / g (The capital to income ratio is equal to the savings
          rate divided by the growth rate. This describes a long-term
          tendency, achieved (if at all) only over a period of decades.)

          The second relationship describes the asymptote: what tends to
          happen over a very long period of time: the stock of capital can
          become quite large relative to annual income, and capital claims
          a large share of national income. But, it’s an equlibrium
          result.

   80

          js. 05.30.14 at 9:48 pm

          The Ackerman piece is indeed excellent—thanks to CR for linking
          to it.

          A question for those who’ve finished the Picketty: I’d gotten
          half way through the penultimate chapter (the global tax on
          capital one), and then… well, I effectively lost the book. How
          much am I missing?

   81

          elm 05.30.14 at 10:08 pm

          TM@77

     how can capital grow at 4-5% rates when there is almost zero growth
     in production?

          The factor r is rate or return on capital, not rate of capital
          accumulation/growth. It would mean that (overall) each $100
          worth of capital produces $4-5 in rent/grain/widgets per year.
          Not that each $100 of capital grows to $104-105 per year.

     And also, if r fell so dramatically in the 20th century as a result
     of “exceptional factors” (Ackerman) due to the world wars, why
     didn’t the wars, epidemics and so on in earlier centuries have
     similar effects?

          Ackerman’s piece covers some of that already:

     And that was due to precipitous capital losses on real estate and
     bonds that accompanied strict postwar rent controls and financial
     repression, as well as high taxes and outright physical destruction
     — all exceptional factors in an era of world wars. From now on,
     Piketty argues, capitalism can be expected to slide back toward the
     nineteenth century norm.

          Presumably rent controls didn’t follow on the crusades, nor did
          the English civil war destroy much of the predominant capital at
          the time (farmland).

          WWII did destroy lots of the sorts of capital goods that were
          valuable at the time, such as factories and buildings.

          That said, I’d much prefer to see error bars/confidence
          intervals on Picketty’s data, but that critique isn’t specific
          to Picketty.

          I don’t think that graph is intended to state that in the year
          1033, the rate of return on capital was exactly 4.5%. In fact,
          the data point is labelled as 1000-1500, suggesting that it’s an
          aggregated value, surely estimated, across 500 years.

   82

          Ronan(rf) 05.30.14 at 10:36 pm

          “Presumably rent controls didn’t follow on the crusades, nor did
          the English civil war destroy much of the predominant capital at
          the time (farmland).
          WWII did destroy lots of the sorts of capital goods that were
          valuable at the time, such as factories and building”

          On that, (from a link in Suresh Naidu’s article also in Jacobin)

          http://www.stanford.edu/~scheidel/Leveler.pdf

   83

          A H 05.30.14 at 11:34 pm

          As Bruce Wilder said above, r is a rate of return, it’s not a
          growth rate.

          Piketty claims the economy tends toward a steady state in which
          the growth rate of capital is the same as the growth rate of
          output. This is determined by Piketty’s second “law”.

          As I understand it, the crux of Piketty’s argument about r > g,
          is that if g declines and r does not decline (and savings
          behavoir stays the same), then the steady state will be a much
          higher capital to output ratio than we have now.

   84

          LFC 05.31.14 at 3:36 pm

          TM wrote this @50:

          If r is the return on capital, … then r > g doesn’t really imply
          anything because it is meaningless. g is a growth rate but r is
          not.

          In other words, TM’s position is that it is “meaningless” to
          compare a growth rate (g) to a rate of return (r), or to chart
          one against the other. As far as I can tell, he has not
          explained why he thinks this is meaningless.

   85

          mattski 05.31.14 at 5:07 pm

          I find TM’s argument against long term sustainability of growth
          rates to be absurd. On the one hand, how many arrowheads would
          you trade for an iphone? On the other hand, take a look at the
          changes in the surface of the planet over the last 1000 years
          for example. Roads, bridges, houses, cities, airplanes,
          automobiles, cargo ships, naval fleets, sports stadiums, golf
          courses, rainforests that have been razed…

          For better AND worse, this is the manifestation of our ever
          increasing wealth.

   86

          mattski 05.31.14 at 5:10 pm

          **And as Krugman has suggested, future forms of growth can take
          many divergent forms, even the form of ameliorating
          environmental damage caused by previous forms.

          There aren’t any consistent “units of growth” over time.

   87

          elm 05.31.14 at 5:35 pm

          LFC @ 84: As a very charitable interpretation of TM’s post I
          could agree that those different types of quantities are
          notintrinsically comparable, but economists (including Piketty)
          can use that fact to draw conclusions within the domain of
          economics.

          Summers surely understands the implications (and vigorously
          denies Piketty’s observations for that reason).

          The significance of r>g lies not in pure math, but in its
          implications within economics. The details of that significance
          can be found in the Ackerman piece, Bruce Wilder’s post @79, and
          surely in Pikettys text.

   88

          roger nowosielski 05.31.14 at 10:48 pm

          #57

          Perhaps Corey is right in that Seth Ackerman’s review of
          Piketty’s Capital in “Piketty’s Fair-Weather Friends” is the
          most incisive to-date; which isn’t saying much since most of the
          reviews we’ve been treated to had come from the mainstream. I
          don’t put much credence, btw, in there being a very significant
          difference between the so-called MIT economic model (credited to
          Paul Samuelson and company) and the one which is being endorsed
          by those who subscribe to an alternative, as per the “Cambridge
          capital debate.” And although Ackerman does a pretty credible
          job at elucidating the main issue underlying the Cambridge
          debate controversy – namely, the questionable validity and
          usefulness of marginal utility theories – I’m afraid that simply
          saying that “history and custom, as well as politics, laws and
          struggle, will determine who gets what, [that[ it’s a system of
          grab what you can,” is sufficient to delineate a radically
          different conception of “doing economics” from the mode that’s
          currently in use.

          To be sure, Ackerman starts with an underlying promise: “To a
          remarkable extent for a work of modern economics,” he says,
          “Piketty’s book explores social class in all its rich historical
          dimensions.” We’re led to believe thus that Ackerman is about to
          break new grounds, that the introduction of the social class
          concept and the ensuing struggle will result in a brand-new
          approach to economic analysis, an approach that will surely
          translate to a brand-new conception of the subject matter, a
          brand-new understanding. I’m afraid the results are all but
          disappointing.

          It would appear that “a return to dynastic wealth,” otherwise
          referred to as “patrimonial capitalism,” is Piketty’s main
          concern, in that it “will fatally erode capitalism’s
          legitimacy.” There’s no telling what Piketty’s main concern
          really is, but the question I put: why should it be the
          reviewer’s? As things stand, however, Ackerman, whether
          unwittingly or not, get drawn into this quagmire and volunteers
          a rebuttal. He doesn’t think it’s necessarily so, and the bulk
          of his argument hinges on the presumably new ethos of the new
          “nouveau riche”: in a startling contrast to Veblen’s depiction
          of the privileged class in his time, as a class of leisure, now
          we’re supposed to believe that the present-day would be captains
          of industry, the movers and the shakers, have all of a sudden
          been instilled by their parents with an ethic of virtue, Max
          Weber addition.

          Whether or not you put credence in such anecdotal evidence is
          really beside the point. What is the point, however, is that
          Ackerman considers this little tidbit, accurate or not, as
          reason enough to discount the gravity of the impending crisis
          simply because the offspring of the ruling class happens to
          believe in work ethic and in the American Dream: as though the
          beliefs of the new elite had any impact on how those who happen
          to experience the growing inequality will tend to believe or
          think. High hopes!

          True to form, however, Ackerman is careful to remain
          noncommittal:

          “Just how the spoils of that twentieth-century victory get
          handed down to future generations is a matter that will no doubt
          depend on the multiplicative dynamics of capital in the
          twenty-first century, as Piketty claims. But whether those
          numbers spell a social crisis or just more of the same will
          depend on how the next chapter of the struggle is written.”

          Spoken like a true academic.

   89

          bob mcmanus 05.31.14 at 11:58 pm

          88: as reason enough to discount the gravity of the impending
          crisis simply because the offspring of the ruling class happens
          to believe in work ethic and in the American Dream

          That is not how I read Ackerman’s argument. I read him as saying
          resistance and reform will be made more difficult by of this
          superficial adoption of petit bourgeois values by the elite
          class.

          Which is what we have, even in the early stages, been seeing,
          that financial and economic crises of capitalism are not being
          accompanied by political crises of sufficient intensity and
          class division to create energy for systemic change, and that is
          a problem, and perhaps a dystopian catastrophe.

          Bill Gates and Ophrah Winfrey just don’t look enough like Louis
          XVI and Maria Antoinette to motivate pitchforks and guillotines.
          Doesn’t mean that they aren’t as dangerous and socially
          destructive.

   90

          roger nowosielski 06.01.14 at 2:49 am

          You’re talking then about the uncanny adaptability of capitalism
          to morph itself, even to the point of appearing completely
          innocuous to the very people it harms; and that’s a problem in
          its own right.

          Apropos of Ackerman, however, I’m not quite convince that he’s
          all so concerned about resistence. He still seems to be
          struggling with the idea whether capitalism is/can be a
          meritorious system,

   91

          Rakesh 06.01.14 at 5:20 am

          Piketty criticizes Marx for not using all the available
          statistics to estimate the capital-intesity of firms at his
          time. But of course Marx did not intend his Capital as a study
          of the English capitalism of his time; he intended to lay bare
          the law of motion of capitalism in its ideal average, and used
          data from English capitalism only because it best approximated
          in his time capitalism in its ideal average. Wassily Leontief
          marveled at the accomplishment:

          “However important these technical contributions to the progress
          of economic theory, in the present-day appraisal of Marxian
          achievements they are overshadowed by his brilliant analysis of
          the long-run tendencies of the capitalistic system. The record
          is indeed impressive: increasing concentration of wealth, rapid
          elimination of small and medium-sized enterprise, progressive
          limitation of competition, incessant technological progress
          accompanied by the ever growing importance of fixed capital,
          and, last but not least, the undiminishing amplitude of
          recurrent business cycles — an unsurpassed series of
          prognostications fulfilled, against which modern economic theory
          with all its refinements has little to show”

   92

          Rakesh 06.01.14 at 5:44 am

          James Galbraith argues that Piketty’s r is a statistical
          artifact, and does not indicate the rate of the creation of new
          physical capital.

          JKG: “What is K? For Piketty, K is the financial valuation of
          privately-held capital assets, including land, bonds, stocks and
          other forms of private wealth, such as housing. One may quarrel
          (as I have) with the connection of this value to prior
          definitions of capital, but that is not the issue here.
          Financial valuation (FV) can be rendered as the present value of
          the expected future returns from the ownership of capital
          assets; for this a discount rate is required. Is the discount
          rate the same as r? Not necessarily. Keeping them distinct, we
          have:
          K = FV = Σi [ Ε(Pi)/(1+d)i]

          where Ε indicates an expected value, d is the discount rate and
          (i) is a time subscript.
          Note that FV depends on d. If the discount rate falls, then the
          financial value of the capital stock will rise. Since the
          discount rate bears some relationship to the interest rate, at
          least in equilibrium, FV and therefore r can be pushed around by
          monetary policy, so long as monetary policy can influence
          financial valuations without also affecting current money
          profits. FV also depends on the current expectation of future
          flows of profit income, which are, in part, a psychological
          matter.
          Clearly, this concept of capital bears no relationship to the
          physical construct that normally enters a neoclassical
          production function or the technological view of the
          capital/output ratio. Piketty’s use of “K/Y” as notation is, in
          this respect, non-standard. Still, nothing prevents us from
          measuring r – as Piketty defines it – from the observed profit
          flow and the financial valuation of the capital stock.
          Why, as an historical matter, would r as measured tend to be
          constant over long periods of time? One answer is now obvious:
          the expected stream of future profits at any given time depends
          on current profits. In a boom, things are good and are expected
          to remain so. In a slump, the reverse. P and FV do not always
          move together. But they will more often than not. And so the
          ratio between the two observed variables – which is r — will
          normally not change very much. One can surely find exceptions –
          in the turning points of the business cycle, or when monetary
          policy drives capital valuations out of synch with current
          profits. But Piketty’s approach of calculating decade-by-decade
          averages may wash those out, to some degree.
          What does the long-run constancy of r have to do with savings or
          with the creation of new physical capital? Nothing at all.
          Piketty’s r is basically a weighted average of financial rates
          of return across the yield curve and the risk profile of
          privately-held capital assets. It is the artifact of current
          profits and the effect of discounted profit expectations on
          market values.”

   93

          Val 06.01.14 at 7:41 am

          This is a little bit off topic but (kind of) related, so I hope
          it’s ok to raise here. As several people have noted there is a
          relationship between population growth and economic growth.
          Piketty begins his book by talking about Malthus and the fear of
          over-population in the late 18thC, and he (Piketty) seems to
          accept that rapid growth in population was a ‘new’ phenomenon.

          I’ve read various discussions about historical population growth
          (eg
          http://www.resilience.org/stories/2009-04-20/peak-people-interre
          lationship-between-population-growth-and-energy-resources) and
          often they seem to relate the rapid period of growth since the
          18thC to energy sources. The thing they don’t seem to discuss is
          that mathematically if you had a long period of small net
          population increase you would always eventually get to a point
          where population started to increase more rapidly.

          This could suggest that people have got causation the wrong way
          round – that it wasn’t technology or fuel sources that caused
          population growth, but rather that increasing population made it
          necessary to find new fuel sources, etc.

          As I say bit off-topic I guess, but it’s an interesting question
          (I think) that no-one seems to talk about, so I wondered if
          anyone here could comment?

   94

          roger nowosielski 06.01.14 at 12:42 pm

          @91

          Good point, Rakesh, especially the laws of motion analogy

   95

          J Thomas 06.01.14 at 12:47 pm

          “This could suggest that people have got causation the wrong way
          round – that it wasn’t technology or fuel sources that caused
          population growth, but rather that increasing population made it
          necessary to find new fuel sources, etc.”

          I think they influenced each other.

          I have the impression that from the neolithic on, there was a
          rather high birth rate but the population did not increase all
          that fast. Particularly local famines would cull the population.

          That was true in europe through something like the 1300’s.
          Later, as before but more so, cities were places where surplus
          farmers went to die. The birth rate in cities was below
          replacement, babies were particularly likely to die in cities,
          etc. Epidemics showed up there first and slowly spread to the
          countryside. The population as a whole had high birth rate, low
          population growth.

          New technologies didn’t happen just because the population was
          already high, but to some extent they could only happen with a
          high population. Port cities maybe used to have less famine
          because ships could bring in food relatively fast and cheap,
          even while they also brought in epidemic diseases. But with
          improved transportation we could get more food from the fields
          to the ports, and more food from the ports to the inland
          populations. But a small population can hardly afford improved
          roads, much less railroads.

          Any given skill set would result in some carrying capacity, the
          population would in theory rise to that level and then fluctuate
          around it. But the population kept rising because we kept
          finding ways to let it rise.

          OK, so I’ve presented these ideas without any backing for them,
          and careful research might show that some of them are wrong. I
          hope I’ve at least presented the ideas clearly.

   96

          P O'Neill 06.01.14 at 1:20 pm

          We all need to wait for the definitive take-down of Piketty.

          Jonah Goldberg –

          I spent pretty much all of May working on a very long essay on
          Piketty’s book for Commentary so I can’t get into all of it here

          Link not included in interest of sanity.

   97

          john c. halasz 06.01.14 at 2:40 pm

          @93:

          “This could suggest that people have got causation the wrong way
          round – that it wasn’t technology or fuel sources that caused
          population growth, but rather that increasing population made it
          necessary to find new fuel sources, etc.”

          The trouble with that proposal is that it involves a kind of
          inverted teleology: just because people needed to find new
          energy sources or other means of subsistence, it doesn’t follow
          that the would or could have found them, rather than just
          succumbing to the usual limiting factors, resulting in higher
          mortality rates. (In fact, the Atlantic economy is thought to
          have been running out of wood resources, the main source of
          thermal energy, such that it is sometimes projected by economic
          historians that it would have collapsed within 100 years, due to
          the loss of wood energy supply, had not the industrial turning
          point occurred).

          The problem with mining coal is not that such resources were
          unknown or too limited previously, but that when coal is mined,
          the shaft quickly floods and the water needs to be pumped out in
          order to further mine the coal. Horses turning water-wheel pumps
          were used to do that, but the horses needed to be feed with
          forage crops, so the amount of coal that could be economically
          mined was limited by the implicit trade-off with agricultural
          produce. With the invention of the steam engine, in effect, coal
          could be used to mine coal, (hence early engines were rated by
          the number of horses they could displace), such that a great
          increase in cheaper coal supply became possible. Prior to then,
          the main sources of energy were wood/charcoal, wind, water
          wheels, and, most of all, muscle power, derived from feeding men
          and animals. But with the new availability of a much more
          intense source of energy in larger quantities, improvements in
          metallurgy became possible, leading to improvements in tools and
          the invention of mechanical machinery, etc. As such developments
          diffused outward, the gradually rising productivity of labor
          resulted in increased net output or productive surpluses, which
          then increased the carrying capacity allowing for increased
          population growth.

   98

          john c. halasz 06.01.14 at 3:14 pm

          The Black Death BTW would have contributed mightily not just to
          the demise of serfdom, but to the revival of trade and the
          growth of cities in Europe, since the greatly reduced population
          would have resulted in the shifting of labor from more marginal
          to more fertile lands, thus automatically raising per capita
          productive surpluses, (“the real wage”). Trade itself increases
          productive surpluses by carrying goods from where they are
          naturally plentiful to where they are scarce and vice versa,
          (which is why it occurs), but it is constrained by the given
          level of productive surpluses and faces diminishing returns. But
          no doubt the evolution of forms of business organization in the
          early modern era of mercantile capitalism was a key to
          potentiating the emergence of industrial capitalism.

   99

          geo 06.01.14 at 5:11 pm

          Rakesh @91. Thanks for the Leontiff quote. Do you remember where
          it came from, by any chance?

   100

          Ed Herdman 06.01.14 at 5:16 pm

          @ geo:
          http://www.jstor.org/discover/10.2307/1804482

   101

          J Thomas 06.01.14 at 7:34 pm

          #96

          “We all need to wait for the definitive take-down of Piketty.”

          We also must carefully distinguish between:

          1. An argument can be made that Picketty made methodological
          mistakes so his conclusions are not certain

          versus

          2. More careful analysis of better data shows that Picketty was
          mistaken.

          Those are two very different things. If eventually a new
          analysis is made that gives different results, we must be sure
          to spend as much effort looking for flaws as has been spent
          looking for Picketty flaws.

   102

          J Thomas 06.01.14 at 7:39 pm

          #97 John C. halasz,

          Very well said! You interrelated a lot of important ideas
          clearly.

   103

          adam.smith 06.01.14 at 7:46 pm

          @J Thomas #101
          That was a joke. If you don’t get it, i.e. if you don’t know who
          Jonah Goldberg is, count yourself lucky and try to keep it that
          way. I promise that you’ll be a happier person.

   104

          Bruce Wilder 06.01.14 at 8:13 pm

          Just like we tend to project linear trends forward — even when
          we know perfectly well that they cannot continue indefinitely —
          we tend to look back into the depths of human history and
          pre-history and imagine a foggy sort of homogeneity or
          uniformity — a constancy — that was never the actual experience.

          Population explosions, migrations, famines and massive epidemics
          have punctuated human history, and from the sketchy evidence of
          archaeology and genetics, pre-history.

          You cannot have an urban civilization without an extractable
          agricultural surplus, with which to feed the soldiers, artisans,
          merchants, entertainers and priests. When that surplus becomes
          available, towns and trade tend to quicken, and when it
          disappears, epidemics — and sometimes, collapse — follow. The
          worst epidemics and famine tend to coincide.

          Agricultural productivity is subject to congestion and depletion
          effects, which can set up the conditions to amplify the longer
          population cycles that drive the rise and fall of civilization,
          or to create a pattern of prolonged stagnation with shorter
          cycles of periodic harvest failure and famine.

          As population on the farm increases, the productivity of the
          marginal farmhand on the margins of the fixed allotment of
          natural resource will run into the law of diminishing returns,
          and the available agricultural surplus will decline, and
          sometimes, because of depletion and congestion, the decline is
          very, very sharp. Practices that answer the immediate demand for
          additional food to feed an increasing population, but deplete
          the fertility of the land in the long-term can help create a
          cliff. If the fishermen overfish the pond, a population crash
          for the fish may trigger a similar effect among the fishermen.

          On the other hand, migrations and trade to bring fertile, virgin
          lands under cultivation or an innovation in technique can
          magnify the available surplus, and a virtuous cycle can carry a
          long upswing forward.

          For obvious reasons, there’s a lot of interest in generalizing
          this pattern to energy use.

          From the end of the Dark Age around 800 BC down to Aristotle’s
          day, the Greek population increased by a factor of more than
          ten. Some of this was amplified by use of iron implements and a
          revival of maritime trade — reviving trade from the Black Sea
          and intercourse with the Persians, Solon planting olive
          orchards, that kind of thing. Some of this was accomplished by
          migration and colonization — Sicily must have been incredibly
          fertile land for Magna Graecia.

          The Romans appear to have been well-fed and pretty healthy down
          to Trajan, conquest and commercial expansion making up for a
          surprisingly backward agricultural tech and increasing social
          problems. Roman plumbing made classical Roman cities healthier
          places than the fetid cities of Western Europe well into the
          19th century. The decline in agricultural productivity and trade
          that began in the 2nd century continued for centuries, and
          culminated in the Plague of Justinian, that marked the beginning
          of another Dark Age.

          The discovery of wet rice methods in China, which permitted
          three crops a year, generated a vast surplus and a flowering of
          an urban civilization on a vast scale. Eventually, population
          pressures on the rice paddy choked off much of the surplus, and
          China stagnated well into the 20th century.

          The Medieval Warming combined with technological innovations
          like the heavy plough, a practical horse collar and better crop
          rotation practices, to increase the agricultural surplus
          available in northern and Western Europe. It also triggered the
          Viking migrations and the German migrations to the east. The
          collision of Franks and Vikings in Normandy and Anjou resulted
          in the invention of the motte and bailey fort, and an explosion
          of the military caste carrying that technology outward in the
          Norman conquest of England and Sicily, the Crusades and Frankish
          conquests in the Mediterranean, etc.

          Most of the population increase in the High Middle Ages remained
          on the farm, though there was some revival of cities and trade
          as well as international war for a tiny warrior elite. And, that
          crowding and congestion on the farm, combined with the end of
          the slight climactic warming, to eliminate the surplus, setting
          up the near-starvation conditions that made the Black Death so
          potent a killer.

          The British Agricultural Revolution’s PR emphasizes Turnip
          Townsend, Jethro Tull and all that — improvements in practice.
          Enclosure also served to put a brake on congestion effects, as
          well as create an urban labor force. But, Victorian Britain was
          underfed — the Industrial Revolution was a near-thing, indeed,
          for that reason, and might not have taken place if Britain
          hadn’t been able to expand its reach into North America,
          Australia, South Africa, and the Argentine, and to expel or
          starve to death the Irish peasantry. The French Revolution and
          the revolutions of 1848 were clearly responses to famine or
          near-famine, as well.

          The success of the New Deal in the 1930s was grounded on
          ordering an agricultural revolution with huge increases in
          agricultural surplus — by-products of the Second Industrial
          Revolution innovations — and a migration off the farm.

          (It seems perfectly reasonable to expect a downcycle of a
          century or three in our immediate future.)

   105

          William Timberman 06.01.14 at 8:55 pm

          BW @ 104

          Like reading Gibbon all over again, that was — the deviltry in
          the details, etc., which late industrial and post-industrial
          technology was touted to overcome. Although I never much
          believed in Stewart Brand’s vision, and the back-to-the-land
          nostalgia of my youth, I’ve been equally skeptical about the
          high-tech alternatives — Star-Trek socialism has always seemed
          to me a lot like the Protestant version of heaven I was raised
          on, i.e bloodless and boring.

          Needn’t be so, of course, but I’ve yet to encounter a convincing
          secular version of the biblical stewardship of creation,
          although there’ve been tantalizing hints, from Brautigan’s
          Machines of Loving Grace, to your own speculations voiced from
          time-to-time in previous CT comments threads.

          Even if something comprehensive and deeply pragmatic were to
          emerge, the disgruntled, the enraged, and those bent on revenge
          for their disappointments real and imagined would still remain
          to be convinced. Lots of luck to those who take that as their
          task in life.

   106

          mattski 06.01.14 at 9:10 pm

          @ 103

          See this helpful tutorial.

   107

          Val 06.01.14 at 10:04 pm

          @95, 97, 98 and 104
          Thanks so much for those interesting and informative responses,
          including amazing rapid historical tour @104

          Re the “inverted teleology” (@ 97), I don’t think it’s that so
          much, more that people don’t tend to take into account the
          mathematical inevitability (as it seems) that at some point a
          small natural increase will turn into a rapid natural increase,
          all else being equal. But of course all else isn’t equal, as
          Bruce Wilder says, and what you actually get seem to be kinds of
          booms and busts of population. It’s possible of course that we
          will see (not literally, but our descendants) a bust in coming
          centuries, but not necessarily brought about by famine etc in
          this case, rather the deliberate lowering of fertility that
          accompanies prosperity, which I guess could also have the same
          characteristics of a small slow decline inevitably leading at
          some point to a rapid decline, mathematically.

          I originally studied maternity in my postgraduate history
          studies, and developed an interest in demography – plus a
          realisation that it’s an area where misunderstandings are
          widespread (don’t get me started on life expectancy), I guess
          because it seems like common sense, when it’s actually very
          complicated. However my historical studies (post school) have
          all been modern, so I don’t know much about earlier periods (and
          haven’t much time to read due to PhD being on other things –
          though can always find time for digressions like this!). But
          this is fascinating stuff.

          On the subject, I’m interested in how economists are thinking
          about the effects of the predicted population stabilisation and
          start of the decline this century? Surely that’s a ‘post growth’
          scenario (though climate change should cause that anyway)? Or
          maybe that’s a topic for another thread, if any CT contributors
          happen to be interested?

   108

          Val 06.01.14 at 10:26 pm

          And of course I’m not forgetting (though I seem to) that what
          happens in coming centuries may be chaos, if we don’t get our
          act together on climate change.

          A seductive thing about climate change is that the ‘warm period’
          which many of us seem to be experiencing at present is actually
          quite pleasant – the brief earlier burst of heatwaves and fires
          (which I believe you are already having in parts of the US) all
          but forgotten in the extended mild autumn we are having here in
          southern Australia. But it’s becoming unseasonable – starting to
          feel wrong.

   109

          Bruce Wilder 06.01.14 at 11:21 pm

          Rakesh @ 92

          Interesting, but I cannot help thinking Galbraith seems to be
          missing a bet here. Literally.

          Terming “r” an artifact makes it seem like putting it into the
          context of the business / financial cycle somehow renders it
          meaningless, but the financial cycle is how financial wealth
          works in a way that concentrates wealth and keeps r elevated
          above g over long periods.

          Financial wealth is insurance, and the financial cycle is
          uncertainty in action. Financial wealth can earn a return as
          insurance, quite apart from the process of forming synthetic
          factors of production (“physical” capital). Owning rent-earning
          factors, like land or some kind of business monopoly, gives the
          owner a capacity to absorb risk, which is valuable as wealth,
          but that value is quite distinct from the value of produced
          goods.

          In the rough-and-tumble of business life over business cycles,
          ordinary abrasion is going to differentially reduce the wealth
          of those who have too little, for whom critical setbacks leave
          permanent marks, and transfer that wealth to those with a
          surplus capacity to absorb risk.

          The apparent stability of r over the business cycle is no mere
          artifact; it is literally how the system works. It is why the
          rich do not go always go down with the sinking ship of their
          original big win — the financial system allows them to make
          money from having money and power, and not just from producing
          goods, like the rest of us.

   110

          Rakesh 06.02.14 at 1:18 am

          Interesting point, Bruce; and I’ll try to reply later. But
          Galbraith is right that Piketty’s capital is defined in term of
          financial valuation, and includes what have not been
          conventionally understood as productive assets; and what
          Galbraith says is consistent with Robert Rowthorn’s conclusion:

          “Piketty argues that the higher income share of wealth-owners is
          due to an increase in the capital-output ratio resulting from a
          high rate of capital accumulation. The evidence suggests just
          the contrary. The capital-output ratio, as conventionally
          measured has either fallen or been constant in recent decades.
          The apparent increase in the capital-output ratio identified by
          Piketty is a valuation effect reflecting a disproportionate
          increase in the market value of certain real assets. A more
          plausible explanation for the increased income share of
          wealth-owners is an unduly low rate of investment in real
          capital. These alternative explanations may have distinct policy
          implications which it is beyond the scope of this paper to
          explore.”

   111

          Rakesh 06.02.14 at 1:20 am

          Quickly on population and coal. It would be helpful to consult
          Robert C. Allen. As I remember it, his argument is that growth
          of international trade =>high wages=>population growth.
          Then a growing population with high wages in England made it
          economical to replace labor with capital and that led to demand
          for coal, which could be met cheaply due to the geographic good
          luck of well-placed coal deposits in England.

   112

          Rakesh 06.02.14 at 1:23 am

          On another thread it was mentioned that defendants now have to
          pay for their own defense. Prisoners sometimes have been billed
          for the costs of their imprisonment, and after their release
          debt collection agencies have added collection fees to these
          incurred charges. In Kafkaesque fashion ex-felons have then even
          been imprisoned for failure to pay these costs. At least that is
          what I understood from a public defender.

   113

          Rakesh 06.02.14 at 1:37 am

          Quickly again. I am just not convinced that the return of
          patrimonial capitalism as a threat to meritocratic ideology
          captures our moment better than many other characterizations of
          our period, such as the return of Manchester capitalism as
          evidenced by industrial unrest in China and elsewhere; or the
          emergence of unsustainable capitalism; or the return of
          primitive accumulation (given land grabs for EPZ’s and resource
          extraction); or the persistence of casino capitalism.
          Why the threat of patrimonial capitalism has become so salient
          seems to be something of a sociological question. Perhaps this
          Foucauldian study of the rich has provoked some resistance, as
          the OP says; but it has also become an international sensation,
          and perhaps it is because it is the kind of conversation that
          well-situated people are willing to engage in.

   114

          geo 06.02.14 at 1:54 am

          WT@105: I’ve yet to encounter a convincing secular version of
          the biblical stewardship of creation

          Try Ernest Callenbach’s Ecotopia.

   115

          LFC 06.02.14 at 2:29 am

          Rakesh @112:
          In Kafkaesque fashion ex-felons have then even been imprisoned
          for failure to pay these costs.

          Off topic, but I doubt that imprisonment for debt exists
          anywhere today, at least not in the ‘developed’ world.

   116

          LFC 06.02.14 at 2:31 am

          Unless perhaps somehow it’s squeezed under the label of contempt
          of court; still, seems unlikely.

   117

          Rakesh 06.02.14 at 2:59 am

          @116
          http://nation.time.com/2013/08/21/welcome-to-prison-will-you-be-
          paying-cash-or-credit/

   118

          Rakesh 06.02.14 at 3:02 am

          Quickly again. I am just not convinced that the return of
          patrimonial capitalism as a threat to meritocratic ideology
          captures our moment better than many other characterizations of
          our period, such as the return of Manchester capitalism as
          evidenced by industrial unrest in China and elsewhere; or the
          emergence of unsustainable capitalism; or the return of
          primitive accumulation (given land grabs for EPZ’s and resource
          extraction); or the persistence of casino capitalism.
          Why the threat of patrimonial capitalism has become so salient
          seems to be something of a sociological question. Perhaps this
          Foucauldian study of the rich has provoked some resistance, as
          the OP says; but it has also become an international sensation,
          and perhaps it is because it is the kind of conversation that
          well-situated people are willing to engage in.
          All that said, see the very interesting debate between Debraj
          Ray and Branko Milanovic on Piketty’s book.

   119

          William Timberman 06.02.14 at 3:32 am

          geo @ 113

          Thanks, I’ll give it a try. For all sorts of reasons, largely
          originating, I suspect, in an essentially egotistical desire on
          my part not to be hoodwinked, I’ve always thought Philip K. Dick
          and Orwell more convincing futurologists than any of the grand
          optimists like Huxley or Gerard K. O’Neill.

          In one of life’s little ironies, I wound up retired in a small
          town in AZ surrounded by slag heaps from a defunct copper
          smelter only 25 miles or so from Soleri’s Arcosanti. I’d admired
          Soleri’s vision, if not his skills as an engineer or politician,
          since I was in my twenties, and still keep a copy of Etica e
          Invenzione Urbana close at hand for a little light in moments of
          darkness. Arcosanti itself, when I was finally able to visit it,
          reminded me of something like the ruins of the Forum Romanum as
          occupied by an encampment of eager flower children. I don’t know
          what I expected, really, but his core idea, that of reducing our
          industrial footprint by more intelligent urbanization, while at
          the same time recovering or re-inventing the lost virtues of
          village culture, had always appealed to me. Discovering
          first-hand that he was a better bellwright than architect was a
          more than a little disappointing. I still have great affection
          for the man and his work, of course, but both feel less like a
          path to the future to me now than a not altogether commendable
          nostalgia for my own youth.

   120

          JanieM 06.02.14 at 3:42 am

          @115

          https://www.wsws.org/en/articles/2010/07/debt-j16.html

          http://thinkprogress.org/justice/2011/12/13/388303/the-return-of
          -debtors-prisons-thousands-of-americans-jailed-for-not-paying-th
          eir-bills/

   121

          Bruce Wilder 06.02.14 at 5:12 am

          Rakesh @ 110: Galbraith is right that Piketty’s capital is
          defined in term of financial valuation, and includes what have
          not been conventionally understood as productive assets

          Yes.

          Piketty is confronting theory with data. And, it is not good
          news for a theory, which has tried to identify wealth
          accumulation with productive capital formation.

   122

          Rakesh 06.02.14 at 6:50 am

          Perhaps not good news for neo-classical theory
          http://glineq.blogspot.fr

   123

          Bruce Wilder 06.02.14 at 7:15 am

          Perhaps not. (hoping, anyway)

   124

          gaddeswarup 06.02.14 at 9:07 am

          Steve Roth on Seth Ackerman review
          http://angrybearblog.com/2014/05/wealth-is-not-capital-the-brill
          iant-seth-ackerman-explains-it-all-4-u.html

   125

          LFC 06.02.14 at 3:11 pm

          Janie M
          “the return of debtors’ prisons”

          ok, this part of the title is enough to persuade me I was,
          apparently, wrong

   126

          TM 06.02.14 at 4:11 pm

          elm 81: You should read the whole back story. I have pointed out
          several times that r is not *defined* as a growth rate but
          everybody treats it like one. Because if it’s not a growth rate,
          then the difference r-g is a meaningless artifact. There is no
          reason why the difference between the rate of *return* on
          capital and the rate of *growth* of GDP would have anything
          meaningful to say about the economy. The argument why r>g is
          meaningful has been presented as follows: If capital grows
          faster than the overall economy, then capital income as a share
          of the economic product must increase. This would be correct
          *if* r is assumed to be a growth rate but it breaks down
          otherwise.

          “I don’t think that graph is intended to state that in the year
          1033, the rate of return on capital was exactly 4.5%. In fact,
          the data point is labelled as 1000-1500, suggesting that it’s an
          aggregated value, surely estimated, across 500 years.”

          How do you think did they define, let alone estimate the
          “aggregate” “rate of return” on capital from 1000-1500? Do you
          even have a concept of what that would mean and how it could be
          measured? If r is *not* a growth rate, as you and I agree, then
          it’s not clear at all what an “aggregate rate of return on
          capital” would even mean. If it were a growth rate, it would be
          crystal clear: it would mean that capital multiplied by a
          *factor* of exp(500*.045)=5.9 billion. I hope we all agree that
          there is no way that that would make sense.

          What is meant is probably an average, not an aggregate. Let’s
          briefly reflect on the terminology “return on capital”. What was
          “capital” at the time was land. Even using that terminology of
          “return on capital” (rather than land rent) for pre-industrial
          feudal society is very dubious. There is a reason why Karl Marx
          identified capitalism as a recent economic innovation, entirely
          different from feudalism. Later, mainstream economists started
          pretending that there was nothing special about capitalism, that
          capitalism had always been around, almost a part of the order of
          nature. Piketty seems to embrace that view, suggesting that
          there hardly was any difference between the 12th and the 18th
          century. After all, in his framework, capitalism is almost
          entirely explained by two numbers, r and g, and those hardly
          changed between the Roman empire to 1820, and moreover,
          according to Piketty, we are heading back to r and g values
          resembling feudalism. And people are swallowing such nonsense
          wholesale? Excuse me people. I’m not gonna give Piketty’s
          confused theories a pass just because I agree with some of his
          conclusions, and neither should you.

   127

          TM 06.02.14 at 4:18 pm

          mattski 85:

          Yours is a tired old argument based on a fantasy, totally bereft
          of any actual evidence. Again I recommend Monbiot
          (http://www.monbiot.com/2014/05/27/the-impossibility-of-growth/)
          for a brief take-down.

          My own, longer answer is here, and I encourage you to actually
          look at some numbers and do some calculations before continuing
          this discussion.

          http://www.slideshare.net/amenning/growth-in-a-finite-world-sust
          ainability-and-the-exponential-function
          http://www.slideshare.net/amenning/exponential-growth-casestudie
          s

   128

          TM 06.02.14 at 4:54 pm

          Val 93: By current estimates, average global population growth
          before about 1750 never exceeded 0.2%. Growth rates started to
          heat up only during industrialization. You are correct of course
          that even a small fractional increase adds up. Population
          increased from 500 million by 1500 to 800 million by 1750. It
          isn’t obvious to me why the latter figure, but not the former,
          should have created a population pressure that ultimately led to
          a fossil fuel powered industrialization. It might be more
          appropriate however to look at the demographic development of
          individual countries, which I haven’t. The conquest of America
          and introduction of the potato in Europe fueled demographic
          change, which probably contributed to creating the conditions
          for industrialization by providing a growing work force not
          needed in agriculture. So in that sense I think you have a
          point. But there is no way population growth could have
          accelerated as much as it did without coal-fueled
          industrialization.

   129

          TM 06.02.14 at 5:14 pm

          And also, mattski 85: by all estimates (including those in
          Piketty’s the famous r-g graph,
          http://assets.nybooks.com/media/graphics/chart/image/krugman_3-0
          50814.png), economic growth has been very slow for most of
          history, a fraction of 1% at best until 1750 (Brad DeLong even
          attempted to estimate “GDP” back in prehistoric times, which I
          think is absurd but of course it confirms that by standard
          definitions, there has been very little “economic growth” before
          industrial capitalism). So economic growth is really a recent
          phenomenon which has been going on only for a few hundred years.
          Nobody disputes that for a time period on that order (but not
          “over the last 1000 years”, as you imply), and starting from a
          low level, growth rates of 2-4% have been observed. It doesn’t
          follow, and is very poor thinking to assume, that trends
          observed in the recent past can, let alone must, go on forever.

   130

          roy belmont 06.02.14 at 5:52 pm

          LFC at 3:11 pm:

          It isn’t just the debtor snare – the existential cannibal
          doo-wop of having to literally pay money for a crime you
          committed because of not having money, or go to jail and owe
          money for going to jail – the “privatization” of US
          incarceration mechanisms, has resulted in virtual enslavement
          for many of the incarcerated.
          Prisons are now being run on the business model. Return to the
          investors. Product. Legal protections. Lobbyists.
          And a big fat check from the government for every filled bed in
          your institution.
          And it’s private. Meaning you don’t really get to see what’s
          going on in there unless someone makes a big stink. And even
          then.
          The stats on imprisonment place America on another, more hellish
          planet as far as prisoners per capita. And what’s happening to
          them inside is socially invisible. Mainstream journalism won’t
          touch it.
          No privacy in there, no privacy out here for most of us now, but
          the scum-sucking greedheads who run the US prison industry get
          all the privacy they want.

          Nice, if you’re a scum-sucking greedhead.

   131

          Bruce Wilder 06.02.14 at 5:57 pm

          TM @ 128, 129: average global population growth before about
          1750 never exceeded 0.2% . . . economic growth has been very
          slow for most of history, a fraction of 1% at best until 1750 .
          . . there has been very little “economic growth” before
          industrial capitalism

          I refer you to my comment @ 104, particularly the first
          paragraph.

          TM @ 126: if it’s not a growth rate, then the difference r-g is
          a meaningless artifact.

          I refer you to my comment @ 76.

          Piketty is focused on what limits the share of total annual
          income flowing to wealth claims, and what limits the
          concentration of those wealth claims. If you want to be dramatic
          about it — what share of national income goes to people who own
          for a living, as opposed to those who work for a living.

          Piketty says that in the limit, the share of capital income in
          national income is equal to the average rate of return on
          capital times the savings rate, all divided by the growth rate.

          The point being, that when the growth rate is less than the rate
          of return — g g, the story is quite different.

   132

          Bruce Wilder 06.02.14 at 6:09 pm

          Something got badly scrambled in transmission in my comment @
          131 Maybe a less-than sign got misread as HTML?

          I append:

          When the rate of return is equal to the growth rate, then in the
          limit, the share of capital income in total or national income
          will approach the savings rate. That is, people will come to
          balance savings with dis-savings while moving along a steady
          growth path.

          If the growth rate is less than the rate of return, then, in the
          limit, the share of national income going to wealth claims can
          become much larger.

   133

          roy belmont 06.02.14 at 6:27 pm

          TM:

          …there is no way population growth could have accelerated as
          much as it did without coal-fueled industrialization.

          Medical science had a part in that too didn’t it? Coming right
          along parallel to the exponentiating industrial.
          So that not only were there more jobs and more jobs coming all
          the time, there were suddenly more and more hands for that work,
          and more coming as well.

          I know the trope of birth reduction after stability, the idea
          that women who have reproductive control have fewer children,
          and when life expectancy increases the birth rate will
          eventually decline.
          But you have that initial bubble of human profusion enabled by
          science – steam, doctors! – and then this odd but tacitly
          accepted idea that everyone who’s born has the right to be, as
          long as they’re human that is.

          The bounce is the 19th c. and its rationoid Euro-American
          eugenicists, leading to some pretty arcane shit in the early
          20th and then of course the German National Socialists and their
          quaint notions of racial itemizing and hierarchical
          distinctions.

          The tension between those two things – everybody gets to be v.
          only the qualified do – is losing its abstract air now.
          Thus “austerity uber alles”. Thus the prison system, the growth
          of inequality, the idiots standing on the even more idiotic and
          proclaiming their superiority to the world.

          What I’m suggesting is what I heard Ken Kesey say in 1974 – that
          the noise of anti-population growth (which is the same noise as
          anti-economic growth), sensible as it is, needs to be modulated
          by some higher goals than simple reduction of growth itself,
          because the thing we’re yelling at won’t go quietly away and
          shrink down, and if we goad it into some sort of forced return
          to sensible practice – trimming, slowing down, letting go of
          delusions of unlimited gratification – it will want to get rid
          of us first, because we’re the irritant, the goads, the
          gadflies.
          It’s a conundrum, filled with paradox.
          And a ticking time bomb more scary than any crap movie plot.

   134

          TM 06.02.14 at 7:13 pm

          “Piketty says that in the limit, the share of capital income in
          national income is equal to the average rate of return on
          capital times the savings rate, all divided by the growth rate.”

          Ok I see that your post at 79 (not 76) presents these
          relationships. The first one, ɑ = r x β, is as you say true by
          definition. The second, β = s / g, you describe as a “long-term
          tendency” under “equilibrium” conditions. Of course, it’s hard
          to see how an equilibrium can be reached when inequality keeps
          increasing. Crucially, the savings rate s is a prominent part of
          the framework but nobody seems to have even mentioned it except
          for your 79 and 131 (and none of the reviews I have read,
          including Kruman’s, except for Ackerman, see (*)). A low savings
          rate would keep inequality low even with high r, and conversely,
          a high savings rate would increase inequality even with low r.

          Even taking these “laws” at face value, it remains the case that
          r-g in itself doesn’t determine the inequality trajectory. In
          fact, given Piketty’s framework (ɑ=r*s/g), it doesn’t even
          matter whether r>g. What matters is whether r, g and s are
          currently increasing or decreasing. That simply follows from the
          mathematical relationships. Would you disagree with that
          deduction?

          I guess part of my skepticism has to do with the s in the
          nominator. It means that a sure-fire way to reduce inequality
          would be to stop investing (s=0). Really??? Another problem I
          have is that there is no distinction between privately and
          publicly owned capital and no mention whatsoever of public
          investment. I reiterate my remark at 50: “What we have seen is
          not a fantastic rate of investment but the opposite:
          deinvestment, deterioration and deindustrialization. I don’t see
          any evidence for the theory that rising inequality has been
          driven by capital investment – the opposite is true!”

          (*) Ackerman does briefly address savings rates. “… the gap
          between r and g will widen due to a fall in the growth rate (g)…
          The problem is that if growth slows while the rate of saving
          (i.e. investment) stays constant [sic!], capital will start
          accumulating faster than output is rising, meaning the measured
          capital-output ratio will increase.” This is not a consequence
          of a “widening gap” between r and g; rather it is simply a
          consequence of declining g with r and s remaining constant. What
          is not explained is why r and s would stay constant when g
          falls.

   135

          TM 06.02.14 at 7:15 pm

          [That was a response to BW 131]

   136

          TM 06.02.14 at 7:18 pm

          [Oops, numerator not "nominator".]

   137

          Bruce Wilder 06.02.14 at 8:01 pm

          What is not explained is why r and s would stay constant when g
          falls.

          Yes, he’s basically asserting as a matter of fact that they tend
          not to fall with growth.

          He’s up against a conventional view among economists that is
          unconcerned with facts.
          http://www.voxeu.org/article/piketty-s-second-law-capitalism-vs-
          standard-macro-theory

   138

          TM 06.02.14 at 9:05 pm

          Thanks for the ref. Let’s agree then that the Piketty model
          makes a lot of implicit assumptions that are not empirically
          tested (to put it mildly). The “standard” macro theory also
          makes assumptions that may not be valid (in this case, constant
          gross investment). I’m not committed to these assumptions
          either. I am just very frustrated with economists claiming this
          or that follows from their “elegant” mathematical model when in
          fact it’s not an implication of the model but of unjustified
          assumptions (the model itself may also be problematic of
          course). I make no bones of my contention that economic growth
          must necessarily slow down and eventually give way to a
          steady-state economy (defined as population stabilization
          together with a roughly constant capital stock and roughly
          constant material production and throughput, while of course
          allowing for qualitative development). The suggestion that a
          steady-state economy implies increasing inequality, “because of
          r>g”, is wrong and dangerous. To the contrary, inequality has
          been rising for decades despite high (by historic standards)
          rates of GDP growth. It’s time to put a final stake through the
          GDP zombie, the oldest and worst of all economic undead.

   139

          Val 06.02.14 at 9:13 pm

          TM @ 128
          The point I think you (and maybe some others) are missing is
          that even a very small growth rate, if it continues long enough,
          will eventually become exponential. That’s the mathematical
          inevitability part. You don’t have to have an enabler for that,
          you just have to have a lack of constraints. Of course in
          reality you do have constraints on what population could be
          supported at different times as Bruce Wilder said, and you can
          also get exponential declines (therefore, booms and busts as I
          put it earlier).

          You may not be exactly saying this, but the ‘humans discovered
          coal and then the population grew exponentially’ theory is
          clearly an oversimplification.

   140

          Matt 06.02.14 at 9:29 pm

          I don’t understand “even a very small growth rate, if it
          continues long enough, will eventually become exponential.” A
          constant positive-percentage growth rate is always exponential
          no matter how small the percentage. A constant-addition growth
          rate is always sub-exponential no matter how large the addition.

   141

          Val 06.02.14 at 9:34 pm

          And just for further info, apparently the world’s growth rate
          peaked in about 1960s and is now slowing down. In most wealthy
          countries the rate of natural population increase is now below
          replacement rate (which is about 2.1 children per woman).

          The expectation is that that pattern will continue until the
          natural increase rate of the world is below replacement rate (ie
          negative population growth rate). The world population is
          expected to peak this century and then start to decline.

          Btw it’s on page 3 that Piketty says that the “sustained
          demographic growth” that people were seeing in the late 18thC
          and 19thC was “a previously unknown phenomenon”. I don’t know
          whether it has any impact on his overall thesis, because I
          haven’t got much further than that yet! But I do think it may be
          oversimplification of the sort Bruce Wilder identified (for some
          reason my iPad is not letting me cut and paste, but that really
          nice intro at 104 about the imagined “foggy sort of homogeneity”
          of the past).

          I guess it depends how you define “sustained”. If it ends this
          century, will that be a longer period of population growth than
          there ever has been before? Perhaps Bruce Wilder knows.

   142

          Val 06.02.14 at 9:39 pm

          Matt @ 140
          Aren’t population growth rates normally expressed as
          percentages? I just mean that if it’s a very small growth rate,
          it will take a long time (historically) before the curve starts
          to shoot up.

   143

          TM 06.02.14 at 9:56 pm

          Val 139: “The point I think you (and maybe some others) are
          missing is that even a very small growth rate, if it continues
          long enough, will eventually become exponential.”

          Maybe I’m missing that point, because it’s nonsensical. Growth
          by a constant fractional growth rate, however small, IS
          exponential. It doesn’t “become” exponential. You should review
          the math of exponential growth
          (http://www.slideshare.net/amenning/exponential-growthmath).

          What is so special about population growth since 1750 is that
          growth rates have *accelerated* so much, from 0.2% p.a. to 2%
          p.a. by 1970.

          “You may not be exactly saying this, but the ‘humans discovered
          coal and then the population grew exponentially’ theory is
          clearly an oversimplification.

          Actually it would be wrong because population growth from about
          1750 up to 1970 has been *hyper-exponential*. Since about 1970,
          it has slowed to linear.
          (http://www.slideshare.net/amenning/growth-in-a-finite-world-sus
          tainability-and-the-exponential-function)

   144

          Bruce Wilder 06.02.14 at 10:01 pm

          TM: Let’s agree then that the Piketty model makes a lot of
          implicit assumptions that are not empirically tested (to put it
          mildly).

          Let’s not agree to that! Piketty is lousy with facts.

          TM: The suggestion that a steady-state economy implies
          increasing inequality, “because of r>g”, is wrong and dangerous.

          Piketty warns that a conventionally capitalist steady-state or
          low-growth economy, in the absence of countervailing policy,
          implies increasing inequality.

          He’s not calling for faster growth. He’s calling for policy —
          taxes — to curb the excessive accumulation and concentration of
          private wealth in the presence of falling growth.

          I understand if you’re concerned about ill-considered calls for
          renewed economic growth, but, otherwise, I’m at a lost to
          understand your concern.

   145

          TM 06.02.14 at 10:03 pm

          “if it’s a very small growth rate, it will take a long time
          (historically) before the curve starts to shoot up.”

          Forgive me for dwelling on this but it’s a teaching opportunity
          ;-)
          The exponential growth curve actually looks exactly the same (up
          to a scale factor) regardless of the value of the growth rate
          and regardless of where you look. There is no point where “the
          curve starts to shoot up”. The exponential is sometimes taught
          as a “J-shaped” curve. That’s completely wrong. There is no kink
          in the curve, it’s totally uniform. Mathematically it’s one of
          the most beautiful structures imaginable.

   146

          Peter T 06.02.14 at 11:46 pm

          Piketty’s r>g seems to me not so much a law of capitalism as a
          straightforward statement that, in any system that allows
          secondary claims on income, ordinarily the share of income going
          to those claims will rise until it hits a political or other
          limit. In other words, income shares between classes are
          politically determined. This much any good historian could have
          remarked as commonplace, but economists seem to need it spelled
          out in simple terms, repeatedly.

          Whether those claims take the form of rents, interest, taxes,
          labour or whatever is a contingent matter (as Piketty
          acknowledges). If the top 10% prefer to take their cut as
          “wages”, well, there is precedent for that – it need not, and
          usually does not, imply that they are “earned” in the ordinary
          sense of the term. Of Jane Austen’s brothers, two went into the
          navy and two into the church. The incomes they drew were nearly
          as much inherited as money in the funds.

   147

          Val 06.03.14 at 1:00 am

          TM @ 145

          Forgive me for dwelling on this but it seems to me there might
          be a bit of mansplaining going on here, rather than a “teaching
          opportunity”.

          I apologise if I have the terminology wrong, it’s been a long
          time since I formally studied maths apart from statistics.
          However it seems pretty clear to me that you are talking about
          the growth curve and I am talking about the total population.
          Obviously the shape of the curve you get depends what you are
          plotting. If you have a fairly large population and a fairly
          small rate of increase, and you plot the total population over
          time, I think what you will get is the kind of J curve I am
          talking about, with a long very gentle curve that ultimately
          shoots up sharply.

          If I’m actually wrong please feel free to demonstrate.

   148

          Val 06.03.14 at 1:17 am

          TM @ 145

          It’s this thing, whatever you want to call it (J curve seems to
          often be used but I don’t know that it’s a good name)
          http://www2.estrellamountain.edu/faculty/farabee/BIOBK/biobookpo
          pecol.html
          (scroll down a bit to graphs)

          - if the growth rate (birth rate minus death rate) is small
          compared to the population, the part of the curve from 0 to
          where the steep upward climb begins will be correspondingly long
          and gradual, but the steep upward curve will still happen at
          some point.

          Of course the ‘exponential/J curve/whatever you want to call it’
          pattern is theoretical, as I’ve said.

          Anyway I think that really is enough about this because it is
          tangential to the post and the main thread. Maybe the
          significance of it might be explored at some other time.

   149

          Matt 06.03.14 at 1:31 am

          I think I see what you mean, that small constant percentage
          increases eventually grow the base to the point where there are
          large absolute increases in each generation. But I don’t think
          that actually fits for historical human population growth. If
          there were only 10,000 humans alive after the Toba catastrophe
          70,000 years ago, and human population growth maintained an
          extremely low rate of 0.05% annually, human population should
          have reached 1 billion around 28000 years ago. It actually
          reached 1 billion only ~200 years ago.

   150

          Val 06.03.14 at 5:34 am

          Matt @ 149
          You should read Bruce Wilder’s comment at 104. There can be
          sharp increases and sharp declines, it works both ways.

          I might try to write something about this on my blog sometime
          because it’s obviously interesting, but tangential here as I
          said, so no more from me here.

   151

          Ze Kraggash 06.03.14 at 7:47 am

          What Peter T 146 said, only even more trivial: the rich are
          getting richer, both absolutely and relatively. Which has little
          to do with equations, and everything with political power. Give
          me enough power, and I’ll pump ‘r’ as high as I want, restrained
          only by the prospect of a pitchfork-wielding mob showing up in
          front of my castle.

   152

          J Thomas 06.03.14 at 1:16 pm

          VAL @ 147, 148

          He actually does have an important mathematical point.

          Putting that aside for the moment, you have a point that the
          math is simple and the reality is complicated. The point of the
          math is that it makes clear a simple idea that’s worth
          understanding thoroughly. The simple idea can be applied to a
          whole lot of things, except of course you have to pay attention
          to the complications each time as well as the simple thing which
          is an important part.

          The simple idea is about things that change by a fraction of
          themselves. Compound interest. Bacteria growing in culture
          medium or in a gallon of milk left out. Blog comments on a
          controversial topic. When each comment gets two responses,
          there’s a sort of explosion.

          You can get absolute explosions even when the relative increase
          doesn’t change. It’s a useful idea that’s worth careful study.

          But of course in reality exponential growth does not continue
          unchanged for a long time. If nothing else, the growth itself
          will change conditions. Cancer cells might grow exponentially
          but then they kill you. Dynamite, one molecule exploding sets
          off more than one more, but after awhile the explosion runs out
          of dynamite. The bacteria in the milk jug starve. Etc.

          Very often the actual curve is more like the second one in the
          link you gave. It can look like two J curves fit together (but
          they can have very different slopes). It looks exponential for
          awhile, and then as things change it levels off.

          We know that human beings have not really had a constant
          population growth rate, not for long. We expand into new
          ecosystems, and then for any given technology we reach an
          equilibrium where the population can’t expand further. Then
          maybe we get a new technology that lets the population expand
          more.

          Before the Black Death the population in europe was expanding
          slowly. People had lots of babies. Poor people’s babies died.
          Rich people’s babies died sometimes. Afterward the population
          expanded fast. Maybe each woman had the same number of babies on
          average, but more of them survived because times were better.

          Population rises when new technology allows it, and stagnates
          until a new opportunity comes along.

          First world nations have stagnant population growth because it’s
          very expensive for wage-slave families to raise children to be
          wage-slaves. They could have more children, but the extra would
          have to become something else and how would they live? So they
          have two children, or one, and they vaguely feel like failures
          because they don’t want to recognize that in the game of
          population ecology they are at best barely breaking even.

          We can apply the same sort of thing to Picketty. Of course we
          don’t have constant r and constant g. The world is complicated.
          We do however have a lot of rich people who do not invest more
          in productive businesses as they get richer. Picketty’s simple
          idea suggests that this is true and maybe inevitably true, and
          he suggests why this is a problem and he suggests simple
          solutions.

          It’s trivial to argue that he does not tell the whole story. It
          would be complicated to collect real data to support a different
          story. In the meantime we can discuss whether he’s right that
          there is a problem, and if so what solutions seem plausible.

   153

          Mike Furlan 06.03.14 at 2:18 pm

          So far absent from the discussion is N. Taleb’s criticism:

          “His measure of inequality could be inconsistent across samples,
          so under fat tails, with his measure,
          Average(Inequality(A)+Inequality(B)) < Inequality(A+B). It can
          rise over time as populations get larger (under fat tails), or
          rise simply from model error or breadth of the measurement. "

          Note 156

          http://www.fooledbyrandomness.com/notebook.htm

   154

          J Thomas 06.03.14 at 3:35 pm

          N. Taleb’s criticism:

          “His measure of inequality could be inconsistent across samples,
          so under fat tails, with his measure,
          Average(Inequality(A)+Inequality(B)) < Inequality(A+B). It can
          rise over time as populations get larger (under fat tails), or
          rise simply from model error or breadth of the measurement. "

          Does N. Taleb have evidence about the question whether this is a
          fat-tail distribution or not?

          You can toss out almost any statistical conclusion if people
          will let you assume that the tails are fat enough that their
          data is wrong. Unless, of course, you actually look at the data
          and see how it is distributed.

          But the problem is more severe than his sloppy empiricism, it is
          at the purely logical level: if the process is fat tailed, then
          wealth is generated at the top, which means increases in wealth
          lead to increases of measured inequality. Within population
          wealth creation is a series of small probability bets. So it is
          natural that the pool of wealth (measured in years of spending,
          as Piketty does) increases with wealth. Consider 100 people, for
          a tail α that corresponds to our measurement, the additional
          wealth should come come 1 person, which the remaining bottom 50
          contributing nothing. It is not a zero sum gain: eliminate that
          person, and there will be almost no wealth increases.

          Taleb is starting from his own assumptions. He assumes not just
          that wealth comes from a small minority of the population, but
          that it comes from the wealthy. It isn’t scientists and
          engineers who create new methods that allow the total wealth to
          increase. It’s the people who are already rich, the rest
          contribute nothing.

          It seems to me this assumption should be tested. Find a way to
          collect data to show how true it is.

          The measured data favors Picketty. But Taleb makes a reasonable
          argument that maybe the measured data is wrong. If the breaks
          fall just right, the statistics could give us wrong conclusions.
          And with fat tails you can think it’s only a 5% chance the data
          is misleading you when in reality it’s some larger chance.

          The obvious opportunity here for Taleb is to demonstrate that
          this is the case, and publish it, and the people who want
          Picketty to be wrong will like him a lot. Just arguing that
          there is a possible way for the facts to be wrong is not nearly
          as good.

   155

          adam.smith 06.03.14 at 4:03 pm

          Just in case anyone is wondering about what J Thomas and TM are
          talking about: The exponential function’s relative rate of
          growth is constant. E.g. the standard exponential function
          exp(x) doubles at intervals of about .7—it’s 1 one at 0, 2 at
          ~.7, 4 at ~1.4, 8 at ~2.1. etc. While the interval changes, the
          general property is true for all functions in the exponential
          family. Of course that doesn’t mean that it doesn’t “shoot up”
          when you look at it. You can just define “shoot up” as a
          one-year growth of any given (absolute) value and then you get a
          point at which the exponential function “shoots up.”

   156

          TM 06.03.14 at 5:54 pm

          as 155: “Of course that doesn’t mean that it doesn’t “shoot up”
          when you look at it. You can just define “shoot up” as a
          one-year growth of any given (absolute) value and then you get a
          point at which the exponential function “shoots up.””

          The exponential function doesn’t “shoot up”, period. It grows
          smoothly by exactly the same fraction each unit of time. Each
          segment of the function looks exactly like any other segment, up
          to a scale factor in the x and y axes. Of course you are free to
          call a chair “beer-mug” by redefining the meaning of the word
          but that doesn’t mean that the rest of us will accept your
          redefinition of this or any other term. Maybe I am pedantic but
          I happen to think we need to be taking this stuff seriously. Al
          Bartlett was on to something when he famously remarked: “The
          greatest shortcoming of the human race is our inability to
          understand the exponential function.”

   157

          TM 06.03.14 at 5:56 pm

          Peter T 146: “Piketty’s r>g seems to me not so much a law of
          capitalism as a straightforward statement that, in any system
          that allows secondary claims on income, ordinarily the share of
          income going to those claims will rise until it hits a political
          or other limit. In other words, income shares between classes
          are politically determined.”

          This is precisely NOT what Piketty is saying.

   158

          TM 06.03.14 at 6:17 pm

          Val 147: “If you have a fairly large population and a fairly
          small rate of increase, and you plot the total population over
          time, I think what you will get is the kind of J curve I am
          talking about, with a long very gentle curve that ultimately
          shoots up sharply.”

          No. If the rate of increase remains constant – whether small or
          large doesn’t matter – you get an exponential growth curve. It
          is not J-shaped and does not “shoot up”. The shoot-up that is
          observed in human population growth is due to *accelerating*
          growth rates after 1750. As I pointed out, the growth rate
          increased from 0.2% to its peak value of 2% in 2 centuries. That
          is called *hyper-exponential* growth and that is what creates
          the (correct) impression of population suddenly shooting up. See
          http://www.slideshare.net/amenning/growth-in-a-finite-world-sust
          ainability-and-the-exponential-function, slides 86-91.

          Val 148: ” if the growth rate (birth rate minus death rate) is
          small compared to the population” etc.

          The (fractional) growth rate is a *percentage*. The size of the
          population doesn’t even matter, it’s a *relative* concept!

          JT 152: “the math is simple and the reality is complicated.”
          And the cliches grow on trees…
          The math is what it is and the reality is what it is. I’m not
          sure what you are trying to do. but what I would talk about is
          how human population actually changed over time, and what
          mathematical models are most appropriate to describe that
          empirical reality. In order to do that, understanding of the
          mathematical models is definitely an advantage.

   159

          Val 06.03.14 at 9:21 pm

          TM @ 158
          Oh well here I go damnit. I honestly don’t understand why you
          keep trying to prove me wrong. I looked at your link above and I
          looked at Wikipedia and various other places – thinking surely I
          must be wrong if he keeps going on about it – and I’m not. We
          are talking about the SAME THING! (Excuse capitals)

          The red curve on your slide
          http://www.slideshare.net/mobile/amenning/growth-in-a-finite-wor
          ld-sustainability-and-the-exponential-function and the green
          curve on Wikipedia
          http://en.wikipedia.org/wiki/Exponential_growth (labelled
          exponential growth) – that is the thing I am talking about.

          I have to finish reading Piketty and do some work on my PhD now.
          Please feel free to visit my blog if you wish to say anything
          further – as I’ve said before I don’t think it’s quite right to
          keep having a discussion here that is, at best, tangential to
          Henry’s post.

          Btw re what I take to be Henry’s main point: inequality, or
          inequity as we often say (ie labelling it as unfair) is very
          much considered ‘a problem’ now in public health (including my
          own thesis) particularly since Wilkinson and Pickett – by which
          process the very rich are now ‘a problem’ also, regardless of
          one’s politics. Though there has of course also been a backlash
          from the usual suspects.

   160

          adam.smith 06.03.14 at 9:40 pm

          TM—you’re just being pompous. I understand exponential functions
          just fine, as surely you could tell by reading my post. “Shoot
          up” is not a mathematical term, so indeed I can define it in any
          way that I find useful. I find it useful to use terms in a way
          that corresponds to their natural usage. I know some people who
          are decent at math like to pretend it’s counter-intuitive and
          doesn’t correspond to what people know. They’re doing a
          disservice to the general perception of maths.
          While the relative changes of the exponential function remain
          constant, its absolute changes grow, well, exponentially. That’s
          what people mean when they say the exponential function shoots
          up. Giving them unsolicited (and poorly executed, at that) math
          lectures in response is not a teaching opportunity but a dick
          move.

   161

          Ed Herdman 06.03.14 at 10:36 pm

          This discussion does reinforce for me that focusing exclusively
          on the exponential function wrt real populations is a mistake.
          It’s useful, but the common perception/takeaway – that mainly
          resource limitations restrict growth – seems too optimistic. I
          didn’t know about the 1Bn 28,000 years ago thing, which is
          interesting – were there other significant population crashes
          beyond the one ~70,000 years ago and the Black Death that helped
          retard population growth?

   162

          TM 06.03.14 at 10:50 pm

          Val, I’m not “trying to prove you wrong”. I just happen to be a
          mathematician who has studied this stuff and I know what I’m
          talking about. If you think you know better than me, why don’t
          you study the Math and then come back.

          AS, “shoots up” in most people’s usage of the term implies an
          abrupt change. There is no such abrupt change in an exponential
          growth process. If you disagree with that statement, why don’t
          you explain mathematically why you think it’s wrong instead of
          insulting others.

   163

          adam.smith 06.03.14 at 11:29 pm

          Tl:dr; When a term doesn’t have a clear mathematical definition,
          you can’t use math to show people they’re wrong about that term.

     AS, “shoots up” in most people’s usage of the term implies an abrupt
     change. If you disagree with that statement, why don’t you explain
     mathematically why you think it’s wrong.

          Sure. For any exponential function f(x)=a^bx I shall define the
          “shoot-up” point s as the point at which f(s)-f(s-1)=10a, in
          other words, at the point at which a one-unit change of x causes
          an increase of the function by 10 times its base.
          Now, you may disagree with that definition. Obviously 10 is an
          arbitrary value. But as I say above there is no mathematical
          definition of “shooting up,” so this definition is just as good
          as the one that you’re proposing and it does at least seem to
          correspond to what Val is seeing and talking about.

          In particular, you seem to be proposing something like
          f(s)/f(s-1)>>f(s-1)/f(s-2)). Which is fine and I’m not going to
          tell you that it’s wrong (again, no mathematical definition
          etc.), but it’s most certainly not the only way of describing
          the idea of a function shooting up. For example, it implies
          that, e.g., f(x)=x^2 doesn’t just not “shoot up,” it does the
          opposite (since for x>2, f(x)/f(x-1)<<f(x-1)/f(x-2)), which I'm
          pretty sure is not what most people would say looking at the
          right side of a parabola.

   164

          Ed Herdman 06.04.14 at 12:00 am

          Additionally, when a population – which up to some point has not
          been strongly following exponential growth patterns due to a
          combination of factors (limited growth potential, occasional
          crashes) – suddenly does start to more closely follow an
          exponential trajectory, it seems appropriate to use some
          language to describe that as an abrupt difference in the
          pattern.

          Even if you insist that the history of population change is
          strongly associated with consistent exponential growth, and that
          people are choosing a point to consider a break point with
          previous eras, I can just refer you to adam.smith’s comment.
          Even in this case, you should have inferred that in fact what
          signified the break is not to be found in the exponential
          pattern alone, or any mathematical model for that matter. It
          might be factors that have some interplay with individuals and
          the carrying capacity of the environment, or it might be
          emotional or social factors (all that 19th c. “fin de siecle”
          stuff about the breaks with tradition of modern life), or
          something else entirely. But nobody here, and none of these
          scenarios of what constitutes a break in a pattern, challenge
          the usefulness of talking about exponential functions – and the
          converse is true also.

          In short, “a break” represents a judgement of the historical
          record and what has actually happened, which may well be more
          useful than limiting the discussion to saying there is some
          arbitrary mathematical model we’d like to use and that it seems
          to fit. We are not striving merely for reducing the explanatory
          model here.

   165

          Val 06.04.14 at 2:10 am

          Thank you adam.smith @160 and everyone else who tried to get
          this conversation on to a sensible footing

          Like so many women, I have to say this is not the first time
          this sort of thing has happened to me, and sadly it probably
          won’t be the last

          https://www.byliner.com/read/rebecca-solnit/men-explain-things-t
          o-me

          but at least it seems it’s only a minority who do it here

   166

          Ed Herdman 06.04.14 at 3:36 am

          Thanks for that comment; made a few things click for me this
          time, for some reason.

          I actually saw this coming from the other direction as well –
          the narrow focus of the specialist leading to conceptual
          blinders. High attainment in a field doesn’t lead to broad
          vistas of the larger world, apparently.

          Us guys are also supposed to carry and obey the religion of pack
          battles, too. Want to win a battle over [DEL: political games
          :DEL] the correct conceptual approach? Snarl back harder!

          It seems to me that all these tendencies of the qualified
          professional can tie into each other.

   167

          Rakesh 06.04.14 at 7:02 am

          http://robertpaulwolff.blogspot.in/2014/06/guest-post-on-piketty
          -by-my-son.html

          Wolff however does not discuss Piketty’s ingenious use of
          returns on University endowments as a way of figuring out the
          kinds of returns the wealthiest may be making on the riskier
          assets that they are holding.

   168

          J Thomas 06.04.14 at 10:10 am

          Val, what made you a target was not so much being a woman, as
          appearing to be a woman who knew no math. Men who look that
          clueless can get that response too, maybe not quite as often.

          The hope is that a clear understanding of the simple math will
          help people think clearer. This might not be true, but
          mathematicians tend to believe it’s true enough to go out of
          their way to explain.

          Despite everything I want to make one last try at explaining
          this simple idea. Even though it doesn’t necessarily fit the
          reality in any simple way.

          The important thing about exponentials is that they do get big
          over time, faster than you’d expect. And a second thing is that
          how they look depends on how you graph them.

          The story about putting one grain of wheat on one square of a
          chessboard, and two on the next and four on the next etc shows
          that an exponential function can get completely out of hand.

          And this can be misleading. Imagine something is increasing at
          only 1 part in a thousand per year. Starting at 1, in 10,000
          years it will get up to around 20 thousand. And in 100,000 years
          it will reach more than 10^43. That looks like it’s jumping up!
          But after 100,000 years it’s still only increasing at 1 part in
          a thousand. It jumped up a whole lot over 90,000 years, but in
          one year it isn’t going up any faster than ever.

          It can look completely different just by how you graph it! And
          that can be very important. For example, Stephen J Gould built
          an entire career out of something he called “punctuated
          equilibrium”. He studied fossils, and he found that when he
          looked at large numbers of trilobite fossils and graphed their
          changes, each change came instantaneously. They didn’t go
          through a time when it was mixed between old and new, suddenly
          100% of them were the new kind. He considered this a tremendous
          anomaly and he spent a lot of effort trying to explain it.

          But a population geneticist could have told him — when a new
          trait is selected, other things equal its numbers will fit a
          logistic curve. With even a small selective advantage it’s
          pretty much over in 1000 generation. And on Gould’s timescale,
          1000 generations was practically instantaneous. The whole thing
          came from how he graphed it. A symmetric pair of J-curves turned
          into a symmetric pair of L-curves. And that math error fueled a
          tremendous amount of creativity.

          There is a useful lesson there if you can get past being
          condescended to.

   169

          Rakesh 06.04.14 at 2:42 pm

          Debraj Ray and Branko Milanovic argument. See links
          http://glineq.blogspot.fr/2014/06/nit-piketting-continued.html

   170

          Rakesh 06.04.14 at 2:58 pm

          It seems like a technical point on which Ray and Milanovic are
          focused, but Ray may be right to call attention to the
          assumption that all capital income is saved.

          If r were falling and capitalists wanted to maintain their
          consumption, capitalist consumption could increase as a
          percentage of capitalist income. Savings/investment would
          decline relatively. This would slow down the growth in the value
          of capital assets held by the non-working owning class. Of
          course to the extent that this capitalist class was sacrificing
          some accumulation of real capital assets to maintain or increase
          their own consumption, then the growth rate of the economy would
          also slow down, so inequality could increase.

   171

          Mike Furlan 06.04.14 at 5:29 pm

          RE:
          http://crookedtimber.org/2014/05/27/political-economy-is-politic
          al/#comment-532522

          Thanks for the reply J Thomas

          Let’s break it down further.

          One of Taleb’s arguments was, I believe if the income
          distribution is fat tailed, all other things being equal:

          If the population grows, measured inequality will increase.

          If the sample size is increased, measured inequality will
          increase.

          Is this correct?

   172

          J Thomas 06.04.14 at 8:57 pm

          One of Taleb’s arguments was, I believe if the income
          distribution is fat tailed, all other things being equal:

          If the population grows, measured inequality will increase.

          Actual inequality should increase. Measured inequality will
          probably increase, but the measured inequality will usually tend
          to understate the actual inequality because a lot of weight is
          in outliers, and if the samples are too small to reliably sample
          the pool of outliers then they’ll be off. Variability among
          samples should be higher than expected because of the outliers.

          If the sample size is increased, measured inequality will
          increase.

          On average, it ought to. The larger the sample, the more
          outliers you’ll get, and the better the chance you’ll get an
          extreme outlier. But it won’t happen every time.

   173

          Val 06.05.14 at 5:40 am

          J Thomas @ 168
          oh FFS. The point is I do understand the concept of exponential
          growth and I always did throughout the whole effing
          conversation. TM imagined that I didn’t. Please, that is enough.

   174

          Val 06.05.14 at 6:03 am

          J Thomas @ 168
          Ok, I’m fed up enough to do this now. I mentioned earlier in the
          thread that I had not formally studied mathematics since school,
          but I also mentioned that I had studied statistics as part of my
          public health studies. Just to clarify that, I did the Masters
          of Public Health course that was offered by a consortium of four
          Victorian Universities, Melbourne, Monash, Deakin and La Trobe.
          The first two are, I believe, ranked amongst the top 50
          universities in the world.

          As part of my MPH studies I was required to do biostatistics and
          epidemiology. I got 83% for biostatistics and 92% for
          epidemiology, and was awarded the prize for epidemiology in my
          year. Now you really cannot be that good at epidemiology without
          having a very good grasp of both logic and mathematical
          concepts. So next time you want to patronise someone for not
          being good at maths, just remember that you once, on a public
          blog, chose to patronise a women who was outstandingly talented
          in at least some branches of mathematics – and don’t do it!

   175

          J Thomas 06.05.14 at 8:48 am

          So next time you want to patronise someone for not being good at
          maths, just remember that you once, on a public blog, chose to
          patronise a women who was outstandingly talented in at least
          some branches of mathematics – and don’t do it!

          Val, what got at least two people to explain the exponential
          concept to you, was that you very strongly gave the impression
          that you had looked at a picture of an exponential function
          without understanding it. You never gave us a clue otherwise.

          If you’re a Freemason and you want other Masons to know you’re
          one, why not give them the secret handshake?

          When you act like you’re ignorant, people assume you’re
          ignorant. Your degrees aren’t tattooed onto your forehead.

   176

          Rakesh 06.05.14 at 3:31 pm

          Maybe Milanovic and others are winning this debate with Debraj
          Ray
          http://ruggedegalitarianism.wordpress.com/2014/06/04/why-is-r-g-
          so-significant-for-piketty/
          But I think it is important to question the assumption that
          capitalists are but ascetic social servants sacrificing their
          consumption for the sake of accumulation. Marx is famously
          thought to have written this, but his view is actually more
          complex, and may be unjustified anyway.

   177

          Rakesh 06.05.14 at 3:37 pm

          very interesting discussion of neglected aspects of Piketty’s
          book (I would include Piketty’s discussion of sovereign wealth
          funds, in particular his explanation for why the Saudis hold a
          disproportionate share of low yield US T-bills).

          http://rajivsethi.blogspot.com/2014/06/plots-and-subplots-in-pik
          ettys-capital.html

   Comments on this entry are closed.
     * Recent Comments
          + cassander on Occupy Central: Civil disobedience in Hong Kong
          + Plume on Occupy Central: Civil disobedience in Hong Kong
          + Layman on Occupy Central: Civil disobedience in Hong Kong
          + Layman on Occupy Central: Civil disobedience in Hong Kong
          + cassander on Occupy Central: Civil disobedience in Hong Kong
     * Search
       ____________________
     *

Contributors
          + Michael Bérubé ∞
          + Chris Bertram ∞
          + Harry Brighouse ∞
          + Daniel Davies ∞
          + Henry Farrell ∞
          + Maria Farrell ∞
          + Eszter Hargittai ∞
          + Niamh Hardiman ∞
          + Kieran Healy ∞
          + John Holbo ∞
          + Scott McLemee ∞
          + Jon Mandle ∞
          + Montagu Norman ∞
          + Tedra Osell ∞
          + John Quiggin ∞
          + Eric Rauchway ∞
          + Ingrid Robeyns ∞
          + Corey Robin ∞
          + Belle Waring ∞
          + Brian Weatherson ∞
       Click on the ∞ symbol next to a name for a list of all of that
       author's posts.
     *

Book Events
          + Francis Spufford / Red Plenty
          + David Graeber / Debt: The First 5,000 Years
          + George Scialabba / What Are Intellectuals Good For?
          + Steven Teles / The Rise of the Conservative Legal Movement
          + Charles Stross / Various
          + China Miéville / Iron Council
          + Chris Mooney / The Republican War on Science
          + Dani Rodrik / One Economics, Many Recipes
          + Doug Henwood / After the New Economy
          + Levitt & Dubner / Freakonomics
          + Sheri Berman / The Primacy of Politics
          + Susanna Clarke / Jonathan Strange & Mr Norrell
          + Yochai Benkler / The Wealth of Networks
     *

Lumber Room
          + 11D
          + 3 Quarks Daily
          + A Fistful of Euros
          + Atrios
          + Balkinization
          + Best of Both Worlds
          + Bleeding Heart Libertarians
          + Blood and Treasure
          + Brad DeLong
          + Cosma Shalizi
          + Corey Robin
          + Critical Mass
          + Daily Kos
          + Daily Nous
          + Daniel Drezner
          + Digby
          + Ed Felten
          + Eric Schliesser
          + Edge of the American West
          + Feminist Philosophers
          + Firedoglake
          + Glenn Greenwald
          + The Inverse Square
          + Jacobin
          + Jim Henley
          + Joshua Marshall
          + Juan Cole
          + Kevin Drum
          + Lawrence Solum
          + Lawyers, Guns and Money
          + Leiter Reports
          + Making Light
          + Marc Lynch
          + Marginal Revolution
          + Mark Thoma
          + Maud Newton
          + Michael Froomkin
          + Miriam Burstein
          + Naked Capitalism
          + New Left Project
          + The New Inquiry
          + Pharyngula
          + Political Theory Daily Review
          + Politics, Theory and Photography
          + Russell Arben Fox
          + Slugger O’Toole
          + Sociological Images
          + Steven Johnson
          + Steven Poole
          + Talk Left
          + Tapped
          + The Virtual Stoa
          + Tim Lambert
          + Timothy Burke
          + Uncertain Principles
          + Yorkshire Ranter
