   #publisher

   [s?19=990&14=0&6=274510411&7=1678561&25=0&18=0.9215966322184124]

   MENU
     * Subscribe
     * Newsletters
     * Events
     * Webinars
     * Reports
     * Magazine
     * Jobs
     * Advertise
     * Awards Programs
     * About
     * More

   Government Technology is the award-winning authority on the smart and
   sustainable use of technology for solving government's business issues.
   [small_round_facebook_icon.png] [small_round_twitter_icon.png]
   [small_round_googleplus_icon.png] [small_round_youtube_icon.png]
   [small_round_linkedin_icon.png?10] [small_round_pinterest_icon.png?10]
   [new_gt_rss_icon.png]

Magazine / Subscribe / Newsletters / News / Events / Webinars / Reports /
Advertise / Center for Digital Government / About / More

   Close
    TECHNOLOGY
     * Applications
     * Computing Platforms
     * Web & Social
     * Network
     * Data
     * Security
     * Gear

    JURISDICTION
     * State
     * Local
     * Federal
     * Education

    DOMAINS/ PRACTICE AREAS
     * Budget and Finance
     * Health and Human Services
     * Justice and Public Safety
     * Transportation
     * Education

   Crowdsourcing Rodrigo Davies

Crowdsourcing Offers Gov Funding Option for Civic Tech

Is the FCC Dragging Its Feet on Net Neutrality?

   Windows 2003

Are You Prepared to Migrate Off Windows Server 2003?

   Illustration depicting the ends of many illuminated fiber optic strands
   against abstract blue background.

Will the FCC Vacate State Broadband Restrictions?

   2013 Boston Marathon Bombing

Social Media: Big Lessons from the Boston Marathon Bombing

   Jennifer Pahlka

7 Code for America Cities Named for 2015

   Close

EDITORIAL

     * Masthead
     * Submit News

COLUMNS

     * Lohrmann

DIGITAL MEDIA

     * Newsletters
     * Videos
     * Photos

RESOURCES

     * Public Sector Jobs
     * Grants

OUR NETWORK

     * Emergency Management
     * Public CIO
     * Governing
     * FutureStructure
     * Center for Digital Government
     * Center for Digital Education

COMMUNITIES

     * GovTech Exchange
     * Digital Communities

PROGRAMS

     * Surveys and Awards

INDUSTRY

     * Industry Insider
     * Navigator
     * Media Kits
     * Labs

COMPANY

     * About Us
     * Contact Us
     * Press
     * Privacy
     * Jobs

State

Should Maryland Paratransit Customers Use Uber? (Opinion)

Government should explore the impact disruptive companies could have in the
public sector -- citizens deserve it.

by Mike Powell, Chief Innovation Officer, Maryland / September 10, 2014

   Just a few years ago, if you needed a ride and couldn’t use mass
   transit, you hailed a cab. If you wanted to know what your home was
   worth, you hired an appraiser, or had a realtor run some comps. And if
   you wanted to avoid traffic, you turned on the car radio, waited 10
   minutes, and prayed that “traffic on the eights” would mention your
   route (or, hopefully, not mention it).

   However, in 2014, consumers have much better options. When we need a
   ride, many of us use a ridesharing service like Uber or Lyft. If you
   want to know what your home is worth (or your neighbor’s home is
   worth), Zillow or Trulia can tell you in seconds. And as I drive home
   tonight, Waze will tell me the best route, and alert me to traffic
   issues in real time based on 10,000 other “Wazers” in the Baltimore
   area right now.
   Uber, Zillow, and Waze are just a few examples of the many disruptive
   companies that are making our personal lives a little easier. But can
   they also help government improve service and help reduce cost? I think
   they can.

   My state of Maryland, like many states, provides paratransit “mobility”
   service for citizens with disabilities that prevent them from taking
   fixed-route mass transit (like light rail). After an intensive
   application process, if you need a ride, you need to schedule your trip
   via a call center (with an average five-minute hold time) by 5 p.m. the
   day before the trip. Ninety-one percent of the time, your driver shows
   up within a 30-minute window. The average trip is around eight miles
   and 36 minutes and costs roughly $54. The total cost of our mobility
   program is around $90 million in 2014, an increase of more than 50
   percent in the past five years.

   Compare the above scenario to Uber. With Uber, you can request your
   ride when you need it, and you don’t need to call and wait. They’re
   incentivized to pick you up promptly, and to provide good customer
   service, since without you, they’re not making any money. A quick check
   shows UberX will do a 10-mile, 35-minute trip for under $25, less than
   half the average cost of our mobility service.

   To be clear, I’m not shilling for Uber, and I know there are other good
   ridesharing services, like Lyft, that are comparable. And I also know
   that private ridesharing may not be a viable alternative for all of our
   mobility customers. But Uber, Lyft and others seem to have a
   business model that suggests that there are more
   customer-friendly, efficient and cost-effective ways to transport our
   mobility customers.

   Uber is just one example of a company that could help government reduce
   cost and improve service.

RELATED

     * Lyft Acquires Hitch to Expand Carpool Service
     * San Francisco Taxi Owners, Cabbies Join Forces Against Rideshare
       Companies
     * Ride Services Decimate San Francisco Taxi Industry's Business
     * Gov. Corbett Expresses His Support for Lyft, Uber in Pennsylvania
     * California Legislature Approves New Insurance Requirements for
       Ride-Sharing Companies
     * Ride-Sharing Makes Friends in Some Jurisdictions, Enemies in Others

   Maryland has hundreds of cameras on our highways so that we can monitor
   traffic and respond to problems. Let me be blunt: I don’t think the
   data collected from these cameras is any better (or more timely) than
   the crowdsourced data collected by Waze, specifically, by the “Wazers”
   in cars 100 yards ahead of me on the beltway that just came to a stop.
   And Zillow says they can estimate the value of a home within 5 percent,
   50 percent of the time. That’s not perfect, but is it worse than our
   own manual assessments, conducted at considerable expense? (Yes,
   I assume our manual assessments are part of Zillow’s algorithm.
   I’d love to test their estimates, excluding the assessment data,
   against our assessments.)
   These disruptive, innovative companies have had an extraordinary impact
   on our daily lives, and I think government owes it to the citizens we
   serve to explore whether they could have a similar impact in the public
   sector.

   Michael Powell, chief innovation officer, Maryland Mike Powell is the
   chief innovation officer of Maryland. The views expressed in this op-ed
   solely those of the author and do not necessarily reflect those of the
   state of Maryland.

RELATED STORIES

Lyft Acquires Hitch to Expand Carpool Service

San Francisco Taxi Owners, Cabbies Join Forces Against Rideshare Companies

   Subscription Banner

Free subscription to Government Technology

From Our Sister Sites

    1.
    2.
    3.
    4.

   Governing

States Confront Past and Present Forced Sterilization

   States -- including California, where female prisoners were
   involuntarily sterilized as late as 2013 -- are figuring out how to
   compensate the victims.
   Fight against Ebola in Guinea
   Emergency Management

Ebola Is a Threat to Global Security, Says Obama

   At a United Nations meeting, leaders said the world is not doing enough
   to contain the Ebola outbreak in West Africa and avert a “humanitarian
   catastrophe.”
   Center For Digital Education

Robotics and Computing Help Make Sense of Math

   High school students in California find that hands-on learning makes
   abstract concepts easier to understand.
   Future Structure

Megacities Project Targets Carbon Emissions

   Cities are serving as bellwethers of society's carbon emission trends.
   While many are experiencing growth in emissions, others are leading the
   charge to reduce them.
   [gt-subscribe-box.png]
   ____________________ [gt-newsletter-go-button.png]-Submit
   Papers

Popular

     * Which States Have the Best Technology?
     * Procurement: What if We're Doing it Wrong?
     * California Gov. Brown Signs Bill to Urge More Drivers Into
       Eco-Friendly Vehicles
     * Michigan Taps Private Sector to Help Reform Procurement System
     * How Digital Are States in 2014?
     * Texas Gets to Keep Taxing Internet Access, for Now
     * More News

   Tweets about "@govtechnews OR #utdgs OR #ordgs OR #njdgs"

From Our Sister Sites

    1.
    2.
    3.
    4.

   Governing

States Confront Past and Present Forced Sterilization

   States -- including California, where female prisoners were
   involuntarily sterilized as late as 2013 -- are figuring out how to
   compensate the victims.
   Fight against Ebola in Guinea
   Emergency Management

Ebola Is a Threat to Global Security, Says Obama

   At a United Nations meeting, leaders said the world is not doing enough
   to contain the Ebola outbreak in West Africa and avert a “humanitarian
   catastrophe.”
   Center For Digital Education

Robotics and Computing Help Make Sense of Math

   High school students in California find that hands-on learning makes
   abstract concepts easier to understand.
   Future Structure

Megacities Project Targets Carbon Emissions

   Cities are serving as bellwethers of society's carbon emission trends.
   While many are experiencing growth in emissions, others are leading the
   charge to reduce them.
   Filter By Topic
   All
     *

ALL
     *
        TECHNOLOGY
          + Applications
          + Computing Platforms
          + Web & Social
          + Network
          + Data
          + Security
          + Gear
     *
        JURISDICTION
          + State
          + Local
          + Federal
          + Education
     *
        DOMAINS/ PRACTICE AREAS
          + Budget and Finance
          + Health and Human Services
          + Justice and Public Safety
          + Transportation
          + Education

      Videos      Photos
   Load More
