
   Skip to Main Content

   Accessibility Skip Site Wide Navigation Skip to Content City Seal |
   Home City of San Diego | Home
     * Home
     * Contact the City

     * Business
     * City Hall
     * Community
     * Departments
     * Information
     * Leisure
     * Services A-Z
     * Visiting

   ____________ Search

   Personnel Department

Employment Opportunities

     * Employment
       Opportunities Home
     * About
       Personnel
     * Current
       City Jobs
     * General
       Information
     * Employee
       Benefits
     * Frequently Asked
       Questions

   Employment Opportunities Home  •  Current City Jobs •  Open Job
   Opportunities

Current City Jobs

     * Current City Jobs Home
     * Applicant Login & Registration
     * Open Job Opportunities
     * Promotional Opportunities
     * Transfer Opportunities (PDF)
     * Job Descriptions
     * Job Interest Cards

     * First Time User Guide
     * Attaching Documents

Open Job Opportunities

   Sunday, September 28, 2014 Powered by NEOGOV

   CITY OF SAN DIEGO

   OPEN JOB OPPORTUNITIES

   The City of San Diego only accepts online applications.  To apply
   online, click the Position Title of any open job opportunity below and
   then click the "Apply" link.
   It is important that your application is complete and thourough -
   please include all requested education, experience, attachments, and
   other information. Resumes and other supporting documents can be
   provided at the time of application; however, resumes will not be
   accepted in lieu of an application. Incomplete applications are subject
   to rejection. Notifications to applicants are sent electronically to
   the email address you provide.

   IMPORTANT:
     * DO NOT share your user account as it WILL jeopardize your status in
       the recruitment process for any position for which you apply.
     * You MUST SAVE your online application at least once every hour,
       even if you are actively entering information. If you fail to save
       your application, your process will be timed out and you will lose
       information not previously saved.
     * You MUST KEEP your Account (e.g., name, address, email and phone)
       accurate to ensure notifications and employment opportunities are
       not missed.

   Online applications are stored on a secure site. Only authorized
   employees and hiring authorities have access to the information
   submitted.
   Hide Search Criteria

   Search Criteria

   All Categories are automatically selected. To change the results,
   deselect and reselect the categories by using the Clear All/Select All
   buttons or by clicking on the check boxes. To reset the search
   criteria, click 'Clear Search' at the bottom of this box.
   Select Category Select All Categories   Clear All Categories
   [X] 911 Telecommunications (3) [X] Airports (1) [X] Arts (1)
   [X] Automotive (1) [X] Building & Grounds Cleaning and Maintenance (2)
   [X] Building & Safety (1)
   [X] Building Maintenance (2) [X] Code Enforcement (3) [X] Customer
   Service (2)
   [X] Dispatch (3) [X] Drivers (1) [X] EMS (3)
   [X] Engineering (4) [X] Fire & EMS (3) [X] Fleet Services (1)
   [X] Green-Collar/Environmental (1) [X] Grounds & Landscaping (2) [X]
   Investigative (5)
   [X] IT and Computers (2) [X] Law Enforcement (7) [X] Legal (1)
   [X] Maintenance (4) [X] Management (1) [X] Miscellaneous (1)
   [X] Parks and Recreation (7) [X] Planning and Development (2) [X]
   Public Relations (1)
   [X] Public Safety (8) [X] Recreation (4) [X] Safety (5)
   [X] Trades (1) [X] Utilities (1) [X] Vehicle Maintenance (1)
   [X] Wastewater (1)

   Search
   Enter keywords (optional): ____________________ Explain this
   Enter keywords that you wish to appear anywhere in the job description.
   Hint: Try searching for related words, such as "Accountant" or
   "Accounting Specialist", or simply "Account*" (Account followed by an
   asterisk), to find jobs matching both descriptions.

   Apply Search or Clear Search

      Print this page    Print this page Print this page
   31 records found.
   Page # 1_ of 2 go First Page Previous Page Next Page Last Page
     Position   Sort Descending   Emp. Type   Sort Ascending   Salary
   Sort Ascending   Closing Date   Sort Ascending
   NEW! Aquatics Technician I - T10628-201409 Varies by Position $18.99 -
   $22.64 Hourly 10/08/14
   NEW! Area Manager II - T10634-201409 Varies by Position $25.36 - $30.73
   Hourly 10/08/14
   NEW! Assistant Engineer - Traffic - T10630-20... Varies by Position
   $27.82 - $33.52 Hourly 10/08/14
   NEW! Boat Operator - T10611-201409 Varies by Position $20.91 - $24.95
   Hourly 10/08/14
   NEW! Code Compliance Officer - T10635-201409 Varies by Position $17.90
   - $21.54 Hourly 10/08/14
   Collections Manager - T10613-201409 Varies by Position $32.10 - $38.89
   Hourly 09/29/14
   Dispatcher I - T10142-201408 Varies by Position $16.36 - $19.72 Hourly
   09/29/14
   Dispatcher II - T10625-201408 Varies by Position $18.00 - $21.72 Hourly
   09/29/14
   Golf Starter - T10556-201406 Varies by Position $14.39 - $17.34 Hourly
   10/07/14
   NEW! Grounds Maintenance Manager - T10163-201... Varies by Position
   $24.74 - $29.98 Hourly 10/08/14
   Horticulturist - T10618-201409 Varies by Position $25.51 - $30.84
   Hourly 10/08/14
   Information Systems Analyst II - T10622-... Varies by Position $25.99 -
   $31.41 Hourly 10/08/14
   Information Systems Analyst III - T10614... Varies by Position $28.54 -
   $34.50 Hourly 10/08/14
   Lifeguard I - T10532-201406 Varies by Position $16.23 - $19.50 Hourly
   12/03/14
   Master Fleet Technician - T10637-201409 Varies by Position $22.94 -
   $27.48 Hourly 10/01/14
   NEW! Pesticide Applicator - T10636-201409 Varies by Position $18.97 -
   $22.62 Hourly 10/08/14
   Plan Review Specialist I - T10606-201409 Varies by Position $19.56 -
   $23.59 Hourly 10/01/14
   Planning Director, Planning Department -... Unclassified Depends on
   Qualifications 10/03/14
   Police Dispatcher - T10143-201408 Varies by Position $21.75 - $26.22
   Hourly 09/29/14
   Police Officer I - T10333 Permanent, Full Time $23.68 - $28.59 Hourly
   Continuous
   Police Officer II - T10334 Permanent, Full Time $30.21 - $36.51 Hourly
   Continuous
   Police Recruit - T10289 Permanent, Full Time $4,039.00/Month Continuous
   Police Service Officer II (Indochinese S... Varies by Position $18.84 -
   $22.66 Hourly 10/06/14
   Public Art Program Administrator - T1062... Varies by Position $32.10 -
   $38.89 Hourly 09/29/14
   Recreation Leader I - T10470-201408 Varies by Position $11.98 - $14.44
   Hourly 09/30/14
   Page # 1_ of 2 go First Page Previous Page Next Page Last Page

   | Employment Opportunities Home | About Personnel | Current City Jobs |

   | General Information | Employee Benefits | Frequently Asked Questions
   |

   | City of San Diego Home | Business | City Hall | Community |
   Departments | Information | Leisure | Services A-Z | Visiting | Top of
   Page |

   | Search | Site Map | Contact the City | Privacy Notice | Disclaimers |
   Accessibility |

   Copyrighted Â© 2002-2011 City of San Diego. All rights reserved.
