   #The Verge - All Posts

The Verge

   Longform Video Reviews Tech Science Culture Design Business US & World
   Forums
   Share: Facebook Twitter Google+
     * Apps
     * Business
     * Tech
     * Exclusive
     * Report

Meet Swarm: Foursquare's ambitious plan to split its app in two

   To take on Yelp, Foursquare is moving beyond the check-in

   By Verge Staff on May 1, 2014 10:01 am 148Comments

   By Ben Popper and Ellis Hamburger.

   Foursquare CEO Dennis Crowley has spent the last year trying to
   convince the world that Foursquare isn't what it used to be. The
   company emerged back in 2009 with a novel app that let people “check
   in” to a location. That vision, and the local information that
   followed, propelled it to amass tens of millions of users, hundreds of
   millions in funding, and billions upon billions of data points from
   people who used Foursquare to check in around the globe. The problem
   was, in 2014, that story no longer worked for Foursquare. In fact, it
   was holding the company back.

   “Listen, the point of the company, this whole thing, was never to build
   an awesome check-in button,” says Crowley. “That’s not the thing we got
   out of bed and said, that we wanted to build the most awesome check-in
   button in the world!” Back in 2009 declaring your location was a
   necessity, because phones didn’t have the power to reliably pinpoint a
   user, and Foursquare didn’t have much data on what venues were nearby.
   By 2014, however, both the technology and the data have finally come of
   age.

   With the check-in front and center, however, Foursquare was still
   struggling to enter the mainstream and saw its user growth overtaken by
   younger startups. The company had created a new paradigm around
   location sharing, but that activity was never going to be as popular as
   snapping a selfie, sharing a link, or firing off a tweet.

   So Crowley decided it was time to do something radical. “What if we
   don't need people to check in anymore?,” he asked. “What does a version
   of Foursquare look like that doesn't beg you to check in as soon as you
   open it up?” Over the last six months, the team has been hard at work
   on a complete reinvention of the company. In the end they decided that,
   in order to save Foursquare, they would have to break it half,
   splitting the iconic service into two separate apps.

   Today, the company is announcing the first fruit of this labor, a brand
   new app called Swarm that will exist alongside the current Foursquare
   app. Swarm will be a social heat map, helping users find friends nearby
   and check in to share their location. A completely rewritten Foursquare
   app will launch in a month or so. The new Foursquare will ditch the
   check-in and focus solely on exploration and discovery, finally
   positioning itself as a true Yelp-killer in the battle to provide great
   local search.

Starting from scratch

   The next era of Foursquare began in a room aptly nicknamed "Don’t Stop
   Believing." Crowley gathered his top brass. They had spent the last
   couple years shaping and reshaping the mobile app, moving buttons
   around, and changing language, but it was time for a bigger
   transformation. Starting in November of 2013, Crowley instructed them
   to break the app down into its basic parts, little Lego blocks that
   represented everything it could do. Then they would rebuild Foursquare
   from scratch.
   ""Listen, the point of the company, this whole thing, was never to
   build an awesome check-in button.""

   One block was Pilgrim, the company’s cutting-edge tech for guessing a
   user’s location. Another was the 60 million venues and points of
   interest the company gathered across the world in one of the largest
   databases of its kind. The team came up with dozens of different ideas
   for what the service should look like in 2014, but every answer had one
   thing in common: they all said Foursquare needed to grow out of its
   one-app approach.

   Foursquare's new direction wasn't based on gut instinct. It relied on
   some pretty scary data the company gathered about how people had been
   using its app — or how they hadn't been using it. "We looked at the
   session analysis and saw that only 1 in 20 sessions had both social and
   discovery," says Noah Weiss, Foursquare’s vice president of product
   management. In other words, just 5 percent of Foursquare’s users were
   opening it to find friends and find a restaurant. "Why not actually
   just split those apart, because 19 out of 20 times, tapping on one icon
   or the other, you have satisfied your need completely," says Weiss.

   "The more we played with that idea the more we realized that there was
   a ton we wanted to do on both sides that we can’t do if they are
   married together," says Jon Steinback, Foursquare’s VP of product
   experience. "It’s like we were in a three legged race and each side was
   slowing the other side down." Weiss is a bit more cynical. "We had been
   taking on a little bit of a mission impossible," he says, "trying to
   make a single-purpose mobile app that actually had two purposes."
   Crowley

The great unbundling

   Foursquare’s decision can be seen as part of a larger trend in the
   mobile space to unbundle complex web properties into a suite of
   connected apps, rather than trying to jam numerous features into a
   single package. Foursquare’s new divide might actually make even more
   sense than the unbundling strategies Facebook, Google, and Twitter have
   employed, since Foursquare’s two sides seemed to be holding each other
   back.
   ""It’s like we were in a three legged race and each side was slowing
   the other side down.""

   "I think mobile forced this fundamental switch. We were born in mobile
   but we were born in this idea that each mobile app was kind of like a
   web property bundled up for mobile," says Steinback. "And as mobile
   usage has broadened and evolved you get individual experiences instead.
   You open an app to do a specific task and not as a gateway to a large
   complicated experience."

   Having the check-in button as the main interface every time users
   opened the app created a noticeable hurdle for engagement. "Imagine if
   you opened up YouTube and the first thing it asked you to do was create
   a video. That would scare off a lot of people," says Bijan Sabet, one
   of Foursquare’s early investors and a current board member. "Just like
   you don’t need to tweet to enjoy Twitter, splitting the app in two will
   help make it clear to a big audience that you don’t need to check in to
   find value in Foursquare."

   During months of testing, the company found that unbundling the two
   halves of Foursquare made each experience more focused and efficient.
   Sessions were shorter, but more frequent. And using some simple hooks
   in iOS and Android, Foursquare can shuttle users back and forth between
   the two apps with ease, much as Facebook does with its main app and its
   Messenger app. "By simplifying a lot of the story, and having an app
   that's dedicated to search and discovery I think it's going to be very
   clear to people that the search and discovery tools that we built are
   some of the best in class," says Crowley.
   Swarm_group

Making serendipity less creepy

   Swarm should work very well for seeing who’s around to get one more
   drink at 1 AM, but Foursquare may have been beaten to the punch by an
   old rival: Facebook. Two weeks before Foursquare announced its big
   split, Facebook debuted "Nearby Friends," a feature two years in the
   making which, for better or worse, looks and acts a whole lot like
   Foursquare’s Swarm. Crowley posted on Tumblr the following day that
   he’s not concerned, for the same reason he wasn’t concerned when
   Facebook first tried check-ins back in 2010. Your Facebook friend list
   is far too big for people to be comfortable sharing intimate data like
   their location, Crowley says.

   "Passive location-sharing in a way that people actually want"A number
   of similar apps like Highlight, Sonar, and Banjo, which helped you
   track down friends and interesting strangers, were so broad that they
   bombed with the mainstream. Both Nearby and Swarm try to ease user’s
   concerns by providing a sense of which friends are close by without
   giving away too much detail. "[We’re] using passive location-sharing in
   a way that people actually want," says Weiss. "They don’t want to be
   precision-pointed [latitude and longitude] on a map so somebody can go
   find them in the middle of a park. What they want is for friends to be
   ambiently aware of where they are, so when they got out of the train in
   Williamsburg, they can say, ‘Who are my 10 friends in Williamsburg?’"

   Most importantly, while you can check in with Swarm, it also passively
   notes your general location even if you don’t open the app. So if you
   come out of a subway station and look at your phone, Foursquare will
   understand that you’re in a new neighborhood and update your status
   accordingly. This might still seem creepy for some people, but in that
   sense Foursquare may have one big advantage over Facebook when it comes
   to ambient location sharing. People who download Swarm are making an
   explicit decision to provide this kind of data to a specific set of
   friends.
   D9c5o-hbnd-3000x3000

Dollars and cents

   Swarm is the big story today, but it’s really the changes that will
   occur within the classic Foursquare app that could grow the company in
   a massive way. It's a distinction signified by the apps’ internal
   nicknames: Batman for Foursquare, Robin for Swarm. It’s a tacit
   acknowledgement by Foursquare that checking in may never appeal to more
   than a niche audience. Local search, however, is a mainstream activity
   that anyone with a smartphone is going to want. "The thinking is, if we
   start to remove a lot of the friction, we make the tools much more
   accessible to people, that’s the path by which you get from where we
   are now to 75, 100 million, more than 100 million users," says Crowley.
   Photo-apr-29_-3-13-31-pm_iphone5s_silver_portrait

   Back in 2012, Foursquare struggled to raise new funding at an
   attractive valuation. First it took on debt, then raised fresh capital,
   but at a lower valuation than its earlier rounds. The company’s net
   worth, in other words, was shrinking, and one of its two co-founders,
   Naveen Selvadurai, departed. The core issue was that its user growth
   had slowed considerably and fallen behind its peers in the world of
   mobile social networks.

   But if these changes help Foursquare finally hit those bigger user
   numbers, its investors believe it will be extremely valuable. The
   company has been inserting ads into its app for a little over two years
   now, and that taught it some critical details. "We’ve learned a lot,"
   says Ben Horowitz, one of the company’s investors and board members.
   "And the results have been quite good in that Foursquare already
   monetizes better than almost any social experience." When it comes to
   advertising, Foursquare can make far more per user than public
   companies like Facebook or Twitter. "That is a powerful fact going
   forward and helps them keep a focus ... they know they can build an
   extremely valuable company without having anything like a billion
   users."

   The company’s head of revenue, Steven Rosenblatt, knows better than
   most about earnings potential. His previous job was at Apple, one of
   the most profitable companies on the planet, where he helped launch its
   mobile ad product. He was inspired to leave for Foursquare, he says,
   because he thought it was simply the best way to do mobile advertising.
   "Everybody else is using geo-fencing, which is nice, but gets things
   wrong about two thirds of the time," he says. "We have location
   accuracy that is better than anything I’ve seen during my 16 years in
   this business, and that’s why advertisers are willing to pay." Sources
   familiar with the situation say Foursquare has grown its revenue from
   around $2 million in 2012 to $12 million in 2013, and is on pace to
   make between $40 to $50 million this year.
   ""They can build an extremely valuable company without anything like a
   billion users.""

   The best model for where the company hopes to be a few years from now
   is probably Yelp, and in fact people around the Foursquare office refer
   to its new discovery app as a "Yelp-killer". Built on its
   user-generated reviews of local shops and restaurants, Yelp is now a
   public company valued at $4.6 billion. Foursquare thinks it has the
   data and technology to beat Yelp, but people just haven’t realized it
   because they were scared off by the check-ins, badges, and social
   features that Foursquare originally pitched.

   "If we all went to Google right now, or went to Yelp right now, we'd
   all get the same results, and that seems really really broken to me,"
   says Crowley. "Foursquare should understand the neighborhoods I've
   spent a lot of time in, and the restaurants that I went to once but
   never went back to." In that sense Foursquare hopes to provide not just
   the best local search, but the kind of predictive intelligence that
   comes with a digital assistant like Microsoft’s Cortana, Apple’s Siri,
   or Google Now. In Crowley’s future, your phone doesn’t just tell you
   what’s nearby — it tells you what you’ll enjoy based on everywhere you
   (and your friends) have ever been.
   Swarm_bee_logo

Check please

   But how can Foursquare personalize its users' results if they are no
   longer collecting check-ins, the foundation of Foursquare’s
   recommendation engine? Crowley smiles and says something a bit
   shocking. He no longer needs check-ins, the meat and potatoes of
   Foursquare’s entire business and data collection engine for the last
   five years.

   Not only has Foursquare collected 6 billion check-ins, he says, but it
   has collected 6 billion signals to help it map out over 60 million
   places around the world. Each place is a shape that looks like a hot
   zone of check-ins — of times when people have said "I’m here."
   Foursquare’s "Pilgrim" location-guessing engine factors in everything
   from your GPS signal, to cell tower triangulation, to the number of
   bars you have, to the Wi-Fi networks nearby, in order to create these
   virtual shapes.

   Now that it has this data, Foursquare can make a very accurate guess at
   where you are when you stop moving, even without a check-in, a
   technology it hopes will allow it to keep its database of places fresh
   and accurate. Foursquare calls these implicit check-ins "p-check-ins,"
   or Neighborhood Sharing. Take your phone into four or five different
   Japanese restaurants over the course of six months and without a single
   check-in Foursquare will learn that you like Japanese food and start
   making recommendations for you based on that data.
   ""We think of Foursquare as a technology that’s enabling these
   superpowers.""

   "This ability to be contextually aware, to have a general sense of the
   things that I like based upon where the device has been, and the things
   that I might like based upon where I’ve been in the past or where my
   friends have been, that’s a really magical ability." argues Crowley.

   Tiny micro-facts are part of what could make Foursquare bigger than a
   recommendations service. "We don’t want you to read longform reviews.
   We don’t even have longform reviews. What we do have is many millions
   of people telling us tens of millions of times what is this place known
   for? What is the vibe of this place?" says Weiss. "How can we surface
   that back to you in a really authoritative way so you can scan that at
   a glance?"

   In this way Crowley and his team don’t really think of Foursquare as a
   Yelp competitor. They think of it as something much bigger — a means to
   finding interesting things around you anywhere in the world. Crowley
   has for years promised a service that buzzed you when something cool is
   nearby, and he might finally be in a position to offer it.

   "We think of Foursquare as a technology that’s enabling these
   superpowers… to see around corners and through walls, it’s like I want
   to find the best stuff that exists within you know, 100 yards, 5 miles,
   10 miles of me," says Crowley. "I walked into a restaurant and it told
   me what to order. I walked into a neighborhood and it told me three
   places to go to. My plane landed in a city I’ve never been to and it’s
   telling me that two friends are nearby. That’s stuff that we’re doing
   now, and I think what people will get is that it’s very clearly the
   future."

   Additional reporting by Chaim Gartenberg and Tyler Gold.

More from The Verge

The Magic Capital of the World

Welcome to Colon, Magic Capital of the World

   By Kyle Chayka

Oculus' new prototype is where VR should be right now

   By Adi Robertson

How the hell did Vizio make a $999 4K TV?

   By Nilay Patel
   Back to top ^
   ____________________
   The Sections
     * Longform
     * Video
     * Reviews
     * Tech
     * Science
     * Culture
     * Design
     * Business
     * US & World

   The Basics
     * Site Status
     * About
     * Contact
     * Tip Us
     * Forums
     * Jobs

   The Elsewhere
     * Facebook
     * Twitter
     * Google+
     * Tumblr
     * YouTube
     * Instagram
     * Subscribe

   Ethics Statement - Community Guidelines
   Terms of Use - Privacy Policy
   v2.0, September 2, 2014
   All Systems Operational Check out our status page for more details.

   © 2014 Vox Media, Inc. All rights reserved.

   X
   Eater The Verge Polygon SB Nation
   Log In Sign Up
   T F G
   Y O
   ____________________
   Open ID Log in

   ____________________

   ____________________ forgot?

   [ ] Remember me? Log in
   Log In Sign Up
   T F G
   Y O
   ____________________
   Open ID Log in

   ____________________

   ____________________

   ____________________

   [ ] Yes, I would like to receive a daily newsletter from The Verge and
   occasional dedicated newsletters from sponsors and/or partners.

   Continue

Forgot password?

   We'll email you a reset link.

   If you signed up using a 3rd party account like Facebook or Twitter,
   please login with it instead.
   ____________________
   Submit

Forgot password?

   Try another email?

Almost done,

   By becoming a registered user, you are also agreeing to our Terms and
   confirming that you have read our Privacy Policy.
   Register
   Spinner.vc97ec6e

Authenticating

Great!

   Choose an available username to complete sign up.

   ____________________

   Sign Up

   In order to provide our users with a better overall experience, we ask
   for more information from Facebook when using it to login so that we
   can learn more about our audience and provide you with the best
   possible experience. We do not store specific user data and the sharing
   of it is not required to login with Facebook.
   (*) Yes, share my data ( ) Please don't share my data
   Submit

   tracking_pixel_5345_tracker Quantcast
   [audmeasure.gif?liveconclientID=5497559777280&PageID=650423876&EventTyp
   e=view]
